### ISSUE TITLE
configuration.yaml error for sonoff username and password

### ISSUE THREAD

**Issue by jmodlinne** [AlexxIT/SonoffLAN#100]
Good Day

I am getting the following error when putting my username credentials in the configuration.yaml file

Configuration invalid
Component error: sonoff - No module named 'Crypto.Util.Padding'

anyone know how to fix?

**Comment by AlexxIT** [comment]
What is your environment? venv? os?

**Comment by jmodlinne** [comment]
I am running off rasparian




Get Outlook for Android







On Tue, May 12, 2020 at 9:14 PM +0200, "Alex X" <notifications@github.com> wrote:















What is your environment? venv? os?

**Comment by AlexxIT** [comment]
What version is HA, SonoffLAN?
Are you using docker, hassio?

**Comment by jmodlinne** [comment]
Hi

the version is : 0.109.6

not using docker or hassio


Alex X wrote on 2020/05/12 21:51:

**Comment by jmodlinne** [comment]
ok some feedback - i put on Hassio and all works like a dream.

**Comment by AlexxIT** [comment]
Hassio rocks! 👍
