### ISSUE TITLE
Error with ipv6 addresses

### ISSUE THREAD

**Issue by defusiondev** [AlexxIT/SonoffLAN#1000]
Seems like the addon is treating IPv6 addresses incorrectly when trying to extract the port. 

```
Logger: custom_components.sonoff.core.ewelink.local
Source: custom_components/sonoff/core/ewelink/local.py:257
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://ha23t.duckdns.org:8384/api/sonoff/617560dc-ed66-425d-bf76-6ca27715e101))
First occurred: 8 October 2022 at 16:20:35 (927 occurrences)
Last logged: 07:53:00

10017388ec => Local4 | {'cmd': 'info'}
10017722a0 => Local4 | {'sledOnline': 'on'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 166, in __new__
    port = val.port
  File "/usr/local/lib/python3.10/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as ':c6de:e2ff:fe11:2af8:8081'
```

**Comment by sipimokus** [comment]
This is not the solution, but if you don't need IPv6, turn it off completely everywhere. (OS, HASS, ...)
Usually IPv6 does more trouble than good. 

I don't know what is your installed version of SonoffLAN component, but I found this commit: https://github.com/AlexxIT/SonoffLAN/commit/9acb74446be54fed07f783eb24b478b9f6d8abd8

Maybe:
- You can try downgrade the plugin version for 3.2.0 if you use newer.
- Or upgrade the version, if you use this or lower version. :)

**Comment by defusiondev** [comment]
thanks i have disabled ipv6 on my router and rebooted it along with the problematic switches - but it's still giving the same error from what looks to be a link local address. 

am using the latest version of SL - will give the downgrade a go.

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0
