### ISSUE TITLE
HA Core Release 2022.10.3 - October 10 breaks power monitoring?

### ISSUE THREAD

**Issue by Bigglesuk** [AlexxIT/SonoffLAN#1004]
Having just upgraded to HA Core Release 2022.10.3 which came out today my Sonoff LAN device that measures power monitoring has stopped working.

I'm running 9 devices via Sonoff LAN and the only one affected is Sonoff Dual R3 setup as a power monitor

![image](https://user-images.githubusercontent.com/22842208/195090742-ae6d7485-6e7c-40b8-a473-f8de2e428368.png)

As you can see pre-upgrade this was working perfectly fine. 
![image](https://user-images.githubusercontent.com/22842208/195090921-babed265-917c-48c7-b0e5-576c146b8bbe.png)

I've performed several restarts with no joy.

**Comment by peditx** [comment]
yeah!!!

503 Service Temporarily Unavailable on https://as-apia.coolkit.cc

**Comment by AlexxIT** [comment]
Temporary problems with cloud
