### ISSUE TITLE
KingArt-M4 / Ewelink Switches

### ISSUE THREAD

**Issue by jmodlinne** [AlexxIT/SonoffLAN#101]
Hey AlexxIT

So Sonoff dont have dimmable switches. however i have KingArt dimmable switches in quite a few rooms - are you able to include them in this integration?

Kingart-M4

**Comment by AlexxIT** [comment]
Please share it to my ewelink account sonofflan@gmail.com

**Comment by jmodlinne** [comment]
i shared it to you... i shared the dimmable switch and an undercounter strip light, led

**Comment by AlexxIT** [comment]
I see. What time can they be switched so as not to bother you?

**Comment by jmodlinne** [comment]
its 16:13 here, so you can play with them, now until like 19:00 or through tomorrow?
When do you want to work on it?

**Comment by AlexxIT** [comment]
Strip already supported in master version #7 
I don't know when I have time. Now I have got info for coding. I won't bother you after 19.

**Comment by jmodlinne** [comment]
awesome - where do i find the strip lights?

**Comment by jmodlinne** [comment]
> awesome - where do i find the strip lights?

never mind, found it..

**Comment by AlexxIT** [comment]
Tell me when can I test

**Comment by jmodlinne** [comment]
anytime from now

Alex X wrote on 2020/05/14 23:23:

**Comment by AlexxIT** [comment]
Supported in latest master
<img width="365" alt="Screenshot 2020-05-15 at 10 01 40" src="https://user-images.githubusercontent.com/511909/82021362-5cd45680-9693-11ea-8954-ef8de122b3f1.png">
