### ISSUE TITLE
sonoff ifan turns off and on by itself

### ISSUE THREAD

**Issue by acmeGR** [AlexxIT/SonoffLAN#1010]
[sonoff-9285498fe27a57139f691eba6b56add1-iFan04 Study-0d4900d1628f5eea2aaecb9d5798dac6.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9832612/sonoff-9285498fe27a57139f691eba6b56add1-iFan04.Study-0d4900d1628f5eea2aaecb9d5798dac6.json.txt)

Hello. I have an ifan 03 and an ifan 04. Both in HA through HACS repository. I also have blocked internet access to them though Unifi router. 
From time to time, when the light is on, it turns off and back on again immediately. This happens to both devices. Is it bcs I don't give them access to internet? All other Sonoff devices I have, don't do something like that. 
Thank you!

**Comment by tomerip** [comment]
I have the exact same problem with iFan04-H, but I’m using it with Homebridge and this plugin:
https://github.com/bwp91/homebridge-ewelink

**Comment by AlexxIT** [comment]
This could be a problem with the RF433. Your neighbors probably have a device that sends similar commands to control the device. Terrible protocol. Terrible protocol. You could try resetting the binding to RF433 or solder out the singal receiver or flash custom firmware.
