### ISSUE TITLE
Sonoff D1 in dyi mode not recognized

### ISSUE THREAD

**Issue by Moldiz** [AlexxIT/SonoffLAN#1015]
Hi!
I've got Sonoff D1 device, and I'm using it in DYI mode. But my device have other UUID name in "
/custom_components/sonoff/core/devices.py" file and its not recognized as dimmer. I have to manually change it after every update.

Line 353:
`    "light": [44, "SONOFF", "D1 DIY"],`
to
`    "diylight": [44, "SONOFF", "D1 DIY"],`

I think its the same problem as in this issue: https://github.com/AlexxIT/SonoffLAN/issues/464
It says its fixed there but i think its not. Thanks for great integration btw!

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0
