### ISSUE TITLE
POWR320D show unknown state for Energy

### ISSUE THREAD

**Issue by odechr** [AlexxIT/SonoffLAN#1017]
We installed about 5 of these new devices. They all show unknown state for energy.
Works fine in Ewelink app and it gives values there.

![image](https://user-images.githubusercontent.com/57597773/198257288-53a8fe1e-8337-4d5c-a526-8dce2759a448.png)

Adding the diagnostic report:
[sonoff-a5455cef31c98175f4e097b4350cec08-POWR320D-316c4527c88b2ce40942365eaf9f2a90.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9878322/sonoff-a5455cef31c98175f4e097b4350cec08-POWR320D-316c4527c88b2ce40942365eaf9f2a90.json.txt)

**Comment by odechr** [comment]
Also i have a strange error in the logs. Might not be related to the issue above.

This error originated from a custom integration.

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:286
Integration: Sonoff (documentation, issues)
First occurred: October 26, 2022 at 11:55:51 (5 occurrences)
Last logged: 12:14:48

Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017fad9d', 'apikey': 'a47bc3a8-8000-44ad-b6b9-f2c60af86403', 'sequence': '1666778146000'}
Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017fad9d', 'apikey': 'a47bc3a8-8000-44ad-b6b9-f2c60af86403', 'sequence': '1666778446000'}
Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017fad9d', 'apikey': 'a47bc3a8-8000-44ad-b6b9-f2c60af86403', 'sequence': '1666863898000'}
Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017fad9d', 'apikey': 'a47bc3a8-8000-44ad-b6b9-f2c60af86403', 'sequence': '1666864924000'}
Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017fad9d', 'apikey': 'a47bc3a8-8000-44ad-b6b9-f2c60af86403', 'sequence': '1666865683000'}

**Comment by odechr** [comment]
Sonoff upgraded to FW 1.0.7 for me and trough the diagnostic field it seems like there is a new field for kwh that was not there before. But it is still unknown in Home Assistant.

        },
        "dayKwh": 26,
        "monthKwh": 76,
        "only_device": {
          "ota": "success",
          "ota_fail_reason": 0
[sonoff-a5455cef31c98175f4e097b4350cec08-POWR320D3-68a7f749b7ee0c57b59dc9c100ab2248.json (1).txt](https://github.com/AlexxIT/SonoffLAN/files/9898870/sonoff-a5455cef31c98175f4e097b4350cec08-POWR320D3-68a7f749b7ee0c57b59dc9c100ab2248.json.1.txt)

        }

**Comment by crazyasyou** [comment]
This is the same as issue 982 - I have the issue with POWR316D (same device but mine is 16amp and your 20amp)

[https://github.com/AlexxIT/SonoffLAN/issues/982](url)

**Comment by odechr** [comment]
Yes that is possible! Wont close the ticket yet untill @AlexxIT have checked if a change can work for both.

**Comment by DaSpors** [comment]
Same over here:
![Screenshot_20221112-161123~2](https://user-images.githubusercontent.com/623201/201480707-3d6986b0-8e66-4de0-810f-696ab50c6a81.png)

**Comment by crazyasyou** [comment]
I've given up with the stock firmware, ewelink and SonoffLAN and flashed with tasmota, so much more control and 10 second updates from the POW to HA

![image](https://user-images.githubusercontent.com/6671537/201492452-88ebeaaa-9446-4bf1-ab1f-969e952d1bcc.png)
