### ISSUE TITLE
Problem with sensor definition in BASIC R3 v3.6.0

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#1018]
hi all

I have problems with a new BASIC R3 device that I was able to enter in HA, but I have noticed that some sensors are not appearing as available, when in the rest of my installation I use them without problems.
Specifically the definition of BSSID and SSID

In the rest of my sonoff I have no problems.

I attach the screenshots.

What could be the problem?

Thanks

`  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "armv7l",
    "timezone": "America/Argentina/Buenos_Aires",
    "os_name": "Linux",
    "os_version": "5.15.61-v7",
    "supervisor": "2022.10.0",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true `

![Basic R3 Diagnostic](https://user-images.githubusercontent.com/65413059/198389536-74e64302-04b0-4331-adaa-fc031230d904.jpg)

![Basic R3 HA](https://user-images.githubusercontent.com/65413059/198389556-31b6a2fa-2247-400e-90a9-e90067749c81.jpg)

**Comment by AlexxIT** [comment]
Is problem still relevant?

**Comment by Gferretta** [comment]
> Is problem still relevant?

Hi Alex
Not an urgency
But I' using SSID in automations and this problem stuck me

**Comment by AlexxIT** [comment]
I thinks this problem can't be fixed. This device just doesn't sends this data on current firmware

**Comment by Gferretta** [comment]
> I thinks this problem can't be fixed. This device just doesn't sends this data on current firmware

Hi Alex
In SonoffLan v3.5.1 appears
Thanks
