### ISSUE TITLE
Powr2 stats

### ISSUE THREAD

**Issue by HyperCriSiS** [AlexxIT/SonoffLAN#1019]
Hi, 
Can you maybe add stats support for Powr2?
[https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics](url)
Best regards 
Hyper

**Comment by HyperCriSiS** [comment]
I wanted to add Powr2 to the energy dashboard as supply device but it is not available there. The app tells to send the above link as information.

**Comment by Tontze** [comment]
I have same issue. As i understood, integration is not giving information properly to energy dashboard. My sensor is this : 

[https://itead.cc/product/sonoff-pow-elite-smart-power-meter-switch/](url)

What information do you need ? 

![kuva](https://user-images.githubusercontent.com/28216916/204093315-5a5ec06a-f320-41ec-8a06-b689b093f38d.png)

**Comment by Tontze** [comment]
Actually this worked out with Riemann sum integral helper :)
