### ISSUE TITLE
EACHEN WiFi Smart Touch Switch-L-RF-US is working

### ISSUE THREAD

**Issue by tonyp740613** [AlexxIT/SonoffLAN#102]
I want to confirm that the EACHEN WiFi Smart Touch Switch-L-RF-US (No neutral wire required) is supported.
https://ewelink.eachen.cc/product/eachen-single-live-wall-switch-us-ac-l123ewelink-app/

**Comment by AlexxIT** [comment]
Please share it to my account sonofflan@gmail.com

**Comment by AlexxIT** [comment]
@tonyp740613 sorry, at first I thought you were asking for support. No need to share the device if it works :)

**Comment by AlexxIT** [comment]
What version of firmware?

**Comment by tonyp740613** [comment]
3.3.0

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by AlexxIT** [comment]
So it has local connection?
Or you use latest stable release 1.10.4, which work only in local mode?

**Comment by tonyp740613** [comment]
I am still running 1.10.3 of your software.  I checked in the ewelink app on android and the Eachen switches have the LAN control toggle so I assume it is using a local connection.

Can I check if it is using local mode by checking the .sonoff.json file?  Or must I update to 1.10.4?

**Comment by AlexxIT** [comment]
Thanks. If you running 1.10 - it's local connection.
