### ISSUE TITLE
sonoff.send_command not working

### ISSUE THREAD

**Issue by jdserras** [AlexxIT/SonoffLAN#1021]
I created some scripts to move the camera but now I get always this message informing that is not possible find the service sonoff.send_command.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/77854423/198832956-83f38a37-148b-4e49-839a-c3d6a79a9bfa.png">

**Comment by AlexxIT** [comment]
Have you setup integration?

**Comment by AlexxIT** [comment]
Closed without response
