### ISSUE TITLE
4CHPROR3- no feedback or loogbook 

### ISSUE THREAD

**Issue by esmaele** [AlexxIT/SonoffLAN#1024]
I am having an issue with the 4CHPROR3 device, I am able to trigger it to turn on from HA, but the state on HA is stuck off only, and the toggle button automatically returns to the OFF state after 10s even if the actual state for the device is ON. also no logback for any new state, I have to trigger it twice in order to turn off the channel 

I can control the device from the ewelink app with no issues. the device is controlled over the cloud, the lan mood is disabled, and the state is updated on the ewelink app when I toggle it from HA.

Diagnostics file :
[sonoff-6f4ae13b1f29098437b73ca3a8fc0897-Back Yard -dfe84c63fd838d1716eb66a18b42044b.json (1).txt](https://github.com/AlexxIT/SonoffLAN/files/9916883/sonoff-6f4ae13b1f29098437b73ca3a8fc0897-Back.Yard.-dfe84c63fd838d1716eb66a18b42044b.json.1.txt)
![image](https://user-images.githubusercontent.com/53559976/199415843-ad5f868d-ad5c-41e5-bbad-8a79cd20a7c2.png)

**Comment by AlexxIT** [comment]
You have cloud issue with some color bulb in your setup. Try to find it first.

**Comment by esmaele** [comment]
I did add     #173: [XLightL1, RSSI], # Sonoff L3-5M-P to the sonoff/core/devices.py file then I got the issue, so I did comment the line hopefully this returned to normal but it didn't 
and I did use the Sonoff L3-5M-P from the ewelink app only 

Thanks

**Comment by AlexxIT** [comment]
Have you some power devices with energy?

**Comment by esmaele** [comment]
yes I have, also noticed some issues with them, no energy data suddenly

**Comment by esmaele** [comment]
I did disable the L3-5M-P from the integration, and the state is reflected from the ewelink app to the devices on HA when I toggle it on ewelink app, lock like it solved

**Comment by slicejunk** [comment]
same issue for me, I have only one 4CHPROR3 on the network.
moreover local mode is not working

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
