### ISSUE TITLE
FIX - SONOFF BULB B02-BL seen as switch and no dimmer or temperature options

### ISSUE THREAD

**Issue by dipdipotat0chip** [AlexxIT/SonoffLAN#1026]
- SONOFF B02-BL seen as switch and no dimmer or temperature option
- found no reference to a fix to this or any mentions on a work around
- SOLUTION
- on the device go to DOWNLOAD DIAGNOSTICS open the file and find the UIID mine was 135
- open /config/custom_components/sonoff/core/devices.py
- you should find the entry for UIID 135 missing
- add the line 

135: [XLightB02, RSSI],  # Sonoff B02-BL 

- B02-BL should now be visible as a light in your drop downs and you will be able to add the dimmer and the cool temperature.

Hope this helps anyone.
DIPDIPOTATOCH1P

**Comment by camsaway** [comment]
This needs to please be added/pulled into code base.

**Comment by AlexxIT** [comment]
Thanks!

**Comment by santiniuk** [comment]
Fix worked a treat!
Thanks for sharing.

**Comment by ZiggySatdust** [comment]
Just what i needed. Thank-you!

**Comment by Cruzy404** [comment]
Un grand merci !!!!!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0
