### ISSUE TITLE
No inching settings for TX2C

### ISSUE THREAD

**Issue by rogozj** [AlexxIT/SonoffLAN#1027]
Hi,
I have two Sonoff smart devices added: TX1C and TX2C switches.
For TX1C inching settings are available but for TX2C they are not.
In Sonoff app on the phone they are present for both devices.
The same firmware version is in both switches.
[sonoff-e6148a36f046b33242b5d6bb9ea28a15-Grzanie wody-8acc40ef37a06df86332235c7f44b9cc.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9969427/sonoff-e6148a36f046b33242b5d6bb9ea28a15-Grzanie.wody-8acc40ef37a06df86332235c7f44b9cc.json.txt)

**Comment by AlexxIT** [comment]
I don't plan to add pulse setting to multichannel device. It can be changed once from mobile app.

Or you can use raw commands:
https://github.com/AlexxIT/SonoffLAN#raw-commands
