### ISSUE TITLE
Cannot connect to host eu-apia.coolkit.cc:443 ssl:default [Try again]

### ISSUE THREAD

**Issue by sm0ke21** [AlexxIT/SonoffLAN#1028]
Cannot log in using my eWeLink account credentials from Settings -> Sonoff -> Configure.
Tested against version 3.3.1 and master (as of today, November 10, 2022).

**Comment by AlexxIT** [comment]
Well. I can't do anything when you have problems with Internet. Maybe you blocked access to the Internet for your server. Maybe your ISP has a problem. Maybe the ewelink cloud is temporarily down.

https://coolkit-technologies.github.io/eWeLink-API/#/en/APICenterV2?id=interface-domain-name

**Comment by sm0ke21** [comment]
I modified the code in cloud.py and replicated the call in postman. Details below.
Please let me know how I can help further.

Request payload
`{
    "password": "REDACTED",
    "countryCode": "+86",
    "email": "REDACTED"
}`

Request headers
`X-CK-Appid: KOBxGJna5qkk3JLXw3LHLX3wSNiPjAVi, Authorization: Sign ....REDACTED`

Response payload
`{
    "error": 400,
    "msg": "sign verification failed",
    "data": {}
}`

**Comment by AlexxIT** [comment]
Do you using original integration code or modified? Collect logs. Maybe there will be something interesting there.
