### ISSUE TITLE
Firmware 3.5.0

### ISSUE THREAD

**Issue by rokam** [AlexxIT/SonoffLAN#103]
I've update some of my sonoffs and the keep switching states. IDK if this is related to the firmware or to this HASS integration.
Can anyone confirm similar issue?

**Comment by rokam** [comment]
I'm using Sonoff Mini.

**Comment by rokam** [comment]
And my sonoffs are configured as lights

**Comment by AlexxIT** [comment]
I don't understand problem.

**Comment by rokam** [comment]
Its related to ghost switching. Although I've shutdown my HASS server and the lights keep changing states by itself. I do think that is a sonoff issue.

**Comment by AlexxIT** [comment]
Do you have this switches? https://www.itead.cc/sonoff-t1.html
You need reset RF 433 lerned codes. It will help.

**Comment by rokam** [comment]
No, I'm using regular switches with sonoff mini.

**Comment by AlexxIT** [comment]
Are there fully mechanical switches or is there electronics in yours (touch or small led light)?

**Comment by rokam** [comment]
They're mechanical.

**Comment by magomao** [comment]
AlexxIT, I update by mistake some TH16 to 3.5.0 and Im screwed now... there's any chance to downgrade them or this plugin will be available to Sonoff TH 3.5.0? tnx in advance

**Comment by AlexxIT** [comment]
Component should work with 3.5.0

**Comment by magomao** [comment]
@AlexxIT I open a new issue for this [https://github.com/AlexxIT/SonoffLAN/issues/527](url)
