### ISSUE TITLE
Add this integration to Home Asssistant Core

### ISSUE THREAD

**Issue by basnijholt** [AlexxIT/SonoffLAN#1031]
Hi @AlexxIT,

This seems to be a very complete integration and it definitely seems good enough to be natively in Home Assistant Core.

What is the reason that this is still a custom integration?

**Comment by AlexxIT** [comment]
- it is much more convenient to keep the integration at my own tempo and at my own level of quality when it is in a separate repository
- no need to spend time on complying with mandatory requirements that do not affect integration quality
- it is possible to write a large readme in own style
- I can support older versions of Hass, all my integrations support Hass v2021.12 and more, I respect the choice of users
- users don't have to wait for the next Hass release for some problem to be fixed
- in any case, I release updates when backward compatibility breaks down in Hass

I disagree with some of the architectural ideas in Hass. But as a developer, I respect all the decisions of its creators.

- I don't think all integrations have to be built into the core. Is this really the "core"? Would you be happy to buy a phone with one million pre-installed apps of any kinds? Maybe Windows should be installed with two thousand different applications?
- I don't think the "core" should break backward compatibility with other applications several times a year. I can run applications in Windows 10 that worked in Windows XP
- I don't think users have to upgrade the entire operating system to fix a bug in one of the application with the chance of getting new bugs in dozens of other very important applications
- I think the core should have a built-in app store. Free one, all my work is free to users

I know that there is a opinion that custom integrations are less quality than embedded integrations. I don't think it's right.

By the way, I have a lot of quite successful projects on quite different topics and technologies. So I think I understand something about "good" application architecture https://github.com/AlexxIT

**PS.** Thanks for your cool custom integration Adaptive Lighting. I've been using it for several years and wrote an article about it https://habr.com/ru/post/529082/
