### ISSUE TITLE
sonoff pow entity energy is unknown

### ISSUE THREAD

**Issue by matusrajnoha** [AlexxIT/SonoffLAN#1032]
Hello, I have an integrated Sonoff POW, everything works but the energy entity is unknown. Is there any way to fix this?
<img width="1052" alt="Snímka obrazovky 2022-11-14 o 16 54 34" src="https://user-images.githubusercontent.com/109215057/201706229-0de32546-8273-4f61-9397-ff8702adde70.png">

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by matusrajnoha** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.9.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.2",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.27.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.3.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "b20e33c",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": false
    },
    "errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017a04dd', 'apikey': '5aa828c9-2710-424d-a0f4-237106346354', 'sequence': '1668504865000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017a04dd', 'apikey': '5aa828c9-2710-424d-a0f4-237106346354', 'sequence': '1668508465000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017a04dd', 'apikey': '5aa828c9-2710-424d-a0f4-237106346354', 'sequence': '1668512066000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017a04dd', 'apikey': '5aa828c9-2710-424d-a0f4-237106346354', 'sequence': '1668513534000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017a04dd', 'apikey': '5aa828c9-2710-424d-a0f4-237106346354', 'sequence': '1668515666000'}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          286
        ],
        "timestamp": 1668515671.2769494,
        "exception": "",
        "count": 22,
        "first_occurred": 1668443667.8526883
      }
    ],
    "device": {
      "uiid": 190,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "ssid": "***",
        "bssid": "***",
        "fwVersion": "1.0.7",
        "current": 8,
        "voltage": 23056,
        "power": 617,
        "uiActive": 180,
        "timeZone": 1,
        "dayKwh": 37,
        "monthKwh": 49,
        "switches": [
          {
            "switch": "on",
            "outlet": 0
          }
        ],
        "configure": [
          {
            "startup": "on",
            "outlet": 0
          }
        ],
        "pulses": [
          {
            "pulse": "off",
            "switch": "off",
            "outlet": 0,
            "width": 500
          }
        ],
        "rssi": -34,
        "threshold": {
          "actPow": {
            "min": 10,
            "max": 500000
          },
          "voltage": {
            "min": 18500,
            "max": 26400
          },
          "current": {
            "min": 10,
            "max": 2000
          }
        },
        "operSide": 1,
        "getHoursKwh": {
          "start": 0,
          "end": 4
        },
        "demNextFetchTime": 1668463200000,
        "only_device": {
          "ota": "success",
          "ota_fail_reason": 0
        },
        "sledOnline": "on"
      },
      "model": "POWR320D",
      "online": true,
      "localtype": null,
      "deviceid": "10017a04dd"
    }
  }
}

**Comment by matusrajnoha** [comment]
Thank you much ...

**Comment by AlexxIT** [comment]
Ok. So your problem related to this issue #982

**Comment by matusrajnoha** [comment]
Hello, does anyone have a solution yet?

**Comment by AlexxIT** [comment]
Keep an eye on the original issue

**Comment by matusrajnoha** [comment]
Ok.. thanks

 

 

Od: Alex X ***@***.***>
Príjemca odpovede: AlexxIT/SonoffLAN ***@***.***>
Dátum: utorok, 15. novembra 2022, 15:54
Komu: AlexxIT/SonoffLAN ***@***.***>
Kópia: Matus Rajnoha ***@***.***>, Author ***@***.***>
Predmet: Re: [AlexxIT/SonoffLAN] sonoff pow entity energy is unknown (Issue #1032)

 

Keep an eye on the original issue
