### ISSUE TITLE
Integration stops working after a few seconds (Cloud Mode)

### ISSUE THREAD

**Issue by rodrigoasrodrigues** [AlexxIT/SonoffLAN#1033]
I am using cloud mode, all devices work fine for a few seconds after I restart the integration but then it all stops reading device statuses.
I can still turn things on and off on HA but HA does not detect any status changes from the device itself, making buttons and sensors useless.
After I restart the logs output CLOUD=>True and after a few seconds { 'online':False} then it stops working.

`2022-11-14 18:19:24 [D] CLOUD True => True`
`2022-11-14 18:19:43 [D] a4400132a0 <= Cloud3 | {'online': False} | None`

**Comment by StephenMilner** [comment]
I am having the same problem.

I have upgraded from 3.3.0 to 3.3.1 in an attempt to resolve this, but without success. Since this problem started without any changes in HA my guess is that Sonof/eWeLink have change something on their platform.

For reference I am in the UK.

You can turn on a device and turn off a device without problem, it's just that the device status are not being read within a few short minutes after a reload - Problem first noticed 17:45 GMT 15/11/22

**Comment by StephenMilner** [comment]
I tried out this suggestion:

https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175877543

Since doing so my automation above has not needed to reloaded the Sonoff integration for the last 30 minutes.

For reference the lines to change are now 108 and 159 for V3.3.1

I do not understand why this would make a difference though.

**Comment by StephenMilner** [comment]
Now all my bulbs have stopped responding but my 4CH RC2 Pro is fine!

**Comment by StephenMilner** [comment]
> It did not work for me, I tried changing both lines, and tried one at a time, but the problem persist.

It did not work for my cloud entities for me either - LAN was fine. I reverted back to running my Automation every 5 minutes and reloading Sonoff if needed. At the last check about 45 minutes ago everything had been working without a reload for 4 hours.

**Comment by StephenMilner** [comment]
Been fine now for 8 hours since 04:20 GMT

**Comment by rodrigoasrodrigues** [comment]
> I reverted back to running my Automation every 5 minutes
Did you change it back to app=0 or just turned the automation on? I am still facing the same issue

**Comment by StephenMilner** [comment]
> > I reverted back to running my Automation every 5 minutes
> 
> Did you change it back to app=0 or just turned the automation on? I am still facing the same issue

Change back to app=0

**Comment by pavelspitz** [comment]
I have the same problem as described higher. The all zigbee Sonoff devices did not send any states and these states could not be get from.
I tried to enable multicast in my router and now everything have seemed to work properly.

**Comment by StephenMilner** [comment]
> I had the same problem as described higher. The all zigbee Sonoff devices did not send any states and these states could not be get from.
> I tried to enable multicast in my router and now everything have seemed to work properly.

I think the problem is at the Sonoff end - The reliability is very intermittent at the moment - Things work for hours, then it stops working every minute or two for a while, and then OK again. I've made no changes during this different behaviours from a HA point of view.

**Comment by pavelspitz** [comment]
> I think the problem is at the Sonoff end - The reliability is very intermittent at the moment - Things work for hours, then it stops working every minute or two for a while, and then OK again. I've made no changes during this different behaviours from a HA point of view.

Yes, I have to agree with you that the problem is probably in Sonnof end. The router multicast settings did not have long lasting effect. The problems are back.

**Comment by Jones1982** [comment]
Similar problem to mine:
the zigbee gateway is no longer receiving data from all zigbee devices.
i have 3 thermometers, 10 door sensors, and 2 PIRs...and they ALL stop sending status for 4/6/8 hours.
The zigbee button doesn't work either.
If I reload the Sonoff Lan integration, it works again for a few minutes, but then starts again.

**Comment by pavelspitz** [comment]
I finally installed official add-on "ewelink smart home" and now there is most of my zigbee devices show relevant status on the ewwlink dashboard.
I have 2 zigbee Sonoff thermometer and 4 zigbee Sonoff sockets. Thermometers are OK, but sockets time-to-time have outages, which are repaired via restart of ewelink add-on (for example I tried to turne on one socket and this was in "on" state in ewelink mobile app, but in ewelink dashboard was still "off" until restart the add-on) .
I have also 7 zigbee smoke detectors (not produced by Sonoff) which are sucessfully connected to Sonoff Zigbee Bridge and these are not suported via this official ewelink add-on.
In my Node-red flows I enforced by time receiving status from the themometers devices added by ewelink add-on --> and they all get relevant temperature values. The smoke detectors control via Sonoff LAN get already irrelevant status --> if I tried test the smoke on one sensor this sensor did not send information about this event (i.e. "smoke" attribute was absent in the message). 
But the most interesting thing is that the ewelink app in my mobile does not register any problem with any devices - all zigbee devices are connected and can be controled via app UI without any problem and lags.

I think that the problem is only in applications usage sonoff (ewelink) web-interface.

**Comment by pavelspitz** [comment]
I probably found the solution of this problem.
This is caused by the restriction of ewelink API which doesn't allow loggin one person with the same account to two or more applications and also web services (on the various devices) at the same time (exception has only using application in web browser environment which is payed).
Thus I tried to create new account and share him all my home from my main account.
This new account I used in Sonoff LAN integration. The previous intalled integration I had to uninstalled and after this I installed the same with my new account and chouse home in settings of this add-on.
After HA restarted all devices and entities were back under the same enity IDs and thus I even didn't have to change any entities in my flow in Node-Red automatizations.

Now all automatizations have been running without any problem about 24 hour.

**Comment by jcdnxs** [comment]
No that solution also don´t work pavelspitz. I tried all the solutions explained in this tread but none of them work. I have to reload the integration every time i want to see what is happening in sonoff devices or to reboot the HA!!! What a boring and frustating situation....

**Comment by JKSniper1** [comment]
It started working on it's own around 8 hours ago again. Probably fault on Ewelink side. 

![image](https://user-images.githubusercontent.com/8069093/203262846-4c5454f1-5dc2-4a3e-9d2c-75868ffe4bce.png)

**Comment by StephenMilner** [comment]
There are periods when it works for hours, and then times when I have to reload all the time.

**Comment by jcdnxs** [comment]
i am waiting for another solution or let ewelink solve the problem. Otherwise I will have to change the firmware of all my devices and never buy sonoffs again! It is a huge risk to have devices that depend on third parties mainly from china. One of these days we find our house controlled by others and totally dependent on third parties.

**Comment by jcdnxs** [comment]
Boa noite Rodrigo, temos que esperar mais uns dias e ver como é que a  
situação evolui. 

Cumprimentos

João Xavier

----- Mensagem de Rodrigo Rodrigues ***@***.***> ---------

  Data: Tue, 22 Nov 2022 08:08:24 -0800

  De: Rodrigo Rodrigues ***@***.***>

  Assunto: Re: [AlexxIT/SonoffLAN] Integration stops working after a  
few seconds (Cloud Mode) (Issue #1033)

  Para: AlexxIT/SonoffLAN ***@***.***>

  Cc: jcdnxs ***@***.***>, Comment ***@***.***>

> I have tried to remove my account from every other device to make  
> sure it wasn't the session problem. Still, the problem persists, I  
> have another house that is using an older version of the integration  
> (2.4.6) and there seems to be no problem (maybe it's in local mode,  
> don't know how to check in that version), that version, however,  
> does not support my NSPanels.
>
>  I moved everything Zigbee to ZHA and most of the other things work  
> on local mode, but my L2 led strips only work on cloud mode and my  
> daughter is constantly changing those from the NSPanel, I can't get  
> the status of the leads but I can set the status on cloud mode.
>
> —
>
>  Reply to this email directly, view it on GitHub[1], or unsubscribe[2].
>
>  You are receiving this because you commented.Message ID:  
> ***@***.***>

----- Fim da mensagem de Rodrigo Rodrigues ***@***.***> -----





Ligações:
---------
[1] https://github.com/AlexxIT/SonoffLAN/issues/1033#issuecomment-1323911121
[2]

**Comment by pavelspitz** [comment]
Hello everyone, I am very sorry that my method didn't work for you. For me this method has been stil working without any problem. Below I attach the sources where I found the informations about:

1. Another Sonoff add-on which was mentioned in SonnofLAN documentation https://github.com/peterbuga/HASS-sonoff-ewelink ... please try to find out description of meaning **grace_period**. 
2. The eWelink staff themself described this problem in this https://help.ewelink.cc/hc/en-us/articles/360060200471-Is-it-possible-to-use-the-same-eWeLink-account-on-multiple-devices-
3. There is described how to share device with another account https://help.ewelink.cc/hc/en-us/articles/360020151692-How-to-share-a-device-with-another-account-in-eWeLink-app

There is settings of my SonoffLAN add-on which used secondary account - I have ticked "_Domov_" as my shared home for this account:
![image](https://user-images.githubusercontent.com/37045313/203440049-79e75340-68a5-4349-b5f1-5fd13bdfa9f8.png)

I hope that this information could be helpful for you.

**Comment by jcdnxs** [comment]
Any news?

**Comment by rodrigoasrodrigues** [comment]
I have just updated my other home from 2.4.6 to the current version and everything went from perfectly working to the same problem, so I don't think it is on the sonoff end if older versions work.

**Comment by jcdnxs** [comment]
Let me understand, you update the SONOFF LAN integration? from 2.4.6 to v3.3.1?
I'm starting to think that the problem is not in ewelink end but with the SONOFFLAN integration...

**Comment by JKSniper1** [comment]
Hey. I commented 4 days ago that it started working for me. It is indeed still working. I have 3.3.1 and latest update on everything. 
![image](https://user-images.githubusercontent.com/8069093/204059792-6f8ac241-abad-48ea-bf08-2e23b8ba6c63.png)

**Comment by rodrigoasrodrigues** [comment]
> Let me understand, you update the SONOFF LAN integration? from 2.4.6 to v3.3.1?

Correct, I have two installations, one that was in the current version and another that I hadn't updated in a while (2.4.6 doesn't even have the GUI config).
v3.3.1 is displaying the issue while v2.4.6 was fine. After the update I have the same behaviour on both.

**Comment by Jones1982** [comment]
> > Fammi capire, aggiorni l'integrazione SONOFF LAN? dalla 2.4.6 alla v3.3.1?
> 
> Esatto, ho due installazioni, una che era nella versione corrente e un'altra che non aggiornavo da un po' (2.4.6 non ha nemmeno la configurazione della GUI). v3.3.1 mostra il problema mentre v2.4.6 andava bene. Dopo l'aggiornamento ho lo stesso comportamento su entrambi.

in previous versions of HACS, you could choose whether to update the integration or not, now it does it automatically. however, I've had the same problem for days, and I'm thinking of buying the sonoff usb stick, so I solve every problem with zigbee devices once and for all. I just don't know which version to use...

**Comment by rodrigoasrodrigues** [comment]
>  I'm thinking of buying the sonoff usb stick, so I solve every problem with zigbee devices once and for all
@Jones1982 if you have the sonoff Zigbee hub connecting everything you could just flash tasmota to it and use ZHA which is precisely what I am about to do, I did it before and it works very well.

**Comment by Jones1982** [comment]
> > I'm thinking of buying the sonoff usb stick, so I solve every problem with zigbee devices once and for all
> 
> @Jones1982 if you have the sonoff Zigbee hub connecting everything you could just flash tasmota to it and use ZHA which is precisely what I am about to do, I did it before and it works very well.

yes, I have the sonoff zigbee hub, but I have stability problems on some door sensors, despite my repeated tickets on the ewelink app, and the latest updates, I have not solved anything. however I can't flash it, because I don't have the other stick to be able to flash.

and since I also have another zigbee hub from tuya, on which t&u sensors with display are connected, I would like to unify everything under a single zigbee hub, that's why I was asking about the sonoff zigbee usb stick [https://www.amazon.it/dp/B0B6P22YJC/?coliid=IUFSU8CV86MSR&colid=O9WAAGSJTG8N&psc=1&ref_=lv_ov_lig_dp_it](url)

**Comment by andreasbuff** [comment]
Hello, had the same problem with "non status updateing", since one or two weeks. 

Today I reconfigured the Integration in HA and  found out, that there is a **new Option** in the configuration UI (see picture). If you have assigned sonoff-devices, in your EWE app to a specific "house", then you have to check this box!
Once checked the box and restarted, the device status is updated again. 

![Sonoff](https://user-images.githubusercontent.com/80002637/204584938-7651f3b0-12dc-4d9a-9ef2-b5cf50f1b0bb.png)

**Comment by adaminaus** [comment]
> Hello, had the same problem with "non status updateing", since one or two weeks.
> 
> Today I reconfigured the Integration in HA and found out, that there is a **new Option** in the configuration UI (see picture). If you have assigned sonoff-devices, in your EWE app to a specific "house", then you have to check this box! Once checked the box and restarted, the device status is updated again.
> 
> ![Sonoff](https://user-images.githubusercontent.com/80002637/204584938-7651f3b0-12dc-4d9a-9ef2-b5cf50f1b0bb.png)

This worked for about all of 90mins then back to no good.
It is killing me I have so many devices.

![image](https://user-images.githubusercontent.com/67089752/204650316-82890083-be86-4361-b0e2-8491c6f55080.png)

**Comment by StephenMilner** [comment]
I’ve tried the specific home, which hasn’t fundamentally changed the situation. 

It can’t be needing a second account as eWeLink wouldn’t work with Alexa if that was the case. 

From 3am to 3pm it worked. Then stopped.

**Comment by StephenMilner** [comment]
> > Hello, had the same problem with "non status updateing", since one or two weeks.
> > Today I reconfigured the Integration in HA and found out, that there is a **new Option** in the configuration UI (see picture). If you have assigned sonoff-devices, in your EWE app to a specific "house", then you have to check this box! Once checked the box and restarted, the device status is updated again.
> > ![Sonoff](https://user-images.githubusercontent.com/80002637/204584938-7651f3b0-12dc-4d9a-9ef2-b5cf50f1b0bb.png)
> 
> This worked for about all of 90mins then back to no good. It is killing me I have so many devices.
> 
> ![image](https://user-images.githubusercontent.com/67089752/204650316-82890083-be86-4361-b0e2-8491c6f55080.png)

If you have a spare or unused device you can set up an automation to turn it on, wait 2 minutes to test if HA thinks it’s still on and if not reload the Sonoff integration. Don’t forget to do the reverse, switch it off and check and if still on reload the integration. 

I trigger this every 20 minutes

**Comment by StephenMilner** [comment]
> Let me understand, you update the SONOFF LAN integration? from 2.4.6 to v3.3.1?
> I'm starting to think that the problem is not in ewelink end but with the SONOFFLAN integration...

Mine was already at 3.2.2 when it started showing the problem. 

I upgraded to 3.3.1 to see if the problem was resolved.

**Comment by rufica** [comment]
after update HA core. everything worked

**Comment by StephenMilner** [comment]
> after update HA core. everything worked

What version have you updated to?

**Comment by adaminaus** [comment]
Ok lets see i have gone from 
Installed version
2022.11.5
to the Latest version
2022.11.5

Fingers Crossed

**Comment by adaminaus** [comment]
It has been 10hrs so far so good

**Comment by adaminaus** [comment]
And over night it stoped again so that did not work! (:

**Comment by StephenMilner** [comment]
Upgrade to 2022.11.5 didn’t help me.

**Comment by sandrobastos** [comment]
Hi All, I have the same problem. I installed a whole new system from the scretch, moved some DualR3 to it for tests and I have the same problem. On this new environment I didn't install anything beyond HACS and SonoffLAN. I am using Home Assistant 2022.11.5 and SonoffLan v3.3.1. I quite new on HA world so I am totally lost on how to progess. Any help here would be very apprecianted

**Comment by jcdnxs** [comment]
already solved the problem "tasmotized all things"
SONOFF cloud is a problem, run away from everything chinese....

**Comment by sandrobastos** [comment]
I will need to learn how to "tasmotized" first, but thanks for the suggestion.

**Comment by JKSniper1** [comment]
- For me, it's still working. It wasn't working and then I was toggling some things about debug options, home check, uncheck, etc. etc. - and it started working and it's working for 10 day+ 
![image](https://user-images.githubusercontent.com/8069093/205516958-0b00e6e8-21de-48ed-aee5-14aedf04de79.png)


- BTW -> Do Tasmota run via Cloud aswell? I have sensors on different network than HA, so I can't actually have local system I presume...

**Comment by StephenMilner** [comment]
> * For me, it's still working. It wasn't working and then I was toggling some things about debug options, home check, uncheck, etc. etc. - and it started working and it's working for 10 day+
>   ![image](https://user-images.githubusercontent.com/8069093/205516958-0b00e6e8-21de-48ed-aee5-14aedf04de79.png)
> * BTW -> Do Tasmota run via Cloud aswell? I have sensors on different network than HA, so I can't actually have local system I presume...

Where are you based geographically? Just wondering if you are using the European servers.

**Comment by JKSniper1** [comment]
I am. central Europe. It wasn't working for me for a few weeks, than I've went and fiddle around with settings and it's working since. Did not change anything significant.

**Comment by StephenMilner** [comment]
> I am. central Europe. It wasn't working for me for a few weeks, than I've went and fiddle around with settings and it's working since. Did not change anything significant.

Well, I followed your advice and also tinkered a bit.  Turned on debug mode and turned off My Home. No better. Downloaded latest HACS update. Switched on My Home and restarted HA. 

I won’t be declaring this a success yet, but I’ve not needed a reload for the last 4 hours since the HA restart. 

Good spot.

**Comment by StephenMilner** [comment]
> > I am. central Europe. It wasn't working for me for a few weeks, than I've went and fiddle around with settings and it's working since. Did not change anything significant.
> 
> Well, I followed your advice and also tinkered a bit. Turned on debug mode and turned off My Home. No better. Downloaded latest HACS update. Switched on My Home and restarted HA.
> 
> I won’t be declaring this a success yet, but I’ve not needed a reload for the last 4 hours since the HA restart.
> 
> Good spot.

Was all ok between 11am until 17:20 when my automation detected a problem and reloaded. *Sigh*

**Comment by andreasbuff** [comment]
After reading a lot of comments, of users, which have issues with this integration and others, haveing no problems, I cam up with an other idea. For all those, haveing an issue with this integarions: "do you have a single instance or Home Assistant", or do you have an other instance of HA running (Test, oder Backup, or High Avalability)?  I think I, you can only have 1 instance of this integration running, at the same time?! I may be wrong, but I think I had this issue once I as testing and have had 2 instances (with same eWe-Account) running for backup and testing? Regards

**Comment by StephenMilner** [comment]
I’ve had another look at the automation and there is a better way to fix this problem. 

Instead of executing a reload of the integration (Home Assistant Core Integration:Reload for a single device, which reloads the entire integration) you can perform a Home Assistant Core Integration:Update Entity and then add ALL of your Sonoff entities (or at least the entity ID of the device) and you then get the correct status reflected of all your Sonoff devices. 

I’m going to trigger this every 20 seconds and keep an eye on the load on the system. 

![6F909E21-FC78-40F6-A60E-DE547434D864](https://user-images.githubusercontent.com/73119931/205709022-5ac0b492-30dc-40bb-8cae-81c7de1c1eae.jpeg)

**Comment by StephenMilner** [comment]
> After reading a lot of comments, of users, which have issues with this integration and others, haveing no problems, I cam up with an other idea. For all those, haveing an issue with this integarions: "do you have a single instance or Home Assistant", or do you have an other instance of HA running (Test, oder Backup, or High Avalability)? I think I, you can only have 1 instance of this integration running, at the same time?! I may be wrong, but I think I had this issue once I was testing and have had 2 instances (with same eWe-Account; same Client-ID and same Secret) running for backup and testing? Regards

Just one instance.

**Comment by StephenMilner** [comment]
> > I’ve had another look at the automation and there is a better way to workaround this problem.
> > Instead of executing a reload of the integration (Home Assistant Core Integration:Reload for a single device, which reloads the entire Sonoff integration) you can perform a Home Assistant Core Integration:Update Entity and then add ALL of your Sonoff entities (or at least the entity ID of the device) and you then get the correct status reflected of all your Sonoff devices.
> > I’m going to trigger this every 20 seconds and keep an eye on the load on the system. EDIT: No noticeable impact on the server load.
> > ![6F909E21-FC78-40F6-A60E-DE547434D864](https://user-images.githubusercontent.com/73119931/205709022-5ac0b492-30dc-40bb-8cae-81c7de1c1eae.jpeg)
> 
> Hi
> 
> I'has an automation that run every 1 minutes exactly like you say (Home Assistant Core Integration:Update Entity) and NO work with the problem that I recently post. Only "Home Assistant Core Integration:Reload" solve the problem and update correctly all devices.
> 
> Regards

Your problem seems to be a different, but similar, problem to the other posters on this thread.

**Comment by adaminaus** [comment]
> 

Can you show me the timer part to continue ever few mins, please 

Thanks
Adam

**Comment by Gferretta** [comment]
> > 
> 
> Can you show me the timer part to continue ever few mins, please
> 
> Thanks Adam

trigger:
  - platform: time_pattern
    minutes: /1

**Comment by adaminaus** [comment]
ok sorry still a little lost here is what i have in the Script 


alias: Sonoff Bug fix
sequence:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - switch.sonoff_1000429fa1
        - switch.sonoff_100170f6fd
        - sensor.sonoff_1000429fa1_voltage
        - sensor.sonoff_1000429fa1_power
        - sensor.sonoff_1000429fa1_current
        - sensor.sonoff_100118f898_temperature
        - switch.sonoff_1000220251
        - switch.sonoff_100118f898
mode: single

**Comment by StephenMilner** [comment]
> ok sorry still a little lost here is what i have in the Script
> 
> alias: Sonoff Bug fix sequence:
> 
> * service: homeassistant.update_entity
>   data: {}
>   target:
>   entity_id:
>   - switch.sonoff_1000429fa1
>   - switch.sonoff_100170f6fd
>   - sensor.sonoff_1000429fa1_voltage
>   - sensor.sonoff_1000429fa1_power
>   - sensor.sonoff_1000429fa1_current
>   - sensor.sonoff_100118f898_temperature
>   - switch.sonoff_1000220251
>   - switch.sonoff_100118f898
>   mode: single

You should use an automation to trigger the action:

![2F953B38-6FC1-4D0A-9DA6-EF902E2C4A24](https://user-images.githubusercontent.com/73119931/205891347-4c095e06-cc95-4850-a555-967c77cf41c5.png)

**Comment by adaminaus** [comment]
Great- it is updating and a workaround - thank you

**Comment by bergrnl** [comment]
> 

The "Home Assistant Core Integration: Reload config entry" automation didn't work for me either. However "Home Assistant Core Integration: Reload config entry" does work for me. I only added 1 entity and all entities are updated now.

**Comment by StephenMilner** [comment]
> The "Home Assistant Core Integration: Update entity" automation didn't work for me either. However "Home Assistant Core Integration: Reload config entry" does work for me. I only added 1 device and all devices are updated now every x minutes.

I am getting mixed results. Update entity has been working for some time, but failed today and a reload config was needed. Once done it seems reliable again just using update entity

**Comment by jcdnxs** [comment]
The only solution for me is to forget sonoff and tasmotized every thing.

**Comment by StephenMilner** [comment]
> The only solution for me is to forget sonoff and tasmotized every thing.

I’ve not got that option for my light bulbs without destroying them in the process.

**Comment by FelisucoVFR** [comment]
> The only solution for me is to forget sonoff and tasmotized every thing.

Luckily the rest of the people are searching a solution. This doesn’t help anybody.
For any reason I never had any issue with any of my >30 SonOff devices for years already.
I also own a few Tasmota and they have their good and bad points.
Anyway, as this post also doesn’t help anybody, just say thanks to AlexxIT and the team helping to grow.

**Comment by StephenMilner** [comment]
I have upgraded to HA 2022.12.5 

Problem persists.

**Comment by jcdnxs** [comment]
Does anyone know which sonoff command to reload the integrations? I wanted to make an auxiliary button so that when you click on it, the sonoff integration is reloaded and updated.
I had tasmotized almost every thing but I still have some sonoff devices I wanted to keep.
Thanks

**Comment by StephenMilner** [comment]
> Does anyone know which sonoff command to reload the integrations? I wanted to make an auxiliary button so that when you click on it, the sonoff integration is reloaded and updated.
> I had tasmotized almost every thing but I still have some sonoff devices I wanted to keep.
> Thanks

Home Assistant Core Integration: Reload config entry [any single Sonoff device]

**Comment by jcdnxs** [comment]
Done!
Thanks

**Comment by AlexxIT** [comment]
@rodrigoasrodrigues `a4400132a0 <= Cloud3 | {'online': False}` is a normal situation
The cloud notified integration that some device had gone offline. Integration can't do anything about it.

**Comment by AlexxIT** [comment]
If anyone else has problems with the cloud connection - he should collect the logs and open a new issue.
