### ISSUE TITLE
Sonoff Dw2 Wifi - Sync issue between ewelink app and homeassistant

### ISSUE THREAD

**Issue by firdaushadi442** [AlexxIT/SonoffLAN#1036]
Sync between home assistant (sonofflan) and ewelink need to reload always. Its only sync a few second/hours after reload. For example, when i close the door, in ewelink app (closed) and home assistant (closed), after a few second/hours when i open the door, in ewelink app (opened) but in home assistant app (closed), then i need to reload sonofflan or restart  home assistant to sync back between ewelink app and homeassistant app. And it happened over and over again. sorry for my bad english.

**Comment by Jellybabz** [comment]
I have a similar issue. Home assistant does not update only when i reload the integration. alle my temperatures and humidity sensors does only pull data from ewelink app when i reload the intergration. 

i have attach an image with the time and date when it stopped working.
![Skærmbillede 2022-11-17 kl  11 50 35](https://user-images.githubusercontent.com/73821854/202427148-4f3ea09a-2220-4d5b-89e0-d71b5f763b57.png)

**Comment by JKSniper1** [comment]
Hello! I have exact same problem. If go in settings and switch between "auto/cloud" or "local/cloud", no matter the combination, it will update that moment just fine. But after that there is no more updates. 

I pressed that button 9h ago... and before that a day...etc. values are not refreshing. 
![image](https://user-images.githubusercontent.com/8069093/202662168-29d75219-d1fe-416a-8712-af877cb6774b.png)

Also when I press a button to turn on/off a switch. It will turn it on, but the icon and state won't get refreshed.

**Comment by scordier1** [comment]
I have the same issue  all my devices hanging off my zigbee bridge only responds for a few minutes after a restart of HA or a reload of the sonoff integration

**Comment by H-B-C** [comment]
I have the same problem. All my Sonoff devices WiFi and Zigbee are hanging.

**Comment by Ceplin82** [comment]
Same issue. I try to use my Sonoff SNZB-02 sensors to trigger the heating system but they refresh only randomly or after Home assistant restart. The sensors are works porperly:
![image](https://user-images.githubusercontent.com/115318022/203409672-afc26f9a-1e1d-4c6c-af9e-19992a438abf.png)

**Comment by BeRGB** [comment]
I have same problem with switches, when I toggle switch ON app change state but on HA don’t, only when I do few times on/off it change state on HA but few minutes later same story again

**Comment by kozaczi** [comment]
I have the same. Zigbee are not rehreshing temp and humidity value.  Propably I swap them by esphome +dht22. :(

**Comment by jan-bee** [comment]
I same problem, its works for seconds after integration reload, than its not renew informations, but eWelink cloud is still functional. After integration reload it is working again for couple of seconds. I hapened after I updated from core 2022.9.5 to 2022.11.5.

**Comment by sgdva** [comment]
I can confirm this behavior as well for contact sensor connected through the bridge: first read works, then stops afterwards

**Comment by danieletognetti01** [comment]
Same problem with sonoff DW2-L wifi

**Comment by AlexxIT** [comment]
This problem can happen because some errors from any of your devices. Without error description it can't be fixed.
