### ISSUE TITLE
Credentials screen requires valid eWelink credentials, does not proceed with "any"

### ISSUE THREAD

**Issue by DurvalMenezes** [AlexxIT/SonoffLAN#1038]
As per the subject.

I've tried entering both a fake phone number and a fake email, in both cases  leaving the password blank, but it always results in the same screen with the "user account XXXXX does not exist" message on top.

Is there a way to use this integration without a eWelink account?

This is with SonoffLAN-3.3.1 in HomeAssistant 2022.11.3

**Comment by DurvalMenezes** [comment]
Managed to get past the authentication screen using another browser: issue was on Firefox on Android, worked with Chrome on desktop Linux (entering "+9" on the username screen and leaving blank the pasword).

Closing this issue now.

**Comment by AlexxIT** [comment]
Blank password for DIY mode
