### ISSUE TITLE
Having option to expose RSSI to HA would be really nice 

### ISSUE THREAD

**Issue by edgarmaloverian** [AlexxIT/SonoffLAN#1048]
Really sorry if I did not read manuals carefully, but I found no way to read RSSI  for devices although I see them in logs. Would be handy to optimize comms moving bridges-sensors around the house.

**Comment by emeyedeejay** [comment]
+1 for this :) Love this integration.

**Comment by Gferretta** [comment]
Add line in Configuration.Yaml

sonoff:
  sensors: [ rssi ]

And voilá! 💪

**Comment by emeyedeejay** [comment]
...... and BOOM! Thank you!

(how did you know to do this? What else can it do?)

![image](https://user-images.githubusercontent.com/8543879/205440502-babcd00d-d3cf-4cd7-b175-227729768e9a.png)

**Comment by Gferretta** [comment]
> ...... and BOOM! Thank you!
> 
> (how did you know to do this? What else can it do?)
> 
> ![image](https://user-images.githubusercontent.com/8543879/205440502-babcd00d-d3cf-4cd7-b175-227729768e9a.png)
>

**Comment by Gferretta** [comment]
> ...... and BOOM! Thank you!
> 
> (how did you know to do this? What else can it do?)
> 
> ![image](https://user-images.githubusercontent.com/8543879/205440502-babcd00d-d3cf-4cd7-b175-227729768e9a.png)



You can add more sensors:

![Screenshot_20221205_001145_GitHub](https://user-images.githubusercontent.com/65413059/205654107-d72c2ffe-2056-43f4-a432-2c2282080f2a.jpg)
