### ISSUE TITLE
Can I delete my eWeLink account

### ISSUE THREAD

**Issue by alejandro5x** [AlexxIT/SonoffLAN#105]
Hi Alexx, great work!
If the sonoff device will work without cloud, can i remove my eWeLink account after i add it to home assistant?

I followed all the instructions and i was able to control a [MHCOZY Garage Door Opener (5V)](https://www.amazon.com/MHCOZY-Updated-Wireless-Inching-Self-locking/dp/B07L69HD6N) with home assistant, then i delete my eWeLink account and then i wasn't able to control it again. 

I include this in my configuration.yaml file
```javascript
sonoff:
  username: mymail@gmail.com
  password: mypassword
  mode: local
  reload: once
```
Also the .sonoff.json file was created

**Comment by AlexxIT** [comment]
Yes! If you have sonoff.json file - all info will be loaded from it.
