### ISSUE TITLE
Circuit breaker switch off automatically, when it is awich on by SonoffLAN

### ISSUE THREAD

**Issue by quinzico** [AlexxIT/SonoffLAN#1050]
Hi,

I've installed a circuit breaker :

https://pt.aliexpress.com/item/1005003988548399.html?spm=a2g0o.order_list.0.0.d6dacaa4pvUFYj&gatewayAdapt=glo2bra

The issue is that if i use ewelink, i can tun on or turn off normally, but if i use SonoffLAN, when i turn on, after 1 second it turns off. I need to try to turn on 3 or 4 times, for it to be on after that.

With the ewelink app, works flawlessly.

Attached is the diagnostics file 
[sonoff-ade0c53cfa28e84df9e79ac45bb76687-Forno-e354120636709c9d41334a0521a8cf59.json.txt](https://github.com/AlexxIT/SonoffLAN/files/10096853/sonoff-ade0c53cfa28e84df9e79ac45bb76687-Forno-e354120636709c9d41334a0521a8cf59.json.txt)

**Comment by AlexxIT** [comment]
You have problems with cloud connection
