### ISSUE TITLE
Sonoff POW R3 (power consumption)

### ISSUE THREAD

**Issue by mlaciak** [AlexxIT/SonoffLAN#1052]
Currently sonoff powR3 in SonoffLan integration supports:
- device_class: current
- device_class: power
- device_class: voltage

Does not support:
- device_class: energy

**Comment by mlaciak** [comment]
I created ticket on eWeLink because looks like, the firmware for POW R3 (25A) has issues similar to the early firmware version in pow elite, when the data is shown only sometimes, or when You start/stop the device multiple times, so 1.0.0 is buggy

**Comment by Tontze** [comment]
Hm ok, so it does not have anything to do with the first post ?

**Comment by mlaciak** [comment]
At this point - hard to tell, i though that energy should appear on entity dashboard anyway no matter if it has 0 kWh or bigger value - Same as it does with current/power/voltage

**Comment by Tontze** [comment]
Ah ok yes.  I have sonoff pow elite, and it does report current/power/voltage only. I use mentioned helper to convert it to energy.

**Comment by AlexxIT** [comment]
@mlaciak please show device diagnostics

**Comment by mlaciak** [comment]
```
"devices": {
      "100168bxxx": {
        "uiid": 32,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "only_device": {
            "ota": "success"
          },
          "sledOnline": "on",
          "ssid": "***",
          "bssid": "***",
          "fwVersion": "1.0.0",
          "staMac": "***",
          "rssi": -74,
          "init": 1,
          "alarmType": "pcv",
          "alarmVValue": [
            -1,
            -1
          ],
          "alarmCValue": [
            -1,
            -1
          ],
          "alarmPValue": [
            -1,
            -1
          ],
          "switch": "off",
          "startup": "off",
          "pulse": "off",
          "pulseWidth": 500,
          "power": "0.00",
          "voltage": "1.28",
          "current": "0.00",
          "oneKwh": "stop",
          "uiActive": 7200,
          "timeZone": 1,
          "demNextFetchTime": 1671490800000,
          "hundredDaysKwh": "get"
        },
        "model": "POWR3",
        "online": true,
        "localtype": "enhanced_plug"
      }
```

**Comment by AlexxIT** [comment]
The other information you have cut out is also important.

**Comment by marcforn** [comment]
I have the same issue about energy not being reported and the only way to fix that was to open the ewelink app. Then magically the energy and power sensors got updated. If I close the mobile app, then stops reporting again :S

**Comment by AlexxIT** [comment]
Power consumption updates only from cloud and only by request. Mobile app makes these requests and integration makes these requests. Unless, of course, you have forbidden it.

**Comment by AlexxIT** [comment]
Energy for this model supported in latest integration version

**Comment by clipse2004** [comment]
Mmh did it really work now? I have same problem. 
It only updates if i open the ewelink app after closing not :/
