### ISSUE TITLE
Can't get LAN control

### ISSUE THREAD

**Issue by aureliusss** [AlexxIT/SonoffLAN#1055]
Hi, first of all thank you very much for your work.
I've upgraded my design using THR316 with Hass running on raspberry.

While raspberry is has internet connection, everything in fine, but as soon as internet is out, LAN control does not work. 
Integration is updated at 3.3.1

How can I show you debug data?

Thanks in advance

**Comment by ENGMohamedAskar** [comment]
I have the same problem too !!

**Comment by aizmob** [comment]
The same problem on Home Assistant 2022.12.3, OS 9.3 on intel nuc.
THR316D operates in auto mode and every time internet connection is lost my device goes down.

**Comment by wsjunior1985** [comment]
Same here, any solution for lan control only?

**Comment by aureliusss** [comment]
@AlexxIT this is the workaround I used, maybe it can help.
My setup is the following:
Raspberry Pi 4 Debian Buster
Home Assistant Docker Installation Home Assistant 2022.12.3
SONOFF LAN 3.3.1
SONOFF THR316

I guess the problem is that ewelink is no longer storing IP, so the plugin can't retrieve it from the cloud.
Raspberry is working as access point, so I bind the MAC address of the sonoff to a fixed IPv4 in **etc/dnsmasq.conf** with this line:
**dns-host=[MAC ADDRESS],[FIXED IPv4]**

than I added this field inside the json from which the plugin loads devices when there is no internet connection (**config/.storage/ewelinkaccount.json**): 
**"host": '[FIXED IP]"**
just after the "apikey" field.

restart sonoff and it's working.

I guess that if internet connection is available again **config/.storage/ewelinkaccount.json** will be overwritten and everything should be done again.

**Comment by jacotec** [comment]
I also got a Sonoff for temperature measurement of my Sauna and would like to run it fully local (I really don't like any chinese cloud connected to my HA).

An ability to generally configure local IP addresses of the Sonoff devices in SonoffLAN and run LAN only without any need of cloud connection would be awesome!

**Comment by aizmob** [comment]
seems to be a [solution](https://github.com/AlexxIT/SonoffLAN/issues/1066#issuecomment-1366548854)

**Comment by AlexxIT** [comment]
#839
