### ISSUE TITLE
WARNING RemoteDevice is deprecated

### ISSUE THREAD

**Issue by tjhiwa** [AlexxIT/SonoffLAN#106]
There is a warning with HA 0.100.0 when it starts.

> Log Details (WARNING)
Logger: homeassistant.components.remote
Source: components/remote/__init__.py:162
Integration: Remote (documentation, issues)
First occurred: 9:13:46 PM (1 occurrences)
Last logged: 9:13:46 PM
> 
> RemoteDevice is deprecated, modify EWeLinkRemote to extend RemoteEntity

**Comment by AlexxIT** [comment]
Fixed in latest master (beta)
