### ISSUE TITLE
Sonoff NS error: could not convert string to float: 'blank'

### ISSUE THREAD

**Issue by Perlnx** [AlexxIT/SonoffLAN#1061]
![Screenshot_20221216_092503](https://user-images.githubusercontent.com/13845123/208247583-d3b0a6da-69be-41e3-8db2-4980d76d5868.png)

![Screenshot_20221217_095313](https://user-images.githubusercontent.com/13845123/208247846-0bbd07e9-f5c9-43ae-b638-6ae636b88581.png)

![Screenshot_20221216_092439](https://user-images.githubusercontent.com/13845123/208247607-ed44808f-8ea4-49a6-bc90-b93c9b9b7ec5.png)

Hello,
This problem occurred since 13 Dec 2022.
I have 24 Sonoff switch in my house, all of them suddenly unavailable every 2-3 minutes.
I tried to swap into Cloud only mode, Lan only mode but It doesn't help. Now I have trouble to control my house since the automation doesn't work when device became unavailable.

My HA system in running on ESXi with Intel NUC this is what I did already.
- Power cycling Router & NUC
- Power cycling my house (to restart every Sonoff device)
- Check WiFi status of router (Asus AX-89X) : It's normal.
- Ping check between NUC and router : Normal, no ping loss.
- Ping check between Router and Sonoff device : Normal, no ping loss.
- Change network adapter of NUC.
- Check status of other WiFi device connected to HA (Tuya platform, Dyson platform): Normal no unavailable every few minutes.

Debug log from HA and Integration has been attach below, Please help.
*Edit* Changed Debug log, You can check from 2022-12-17 22:30 which device "Sonoff NSPanel MBRC" became unavailable

[Debug log from HA & Integration.zip](https://github.com/AlexxIT/SonoffLAN/files/10252094/Debug.log.from.HA.Integration.zip)
[HA log filter at 2230 Log.txt](https://github.com/AlexxIT/SonoffLAN/files/10252095/HA.log.filter.at.2230.Log.txt)

**Comment by Perlnx** [comment]
![Screenshot_20221217_101642](https://user-images.githubusercontent.com/13845123/208248848-5f229c8e-c482-4cf6-a324-f0c557f2c2fe.png)

Compare with other WiFi device in my house since 13 Dec 2022

**Comment by lordwizzard** [comment]
I'm having flaky issues too. I have 8 (S31 Smart Plugs). I have 4 of them running the Loop Timer (alternate). (basically ON for 15min then Off for 15 minutes. Only one is cycling correctly, 3 are not. I have to use the eWeLink Smart home Add-on slug in HA to cycle by clicking on the arrow circle icon that basically pulls the device list again. Then everything updates correctly. Trying to figure out what broke in HA (core/frontend/backend/HACS. This had been working up till the December HA updates which included some "Matter" implementations.

**Comment by Perlnx** [comment]
They are all unavailable every 2:58 or 2:56 min.
I don't know what it is checking every 2:58 min.
But If I tried to block internet access from the router, a problem still occurred.

Pretty sure there are problems from HA since the internet doesn't relate to this.
Now I am seriously thinking about moving all of them to tasmota.


![Screenshot 2022-12-20 032103](https://user-images.githubusercontent.com/13845123/208514073-3ba79f9f-6df0-4fb5-8808-f716b1e6d127.png)

**Comment by lordwizzard** [comment]
I' not sure but, for mine the software is not processing the switch.sonoff.XXXXXXXXXX (EWeLink) into switch.XXXXXXXXXX (AlexxIT/Sonoff LAN) 
![Switch vs Switch_Sonoff_Switch comparison](https://user-images.githubusercontent.com/115957955/208531002-cc351fd9-55d4-4fa4-839c-df9104090f4f.jpg)
for display and usage. I'm not sure if that is a HACS issue from changes there or a frontend issue, because the raw data is correct

**Comment by kingwap99** [comment]
faced the same issue, and got the message as below
"Retrying setup: Cannot connect to host eu-apia.coolkit.cc:443 ssl:default [Try again]"
and finally I found, it's because the gateway of ha not working.

**Comment by Zylazy** [comment]
I have checked the network settings and it is ok. The ip is set to static, but sonoff integartion is very unstable for a long time now.

**Comment by lordwizzard** [comment]
I would check your 2.4 GHz Wifi network out next then.

**Comment by AlexxIT** [comment]
```
{
  "name": "Sonoff NSPanel MBR",
  "deviceid": "100156c8f9",
  "apikey": "***",
  "extra": {
    "uiid": 133,
    "description": "20211109003",
    "brandId": "5c4c1aee3a7d24c7100be054",
    "apmac": "***",
    "mac": "***",
    "ui": "HMI墙面开关",
    "modelInfo": "5f73390defe12b0b619e66d5",
    "model": "E32-MSW-NX",
    "manufacturer": "深圳松诺技术有限公司",
    "chipid": "4417937D1AAC"
  },
  "brandName": "SONOFF",
  "brandLogo": "https://as-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png",
  "showBrand": true,
  "productModel": "NSPanel",
  "tags": {
    "m_b681_perl": "on",
    "ck_channel_name": {
      "0": "Rear",
      "1": "Ceiling"
    }
  },
  "devConfig": {
    "timerCount": "16/16"
  },
  "settings": {
    "opsNotify": 0,
    "opsHistory": 1,
    "alarmNotify": 1,
    "wxAlarmNotify": 0,
    "wxOpsNotify": 0,
    "wxDoorbellNotify": 0,
    "appDoorbellNotify": 1
  },
  "devGroups": [],
  "family": {
    "familyid": "5edb0d104c34480007d39e45",
    "index": 8,
    "members": [],
    "roomid": "5edb0d104c34480007d39e43"
  },
  "shareTo": [],
  "devicekey": "***",
  "online": true,
  "params": {
    "bindInfos": {
      "smartThings": [
        "***"
      ]
    },
    "version": 8,
    "pulses": [
      {
        "pulse": "off",
        "width": 1000,
        "outlet": 0
      },
      {
        "pulse": "off",
        "width": 1000,
        "outlet": 1
      }
    ],
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "off",
        "outlet": 1
      }
    ],
    "configure": [
      {
        "startup": "stay",
        "outlet": 0
      },
      {
        "startup": "stay",
        "outlet": 1
      }
    ],
    "lock": 0,
    "fwVersion": "1.3.1",
    "reset_reason": "ESP_RST_POWERON",
    "value": 1,
    "temperature": 27,
    "humidity": "blank",
    "tempUnit": 0,
    "HMI_outdoorTemp": {
      "current": 26,
      "range": "22,31"
    },
    "HMI_weather": 35,
    "cityId": "***",
    "dst": 0,
    "timeZone": 7,
    "geo": "***",
    "cityStr": "***",
    "tempCorrection": 2,
    "HMI_dimEnable": 1,
    "HMI_dimOpen": 1,
    "HMI_resources": [
      {
        "ctype": "idle"
      },
      {
        "ctype": "idle"
      },
      {
        "ctype": "idle"
      },
      {
        "ctype": "idle"
      },
      {
        "ctype": "idle"
      },
      {
        "ctype": "idle"
      },
      {
        "ctype": "idle"
      },
      {
        "ctype": "idle"
      }
    ]
  },
  "denyFeatures": [
    "bleTempHumidySource",
    "wallpaper"
  ],
  "isSupportGroup": false,
  "isSupportedOnMP": false,
  "deviceFeature": {}
}
```

**Comment by AlexxIT** [comment]
Should be fixed in the latest integration version
