### ISSUE TITLE
NSPanel temperature updates are slow

### ISSUE THREAD

**Issue by HenryJoe666** [AlexxIT/SonoffLAN#1062]
Hi @AlexxIT, do you know if the refresh rate for NSpanel updates can get improved?
its taking forever for the temperature to update, sometimes i can see that the NSPanel screen updates but on HA it goes like from 25°C to 22°C without registering 24°C and 23°C ( in like 5 hours or so it gets only 2 samples, while the device shows the changes going through 24°C and 23°C).
Force update entity doesn´t seem to work on that case.
I know it could be the device limitation, as not showing the decimals could be limitation by the sensor itself, but maybe your integration can request more updates in lets say, 1 hour. it that something that can be done?

Sonoff For LAN latest version
NS Panel Firmware 1.3.1

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#force-update
