### ISSUE TITLE
Automation using a state trigger doesn't fire 

### ISSUE THREAD

**Issue by NeilAdamson** [AlexxIT/SonoffLAN#1064]
HI 
I have an automation set up that should be triggered when the Sonoff POWR2 device becomes unavailable
This means that I have lost power from the grid and I need to then switch off other heavy consumers of power that are attached to an inverter (long story as to why they are connected to the inverter).

The automation is set up as per attached  jpg- but it fails to trigger 

The logs and history shows that the device does become unavailable but for some reason this does not trigger the automation.

Any assistance would be appreciated 

The attached file is for when the POWR2 device is in an off state / I have another automation for when it is in an on state - - I split them out for troubleshooting and simplification purposes - but  none of them trigger.

As you can see the status does change in the HASS log and the device is automated through Google Home - so it can be controlled

Regards
Neil 

![HAS-Automation](https://user-images.githubusercontent.com/72753518/208708741-c7af0cf1-fd0b-4a8c-893e-9b45091b8dfd.jpg)
![HAS-Automation2](https://user-images.githubusercontent.com/72753518/208709481-e8590381-373b-463f-bd35-f2c66f3000bb.jpg)

**Comment by AlexxIT** [comment]
I can see from ON to Unavailable in your triggers. But it is from OFF to Unavailable in your logs.

**Comment by NeilAdamson** [comment]
Yes  - I have two separate automations - for on / off as the state of the POWR2 device could be either on or off at the time the grid loses power - here is the other automation to cater for when the grid loses power and the pool pump is off 
![HAS-Automation3](https://user-images.githubusercontent.com/72753518/208737920-494270ce-2355-4205-8e74-5a3b02814006.jpg)

**Comment by AlexxIT** [comment]
It seems to be a common question about HA, not related to the integration.

**Comment by NeilAdamson** [comment]
> It seems to be a common question about HA, not related to the integration.

Sorry I-  dont understand this comment ?

**Comment by NeilAdamson** [comment]
When I select edit in YAML it seems like there are some differences in the way the expression is defined - with quotes / no quotes and also with no caps on first letter

trigger:
  - platform: state
    entity_id:
      - switch.sonoff_10012d8d3c
    to: Unavailable
    for:
      hours: 0
      minutes: 0
      seconds: 0
    from: "off"
condition: []
action:
  - service: notify.mobile_app_neil_s21
    data:
      message: >-
        Pool pump lost power - could be load shedding - Geyser has been turned
        off
      title: "Pool pump unavailable - could be load shedding "
  - type: turn_off
    device_id: f71280937efe257552c011cfcf601e7f
    entity_id: switch.wifi_smart_timer_meter_socket_1
    domain: switch
mode: single

**Comment by AlexxIT** [comment]
I think you should ask for advice in the Home Assistant community. It does not seem to be an integration issue.

**Comment by NeilAdamson** [comment]
Okay - thanks
