### ISSUE TITLE
Innr Bulb - Showing as ZigbeeWhiteLight Switch

### ISSUE THREAD

**Issue by madtbh** [AlexxIT/SonoffLAN#1075]
I just got a Innr RB 266-3 E27 bulb and it's showing in HA as ZigbeeWhiteLight Switch, not a light. I'm able to toggle it on and off, but no brightness controls.

      "model": "ZigbeeWhiteLight",
      "online": true,
      "localtype": null,
      "deviceid": "a480046bd9"

**Comment by madtbh** [comment]
I've manage to fix the light option via the config, but the brightness controls just turns the bulb either on or off.

**Comment by AlexxIT** [comment]
You need to provide full device diagnostics
