### ISSUE TITLE
lost connection with Sonoff device and update of SonoffLAN is not possible

### ISSUE THREAD

**Issue by schel4ok** [AlexxIT/SonoffLAN#1078]
I use homeassistand in docker and recently I lost connection with my Sonoff device, though it works in eWelink app.

When I do server check I see error
```
Component error: sonoff - cannot import name 'ConfigEntryState' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
```

When I go to HACS I see that SonoffLAN installed version is 2.4.6 and it advices me to update.
![image](https://user-images.githubusercontent.com/10367464/211003945-0655932a-55e7-4e5a-a0be-1a8cd916e002.png)

![image](https://user-images.githubusercontent.com/10367464/211003575-6fff2e6d-98fb-4d9b-ab87-e14b50944ea1.png)

But update seems not possible. I tried to update several times and every time after restart I see the same screen that I still running SonoffLAN 2.4.6. Even if I remove SonoffLAN after restart I see that it is installed.

I tried to update to latest HA image, but it doesn't help me.
![image](https://user-images.githubusercontent.com/10367464/211003298-d0b91ca2-b5ac-4268-a984-05a59cb94ae2.png)

What is the problem?

**Comment by AlexxIT** [comment]
About HACS problems you should ask in HACS repo. You always can download new SonoffLAN version manually

**Comment by marcpaulv** [comment]
This is not about the HACS integrattion, it's about the compatibility with Home Assistant itself.
I was running HA 2021 and started getting this issue, i solved it by upgrading to the latest HA 2023.
