### ISSUE TITLE
Cant add this integration in HACS Settings

### ISSUE THREAD

**Issue by kindberg95** [AlexxIT/SonoffLAN#108]
I try to add this integration in the HACS settings according to the guide. But nothing happends when i press save?

Im using the following
Raspberry pi 3b+
Home Assistant 0.110.1
I dont have any error messages.

**Comment by AlexxIT** [comment]
Screenshot?

**Comment by kindberg95** [comment]
![image](https://user-images.githubusercontent.com/65718722/82574317-30cf3e80-9b87-11ea-9c90-50b5b611ee1f.png)

I dont know if this shows my problem but thats how it looks and nothing happens when i press the save icon.

**Comment by AlexxIT** [comment]
It looks fine. There may be problems with HACS or the Internet on the HA server.
Or with permissions on the custom_components folder.
Try restart raspberry.

**Comment by kindberg95** [comment]
I tried reinstalling both Home assistant and Hacs and rebooting my raspberry pi and still the same problem. :(

**Comment by AlexxIT** [comment]
Do you use venv, docker or hassio?

**Comment by AlexxIT** [comment]
You can always copy sonoff folder to the custom components folder manually. But it will be difficult to get updates

**Comment by kindberg95** [comment]
I got HassOS 3.13.
Yep, ill copy the sonoff folder to the custom components.
Thanks for the help :)
