### ISSUE TITLE
Energy sensor yes or no?

### ISSUE THREAD

**Issue by spanzetta** [AlexxIT/SonoffLAN#1082]
HI,
it seems that the energy sensor exists.. but it gives no data..
Is it "normal" (I mean, maybe it is not implemented) or I am doing something wrong?
Thanks in advance

![1](https://user-images.githubusercontent.com/49818743/212355920-d8a9f383-d4e1-4e93-9a2c-35e16697dfa9.jpg)
![2](https://user-images.githubusercontent.com/49818743/212355939-e7b9719f-1b08-4768-9f68-357d82883dff.jpg)
![3](https://user-images.githubusercontent.com/49818743/212355954-aaf578be-5301-47b1-a4b0-03f6534cb626.jpg)

**Comment by yuz123** [comment]
The same behavior for me. Sonoff POWR320D, firmware 1.0.7

**Comment by spanzetta** [comment]
I "solved" the problem by using the "Riemann sum integral" which apparently works..
I would appreciate anyway if someone confirms that this limitation is "normal"

**Comment by AlexxIT** [comment]
This is not normal. But integration "integration" is better solution anyway.
