### ISSUE TITLE
Sonoff R5 Switchman disconnects after a wile

### ISSUE THREAD

**Issue by bartgabriels** [AlexxIT/SonoffLAN#1083]
Hello,

I have a setup with multiple Switchman M5 switches and 1 R5 Remote Switch. Pairing works fine, R5 switch shows up in HomeAssistant. Automations with the different switches also works, for a while.

After a while, HomeAssistant is not receiving the signals anymore, although the commands are visible in the Ewelink app.

Not really sure how long it takes for the disconnect to happen, but anyway less then 24h. If the integration is reloaded, automations start to work again.

**Comment by AlexxIT** [comment]
You need to collect debug logs

**Comment by bartgabriels** [comment]
Fixed itself. Issue intermittent

**Comment by bartgabriels** [comment]
Fixed itself. Issue intermittent

**Comment by AlexxIT** [comment]
Closed, because no additional debug logs.
