### ISSUE TITLE
No Energy entity for CK-BL602-SWP1-01(182) by coolkit

### ISSUE THREAD

**Issue by nabster82** [AlexxIT/SonoffLAN#1084]
Hi,
First, I would like to say how awesome all entities are working !
I am new on HA. I started with Sonoff as first entities.

All my POWR2 are working perfectly with Energy monitoring, but for ewelink outlets (CK-BL602-SWP1-01(182) by coolkit), no energy entity is present in sensor.

![image](https://user-images.githubusercontent.com/94915679/212495074-7fcee88c-96e0-4ccc-95f5-392f88daa287.png)

Is it possible to add energy statistics to this entity ? Thank you.

**Comment by luca6003** [comment]
Hi @nabster82 
did you solve the problem?

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by nabster82** [comment]
> Hi @nabster82 did you solve the problem?

Not yet :(

**Comment by nabster82** [comment]
> Show device diagnostics

![Screenshot_20230207_085845_Home Assistant](https://user-images.githubusercontent.com/94915679/217185744-ec49fb12-b65d-47bb-8d72-956e231cef38.jpg)

**Comment by nabster82** [comment]
Below the diagnostics.
Sorry for the connection error. I did a quick  screenshot with my VPN down :)

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.1.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "5.10.60-qnap",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "google_home": {
      "version": "1.9.15",
      "requirements": [
        "glocaltokens==0.6.8"
      ]
    },
    "pyscript": {
      "version": "1.3.3",
      "requirements": [
        "croniter==1.3.4",
        "watchdog==2.1.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.3.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "b20e33c",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": false
    },
    "errors": [],
    "device": {
      "uiid": 182,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "demNextFetchTime": 1675634400000,
        "rssi": -34,
        "fwVersion": "1.0.1",
        "switches": [
          {
            "switch": "on",
            "outlet": 0
          },
          {
            "switch": "off",
            "outlet": 1
          },
          {
            "switch": "off",
            "outlet": 2
          },
          {
            "switch": "off",
            "outlet": 3
          }
        ],
        "pulses": [
          {
            "pulse": "off",
            "switch": "off",
            "width": 1000,
            "outlet": 0
          },
          {
            "pulse": "off",
            "switch": "off",
            "width": 1000,
            "outlet": 1
          },
          {
            "pulse": "off",
            "switch": "off",
            "width": 1000,
            "outlet": 2
          },
          {
            "pulse": "off",
            "switch": "off",
            "width": 1000,
            "outlet": 3
          }
        ],
        "sledOnline": "on",
        "configure": [
          {
            "startup": "on",
            "outlet": 0
          },
          {
            "startup": "off",
            "outlet": 1
          },
          {
            "startup": "off",
            "outlet": 2
          },
          {
            "startup": "off",
            "outlet": 3
          }
        ],
        "timeZone": 1,
        "current": "0.13",
        "voltage": "229.71",
        "power": "5.13",
        "alarmVValue": [
          -1,
          -1
        ],
        "alarmCValue": [
          -1,
          -1
        ],
        "alarmPValue": [
          -1,
          -1
        ],
        "alarmType": "pcv",
        "ssid": "***",
        "bssid": "***",
        "staMac": "***",
        "threshold": {
          "current": {
            "min": 0.1,
            "max": 15
          },
          "voltage": {
            "min": 0.1,
            "max": 240
          },
          "minActPow": {
            "min": 0.1,
            "max": 3500
          },
          "maxActPow": {
            "min": 10,
            "max": 3500
          }
        },
        "uiActive": 180,
        "addr": "0080e88c",
        "hundredDaysKwh": "get",
        "oneKwh": "get"
      },
      "model": "CK-BL602-SWP1-01(182)",
      "online": true,
      "localtype": null,
      "deviceid": "1001d45fe1"
    }
  }
}

**Comment by edu24x** [comment]
Hi, I join the petition and provide diagnoses.

Greetings.
[sonoff-571557c22c5f766f4793479bab03adf2-PC-1085df52f25f958a2c4077e9c17bde8c.json.txt](https://github.com/AlexxIT/SonoffLAN/files/10683927/sonoff-571557c22c5f766f4793479bab03adf2-PC-1085df52f25f958a2c4077e9c17bde8c.json.txt)
[config_entry-sonoff-571557c22c5f766f4793479bab03adf2.json.txt](https://github.com/AlexxIT/SonoffLAN/files/10683928/config_entry-sonoff-571557c22c5f766f4793479bab03adf2.json.txt)

**Comment by nabster82** [comment]
Hi,
Any news/progress on this topic ?
Thanks for your help

**Comment by nabster82** [comment]
Hi all,
Anyone could figure out how to add energy entity to this device ?
@AlexxIT could you please help ? You're our master geek :)
Thanks again for all you have already provided..you really rock !

**Comment by AlexxIT** [comment]
Can someone share device with my account? sonofflan@gmail.com

**Comment by edu24x** [comment]
> Can someone share device with my account? [sonofflan@gmail.com](mailto:sonofflan@gmail.com)

Shared!.


[photo_2023-03-30_13-34-31](https://user-images.githubusercontent.com/67578427/228823908-4f78bc88-e47c-4f9c-9e45-7983133ad835.jpg)

**Comment by AlexxIT** [comment]
Added to latest master version. You can download it or wait next release

**Comment by edu24x** [comment]
> Added to latest master version. You can download it or wait next release

Perfect!!!

Thank you very much Alex.

![Sonoff S40](https://user-images.githubusercontent.com/67578427/228856526-a2116832-6f3f-4b30-a63d-c0e42c07774d.png)

**Comment by edu24x** [comment]
- platform: integration
    source: sensor.sonoff_1001d4622f_power
    name: Manta
    unit_prefix: k
    round: 2

**Yes, that's how I had the sensors declared but in this way we avoid the code.**

**Comment by nabster82** [comment]
Thank you so much @AlexxIT !!
You did an amazing work. So nice to know that people like you are here to give a hand to community.
Thank you !

**Comment by pasqualehun** [comment]
> * platform: integration
>   source: sensor.sonoff_1001d4622f_power
>   name: Manta
>   unit_prefix: k
>   round: 2
> 
> **Yes, that's how I had the sensors declared but in this way we avoid the code.**

Just one more thing with this: I've got false integral when there was idle period. To solve this you should add `method: left` to the integration
