### ISSUE TITLE
Sonoff POWR3

### ISSUE THREAD

**Issue by southwalesboy** [AlexxIT/SonoffLAN#1088]
When setting up the Sonoff LAN integration, my devices (Including POWR2) were instantly found and added via UI, I have a POWR3 device also setup on the same eWelink account, but it was not shown? I see from past issues there was support for POWR3 added, but I am confused as to why I am not seeing in from the UI config, is this a bug or is UI not available for POWR3?

**Comment by AlexxIT** [comment]
Maybe you have multiple homes?

**Comment by southwalesboy** [comment]
I have confirmed the POWR3 is in the same home as the working POWR2, I notice in the downloadable diagnostics file, the POWR2 has a whole bunch of information, but the device ID for my POWR3 shows up (I have omitted the last 3 digits) but simply says:
      "100147xxxx": {
        "localtype": "enhanced_plug"

Where as the log for the POWR2 says:
      "1000aexxxx": {
        "uiid": 32,
        "params": {
          "bssid": "***",
          "ssid": "***",
          "only_device": {
            "ota": "success"
          },
          "startTime": "2022-02-04T10:32:49.318Z",
          "endTime": "2022-02-04T10:32:52.931Z",
          "timers": "***",
          "hundredDaysKwh": "get",
          "timeZone": 1,
          "uiActive": 7200,
          "oneKwh": "stop",
          "current": "0.00",
          "voltage": "236.22",
          "power": "0.00",
          "pulseWidth": 500,
          "pulse": "off",
          "startup": "on",
          "switch": "on",
          "alarmPValue": [
            -1,
            -1
          ],
          "alarmCValue": [
            -1,
            -1
          ],
          "alarmVValue": [
            -1,
            -1
          ],
          "alarmType": "pcv",
          "init": 1,
          "rssi": -85,
          "staMac": "***",
          "fwVersion": "3.5.0",
          "sledOnline": "off",
          "version": 8,
          "bindInfos": "***",
          "demNextFetchTime": 1675810800000
        },
        "model": "POWR2",
        "online": false,
        "localtype": null
