### ISSUE TITLE
Can not find in integration

### ISSUE THREAD

**Issue by drk-geek** [AlexxIT/SonoffLAN#109]
I have Home assistant core version 0.110.1 is installed on RPI on venv. I can not find AlexxIT/SonoffLAN integration on HACS version 1.0.0. 
Screen shots are attached
![HACS1](https://user-images.githubusercontent.com/63916817/82595632-5aa45780-9bbf-11ea-9fff-29dcb868dedc.png)
![HACS2](https://user-images.githubusercontent.com/63916817/82595640-61cb6580-9bbf-11ea-8d89-556ec7c8043c.png)
![HACS3](https://user-images.githubusercontent.com/63916817/82595650-65f78300-9bbf-11ea-9122-e69ae34a82f3.png)
![HACS4](https://user-images.githubusercontent.com/63916817/82595656-698b0a00-9bbf-11ea-9d4b-05c2831e423b.png)

**Comment by Gferretta** [comment]
You have to add the "AlexxIT/SonoffLAN" repository here.


![Repository](https://user-images.githubusercontent.com/65413059/82601694-5c055e00-9b86-11ea-842a-a33c5e310a5c.jpg)

**Comment by peterkexas** [comment]
I have Home assistant core version 0.110.1. I can not find AlexxIT/SonoffLAN integration on HACS version 1.0.0.
"GitHub returned 404 for https://api.github.com/repos/AlexxIT/SonoffLAN"
![sonoff alexxit](https://user-images.githubusercontent.com/28904794/82688999-7dd41300-9c62-11ea-9dfd-7c973d5bae23.png)

**Comment by tescophil** [comment]
This updated version of HACS is terrible, causing many problems on my install after update 0.110.1. I deleted it and went back to manually installing add-ons. I would raise this issue on the HACS repo and/or bin it an go old school...

**Comment by GutoFagundes007** [comment]
I have the same problem. Did you find a solution?

**Comment by jgasparelo** [comment]
I have the same problem. Did you find a solution?

**Comment by AlexxIT** [comment]
@peterkexas try latest HACS

I added new howto video about new HACS in readme

**Comment by bobthiel** [comment]
Thanks for the answer in:  https://github.com/AlexxIT/SonoffLAN/issues/109#issuecomment-632319125

**Comment by SPYUK** [comment]
I have same problem on newly added HACS
![image](https://user-images.githubusercontent.com/28460074/100231516-0936a580-2f1f-11eb-8cd3-258fa2d390a0.png)

**Comment by AlexxIT** [comment]
You have a typo
