### ISSUE TITLE
The new POWR316, POWR316D, POWR320D do not work locally 

### ISSUE THREAD

**Issue by wreuvers** [AlexxIT/SonoffLAN#1094]
Hi 

I love the SonoffLAN integration - it is a godsend for controlling everything. Thanks!

When Mode=Local, the new Sonoff POWR316/POWR316D/POWR320D do not toggle, yet they correctly show the state when we manually toggle the switches.
All the other 12 Sonoff switches and devices all work without a problem when Mode=Local

When I chage Mode to Auto, then the POW316/POWR316D/POWR320D all work correctly with toggle.

Thanks
Wayne
[config_entry-sonoff-213b1b89a2f93b16dc8516372ed9beab.json.txt](https://github.com/AlexxIT/SonoffLAN/files/10541807/config_entry-sonoff-213b1b89a2f93b16dc8516372ed9beab.json.txt)

**Comment by ewelink-toac** [comment]
Hi @wreuvers , also loving @AlexxIT Sonoff-LAN integration, but am noticing some anomalies with the these new POWR series  (specifically POWR320D in my case). I have noticed these devices go through stages where the they go "unavailable" randomly while my other Sonoff devices (in same location) remain online. Reason for my post here is that maybe the Sonoff-LAN integration isn't the route cause, but rather the actual device availability? I have read a few blogs moaning about these particular Sonoff devices wifi connection reliability. I know this is not a in direct relation to your query, but maybe it is related. I am considering swapping out the POWR3xx units for the older (more reliable?) units. I am using latest FW1.0.7.

**Comment by wreuvers** [comment]
Yes, they are definitely not as reliable - I see them lose connection fairly often (3 to 4 times per evening). But the toggle issue is very likely an integration issue as when mode=local I can see the state of the switch in home assistant as I change it with the manual button, I just cannot toggle the switch through home assistant unless mode=auto

**Comment by AlexxIT** [comment]
Should be fixed in latest master version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.1
