### ISSUE TITLE
SNZB-02D reports temperature and humidity without decimal separator

### ISSUE THREAD

**Issue by koskila** [AlexxIT/SonoffLAN#1097]
So this is an interesting one... I recently added a SNZB-02D (hygrometer with a screen) and added it to eWelink app. It shows properly there. But when you add it to Home Assistant, it reports humidity and temperature in 100-fold values (100 times the actual value).

This is an interesting approach from Sonoff and I wonder if it'll stick. 

![image](https://user-images.githubusercontent.com/4086860/216546699-228b5a44-4c2e-4f15-bc40-16a225517174.png)

I'm not sure if this can be fixed somewhere else, or if I'd need to modify sensor.py (or somewhere else) to add handling for values reported this way?

Appreciate your insights.

**Comment by koskila** [comment]
Just to add some more screenshots - the values are pretty wild, but I think they're consistent with just being 100-fold (it's Winter and the room that the sensor is in has no dedicated heating as it's not in use now - so 15.2 C is within reason).

![image](https://user-images.githubusercontent.com/4086860/216547638-3daa2648-6f0f-4b76-9ce8-027580c991d2.png)

![image](https://user-images.githubusercontent.com/4086860/216547735-a0e715b4-a22e-4b09-bf3c-9f54a61748b8.png)

**Comment by AlexxIT** [comment]
Please show device diagnostics

**Comment by koskila** [comment]
[sonoff-30def58928d022964d930a412d6963e4-hygroview_mari-707563f02812c08c656b63bdcc625567.json.txt](https://github.com/AlexxIT/SonoffLAN/files/10579039/sonoff-30def58928d022964d930a412d6963e4-hygroview_mari-707563f02812c08c656b63bdcc625567.json.txt)

[config_entry-sonoff-30def58928d022964d930a412d6963e4.json (1).txt](https://github.com/AlexxIT/SonoffLAN/files/10579055/config_entry-sonoff-30def58928d022964d930a412d6963e4.json.1.txt)

**Comment by AlexxIT** [comment]
Fixed in the latest master version #1150
Will be in next release

**Comment by koskila** [comment]
@AlexxIT awesome work, mate. Appreciate it!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.1
