### ISSUE TITLE
Can't send switch to

### ISSUE THREAD

**Issue by dawiduniec** [AlexxIT/SonoffLAN#11]
Hello,

I can see the state of the devices, but when I'm trying to switch on/off any I'm getting this:

2020-02-14 07:01:54 DEBUG (SyncWorker_13) [custom_components.sonoff] Send switch to 3030a05abf: {'sequence': '1581660114', 'deviceid': '3030a05abf', 'selfApikey': '123', 'data': '2UA9Ie507+HgJVuOfCc2tLQa/x3DBnxzgnidsb9e1eo=', 'encrypt': True, 'iv': 'XvZFLmaIc2scA3ULzhKp2Q=='}
2020-02-14 07:01:57 WARNING (SyncWorker_13) [custom_components.sonoff] Can't send switch to 3030a05abf

(I've changed the Id's/data/iv)

**Comment by AlexxIT** [comment]
Sometimes devices stop receiving commands. You can either wait or reboot the device.

**Comment by dawiduniec** [comment]
I have around 13 sonoff devices, and none is working.

**Comment by AlexxIT** [comment]
Very strange. `Can't send switch to` appears with all devices?

**Comment by dawiduniec** [comment]
Yes it did appear to all, but I've tested today, and it's working now.

**Comment by dawiduniec** [comment]
Sorry, i retested status, sending commands still give me same issue.

**Comment by AlexxIT** [comment]
Are all 13 devices causing problems?

**Comment by dawiduniec** [comment]
No, 3 of them worked.

**Comment by AlexxIT** [comment]
Do all the other 10 cause an "Can't send switch" error for every toggle?

**Comment by dawiduniec** [comment]
Yes, they are

wt., 25 lut 2020 o 19:38 Alex X <notifications@github.com> napisał(a):

**Comment by dawiduniec** [comment]
It's really wired, now when I'm trying multiple times, some of them are working time to time

**Comment by dawiduniec** [comment]
It's getting even more weird. Now after I play 15 minutes with them, almost every work.

**Comment by dawiduniec** [comment]
Now all switches work

**Comment by LennyLip** [comment]
Same here. I think it's related to a LAN mode. When I enabled LAN mode in eWeLink and trying multiple times on\off it's starting to work.

**Comment by AlexxIT** [comment]
LAN mode in eWeLink app works only with 2nd device firmware!

**Comment by LennyLip** [comment]
> LAN mode in eWeLink app works only with 2nd device firmware!

And so? Switching to LAN mod:
![so2](https://user-images.githubusercontent.com/955994/77062818-ab47da80-69ed-11ea-8b71-52ad4ffc0899.jpg)
 =>
![so1](https://user-images.githubusercontent.com/955994/77062824-aedb6180-69ed-11ea-9a8f-0ee82db15e52.jpg)

**Comment by ha14937** [comment]
Looks like I'm having the same issue, but only with 1 of my 3 Sonoff switches.
~~~
WARNING (MainThread) [custom_components.sonoff] Can't send switch to 1000ad7978
~~~

**Comment by AlexxIT** [comment]
Try new version #99
