### ISSUE TITLE
New Update WARNING

### ISSUE THREAD

**Issue by milandzuris** [AlexxIT/SonoffLAN#1106]
after new update every device stop working, logs clear
![image](https://user-images.githubusercontent.com/42905545/216867188-d7c67cc2-ba88-4286-9f84-7acd1e1993cd.png)

**Comment by AlexxIT** [comment]
Well. Nothing useful if you not provide more info

**Comment by vlaryn** [comment]
I am having same issue

**Comment by milandzuris** [comment]
LOGS CLEAR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! YOU KNOW

**Comment by BaseCampLab** [comment]
Same Issue as well

**Comment by fotis3d** [comment]
I also face the same

**Comment by barto64** [comment]
Same issue in here. I had to rollback to previous version. I look the logs and nothing indicates an error.

**Comment by AlexxIT** [comment]
None of you have attached diagnostics and debug logs
https://github.com/AlexxIT/SonoffLAN#issues

**Comment by barto64** [comment]
You are right, apologies. At work now, late in the day when at home will try to troubleshoot the issue and provide you as much info as I can.

**Comment by bax137** [comment]
I posted a message in this issue: https://github.com/AlexxIT/SonoffLAN/issues/1108#issuecomment-1422297688
but it seems that this is the same issue as here.

**Comment by Spp595** [comment]
> Same issue in here. I had to rollback to previous version. I look the logs and nothing indicates an error.

How can I roll back to the previous version?

**Comment by barto64** [comment]
This is what i have been able to see when activating DEBUG for 3 different devices just before they become disabled in HA. Not sure if it helps. There is not any ERROR. After they become disabled they stop appearing in the list of what seems to be a polling to all the devices every minute or so. It looks like some sort of  validation of the communication failed and the device were marked as offline and forgotten afterwards.

Device 1:
======
2023-02-08 20:39:44.351 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10006ca1e3 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 20:40:59.609 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10006ca1e3 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 20:41:07.743 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 10006ca1e3 <= Local0 | {'online': False} | 
2023-02-08 20:41:18.235 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10006ca1e3 => Local4 | {'cmd': 'info'} !! Timeout 10
2023-02-08 20:41:18.235 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 10006ca1e3 !! Local4 | Device offline

Device 2:
======
2023-02-08 21:11:15.368 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10005ca789 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 21:12:30.420 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10005ca789 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 21:13:44.845 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10005ca789 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 21:13:58.051 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 10005ca789 <= Local0 | {'online': False} | 
2023-02-08 21:14:08.249 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10005ca789 => Local4 | {'cmd': 'info'} !! Timeout 10
2023-02-08 21:14:08.249 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 10005ca789 !! Local4 | Device offline

Device 3:
======
2023-02-08 21:09:59.598 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 1000b90c39 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 21:11:15.390 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 1000b90c39 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 21:12:29.682 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 1000b90c39 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 21:13:44.578 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 1000b90c39 => Local4 | {'cmd': 'info'} <= info: 200
2023-02-08 21:13:58.050 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 1000b90c39 <= Local0 | {'online': False} | 
2023-02-08 21:14:08.240 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 1000b90c39 => Local4 | {'cmd': 'info'} !! Timeout 10
2023-02-08 21:14:08.241 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 1000b90c39 !! Local4 | Device offline

**Comment by dbullendsl** [comment]
Same issue Sonoff IFan04 goes off line after unknown time. Reload of integration gets it going again but eventually it drops.

**Comment by jawn22** [comment]
Same issue here

**Comment by dmspils** [comment]
Same issue, logs look exactly the same so no point in posting. I have to reload also to get it working again.

**Comment by ChrisB85** [comment]
I also had this problem. Downgrading to version 3.3.1 resolved it.

**Comment by Tamsy** [comment]
Similar issues with all my Sonoff POW R2: While those are correctly detected by the integration/HA all readings like Current, Power and Voltage read 0 with v.3.4.0. Reloading the integration doesn't help. Rolled back to v.3.3.1 and all issues were solved.

**Comment by heidricha** [comment]
Would be nice to use one issue for the device unavailable issue, instead of three (minimum)...

Still interested if you guys use fixed IP address for the devices, or not? For me, downgrade didn't help, but setting a fixed IP in the router seems to. I need more time to test, but it looks definitely better now.

**Comment by barto64** [comment]
All my Sonoff devices have fixed Ip and the last update of the integration killed them all.

**Comment by heidricha** [comment]
> All my Sonoff devices have fixed Ip and the last update of the integration killed them all.

yep... I also got disconnection with fixed IP too, with integration version 3.3.1 (downgraded). It is true, that I didn't have this with 3.3.1 BEFORE I upgraded to 3.4

**Comment by kamilparczewski** [comment]
Go to `config/integrations` click `configure` for sonoff, select your home and save. Thats helped me

**Comment by fotis3d** [comment]
> Go to `config/integrations` click `configure` for sonoff, select your home and save. That helped me

Can you please confirm that in 2-3 days ? Cause I do not see why would that help. It was not checked and worked fine before as it is now at the old release. Thanks :)

**Comment by heidricha** [comment]
> 

I cannot select home there..

**Comment by Tamsy** [comment]
> > 
> 
> I cannot select home there..

The poster *might* mean "My Home"


![myhome](https://user-images.githubusercontent.com/6210614/218957882-368ad5a4-6df9-4a80-8392-38f6be0182e5.jpg)

**Comment by heidricha** [comment]
Thanks but...



Tamsy ***@***.***> ezt írta (időpont: 2023. febr. 15., Sze
8:14):

**Comment by davidolrik** [comment]
> Go to `config/integrations` click `configure` for sonoff, select your home and save. That helped me

This also worked for me.

**Comment by heidricha** [comment]
> > Go to `config/integrations` click `configure` for sonoff, select your home and save. That helped me
> 
> This also worked for me.

still don't have any options to select there

does anyone knows how to reset device data? looks like the integration doesn't connect to the cloud, nor it refresh device data locally. It works for a while somehow, then the device goes offline. Sometimes just one of them, but usually both of them.

devices already run fw version 3.6, but in HA they are still ion 3.5.1. 
in the logs there is a cache mentioned, looks like the integration gets the data from some stored data in the homeassistant environment, and doesn't connect the cloud or the devices themselves.

**Comment by barto64** [comment]
The option to click "My Home" does NOT even appear in my HA, only the header appears.

**Comment by heidricha** [comment]
> The option to click "My Home" does NOT even appear in my HA, only the header appears.

I finally tried to remove the integration. It didn't get removed but removed the previous configuration with the outdated device info, and possibly bad cloud-config.
Also initialized the cloud access again from the config.yaml, and updated the device data too.
Now I have got the default home, and I could check it

Now waiting for the long-term effect...

**Comment by Masterz69** [comment]
Reg. device disappearing mentioned in https://github.com/AlexxIT/SonoffLAN/issues/1106#issuecomment-1423203426

3.4.0. have different zeroconf browser, which claim device as locally offline as soon received ZC REMOVED state change.
But this is wrong idea. Cause ZC remove device after some time device NOT sending any data.
And every SONOFF switches behave that - NOT sending any data unless operated manually or by Cloud or locally.

See my small test in https://github.com/AlexxIT/SonoffLAN/issues/1112#issuecomment-1436067690

You can see history of ADDED/REMOVED events by ZC browser on different machine (not HA server).
Only devices 1000cf7638 & 1000f3e195 was actually unpowered.

All other state changes actually NOT reflect devices availability - they all the time was locally online.
Unfortunately periodic ```check_offline``` call in ```run_forever``` does not help. 
ZC, as I see in my test, only react on data sent FROM device, not answers on info command.

**Comment by Masterz69** [comment]
```
2023-02-08 21:13:58.051 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 10005ca789 <= Local0 | {'online': False} |
2023-02-08 21:14:08.249 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.local] 10005ca789 => Local4 | {'cmd': 'info'} !! Timeout 10
```

^^ that is staff, can't understand for now.
After new ZC browser (3.4.0.) receive ZC REMOVED state change, it looks do same staff as in 3.3.1.
But device actually stops responding to info requests from integration, to ```wget``` from console, to ON/OFF commands.
And local mode will NOT recover till integration restart (at least in my case - https://github.com/AlexxIT/SonoffLAN/issues/1112#issuecomment-1436033587).

**Comment by Masterz69** [comment]
PR https://github.com/AlexxIT/SonoffLAN/pull/1116 created with some ideas for @AlexxIT to deal with "False local offline" issue.

So far it works fine in my HA - no devices falling out. Tried also disconnect Internet - see no issues.

**Comment by thefunkygibbon** [comment]
I too am expericing this (or very similar).  I'm having to 'reload' the plugin every morning else none of my sonoff sockets work

**Comment by georgepauna** [comment]
> Go to `config/integrations` click `configure` for sonoff, select your home and save. That helped me

This!

My devices were "unavailable" for few seconds/minutes few times each hour. After doing this, 0 disconnects so far (almost 2 hours)

**Comment by Tamsy** [comment]
> PR #1116 created with some ideas for @AlexxIT to deal with "False local offline" issue.
> 
> So far it works fine in my HA - no devices falling out. Tried also disconnect Internet - see no issues.

Tested with your patches for the last 24 hours and can confirm: No devices falling out, no issues so far.

**Comment by thefunkygibbon** [comment]
I changed mine yesterday to "select my home" in the plugin options, but i still woke today to a bunch of non-responding smart plugs.  :-(

**Comment by AlexxIT** [comment]
@barto64 same problem like here #1126
Should work better after v3.5.0
But you wouldn't have this problem at all in mode auto

**Comment by AlexxIT** [comment]
I haven't saw any debug info from author, so closing issue

**Comment by AlexxIT** [comment]
@barto64 Homes list loaded at the moment when you open Options window. Maybe you have some cloud issues at that moment.

**Comment by AlexxIT** [comment]
PR #1116 from @Masterz69 very helpful and should fix LAN problems.
But anyway it's better always use auto mode (cloud+local).
Because Sonoff devices sometimes stop responding on LAN requests.

**Comment by thefunkygibbon** [comment]
> 

Dude. Just because this is the first time you've looked at these posts in the past few months and it's pretty overwhelming with the amount of problems people are having.  It's a bit harshe to start dismissing everything.
