### ISSUE TITLE
V3.4.0 has lost connectivity to all my Sonoff devices

### ISSUE THREAD

**Issue by CraigBoswell** [AlexxIT/SonoffLAN#1110]
I tried to update Sonoff to 3.4.0 this evening, as well as from HACS 1.29.0 to 1.30.1. I was running HAOS 9.4  and Core 2023.1.2.
On succesfull reboot all other integrations were fine, but Sonoff-LAN integration not updating, even after a re-load. When looking at an entity details, there is a warning "This entity is no longer being provided by sonoff integration. If the entity is no longer in use, delete it in settings."
![image](https://user-images.githubusercontent.com/121049470/218586345-a8e6332d-7158-4c55-a027-ec9532e11784.png)

I then tried updating HAOS to latest (9.5) and Core to latest (2023.2.4). No change was found, even after complete OS shutdown and reload of Sonoff-LAN.

I have now rolled back to a previous backup from a day ago, yet the Same Sonoff error persists.
[230214 00h21config_entry-sonoff-3c6681e36723697e1817beacce156b2a.json (auto).txt](https://github.com/AlexxIT/SonoffLAN/files/10726795/230214.00h21config_entry-sonoff-3c6681e36723697e1817beacce156b2a.json.auto.txt)
This is still with Sonoff-LAN integration in "Auto Mode", Local Mode gives same result.

DESPERATELY looking for help, as unfortunately half my house now runs on HA primarily using Sonoff-LAN integration.

**UPDATE - RESOLVED (KIND OF)**: 
After fiddling with modes a few times, and changing to cloud, then back to Auto, miraculously all points are working again. Unfortunately, I'm now too nervous to upgrade to V3.4.0 again, so will wait for more feedback on the upgrade version.

**Comment by heidricha** [comment]
Do you thing it is different of this one: https://github.com/AlexxIT/SonoffLAN/issues/1108

Many suffers the same issue, refreshing the configuration usually helps. For a while at least.

**Comment by thefunkygibbon** [comment]
hey all, a great workaround since this issue doesn't appear to be being worked on,  is to create an automation to monitor a sonoff device and restart the service automatically.  its not a perfect solution but hopefully it should make the devices work for "most" of the time. 
https://github.com/AlexxIT/SonoffLAN/issues/1138#issuecomment-1478580171

**Comment by AlexxIT** [comment]
@CraigBoswell you have a lot unknown local devices.
This can happen if you use different ewelink accounts. Or if you are using different homes in the ewelink application.
Devices can be shared between accounts. And the home can be specified in the integration settings
