### ISSUE TITLE
New Sonoff POW Origin (POW R2 'new' version)

### ISSUE THREAD

**Issue by gabrymed** [AlexxIT/SonoffLAN#1115]
Itead launched new version of Sonoff POW R2 called Sonoff POW Origin. Also the link of Sonoff POW R2 in Tested Devices list leads to the new POW Origin.
Is this new device tested with SonoffLAN ?
Thanks in advance for your work

**Comment by AlexxIT** [comment]
Looks like they put new device to the old link. I don't think there will be any problems with the support.
I don't think there will be any problems with the support.
If the device has new firmware, you will need to add support. It's not hard, just a matter of free time.
