### ISSUE TITLE
Enhancement: Native DIY Support with no eweLink

### ISSUE THREAD

**Issue by camsaway** [AlexxIT/SonoffLAN#1118]
Request enhancement to support devices without ever connecting to ewelink cloud.

Proposed Approach
1) Manually Place device into DIY mode and set WLAN
2) Manually add the device to SonoffLAN via config (or better yet auto-discovery)

This would allow for the new range of DIY mode devices to never have to be added to ewelink cloud. Flashing ESPHome is not an alternative approach as they are now using BL602 chips instead of ESP chips in a number of their devices.

**Comment by AlexxIT** [comment]
I don't plan to do this. DIY mode doesn't work well. Local mode is very much tied to the zeroconf protocol, which has huge stability problems.

Sonoff devices work best when connected to eWeLink servers and integration in auto mode (local+cloud). Or flashing in ESPHome.

If that doesn't suit you, you need to look for an alternative to ESPHome.
