### ISSUE TITLE
Error EWeLinkRemote

### ISSUE THREAD

**Issue by camui-alexandru** [AlexxIT/SonoffLAN#112]
Log Details (WARNING)
Logger: homeassistant.components.remote
Source: components/remote/__init__.py:162
Integration: La distanţă (documentation, issues)
First occurred: 10:55:50 (1 occurrences)
Last logged: 10:55:50

RemoteDevice is deprecated, modify EWeLinkRemote to extend RemoteEntity

**Comment by AlexxIT** [comment]
#106
