### ISSUE TITLE
Sonoff RF bridge multiple remotes support

### ISSUE THREAD

**Issue by DuckyNZ** [AlexxIT/SonoffLAN#113]
First of all, thanks very much Alex for developing this integration. I can now integerate my sonoff RF bridge to HA. 

The only issue is I have a few RF remote buttons (learned in eWeLink app) but only the buttons from the first one seems to work in HA. The buttons from second remote is not recognised by HA eventhough I've given them unique names. In below example, only buttons from the remote "Speaker" is recognised but not the buttons from "BedroomLight" remote.

Would be great if I can use multiple remotes in HA.

Many thanks,

William

![Screenshot_20200523-122400_eWeLink](https://user-images.githubusercontent.com/33687725/82717540-cdf9b680-9cf0-11ea-8be2-7da3a598fa67.jpg)

**Comment by AlexxIT** [comment]
Any buttons should work. There are not limitations.

**Comment by tjhiwa** [comment]
I experienced this, too. In my case, I had a remote, then few alarms, then a remote, the more alarms.
Those alarms after the 2nd remote would not work properly. specifying the ID also wouldn't work correctly. it would listen to different alarm instead. After each restart (load always), the previously working alarm (after 2nd remote) would not work again, seemingly incorrectly pointing to other alarm.
I resolved it by removing the 2nd remote. 
I can live without the 2nd remote as they aren't essential.

**Comment by AlexxIT** [comment]
Please share Bridge to my ewelink account sonofflan@gmail.com

**Comment by tjhiwa** [comment]
> Please share Bridge to my ewelink account [sonofflan@gmail.com](mailto:sonofflan@gmail.com)

what's your country code? it says failed to share when using my country code.

**Comment by AlexxIT** [comment]
Russia +7

**Comment by tjhiwa** [comment]
![Screenshot_20200526-204742~01](https://user-images.githubusercontent.com/64679755/82903136-19cb8a80-9f93-11ea-8a6e-2e4d18d277d8.png)

**Comment by AlexxIT** [comment]
I checked same situation. All works fine.
Please send your sonoff.json file to my mail. You can hide private data.

![download-2](https://user-images.githubusercontent.com/511909/83128143-a8e7b800-a0e3-11ea-94a0-97ea4ec944a2.png)

**Comment by DuckyNZ** [comment]
Sorry, doesn't work for me. Only the buttons on first remote works.

**Comment by tjhiwa** [comment]
@AlexxIT , try this to replica problem:
1. Add one remote (4 buttons), pair 4 of them (remote1, button1, button2, button3, button4)
2. Add 6 alarms, pair all 6 (alarm1,alarm2,alarm3,alarm4,alarm5,alarm6)
3. Add one remote (4 buttons), pair only 1 button, let 3 buttons unpaired (remote2, button5)
4. Add 5 alarms, pair first 2 only and last one, leaving 3rd and 4th unpaired (alarm7, alarm8, alarm9)

If problem is replicated, alarms7, alarm8 and alarm9 will be received incorrectly, randomly with each HA restart. Using LAN mode, reload always.

**Comment by DuckyNZ** [comment]
All my remotes started to work all of a sudden. I have tried 3 RF sockets
and all remotes working now. I don't remember doing anything they just
started working.

Thanks.

**Comment by AlexxIT** [comment]
@tjhiwa I'll check your situation

**Comment by AlexxIT** [comment]
@tjhiwa I don't have so many RF button to lear so many buttons and alarms. Could you send sonoff.json to my email? You can hide private data.

**Comment by AlexxIT** [comment]
@tjhiwa did you send `sonoff.json` to my mail? Maybe I missed it.

**Comment by AlexxIT** [comment]
No answer. Reopen issue if the problem is still actual
