### ISSUE TITLE
Feature request: THR 316D auto refresh

### ISSUE THREAD

**Issue by MayBankCH** [AlexxIT/SonoffLAN#1133]
When refresh is clicked, THR will send real time data to Home Assistant for about 1.5 min. then stop sending for a while. 
Is it possible to having a refresh switch or real time data.
![image](https://user-images.githubusercontent.com/82813803/223455652-f7ecd5f3-fa43-4a33-984c-19a3befceccc.png)
![image](https://user-images.githubusercontent.com/82813803/223455963-7680b3b5-02ff-4024-962c-54350b95c534.png)

**Comment by skaffff** [comment]
same issue here https://github.com/AlexxIT/SonoffLAN/issues/1130
