### ISSUE TITLE
UNKNOWN cloud msg: {'action': 'subDevice'

### ISSUE THREAD

**Issue by drzoidberg33** [AlexxIT/SonoffLAN#1139]
I am trying to set up a few SONOFF SNZB-02 temp/humidity sensors connected via a SONOFF ZB Bridge. When I first got them I was able to add it via my cloud account and it allowed me to configure all the device and the 3 sensors.

Then I did a firmware update on the bridge to 1.7.0 and it looks like maybe after that things went south and my sensors were no longer updating (similar reports here: https://github.com/AlexxIT/SonoffLAN/issues/1046)

When trying to completely reinstall the integration, it would no longer allow me to see or configure the devices.

Here is the diagnostic:

```
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.3.1",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Africa/Johannesburg",
    "os_name": "Linux",
    "os_version": "5.4.0-144-generic",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "load_shedding": {
      "version": "1.2.0",
      "requirements": [
        "load_shedding==0.11.5"
      ]
    },
    "localtuya": {
      "version": "5.0.0",
      "requirements": []
    },
    "olarm_sensors": {
      "version": "0.1.1",
      "requirements": [
        "requests"
      ]
    },
    "sonoff": {
      "version": "3.4.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "/api/sonoff/ba69c693-d22f-4476-a13d-d7e7dd84e2f3",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.4.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "5406fa7",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": true
    },
    "errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "UNKNOWN cloud msg: {'action': 'subDevice', 'deviceid': '***', 'apikey': '***', 'userAgent': 'device', 'd_seq': 29759, 'params': {'cmds': [{'type': 0, 'subDevId': '***', 'uiid': '1770', 'deviceid': '***'}]}}",
          "UNKNOWN cloud msg: {'action': 'subDevice', 'deviceid': '***', 'apikey': '***', 'userAgent': 'device', 'd_seq': 29680, 'params': {'cmds': [{'type': 0, 'subDevId': '***', 'uiid': '1770', 'deviceid': '***'}]}}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          357
        ],
        "timestamp": 1679044951.4295893,
        "exception": "",
        "count": 2,
        "first_occurred": 1679044756.4469762
      }
    ],
    "devices": {}
  }
}
```

It seems to be receiving a new action called "subDevice" which isn't being handled here in this function: https://github.com/AlexxIT/SonoffLAN/blob/453cbed2dfa2fb94a0d9e007310673b1423e4063/custom_components/sonoff/core/ewelink/cloud.py#L330-L357

As a quick test I just created a new case for the "subDevice" action like so:

```
        elif data["action"] == "subDevice":
            self.dispatcher_send(SIGNAL_UPDATE, data)
```

After reloading HA, I'm now able to configure the devices again - not yet sure if they're updating correctly though. This probably isn't the correct call for this but it was a shot in the dark as I am completely unfamiliar with this code.

**Comment by drzoidberg33** [comment]
Been monitoring my hack over the weekend and it seems to be updating correctly, although I'm still unsure if my change is the correct one though.

**Comment by AlexxIT** [comment]
You don't have any devices in your diagnostics. You need to find out why.
Integration support this model. "UNKNOWN cloud msg" just info messages not affect to anything.

**Comment by drzoidberg33** [comment]
Yep, I suspect there are no devices listed because it wouldn't add them for some reason.

I removed my lines of code and restarted HA and will monitor and check that everything still works as expected.

Thanks for the work on this integration!
