### ISSUE TITLE
What of there are two ALARM sensors?

### ISSUE THREAD

**Issue by snug-inglenook** [AlexxIT/SonoffLAN#114]

**Comment by snug-inglenook** [comment]
I have two water alarm sensors connected to the RF bridge. What is a command to distinguish the two?
event_data:
      name: Alarm (???)
And now what (name in eweling Basement and Laundry.

Any hints> Thank you

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#sonoff-rf-bridge-433

> Entity RF Buttons or RF Sensors are not created automatically!

**Comment by snug-inglenook** [comment]
Alex this is a bit of answer without an answer. I seem to not know how to
proceed in this situation. I couldn't find any information on how to
implement 2 alarms. I have them both working with ewelink and don't know
what would be a command line in HA.
If not automatically then I presume manually. How?

**Comment by maciak** [comment]
Hi,
You need to distinguish them by name in ewelink app
for me it's
event_data:
  name: Motion sensor

**Comment by snug-inglenook** [comment]
I get that, but in eWelink you have the following remote names: 1-button,
2, 3, 4, Curtain and Alarm
I have two Alarms connected here (water sensors). they have different
names, Alarm Laundry, Alarm Basement (that's how i named them), both work
work with the app
so in the command line I have
trigger:
  - event_data:
      event_data:
        name: Alarm Basement
    event_type: sonoff.remote
    platform: event

the thing is how do I distinguish them in HA bec. now when one is
triggered, it triggers two automations that are set up separately.

OR perhaps the word Alarm should not be used here, just a name - basement
of laundry.
Beats me.

**Comment by maciak** [comment]
My automation is triggered like this and I use full name from the app.

event_data:
  event_data:
    name: Door Sensor
event_type: sonoff.remote
platform: event

Works independently for any sensor I've got.

Try to look in states for remote.sonoff it will show you the name of the current triggered alarm.

**Comment by snug-inglenook** [comment]
I take it that you have different names for different sensors (like Door
Sensor). If so,  then it looks identical to what I have. No idea what is
the problem.

**Comment by tjhiwa** [comment]
> I have two water alarm sensors connected to the RF bridge. What is a command to distinguish the two?
> event_data:
> name: Alarm (???)
> And now what (name in eweling Basement and Laundry.
> 
> Any hints> Thank you

- alias: Store ON/OFF
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      name: Store
  action:
    service: switch.toggle
    entity_id: switch.sonoff_store

**Comment by AlexxIT** [comment]
@snug-inglenook please show logs https://youtu.be/Lt5fT4N5Pm8

**Comment by snug-inglenook** [comment]
2020-05-28 17:12:27  DEBUG    main          SysInfo: {'version':
'0.110.3', 'dev': False, 'hassio': False, 'virtualenv': False,
'python_version': '3.7.7', 'docker': True, 'arch': 'x86_64',
'os_name': 'Linux', 'os_version': '5.4.0-31-generic'}
2020-05-28 17:12:27  DEBUG    main          LOCAL mode start
2020-05-28 17:12:29  ERROR    sonoff_cloud  Login error: {'error':
400, 'msg': 'params is error'}
2020-05-28 17:12:29  WARNING  main          Can't connect to eWeLink Cloud
2020-05-28 17:12:29  DEBUG    sonoff_local  1000a8f1a3 <= Local1 |
{'sledOnline': 'off', 'arming': True, 'rfTrig0':
'2020-05-28T21:10:18.000Z'}
2020-05-28 17:12:29  DEBUG    main          1000a8f1a3 == Init   |
{'uiid': 28, 'extra': {'manufacturer': 'SONOFF', 'model': 'RFBridge',
'sw_version': 'PSF-BRA-GL v3.4.0'}, 'params': {'sledOnline': 'off',
'arming': True, 'rfTrig0': '2020-05-28T21:10:18.000Z', 'local':
'online'}}
2020-05-28 17:12:29  DEBUG    sonoff_local  100080e35b <= Local1 |
{'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline':
'on', 'pulseWidth': 500, 'rssi': -71}
2020-05-28 17:12:29  DEBUG    main          100080e35b == Init   |
{'uiid': 1, 'extra': {'manufacturer': 'coolkit', 'model': '0185',
'sw_version': 'PSF-B01-GL v3.4.0'}, 'params': {'switch': 'off',
'startup': 'off', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth':
500, 'rssi': -71, 'local': 'online'}}
2020-05-28 17:13:05  DEBUG    sonoff_local  100080e35b => Local4 |
{'switch': 'on'} <= {'seq': 356, 'sequence': '1590700385409', 'error':
0}
2020-05-28 17:13:05  DEBUG    sonoff_local  100080e35b <= Local3 |
{'switch': 'on', 'startup': 'off', 'pulse': 'off', 'sledOnline': 'on',
'pulseWidth': 500, 'rssi': -71}
2020-05-28 17:13:10  DEBUG    sonoff_local  100080e35b => Local4 |
{'switch': 'off'} <= {'seq': 357, 'sequence': '1590700390173',
'error': 0}
2020-05-28 17:13:10  DEBUG    sonoff_local  100080e35b <= Local3 |
{'switch': 'off', 'startup': 'off', 'pulse': 'off', 'sledOnline':
'on', 'pulseWidth': 500, 'rssi': -71}
2020-05-28 17:13:15  DEBUG    sonoff_local  1000a8f1a3 <= Local3 |
{'sledOnline': 'off', 'arming': True, 'rfTrig0':
'2020-05-28T21:13:15.000Z'}
2020-05-28 17:13:15  DEBUG    remote        Fire event sonoff.remote:
{'command': 0, 'ts': '2020-05-28T21:13:15.000Z', 'name': 'My Remote',
'entity_id': 'remote.sonoff_1000a8f1a3'}
2020-05-28 17:13:17  DEBUG    sonoff_local  1000a8f1a3 <= Local3 |
{'sledOnline': 'off', 'arming': True, 'rfTrig0':
'2020-05-28T21:13:17.000Z'}
2020-05-28 17:13:17  DEBUG    remote        Fire event sonoff.remote:
{'command': 0, 'ts': '2020-05-28T21:13:17.000Z', 'name': 'My Remote',
'entity_id': 'remote.sonoff_1000a8f1a3'}
2020-05-28 17:13:23  DEBUG    sonoff_local  1000a8f1a3 <= Local3 |
{'sledOnline': 'off', 'arming': True, 'rfTrig0':
'2020-05-28T21:13:23.000Z'}
2020-05-28 17:13:23  DEBUG    remote        Fire event sonoff.remote:
{'command': 0, 'ts': '2020-05-28T21:13:23.000Z', 'name': 'My Remote',
'entity_id': 'remote.sonoff_1000a8f1a3'}

**Comment by AlexxIT** [comment]
@snug-inglenook I see 3 signals from first sensor. No other signals.

**Comment by snug-inglenook** [comment]
That's right, I didn't trigger it. I think what you see is this:
remote.sonoff_1000a8f1a3.
I can check the other one in the later time. Meanwhile could you please
write the correct commands for this one, then I can fill it in with the
other one in later time.
THis is what I have now, but I'm not sure if this is correct:
trigger:
  - event_data:
      event_data:
        name: Alarm
        entity_id: remote.sonoff_1000a8f1a3
    event_type: sonoff.remote
    platform: event

Alex, thank you for your help!!

**Comment by AlexxIT** [comment]
@snug-inglenook check new examples in readme:
https://github.com/AlexxIT/SonoffLAN#sonoff-rf-bridge-433

**Comment by snug-inglenook** [comment]
trigger:
  - event_data:
      command: 1
    event_type: sonoff.remote
    platform: event

trigger:
  - event_data:
      command: 0
    event_type: sonoff.remote
    platform: event
This is tested and working perfectly.
Thanks Alex and everyone!
