### ISSUE TITLE
Sonoff SNZB-02D temp and humidity sensor shows up as some kind of clock

### ISSUE THREAD

**Issue by edwoody** [AlexxIT/SonoffLAN#1145]
Sonoff SNZB-02D shows up on ewelink app as temp and humidity sensor with temp and humidity, but now in HomeAssistant.  Shows up as a clock I think.  It's there, just no temperature or humidity information.

**Comment by AlexxIT** [comment]
I don't understand what you wrote.

**Comment by edwoody** [comment]
Hi Alex.  Sorry for the confusion.  I can’t set values in homeassistant.  Usually there are tempearature and humidity values.   I’m not sure what the colors mean here.  The temp and humidity values show in the ewelink app.  But this is all I get from homeassistant.  I have a clock icon on the left?   Also, the “changed to March” part I don’t know.   Thanks for your time.     Sent from Mail for Windows From: Alex XSent: Monday, March 27, 2023 11:08 AMTo: AlexxIT/SonoffLANCc: edwoody; AuthorSubject: Re: [AlexxIT/SonoffLAN] Sonoff SNZB-02D temp and humidity sensor shows up as some kind of clock (Issue #1145) I don't understand what you wrote.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> Virus-free.www.avast.com

**Comment by AlexxIT** [comment]
I don't think your messages related to this integration. There is no any colors or clocks.
