### ISSUE TITLE
All devices not in lan?

### ISSUE THREAD

**Issue by Piipz** [AlexxIT/SonoffLAN#1148]
Hi, I recently started using the Sonofflan.

If  this is the wrong place to post this question, then please help to point out where it should go.
So far I used Ewelink directly, meaning that all my devices are in Ewelink cloud.
Then I set up a home assistant, but used Ewelinks own integration, which didn't work very well.
Now I moved over to Sonofflan, and it works well, but I have some questions.

I have around 30 devices all around the house.
I want to be able to control all of them via home-assistant in local mode.

How do I make sure that all my devices are in local mode?

Here is the list of devices that I have.
SONOFF ZBBridge
17 x Temp/humid sensor SNZB-02 (zigbee)
6  x SONOFF S26 R2ZB (zigbee)
2 x Plug S26R1 (wifi)
Plug S26R2 (wifi)
Switch BASICR2 (wifi)
Bulb (B02) (wifi) (yes, I know,  cloud only)

Here is what HASS system integration tells me:
![image](https://user-images.githubusercontent.com/127694714/227935598-3e92d958-0d78-4a7d-8fc9-3c3f29003a80.png)

Why only 5 of them are local and the rest cloud?
Is it because the Zigbee bridge and the Zigbee plugs / sensors are cloud only?

I would want all of them be also local in case there is no cloud connection.

Would it help, if i ditch the Zigbee bridge and use a ZBDongle-P connected to my raspberry directly?

Any kind of help is appreciated :)

**Comment by AlexxIT** [comment]
You have not read the documentation carefully. Everything about zigbee is only through the cloud. All questions to the creators of these devices. Integration can't do anything about it.

https://github.com/AlexxIT/SonoffLAN#tested-devices
