### ISSUE TITLE
Switching in groups no longer works

### ISSUE THREAD

**Issue by tescophil** [AlexxIT/SonoffLAN#115]
HASSIO on Pi running 1.110.1 and the SonoffLAN master Branch.

Context : Cloud Control (my switches are on a different subnet to my HASSIO install, so LAN control does not work)

Problem: Toggling multiple switches via a home assistant Group no longer works. Previous versions worked fine.

Model : Sonoff T1 3C sw version PSF-B04-GL v3.4.0

With this integration I would expect to see 4 entities for this switch consisting of three individual switches plus a master switch which toggles them all at the same time. With this integration only the three switches are exposed (I see 4 switches in my google home integration).

So, I had these three switches in a Home Assistant group, then just turned the group on/off which switched all the lights no problem. With the current version of the master branch this no longer works. Only one of the three switches will be toggled, and the others remain in their initial state. The integration believes that all three switches were toggled, and this never updates/changes to the correct state despite the eWeLink App showing the switch in the correct switch state.

**Comment by AlexxIT** [comment]
What version worked fine? Another master? Or previosly you used only LAN control version?

**Comment by AlexxIT** [comment]
You can config Sonoff T1 3C as single light with brigthness control. If it suits you.

**Comment by tescophil** [comment]
Previous version of the master worked with no issues. How do you configure the 3C as a single switch ?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#custom-device_class-for-any-mode
```
sonoff:
  devices:
    1000abcdef:
      device_class:
      - light: [1, 2, 3]
```

**Comment by tescophil** [comment]
Perfect, your a star !

Thanks for all your help and work on this project.
