### ISSUE TITLE
SNZB-02D

### ISSUE THREAD

**Issue by edwoody** [AlexxIT/SonoffLAN#1150]
re:#1145  
![image](https://user-images.githubusercontent.com/44067243/228054306-ec691e05-9b26-4daa-89b1-0b50b40143ab.png)

**Comment by AlexxIT** [comment]
Show device page screen

**Comment by AlexxIT** [comment]
Please attach device diagnostics (download button on your screen).

**Comment by edwoody** [comment]
"home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.3.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "armv7l",
    "timezone": "America/New_York",
    "os_name": "Linux",
    "os_version": "5.15.84-v7",
    "supervisor": "2023.03.2",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.4.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hacs": {
      "version": "1.31.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.4.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "5406fa7",
    "cloud_auth": true,
    "config": {
      "username": "***",
      "password": "***",
      "scan_interval": 60,
      "grace_period": 600
    },
    "options": {
      "mode": "auto",
      "debug": false
    },
    "errors": [],
    "device": {
      "uiid": 1771,
      "params": {
        "subDevId": "81bd74feff10fb301770",
        "parentid": "10013d919a",
        "fwVersion": "1.0.9",
        "tempComfortLower": "1900",
        "humiComfortLower": "4000",
        "ASYNC": 2,
        "temperature": "2290",
        "tempComfortStatus": 0,
        "humidity": "5630",
        "humiComfortStatus": 0,
        "tempComfortUpper": "2700",
        "tempUnit": 1,
        "humiComfortUpper": "6000",
        "timeZone": -4,
        "trigTime": "1679534559960",
        "key": 0,
        "battery": 100,
        "supportPowConfig": 1
      },
      "model": "SNZB-02D",
      "online": true,
      "localtype": null,
      "host": null,
      "deviceid": "a440018a3c"
    }
  }
}

**Comment by pitykeee** [comment]
Hi! I have the same problem with SNZB-02D in HomeAssistant. I have two older SNZB-02, thats works fine.
Thanks for your help and work!
[sonoff-7650298e2c2eb9f47b7ab7e3d6ee97dd-SNZB-02D-b036f86c513c1e6fece8f0f57dd85b5c.json (1).txt](https://github.com/AlexxIT/SonoffLAN/files/11100290/sonoff-7650298e2c2eb9f47b7ab7e3d6ee97dd-SNZB-02D-b036f86c513c1e6fece8f0f57dd85b5c.json.1.txt)

**Comment by AlexxIT** [comment]
This device don't supported. Will be in next release

**Comment by edwoody** [comment]
Thanks Alex.   Sent from Mail for Windows From: Alex XSent: Thursday, March 30, 2023 3:50 AMTo: AlexxIT/SonoffLANCc: edwoody; State changeSubject: Re: [AlexxIT/SonoffLAN] SNZB-02D (Issue #1150) This device don't supported. Will be in next release—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***> Virus-free.www.avast.com

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.1

**Comment by wcambris** [comment]
First, thank you for the amazing work and time you're putting into making our life easier. 
I have two SNZB-02B installed on two separate SONOFF zigbee hubs. 
One is working perfectly well, the other shows ## minutes ago. 
Everything in my home assistant is up to date. 
Thank you, hope it might help.
