### ISSUE TITLE
Duplicate and not working controls for RFR3 devices

### ISSUE THREAD

**Issue by solnitza** [AlexxIT/SonoffLAN#1156]
Hello.
Since the last update, 3.5.1, my RFR3 devices are not working anymore. Every device has a duplicate control that is not working (like in the attached image).
<img width="511" alt="Fără titlu" src="https://user-images.githubusercontent.com/37184826/229311483-0e271deb-4c78-42d4-8689-39f0e13e9e04.png">

I think the problem is related to the issue #1136 that was resolved with this update. For my RFR3, the API uses http://IP:8081/zeroconf/switch (not switches).

Another thing that I noticed is that all of my RFR3 devices are detected as MINI DIY (this is before the update) and that may count, except for one of them which is BASICRF_R3 (can't tell why) (see second image). This one is working and it was not affected by the update.
<img width="833" alt="Fără titlu2" src="https://user-images.githubusercontent.com/37184826/229311871-14527d5e-8eb3-48b5-96c7-4aa93f2099fe.png">

If logs are necessary, please guide me to find them. Although I enabled Debug logging, I don't know where to find the integration logs.

Thank you.

**Comment by Smosia** [comment]
Looks like i have the same issue with basic r3 wifi switch in diy mode.

**Comment by Smosia** [comment]
my debug log
```
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.12.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Moscow",
    "os_name": "Linux",
    "os_version": "5.10.0-10-amd64",
    "supervisor": "2023.03.3",
    "host_os": "Debian GNU/Linux 11 (bullseye)",
    "docker_version": "20.10.21",
    "chassis": "desktop",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.5.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "6935784",
    "cloud_auth": false,
    "config": {
      "devices": {
        "100136e348": {
          "name": "Sonoff BR3_348"
        },
        "100136dc18": {
          "name": "Sonoff BR3_c18"
        }
      }
    },
    "options": {
      "mode": "local",
      "debug": false
    },
    "errors": [],
    "device": {
      "uiid": 1,
      "params": {
        "switch": "on",
        "startup": "off",
        "pulse": "off",
        "sledOnline": "on",
        "fwVersion": "3.6.0",
        "pulseWidth": 500,
        "rssi": -58
      },
      "model": "MINI DIY",
      "online": null,
      "local": true,
      "localtype": "diy_plug",
      "host": "192.168.1.162:8081",
      "deviceid": "100136dc18"
    }
  }
}
```

**Comment by AlexxIT** [comment]
Fixed

**Comment by Smosia** [comment]
Update to master. Everything works. Sonoff Basic R3 wifi relay. 
Thank you

**Comment by solnitza** [comment]
Can someone guide me on how to test the fix, please? Updating the integration in HACS to 3.5.1 leads to the same issue. Thanks.

**Comment by ashirchkov** [comment]
> Update to master. Everything works. Sonoff Basic R3 wifi relay. Thank you

I confirm that the bug has been fixed in the master branch

**Comment by Smosia** [comment]
> Can someone guide me on how to test the fix, please? Updating the integration in HACS to 3.5.1 leads to the same issue. Thanks.

You need to click on sonofflan in hacs, then click three dots in right top corner and  reinstall beta master version.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.2

**Comment by kingwap99** [comment]
would be faced the same issue  on sonoff s31

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.7.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Asia/Taipei",
    "os_name": "Linux",
    "os_version": "6.1.34",
    "supervisor": "2023.07.1",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "notify_line": {
      "version": "2022.7.1",
      "requirements": []
    },
    "zhimi": {
      "version": "1.0.1",
      "requirements": [
        "miservice>=2.0.1"
      ]
    },
    "line_notify": {
      "version": "1.0.1",
      "requirements": []
    },
    "dohome": {
      "version": "0.2.0",
      "requirements": []
    },
    "sonoff": {
      "version": "3.5.2",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "yeelight_pro": {
      "version": "0.0.1",
      "requirements": []
    },
    "webrtc": {
      "version": "v3.2.1",
      "requirements": []
    },
    "xiaomi_miio_cooker": {
      "version": "2023.6.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "hello_miai": {
      "version": "1.0.0",
      "requirements": []
    },
    "yeelight_bt": {
      "version": "1.3.0",
      "requirements": [
        "bleak>=0.18.0",
        "bleak-retry-connector>=2.1.3"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.10",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "frigate": {
      "version": "4.0.0",
      "requirements": [
        "pytz==2022.7"
      ]
    },
    "xiaomi_gateway3": {
      "version": "3.3.2",
      "requirements": [
        "zigpy>=0.44.1"
      ]
    },
    "nodered": {
      "version": "2.1.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tapo_control": {
      "version": "5.1.0",
      "requirements": [
        "pytapo==3.1.12"
      ]
    },
    "aqara_gateway": {
      "version": "0.0.14",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "xiaomi_miio_fan": {
      "version": "2023.7.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "var": {
      "version": "0.15.0",
      "requirements": []
    },
    "xiaomi_miio_raw": {
      "version": "2023.6.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "/api/sonoff/705781f7-d8b2-46a7-82f9-08a7f4e46ffe",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.2",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "2ad1cd7",
    "cloud_auth": false,
    "config": {
      "username": "***",
      "password": "***",
      "force_update": [
        "temperature",
        "humidity",
        "power",
        "switch",
        "remote"
      ],
      "scan_interval": "00:00:10",
      "debug": false
    },
    "options": {
      "mode": "auto",
      "debug": true
    },
    "errors": [],
    "device": {
      "uiid": 32,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "only_device": {
          "ota": "success"
        },
        "sledOnline": "on",
        "ssid": "***",
        "bssid": "***",
        "fwVersion": "3.6.0",
        "staMac": "***",
        "rssi": -28,
        "init": 1,
        "alarmType": "pcv",
        "alarmVValue": [
          -1,
          -1
        ],
        "alarmCValue": [
          -1,
          -1
        ],
        "alarmPValue": [
          -1,
          -1
        ],
        "switch": "on",
        "startup": "on",
        "pulse": "off",
        "pulseWidth": 500,
        "power": "10.37",
        "voltage": "111.16",
        "current": "0.17",
        "oneKwh": "stop",
        "uiActive": 60,
        "timeZone": 8,
        "hundredDaysKwh": "get",
        "demNextFetchTime": 1690473600000,
        "rstReason": 0,
        "exccause": 0,
        "epc1": 0,
        "epc2": 0,
        "epc3": 0,
        "excvaddr": 0,
        "depc": 0
      },
      "model": "S31TPB(US)",
      "online": true,
      "local": true,
      "localtype": "enhanced_plug",
      "host": "192.168.31.182:8081",
      "deviceid": "10016f32ee"
    }
  }
}
