### ISSUE TITLE
Feature Request: Subnet scanning / IP configuration

### ISSUE THREAD

**Issue by tescophil** [AlexxIT/SonoffLAN#116]
I would like to configure the integration the scan specific sub-nets for switches AND/OR specify the IP address of individual switches.

Why, because I have my Sonoff switches on a different subnet to my HA (eg. HA on 192.168.1.0/24 and Sonoff devices on 192.168.2.0/24), so currently LAN control does not function. (cloud control works fine)

Great work this BTW ;-)

**Comment by AlexxIT** [comment]
HA server is in both subnets?
I do not know how to pass multicast traffic between different subnets:
https://en.wikipedia.org/wiki/Multicast_DNS

**Comment by tescophil** [comment]
No, just one subnet. Didn't realise they were using multicast for Comms. The switches are reachable from the network that the HA server is on via a local gateway, but I guess if they are multicasting their data it's not going to work across subnets.

**Comment by sneakythr0ws** [comment]
@tescophil Hi! Did you fix it?
