### ISSUE TITLE
SNZB-02D still not working in 3.5.1

### ISSUE THREAD

**Issue by m-toso** [AlexxIT/SonoffLAN#1166]
Home Assistant 2023.4.4 (container), SonoffLAN integration 3.5.1 .
My SNZB-02D shows up as in https://github.com/AlexxIT/SonoffLAN/issues/1145 and https://github.com/AlexxIT/SonoffLAN/issues/1150
I also tried on a fresh install of HA, same problem.

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by m-toso** [comment]
`{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.4.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "4.4.180+",
    "run_as_root": true
  },
  "custom_components": {
    "tapo": {
      "version": "1.6.1",
      "requirements": [
        "plugp100==2.5.1"
      ]
    },
    "sonoff": {
      "version": "3.5.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "pun_sensor": {
      "version": "0.3.3",
      "requirements": [
        "holidays",
        "bs4"
      ]
    },
    "meross_lan": {
      "version": "3.0.3",
      "requirements": []
    },
    "tapo_control": {
      "version": "4.2.1",
      "requirements": [
        "pytapo==3.1.7",
        "onvif-zeep-async==1.2.3"
      ]
    },
    "ecowitt": {
      "version": "0.7",
      "requirements": [
        "pyecowitt==0.14"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "122751c",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": false
    },
    "errors": [],
    "device": {
      "uiid": 7014,
      "params": {
        "subDevId": "fe946efeff10fbxxxxxx",
        "parentid": "10017axxxx",
        "fwVersion": "1.0.9",
        "battery": 100,
        "trigTime": "1681702319000",
        "supportPowConfig": 1,
        "tempUnit": 0,
        "tempComfortLower": "1900",
        "tempComfortUpper": "2700",
        "humiComfortLower": "4000",
        "humiComfortUpper": "6000",
        "temperature": "1790",
        "ASYNC": 2,
        "tempComfortStatus": 1,
        "humidity": "5050",
        "humiComfortStatus": 0,
        "timeZone": 2
      },
      "model": "SNZB-02D",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "a48005xxxx"
    }
  }
} `

**Comment by m-toso** [comment]
```
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.4.4",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "4.4.180+",
    "run_as_root": true
  },
  "custom_components": {
    "tapo": {
      "version": "1.6.1",
      "requirements": [
        "plugp100==2.5.1"
      ]
    },
    "sonoff": {
      "version": "3.5.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "pun_sensor": {
      "version": "0.3.3",
      "requirements": [
        "holidays",
        "bs4"
      ]
    },
    "meross_lan": {
      "version": "3.0.3",
      "requirements": []
    },
    "tapo_control": {
      "version": "4.2.1",
      "requirements": [
        "pytapo==3.1.7",
        "onvif-zeep-async==1.2.3"
      ]
    },
    "ecowitt": {
      "version": "0.7",
      "requirements": [
        "pyecowitt==0.14"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "122751c",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": false
    },
    "errors": [],
    "device": {
      "uiid": 7014,
      "params": {
        "subDevId": "fe946efeff10fb307014",
        "parentid": "10017ae779",
        "fwVersion": "1.0.9",
        "battery": 100,
        "trigTime": "1681702319000",
        "supportPowConfig": 1,
        "tempUnit": 0,
        "tempComfortLower": "1900",
        "tempComfortUpper": "2700",
        "humiComfortLower": "4000",
        "humiComfortUpper": "6000",
        "temperature": "1790",
        "ASYNC": 2,
        "tempComfortStatus": 1,
        "humidity": "5050",
        "humiComfortStatus": 0,
        "timeZone": 2
      },
      "model": "SNZB-02D",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "a480052937"
    }
  }
}
```

**Comment by m-toso** [comment]
<img width="1019" alt="Schermata 2023-04-17 alle 06 11 52" src="https://user-images.githubusercontent.com/48298884/232376183-de030ab4-7ca0-471b-b8cc-9465ff202944.png">

**Comment by AlexxIT** [comment]
Thanks. New UIID for your sensor. Will fix it

**Comment by m-toso** [comment]
How can I change UIID?
And why in a fresh HA installation it still doesn't work?
Thank you.

**Comment by AlexxIT** [comment]
Should be fixed in master version

**Comment by m-toso** [comment]
Thank you!

**Comment by evilpl** [comment]
Is support for SNZB-02D already added? Because for me this sensor is not working properly.
![image](https://github.com/AlexxIT/SonoffLAN/assets/58123004/3042e49d-0258-4aac-b3bb-f91f5d85c506)
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.6.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Warsaw",
    "os_name": "Linux",
    "os_version": "6.1.34",
    "supervisor": "2023.06.4",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "version": "3.5.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.1",
    "iot_class": "local_push",
    "is_built_in": false
  },`

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.2
