### ISSUE TITLE
Sonoff mini doesn't work after update V3.5.1

### ISSUE THREAD

**Issue by Dynamix72** [AlexxIT/SonoffLAN#1167]
My sonoff mini in local mode did work with version V3.4.0, but after the update to version V3.5.1 the device is unavailable.
If I do a rollback towards version v3.4.0, then the sonoff mini works correctly.

Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 10.0
Frontend-versie: 20230411.1 - latest

**Comment by sipimokus** [comment]
Try with master branch, see diff: https://github.com/AlexxIT/SonoffLAN/compare/v3.5.1...master

**Comment by Dynamix72** [comment]
Master branch works.

**Comment by sarus3749** [comment]
Hello.
I have the same issue I guess. By reading other issues it seems to be a common problem.
How can I try with the master branch ? I did not see any option to choose it during integration.
Thank's

**Comment by sipimokus** [comment]
@sarus3749 like this: https://github.com/AlexxIT/SonoffLAN/issues/1164#issuecomment-1513563149

**Comment by sarus3749** [comment]
oh thank you @sipimokus  ! I did not think of that.

**Comment by caco3** [comment]
I can confirm this issue. 3.4 was the last version which worked with my in DIY mode. After an upgrade to a89296d it works again.

Big thanks to all the developers!
