### ISSUE TITLE
Sonoff SPM Switches change device_class

### ISSUE THREAD

**Issue by thomasfowler** [AlexxIT/SonoffLAN#1178]
In my `configuration.yml` I have my `default_class` set to `light`, as I primarily have Sonoff light switches. However, I also have a SPF controlling and monitoring some devices in my household.

I would like to configure the switches on the SPM to come through as entities with the device_class `switch` rather than `light`.

Each of the light entities has the following entity_id on the SPM Sub-board:

1.  `light.sonoff_ab30000101_1`
2. `light.sonoff_ab30000101_2`
3. `light.sonoff_ab30000101_3`
4. `light.sonoff_ab30000101_4`

As per the docs, in order to set the `device_class` in the `configuration.yml` "DeviceID is always 10 symbols string from entity_id or eWeLink app."

So, if I set the config as follows:

```yaml
devices:
  ab30000101:
    device_class: switch
```

Only the first switch is now a switch entity with id `switch.sonoff_ab30000101_1`. The remaining 3 are still `light` entities with the ids noted above.

And if I use, for example, `ab30000101_1`, it is ignored.

How do I configure the integration such that all 4 entities device_class is `switch`?

**Comment by sipimokus** [comment]
@thomasfowler I don't use this function, but here is a description for multi channel devices, please check the readme: https://github.com/AlexxIT/SonoffLAN#custom-device_class
<img width="898" alt="image" src="https://user-images.githubusercontent.com/1633489/236788149-c67942d2-d362-442f-8483-e8ed2eca1f1e.png">

**Comment by thomasfowler** [comment]
Thanks for pointing that out. Not sure how I missed it in the docs....

For those who come across this, this was my solution that got it working:

```yaml
devices:
  ab30000101:
      device_class: [switch, switch, switch, switch]
```
