### ISSUE TITLE
Change email/password information

### ISSUE THREAD

**Issue by leoheitor** [AlexxIT/SonoffLAN#1179]
Hi Alexx & contributors.

I started automation in my house using my personal email and now I noticed that I have more that 100 devices, most part of them Sonoff. I already created lot of automation in homeassistant. I was wondering to change my email from xxxxx@gmail,com to automation@leonardohome.com, into ewelink app (change email address option) and after that, update sonoff integration in homeassistant setup. I did´t find where I can update email and password information without interfering in existing devices, entities and automation. 

Would be intresting to have something like LocalTuya integration where we find into "configure", an option "Reconfigure Cloud API Account" to update email/password/other info.

Do you have a procedure to change email/password without affect defined entrances?

PS: My system is running latest sw releases.

Kind Regards,
Leonardo

**Comment by leoheitor** [comment]
Would be intresting to have something like LocalTuya integration where we find into "configure", an option "Reconfigure Cloud API Account" to update email/password/other info.

**Comment by Eskander** [comment]
I had a similar situation and fixed it this way: Keep the old integration in Home Assistant and add another Sonoff integration with the new credentials. It'll show a "Re-authentication successful" dialog without duplicating the integration or the devices. My automations also still work. Do a backup and see if it works for you.

**Comment by Eskander** [comment]
I had a similar situation and fixed it this way: Keep the old integration in Home Assistant and add another Sonoff integration with the new credentials. It'll show a "Re-authentication successful" dialog without duplicating the integration or the devices. My automations also still work. Do a backup and see if it works for you.

**Comment by AlexxIT** [comment]
`/config/.storage/core.config_entries`

**Comment by leoheitor** [comment]
Hi Eskander, good morning.
I tried your method, but no success. Old email config was not migrated for new one. 

AlexxIT, 
It worked changing the email and password into this file! 

For both, tks!

**Comment by yingyann** [comment]
Hello, I'm in the same process as I will sell my house. so to transfer account I have 
- created a new ewelink account for the buyer.
- add the devices in this new account
- all devices have the same IDs as before but a different name
My questions are:
1- should I first change the account/password in ? : /config/.storage/core.config_entries

2- then I will have double devices in HA?

**Comment by AlexxIT** [comment]
You won't have double devices because deviceid will be same

**Comment by yingyann** [comment]
> You won't have double devices because deviceid will be same

Thank you very much Alex :-) 
About SONOFFLAN, should I change th password and username only in configuration .yaml?
sonoff:
  username: xxxx
  password: xxxx

or I just reinstall SONOFFLAN ?
thank you :-)

**Comment by AlexxIT** [comment]
Better to change user/pass in the `/config/.storage/core.config_entries`. Because all devices will be deleted if you reinstall integration
