### ISSUE TITLE
Support Mini R4

### ISSUE THREAD

**Issue by CaTeIM** [AlexxIT/SonoffLAN#1182]
Can you add Mini R4?

**Comment by CaTeIM** [comment]
Sorry, I see now that it's already in testing.

**Comment by irsl** [comment]
Is it working fine? I'm about to buy one and it is not among the tested devices on the front page.

**Comment by CaTeIM** [comment]
Yeah! Everything is ok!

Atenciosamente,

Gustavo Cateim
Cel.: +55 (28) 99991-9444


Em qua., 17 de jul. de 2024 às 17:10, irsl ***@***.***>
escreveu:
