### ISSUE TITLE
Sonoff MINIR4 does work

### ISSUE THREAD

**Issue by pascalsaul** [AlexxIT/SonoffLAN#1184]
The Sonoff MINIR4 does work also. Only DIY mode is not there (anymore).

![image](https://github.com/AlexxIT/SonoffLAN/assets/659660/7d8bf47d-0a9d-466a-a24b-11aad620b2ff)

https://sonoff.tech/product/diy-smart-switches/minir4/

**Comment by Opontios** [comment]
Sure it works as a switch. But what about it's detached mode? Would be great if i was implemented also.

**Comment by Sfernandox** [comment]
It would be interesting to implement the detach relay function, It's the best of this relay

**Comment by trimtechnology** [comment]
Does it also work in local mode (without cloud) or is this "cloud-only" variant? Not able to find any information about DYI mode and MINIR4. Thanks for any info

**Comment by AlexxIT** [comment]
You need to give a more detailed description of the problem than just "it doesn't work"

**Comment by dijiflex** [comment]
> Does it also work in local mode (without cloud) or is this "cloud-only" variant? Not able to find any information about DYI mode and MINIR4. Thanks for any info

Did you confirm if it is working locally with the internet?

**Comment by trimtechnology** [comment]
> > Does it also work in local mode (without cloud) or is this "cloud-only" variant? Not able to find any information about DYI mode and MINIR4. Thanks for any info
> 
> Did you confirm if it is working locally with the internet?

No, I was not able to make it work in local mode (without cloud). Standard procedure to enably DYI mode and read apikeys does not work anymore.

**Comment by wishie** [comment]
I am also really interested in the 'detached mode' setting of this device.. so I assume this setting is NOT exposed to Home Assistant?

Am I understanding correctly that this MINIR4 does also NOT support LAN Control?

**Comment by pascalsaul** [comment]
> I am also really interested in the 'detached mode' setting of this device.. so I assume this setting is NOT exposed to Home Assistant?
> 
> Am I understanding correctly that this MINIR4 does also NOT support LAN Control?

It does have LAN control. At least that is enabled on the device.

**Comment by wishie** [comment]
Ok, so LAN Control works, "Detach Mode" is a toggle in the eWeLink app, right?

So if it is set in the eWeLink app, is HA still able to control it? The holy grail would obviously be if you were able to enable/disable "Detach Mode" from within HA, but I assume that's what isn't currently (or ever going to?) working

**Comment by pascalsaul** [comment]
> Ok, so LAN Control works, "Detach Mode" is a toggle in the eWeLink app, right?
> 
> So if it is set in the eWeLink app, is HA still able to control it? The holy grail would obviously be if you were able to enable/disable "Detach Mode" from within HA, but I assume that's what isn't currently (or ever going to?) working

Not sure for other mini versions but that option is not available in HA nor eWelink

**Comment by dennislopes** [comment]
Hi guys!

I have a plenty of minir4 in my house and today after a internet outage I was not able to control my switches from the LAN. Lan Control did not work, on the original firmware,  when Internet is not available. If I could help on troubleshooting that, please let me know and I will do my best.

thanks!

**Comment by wishie** [comment]
> Hi guys!
> 
> I have a plenty of minir4 in my house and today after a internet outage I was not able to control my switches from the LAN. Lan Control did not work, on the original firmware, when Internet is not available. If I could help on troubleshooting that, please let me know and I will do my best.
> 
> thanks!

Can you confirm if 'Detach Relay' is an option in eWeLink app for the MINIR4? Also, is that option exposed to HA? Can you control the 'switch' and the 'relay' independent of each other?

**Comment by wishie** [comment]
Ok, so my MINIR4 switches arrived today, and I have installed 1 so far. Here is what I have figured out.

Once added in the eWeLink app, you can go and enable "Detach Relay" and then restart the SonoffLAN integration.. you will get a new (disabled by default) entity called 'Detach'. This is the external switch connected to the MINIR4. You can use this new entity in automations etc and it will work, **BUT... Toggling the external switch does NOT update the state of that entity in HA.**.

If I go into the eWeLink app and make a 'scene' to send a push notification whenever the external switch is triggered, that works. So it appears that eWeLink app sees the toggling of the external switch, but HA does not.. so is this a bug?

**Comment by wishie** [comment]
So I have just noticed something.. the 'Detach' entity in HA is actually toggling the 'Detach Relay Mode' setting in eWeLink.. so it has nothing to do with the external switch.

So it would appear the external switch is not being 'exported' to HA

Is this fixable?

**Comment by Geheim49** [comment]
I just installed almost 10 devices as wel, and just noticed this.

[sonoff-ab196d12d09ef2d5decbaee51418e600-Woonkamer-4ac0c5d42f3ba56657224b17e102cfa7.json.txt](https://github.com/AlexxIT/SonoffLAN/files/12408752/sonoff-ab196d12d09ef2d5decbaee51418e600-Woonkamer-4ac0c5d42f3ba56657224b17e102cfa7.json.txt)

**Comment by Geheim49** [comment]
![Screenshot_20230822_145849_eWeLink](https://github.com/AlexxIT/SonoffLAN/assets/1252531/4c219d98-be57-415d-af21-98b916bf11b0)

This how it looks when you make a scene with detach relay. But I don't see it at the device itself in the EwLink app. Only the on/off button that switches the relay is visable.

**Comment by wishie** [comment]
The device is aware of when the detached switch is triggered though, as it can be used in eWeLink scenes.

**Comment by wishie** [comment]
That's exactly my point. We can toggle the relay, and toggle the 'detach relay mode' setting, but can not currently toggle the 'external switch'. I really hope that is able to be exposed to HA, as that opens up a lot of possibilities.

I also noticed in the eWeLink app, it says if the MINIR4 drops off the network, it automatically 'reattaches' the relay.

**Comment by VoyteckPL** [comment]
That would be ultra useful for smart bulbs.

**Comment by asierralozano** [comment]
> That's exactly my point. We can toggle the relay, and toggle the 'detach relay mode' setting, but can not currently toggle the 'external switch'. I really hope that is able to be exposed to HA, as that opens up a lot of possibilities.
> 
> I also noticed in the eWeLink app, it says if the MINIR4 drops off the network, it automatically 'reattaches' the relay.

I'm thinking about buying a MiniR4, and by reading your comment, I assume that the MiniR4 exposes a switch, referencing the external switch into the Ewelink App. Am I correct?
And for sure, I get your point. This entity should be exposed into HA if it is exposed into the EwelinkApp, because for smart bulb scenarios, being able to create automations based on the external switch toggle is a nice feature.

**Comment by brin007** [comment]
The detached mode does work. I have had these installed behind light switches in my house controlling smart bulbs, hence the need for a detached mode. 

Took me a while to figure out but i did it in the end.

Although the detached mode is in the controls section to use it you need to activate it as a sensor. 

<img width="234" alt="Screenshot 2023-11-23 152642" src="https://github.com/AlexxIT/SonoffLAN/assets/120916423/14d14195-454b-4553-aa30-a27855515b7d">

**Comment by az82** [comment]
As @brin007 mentioned the detached mode works, but only with a cloud connection, not locally. The relay itself also works with only a local connection. Local only detached mode would be really nice.

**Comment by AlexxIT** [comment]
My bad. This issue was just info about device is working. Thanks!

**Comment by lennartwoermer** [comment]
Has anyone managed to achieve this yet or are people working on it? I have also bought the MINIR4M but faced this issue.

**Comment by ivmirand** [comment]
I just reached the same point, works as a cloud enabled sensor, but not locally.
