### ISSUE TITLE
I have a Sonoff Camera GK-200MP2-B.   The integration creates an entity as a sensor not as a camera.   any thoughts?  Thanks

### ISSUE THREAD

**Issue by briveland1** [AlexxIT/SonoffLAN#1186]

**Comment by atlaspl** [comment]
As i can read in the description of the repository it seems that currently only PTZ commands are supported. Camera entity is not created now.
Maybe in the next update.....I hope

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#sonoff-gk-200mp2-b-camera
