### ISSUE TITLE
Refresh of Sonoff devices causes immediate toggling of power state

### ISSUE THREAD

**Issue by tonyp740613** [AlexxIT/SonoffLAN#119]
I applied version 2.01 of sonofflan component running on 0.109.6 of Home Assistant.  

The refresh of Sonoff devices works very well.  However when I call service switch.toggle, switch.turn_on or switch.turn_off it returns to the previous state immediately, eg. if the switch is on and you want to switch it off, it switches off and then immediately on again.  The logbook shows that the switch was turned off and then turned on again.

If I comment the force_update option then the switch functions properly.

I attached the debug log:
[sonofflan_debug.txt](https://github.com/AlexxIT/SonoffLAN/files/4681478/sonofflan_debug.txt)

I ran into the same problem when I was setting up automations to refresh the data before your update.  I had to schedule the automations so that the refresh didn't happen at the exact same time as the actual switch_on of the device or else it would just toggle the state immediately.

eg. When turning on a switch at 4:00pm I had to schedule the automation to send the switch_on command for info refresh at 4:01pm

**Comment by AlexxIT** [comment]
I knew that sending a command is a bad idea and will lead to this problem :)
Please check if any of this commands force state update for your device:
`signal_strength, info, wifi, switch, switches, pulse, startup`

![download](https://user-images.githubusercontent.com/511909/82895918-b7a46280-9f5d-11ea-96ed-57852533eb36.png)

**Comment by tonyp740613** [comment]
sonoff,send_command using pulse, startup and switch appears to trigger a refresh.

[sonofflan_debug_2.txt](https://github.com/AlexxIT/SonoffLAN/files/4688110/sonofflan_debug_2.txt)

**Comment by AlexxIT** [comment]
@tonyp740613 other commands do nothing?

**Comment by tonyp740613** [comment]
That is correct, nothing happens.  I also noticed the send_command only updates if the actual switch is switched on.  If it switched off then no updates happen.

**Comment by AlexxIT** [comment]
I found solution! I'll send "Network indicator" change command. It's save and will call update state for all devices.

**Comment by AlexxIT** [comment]
Fixed in 2.0.4
