### ISSUE TITLE
Unable to detect DualR3 Lite

### ISSUE THREAD

**Issue by espilioto** [AlexxIT/SonoffLAN#1197]
Hey guys, sorry if this is a duplicate, tried searching but found nothing related.

I just got 3 devices: MiniR2, MiniR4 and DualR3 Lite, all wifi, all stock firmware and updated to the latest version.
The MiniR2 works perfectly (except version 3.5, currently on master branch).
The MiniR4 and DualR3 Lite however do not get detected even though I paired them and tested them successfully with the ewelink app.

I do know that the MiniR4 is yet not supported, however when trying to add them as new devices I saw this in the logs:

```
Logger: homeassistant.components.switch

Source: helpers/entity_platform.py:607
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
Platform sonoff does not generate unique IDs. ID 100172d4bf is already used by switch.sonoff_100172d4bf - ignoring sonoff.sonoff_100172d4bf
```
That device id belongs to the MiniR2 that always works.

Sorry for the long post.
Any ideas?

**Comment by ieronimf** [comment]
Hello. Can you post the solution ? Have the same issue now
