### ISSUE TITLE
The opening sensor does not work Sonoff DW2-wifi

### ISSUE THREAD

**Issue by klugev303** [AlexxIT/SonoffLAN#1198]
I ask for help, the sensor is forwarded to the integration but does not see the status. I'm posting photos. 
![Screenshot_20230725-093727_Home Assistant](https://github.com/AlexxIT/SonoffLAN/assets/19494749/5f611338-a21e-4d2c-82ad-0d8e7b7212f4)
![Screenshot_20230725-093550_OfficeSuite](https://github.com/AlexxIT/SonoffLAN/assets/19494749/b51cc187-5cdd-4e50-86fd-22dd3b64c2ee)
![Screenshot_20230725-093543_OfficeSuite](https://github.com/AlexxIT/SonoffLAN/assets/19494749/197c080b-34cc-4ed8-9676-3ad48668b3a9)

**Comment by TTLucian** [comment]
Same here!

**Comment by ITMPGIT** [comment]
dw2 and pow unavailable

**Comment by ITMPGIT** [comment]
resolved on 3.5.2! tks

**Comment by klugev303** [comment]
thank you, problem solved

**Comment by klugev303** [comment]
thank you, problem solved

**Comment by AlexxIT** [comment]
@klugev303 you just have WiFi connection issue to your sensor

**Comment by klugev303** [comment]
> WiFi connection issue to your sensor

Is it possible to wait for the possibility of connecting a given sensor using local technology not through the cloud?

**Comment by AlexxIT** [comment]
This model doesn't support local API
