### ISSUE TITLE
Support for SONOFF RE5V1C - 5V Wifi Inching/Selflock Relay Module

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/SonoffLAN#120]
https://www.itead.cc/sonoff-re5v1c.html
Are You planning to add support for it? It pretty interesting module as it doesn't pass voltage to relay, so it can work very well for opening garage doors and many other things which require just "sticking 2 wires".

**Comment by AlexxIT** [comment]
I think it's supported. Because a lot a similar devices supported.

**Comment by guciopl** [comment]
Ok, will check that soon, two of them are on way to me. Thx.

**Comment by guciopl** [comment]
Just informing that it work perfectly.

**Comment by AlexxIT** [comment]
What is it firmware?

**Comment by guciopl** [comment]
3.4.0
Already shared if You want to take a look at it.

**Comment by AlexxIT** [comment]
Thanks. At first I didn’t understand what it was. You can unshare now.
