### ISSUE TITLE
Integration asking to reconfigure

### ISSUE THREAD

**Issue by kevtuning** [AlexxIT/SonoffLAN#1204]
hi,

I use this integration for years... and today after a HA restart (no update), the sonoff integration is asking to reconfigure and when I type my mail and correct password... it gives me an error message app if is unauthorised..

Is anyone else facing this issue ?

**Comment by jorgemudry** [comment]
Did you solve it? It is happening to me too

**Comment by kevtuning** [comment]
> Did you solve it? It is happening to me too

Yes... there's a solved issue... and an update has been released by Alex
