### ISSUE TITLE
After Start HA Devices Unavailable

### ISSUE THREAD

**Issue by milandzuris** [AlexxIT/SonoffLAN#1205]
When im Restart/Reboot HA some Devices are Unavailable, how fix this?, only help me Mode Auto but when im try back to Local once again are Unavailable, this problem i have last 4-5 Months.

[home-assistant_sonoff_2023-07-27T01-58-03.036Z.log](https://github.com/AlexxIT/SonoffLAN/files/12178635/home-assistant_sonoff_2023-07-27T01-58-03.036Z.log)

**Comment by kingwap99** [comment]
just got the same issue

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.7.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Asia/Taipei",
    "os_name": "Linux",
    "os_version": "6.1.34",
    "supervisor": "2023.07.1",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "notify_line": {
      "version": "2022.7.1",
      "requirements": []
    },
    "zhimi": {
      "version": "1.0.1",
      "requirements": [
        "miservice>=2.0.1"
      ]
    },
    "line_notify": {
      "version": "1.0.1",
      "requirements": []
    },
    "dohome": {
      "version": "0.2.0",
      "requirements": []
    },
    "sonoff": {
      "version": "3.5.2",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "yeelight_pro": {
      "version": "0.0.1",
      "requirements": []
    },
    "webrtc": {
      "version": "v3.2.1",
      "requirements": []
    },
    "xiaomi_miio_cooker": {
      "version": "2023.6.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "hello_miai": {
      "version": "1.0.0",
      "requirements": []
    },
    "yeelight_bt": {
      "version": "1.3.0",
      "requirements": [
        "bleak>=0.18.0",
        "bleak-retry-connector>=2.1.3"
      ]
    },
    "xiaomi_miot": {
      "version": "0.7.10",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.6",
        "micloud>=0.3"
      ]
    },
    "frigate": {
      "version": "4.0.0",
      "requirements": [
        "pytz==2022.7"
      ]
    },
    "xiaomi_gateway3": {
      "version": "3.3.2",
      "requirements": [
        "zigpy>=0.44.1"
      ]
    },
    "nodered": {
      "version": "2.1.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tapo_control": {
      "version": "5.1.0",
      "requirements": [
        "pytapo==3.1.12"
      ]
    },
    "aqara_gateway": {
      "version": "0.0.14",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "xiaomi_miio_fan": {
      "version": "2023.7.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    },
    "var": {
      "version": "0.15.0",
      "requirements": []
    },
    "xiaomi_miio_raw": {
      "version": "2023.6.0.0",
      "requirements": [
        "construct==2.10.56",
        "python-miio>=0.5.12"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "/api/sonoff/9c1359b6-873f-4369-bc0d-98d0a97e01be",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.2",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "2ad1cd7",
    "cloud_auth": false,
    "config": {
      "username": "***",
      "password": "***",
      "force_update": [
        "temperature",
        "humidity",
        "power",
        "switch",
        "remote"
      ],
      "scan_interval": "00:00:10",
      "debug": false
    },
    "options": {
      "mode": "local",
      "debug": true
    },
    "errors": [],
    "device": {
      "uiid": 32,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "only_device": {
          "ota": "success"
        },
        "sledOnline": "on",
        "ssid": "***",
        "bssid": "***",
        "fwVersion": "3.6.0",
        "staMac": "***",
        "rssi": -55,
        "init": 1,
        "alarmType": "pcv",
        "alarmVValue": [
          -1,
          -1
        ],
        "alarmCValue": [
          -1,
          -1
        ],
        "alarmPValue": [
          -1,
          -1
        ],
        "switch": "off",
        "startup": "stay",
        "pulse": "off",
        "pulseWidth": 500,
        "power": "0.00",
        "voltage": "111.63",
        "current": "0.00",
        "oneKwh": "stop",
        "uiActive": 60,
        "password": "tKH4K6p4QnULfPMpjpozMw==",
        "timeZone": 8,
        "hundredDaysKwh": "get",
        "demNextFetchTime": 1690473600000,
        "rstReason": 0,
        "exccause": 0,
        "epc1": 0,
        "epc2": 0,
        "epc3": 0,
        "excvaddr": 0,
        "depc": 0
      },
      "model": "S31TPB(US)",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "10012b7a0e"
    }
  }
}

**Comment by albkk** [comment]
Same issue here. The devices became unavailable on HA over SonoffLAN integration (they are available over ewelink integration) after a restart of HA. Before the restart everything was working perfectly. Updating to the latest version of SonoffLAN which was made available today (27/7), did not solve the issue.
I have tried with local / cloud and auto modes and devices are not available on either of those modes.

**Comment by AlexxIT** [comment]
@milandzuris answer in docs
https://github.com/AlexxIT/SonoffLAN#mode

**Comment by milandzuris** [comment]
> @milandzuris answer in docs https://github.com/AlexxIT/SonoffLAN#mode

Idk where find fix for my problem but i have Proxmox and Asus Router u know some problems in this solutions?

**Comment by AlexxIT** [comment]
Anything can be a source of problem. mDNS very complicated protocol.
