### ISSUE TITLE
Just updated to latest now can't use

### ISSUE THREAD

**Issue by jimmyz5150** [AlexxIT/SonoffLAN#1208]
Iget this error, I've updated via HACS, uninstalled Sonoff integration... restarted
any idea thx

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:899
Integration: HACS (documentation, issues)
First occurred: 15:18:33 (4 occurrences)
Last logged: 15:18:33

<Integration AlexxIT/SonoffLAN> [__init__.py] was not downloaded.
<Integration AlexxIT/SonoffLAN> [entity.py] was not downloaded.
<Integration AlexxIT/SonoffLAN> [climate.py] was not downloaded.
<Integration AlexxIT/SonoffLAN> [binary_sensor.py] was not downloaded.

**Comment by AlexxIT** [comment]
This is error from HACS integration. Not related to this component.

**Comment by jimmyz5150** [comment]
Do I need anything in yaml config bc I have user n pass setup now it says invalid so I commented out. Are there known problems nowadays with HACS bc I keep running in to problems with it. n not just your integration

**Comment by AlexxIT** [comment]
This can be some network problem

**Comment by jimmyz5150** [comment]
I know it's not ur problem... lol but I figured out the HACS thing... I turned off IPv6 on wifi. Was able download all of integrations no problems. found another HACS post which had it buried.
