### ISSUE TITLE
Sonoff 3.5.2 does not connect to devices

### ISSUE THREAD

**Issue by RMLReis** [AlexxIT/SonoffLAN#1213]
I loaded the latest version of sonoff 3.5.2 then restarted.
Does not connect to any devices.
I have 21 devices. 
Using:
Home Assistant 2023.8.1
Supervisor 2023.07.1
Operating System 10.4
Frontend 20230802.0 - latest

**Comment by RMLReis** [comment]
After restart of home assistant it has found all 24 devices but all devices connected to repeater wife are unavailable.

**Comment by blackbasilisk** [comment]
Might be related to #1211

**Comment by joabfe** [comment]
hello
what is happening is that when restarting the router another ip is assigned to the sonoff device.
SonoffLan is not downloading the new assigned IP.
this Scan is not happening "scan_interval: '00:01:00'"
In one of the devices I managed to put the old IP, and it becomes available

**Comment by blackbasilisk** [comment]
Deleted SonoffLan integration, re-added and works! :)

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by RMLReis** [comment]
Helô

I re paired the devices with ewlink then restarted sonoffLan and it worked.
I am not sure what is causing it but it seems to hapening only to devices connected to repeaters.
It is resolved for now.

Thank you

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
