### ISSUE TITLE
Unavailable devices after latest update to v.3.5.2

### ISSUE THREAD

**Issue by Softwaremaker** [AlexxIT/SonoffLAN#1214]
It was working for quite a while until I decided to upgrade to v.3.5.2 from HACS. All entities are unavailable or disabled now. What am I missing

![image](https://github.com/AlexxIT/SonoffLAN/assets/1997252/ad588833-c9d2-4065-86c5-c7e0edc031d0)

**Comment by AlexxIT** [comment]
Integrations can't disable entities. It's done by you

**Comment by Softwaremaker** [comment]
Thank you. I did not do anything to it. One minute its fine and the next after the update, it becomes like this
![image](https://github.com/AlexxIT/SonoffLAN/assets/1997252/995943ca-333e-4ed2-b835-805c66c1d3a4)

What should I be looking at to do or is there a way to "roll-back" ? thanks !

**Comment by Softwaremaker** [comment]
Never mind. I have "rolled back" to v3.4.2 through a backup of home assistant and it is fine now. Will stick with v3.4.2 for now. Thanks !
