### ISSUE TITLE
POW R3 power meter on Local does not update

### ISSUE THREAD

**Issue by frlequ** [AlexxIT/SonoffLAN#1217]
I've seen some previous post about this issue as resolved but, for me it still doesn't work.

I've disable internet access to my Sonoffs and set SonoffLAN to local puling. As for POWR316 power, current and voltage updates normally, but POW R3 does not. I'm aware that Energy Meter needs internet time to calculate, but Power should update without it. 

Version | 3.5.2 (2ad1cd7)
Cloud devices online | 0 / 2
Local devices online | 2 / 2
Running Firmware: 1.1.0.

The only way it works is to set SonoffLAN to Cloud or Auto, and enable internet access.
Is there any solution to put POW R3 to local?

**Comment by CestLaGalere** [comment]
I to have just started to have this problem - the power (and current and voltage) lags - when I turn the POWR3 off the power updates to what it was drawing when it was on, and likewise turning it on the power goes to 0.

There is nothing in the logs (I haven't enabled debug in configuration.yaml - and having turned debug mode on in integrations as suggested trying to look the debug log at https://192.168.1.11:8123/api/sonoff/c8503fee-88fb-4a18-84d9-abb782bf0aa7?q=1000xxxxxx&r=2 gives a 404 not found error... is this GUID specific to my device, if so where do I find it?

**Comment by sayinzest** [comment]
I got the same problems. the current and the voltage update without the energy. and others use a temporary, not working， except the local  one install a local  homeassistant.

**Comment by rafalgiit** [comment]
Power consumption updates come (not very frequently) when mobile app (eWelink) is on and active.

**Comment by rafalgiit** [comment]
Uninstall the eWelink app and restart HA :)

**Comment by frlequ** [comment]
> Uninstall the eWelink app and restart HA :)

This doesn't work when Sonofflan is set to local.

**Comment by slipx06** [comment]
> I to have just started to have this problem - the power (and current and voltage) lags - when I turn the POWR3 off the power updates to what it was drawing when it was on, and likewise turning it on the power goes to 0. Looking at the device in the eWelink app when I turn it on / off from HA the current power etc are updated correctly withing a second of the state changing.
> 
> There is nothing in the logs (I haven't enabled debug in configuration.yaml - and having turned debug mode on in integrations as suggested trying to look the debug log at https://192.168.1.11:8123/api/sonoff/c8503fee-88fb-4a18-84d9-abb782bf0aa7?q=1000xxxxxx&r=2 gives a 404 not found error... is this GUID specific to my device, if so where do I find it?

I can confirm this issue POW R2

**Comment by Shaolo** [comment]
Same. Sometimes it continues to report power even if the switch is off.

**Comment by peregrines2** [comment]
Same problem here. Would be very happy if this could be resolved :)

**Comment by AlexxIT** [comment]
This data is cloud only. Only solution - use internet or flash your firmware
