### ISSUE TITLE
Sonoff LAN not detecting POW2

### ISSUE THREAD

**Issue by meneerfrikkie** [AlexxIT/SonoffLAN#1220]
Hi everyone, I recently installed Sonoff LAN via HACS since my POW2 was having issues with flashing ESPHome, anyways I've got the Sonoff Lightbulb detected by the integration however I'm unable to detect my POWR2 device, does anyone have a solution to detecting new devices once the integration is set up, many thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#issues

**Comment by meneerfrikkie** [comment]
Signed in with my EweLink account again and the device popped up, noticed that I have to resign in whenever new devices are added in the EweLink app 😄

**Comment by AlexxIT** [comment]
You just need to restart Hass
