### ISSUE TITLE
eWeLink CoolKit servers are returning wrong port on handshake

### ISSUE THREAD

**Issue by n-vodenicharski** [AlexxIT/SonoffLAN#1223]
Looks like the CoolKit severs are returning wrong port **8080** when creating the session with the dispatch API: _await self.session.get(self.ws_host, headers=self.headers)_
Changing the port to 443 is fixing the issue: f"wss://{resp['domain']}:443/api/ws", heartbeat=90

It will be nice to have a configurable parameter to override the port.

**Comment by AlexxIT** [comment]
I haven't heard about this problem. Maybe temporary issue

**Comment by n-vodenicharski** [comment]
True, it is working now.
GET to https://eu-dispa.coolkit.cc/dispatch/app, returns 
{
    "port": 8080,
    "domain": "eu-pconnect11.coolkit.cc",
    "error": 0,
    "reason": "ok",
    "IP": "52.59.155.15"
}
but now you can wss://52.59.155.15:8080/api/ws to it. It was not the case before.

**Comment by n-vodenicharski** [comment]
Maybe a temp issue.
