### ISSUE TITLE
[Feature request] Add digital inputs S1 and S2 as entities in HA

### ISSUE THREAD

**Issue by elminos** [AlexxIT/SonoffLAN#1229]
For some automations it'd be great to have the digital inputs S1 and S2 of the different devices that have DI and control the relays via HA instead than the firmware itself.

My specific case is that I want to control a Fan which only works via RF remote (I use broadlink RM4 Pro for the commands) and I want to keep the relay always active and use the **Dual R3** meerely as a Digital Input interface to HA. 
Then I will loop the 4 velocities of the fan for each pulse of the S1 input. 
Something similar I'll do with the light of the Fan with the S2 input.

I hope some people finds this helpful as well.

All the best!

**Comment by AlexxIT** [comment]
I don't understand your idea and what you want

**Comment by elminos** [comment]
Let me clarify. Basically it'd be nice to have the signals S1 and S2 into home assistant as entities so you'd treat the Dual R3 as a digital input interface with HA.
With these digital inputs you can trigger automations.

Finally I flashed ESPHome and got it to work but this might help other people.
Thank you for your time

**Comment by AlexxIT** [comment]
I can't do it if default firmware doesn't support it.
