### ISSUE TITLE
No connection after update in Hassio

### ISSUE THREAD

**Issue by panjas51** [AlexxIT/SonoffLAN#123]
Hello,

My home assistant HASSIO(0.110.3) doen't see anymore my basicR3, neither my 4ch pro after update of this module (2.0.3) and Hacs.(1.0.3)

Invalid configuration
The Following intégration and platforms could not be set up:
Sonoff
Sonoff.switch
Check tour config

i didn't changed the config files…….

**Comment by AlexxIT** [comment]
Hi. Check logs for errors.

**Comment by panjas51** [comment]
i have renewed the password in ewelink a d it works..
Thanks

**Comment by AlexxIT** [comment]
**Breaking changes 2.0**: by default, both local and cloud modes will start working together. If you do not want this - enable the mode: local setting. But I recommend using the new mode, it works great.
