### ISSUE TITLE
Extract current day/month $$ from POW R2?

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/SonoffLAN#124]
As in topic. I am curious if this kind of info is possible to obtain to put it on Dashboard.

**Comment by AlexxIT** [comment]
eWeLink app shows this data?

**Comment by guciopl** [comment]
Yes, "Usage" or something simmilar (I am not using english version), chart icon in bottom left corner when You enter POW. It shows chart + usage per every day and total usage along with prices for whole month. Price needs to be set in module settings, same place where You turn off network light, set LAN control etc.

**Comment by AlexxIT** [comment]
Can you share it to my acc? sonofflan@gmail.com
Sharing does not work for some users, I do not know how to fix it.

**Comment by guciopl** [comment]
Done. This is how it looks like in case sharing won't work.
![Screenshot_20200527-112901_eWeLink](https://user-images.githubusercontent.com/61185430/83002486-694e9c80-a00d-11ea-8142-55dd57a1a019.jpg)

3.13 is total KWh used this month and 1.72 is price for that. I have price set to 0.55 per KWh.

**Comment by AlexxIT** [comment]
I see this information. Later I will see what can be done

**Comment by AlexxIT** [comment]
Added to 2.0.4
https://github.com/AlexxIT/SonoffLAN#sonoff-pow-power-consumption

**Comment by AlexxIT** [comment]
```
Today consumpion: {{ state_attr('switch.sonoff_1000abcdef', 'consumption')[0] }}
10 days consumpion: {{ state_attr('switch.sonoff_1000abcdef', 'consumption')[:10]|sum }}
```

![download](https://user-images.githubusercontent.com/511909/83110894-6d8dbf00-a0cc-11ea-8898-278ea56f2be3.png)

**Comment by guciopl** [comment]
Thank You, You are true wizard, I never received support so fast.
Can You please advise how to put that data to entity? HA code is still mystery for me if.

**Comment by guciopl** [comment]
1 day multiplied by 0.001 seems to have ideal values in HA:
{{ state_attr('switch.sonoff_10005bfa0c', 'consumption')[0] | multiply(0.001) | float }}

however 30 days multiplied by 0.001 still shows pretty big numbers, cant figure why
value_template: "{{ state_attr('switch.sonoff_100042c55d', 'consumption')[:30]|sum }}" | multiply(0.001) | float

**Comment by guciopl** [comment]
Ok, got the issue. 3 digits reading are ok. When there is 4 digit reading there is aditional 0 put after 1st digit and therefore it becomes 5 digit reading, being 10times too big:

![Untitled-1](https://user-images.githubusercontent.com/61185430/83119681-5224b300-a0d0-11ea-9f17-80aa89873e91.jpg)

**Comment by AlexxIT** [comment]
Check v2.0.5

**Comment by guciopl** [comment]
Awesome. Works like a charm. Used | round(2) tho, because some of readings have 10digit precission, but I assume it may be hardware dependent.

Thanks anyway, now it is what I wanted ;)

**Comment by AlexxIT** [comment]
Please share device wih 10 digits precission problem.

**Comment by guciopl** [comment]
Done. Actually the precission is much bigger than 10 digits. Like 16 or so.

**Comment by AlexxIT** [comment]
I updated version v2.0.5 with the same number. If HACS does not want to update - you need to do reinstall.

**Comment by guciopl** [comment]
Thanks mate. Basically what You did here is saving me a lot of time with flashing Tasmota on all my Sonoff devices. Now I have what I wanted on stock firmware.

Shared some coffee with You, hope You can get a nice pizza and some beer for that amount. Thanks again. Hoping to meet more people like You during my Home Assistant adventure.
