### ISSUE TITLE
Local mode do not work when connected to vpn

### ISSUE THREAD

**Issue by siriostar89** [AlexxIT/SonoffLAN#1241]
Hello, just wanted to say that local mode do not work (grayed) when I'm connected to a vpn, maybe it cannot recognize the devices in the local network, or I don't know, didn't look at the code. Anyway do you have any fix? because I had to stop my openvpn everytime I restart home assistant and start again openvpn after everything it's loaded so I can use local mode...
What can I do?
Thanks!

**Comment by AlexxIT** [comment]
Forward mDNS over VPN - VERY complicated but possible task. Not ask me how to do that.
