### ISSUE TITLE
MINIR4M action triggers twice

### ISSUE THREAD

**Issue by tsemer** [AlexxIT/SonoffLAN#1242]
Thanks so much for adding support for #1227 😄

Looks like the new sensor is called "Action". I'm seeing now in the HA logbook two events fire every time the physical (detached) switch is being pressed:

1. "\<Action sensor name>"
1. "\<Action sensor name> changed to single"

Here's a screenshot:

<img src="https://github.com/AlexxIT/SonoffLAN/assets/11571248/9a7f6d10-e8fa-4bb6-9b79-be73cca03c2c" width="300" />

Was this the intention or is this a bug?

If this was intentional - I have a question about how to create an automation using this new sensor. When I create a simple automation using the sensor as a "state" trigger, then the automation is triggered twice for every physical switch toggle (light goes on and immediately goes off, or vice versa depending on initial state). This is how a simple automation looks:

<img src="https://github.com/AlexxIT/SonoffLAN/assets/11571248/a677e984-3c6f-47cb-ac09-35a51dd67d28)" width ="300" />

Obviously, we want the automation to hit only once for every physical switch toggle. I've tried to fill different values in the fields "Attribute", "To" and "From", including `to: single` and directly in YAML `to:` (based on [HA docs](https://www.home-assistant.io/docs/automation/trigger/#state-trigger) for "trigger on all state changes, but not attributes"). So far I haven't managed to filter a single event.

My current only workaround is to add a 1 second delay using the "For" field, but this is of course sub-optimal, home users expect a physical light switch to work almost immediately.

I don't mind editing the automation in YAML if necessary, there are a few additional fields available that are not supported by the UI.

Thanks in advance!

**Comment by tsemer** [comment]
\<Embarrassed> :dizzy_face: now the value `to: single` seems to work. I don't know what I did wrong before. Perhaps I accidentally used a capital "S". Either way, this value seems to be the solution.

**Comment by AlexxIT** [comment]
I think device firmware not support local button press. You can try to write to sonoff team.

**Comment by SpartanTech** [comment]
tsemer, 

how did you get this to work? my Action sensor is always blank when i flip my light switch. it is currently in attached-relay mode until i can program the automation. does the sensor only update when detached?

and if i may ask, what switch mode (not detach relay option) is your switch in? Is your Lan Mode (on the device settings) enabled or disabled?

looking to have my smart lights always powered so i bought these. and handling receiving the signal from the light switch to act as a automation switch via H.A.

**Comment by tsemer** [comment]
> does the sensor only update when detached?

I seem to remember so, yes. You can easily test it yourself - just set it to "detached" and see if it starts working.

> what switch mode (not detach relay option) is your switch in?

Mine is in edge mode, since that's the type of switch I have - what you might call a "standard" switch.

> Is your Lan Mode (on the device settings) enabled or disabled?

If you mean "LAN control" then it's enabled.

Hope this helps!

**Comment by tsemer** [comment]
> I think device firmware not support local button press. You can try to write to sonoff team.

I've written to sonoff team. Will update their response.

cc @wishie

**Comment by AlexxIT** [comment]
Two times trigger is a bug. You need to collect debug logs

**Comment by tsemer** [comment]
> Two times trigger is a bug. You need to collect debug logs

Thanks @AlexxIT, but I think this got reopened by accident when I left my last comment. @wishie saw the same behaviour, and filtering the action `to: single` works, so we figured it's by design no? For me this is good enough. If you still want any logs to debug please tell me exactly how to get them for you and I will.

For me, I'm only coming back here to follow up on the additional request of @wishie to make this action local (as you suggested above, I wrote to the Sonoff team).

**Comment by AlexxIT** [comment]
Ah. Of course `to: single` is important in the trigger.
