### ISSUE TITLE
Feature request: Add support for SNZB-06P

### ISSUE THREAD

**Issue by atlaspl** [AlexxIT/SonoffLAN#1245]
Hi Alex, 
could you add the support for the new SONOFF Zigbee Human Presence Sensor | SNZB-06P:  
https://itead.cc/product/sonoff-zigbee-human-presence-sensor/?utm_source=itead&utm_medium=homebanner&utm_campaign=SNZB-06P 

Thank you for your great work

**Comment by AlexxIT** [comment]
Do you have it? Please show device info.

**Comment by Netfalls** [comment]
Device info
SNZB-06P
by SONOFF
Firmware: 1.0.5

**Comment by atlaspl** [comment]
May be, did you want this?
[sonoff-bfafcfbdaa9afbe8d6413cdd8f126169-PresenzaLetto-985d049fc5025cc5ea76c7158b07231c.json.txt](https://github.com/AlexxIT/SonoffLAN/files/13850809/sonoff-bfafcfbdaa9afbe8d6413cdd8f126169-PresenzaLetto-985d049fc5025cc5ea76c7158b07231c.json.txt)

**Comment by AlexxIT** [comment]
OK. You need to collect debug logs for this device.

**Comment by malanleroux** [comment]
Hi @AlexxIT.

I recently got the SNZB-06P Human Presence Sensor. And the only Sensor being detected is the Motion.
My understanding is that there should be two sensors.
1. Motion
2. Occupancy

As per this [video](https://www.youtube.com/watch?v=z5SJdtf4cgQ).
![image](https://github.com/AlexxIT/SonoffLAN/assets/130469482/a1f2d4c7-3ab1-4c6b-a3c5-555203a38a58)

Would it be possible to add that support for the SNZB-06P device?

**Comment by AlexxIT** [comment]
> You need to collect debug logs for this device.

**Comment by malanleroux** [comment]
The only log I see in home assistant I see with regards to the device in this one.
I have redacted some of the properties that I believe might be sensitive, please let me know if this is what you are looking for, and if you need the redacted information, and maybe a way to contact you on a less public manner :)

If this is though not the information/logs you require, would you be able to guide me or point me to documentation to the requested logs.

Kind Regards

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:394
integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 8:52:04 AM (1 occurrences)
Last logged: 8:52:04 AM
UNKNOWN cloud msg: {'action': 'subDevice', 'deviceid': '10016aXXXX', 'apikey': '6925XXXX-bXXX-4XXX-bXXX-XXXX69b5XXXX', 'userAgent': 'device', 'd_seq': 54104, 'params': {'cmds': [{'type': 0, 'subDevId': '011f17fefff6ef0cXXXX', 'uiid': 'XXXX', 'deviceid': 'a48009XXXX', 'productName': 'SNZB-06P'}]}}

**Comment by AlexxIT** [comment]
Have you checked debug logs? https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues
You should do something with device while debug logs enabled

**Comment by malanleroux** [comment]
Here is the logs I see related to my presence sensor. (Device ID = a480090ad1)
I do not see any error's or warning related to it. I have an automation setup to turn on the light (That works).

With that said, maybe your integration just works a little different :)
I have another (PIR) motion sensor in same room that "Clears" motion when I sit still, but the SNZB-06p sensor does not "Clear".

An I being a Muppet? If i am, I am so sorry for that. I'm fairly new to the whole HA thing.

Test time was at 
17:46:11.281 (Cleared)
17:46:56.688 (Detected)

2024-04-15 15:23:08.149 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] a480090ad1 UIID 2026 | {'bindInfos': {'gaction': ['69252b4d-b9d3-4f33-bcf5-97a569b518b7_ewelinkGoogleHome'], 'smartThings': []}, 'subDevId': '011f17fefff6ef0c2026', 'parentid': '10016ad9d2', 'motion': 1, 'trigTime': '1713186368278', 'subDevRssiSetting': {'active': 60, 'duration': 5}}

2024-04-15 15:23:08.150 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 10016ad9d2 UIID 0066 | {'bindInfos': {'gaction': ['69252b4d-b9d3-4f33-bcf5-97a569b518b7_ewelinkGoogleHome'], 'smartThings': []}, 'version': 8, 'subDevNum': 17, 'subDevMaxNum': 32, 'sledOnline': 'on', 'zled': 'off', 'staMac': '48:3F:DA:27:3D:6F', 'fwVersion': '1.7.0', 'timeZone': 2, 'subDevices': [{'subDevId': 'b9ea3429004b12001770', 'deviceid': 'a48005ce4d', 'uiid': '1770', 'index': 0}, {'subDevId': 'd4959623004b12001000', 'deviceid': 'a480058c44', 'uiid': '1000', 'index': 0}, {'subDevId': 'eba74e2a004b12003026', 'deviceid': 'a480066ea4', 'uiid': '3026', 'index': 0}, {'subDevId': 'b5972b29004b12003026', 'deviceid': 'a48007a2de', 'uiid': '3026', 'index': 0}, {'subDevId': 'fdea2b29004b12003026', 'deviceid': 'a4800831ed', 'uiid': '3026', 'index': 0}, {'subDevId': 'fb3f3229004b12002026', 'deviceid': 'a480060f70', 'uiid': '2026', 'index': 0}, {'subDevId': '2f553229004b12002026', 'deviceid': 'a480060f6f', 'uiid': '2026', 'index': 0}, {'subDevId': 'bfeb3429004b12001770', 'deviceid': 'a48005ce49', 'uiid': '1770', 'index': 0}, {'subDevId': 'fb972b29004b12003026', 'deviceid': 'a480071734', 'uiid': '3026', 'index': 0}, {'subDevId': 'b14f3229004b12002026', 'deviceid': 'a4800601b6', 'uiid': '2026', 'index': 0}, {'subDevId': 'fb431729004b12002026', 'deviceid': 'a480052ee2', 'uiid': '2026', 'index': 0}, {'subDevId': '938b9623004b12001000', 'deviceid': 'a480058c47', 'uiid': '1000', 'index': 0}, {'subDevId': 'b6c61829004b12002026', 'deviceid': 'a48007eef6', 'uiid': '2026', 'index': 0}, {'subDevId': '72f41829004b12002026', 'deviceid': 'a48007ef07', 'uiid': '2026', 'index': 0}, {'subDevId': 'c73b2b29004b12003026', 'deviceid': 'a48007172a', 'uiid': '3026', 'index': 0}, {'subDevId': '76673529004b12003026', 'deviceid': 'a480066ea0', 'uiid': '3026', 'index': 0}, {'subDevId': '011f17fefff6ef0c2026', 'deviceid': 'a480090ad1', 'online': True, 'uiid': '2026', 'index': 0}], 'addSubDevState': 'off', 'addDevTime': 180, 'rssi': -27}

2024-04-15 17:46:11.281 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] a480090ad1 <= Cloud3 | {'motion': 0, 'trigTime': '1713195951322'} | None

2024-04-15 17:46:56.688 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] a480090ad1 <= Cloud3 | {'motion': 1, 'trigTime': '1713195995501'} | None

**Comment by AlexxIT** [comment]
Are you sure `a480090ad1` is SNZB-06p? Can you show device diagnostics? Because @atlaspl has another UIID:

```
"uiid": 7016,
"model": "SNZB-06P",
```

**Comment by malanleroux** [comment]
![image](https://github.com/AlexxIT/SonoffLAN/assets/130469482/5ca7acc8-1e2f-4afd-a3c8-3974b8a9c43b)

**Comment by AlexxIT** [comment]
This is not a diagnostics

**Comment by Marcelo-Y** [comment]
"It always has been. This sensor has never been supported in integration:"

But the sensor was working before update, even if was not supported. I don't see any benefit in have RSSI if the sensor is not supported, right?

Hope one day people can use this sensor in your integration.
Keep going, you're doing a great job.

Thanks you very much, Alex.

**Comment by AlexxIT** [comment]
I absolutely agree that the sensor is useless now. But none of its users want its support...
I still haven't seen the debug logs collected.
I have no idea what this sensor is sending or what its converter should look like.

Only @malanleroux sent debug logs. But these logs are from some other device. He has UIID 2026. But SNZB-06P should be 7016.

**Comment by AlexxIT** [comment]
You can check latest master version

**Comment by Marcelo-Y** [comment]
Wow man, you were incredibly fast!
I've tested and so far it's working flawlessly.
Tested changing "sensitivity" through HA, and updates of light, occupancy and RSSI states. Everything in order.

That's an amazing job!
Thank you very, very much!

**Comment by xeberth** [comment]
Same issue here.

This are my debug and diagnostics for my SNZB-06P that is not showing other sensors than RSSI after latest integration updates. (sensor works well a few versions ago)

[sonoff-SNZB-06P-logs&diagnostics.json](https://github.com/AlexxIT/SonoffLAN/files/15209361/sonoff-SNZB-06P-logs.diagnostics.json)

![image_2024-05-04_041524626](https://github.com/AlexxIT/SonoffLAN/assets/54719682/6a45eff3-ae23-4e61-8fca-941d54360229)

**Comment by atlaspl** [comment]
> Same issue here.
> 
> This are my debug and diagnostics for my SNZB-06P that is not showing other sensors than RSSI after latest integration updates. (sensor works well a few versions ago)
> 
> [sonoff-SNZB-06P-logs&diagnostics.json](https://github.com/AlexxIT/SonoffLAN/files/15209361/sonoff-SNZB-06P-logs.diagnostics.json)
> 
> ![image_2024-05-04_041524626](https://private-user-images.githubusercontent.com/54719682/327941001-6a45eff3-ae23-4e61-8fca-941d54360229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODY0MTksIm5iZiI6MTcxNTc4NjExOSwicGF0aCI6Ii81NDcxOTY4Mi8zMjc5NDEwMDEtNmE0NWVmZjMtYWUyMy00ZTYxLThmY2EtOTQxZDU0MzYwMjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1MTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MTBhN2IxYmQ5OTQ2NDcwOWIyZTIwNmQ3OWU3NjI2ZjFkYTYxMDBjNzI0MTc4YmI2YzFlMmY1NTE5ZjFkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RCn6LxStDLv0JFouNdANODEEwmvjWHC0ETHrWyyI8FQ)

I Have the same problem. Since the last SonoffLAN update ican see just the RSI sensor but the presence sensor is unavailable.
What could I do to solve the problem or how could I help you to 
![Screenshot_15-5-2024_172430_carhome duckdns org](https://github.com/AlexxIT/SonoffLAN/assets/75225632/7651067c-3d32-48a1-ac2e-d6fb23c07993)
solve it?

**Comment by neilheyes** [comment]
Hi - I can only see the RSSI as above.
[sonoff-6e89fa58c5d037f90cafcfce9f711741-KitchenPresence-9a3926f13ed389dacc0c461c98d4de90.json](https://github.com/AlexxIT/SonoffLAN/files/15369987/sonoff-6e89fa58c5d037f90cafcfce9f711741-KitchenPresence-9a3926f13ed389dacc0c461c98d4de90.json)

Hopefully the diagnostics will help, also added the debug log - the device does seem to report the entities but not in the UI.

[home-assistant_sonoff_2024-05-19T16-04-02.603Z.log](https://github.com/AlexxIT/SonoffLAN/files/15369997/home-assistant_sonoff_2024-05-19T16-04-02.603Z.log)

**Comment by AlexxIT** [comment]
You can stop sending debug logs. Device supported more than two weeks ago.

**Comment by neilheyes** [comment]
> You can stop sending debug logs. Device supported more than two weeks ago.

Sorry, thought it might help. I can only see the hidden rssi in the entities

**Comment by neilheyes** [comment]
> > Same issue here.
> > This are my debug and diagnostics for my SNZB-06P that is not showing other sensors than RSSI after latest integration updates. (sensor works well a few versions ago)
> > [sonoff-SNZB-06P-logs&diagnostics.json](https://github.com/AlexxIT/SonoffLAN/files/15209361/sonoff-SNZB-06P-logs.diagnostics.json)
> > ![image_2024-05-04_041524626](https://private-user-images.githubusercontent.com/54719682/327941001-6a45eff3-ae23-4e61-8fca-941d54360229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODY0MTksIm5iZiI6MTcxNTc4NjExOSwicGF0aCI6Ii81NDcxOTY4Mi8zMjc5NDEwMDEtNmE0NWVmZjMtYWUyMy00ZTYxLThmY2EtOTQxZDU0MzYwMjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1MTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MTBhN2IxYmQ5OTQ2NDcwOWIyZTIwNmQ3OWU3NjI2ZjFkYTYxMDBjNzI0MTc4YmI2YzFlMmY1NTE5ZjFkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RCn6LxStDLv0JFouNdANODEEwmvjWHC0ETHrWyyI8FQ)
> 
> I Have the same problem. Since the last SonoffLAN update ican see just the RSI sensor but the presence sensor is unavailable. What could I do to solve the problem or how could I help you to ![Screenshot_15-5-2024_172430_carhome duckdns org](https://private-user-images.githubusercontent.com/75225632/330868021-7651067c-3d32-48a1-ac2e-d6fb23c07993.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDg2OTMsIm5iZiI6MTcxNjgwODM5MywicGF0aCI6Ii83NTIyNTYzMi8zMzA4NjgwMjEtNzY1MTA2N2MtM2QzMi00OGExLWFjMmUtZDZmYjIzYzA3OTkzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxMTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjAwYWFhNTQ4MzZjMDAzNzc0YzM4OTJkOWRmMTJhZGMzOWI2NzY4N2U3MzRjZWY1NTYxYjdkMjY3ZmE4MWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K4mRuTSPxJ5xPBxtIqNDjBbS8PulT5vg0KYRqZq6JqM) solve it?



> > Same issue here.
> > This are my debug and diagnostics for my SNZB-06P that is not showing other sensors than RSSI after latest integration updates. (sensor works well a few versions ago)
> > [sonoff-SNZB-06P-logs&diagnostics.json](https://github.com/AlexxIT/SonoffLAN/files/15209361/sonoff-SNZB-06P-logs.diagnostics.json)
> > ![image_2024-05-04_041524626](https://private-user-images.githubusercontent.com/54719682/327941001-6a45eff3-ae23-4e61-8fca-941d54360229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODY0MTksIm5iZiI6MTcxNTc4NjExOSwicGF0aCI6Ii81NDcxOTY4Mi8zMjc5NDEwMDEtNmE0NWVmZjMtYWUyMy00ZTYxLThmY2EtOTQxZDU0MzYwMjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE1MTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MTBhN2IxYmQ5OTQ2NDcwOWIyZTIwNmQ3OWU3NjI2ZjFkYTYxMDBjNzI0MTc4YmI2YzFlMmY1NTE5ZjFkN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RCn6LxStDLv0JFouNdANODEEwmvjWHC0ETHrWyyI8FQ)
> 
> I Have the same problem. Since the last SonoffLAN update ican see just the RSI sensor but the presence sensor is unavailable. What could I do to solve the problem or how could I help you to ![Screenshot_15-5-2024_172430_carhome duckdns org](https://private-user-images.githubusercontent.com/75225632/330868021-7651067c-3d32-48a1-ac2e-d6fb23c07993.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDg2OTMsIm5iZiI6MTcxNjgwODM5MywicGF0aCI6Ii83NTIyNTYzMi8zMzA4NjgwMjEtNzY1MTA2N2MtM2QzMi00OGExLWFjMmUtZDZmYjIzYzA3OTkzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxMTEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjAwYWFhNTQ4MzZjMDAzNzc0YzM4OTJkOWRmMTJhZGMzOWI2NzY4N2U3MzRjZWY1NTYxYjdkMjY3ZmE4MWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K4mRuTSPxJ5xPBxtIqNDjBbS8PulT5vg0KYRqZq6JqM) solve it?

I did figure this out - it seems that the devices.py coming from HACS does not have the full set of entities in it, but the one direct from here does and they both report v3.7.3

**Comment by atlaspl** [comment]
Issue with SNZB-06P Sensor Status Post-Update of SonoffLAN at v3.7.3

@AlexxIT I’ve encountered a persistent issue where the status of my SNZB-06P sensors is no longer visible, although the RSSI remains accessible. This problem surfaced following the most recent update. Prior to this, the status of my three SNZB-06P sensors was displayed without any complications. It seems that the update may have inadvertently affected the sensor status visibility within the system.

I don't know if it can be useful, but the three devices are all associated with a ZBBridge-P

**Comment by atrambauer** [comment]
> Hi @AlexxIT , support for this device is not possible?

Sorry, i just see that support was added but not compiled into last version. Will update manually

**Comment by atrambauer** [comment]
> > Hi @AlexxIT , support for this device is not possible?
> 
> Sorry, i just see that support was added but not compiled into last version. Will update manually

I can confirm that Occupancy and Light is working.

**Comment by atlaspl** [comment]
> > > Hi @AlexxIT , support for this device is not possible?
> > 
> > 
> > Sorry, i just see that support was added but not compiled into last version. Will update manually
> 
> I can confirm that Occupancy and Light is working.

What do you mean by "will update manually"? How can I do it as well?

**Comment by atrambauer** [comment]
Auto would be directly from HACS in HA, It didn't update the integration
for me. I uploaded files manually.

**Comment by atrambauer** [comment]
> > > > Hi @AlexxIT , support for this device is not possible?
> > > 
> > > 
> > > Sorry, i just see that support was added but not compiled into last version. Will update manually
> > 
> > 
> > I can confirm that Occupancy and Light is working.
> 
> What do you mean by "will update manually"? How can I do it as well?

I uploaded and replaced the modified files from HA folder
[https://github.com/AlexxIT/SonoffLAN/commit/af725189c9f506b12c52bda59846dc3bd7deb96a](url)

**Comment by atlaspl** [comment]
> > > > > Hi @AlexxIT , support for this device is not possible?
> > > > 
> > > > 
> > > > Sorry, i just see that support was added but not compiled into last version. Will update manually
> > > 
> > > 
> > > I can confirm that Occupancy and Light is working.
> > 
> > 
> > What do you mean by "will update manually"? How can I do it as well?
> 
> I uploaded and replaced the modified files from HA folder [https://github.com/AlexxIT/SonoffLAN/commit/af725189c9f506b12c52bda59846dc3bd7deb96a](url)

Sorry, the link for me didnt' work, is it a my problem?

**Comment by atrambauer** [comment]
> Have you got a solution?

Check commit af72518, you can replace those files to make it work. Master version hasn't been compiled since that change yet.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
