### ISSUE TITLE
Feature Request: Working Mode of DualR3

### ISSUE THREAD

**Issue by haideralipunjabi** [AlexxIT/SonoffLAN#1246]
Can you please add a feature by which we can control the Working Mode of DualR3. It is the param `workMode`.

**Comment by AlexxIT** [comment]
Why do you want to control it from Hass? It changes once in a few years. You can do it in ewelink app

**Comment by haideralipunjabi** [comment]
> once

That's the thing. One of mine is probably broken 😅. Switches to Motor Mode every couple of hours. 
If it isn't reasonable, I guess I will figure it out myself. I tried a bit.  I can read the work mode, but I guess I need to send more params to write it

**Comment by AlexxIT** [comment]
You can send any raw command. Check docs

**Comment by haideralipunjabi** [comment]
> You can send any raw command. Check docs

Yes, I got it to work. You can close the issue if you want. Thanks 😄

**Comment by vaites** [comment]
> Why do you want to control it from Hass? It changes once in a few years. You can do it in ewelink app


@AlexxIT I have a [SONOFF DUALR3](https://sonoff.tech/product-review/product-insight/insights-into-dualr3s-three-working-modes-switch-motor-and-meter-modes/) to control a balcony shutter. For me the reason to change the working mode is that if the balcony door opens, the shutter can hit it (and break something). I want to disable the possibility of raising and lowering the shutter with a detector. This can be done with this device changing its working mode to _meter_.  Moreover, as Alexa also controls the device directly, it would not be enough to block in Home Assistant, but would have to be done on the device itself...

> Yes, I got it to work. You can close the issue if you want. Thanks 😄

@haideralipunjabi Can you please provide the parameters for the `sonoff.send_command` service? Or, where can I find the specification? (don't know what are the options for the working mode)

**Comment by AlexxIT** [comment]
You can enable debug. Change mode via app. And check params in debug.
