### ISSUE TITLE
Sonoff ultimate tx - ambient light change effect back to 0

### ISSUE THREAD

**Issue by tavarez992** [AlexxIT/SonoffLAN#1247]
Recently added feature for Sonoff ultimate TX switch to control ambient light has problem when changing effect back to "0" - Night Light mode. It ignores "0" and keeps last chosen mode, even after On/Off. 
It's possible for me to change it back only in the eWeLink app.

I also recommend adding nicknames for effect (from eWeLink) :) 
0 - Night Light
1 - Party
2 - Leisure
3 - Color
4 - Childhood
5 - Wiper
6 - Fairy
7 - Starburst

Feature for changing RGB and brightness of light will be really cool :) (and also for state lights :P ) 
but it's really good job as it is :) so big thank you for your work

**Comment by rdaraujo** [comment]
I've also noticed that minor misbehavior.
And I can confirm the fix from @frborda ([9f662ba](https://github.com/frborda/SonoffLAN/commit/9f662baeef0c9707c010860ee3d09b3eb5b30512)) also properly fixed it.
Thanks.

**Comment by frborda** [comment]
Now the names are displayed on my TX5 on the select list @rdaraujo 
The current name was missing after having set one. Fixed [113cfc1](https://github.com/frborda/SonoffLAN/commit/113cfc13b70af519155fb97e8d48737402d126f8)

**Comment by rdaraujo** [comment]
Nice, now is all good :D

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.6.0

**Comment by pieterhill** [comment]
Hi guys,
This bug seems to have returned in 3.9.0
Night Light is no longer working when selected…
