### ISSUE TITLE
No Ambient light in Sonoff Ultimate Tx T5-4c

### ISSUE THREAD

**Issue by atlaspl** [AlexxIT/SonoffLAN#1251]
Hi, in your last update I saw a fantastic addition: the ability to control the ambient light of 2c and 3c that works  beautifully. However , I also have 4cs where this feature isn't available. 
When can we expect this new functionality on the 4c too?

Thank you

**Comment by AlexxIT** [comment]
You should provide device info

**Comment by atlaspl** [comment]
Here it is. Thank you

[sonoff-bfafcfbdaa9afbe8d6413cdd8f126169-Lampadario cameretta-f244b1bb81eddaa1e68e5863133e34ff.json.txt](https://github.com/AlexxIT/SonoffLAN/files/13196603/sonoff-bfafcfbdaa9afbe8d6413cdd8f126169-Lampadario.cameretta-f244b1bb81eddaa1e68e5863133e34ff.json.txt)

**Comment by Opontios** [comment]
Since when sonoff started manufacturing TX Ultimate 4ch???

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.4
