### ISSUE TITLE
Fix slide_2 action sensor always triggered by any command (T5-3C-86)

### ISSUE THREAD

**Issue by catalinescu-sudo** [AlexxIT/SonoffLAN#1252]
Hi, I want to use capabilities of T5-3C-86 with slide_1 and slide_2. The problem is that everytime I turn on or off one of the light channels of the device, also "slide_2" action is received by home assistant, and this disturbs my other plans, so I can't make usable automations with this function. Is a bug perhaps of the new update? Thank you!

**Comment by AlexxIT** [comment]
You need to collect debug logs with this problem

**Comment by catalinescu-sudo** [comment]
[home-assistant_sonoff_2023-11-01T14-56-29.455Z.log](https://github.com/AlexxIT/SonoffLAN/files/13228480/home-assistant_sonoff_2023-11-01T14-56-29.455Z.log)
Is this what you need?

**Comment by catalinescu-sudo** [comment]
Another observation: this behavior is happening when I use switches in home assistant interface. If I press actual physical switches or in ewelink app is not happening, is working correctly.

**Comment by Opontios** [comment]
> Another observation: this behavior is happening when I use switches in home assistant interface. If I press actual physical switches or in ewelink app is not happening, is working correctly.

I also have noticed that if you trigger the lights off as in a "all off" group command, the slide sensor gets triggered. I have automations created with slide triggers that are executed while sending the all off command to the group that has the T5 included.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.4
