### ISSUE TITLE
[Question] Sonoff NSPanel non Pro and Pro Offline Only

### ISSUE THREAD

**Issue by DEAD1SIDE** [AlexxIT/SonoffLAN#1254]
Hey,
i'm starting to build my smart home and I was thinking of buying the NSPanel or the Pro. I'm currently looking into how to run them offline without a connection to the eWeLink cloud. I found this and saw that the NSPanel has "LAN and Cloud" Support. 
my question: Can I set up and run the NSPanel non Pro and/or Pro without them ever seeing a single byte from the outside of my network with this intigration?

**Comment by AlexxIT** [comment]
If you are afraid of clouds - you need to flush your devices with custom firmware. This component is not about break connection to cloud.
