### ISSUE TITLE
Feature request: Add Support to BasicR4

### ISSUE THREAD

**Issue by mrkaqz** [AlexxIT/SonoffLAN#1259]
I have 2 of Basic R4 linked to my account but it won't show up on HA.
I try reload the integration a few times also reboot my HA but nothing show up.

Please help add support to Basic R4

**Comment by AlexxIT** [comment]
Start from this
https://github.com/AlexxIT/SonoffLAN#issues

**Comment by mrkaqz** [comment]
After leave it run over night. it show up on the device page.
Problem sloved.
