### ISSUE TITLE
.

### ISSUE THREAD

**Issue by pedrohtd** [AlexxIT/SonoffLAN#1262]
.

**Comment by pedrohtd** [comment]
I am sorry, I thought that it was the official "page" of the Sonoff. I even
don't know who are you. Give me one moment and I will delete my comment.

**Comment by pedrohtd** [comment]
I don't know how to delete it, but I edited as a dot (.) and closed.  I
hate Sonoff now on.  I am sorry if the comment came for you instead. It's
for Sonoff, not for you. Have a great day.

**Comment by AlexxIT** [comment]
You can flash many Sonoff devices with some open firmware and use it as you want.

**Comment by pedrohtd** [comment]
Thanks man. I know, but this takes too much time. I've been tweaking my HA
for 2ys and now I got this bad surprise from them.  I am installing the
integration of the HACS and let's see what happens. I'll find a way
anyways, but everything I didn't wanted to do is waste time with something
that it was working perfectly before, do you know what I mean?  But man,
one more time, I am sorry for the comment and you are awesome for trying to
help me out.
