### ISSUE TITLE
Feature request: Support for Gledopto GL-C-008P

### ISSUE THREAD

**Issue by MarekWatroba** [AlexxIT/SonoffLAN#1265]
Gledopto GL-C-008P LED controller pairs well with Sonoff Zibgee Bridge (ZBBridge) and in eWeLink app I have full control over the diming, colour selection and white temperature selection. 
However when the device (Gledopto) pops up in HA it says it is **ZigbeeColorTunableWhiteLight** by coolkit, yet it appears as switch, and the only thing I can do is just to turn it on or off, no other control.

**Comment by AlexxIT** [comment]
You should start from https://github.com/AlexxIT/SonoffLAN#issues

**Comment by MarekWatroba** [comment]
I am unable to open the debug page, even if the debugging is enabled.
Integraion > Menu > Known issues always redirect me to Git Hub.

**Comment by AlexxIT** [comment]
Try to refresh page.
You attach diagnostics from wrong device.

**Comment by MarekWatroba** [comment]
Device diagnostics
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Warsaw",
    "os_name": "Linux",
    "os_version": "6.1.70-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.3",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "omada": {
      "version": "0.4.0-beta.1",
      "requirements": []
    },
    "sonoff": {
      "version": "3.5.4",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "electrolux_status": {
      "version": "1.2.0",
      "requirements": [
        "pyelectroluxconnect==0.3.20"
      ]
    },
    "tapo_control": {
      "version": "5.4.13",
      "requirements": [
        "pytapo==3.3.18"
      ]
    },
    "roborock": {
      "version": "1.0.13",
      "requirements": [
        "python-roborock==0.36.0",
        "ical==6.1.0",
        "dacite==1.8.0"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "custom_templates": {
      "version": "v1.2.3",
      "requirements": []
    },
    "nodered": {
      "version": "3.1.3",
      "requirements": []
    },
    "hydro_imgw": {
      "version": "v1.0.4",
      "requirements": [
        "requests"
      ]
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "solis": {
      "version": "3.5.1",
      "requirements": []
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "holidays": {
      "version": "1.9.10",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.35"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "codeowners": [
      "@AlexxIT"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "iot_class": "local_push",
    "issue_tracker": "/api/sonoff/afd858c7-77a5-4ee8-97aa-dda3b4cb4353",
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.4",
    "is_built_in": false
  },
  "data": {
    "version": "a4a8c5f",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": true
    },
    "errors": [],
    "device": {
      "uiid": 3258,
      "params": {
        "bindInfos": "***",
        "subDevId": "3c444a0f9538c1a43258",
        "parentid": "1000deefb2",
        "fwVersion": "20251203",
        "switch": "on",
        "colorTemp": 100,
        "brightness": 100,
        "hue": 183,
        "saturation": 100,
        "colorMode": "cct",
        "cctBrightness": 100,
        "rgbBrightness": 100
      },
      "model": "ZigbeeColorTunableWhiteLight",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "a480076b13"
    }
  }
}`

**Comment by AlexxIT** [comment]
OK. It's light device with many functions. You need to collect logs to all of them (color, bright, hut, saturation, color mode, etc.)

**Comment by MarekWatroba** [comment]
I'm unsure if I can collect all the required logs, so I prefer to share the device with your account.
When trying to do so, I need to provide the country code of your account, could you please share it?

**Comment by AlexxIT** [comment]
Russia +7

**Comment by MarekWatroba** [comment]
Done, feel free to test it

**Comment by MarekWatroba** [comment]
My bad, just added the correct one, Kitchen LED 1

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.6.0
