### ISSUE TITLE
sonofflan component does not work if debug is enabled

### ISSUE THREAD

**Issue by tonyp740613** [AlexxIT/SonoffLAN#127]
After updating to 2.0.4 or 2.0.5 there are errors when Home Assistant start up if debug is enabled.
[sonofflan_debug_3.txt](https://github.com/AlexxIT/SonoffLAN/files/4695448/sonofflan_debug_3.txt)

**Comment by tonyp740613** [comment]
Running 0.109.6 of home assistant

**Comment by AlexxIT** [comment]
I fix it later
