### ISSUE TITLE
Feature Request: Support for SNZB-01P

### ISSUE THREAD

**Issue by PeterD888** [AlexxIT/SonoffLAN#1271]
Any chance you can add full support for the SNZB-01P Wireless Switch.

It currently links, but only provides access to the battery level.

Support for creating automation's based on clicking / double clicking / long pressing the button is currently not supported.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/pull/1189

**Comment by PeterD888** [comment]
Thanks Alexx, but I'm not understanding your link.

If I understand correctly, this is functionality that you committed into the main branch several years ago.

I'm a fairly noob to HA, having just started using it a few months ago. My installation of your Integration would only have been done less than 2 months ago, so it should surely "work out of the box"?

**Comment by PeterD888** [comment]
For information, here is my diagnostics file
[config_entry-sonoff-db430a58a9176b8d5dff47f4cbf152b8.json(2).txt](https://github.com/AlexxIT/SonoffLAN/files/13714356/config_entry-sonoff-db430a58a9176b8d5dff47f4cbf152b8.json.2.txt)

**Comment by AlexxIT** [comment]
You need to learn how to create automations based on entity state.

**Comment by PeterD888** [comment]
Does not make sense to me - If I go to Developer Tools / States / call up that entity, it has a blank state
The battery has a state, but not the button itself

![Switch State](https://github.com/AlexxIT/SonoffLAN/assets/144859300/1997150f-f320-4dea-8111-249fdbe5bb3e)

**Comment by AlexxIT** [comment]
Because buttons don't have a persistent state. It changes during pressing for a fraction of a second.

**Comment by PeterD888** [comment]
Ok, thanks

I'll check that out

**Comment by PeterD888** [comment]
Got it working - thanks for the assistance
