### ISSUE TITLE
Feature request: Lan Mode only

### ISSUE THREAD

**Issue by FhemiR** [AlexxIT/SonoffLAN#1275]
Is it possible to force device to operate only in Lan Mode after initial setup?Means to Control it only over Lan and discount it from internet?

**Comment by AlexxIT** [comment]
You should do it on your router. Or flash custom firmware.

**Comment by FhemiR** [comment]
I want to keep the original firmware. By just blocking it from Internet from Router side would it work? I mean the credential validation.

**Comment by AlexxIT** [comment]
This is not recommended because the firmware doesn't always work well over the LAN. And then the component will be able to send the command via the cloud.

But if you "afraid" clouds - you can block Internet for your devices.
