### ISSUE TITLE
Consumption only updates 1 sonoff POW out of 2

### ISSUE THREAD

**Issue by tonyp740613** [AlexxIT/SonoffLAN#128]
I have 2 sonoff POW R2 devices on the same firmware and when I run the sonoff.update_consumption service it only updates 1 of them, the same one each time.

![image](https://user-images.githubusercontent.com/63099092/83141232-9c695c80-a0ef-11ea-9b9f-e8ea4b3dda4e.png)

**Comment by AlexxIT** [comment]
Please show logs https://youtu.be/Lt5fT4N5Pm8

**Comment by tonyp740613** [comment]
[sonofflan_debug_4.txt](https://github.com/AlexxIT/SonoffLAN/files/4699699/sonofflan_debug_4.txt)
consumption update is at the end of the log

**Comment by AlexxIT** [comment]
I think too frequent requests to the cloud bother it.
Please share both pow to my acc sonofflan@gmail.com

**Comment by AlexxIT** [comment]
I got your devices and remember about you. I haven’t had time to do yet.

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.1.1
Please feedback

**Comment by tonyp740613** [comment]
It is working great now.  Thanks.

**Comment by pdrivo** [comment]
Hi. Could moneso explain me how do I call sonoff.update_consumption servide?

**Comment by pdrivo** [comment]
Hi. Could someone explain me how do I call sonoff.update_consumption servide?

**Comment by brunokelo** [comment]
hello, how do i call sonoff.update_consumption? thanks

**Comment by tonyp740613** [comment]
To do it manually In Home Assistant go to _developer options, services_ and select sonoff.update_consumption from the list then click CALL SERVICE.

Or you can setup an automation to call the service at a preset time and/or when home assistant starts up:

- id: '1591190008529'
  alias: Sonoff update consumption
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 00:02:00
  - data: {}
    service: sonoff.update_consumption

**Comment by cfgroenewald** [comment]
> Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.1.2
> Please feedback

How do I implement this?
