### ISSUE TITLE
INCHING Duration Entity Unavailable

### ISSUE THREAD

**Issue by milandzuris** [AlexxIT/SonoffLAN#1281]
hi, why all INCHING Duration entities are Unavailable?, thx.
![image](https://github.com/AlexxIT/SonoffLAN/assets/42905545/89981874-1912-4da5-9b1b-d8c80c49f613)

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by yousaf465** [comment]
same issue with my S26 plug 

![image](https://github.com/AlexxIT/SonoffLAN/assets/83491212/58bdca55-714d-4cb2-9105-645c01d23e46)

**Comment by milandzuris** [comment]
> Show device diagnostics

[sonoff-f50f9f94515155ece9159f24a92a7368-Bedroom Light-d7fc93dade5aa4ca79a58ca716067671.json.txt](https://github.com/AlexxIT/SonoffLAN/files/13798757/sonoff-f50f9f94515155ece9159f24a92a7368-Bedroom.Light-d7fc93dade5aa4ca79a58ca716067671.json.txt)

**Comment by AlexxIT** [comment]
This is Hass 2024.1 issue https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.4
