### ISSUE TITLE
No crypto / cryptodome dependencies installed using HACS

### ISSUE THREAD

**Issue by oddbytes** [AlexxIT/SonoffLAN#129]
Hi there!

I have installed v2.04 using HACS 1.0.3. On HA restart sonoff has not started cause module Crypto was not found. Installed with pip, next restart asked for Crypto.Utils.Padding, so i have manually installed cryptodome.

Found on Linux Synology_DS 3.2.40 #24922 Mon Aug 19 12:09:30 CST 2019 armv7l GNU/Linux synology_armada370_213j

Regards,

Mack

**Comment by AlexxIT** [comment]
Please show your `/developer-tools/info`

**Comment by AlexxIT** [comment]
Check v2.0.6

**Comment by oddbytes** [comment]
Hi,

Installed 2.0.6, uninstalled cryptodome and everything is working.

Thanks!
