### ISSUE TITLE
Malfunction after core_2024.1.0 update

### ISSUE THREAD

**Issue by ivanleovitanza** [AlexxIT/SonoffLAN#1292]
hi,
after core_2024.1.0 update the integration does not update sonoff states, but the current measurements work

**Comment by Rikus102** [comment]
I'm having the same issue.

**Comment by hmmbob** [comment]
Duplicate of #1288, please close this issue and track #1288

**Comment by VaughanGerson** [comment]
Same issue with my POWR320D, after latest core update no measurement data is available, also the device is no longer in the debug log

**Comment by cheehueisutd** [comment]
Yes. I am facing the same issue. Please help. Thank you so much.

**Comment by hmmbob** [comment]
People, stop posting here and head over to #1288

**Comment by cheehueisutd** [comment]
There is a fix in #1288. Thank you!
