### ISSUE TITLE
Switch toggle on S31 smart plugs not working

### ISSUE THREAD

**Issue by the509man** [AlexxIT/SonoffLAN#1295]
After 2024.1.0 the toggle function is not working properly for my Wi-Fi smart plugs S31.  Happy New Year and thanks.

**Comment by elkadye** [comment]
try this fix https://github.com/AlexxIT/SonoffLAN/issues/1288#issuecomment-1876688902

**Comment by jamespoore** [comment]
> try this fix [#1288 (comment)](https://github.com/AlexxIT/SonoffLAN/issues/1288#issuecomment-1876688902)

This resolved the toggle issue for me. Thanks

**Comment by hmmbob** [comment]
Please close the issue :+1:

**Comment by AlexxIT** [comment]
#1285

**Comment by the509man** [comment]
The fix worked. Thank you all for the great support you provided me!
