### ISSUE TITLE
POWR316 Unavailable

### ISSUE THREAD

**Issue by wissamnad** [AlexxIT/SonoffLAN#1297]
Not sure if issue happened after the Home Assistant latest update but all my POWR316 Devices are unavailable now. **Firmware: 1.1.1**

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Beirut",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "dahua": {
      "version": "0.5.0",
      "requirements": []
    },
    "solarman": {
      "version": "1.0.0",
      "requirements": [
        "pyyaml",
        "pysolarmanv5"
      ]
    },
    "ping_arp": {
      "version": "0.1.0",
      "requirements": []
    },
    "spotcast": {
      "version": "v3.6.30",
      "requirements": []
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "alarmo": {
      "version": "v1.9.13",
      "requirements": []
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "sonoff": {
      "version": "3.5.3",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hpprinter": {
      "version": "1.0.12",
      "requirements": [
        "xmltodict==0.12.0"
      ]
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "codeowners": [
      "@AlexxIT"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.5.3",
    "is_built_in": false
  },
  "data": {
    "version": "fa68586",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": false
    },
    "errors": [],
    "device": {
      "localtype": "plug",
      "deviceid": "10017b4bb8"
    }
  }
}

**Comment by AlexxIT** [comment]
#1285
