### ISSUE TITLE
Energy consumption resetting at wrong time on some Sonoff S31 smart plugs

### ISSUE THREAD

**Issue by lordwizzard** [AlexxIT/SonoffLAN#1299]
Seeing that some Sonoff s31 are resetting energy/power consumption at 11:00 PM EST for me, while others reset at midnight (which is as it should be). I'm seeing that in on my dashboard. Will attach a screen capture later tonight. Need help in trying to locate why,

**Comment by AlexxIT** [comment]
#1256
