### ISSUE TITLE
status not updated 

### ISSUE THREAD

**Issue by engalzaid** [AlexxIT/SonoffLAN#13]
I have sonoff s26 connected by SonoffLAN and working fine when I restarted my Hass, and my sonoff was off. After my Hass up the status in dashboard was on even the status of my sonoff  was off! 
how to make the status sync with current status after restart?

**Comment by AlexxIT** [comment]
HA forgets all sonoff devices every restart. Devices only appear when they report again about themselves via Multicast.

**Comment by engalzaid** [comment]
Thanks
