### ISSUE TITLE
Errors with 2.05

### ISSUE THREAD

**Issue by Mibo999** [AlexxIT/SonoffLAN#130]
Hi,

tried to install version 2.05 and getting the following errors:

Component error: sonoff - No module named 'Crypto.Util.Padding'
Component error: sonoff - cannot import name 'ConsumptionHelper' from 'custom_components.sonoff.sonoff_cloud' (/home/pi/hass_config/custom_components/sonoff/sonoff_cloud.py)

How to solve.

Regards
Mikael

**Comment by AlexxIT** [comment]
Duplicate #129

**Comment by AlexxIT** [comment]
Please show your `/developer-tools/info` System Health section.

**Comment by AlexxIT** [comment]
Check v2.0.6
