### ISSUE TITLE
TEMP_CELSIUS versus UnitOfTemperature.CELSIUS

### ISSUE THREAD

**Issue by clangren** [AlexxIT/SonoffLAN#1300]
Logged this error in HomeAssistantCore after updating to HA Core 2024.1

TEMP_CELSIUS was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

Happy to provide any addtional information which assists.

**Comment by AlexxIT** [comment]
#1278

**Comment by clangren** [comment]
Sorry - I did do a seach, obviously not a good enough one.
