### ISSUE TITLE
NS Panel (not pro) motion sensor 

### ISSUE THREAD

**Issue by HACS-bank** [AlexxIT/SonoffLAN#1302]
I have four NS Panel connected to HA using this excellent integration. The temperature and humidity sensors, and the two buttons, work as expected. 

The motion sensor however, always seems to show "motion detected".  Is this sensor supported? It doesn't seem to be there in the eWeLink app.

If this can be used it would be useful; if it doesn't really work then I can disable it 😀

**Comment by HACS-bank** [comment]
![Screenshot_20240104_234212_Home Assistant.jpg](https://github.com/AlexxIT/SonoffLAN/assets/84039996/43c3ab5f-76fc-4cc4-9047-49b8fbf3b996)

**Comment by AlexxIT** [comment]
Don't know what you talking about. NS Panel's spec don't have motion sensor.

https://github.com/AlexxIT/SonoffLAN/blob/98ae182087308f958ed13108c4b2c5d9248e9627/custom_components/sonoff/core/devices.py#L275-L283

**Comment by HACS-bank** [comment]
My mistake. I had a different device configured with the same name. It doesn't really do motion detection either.
