### ISSUE TITLE
Why is an eWeLink Account needed??

### ISSUE THREAD

**Issue by oywino** [AlexxIT/SonoffLAN#1308]
I have several Sonoff devices in DIY use, fully integrated into Home Assistant via a Tasmotized Sonoff ZB-Bridge and Z2M. I never had to create any eWeLink account!  So why do I need such an account to use your Sonoff LAN integration if I have no plans to use any cloud based Sonoff devices?
Isn't the whole point to de-Cloud things (by, by Sonoff cloud)?

**Comment by AlexxIT** [comment]
I don't know why you ask this. It's up to you to decide why.

**Comment by oywino** [comment]
No, the only way to install and use this integration is og you have an eWeLink account. That step cannot be bypassed.

**Comment by AlexxIT** [comment]
That's not true.

**Comment by oywino** [comment]
> That's not true.

No?
So how do you pass by this screen? 
![Screenshot_20240106_141255_Home Assistant](https://github.com/AlexxIT/SonoffLAN/assets/18447119/0f592a20-f54f-4678-ba16-911f996a4bc7)

**Comment by AlexxIT** [comment]
Just to read what it says

**Comment by oywino** [comment]
Ah! Of course - How stupid am I ?  
No excuse 😥
Thank you .....
