### ISSUE TITLE
It's working fine but ?

### ISSUE THREAD

**Issue by retromarky** [AlexxIT/SonoffLAN#131]
SonoffLAN installed and it found my devices on installation, how ever i've added a new plug since  but it does not show up on sonoffLAN  . It shows up in eWeLink app ok, any ideas

**Comment by AlexxIT** [comment]
Device list updates only with start HA.

**Comment by retromarky** [comment]
I don't understand your comment. I have done a restart, still no new devices showing. Do i have to do a reinstall of SonoffLAN ?

**Comment by AlexxIT** [comment]
What's your component version? Do you use `mode: local`?

**Comment by retromarky** [comment]
Version v2.1.0
sonoff:
  username: mymail@gmail.com
  password: mypassword
  mode: local
  reload: always  # update device list every time HA starts
No i do not use mode: local
I've tried it now 
NO FIX

**Comment by retromarky** [comment]
Configuration
Entities
The new device shows up in the above.

**Comment by AlexxIT** [comment]
No problem now?

**Comment by retromarky** [comment]
The device is not showing in Overview
(sonoff POWR2)

**Comment by retromarky** [comment]
manufacturer
Sonoff
model
Pow_R2
sw version
PSC-B67-GL v3.4.0
cloud
online
rssi
-49
power
0.00
current
0.00
voltage
235.83
local
online

**Comment by AlexxIT** [comment]
I think you turned off automatic filling overview. And now you must add the device there manually.

Or look for instructions on how to enable back automatic filling in the community.

**Comment by retromarky** [comment]
I went in to Overwiew
then Entities card configuration and added in manually
All working now thanks for your help
