### ISSUE TITLE
L1 led strip not available after 2024.1.1 core update

### ISSUE THREAD

**Issue by Kydonakis** [AlexxIT/SonoffLAN#1310]
I tried both SonoffLAN v3.5.3 and v3.5.4 but result is the same.

Once I get the 2024.1.1 core update the two Sonoff L1 devices (led strips) I own disappear from the system. eWelink works normal and devices can be operated. Both devices remain online during the update and testing. All other devices (including the L2 led strip) seems to operate normally after the update.

When downgrading to core 2023.12.4, the two L1 led strip are again available.

Relevant entries I find in the logs are:

`  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Athens",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true`

`2024-01-06 08:31:18.885 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.sonoff_1000ee2049 are missing or not currently available`

`    "errors": [],
    "device": {
      "uiid": 59,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "sledOnline": "on",
        "rssi": -85,
        "fwVersion": "3.4.3",
        "staMac": "***",
        "switch": "off",
        "light_type": 1,
        "colorR": 191,
        "colorG": 0,
        "colorB": 255,
        "bright": 49,
        "mode": 1,
        "speed": 100,
        "sensitive": 5,
        "only_device": {
          "ota": "success"
        },
        "ssid": "***",
        "bssid": "***"
      },
      "model": "L1",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "1000ee2049"`

**Comment by bbasti16** [comment]
Have you updated the sonoff integration from HACS?

**Comment by Kydonakis** [comment]
> bbasti16

Yes, always.

**Comment by CraigBell** [comment]
Similar issue with 4 of my LED bulbs, all other devices are working now after 3.5.4. 

The logs sate:

Logger: custom_components.sonoff.core.entity
Source: custom_components/sonoff/core/entity.py:86
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 6 January 2024 at 16:54:30 (4 occurrences)
Last logged: 6 January 2024 at 16:54:32

Can't init device: {'name': 'Garage Outside Light', 'deviceid': '1000b3e429', 'apikey': 'REMOVED', 'extra': {'uiid': 103, 'description': '', 'brandId': '5da282716cc4c3b59fa01a81', 'apmac': 'd0:27:01:67:c5:a3', 'mac': 'd0:27:01:67:c5:a2', 'ui': '双色冷暖灯_支持随调及场景', 'modelInfo': '5da686d0f8544da50466b402', 'model': 'WTW-705-GL', 'manufacturer': '贵州财富之舟科技有限公司'}, 'brandName': 'FortuneShip', 'brandLogo': '', 'showBrand': True, 'productModel': 'FS-1', 'tags': {'m_65c6_crai': 'on'}, 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5e95f133e75aa80007ed14e1', 'index': -4}, 'shareTo': [], 'devicekey': 'c71b0ded-6321-4c61-a422-4dc20a245a83', 'online': True, 'params': {'bindInfos': {'alexa': [], 'gaction': ['9e78bd7d-1564-4e77-9621-e9fe9ca165c6_ewelinkGoogleHome']}, 'version': 7, 'switch': 'off', 'ltype': 'white', 'white': {'br': 100, 'ct': 0}, 'fwVersion': '1.4.8', 'sequence': '1704302879000', 'selfApikey': '123', 'bright': {'br': 100, 'ct': 255}, 'nightLight': {'br': 5, 'ct': 0}, 'computer': {'br': 20, 'ct': 255}, 'read': {'br': 50, 'ct': 0}}, 'isSupportGroup': True, 'isSupportedOnMP': True, 'isSupportChannelSplit': False, 'deviceFeature': {}, 'device_class': 'light'}

**Comment by Kydonakis** [comment]
Since it appears that L1/L2 might have some problem in the latest versions of core, is there any feedback from the developers?

I also tested core v. 2024.1.2 with SonoffLAN v3.5.4 and the L1 ledstrip remains unavailable.

**Comment by Kydonakis** [comment]
So many issues reported in here lately. Tested on 2024.01.04 core version and the L1 ledstrips disappear.

I wish AlexxIT could verify he is working on solutions.

Until then so many of us are trapped in 2023.12.4 core I guess.

**Comment by Kydonakis** [comment]
Thanks @AlexxIT for the reply. Once I saw the exact error message, I reported it [here](https://github.com/AlexxIT/SonoffLAN/issues/1333#issue-2104815623). Please let me know if you can see anything strange or hints for the cause.

**Comment by AlexxIT** [comment]
@Kydonakis OK, so I will close this issue and let's continue there.
