### ISSUE TITLE
NSPanel setting temperature 

### ISSUE THREAD

**Issue by ivgo** [AlexxIT/SonoffLAN#1320]
How can I control thermostat. ClimateEntity is not active.
![sonnof](https://github.com/AlexxIT/SonoffLAN/assets/10232491/0bbc48db-82db-4022-9430-9fc4e2bbf5dc)
[sonoff-70c6783a988ca74a2de359fb85a3227a-Bad-b401bebe2b84e33d5763650329a605d0.json (1).txt](https://github.com/AlexxIT/SonoffLAN/files/13929843/sonoff-70c6783a988ca74a2de359fb85a3227a-Bad-b401bebe2b84e33d5763650329a605d0.json.1.txt)

**Comment by MatthiasVanDE** [comment]
It's because of the new update from HA; you need to roll it back and skip it

**Comment by ivgo** [comment]
which version?

**Comment by ivgo** [comment]
Or will there be an update coming out next? Can you change something?

**Comment by MatthiasVanDE** [comment]
Rollback to core_2024.1.2

**Comment by ivgo** [comment]
Bekomme Error 

WARNING (MainThread) [homeassistant.helpers.entity] Entity sonoff.sonoff_100162ee34 (<class 'custom_components.sonoff.climate.XClimateNS'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature: 0>, please create a bug report at /api/sonoff/ and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by ivgo** [comment]
Perhaps this is somehow related

HVAC_MODE_HEAT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/rospogrigio/localtuya/issues
HVAC_MODE_OFF was used from localtuya, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/rospogrigio/localtuya/issues
SUPPORT_TARGET_TEMPERATURE was used from spaclient, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-spaclient/issues
HVAC_MODE_HEAT was used from spaclient, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-spaclient/issues
HVAC_MODE_OFF was used from spaclient, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-spaclient/issues

**Comment by AlexxIT** [comment]
This is the default behaviour. You need to activate it
