### ISSUE TITLE
Crashed - this is a deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by mrchris82** [AlexxIT/SonoffLAN#1322]
Hi, please help with the above. Thanks

Logger: homeassistant.components.fan
Source: helpers/deprecation.py:205
Integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 20:25:39 (6 occurrences)
Last logged: 20:25:44

SUPPORT_PRESET_MODE was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

SUPPORT_SET_SPEED was used from sonoff, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

**Comment by digdilem** [comment]
FIXED, at least for me. I had forgotten this was a HACS integration, and there was an update pending in there. 

Applied that, restarted HA, and all is working again. Thanks.

**Comment by digdilem** [comment]
@mrchris82 you may wish to check this on yours, and if it fixes it, close this issue. Thank you.

**Comment by mrchris82** [comment]
My fault thought hacs had auto update or would inform me. My apologies
