### ISSUE TITLE
Only POW R1 devices are unavailable 

### ISSUE THREAD

**Issue by edpenas** [AlexxIT/SonoffLAN#1330]
I just noticed that i have some devices unavailable on closer inspection its only older POW. R1 that are affected the rest {Basic , Pow elites, POW r2 , S31 }are ok

**Comment by julian4646** [comment]
Anyone make progress on this ? - Ive tried restoring old backups, downgrading - reconfigured - nothing seems to bring them back (three temp sensors down now) - (SNZB-02D, SNZB-02, SNZB-02P) - other Zigbee devices working fine

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#issues
