### ISSUE TITLE
PTZ is not working on GK-200MP2-B

### ISSUE THREAD

**Issue by felipebraz** [AlexxIT/SonoffLAN#1331]
I have an GK-200MP2-B and I can't make the PTZ work in HA.
My camera is on 50520230320 firmware version and I already tried to call the service lots os times but no success.

`service: sonoff.send_command
data:
  device: "xxxxxx"
  cmd: up
`

The Integration in HACS is updated also.

I couldn't find any errors on HA logs, it just doesn't work.

**Comment by AlexxIT** [comment]
#1187
