### ISSUE TITLE
4ChPror3 doesn't work after 2023.12.3

### ISSUE THREAD

**Issue by dsetta13** [AlexxIT/SonoffLAN#1334]
Sonoff integration does not work with sonoff 4ChPror3 after update 2023.12.3. I have tried every update through 2024.1.6... Reverted back to 12.3 for now

**Comment by deinloft** [comment]
Same issue with Sonoff 4CH

**Comment by KevinFromUpThere** [comment]
Same issue with the S40TPB Smart Plugs!  LOL wife not happy! :D   Open to suggestions!

**Comment by KevinFromUpThere** [comment]
Manually added the latest version of SonoffLAN and it works again!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#issues
