### ISSUE TITLE
Sonoff TVRZB Thermostatic Radiator Valve

### ISSUE THREAD

**Issue by kazdajan86** [AlexxIT/SonoffLAN#1336]
![Snímek obrazovky 2024-02-04 093123](https://github.com/AlexxIT/SonoffLAN/assets/156926459/561f35cf-5160-4b79-bbb5-021360c9b5cf)

Hello,

I bought a Sonoff bridge Pro + Sonoff TVRZB (thermostat head) and I don't see any important entities. I would like to see the current temperature and the desired temperature. Could you do an update?

**Comment by zipzipro** [comment]
Ahoj,
hlavici mám připojenou přes SkyConnect v1.0 a v HA je vše zobrazeno, mimo chytré plánování jako je v app eWelink, ale to jde nahradit automatizací v HA.
Hlavice připojená přes Sonoff ZBBridge PRO se správně zobrazuje pouze v app eWelink, v HA lze hlavici připojenou přes Sonoff ZBBridge PRO pouze zapínat a vypínat, termostat jak píšeš tam bohužel není, proto doporučuji hlavici připojit přes ZigBee2MQTT protokol ZigBee 3.0 přes HA.
Zobrazení hlavice v HA přes SkyConnect v1.0:
![Screenshot_20240130_192649_Home Assistant](https://github.com/AlexxIT/SonoffLAN/assets/150837500/99fa6255-bef4-43be-83ab-2763382b1964)
![SmartSelect_20240130_220741_Home Assistant](https://github.com/AlexxIT/SonoffLAN/assets/150837500/2e2c407e-3ff3-4dfe-aafd-3a26dcd09dcd)
![SmartSelect_20240130_193259_Home Assistant](https://github.com/AlexxIT/SonoffLAN/assets/150837500/0e059317-21f7-4190-9645-556deecf3b47)

**Comment by kazdajan86** [comment]
> Ahoj, hlavici mám připojenou přes SkyConnect v1.0 a v HA je vše zobrazeno, mimo chytré plánování jako je v app eWelink, ale to jde nahradit automatizací v HA. Hlavice připojená přes Sonoff ZBBridge PRO se správně zobrazuje pouze v app eWelink, v HA lze hlavici připojenou přes Sonoff ZBBridge PRO pouze zapínat a vypínat, termostat jak píšeš tam bohužel není, proto doporučuji hlavici připojit přes ZigBee2MQTT protokol ZigBee 3.0 přes HA. Zobrazení hlavice v HA přes SkyConnect v1.0: ![Screenshot_20240130_192649_Home Assistant](https://private-user-images.githubusercontent.com/150837500/302118218-99fa6255-bef4-43be-83ab-2763382b1964.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjc1MTYsIm5iZiI6MTcwNzEyNzIxNiwicGF0aCI6Ii8xNTA4Mzc1MDAvMzAyMTE4MjE4LTk5ZmE2MjU1LWJlZjQtNDNiZS04M2FiLTI3NjMzODJiMTk2NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMDAwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mjk4YTQ2ZGNlM2ZjNjYxYzQ3ZTg4ZTQ1MWE5YzI2ZDE0NTdkM2M3ZDMyNmQ3MjFjZmJjOTAwMmYyMDAzYTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z3LUga1N1rJJGCfjI3bpzfvBzm_UPnh-NvXFyjEMZMs) ![SmartSelect_20240130_220741_Home Assistant](https://private-user-images.githubusercontent.com/150837500/302118228-2e2c407e-3ff3-4dfe-aafd-3a26dcd09dcd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjc1MTYsIm5iZiI6MTcwNzEyNzIxNiwicGF0aCI6Ii8xNTA4Mzc1MDAvMzAyMTE4MjI4LTJlMmM0MDdlLTNmZjMtNGRmZS1hYWZkLTNhMjZkY2QwOWRjZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMDAwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzExMWM2NTY4ZWUxYzUxNjQ3YmQ4NmY1MjljNDg2MDNjYjkwNTNhZDBjOGE0NzdhYTAxYzJlMjUwMDBmNmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I2kFX5hDVqSWovECvr2gzzzu33fdcSW2kQAc0DjkTAU) ![SmartSelect_20240130_193259_Home Assistant](https://private-user-images.githubusercontent.com/150837500/302118263-0e059317-21f7-4190-9645-556deecf3b47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjc1MTYsIm5iZiI6MTcwNzEyNzIxNiwicGF0aCI6Ii8xNTA4Mzc1MDAvMzAyMTE4MjYzLTBlMDU5MzE3LTIxZjctNDE5MC05NjQ1LTU1NmRlZWNmM2I0Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMDAwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGZmMTJkY2Q0YzkwMGFhOWE0M2QwY2NhODJhMGE3MTI0YzNkNDRkZmVmOWI5MzIzOTBhMDZkMzAxNzFkZDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Tih1ij1hYy7VmyhgRD6g8ScCdGiXoyjF04GOI9x7bc)

díky za radu. používám HA na synology v dockeru a tam jsou pro mě trošku problémová nastavení USB sticků. Prostě to neumím a z návodů to nevykoukám, zvažuji flashnutí sonoff bridge pro na firmware tasmota a to by mělo chodit pak jednoduše přes Zigbee home automation (ZHA).. aspoň tedy doufám. Máte nějaké zkušenosti s tímto? Jaká je spokojenost s těmito hlavicemi? Mám zatím jednu na zkoušku, tak se ještě mohu rozhodnout zda zůstanu u sonoff nebo půjdu jinam. Případné rady nebo dokonce vzdálenou pomoc uvítám.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/1244
