### ISSUE TITLE
Another method to extract devicekey

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/SonoffLAN#134]
I noticed that in Your manual only method to check devicekey is to reset device and check it via browser. There is second possibility to do that without doing reset. In HA's config directory there is hidden file named .sonoff.json which contains all devices loaded from cloud along with their names and devicekeys. Its kind of messy there, but all devicekeys are possible to find.

I think its worth adding in case someone want to skip ewelink cloud and don't lose device settings.

**Comment by AlexxIT** [comment]
This file just creates my component when filling the login and password.
In local mode, all data is downloaded from this file even when there is no Internet connection.
You can remove the username / password from the config - everything will continue to work.
This is all described in the readme.
