### ISSUE TITLE
Automations not working when using sensors from Sonoff Addon

### ISSUE THREAD

**Issue by Dorinutu** [AlexxIT/SonoffLAN#1340]
The HA Automations are not working when using sensors from Sonoff Addon.
If I use the sensors from eWeLink addon automations are working fine.

In HA dashboard the values for the sensors are correct but somehow they are not used in automation.

I use the latest Sonoff Addon and latest HA.

**Comment by AlexxIT** [comment]
This project not related to ewelink addon

**Comment by Dorinutu** [comment]
The ticket is for Sonoff Addon not for eWeLink.

**Comment by AlexxIT** [comment]
Start from this https://github.com/AlexxIT/SonoffLAN#issues
