### ISSUE TITLE
Fix Hass 2024.2 climate entity deprecation

### ISSUE THREAD

**Issue by sebastiangebosz** [AlexxIT/SonoffLAN#1341]
Hi. After the update, I have a warning in the log.
Everything works ok. Thanks for your work

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klimat (documentation, issues)
First occurred: 14:12:12 (2 occurrences)
Last logged: 14:12:12

Entity sonoff.sonoff_1000e5a55c (<class 'custom_components.sonoff.climate.XClimateTH'>) implements HVACMode(s): off, heat, cool, dry and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
Entity sonoff.sonoff_1000e5a54f (<class 'custom_components.sonoff.climate.XClimateTH'>) implements HVACMode(s): off, heat, cool, dry and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

**Comment by AlexxIT** [comment]
Correct message - please check that you are using the latest version of the component

**Comment by sebastiangebosz** [comment]
> Correct message - please check that you are using the latest version of the component

I use version SonoffLAN v3.5.4 
Core 2024.2.0
Supervisor 2024.01.1
Operating System 11.5

Firmware of TH16R2 :  3.5.0


previously, before the update to HA 2024.02, this information was not in the log

**Comment by AlexxIT** [comment]
Please show device diagnostics

**Comment by sebastiangebosz** [comment]
[sonoff-d6127c3e6345e5772ea3df263b78e947-Spiżarnia-f51f9681fc3fc59a4e1c4d21e05874ea.json](https://github.com/AlexxIT/SonoffLAN/files/14221934/sonoff-d6127c3e6345e5772ea3df263b78e947-Spizarnia-f51f9681fc3fc59a4e1c4d21e05874ea.json)

**Comment by AlexxIT** [comment]
I can see you using latest version. Are you sure you have this warning with this version?

**Comment by RealLord** [comment]
@AlexxIT If you can defeat this alert, can you explain what are you doing for this? 
I have the same warning in another climate integration, i was implemented all needed methods, but warning still present. And this issue doesn't have clear explanation in documentation. 
Adding this into integraton doesn't disable warning:
```
    def turn_on(self) -> None:
        pass
    def turn_off(self) -> None:
        pass

```

**Comment by AlexxIT** [comment]
https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.6.0
