### ISSUE TITLE
Power, current, volt not update in lan mode

### ISSUE THREAD

**Issue by pilurizzu** [AlexxIT/SonoffLAN#1343]
Values of power, current, volts before updated every few seconds , now (last release of ha) stuck. It change only when i open sonoff app.

**Comment by AlexxIT** [comment]
I don't think this related to Hass update. This can be related to device firmware update or problem with cloud connection.

**Comment by pilurizzu** [comment]
No firmware update in last year. All is same. Maybe sonoff changed anything of refresh rate?
If i go in sonoff app it refresh values only if i push refresh button.
Could you do something in your integration?

**Comment by AlexxIT** [comment]
I haven't saw any button earlier. Looks like they have change update logic

**Comment by pilurizzu** [comment]
New release of home assistant app, fix problem. Thank you

**Comment by AlexxIT** [comment]
Yet again. I don't think this is related to Hass update.
