### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by hairy-dog** [AlexxIT/SonoffLAN#1344]
I can't find this inside home assistant. 

If I try to add this repository, I get "https://github.com/AlexxIT/SonoffLAN is not a valid add-on repository"

Am I doing something wrong, or is it broken?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#installation

**Comment by hairy-dog** [comment]
Thank you for the quick response.

Unfortunately, your response, although quick, does not solve the problem. Those are the instructions I was carefully followong when I ran into this problem.

The instructions you link to tell me to add an integration that does not appear on the list, with or without refreshing my browser cache.

"Or manually copy sonoff folder from [latest release](https://github.com/AlexxIT/SonoffLAN/releases/latest) to custom_components folder in your config folder." but as a new user of Home Assistant Operating system, I have no idea how to transfer files into my config folder. 

And I still don't have an address for  valid repository for this addon. Is there one?

**Comment by hairy-dog** [comment]
This is still showing as closed, but it is not resolved. 

Should I start again, posting a new issue?
