### ISSUE TITLE
Still can't install. 

### ISSUE THREAD

**Issue by hairy-dog** [AlexxIT/SonoffLAN#1345]
Thank you for the quick response.

Unfortunately, your response, although quick, does not solve the problem. Those are the instructions I was carefully following when I ran into this problem.

The instructions you link to tell me to add an integration that does not appear on the list, with or without refreshing my browser cache.

"Or manually copy sonoff folder from [latest release](https://github.com/AlexxIT/SonoffLAN/releases/latest) to custom_components folder in your config folder." but as a new user of Home Assistant Operating system, I have no idea how to transfer files into my config folder. 

And I still don't have an address for  valid repository for this addon. Is there one?

_Originally posted by @hairy-dog in https://github.com/AlexxIT/SonoffLAN/issues/1344#issuecomment-1943583716_

**Comment by AlexxIT** [comment]
This is not addon. This is custom component. You need to learn more about Hass.
Just search lessons how to install custom component.
This repository is not related to teaching the basics of Hass.

**Comment by hairy-dog** [comment]
You are ignoring the fact that your instructions do not work, whether it is an addon or a custom component.

Clearly, installing this would be a mistake in any case: it is developed by someone with an attitude problem, who refuses to offer help or realise when he has made a mistake.

**Comment by AlexxIT** [comment]
You just didn't read the instructions carefully enough. HACS is a link to Home Assistant Community Store

https://github.com/AlexxIT/SonoffLAN#installation

> [HACS](https://hacs.xyz/) > Integrations > Plus > SonoffLAN

**Comment by hairy-dog** [comment]
Yes, that link takes me to   
  
"Installation
  

  
HACS  >  Integrations  >  Plus  >  SonoffLAN"
  

  
which does not exist.   
  

  
That's the issue I'm reporting and the issue you are ignoring.
  

  

  
  

  
  
  
  
>

**Comment by AlexxIT** [comment]
SonoffLAN third popular default integration in the HACS. So can't confirm your words.

![Screenshot_20240214-184900.png](https://github.com/AlexxIT/SonoffLAN/assets/511909/3a88feb9-116a-4585-b00c-a9750fe83cb2)
