### ISSUE TITLE
SonoffLan error 406

### ISSUE THREAD

**Issue by marinus61** [AlexxIT/SonoffLAN#1346]
Hi there

Using SonoffLan for a long time, but after latest update i get:

´´´Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:323
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 17:27:29 (9 occurrences)
Last logged: 17:53:06

Cloud WS exception

Traceback (most recent call last): File “/config/custom_components/sonoff/core/ewelink/cloud.py”, line 323, in connect raise Exception(resp) Exception: {‘error’: 406, ‘reason’: ‘Authentication Failed’, ‘apikey’: ‘94ca39b6-f663-40d1-89ee-730b4ad6e3b5’, ‘sequence’: ‘1707928049629’, ‘actionName’: ‘userOnline’}‘’’

First update error was last HA verison in January, and I managed to make it work again.

Latest update yesterday Core 2024.2.1 / operating system 11.5, it fail with the above error message

I have tried the suggestion found on github, but error persists

Any one having a suggestion

Marinus

**Comment by Henning5** [comment]
I have the same problem.

**Comment by marinus61** [comment]
@Henning5 
I believe that it might be a SonoffLan integration error, I have two installations and both report the same issue, although one of my installations is running
Core 23.11.2 and the other 24.2.1
OS 11.1 and 11.5

Both have few days ago updated the SonoffLan

**Comment by AlexxIT** [comment]
#1011

**Comment by AlexxIT** [comment]
PS. "Authentication Failed" can be if you logged in with same account from another place.
