### ISSUE TITLE
Device groups in ewelink broke SonoffLAN

### ISSUE THREAD

**Issue by Kodlitko** [AlexxIT/SonoffLAN#1347]
Hello all,

I created a group of two lights (Sonoff MINIR4 fw1.0.1) in eWeLink app and now SonoffLAN does not work. I am getting this error when tried to reload integration or restart HA:
```
Logger: homeassistant
Source: custom_components/sonoff/__init__.py:325
Integration: Sonoff (documentation, issues)
First occurred: 14:12:00 (2 occurrences)
Last logged: 14:18:46

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 252, in internal_normal_setup
    await internal_cache_setup(hass, entry, devices)
  File "/config/custom_components/sonoff/__init__.py", line 279, in internal_cache_setup
    devices = internal_unique_devices(entry.entry_id, devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/__init__.py", line 325, in internal_unique_devices
    if UNIQUE_DEVICES.setdefault(device["deviceid"], uid) == uid
                                 ~~~~~~^^^^^^^^^^^^
KeyError: 'deviceid'
```

When group is deleted in ewelink, integration works normally. I did not found anything about issues with device grouping in app so it might be a bug :-)

Debug logs attached. Between 14:35 and 14:40 I deleted group in ewelink app and then reloaded integration.

System health page before:
![image](https://github.com/AlexxIT/SonoffLAN/assets/42772673/a83a0fa5-47ae-4e11-9059-569746968d2d)
System health page after:
![image](https://github.com/AlexxIT/SonoffLAN/assets/42772673/be2631d6-ddbd-4df9-83ed-f6c18a571fbf)

[config_entry-sonoff-7a775c7fe5050138278434c01236afd4.json](https://github.com/AlexxIT/SonoffLAN/files/14311575/config_entry-sonoff-7a775c7fe5050138278434c01236afd4.json)
[home-assistant_sonoff_2024-02-16T14-08-24.796Z.log](https://github.com/AlexxIT/SonoffLAN/files/14311998/home-assistant_sonoff_2024-02-16T14-08-24.796Z.log)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.7.0
