### ISSUE TITLE
Sonoff 4CHPro used to be sensor.xxxxxx is after update a switch.xxxxxx

### ISSUE THREAD

**Issue by OJBender** [AlexxIT/SonoffLAN#1348]

**Comment by OJBender** [comment]
After updating to 5.6 the HomeAssistant logs are missing their sensor, now expecting a switch. What is the best way to fix this sustainably? 

Logger: homeassistant.helpers.service
Source: helpers/service.py:250
First occurred: 9:54:23 AM (123 occurrences)
Last logged: 1:30:48 PM

    Referenced entities switch.sonoff_10015bc4ec_1 are missing or not currently available
    Referenced entities switch.sonoff_10015bc4ec_2 are missing or not currently available
    Referenced entities switch.sonoff_10015bc4ec_3 are missing or not currently available
    Referenced entities switch.sonoff_10015bc4ec_4 are missing or not currently available

**Comment by AlexxIT** [comment]
I don't know what is 5.6. I didn't release anything like that

**Comment by OJBender** [comment]
> I don't know what is 5.6. I didn't release anything like that

My bad. v3.6.0 I meant. :-/

**Comment by AlexxIT** [comment]
Well you needs to install latest version. Oldest can be incompatible with never Hass

**Comment by OJBender** [comment]
latest version installation reports "Failed to call service update/install. Empty filename."
any way to force update on command line?
<img width="323" alt="image" src="https://github.com/AlexxIT/SonoffLAN/assets/67625635/0aa4ab4d-7ce8-446a-8f2e-db9dbadfd011">

HA core is 2024.2.2 latest

**Comment by OJBender** [comment]
If you like you can close the issue. I tasmotized the 4CH Pro.
