### ISSUE TITLE
Version 3.6 not installing

### ISSUE THREAD

**Issue by cvasantrao** [AlexxIT/SonoffLAN#1350]
Try updating to v3.6 but update failed and integration was broken.

**Comment by Batou38** [comment]
Same here... not even downloading correctly from HACS... I'll try a manual install and keep you posted.

**Comment by Batou38** [comment]
OK so I am confirming that the issue is on the install process. Copying manually the repo into custom components folder let me reinstall correctly the last version. I am not able to say more... Might be an issue with HACS...

**Comment by cvasantrao** [comment]
Manually installed by copying the sonoff folder into custom_integration folder. Everything worked as before.

**Comment by cvasantrao** [comment]
Closing the issue

**Comment by cvasantrao** [comment]
Closed as issue is resolved.
