### ISSUE TITLE
ifan04 duplicated

### ISSUE THREAD

**Issue by patchido** [AlexxIT/SonoffLAN#1353]
With this integration i am getting my entities duplicated, tried in auto and LAN and it happens in both cases, im usign the latest release via HACS, also latest firmware 3.5.0

the pair that has no "sonoff" in the entity name i cant even see the properties to see from where its being added, i am guessing the config storage adds an extra unit?

![image](https://github.com/AlexxIT/SonoffLAN/assets/2708577/479130d3-03f4-4307-a84c-19c58f5764ff)
![image](https://github.com/AlexxIT/SonoffLAN/assets/2708577/80820752-f01b-4bf5-9d65-7e7dc5995e88)

**Comment by AlexxIT** [comment]
This is entities from different integrations. You can see integration name in the table column.

**Comment by patchido** [comment]
> This is entities from different integrations. You can see integration name in the table column.

if i delete the sonoff integration the 4 of them disappear after HA restart, my guess its adding from the config?

**Comment by AlexxIT** [comment]
Maybe you have added them manually. I don't know. Check column Integration
