### ISSUE TITLE
SNZB-06P presence sensor

### ISSUE THREAD

**Issue by tammeryousef1006** [AlexxIT/SonoffLAN#1359]
![Screenshot 2024-03-13 144933](https://github.com/AlexxIT/SonoffLAN/assets/62266828/a6cc9a1a-3218-40eb-9d39-b4078b18b81a)
kindly note i added SNZB presence sensor at NSpanel pro zigbee , its already appear the device at sonoff lan integration but without entity , at the attributes i can see all changes , is it possible to add support for this device please

**Comment by tammeryousef1006** [comment]
![Uploading Screenshot 2024-03-13 144933.png…]()

**Comment by tammeryousef1006** [comment]
![Screenshot 2024-03-13 144933](https://github.com/AlexxIT/SonoffLAN/assets/62266828/65b4bd1d-8f96-4fdf-9a72-1f77e69f49a5)
here is the reading from Attributes

**Comment by Yiken115** [comment]
I have the same issue and am trying to use it to trigger my lights to turn on and off but am unable to do so without the entities for the blueprints. 

Appreciate if this can be looked into, thanks!

**Comment by RTouris** [comment]
Can I also chime in just to ask for the dev to tweak the coloring scheme for these sensors in order for these to follow the motion sensors one. Here's a screenshot - guess which TWO entries relate to the Presence sensors ;)

![tempImagehu2LNZ](https://github.com/AlexxIT/SonoffLAN/assets/45532716/85d7fe17-a4c2-4815-a49a-683d1bbb5da2)

**Comment by patrickgmail** [comment]
Hi.
Same for me. Below the view by Sonofflan
![image](https://github.com/AlexxIT/SonoffLAN/assets/10470772/6cd1b495-fb49-4c7e-8762-be8f04977f22)
I'm unable to use it for any automation.

Another one connected by zigbee2mqtt
![image](https://github.com/AlexxIT/SonoffLAN/assets/10470772/ed4a43ae-2b70-4d0a-8130-96fd7096981f)
In this case, it's usefull for HA automation

**Comment by AlexxIT** [comment]
#1245

**Comment by malanleroux** [comment]
Hi @AlexxIT.

I recently got the SNZB-06P Human Presence Sensor. And the only Sensor being detected is the Motion.
My understanding is that there should be two sensors.
1. Motion
2. Occupancy

As per this [video](https://www.youtube.com/watch?v=z5SJdtf4cgQ).
![image](https://github.com/AlexxIT/SonoffLAN/assets/130469482/a1f2d4c7-3ab1-4c6b-a3c5-555203a38a58)

Would it be possible to add that support for the SNZB-06P device?
