### ISSUE TITLE
Fix expected device class for energy_day sensor

### ISSUE THREAD

**Issue by elax46** [AlexxIT/SonoffLAN#1377]
Hi everyone, I wanted to add the daily energy sensor in the individual devices section to the energy dashboard but HA gives me an error

```
The following entities do not have the expected device class:
sensor.sonoff_XXXXXX_energy_day

```

**Comment by elax46** [comment]
Hi @AlexxIT , will it take a long time to implement a fix?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.7.0

**Comment by elax46** [comment]
thank you for your great work

**Comment by AlexxIT** [comment]
This is not a sensor. It's energy tab. I'm not sure if this sensor can be used there

**Comment by elax46** [comment]
I'm sorry why wouldn't it be possible to use it? my goal is to display the consumption of the single pow316 perhaps it would be more correct to use `sensor.sonoff_XXX_power` but from the individual devices section it is not possible to add it

**Comment by AlexxIT** [comment]
Because it's data from cloud with daily energy. It is reset to zero every day, resulting in negative values in the statistics

**Comment by elax46** [comment]
> Because it's data from cloud with daily energy. It is reset to zero every day, resulting in negative values in the statistics

Yes, you are absolutely right about the daily sensor but why is it not possible to insert the power sensor in Watts? I have other devices and with the watt sensor it works
