### ISSUE TITLE
A lot of Cloud ERROR: 'error': 504 messages

### ISSUE THREAD

**Issue by invisible999** [AlexxIT/SonoffLAN#1380]
Currently  I am receiving a lot of messages in HA System->Logs

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:379
integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: April 7, 2024 at 1:34:56 PM (**4246 occurrences**)
Last logged: 10:14:04 AM

Messages are in the following format:
Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1001710bf5', 'apikey': '_the api key for the sonoff site_', 'sequence': '1712682539312'}

I jave just S31 wifi energy monitors - 4 of them. Diagnostics are attached.

[sonoff-4de7ada4da267f89c0532539a24bde50-Family-Room-S31-ae71fcd86d2e2b82a06e68828b5908f5.json](https://github.com/AlexxIT/SonoffLAN/files/14921991/sonoff-4de7ada4da267f89c0532539a24bde50-Family-Room-S31-ae71fcd86d2e2b82a06e68828b5908f5.json)

How can this be fixed?

**Comment by AlexxIT** [comment]
504 is a problem with connection to your device from cloud. Maybe bad WiFi or something else. Integration can't do anything about this.

**Comment by AlexxIT** [comment]
Check this issue https://github.com/AlexxIT/SonoffLAN/issues/1563
