### ISSUE TITLE
Sonoff S60 "energy_day entities" missing attribute Device_class: energy

### ISSUE THREAD

**Issue by tpehant** [AlexxIT/SonoffLAN#1384]
Hi!
First off all, thank you for integration.
I have four S60 Sonoff devices to use. They are recognized well within integration. There is only problem when adding them to the Energy dashboard. Adding gives me following error:
**Unexpected device class
The following entities do not have the expected device class:
- sensor.sonoff_1002231aba_energy_day**
![sonoff_s60](https://github.com/AlexxIT/SonoffLAN/assets/58683756/5383be73-76c4-43c6-8594-61ed2c8c279c)
Device states in developer tools are:
![sonoff_s602](https://github.com/AlexxIT/SonoffLAN/assets/58683756/ae135b93-0bd8-4161-91ad-5d5e3a59ba30)

What seems to be the issue? How do I add Device_class: energy to those entities?

Thank you in advance.
Best regards,
Tomaž

**Comment by AlexxIT** [comment]
#1377
