### ISSUE TITLE
After update to 3.7.0 only 3 of 10 devices show up as local online

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [AlexxIT/SonoffLAN#1387]
As the tille said I did do update through HACS from V3.6.0 to V3.7.0 and now only 3 of 10 devices show up local. Through cloud still 10 of 10 show up 

Also it shows in system info 3/3 local devices and not 3/10 (see picture)

![Screenshot_20240418_172021_Home Assistant](https://github.com/AlexxIT/SonoffLAN/assets/97987488/e81572c1-b4f6-4510-a978-37bddd168844)

I am on H.A. 2024.4.3

EDIT. In the EweLink App the devices still show as LAN connected

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#issues

**Comment by ianvnza** [comment]
4/5 devices is currently unavailable to control using Homeassistant.

1. I see no warnings/errors in my log
2. I am unsure how the debug page works
3. I'm attaching the diagnostic file

I have rebooted the system multiple times. 
As I was busy posting this 2 of my devices have devices to come online and is now available. So I'm uploading a 2nd diagnostics file.

[config_entry-sonoff-c6892c4c076a46a5b7600b452d683864.json](https://github.com/AlexxIT/SonoffLAN/files/15027407/config_entry-sonoff-c6892c4c076a46a5b7600b452d683864.json)

[config_entry-sonoff-c6892c4c076a46a5b7600b452d683864 -2.json](https://github.com/AlexxIT/SonoffLAN/files/15027445/config_entry-sonoff-c6892c4c076a46a5b7600b452d683864.-2.json)

![info](https://github.com/AlexxIT/SonoffLAN/assets/11595723/90e6f31b-1ec7-4542-ad34-fae6554a564c)
![info2](https://github.com/AlexxIT/SonoffLAN/assets/11595723/f685aca7-aea7-4ef6-b0e1-8f858314fe6e)

**Comment by ianvnza** [comment]
After logging into the ewelink app and manually switching all devices off and back on, they are now available in Homeassistant.

**Comment by smarthomefamilyverrips** [comment]
@ianvnza how you mean switch off and back on? All my devices are already in Off state, or you mean switching the LAN option off and on?

**Comment by ianvnza** [comment]
> @ianvnza how you mean switch off and back on? All my devices are already in Off state, or you mean switching the LAN option off and on?

My devices were all in an off, so I just switched them on and the off again. The Lan option was already on and I didn't do anything there.

**Comment by smarthomefamilyverrips** [comment]
> > @ianvnza how you mean switch off and back on? All my devices are already in Off state, or you mean switching the LAN option off and on?
> 
> My devices were all in an off state, so I just switched them on and the off again. The Lan option was already on and I didn't do anything there.

@ianvnza unfortunately this not works for me, also did you try what happens if after this you reload the integration or reboot H.A.

@AlexxIT you can tell what you need from us please

**Comment by ianvnza** [comment]
@smarthomefamilyverrips after a reboot everything is unavailable in home assistant again and I have to toggle the power on them in the ewelink app again to get them available in homeassitant. So this is only a temporary "fix"

**Comment by smarthomefamilyverrips** [comment]
> @smarthomefamilyverrips after a reboot everything is unavailable in home assistant again and I have to toggle the power on them in the ewelink app again to get them available in homeassitant. So this is only a temporary "fix"

@ianvnza thanks for testing! 👍 it seems we need to wait for a permanent fix then.

**Comment by AlexxIT** [comment]
The answer was in the logs. Good thing the problem was on my server as well. Should be fixed in latest master version

**Comment by smarthomefamilyverrips** [comment]
> The answer was in the debug logs. Good thing the problem was on my server as well. Should be fixed in the latest master version

@AlexxIT Thanks! 👍 Looking forward to the fix being applied.

**Comment by AlexxIT** [comment]
Master version always available through HACS via manual redownload feature

**Comment by smarthomefamilyverrips** [comment]
> Master version always available through HACS via manual redownload feature

@AlexxIT I did mean for the fix to be applied in the next regular update V3.X.X

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.7.1

**Comment by smarthomefamilyverrips** [comment]
Thanks @AlexxIT !!! 🥇 all working again after 3.7.1 💯
