### ISSUE TITLE
RFBridge Sonoff dropped all the objects

### ISSUE THREAD

**Issue by kpe03031973** [AlexxIT/SonoffLAN#1389]
Good afternoon. Thank you for your hard work. After the integration update to 3.7.1, RFBridge Sonoff dropped all the objects added to it. After rolling back to 3.7.0, everything works again. Thanks for your attention.

**Comment by AlexxIT** [comment]
I can't see any related code changes for this problem. You should provide more useful info.

**Comment by AlexxIT** [comment]
Fixed in latest master version

**Comment by JokeRsevilla** [comment]
> Fixed in latest master version

Are you referring to version 3.7.1?

the problem continues

**Comment by lesgrebe** [comment]
Hello!

Since update to 3.7.1 all entities related to sonoff rf bridge are unavailable. No errors in the log and also restarting HASS didn´t change the behavior. Devices like sonoff micro working fine with 3.7.1. Rolling back to 3.7.0 did fix the problem at the moment...

3.7.1
![image](https://github.com/AlexxIT/SonoffLAN/assets/37287548/1b64baf4-fadc-4df0-92ac-1fd156e62c93)

3.7.0
![image](https://github.com/AlexxIT/SonoffLAN/assets/37287548/c0c5d2fc-ee03-40ec-abe4-ed298d2b658e)


My System running on a Pi 4 8GB:
Core: 2024.4.3
Supervisor: 2024.04.0
Operating System: 12.2
Frontend: 20240404.2

Regards
Michi

**Comment by lesgrebe** [comment]
> Fixed in latest master version

As you mentioned, I´ve redownloaded and choose the master branch and everything works fine - thank you! I will stay on this master branch till this fix will be available in a new update (maybe 3.7.2 ?).

Thanks for your effort!!

Regards
Michi

**Comment by antonyslater** [comment]
Unfortunately I too get the same issue, the RF Bridge Device does show all my loaded buttons but they are greyed and when I select an individual entity I get the message below.  Rolling back to v3.7.0 specifically was my only fix as I seem to be unable to download the MASTER branch at the bottom of the versions list.

**This entity is no longer being provided by the sonoff integration. If the entity is no longer in use, delete it in settings.**

**Comment by JokeRsevilla** [comment]
I found it
![Captura de pantalla 2024-04-20 132104](https://github.com/AlexxIT/SonoffLAN/assets/110050710/1abf1da6-66fb-428d-879b-7a2b4d1fdfff)

**Comment by antonyslater** [comment]
> I found it
> ![Captura de pantalla 2024-04-20 132104](https://github.com/AlexxIT/SonoffLAN/assets/110050710/1abf1da6-66fb-428d-879b-7a2b4d1fdfff)
> 

I can see it, it just won't let me download it for some reason... 3.7.0 working for now though.

**Comment by JokeRsevilla** [comment]
> > Lo encontré
> > ![Captura de pantalla 2024-04-20 132104](https://private-user-images.githubusercontent.com/110050710/324173960-1abf1da6-66fb-428d-879b-7a2b4d1fdfff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTM3NTcsIm5iZiI6MTcxMzYxMzQ1NywicGF0aCI6Ii8xMTAwNTA3MTAvMzI0MTczOTYwLTFhYmYxZGE2LTY2ZmItNDI4ZC04NzliLTdhMmI0ZDFmZGZmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxMTQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzJkZTY1OTExMWE1NzEwN2Q5MzEzZjUxMWU0NDI4MTQ3YzNhZTZjMDRmOTY3ODM4OGM0YjQwZTMzZmU0ZDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vWXTWa9DtVtsOFaGeNbPrHg46ZsXwCvn7rVTQ6gNd9Y)
> 
> Puedo verlo, simplemente no me deja descargarlo por alguna razón... Aunque 3.7.0 funciona por ahora.

After selecting it you should expect that the letters are white, not gray

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.7.2

**Comment by antonyslater** [comment]
> https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.7.2

Excellent work as ever AlexxIT, that has sorted it for me :-)

**Comment by oywino** [comment]
Perhaps not related, but after updating my SonOff Bridge (not the Pro version) to Tasmota 13.4.0 Z2M could no longer start zigbee-herdsman (Failed to start zigbee).  Downgrading Tasmota to 13.3.0 or lower, solved the issue temporarily.
