### ISSUE TITLE
Group switch doesn't work

### ISSUE THREAD

**Issue by luca336** [AlexxIT/SonoffLAN#139]
I just did the latest update but  an seem to get groups to work in home assistant.

From off to on state
Only the first switch turns on.

On to off
Nothing happens

Off to on
2nd switch turns on

Etc

Is anyone having this issue it only popped up after the update.

Looking forward for your reply, Luca.

**Comment by AlexxIT** [comment]
Maybe single light suits to you? #115

**Comment by luca336** [comment]
A single light works perfectly, I am not understanding your question.
Do you require anything from my part to diagnose it ?

**Comment by luca336** [comment]
It doesnt because with a single group i can call from google assistant that virtual switch, then this turns on and off 4 different sonoff devices not just the one 3 gang switch.

**Comment by luca336** [comment]
new integration https://we.tl/t-BJMaoBItHq

Log file 
2020-06-01 22:58:51 WARNING (MainThread) [custom_components.sonoff.sonoff_local] 100095cd4b => Local4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} !! [Errno 104] Connection reset by peer
2020-06-01 22:58:51 WARNING (MainThread) [custom_components.sonoff.sonoff_local] 100095cd4b => Local4 | {'switches': [{'outlet': 2, 'switch': 'off'}]} !! [Errno 104] Connection reset by peer

**Comment by AlexxIT** [comment]
Ok, I'll check it

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.1.3

**Comment by luca336** [comment]
Fully working cheers.
