### ISSUE TITLE
Local access to socket CK-BL602-SWP1-01(182) coolkit

### ISSUE THREAD

**Issue by sashakozlov86** [AlexxIT/SonoffLAN#1392]
Good afternoon  I have several Ewelink CK-BL602-SWP1-01(182) coolkit sockets.  I just can’t set up work via local mode (only auto or cloud modes work).  Can you please tell me if there is anything I can do for this?  I also tried to write a manual device configuration in configuration.yaml by setting the IP address manually (devices: xxxxxxxxxx: name: "xxx" host: 192.168.x.x), but this does not help.  When local mode is activated in the integration, devices are not available.  I am attaching screenshots.  What can you do about it?  Thanks a lot!
![Screenshot_2024-04-22-10-14-11-41_41b172fd405cd4f56cfde6a38027ffd1](https://github.com/AlexxIT/SonoffLAN/assets/93244850/b8166edb-077e-4e8e-b96d-25beba762209)
![Screenshot_2024-04-22-10-05-31-25_c3a231c25ed346e59462e84656a70e50](https://github.com/AlexxIT/SonoffLAN/assets/93244850/5ad9fe27-99da-4408-82a5-4f89810e42ed)

**Comment by sashakozlov86** [comment]
[sonoff-0c1acf4a726f9587b9f34c4755d8b1f1-Розетка датчика газа в котельной-d337a6f737bf7f4f7a1a4149e4603e21-1.json](https://github.com/AlexxIT/SonoffLAN/files/15058976/sonoff-0c1acf4a726f9587b9f34c4755d8b1f1-.-d337a6f737bf7f4f7a1a4149e4603e21-1.json)

**Comment by sashakozlov86** [comment]
Unfortunately, I can’t even understand in which direction I can dig.  The fact is that I have a Keenetic Viva router, in Homeassistant, thanks to the integration of Keenetic NDMS, all devices on the ESPHome platform, as well as Sonoff TH, are correctly identified using the mDNS protocol.  Accordingly, in your SonoffLAN integration they are correctly detected in local mode and managed.  But for some reason, devices on the Ewekink platform - the Coolkit socket on the CK-BL602-SWP1-01 firmware are not detected in any way in Keenetic NDMS.  But why, even if it doesn’t work via mDNS, can you bind a device to SonoffLAN by manually entering the IP address?  I can bind a static IP address to a specific device through a router; in fact, I’ve already connected to it via the cloud once and SonoffLAN has already downloaded the data using the encryption key, etc.  It would be great if you could manually enter the IP address and encryption key, but I tried to do that and it didn’t work - the device is not accessible in local mode.

**Comment by AlexxIT** [comment]
Show integration diagnostics

**Comment by sashakozlov86** [comment]
I am attaching diagnostic data on integration

[config_entry-sonoff-0c1acf4a726f9587b9f34c4755d8b1f1-1.json](https://github.com/AlexxIT/SonoffLAN/files/15071008/config_entry-sonoff-0c1acf4a726f9587b9f34c4755d8b1f1-1.json)

**Comment by AlexxIT** [comment]
182 - it's a model ID of Sonoff S40
Sonoff S40 on fw 1.1 marked as cloud only in the docs:
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#tested-devices
