### ISSUE TITLE
Feature request: RSSI for devices SNZB-06P and ZBMINIL2

### ISSUE THREAD

**Issue by Marcelo-Y** [AlexxIT/SonoffLAN#1398]
Hi Alex,
First of all, thanks for your great job...
I got some SNZB-06P and ZBMINIL2, they work great but have no RSSI values available. ZBMINIL2 has an entity for RSSI but it's always "unavailable". SNZB-06P has no entity for RSSI.
For both of them I can see RSSI values in Debug Log file as "subDevRssi".

SNZB-06P:
[sonoff-e7fdf11c007c4ade76171c90a5d62fc4-SNZB-06P Cozinha-6e8cdcb0688f8c5a280acf272b2078f5.json](https://github.com/AlexxIT/SonoffLAN/files/15136221/sonoff-e7fdf11c007c4ade76171c90a5d62fc4-SNZB-06P.Cozinha-6e8cdcb0688f8c5a280acf272b2078f5.json)

ZBMINIL2:
[sonoff-e7fdf11c007c4ade76171c90a5d62fc4-ZBMINIL2-Quarto 1-28c93fe5fe4cbff29dbad34847378924.json](https://github.com/AlexxIT/SonoffLAN/files/15136226/sonoff-e7fdf11c007c4ade76171c90a5d62fc4-ZBMINIL2-Quarto.1-28c93fe5fe4cbff29dbad34847378924.json)

Thank you very much!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.7.3
