### ISSUE TITLE
SNZB-06P got only "RSSI" sensor entity after v3.7.3

### ISSUE THREAD

**Issue by Marcelo-Y** [AlexxIT/SonoffLAN#1404]
Hi, Alex!!!
Thanks for the fast response in adding the RSSI to the ZBMINIL2 and SNZB-06P.
After the v3.3.3 update I got the ZBMINIL2 rssi entity working great...
The SNZB-06P has a new entity called RSSI, but the other "sensor" entity is not available anymore.
The new RSSI entity is OK, the value is being updated, but others attributes I had before in sensor entity like "human", "brState"...all of them had gone. Can't even see the "brState" in the debug file anymore.

The debug file begore update:
[sonoff-e7fdf11c007c4ade76171c90a5d62fc4-SNZB-06P.Cozinha-6e8cdcb0688f8c5a280acf272b2078f5.json](https://github.com/AlexxIT/SonoffLAN/files/15182384/sonoff-e7fdf11c007c4ade76171c90a5d62fc4-SNZB-06P.Cozinha-6e8cdcb0688f8c5a280acf272b2078f5.json)

The debug file after update:
[sonoff-e7fdf11c007c4ade76171c90a5d62fc4-SNZB-06P-fbed9101863a7f8e3ee4087013add6bc.json](https://github.com/AlexxIT/SonoffLAN/files/15182385/sonoff-e7fdf11c007c4ade76171c90a5d62fc4-SNZB-06P-fbed9101863a7f8e3ee4087013add6bc.json)

Thank you very much!

**Comment by AlexxIT** [comment]
It always has been. This sensor has never been supported in integration:
https://github.com/AlexxIT/SonoffLAN/issues/1245
