### ISSUE TITLE
SNZB-06P stops working

### ISSUE THREAD

**Issue by atlaspl** [AlexxIT/SonoffLAN#1407]
Since the last update of the Sonoff integration, I've noticed that the SNZB-06Ps, which were previously functioning, have now stopped working. It appears that Home Assistant no longer recognizes these devices (although my other Sonoff devices continue to work normally), and as a result, the integration of my three SNZB-06P devices is unavailable.
 
I can see this in my diagnostic file log:
[sonoff-bfafcfbdaa9afbe8d6413cdd8f126169-PresenzaSalone-c5ff2745a2b9b6264249a21db015cb26.json](https://github.com/AlexxIT/SonoffLAN/files/15209367/sonoff-bfafcfbdaa9afbe8d6413cdd8f126169-PresenzaSalone-c5ff2745a2b9b6264249a21db015cb26.json)

  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.4.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.1.73-haos-raspi",
    "supervisor": "2024.04.4",
    "host_os": "Home Assistant OS 12.2",

   "sonoff": {
      "version": "3.7.3",

**Comment by AlexxIT** [comment]
#1245
