### ISSUE TITLE
Sonoff THR316 Sensor Data missing in HA, but available in Smart Home

### ISSUE THREAD

**Issue by alexandru4444** [AlexxIT/SonoffLAN#1414]
Hello,

I've seen similar issues, but do not how to solve them. I have 3xTHR316 with T&H sensors attached which work fine, like the one in green square and 3xTHR316 with T&H sensors attached which don't work as expected. All 6 THR are the same, in the same HA, same network, updated firmware, updated HA. Also missing in Grafana. Any idea why? Or where to look? Please help. Thanks!

![THR316 Smart Home](https://github.com/AlexxIT/SonoffLAN/assets/144016364/6c1086c3-1085-474a-b345-4e8a8e71ddcc)
![THR316 HA History](https://github.com/AlexxIT/SonoffLAN/assets/144016364/b4ca1761-063b-404f-ad00-28aaa40b0112)

**Comment by AlexxIT** [comment]
Are you sure your questing related to this integration?

**Comment by alexandru4444** [comment]
I am asking about Ewelink Smart Home Add-on and Sonoff THR316. I found possible similar issues here. Is this the wrong section?

**Comment by AlexxIT** [comment]
This project not related to ewelink addon

**Comment by alexandru4444** [comment]
Can you please point any direction?

**Comment by AlexxIT** [comment]
Ask ewelink support
