### ISSUE TITLE
Deleted devices in Eweling remain in SonoffLAN

### ISSUE THREAD

**Issue by FredM17** [AlexxIT/SonoffLAN#1416]
Hi,

When I delete a device in Ewelink, it still appears in SonoffLAN.

I tried to reload and also to configure again but nothing changed

So far the only solution is to uninstall and reinstall SonoffLAN and activate again all inactive entities I need.

Any other smarter solution?

Thanks in advance

**Comment by sipimokus** [comment]
Hi, these steps working for me : 
- find the .json file in the /config/.storage/sonoff folder,
- make backup and remove it,
- then restarting Home Assistant.

The .json file contains the old devices, I think this is the cause of the problem (maybe caching?).

**Comment by FredM17** [comment]
Thanks. I'll try.

**Comment by PalliMcbain** [comment]
Same problem here

**Comment by FredM17** [comment]
I'll try to delete the info about the deleted device in the json file.

**Comment by AlexxIT** [comment]
You can remove a device from the Home Assistant via the device page. Three-dot button.

If the device remains in the ewelink account - it will load again when you restart the integration. And you need to remove it from cloud first.

Deleting a file from `.storage` is the wrong advice.

**Comment by FredM17** [comment]
Hi, thanks. The three-dot bring just close to the Download Diagnostics, I never tried it. Just do it. Perfect.Thank you.
