### ISSUE TITLE
no Camera Feed - GK-200MP2-B Camera

### ISSUE THREAD

**Issue by BMiZEL** [AlexxIT/SonoffLAN#1419]
I added the Camera to eWeLink and it shows up in HA as a Sensor. 

![Screenshot from 2024-05-17 09 19 24](https://github.com/AlexxIT/SonoffLAN/assets/55613906/75eb88b8-7565-4228-b44a-a4a9c49b6245)

There is no Video Feed.

I tried adding to the YAML - but there are no changes:

_script:
  left:
    sequence:
      - service: sonoff.send_command
        data:
          device: '012345'  # use quotes, this is important
          cmd: left_

**Comment by AlexxIT** [comment]
#67
