### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by serlinGi** [AlexxIT/SonoffLAN#142]
Hi, thank's for your job;
until about 1 hour ago everything was fine.
I use 2 devices in cloud mode and about another 30 in apikeys mode only.
after this latest update, only the 2 in the cloud work: all the others are unavailable.
for the moment I solved it using yesterday's backup.
I hope it is not only my problem and that you can solve it soon. 
Thanks again

**Comment by dudu631** [comment]
Seems like a problem on the latest release (2.1.1). I rolled back to 2.1.0 and it's working fine.

**Comment by AlexxIT** [comment]
Sorry, my bad https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.1.2
