### ISSUE TITLE
All devices are unaivailable / HA core upgrade 2024.5.4

### ISSUE THREAD

**Issue by saltabas** [AlexxIT/SonoffLAN#1423]
Hi, first of all, many thanks for your awesome integration. I'm from Italy. Starting from a HA core upgrade to 2024.5.4 (the first I tryed in may, same issue with 2024.5.5) all of my sonoff devices, TH, rf bridges and basic, became in unaivailable state. They work correctly in ewelink app (both first and second account I use for integration) but in the debug files I can see an error to log in at ewelink server (I tryed both local and auto mode). Downgrade to older integration versions doesn't work, issue is still there. What can I do? Thx

[Local mode debug.txt](https://github.com/AlexxIT/SonoffLAN/files/15446358/Local.mode.debug.txt)
[Auto mode debug.txt](https://github.com/AlexxIT/SonoffLAN/files/15446359/Auto.mode.debug.txt)
[diagnostics config_entry-hacs-555296aeb62481b4869d95446410c751.json](https://github.com/AlexxIT/SonoffLAN/files/15446360/diagnostics.config_entry-hacs-555296aeb62481b4869d95446410c751.json)
[1st reg error.txt](https://github.com/AlexxIT/SonoffLAN/files/15446361/1st.reg.error.txt)

**Comment by krupaw2** [comment]
I have the same problem

**Comment by wrcaston84** [comment]
Same as me too

**Comment by kiclaw** [comment]
Same here, 2024.5.5

**Comment by Breworks** [comment]
Did anyone find a solution to this? I have the same issue. All devices showing in ewelink, but unavailable in HAS version 2024.5.5. Update to this version seems to be the trigger to the failure.

**Comment by mesut3000** [comment]
Same here. Wifi devices are all OK, but zigbee not working. I'm using Home Assistant 2024.6.3 version.

**Comment by chavalitoguay** [comment]
I have the same problems, before with the latest version of HA from 2023 everything worked ok, I updated 6-2-2024 and all my Sonoff devices stopped working (62 units), Please help

**Comment by EugeneVR79** [comment]
I have had this happen a few times after upgrading HA. The only thing that seems to work for me is to remove the Integration Entry:

![image](https://github.com/user-attachments/assets/3cf859c1-c222-424c-93c9-9541bfe6a112)

add the Integration Entry again

**Comment by tackleza** [comment]
Remove the Integration Entry and re-add look like it's work for me. It's need to restart HA for about 3 time to make it fully work

- First reboot because when I re-add the entry it's only show me about 2 devices (I have about 15~ of them)
- Second reboot to make it Sonoff fully work. but some of custom "Automations" it's marked some of them invalided due to invalided devices. Due to Sonoff start up slow and need to reload all the device lists
- Third reboot to make Automations back to normal.

**Comment by AlexxIT** [comment]
```
Login error: {'error': 406, 'msg': '{"error":401,"msg":"Sign:sign is error"}'}
```

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Registratore: py.warnings
Fonte: custom_components/__sonoff/sonoff_local.py:238
Integrazione: __sonoff
Prima occorrenza: 07:37:01 (1 occorrenze)
Ultima registrazione: 07:37:01

/config/custom_components/__sonoff/sonoff_local.py:238: RuntimeWarning: coroutine 'async_load_platform' was never awaited _LOGGER.debug(
```

**Comment by AlexxIT** [comment]
@saltabas do you still have the problem?

The others who have posted here have not provided any debugging information.

**Comment by AlexxIT** [comment]
I just noticed. The issue author has an error in an unclear version of the component:

`custom_components/__sonoff/sonoff_local.py:238`

**Comment by saltabas** [comment]
Thanks for clearing that up @AlexxIT: as a result a manual deletion and reinstalling brings it back to working (simply hacs remove was not enough for me)
