### ISSUE TITLE
Issue with SNZB-06P Sensor Status Post-Update of SonoffLAN at v3.7.3

### ISSUE THREAD

**Issue by Mike76Mer** [AlexxIT/SonoffLAN#1428]
Issue with SNZB-06P Sensor Status Post-Update of SonoffLAN at v3.7.3

@AlexxIT I’ve encountered a persistent issue where the status of my SNZB-06P sensors is no longer visible, although the RSSI remains accessible. This problem surfaced following the most recent update. Prior to this, the status of my three SNZB-06P sensors was displayed without any complications. It seems that the update may have inadvertently affected the sensor status visibility within the system.

I don't know if it can be useful, but the three devices are all associated with a ZBBridge-P

_Originally posted by @atlaspl in https://github.com/AlexxIT/SonoffLAN/issues/1245#issuecomment-2134068446_

**Comment by Mike76Mer** [comment]
Same problem here, I'm new to the community. Is there another report where I can get support? 

This issue seems closed (#1245).

Thank you.

**Comment by tinker-tillit-works** [comment]
I have the same issue since upgrade to 3.7.3, my SNZB-06P now shows status of unknown. I needed to change the logic to use an Ewelink Scene since the status is not reported anymore.

**Comment by cpmarexel2f** [comment]
I have the same problem....Only RSSI SNZB-06P is available.

![Screenshot 2024-07-11 153127](https://github.com/AlexxIT/SonoffLAN/assets/81263403/b0d65427-6644-4233-ad44-c89daf327fe7)

**Comment by AlexxIT** [comment]
#1245
