### ISSUE TITLE
Wrong Channel names in Home Assistant

### ISSUE THREAD

**Issue by arahag** [AlexxIT/SonoffLAN#143]
I am using the Sonoff 4ch Pro R2. I have set "reload: always" in my configuration.yaml file, and I see in the .sonoff.json the correct names for each channel, but Home Assistant is somehow showing the name of the Ch2 for Ch1 and the name of Ch1 for Ch2.

**Comment by AlexxIT** [comment]
Can you share this device with me? sonofflan@gmail.com

**Comment by arahag** [comment]
I am unable to share with your email, I get "Failed to share. Please try again.".

**Comment by AlexxIT** [comment]
Are you using ewelink mobile app version 4? Check about info.

**Comment by arahag** [comment]
Yes, using app version 4.1.0 on Android.

**Comment by AlexxIT** [comment]
Ok. Please send `sonoff.json` to my email. You can hide private data.

**Comment by arahag** [comment]
After fiddling with HA restarts and renames in the eWelink app, I was able to get it to work. The entity names finally reflected the names in the app, but Lovelace would still not update the entity names in the entity card. By removing and adding the channels again in lovelace, it finally took the correct names. My issue is solved...
