### ISSUE TITLE
Is this addon able to retrieve Scene from eWeLink?

### ISSUE THREAD

**Issue by lukedoomer** [AlexxIT/SonoffLAN#1431]
I would like to have home assistant entity for the scene in eWeLink app as well
Is it possible? Not building automation of home assistant from scratch seperately
![ewelink](https://github.com/AlexxIT/SonoffLAN/assets/18679207/263aedd0-88d3-45cb-bc89-df990b4b0653)

**Comment by AlexxIT** [comment]
#336

**Comment by ShtefanThe** [comment]
Hello! Small bump for this. I know it does not make a lot of sense to invest into this, but I would need it to "hack" some command from an NSPannel to Home Assistant. 
My Vision:
1. Create Blank scene in eWeLink
2. Add it as a Widget on NSPannel
3. Catch the trigger of said scene in Home Assistant
4. Perform any complex action in HASS
This would allow to trigger any action\automation\scene in HASS from an NSPannel
Thank you! 🙇
