### ISSUE TITLE
Fix deprecated hass.helpers

### ISSUE THREAD

**Issue by Danieldiazi** [AlexxIT/SonoffLAN#1434]
Hi:
I've this error:

Registrer: homeassistant.helpers.frame
source: helpers/frame.py:184

Detected that custom integration 'sonoff' accesses hass.helpers.system_info. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from system_info directly at custom_components/sonoff/system_health.py, line 61: info = await hass.helpers.system_info.async_get_system_info(), please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

Following the message, I've created a bug report at https://github.com/AlexxIT/SonoffLAN/issues

Thanks for your support.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
