### ISSUE TITLE
Add support Sonoff SNZB-03P

### ISSUE THREAD

**Issue by Marcelo-Y** [AlexxIT/SonoffLAN#1435]
First of all thank you very much for your great job on this.

 I'd like to have SNZB-03P attributes as entities, like you have done with SNZB-06P in the "master" so far.
 I started using SNZB-03P and found it much better to use entities like in SNZB-06P than as attributes.
 Here are the files:
[snzb-03p debug.txt](https://github.com/user-attachments/files/15908351/snzb-03p.debug.txt)
[snzb-03p diagnostics.json](https://github.com/user-attachments/files/15908352/snzb-03p.diagnostics.json)

 Hope it can be possible.
 Thank you very much.

**Comment by ramirosaraiva** [comment]
I'm also looking for it! Can anyone help?

**Comment by AlexxIT** [comment]
Nice debug and diagnostics. Thanks.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
