### ISSUE TITLE
Add support Sonoff SNZB-04P

### ISSUE THREAD

**Issue by nautos** [AlexxIT/SonoffLAN#1439]
Sonoff SNZB-04P does not indicated status Open OR Closed

**Comment by Rob-in-Molyvos** [comment]
Another request for the SNZB-04P to be added to this integration.

Currently the default icon is mdi:clock and the sensor shows "X minutes ago", where X appears to be from when the app was started.

**Comment by Rob-in-Molyvos** [comment]
Developer tools --> State

device_class: timestamp
friendly_name: SNZB-04P
subDevId: 6410eafefff410347003
parentid: "1002061833"
fwVersion: 2.2.0
battery: 100
trigTime: "1720277705000"
supportPowConfig: 1
subDevRssi: -61
lock: 0

Surely the device_class should be door.

**Comment by LPX64** [comment]
Hi, got the same issue. Moreover the attribute LOCK (0 or 1) cannot be used for automation, so a great request to fix this one.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
