### ISSUE TITLE
Fix broken request to zeroconf/getState

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/SonoffLAN#1442]
File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 270, in local_update|    params = self.local.decrypt_msg(msg, device["devicekey"])

This integration works after all devices are reset but then I get the above message as well as the below for all devices:

1001xxxnnn => Local4 | 192.168.68.112:8081 | None !! Can't read JSON 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://192.168.68.112:8081/zeroconf/getState')

Can anyone do anything because this worked flawlessly with previous versions of HA. It stopped working around April when I did an update.

_Originally posted by @wrcaston84 in https://github.com/AlexxIT/SonoffLAN/issues/1410#issuecomment-2212436693_

**Comment by Phara0h** [comment]
Same here

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
