### ISSUE TITLE
Problem with sonoff Ewilink CORE 2024.7.2

### ISSUE THREAD

**Issue by cartheryromuald** [AlexxIT/SonoffLAN#1447]
Hi, 
sorry i'm french :)
My Ewilink integration linked with sonoff in home assistant by HACS connects and disconnects every 20/30 seconds.
I tried to reinstall but nothing works.

Do you have an idea ? I don't understand the problem?
no problems with other integration by tuya or other... Just on sonoff

https://github.com/user-attachments/assets/299394e8-56cc-4f44-a3ed-f29b920c91b7

**Comment by AlexxIT** [comment]
Sounds similar https://github.com/AlexxIT/SonoffLAN/issues/1445#issuecomment-2225431813
