### ISSUE TITLE
Update target_temperature_step for NSPanel to 0.5

### ISSUE THREAD

**Issue by nikos445** [AlexxIT/SonoffLAN#1449]
NSPanel thermostat and temperature accuracy was updated in v1.5.0

 Step is 0.5 degree now and temperature accuracy +- 0.5
 
 Please update the code.

**Comment by nikos445** [comment]
![Screenshot from 2024-07-17 18-55-22](https://github.com/user-attachments/assets/76ea90f2-5f6c-4fa6-9396-321e6bf09c22)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
