### ISSUE TITLE
Smart circuit breaker with power meter coolkit

### ISSUE THREAD

**Issue by mirokkkk** [AlexxIT/SonoffLAN#1454]
There are integration for _coolkit_ Smart circuit breaker with power meter but in integration is missing power combustion meter, please add it.
Model: CK-BL602-W102SW18-01(226)
From coolkit
Thanks

**Comment by AlexxIT** [comment]
Please show device diagnostics.
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by mirokkkk** [comment]
[sonoff-8bf650ae4fe9b7410113756e813a295f-Istič Čerpadlo pivnica -bc55c6d1d0c601556c0d038c5bcf2af6.json](https://github.com/user-attachments/files/16403080/sonoff-8bf650ae4fe9b7410113756e813a295f-Istic.Cerpadlo.pivnica.-bc55c6d1d0c601556c0d038c5bcf2af6.json)

**Comment by mirokkkk** [comment]
[sonoff-8bf650ae4fe9b7410113756e813a295f-Istič Čerpadlo pivnica -bc55c6d1d0c601556c0d038c5bcf2af6.json](https://github.com/user-attachments/files/16403083/sonoff-8bf650ae4fe9b7410113756e813a295f-Istic.Cerpadlo.pivnica.-bc55c6d1d0c601556c0d038c5bcf2af6.json)

**Comment by AlexxIT** [comment]
Can you explain which of these parameters are missing? I don't really understand what they mean.

```json
{
        "bindInfos": "***",
        "version": 8,
        "rssi": -66,
        "fwVersion": "1.0.0",
        "switch": true,
        "pulse": "off",
        "pulseWidth": 1000,
        "sledOnline": "on",
        "startup": "on",
        "prepaid_support": true,
        "alarm_v_min": -1,
        "alarm_v_max": -1,
        "alarm_c_min": -1,
        "alarm_c_max": 2,
        "alarm_p_min": -1,
        "alarm_p_max": -1,
        "availablePower": 5.87,
        "prepaidEnale": true,
        "prepaidLowBalanceAlert": true,
        "prepaidLowest": 1,
        "min_p_upper": 5000,
        "min_p_lower": 1,
        "max_p_upper": 15000,
        "max_p_lower": 1,
        "min_v_upper": 220,
        "min_v_lower": 76,
        "max_v_upper": 300,
        "max_v_lower": 220,
        "max_c_upper": 63,
        "max_c_lower": 0.1,
        "calibrateFlag": false,
        "ssid": "***",
        "bssid": "***",
        "staMac": "***",
        "totalPower": 0.13,
        "phase_0_c": 0,
        "phase_0_v": 234.47,
        "phase_0_p": 0,
        "uiActive": 60,
        "alarmType": "c",
        "hundredDaysKwh": "get",
        "msgType": 1,
        "batteryRecharge": 5,
        "oneKwh": "start",
        "alarmList": [],
        "endTime": "",
        "startTime": "2024-07-04T19:58:29.057Z",
        "zeroPower": true,
        "alarmReport": 8
      }
```

**Comment by AlexxIT** [comment]
Your issue is duplicate. Please answer in first issue #1425
