### ISSUE TITLE
Sonoff SNZB-04P error with period of time open or closed

### ISSUE THREAD

**Issue by flgimenes77** [AlexxIT/SonoffLAN#1458]
Hi, The Sonoff SNZB-04P doesn't work with an open or closed time period. On ewelink, I created a scene that notifies you when it is open for x minutes. Then the sensor opens and the trigger starts. However, if you close the sensor, it continues counting as if it were open. It does not cancel the open status when closing, so the scene says that the sensor is open even when it has already closed.

Iam using ewelink 5.8.0 and SNZB-04P 2.2.0 if is relevant.

Thank you

**Comment by AlexxIT** [comment]
This is wrong place for ewelink app and scenes support.
