### ISSUE TITLE
Yesterday all devices (DW2-Wi-Fi-L SONOFF) fell off - 

### ISSUE THREAD

**Issue by klugev303** [AlexxIT/SonoffLAN#1461]
SonoffLAN v.3.7.3

    "installation_type": "Home Assistant OS",
    "version": "2024.7.3",
    "os_version": "6.6.33-haos",
    "supervisor": "2024.06.2",
    "host_os": "Home Assistant OS 12.4"

If you enable only the cloud in the integration settings, we see this error:
"Cannot connect to host cn-apia.coolkit.cn:443 ssl:default [[SSL] record layer failure (_ssl.c:1000)]"

If you enable both local connection and cloud in the integration settings, we see that the devices are not available!
![изображение](https://github.com/user-attachments/assets/f44ecdc7-a691-4c8a-9eb4-0f1290a9aff8)

**Comment by klugev303** [comment]
Figured it out myself, the address cn-apia.coolkit.cn was not resolved by the upstream DNS server. Added a local DNS entry in Mikrotik and everything worked. Maybe it will be useful to someone.

**Comment by RiaanSaayman** [comment]
Thanks! same for me my pihole DNS was blocking traffic to cn-apia.coolkit.cn added to the witelist and it came back :) <3
