### ISSUE TITLE
Support fan changes in Hass 2024.8

### ISSUE THREAD

**Issue by cdvreede** [AlexxIT/SonoffLAN#1462]
getting following error...

Entity sonoff.sonoff_1001f1826d (<class 'custom_components.sonoff.fan.XFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues
Entity sonoff.sonoff_1001f1826d (<class 'custom_components.sonoff.fan.XFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

**Comment by the-rexmundi** [comment]
https://developers.home-assistant.io/blog/2024/07/19/fan-fanentityfeatures-turn-on_off/

- Introduced in 2024.8.  
- unflagged feature (turn_on/turn_off) will stop working 2025.2

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
