### ISSUE TITLE
Change min_temp for TH to -40

### ISSUE THREAD

**Issue by caitotheonlypotato** [AlexxIT/SonoffLAN#1466]
Hi Alex.

Something I stumbled over by accident.
I've used automations to adjust freezer temps based on various condition or button presses for some time, however recently noticed this wasn't working.  I can only presume something since the last update to v3.7.3.

I was getting the following error when running the service calls manually
Provided temperature -16.0 is not valid. Accepted range is 1 to 99

The climate sensor attributes were as follows in the developer tools (States tab)
```
hvac_modes:
  - "off"
  - heat
  - cool
  - dry
min_temp: 1
max_temp: 99
target_temp_step: 1
current_temperature: -16.2
target_temp_high: -14.5
target_temp_low: -16.5
friendly_name: Chest Freezer
supported_features: 386
```

The model in question is TH16R2

![image](https://github.com/user-attachments/assets/b023c32d-5d1b-4bcd-bb00-d76dfc23b248)

I've noticed in the climate.py file there is a setting for 'min-temp: 1' on line 31.  For my purposes I changed this to min_temp: -20 which has fixed my issue, however I wonder if this is something can can be rolled into the next update without breaking stuff for others?

![image](https://github.com/user-attachments/assets/0913d651-c74d-484e-8a1b-885425224e95)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
