### ISSUE TITLE
Periodical disconnecting and connecting of devices

### ISSUE THREAD

**Issue by fk1975** [AlexxIT/SonoffLAN#1469]
I'm running 2 HA instances in one local network, the main with all the features and 2nd as a backup for critical functions. Both are using SonOffLAN custom integration, which is absolutely awesome. 

There are 28 SonOff devices in local network. All work fine, only with SonOff ZigBee bridge and smart bulb (B05-B), I'm facing last few weeks following issue:

Every 15-17seconds, those 2 devices go offline and then, after 15s online again. 

There is following error in logs :

```
Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:576
integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](http://192.168.1.123:8123/api/sonoff/a38318f0-13c1-4444-b601-65da116be253))
First occurred: 06:14:57 (66 occurrences)
Last logged: 06:55:19

You logged in from another place

```
Downgrade to older version or disbling of "problematic" devices, which are not necessary for the backup HA instance did not help. Only disabling of entire integration. As well, logout from the cloud (native eWelink app on mobile and web) has no effect

After quite long investigation, I've tried to disable SonOffLAN integration on 2nd HA instance and since then, all works as desired. 

Please is it possible to fix the issue with access on the device from multiple HA instances? Or which configuration can I update in order to enable access on SonOff devices over the LAN?

There is  similar issue already reported, but without any details. Therefore I've created a new one.

Thank you in advance

Versions:
```
Core: 2024.8.2
Supervisor: 2024.08.0
Operating System: 13.0
Frontend: 20240809.0

SonOffLAN: 3.7.3
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#configuration
