### ISSUE TITLE
sonoff rf bridge issues with firmware 3.4.1 

### ISSUE THREAD

**Issue by maxmib** [AlexxIT/SonoffLAN#147]
sonoff rf bridge in homeassistant stop working after  3.4.1 firmware upgrade，it gets nothing when smoke sensor sends a 433 signal ，the official ewelink app works fine 。

**Comment by maxmib** [comment]
The reason is that I turn off the rf bridge in ha . I misunderstand the function of rf bridge switch . I thought it is for sending rf commands. But I have another question ,I found that a smoke sensor was automatically  created by sonofflan , it might just because I use rf bridge for receiving signal from smoke detector sensor . So what's the right way to change this smoke detector sensor's status  twhen rf bridge receiving a signal ?  by automation? Thanks .

**Comment by AlexxIT** [comment]
Please show link to your smoke detector.

**Comment by maxmib** [comment]
this is the link
https://www.bmxchile.cl/ewelink-smoke-detector-sensor/

**Comment by diazwatson** [comment]
I have a similar issue with motion sensors using the bridge. I can see that the bridge changes its name to what ever sensor is fired but don't know how to use that information to actually set automations and other stuff

**Comment by AlexxIT** [comment]
@maxmib RF devices should not created automatically. Do you have this separate device on your ewelink home screen?

**Comment by maxmib** [comment]
upgrade to the newest sonoff, rf sensors work fine,thanks
