### ISSUE TITLE
Can anybody explain me about this device CK-BL602-W102SW18-01 why it is not supported on the web.ewelink.cc

### ISSUE THREAD

**Issue by hosand** [AlexxIT/SonoffLAN#1470]
Hi everyone,

Can anybody explain me about this device CK-BL602-W102SW18-01 why it is not supported on the web.ewelink.cc
I just dont undestend how does it works.
And I also dont know this is a right place to ask.
I tried to ask on https://forum.ewelink.cc/ but the admins told me to go somewhere else.

https://forum.ewelink.cc/t/ck-bl602-w102sw18-01-anybody-have-any-luck-with-this-device/39057

but I dont know where to go or what to do anymore

any suggestion?

the only thinks I managed to modified  your /homeassistant/custom_components/sonoff/core/devices.py

and added  this in 

226: [
       LED,
       RSSI,
       spec(XEnergyTotal, param="totalPower", uid="energy", multiply=1, ),
       spec(XSensor100, param="phase_0_c", uid="current", multiply=1, ),
       spec(XSensor100, param="phase_0_p", uid="power", multiply=1),
       spec(XSensor100, param="phase_0_v", uid="voltage", multiply=1, round=2),
    ],  # CK-BL602-W102SW18-01(226)

So i can read some data  but no update  just if you log in to mobile app 
and also to turn it on or off that is not working in homeassistant 

Regards

hosand

**Comment by AlexxIT** [comment]
This project not related to web.ewelink.cc

**Comment by hosand** [comment]
? Invalid
