### ISSUE TITLE
HACS 2.0 Compatibility Question

### ISSUE THREAD

**Issue by HoracioDos** [AlexxIT/SonoffLAN#1471]
Hello!
First, I want to thank you for this integration. Since the last HACS 2.0 upgrade, I would like to know if the SonnofLan integration will be compatible with HACS 2.0.
Thanks!

**Comment by AlexxIT** [comment]
I have no idea

**Comment by ronjtaylor** [comment]
Yes I would like to know this as well as I use  SonoffLAN and SmartIR.  
this is from the HACS team in HA on V2.0

_**Breaking changes

    HACS requires Home Assistant 2024.4.1 or later.
    The sensor platform has been removed.
    You can no longer configure HACS in YAML.
    NetDaemon apps are no longer in HACS.
    HACS now uses a new data source hosted on Cloudflare for most metadata.
    The /hacsfiles/ endpoint no longer works for Themes.
    Custom hacs prefixed events are no longer fired.
    info.md files are no longer rendered. Instead, the README is used.**_

**Comment by neomvll** [comment]
2x powR320D
HACS 2.0.1
HA Core 2024.9.0
HA Supervisor 2024.08.0

All Working
