### ISSUE TITLE
Sonoff Power (powr2) consumption not reflecting correctly

### ISSUE THREAD

**Issue by Supermanenvysme** [AlexxIT/SonoffLAN#1473]
Have 2 Sonoff powr2 which only shows the power consumption once when the devices are turned off.

The consumption is then not updated in real time. When home assistant is restarted the problem is resolved and reflects the power consumption when the device is turned on and shows the real time changes. This lasts a day or two then the problem experienced again.

Two screen grabs first when the device is off, power consumption is shown while the second is when the device is on, the power consumption is not shown.

![image](https://github.com/user-attachments/assets/118add85-b09e-48c9-8f9d-5fe5eb9dcc5b)

![image](https://github.com/user-attachments/assets/cff480ee-dc90-44c7-8230-c28ef29349a8)

**Comment by AlexxIT** [comment]
This is know device firmware bug. If you enable logs - you will see it.
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

You can try setup periodic force updates:
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#force-update

Also check:
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#sonoff-pow
