### ISSUE TITLE
S60TPF plug and power meter problems

### ISSUE THREAD

**Issue by atrambauer** [AlexxIT/SonoffLAN#1474]
Installed a few days ago two S60TPF sonoff plugs with power consumption and even they work correctly in eWelink and from HA commands, i get these errors:

Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '1002271022', 'apikey': 'XXXXX', 'sequence': '1725040709185'}
Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '100226eeda', 'apikey': 'XXXXX', 'sequence': '1725040709286'}

If I check the entities they are OK, I can command them, check sensors logs that look ok.
But also in Energy Dashboard i cannot make them show the correct values as they have if i open the sensor history.

**Comment by AlexxIT** [comment]
Your device not respond to cloud. Maybe WiFi issue. Not related to work of this integration.
