### ISSUE TITLE
Cloud based switches and sensors became unavailable

### ISSUE THREAD

**Issue by adamnagybig** [AlexxIT/SonoffLAN#1476]
[config_entry-sonoff-01J6MA1HPBW0MH3GNPQT4J9H6X.json](https://github.com/user-attachments/files/16825424/config_entry-sonoff-01J6MA1HPBW0MH3GNPQT4J9H6X.json)

I Have SonoffLan installed more than 1 year ago and there were no problems but since 2 months ago all my switches and sensors which are connected via cloud ( sonoff is on auto mode ) are becaming available and after 5 second unavailable and this goes in a loop since 2 months.
In paralel I was checking the ewelink software and there are no problems.

Today i have deleted everything from HA and made a new setup and the result was the same.

Can you please offer support to make it stable again or maybe something is wrong on the ewelink side that it is not communicating stable ?

**Comment by Claudiotas** [comment]
I have a similar problem but the devices are always unavailable

**Comment by gedm** [comment]
Hello, I'm seeing similar behavior with my WIFI devices.  Also, they indicate not available in HA but work fine in Ewelink.  Please let me know what information is needed to help resolve the issue.

**Comment by AlexxIT** [comment]
```
Traceback (most recent call last):
  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 598, in _process_ws_msg
    self._set_response(data[\"sequence\"], data[\"error\"])
                       ~~~~^^^^^^^^^^^^
KeyError: 'sequence'
```

**Comment by AlexxIT** [comment]
```
Traceback (most recent call last):
  File \"/config/custom_components/sonoff/__init__.py\", line 208, in async_setup_entry
    devices = await registry.cloud.get_devices(homes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 433, in get_devices
    raise Exception(resp[\"msg\"])
Exception: cannot found access token info
```

**Comment by AlexxIT** [comment]
Error is duplicate #1460
Fixed in master version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.8.0
