### ISSUE TITLE
POWR316D Missing a total cumul for the energy dashboard summary

### ISSUE THREAD

**Issue by chriscatuk** [AlexxIT/SonoffLAN#1477]
A nice detail in the energy dashboard is to show a per device consumption.

On 1st of the month, the monthly cumul of `POWR316D` is reset to zero and shows as a negative cost for the whole day equal to all of the past month cost.

Daily cumul is doing the same, daily.

Could we add a total cumul like HA requires for all energy tracking purpose?

we have
- `sensor.sonoff_<id>_energy_month`
- `sensor.sonoff_<id>_energy_day `

we would need
- `sensor.sonoff_<id>_energy` never reset to 0, ever

**Comment by AlexxIT** [comment]
For Hass  energy dashboard is better to use integration sensor
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#sonoff-pow

**Comment by chriscatuk** [comment]
> For Hass energy dashboard is better to use integration sensor https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#sonoff-pow

Already done before opening the ticket. But you'd rather have all users go to configuration.yaml do this instead of adding it to the integration?

**Comment by AlexxIT** [comment]
Sonoff energy sensors are could data. With specific logic. With personal reset time. They not compatible with Hass energy dashboard. 

Maybe them can be processed with some advanced logic. But I don't use them. And don't have time to make all researching.
