### ISSUE TITLE
reporting issue 

### ISSUE THREAD

**Issue by kourounas** [AlexxIT/SonoffLAN#1478]
I just copy paste this one. I am not familiar 

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 8:44:04 PM (13 occurrences)
Last logged: 8:44:04 PM

Detected code that calls async_forward_entry_setup for integration, sonoff with title: andreaziso@gmail.com and entry_id: 01J6FA47HRYQBDSVWZ8PD77S8Z, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
Detected code that calls async_forward_entry_setup for integration sonoff with title: andreaziso@gmail.com and entry_id: 01J6FA47HRYQBDSVWZ8PD77S8Z, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by AlexxIT** [comment]
#1468
