### ISSUE TITLE
Gestures T5-1C-86 FW 1.4.0 do not work

### ISSUE THREAD

**Issue by unixtall** [AlexxIT/SonoffLAN#1485]
Hi, my device has updated and now i cant use the gestures. I tried to rollback the version of SonoffLAN and the problem persists. So i guess the problem is with the new firmware.

Only the custom component shows if action "touch" is pressed. But slide left or slide right not.

I have check the debug log and only i can see when i power on the light (Action "touch").:

**2024-09-09 09:10:04 [D] 1001ec6df0 <= Local3 | 10.10.10.250:8081 | {'switches': [{'switch': 'on', 'outlet': 0}], 'electromotor': 1, 'percentageControl': 0, 'calibState': False, 'triggerType': 2, 'lightSwitch': 'off', 'lightMode': 6, 'shock': 1, 'doNotDisturb': 0, 'doNotDisturbTime': {'from': '22:00', 'to': '07:00'}, 'sledOnline': 'on', 'fwVersion': '1.4.0', 'rssi': -39} | 2348**

And in the diagnostic file i only can see that:

`"1001ec6df0": {
        "uiid": 209,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "timeZone": 2,
          "ssid": "***",
          "bssid": "***",
          "fwVersion": "1.2.0",
          "switches": [
            {
              "switch": "off",
              "outlet": 0
            }
          ],
          "lightSwitch": "off",
          "lightMode": 6,
          "shock": 1,
          "doNotDisturb": 0,
          "doNotDisturbTime": {
            "from": "22:00",
            "to": "07:00"
          },
          "onEffects": {
            "lightEffect": 1,
            "soundEffect": 0,
            "statusLight": "on",
            "statusLightTop": 1,
            "statusLightBelow": 1,
            "r": 0,
            "g": 255,
            "b": 0,
            "br": 60,
            "volume": 50
          },
          "offEffects": {
            "lightEffect": 2,
            "soundEffect": 2,
            "statusLight": "off",
            "statusLightTop": 1,
            "statusLightBelow": 1,
            "r": 0,
            "g": 0,
            "b": 255,
            "br": 5,
            "volume": 50
          },
          "configure": [
            {
              "startup": "stay",
              "enableDelay": 0,
              "width": 9000,
              "outlet": 0
            }
          ],
          "pulses": [
            {
              "pulse": "off",
              "switch": "off",
              "outlet": 0,
              "width": 500
            }
          ],
          "sledOnline": "on",
          "rssi": -72,
          "staMac": "***",
          "slide": 2,
          "reset_reason": "ESP_RST_POWERON",
          "only_device": {
            "ota": "success",
            "ota_fail_reason": 0
          },
          "addSubDevState": "off",
          "addTimeOut": 10,
          "preEffects": {
            "lightEffect": 1,
            "soundEffect": 0,
            "statusLight": "on",
            "statusLightTop": 1,
            "statusLightBelow": 1,
            "r": 0,
            "g": 255,
            "b": 0,
            "br": 60,
            "volume": 50
          }
        },
        "model": "T5-1C-86",
        "online": false,
        "local": true,
        "localtype": "plug",
        "host": "10.10.10.250:8081"
      },`

And another thing i saw, cloud doesnt work:

**_2024-09-09 09:23:27 [W] Can't login in cloud mode: ClientConnectorCertificateError(ConnectionKey(host='cn-apia.coolkit.cn', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=-1653947178309603543), SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'cn-apia.coolkit.cn'. (_ssl.c:1000)"))_**

Thanks you.

**Comment by AlexxIT** [comment]
Some problems with cloud server `cn-apia.coolkit.cn`. Not related to integration.
