### ISSUE TITLE
S60 not show in home assistant

### ISSUE THREAD

**Issue by yossiwu** [AlexxIT/SonoffLAN#1495]
Good morning all, 

I just installed s60 plug. 
I can see it correctly in ewelink app but it not show in home assistant at all, the integration is working correctly and sowing other devices.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN?tab=readme-ov-file#issues

**Comment by Rob-in-Molyvos** [comment]
I have 2 x S60 plugs. They load and work perfectly in HA 2024.9.2.

**Comment by Deedikjupijn** [comment]
Restarting my home assistant instance worked for me

**Comment by glendower** [comment]
Same problem here. Restarting HA did not fix the problem also using 2024.8.2

**Comment by klugev303** [comment]
@Deedikjupijn 
Socket S60 is it fully supported in local mode in integration?

**Comment by yossiwu** [comment]
I solved the problem with adding new account, maybe happen after changing password

**Comment by AlexxIT** [comment]
@klugev303 I have no idea about local mode. Don't have this model.

**Comment by Deedikjupijn** [comment]
> @Deedikjupijn @AlexxIT 
> Socket S60 is it fully supported in local mode in integration?

Im not sure how to check if it's fully supported in local mode. I'm able to see everything when adding the integration (had a couple issues with it first detecting the plugs, a restart ended up fixing it).

If you wish for me to test something specific on these plugs just reply.

![Screenshot_2024-09-24-09-40-39-925_io.homeassistant.companion.android.jpg](https://github.com/user-attachments/assets/e60f5371-a972-4dca-9d61-f31dfdb213c0)

**Comment by klugev303** [comment]
> > @Deedikjupijn 
> Switch the integration settings to **local mode only**, return to the outlet (plugs) and try to control it.

![изображение](https://github.com/user-attachments/assets/88a4b933-577f-4262-9b66-d0fc88932f1f)

**Comment by klugev303** [comment]
> > > > @Deedikjupijn
> Everything works!

Excellent! Thank you, then I will buy a lot of them for the house. Thank you!

**Comment by Deedikjupijn** [comment]
> > > > > @Deedikjupijn
> > Everything works!
> 
> Excellent! Thank you, then I will buy a lot of them for the house. Thank you!
> 

No problem, the only issue I had was initially getting them in home assistant, but I think it was some initialization script or smth that only ran at startup/install, cause a restart fixed it for me (use the app first to pair them and then log into the home assistant integration). They have been working amazing since then!
