### ISSUE TITLE
support for Sonoff TRVB

### ISSUE THREAD

**Issue by cpmarexel2f** [AlexxIT/SonoffLAN#1498]
Is it possible to implement support for Sonoff TRVB?

    "device": {
      "uiid": 7017,
      "params": {
        "subDevId": "3c2ef5fffebafc327017",
        "parentid": "10022783f5",
        "staMac": "***",
        "fwVersion": "1.2.1",
        "otaInfo": {},
        "sun": "000000a001a400be025800be025800be025800be056400a0",
        "mon": "000000a001a400be025800a0025800a003fc00be056400a0",
        "tues": "000000a001a400be025800a0025800a003fc00be056400a0",
        "wed": "000000a001a400be025800a0025800a003fc00be056400a0",
        "thur": "000000a001a400be025800a0025800a003fc00be056400a0",
        "fri": "000000a001a400be025800a0025800a003fc00be056400a0",
        "sat": "000000a001a400be025800be025800be025800be056400a0",
        "tempCorrection": 0,
        "battery": 97,
        "runVoltage": 132.7,
        "workMode": "1",
        "manTargetTemp": 190,
        "curTargetTemp": 40,
        "workState": "0",
        "fault": "reasonCode0",
        "temperature": "243",
        "trigTime": 1727111049341,
        "childLock": false,
        "windowSwitch": true,
        "openPercent": 100,
        "closePercent": 100,
        "ecoTargetTemp": 40
      },
      "model": "TRVZB",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "a48009dcbe"
    }

**Comment by AlexxIT** [comment]
Looks like it's a difficult device. A lot of unclear params.

**Comment by cpmarexel2f** [comment]
> Looks like it's a difficult device. A lot of unclear params.

Maybe this can be helpful!
![Screenshot_2024-09-25-13-15-25-959_com coolkit](https://github.com/user-attachments/assets/66c8620f-b442-46ef-8da8-a0ec94c7d98f)

**Comment by macxq** [comment]
+1 for initially limited support status(off/heating) + current temperature  would be awesome

**Comment by Pante90** [comment]
To be honest, someone doesn't want to integrate TVRZB with sonoffLAN, because if you connect direct with ZHA, there are all functions from these device, but if you using these device with sonoff zbridge or NSPanel Pro, the device is not avaible. It's very frustated and useless. It's a shame because this integration was really convenient. I think is not really complicated implement to use TRVZB but someone doesn't want.

**Comment by AlexxIT** [comment]
I discovered that this issue is a duplicate #1244
