### ISSUE TITLE
Work on two routers

### ISSUE THREAD

**Issue by stovedoctor** [AlexxIT/SonoffLAN#15]
it pulled my ewelink info into the sonoff.Jason file but when I go to 
Current entities in Developer Tools no sonoffs are there.
any other place to look or other settings ?
I even tried putting one in with the ID and switch in the config but nothing. 
could this be because all 12 of my ewelink sonoffs are on different wifi router and SSID . 
my HA HassIO new fresh install but its connected with Ethernet to my main DLS modem?router. and all my ewelink devises are on a separate router that is connected to the DSL moden/router. 
not sure why this would matter because my shellys using factory setting MQTT show up and they are on the same SSID as the ewelink sonoffs. 
HassOS 3.10 Home Assistant 0.105.3
raspberry pi 4

**Comment by AlexxIT** [comment]
Devices are detected by multicast. Multicast really may not pass between different routers.

**Comment by stovedoctor** [comment]
So you saying It can't find because on a separate router on same network?

**Comment by stovedoctor** [comment]
That was the problem 
I connected the pi to the same router and all sonoffs were found

**Comment by AlexxIT** [comment]
Yes, you can read how multicast traffic works. Many devices use it.
