### ISSUE TITLE
Zigbee bridge

### ISSUE THREAD

**Issue by hosting-io** [AlexxIT/SonoffLAN#150]
is there support for https://www.itead.cc/sonoff-zbbridge.html

**Comment by AlexxIT** [comment]
No, I don't have this device. But I can add cloud support if anyone share it with me via ewelink app.

**Comment by hosting-io** [comment]
im about to order one, so i can order you one if you think you will use it ?

**Comment by AlexxIT** [comment]
I can order myself, thanks. It can only work with sonoff devices. This is a minus.

**Comment by hosting-io** [comment]
Works with other smart devices certified by ZigBee Alliance.

**Comment by AlexxIT** [comment]
Ok, I'll order it soon.

**Comment by Roglogg** [comment]
> No, I don't have this device. But I can add cloud support if anyone share it with me via ewelink app.

I have two Zigbee devices.

Temperature sensor - SNZB02
Motion Sensor - SNZB03

If you send me an ewelink account from USA, you can share it with you to carry out the tests.

**Comment by spygibas** [comment]
I'm Look forward to these device too.

**Comment by AlexxIT** [comment]
Added support https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.3.0

**Comment by Roglogg** [comment]
The temperature and humidity keep coming out like before.

temperature: "1990"
humidity: "8401"

Without separation point.

[https://photos.app.goo.gl/u1qPghwgEXiFY8sj6](url)

**Comment by Roglogg** [comment]
The motion sensor works.
The sensor when it detects presence changes the Motion function to 1.

Idle: Motion = 0
With presence: Motion = 1

[https://photos.app.goo.gl/mE4gv1iFwJ8XPTsAA](url)

**Comment by fogarty** [comment]
Hello,
From what I can see the Temp / humidity works perfectly but seems like the Motion sensor is not even visible...
Aka missing the entity for it whil I do see the zbbridge and temps/humidity sensor
Thanks

**Comment by AlexxIT** [comment]
Will check it

**Comment by marcosamm** [comment]
Does the ZigBee bridge work on LAN mode?

**Comment by AlexxIT** [comment]
@marcosamm No. It works only on cloud mode

**Comment by OnTarget600** [comment]
Will this only work in cloud mode or is lan support on the horizon?  Eg is it a device issue or a programming one?

Love your work!

**Comment by AlexxIT** [comment]
Device firmware doesn't support LAN protocol.
