### ISSUE TITLE
privacy issues...

### ISSUE THREAD

**Issue by hs6666** [AlexxIT/SonoffLAN#1507]
got two sonoff s26 given to me, too awkward to reflash

if i was to create a ewelink acocunt using a throw away email address and and add the s26's using this addon, can i then...

1) Delete my ewelink account

2) Stop the units ever reaching out to the internet in my firewall

will my s26's keep working in home assistant but above all survive addon and ha upgrades?

thanks

**Comment by AlexxIT** [comment]
I have no idea. I guess if you're afraid to use cloud platforms - you shouldn't use their devices and/or their firmwares.
When designing this component, I never considered the option of disabling or blocking the cloud.
If it's important to you, run the tests yourself. Also explore other issues or forums. You are not alone in your wishes.
