### ISSUE TITLE
Sonoff TRVs

### ISSUE THREAD

**Issue by tim-mills** [AlexxIT/SonoffLAN#1508]
is there any plans to add support for TRVs?

**Comment by AlexxIT** [comment]
I have no idea what device you're asking about

**Comment by tim-mills** [comment]
Sounds like a no then? TRVZB

https://www.amazon.co.uk/SONOFF-Thermostatic-Radiator-Installation-Assistant/dp/B0CFXY26H1

**Comment by AlexxIT** [comment]
#1244
