### ISSUE TITLE
Integration Stopped Functioning after Update

### ISSUE THREAD

**Issue by brownr695cole** [AlexxIT/SonoffLAN#1511]
After Updating Home Assistant to
Core 2024.10.3
Supervisor 2024.10.2
Operating System 13.2
Frontend 20241002.3
Integration Devices and services, gives the following message:
This device cannot be added from the UI
You can add this device by adding it to your 'configuration.yaml'.
Tried removing both from Integrations and HACS and reinstalling with same results.

**Comment by AlexxIT** [comment]
Can you show screenshot with the error/problem?

**Comment by brownr695cole** [comment]
Is there something I can put in configuration.yaml to get it to functioning?

**Comment by AlexxIT** [comment]
What you get when you click to open documentation?

**Comment by brownr695cole** [comment]
It took me to https://github.com/AlexxIT/SonoffLAN

**Comment by AlexxIT** [comment]
Maybe you have something interesting in logs about this problem?

**Comment by brownr695cole** [comment]
Only a few repeating lines.
2024-10-21 00:07:06.824 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by brownr695cole** [comment]
Solution Found
I swap between 2 NUCs for every update that I decide to do.
I put the latest HAOS image on the other NUC and restored from full backup again.
Went to Integrations and was able to delete SonoffLan
Using Samba Share I deleted sonoff folder from custom_components
Went to HACS and removed Sonoff Lan
Restarted HA
Went to Hacs and downloaded Sonoff Lan and restarted HA.
Went to Integrations from Settings and reinstalled.
All is well!
Thank you for your responses and the work that you do.
It is much appreciated.
