### ISSUE TITLE
SONOFF LED drivers not available

### ISSUE THREAD

**Issue by magilla13** [AlexxIT/SonoffLAN#1519]
Hi,

From today morning it seems all my L2 Sonoff led driver went to offline and not working even if I can reach them via the ewelink app.
[config_entry-sonoff-6dc973a342efe5cabc38657981f06212.json](https://github.com/user-attachments/files/17661064/config_entry-sonoff-6dc973a342efe5cabc38657981f06212.json)

**Comment by AlexxIT** [comment]
This is really strange. I can see that cloud connection works for you. And two devices online. But three L2 and two Basic2 - offline. I don't know why them works for you form mobile app. Can't see any reason of problem.

**Comment by magilla13** [comment]
Hi,

Sorry. It was my fault. I didn't realize my phone connecting to the devices via BT and not via WIFI. Somehow the devices disconnected from my WIFI network. 

Sorry and thanks for your really fast review and feedback :)
