### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by drk-geek** [AlexxIT/SonoffLAN#152]
Fresh installation
Home Assistant 0.110.4

arch | armv7l
-- | --
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core in a Python Virtual Environment
os_name | Linux
os_version | 4.19.118-v7+
python_version | 3.7.3
timezone | Asia/Karachi
version | 0.110.4
virtualenv | true

![sonoff error](https://user-images.githubusercontent.com/63916817/83902767-6f175100-a776-11ea-9962-79a99a3ff7c1.png)

**Comment by AlexxIT** [comment]
You can manually install `pip install pycryptodome`
I don't know why venv don't do it automatically.

**Comment by drk-geek** [comment]
This issue is with latest version only while "master" works fine. I tried it and have no issues. I will see in next installation, if needed will install manually. Thanks for the support indeed.

**Comment by Gferretta** [comment]
Hi

**Comment by Gferretta** [comment]
Hi

A friend using a venv HA in Android has this problem:

Component error: sonoff - Integration 'sonoff' not found.
1:04:37 – Home Assistant (ERROR) - el mensaje se produjo por primera vez a las 0:49:00 y aparece 4 veces
Login attempt or request with invalid authentication from 127.0.0.1
1:01:57 – HTTP (WARNING) - el mensaje se produjo por primera vez a las 0:45:22 y aparece 5 veces
Error loading custom_components.sonoff. Make sure all dependencies are installed
0:49:00 – custom_components/sonoff/sonoff_local.py (ERROR)
'install' is deprecated, use 'async_install' instead
0:44:36 – custom_components/hacs/repositories/helpers/methods/installation.py (WARNING)

It's similar error?
Loosed a component or dependence?

Thanks

**Comment by AlexxIT** [comment]
@Gferretta This can be the same error. He need to install the dependencies manually. I do not know why they are not installed automatically.

**Comment by Gferretta** [comment]
and what would be the instruction to install the dependency manually in this case?  
We were unable to understand whether the dependency is crypto, as in the previous answer.

**Comment by AlexxIT** [comment]
It’s best to switch to hassio. There are no problems with dependencies.
To install the dependency in venv, you need to activate venv and run:
```
pip install pycryptodome
```

**Comment by drk-geek** [comment]
> It’s best to switch to hassio. There are no problems with dependencies.
> To install the dependency in venv, you need to activate venv and run:
> 
> ```
> pip install pycryptodome
> ```

Hi @AlexxIT I wish I could switch to hassio as in that case my RPI is fully engaged for only one application while in case of venv (Home Assistant Core) I am using other applications on same RPI.

**Comment by AlexxIT** [comment]
It's not necessary to install HassOS. You can use hassio on any Linux (not officially supported version)

**Comment by AlexxIT** [comment]
Probably not relevant
