### ISSUE TITLE
Error after uninstall

### ISSUE THREAD

**Issue by s-anderss** [AlexxIT/SonoffLAN#1520]
Hello!
I'm getting the following message after uninstalling the integration:

> Setup failed for 'sonoff': Integration not found.
> Failed to load integration for translation: Integration 'sonoff' not found.

How do I get rid of those messages?

![Bildschirmfoto vom 2024-11-07 17-59-36](https://github.com/user-attachments/assets/20d49bf8-6ff8-413e-ac16-7784f675dc7c)

**Comment by AlexxIT** [comment]
Probably the mention of sonoff was left in your config.

**Comment by s-anderss** [comment]
Ok, you're right.
I had some leftovers in the config.
I was confused by the "failed" messages and I thought there may be some leftovers from the package itself...
Thanks!
