### ISSUE TITLE
SNZB-05P shows as device_class: timestamp

### ISSUE THREAD

**Issue by Rob-in-Molyvos** [AlexxIT/SonoffLAN#1526]
My SNZB-05 is reporting as a timestamp. 
It is connected via ZBBridge-P
I am running V 3.8.1

'Developer Tools' - 'States'  shows the following

![SNZB-05P](https://github.com/user-attachments/assets/26dcd597-638d-4e32-9baa-722bd8fecc26)

I have attached the "Download Diagnostics" json file.

[sonoff-00779540fd4a240c7ce2a30276a068c0-Water Detector-6fc957e87a4916094c768ed8d0f40e35.json](https://github.com/user-attachments/files/17800844/sonoff-00779540fd4a240c7ce2a30276a068c0-Water.Detector-6fc957e87a4916094c768ed8d0f40e35.json)

**Comment by AlexxIT** [comment]
#1496 fixed in master version

**Comment by Rob-in-Molyvos** [comment]
Great.

Sorry for asking basic questions, but where do I download 3.8.2?

Thanks.

**Comment by AlexxIT** [comment]
It's not released yet. You can download current repo version manually or wait release.

**Comment by Rob-in-Molyvos** [comment]
Thank you, all now working as expected.
