### ISSUE TITLE
Bug report when reloading it trigers all switches

### ISSUE THREAD

**Issue by MarekPro1** [AlexxIT/SonoffLAN#1530]
Hello when I reload the integration or enable feature of device my automations that are cofigured to run when state of a switch is changed runs is there any way to fix this its realy scary when my Tesla unlocks randomly :) i have it configured on my switch in garage for children that they can go in the car.

**Comment by AlexxIT** [comment]
I didn't understand anything at all from your question.

**Comment by MarekPro1** [comment]
I have sonoff M5 switch installed and created on it automation and when electricity goes out in our house and the switch shuts off. In home assistant I have created automations on that switch that is: "When this switch is turned on or off do this.". And the point is, that when the electricity goes out in my home asistant all the automations runs like the switch was pressed.

Thank you for your time.

**Comment by AlexxIT** [comment]
Show device diagnostics for this switch.

**Comment by AlexxIT** [comment]
Your attachment has not uploaded to GitHub.

**Comment by MarekPro1** [comment]
Here my attachment on GitHub.
[sonoff-c8978584075f5b31ec4a011d65709faa-Vypinac garaz tesla-b4be86a423b2ab257fa78cb7362545aa.json](https://github.com/user-attachments/files/18010226/sonoff-c8978584075f5b31ec4a011d65709faa-Vypinac.garaz.tesla-b4be86a423b2ab257fa78cb7362545aa.json)

**Comment by AlexxIT** [comment]
Show yaml code of automation.

**Comment by MarekPro1** [comment]
alias: Tesla charge open (vypinac)
description: ""
triggers:
  - type: changed_states
    device_id: b4be86a423b2ab257fa78cb7362545aa
    entity_id: c3c1476ddfc17ae1f0cc4e153a8e3f11
    domain: switch
    trigger: device
conditions:
  - condition: device
    device_id: eccb630cdf4a459ee8c2627921d80c27
    domain: device_tracker
    entity_id: 59542847345d33e6ab431fab9377b5b6
    type: is_home
actions:
  - action: notify.mobile_app_marek_12
    metadata: {}
    data:
      message: firstf
  - device_id: eccb630cdf4a459ee8c2627921d80c27
    domain: cover
    entity_id: 5b6ae9cf654f74d8f15fba24e52265b9
    type: open
    enabled: true
mode: single

**Comment by AlexxIT** [comment]
`changed_states` also means to `unavailable` state. So the automation is working quite well.

**Comment by MarekPro1** [comment]
Okay my bad thank you for your help. Sorry for wasting your time. :(

**Comment by MarekPro1** [comment]
So its an home assistant issue look, when coding in visual editor its like this.
![image](https://github.com/user-attachments/assets/b9f4a16b-1401-4236-b9dc-bfa654812af3)
