### ISSUE TITLE
Sonoff POW2 16A POWR316 does not connect to my WiFi

### ISSUE THREAD

**Issue by fritserasmus** [AlexxIT/SonoffLAN#1532]
I have 16 Sonoffs on my LAN that send payloads to a LAN MQTT server
I have a few POW1 sonoffs and they all work seamlessly.

I recently acquired five POW2 POWR316 and tried to flash one. 
After online flashing it did not follow the screens as in the manual. 
An article warns against FTDI programmer so I acquired the exact same model that is used in the manual

After flashing from the web, the post-flash screens did not follow the screens as described, so I tried to connect to the POW2 with my phone. I could not see it.
I then read an article that I need to power the POW2 with AC.
I was then able to connect to the POW temp AP

Once selected the best Wifi AP an entered the PW it rebooted and I could no longer find it on my network.
Scanning network with Advanced AP Scanner cannot find it. From my DPHC server I could not find it.

I am using a reasonable modern TP-LInk router Archer AX72 connected to the internet and acts as the DHCP server and I also have a closer TP-Link Archer C6 that I want to connect thePOW2 to. I already have sonoffs connected to it

Settings on the TP_Link if someone wants to comment
2.4 GHz 
WPA2-PSK[AES]
Mode 802.11b/g/n

Does anyone have any suggestions on what changes to make to to see the POW 2 POW316 on my LAN? 

Thank you for the help

**Comment by AlexxIT** [comment]
I don't really see how this all relates to the current project.

**Comment by AlexxIT** [comment]
Try contacting official device support
