### ISSUE TITLE
Sonoff Pow Power Consumption

### ISSUE THREAD

**Issue by rhgiter** [AlexxIT/SonoffLAN#154]
cant get this to work. (is this the way to do it) ?
(no data is showing up on the sensor card)

```
- id: '1591449159423'
alias: pow2 pool forbrug
description: ''
trigger:
- at: '23:59'
platform: time
condition: []
action:
- data: {}
service: sonoff.update_consumption
```

**Comment by AlexxIT** [comment]
You need to fix the indentations

**Comment by rhgiter** [comment]
I have --  but how do I get the info in a card?
![image](https://user-images.githubusercontent.com/61065752/83977562-a9612980-a901-11ea-8ded-6e71c9dad141.png)

**Comment by AlexxIT** [comment]
I'm not an yaml automation specialist.
You can always call the service manually `/developer-tools/service`

**Comment by tonyp740613** [comment]
I have the same automation except I also have a trigger when Home Assistant is started.  The consumption values are empty when Home Assistant starts up and are only populated when you call the service.

- id: '1591190008529'
  alias: Sonoff update consumption
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data: {}
    service: sonoff.update_consumption

**Comment by rhgiter** [comment]
Thanks... 
but after Home Assistant 0.111.2   it dont work :/   i can start and stop my sonoff , but cant see consumption

**Comment by rhgiter** [comment]
how it get 2 digits 

![image](https://user-images.githubusercontent.com/61065752/85180804-a57bc280-b284-11ea-9d14-f9cad87aa659.png)

i try with this , but it dont work

{% set p=state_attr('switch.sonoff_100054cd9a', 'consumption') %}{{ p[:14]|sum if p|round(2)}}

**Comment by AlexxIT** [comment]
Use this:
```
{% set p=state_attr('switch.sonoff_100054cd9a', 'consumption') %}{{ p[:14]|sum|round(2) if p }}
```
