### ISSUE TITLE
Bug report: SONOFF TRVZB not showing the right status (turned ON or OFF)

### ISSUE THREAD

**Issue by franchojavilondo** [AlexxIT/SonoffLAN#1546]
Hello,

Currently testing and impresed by this whole solution. Many thanks for the efforts!!

I tested and can control my TRVZB from my radiators but for some reason the status is not updated. I can turn OFF and ON manually and the device works but the status is never updated in HA

Logs report:
Source: custom_components/sonoff/core/ewelink/cloud.py:616
Cloud ERROR: {'error': 411, 'deviceid': 'xxxxx', 'apikey': 'xxxxx', 'sequence': 'xxxxx', 'uid': 'xxxxxx'}

(I hide the uuids just in case is sensible data)

**Comment by AlexxIT** [comment]
#1244

**Comment by aferende** [comment]
For error 411 see here: https://github.com/AlexxIT/SonoffLAN/issues/1533

Seems an interference issue in your home.
Try to change ZigBee and wifi channel
