### ISSUE TITLE
Ihost on Home assitant

### ISSUE THREAD

**Issue by Yoshi31102020** [AlexxIT/SonoffLAN#1548]
I have all my devices zigbee Sonoff linked to the Sonoff's Ihost to have local control.  On the Ihost I installed Home Assistant  using Dockers but it can't see the  devices.
![image](https://github.com/user-attachments/assets/98dda112-7043-4ea5-ae34-db0f7c41ce9d)
 The only possible way is using the ewelink app, which means using the cloud.

**Comment by AlexxIT** [comment]
#1144
