### ISSUE TITLE
EWeLink Smart Switch 2, does this work in the app

### ISSUE THREAD

**Issue by rhgiter** [AlexxIT/SonoffLAN#1552]
EWeLink Smart Switch 2, does this work in the app so I can use it in home assistant

https://www.aliexpress.com/item/1005007115004182.html?spm=a2g0o.productlist.main.1.3e3738c3wWGlZa&algo_pvid=593372e2-4cc3-4473-aef4-e7abfe1913ba&algo_exp_id=593372e2-4cc3-4473-aef4-e7abfe1913ba-0&pdp_npi=4%40dis%21DKK%2162.50%2162.50%21%21%218.50%218.50%21%40211b807017350398036156735e4408%2112000039450383249%21sea%21DK%21824211687%21X&curPageLogUid=vJtixvCXZDW4&utparam-url=scene%3Asearch%7Cquery_from%3A

![image](https://github.com/user-attachments/assets/d1199223-9e94-4fe6-bf87-0b40af9397f0)

**Comment by AlexxIT** [comment]
I have no idea if it works in the app.
