### ISSUE TITLE
"Improvement": Add calibration values for TH16

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#157]
Hello
Is there a possibility to add calibration values for TH16 readings as an "improvement" of addon?
That is, most controller software has a "calibration value" (positive or negative) in order to adjust the measured value against another "control device" such as a thermohygrometer.
There are times that there are differences of +-1/2ºC and in terms of humidity it can be between +-10/15% depending on where the sensors are located.
It would be a good improvement to be able to correct the read value with those values that can be loaded in the configuration.yaml, for example with "CalibrationTemperature: 0" and "CalibrationHumidity: 0" as default.
The idea can be extended to any other device with read values like POW.

I have already made the same request to iTead to be added in the configuration of the TH, even without response.

Thanks and regards

**Comment by AlexxIT** [comment]
You can create template sensors and add difference there.
Example of Template Sensors:
https://github.com/AlexxIT/SonoffLAN#sonoff-pow-power-consumption

**Comment by Gferretta** [comment]
Ok.
I'm going to test it.
Thank you
