### ISSUE TITLE
Inching settings didn't work.

### ISSUE THREAD

**Issue by Resurrection2981** [AlexxIT/SonoffLAN#159]
I use eWelink app to set inching duration,but it seems didn't work on HA.

**Comment by AlexxIT** [comment]
Inching duration stored in device. It does not depend on HA.

**Comment by Resurrection2981** [comment]
But how  to explane my electric appliance(A glassdoor with detect rising edge
maybe) work well with eWelink,but I can't use HA to control it?
I hear relay on for a second and soon relay off when I use HA,but the door open when relay on immediately when I use eWelink.

**Comment by AlexxIT** [comment]
I did not understand the described situation

**Comment by Resurrection2981** [comment]
Sorry,my bad. It works.
