### ISSUE TITLE
Sonoff camera

### ISSUE THREAD

**Issue by anandsuppiah12** [AlexxIT/SonoffLAN#161]
Hi. Sorry to trouble you. I refer to the sonoff camera where you stated 
"In development: camera entity with still image and stream support.".

Doesn't this camera come with Rtsp support. Can we use that in HA for streaming? Or it doesnt work at all?

Thanks.

**Comment by diazwatson** [comment]
If your question is related to the camera model GK-200MP2-B then the answer is yes, it does come with RTSP Support.
This guys make a good video that explains how to integrate it with HA
https://www.youtube.com/watch?v=nYN53LiqVQk

**Comment by anandsuppiah12** [comment]
Thanks. I am thinking of getting one. Wanted to make sure because its stated as in development. Have a few devices lying around the house that cant be integrated into HA

**Comment by diazwatson** [comment]
I have mine working fine, the only things I have not figured out how to do is to 
- access the local recordings 
- control PTZ of the camera, 
- use the motion sensor of the camera in HA

other than that everything works fine

**Comment by anandsuppiah12** [comment]
Isn't PTZ supported in this addon?

**Comment by anandsuppiah12** [comment]
Awesome. Thanks. Guess that will work

**Comment by diazwatson** [comment]
Thanks @AlexxIT 
To clarify, Is it PTZ supported or is it not?

**Comment by AlexxIT** [comment]
PTZ supported, check this video. This is countrol from HA https://youtu.be/TnFS7qWgKoo

**Comment by diazwatson** [comment]
hahaha, looks Nice @AlexxIT could you point me in the right direction to find information on how to implement de UI in HA?

**Comment by diazwatson** [comment]
Forget my comment, just fund it 😆 
https://github.com/AlexxIT/SonoffLAN#sonoff-gk-200mp2-b-camera
