### ISSUE TITLE
Sonoff L1 no change state icon 

### ISSUE THREAD

**Issue by djgragra** [AlexxIT/SonoffLAN#164]
Integration is fine the only problem is that by creating a button the icon always remains with the last color selected even when it is turned off. This only happens to the BUTTON tab also using state_color: true
I attach image, of Led mobile
![Schermata 2020-06-17 alle 13 25 44](https://user-images.githubusercontent.com/65872226/84892641-39d80080-b09e-11ea-9fb8-e1aafa1038a0.png)

**Comment by AlexxIT** [comment]
Please show lovelace config of this section.

**Comment by djgragra** [comment]
This is the son off configuration in configuration.yaml

# Configurazione Sonff
sonoff:
 username: !secret username_sonoff
 password: !secret password_sonoff
 reload: always

This is the configuration of a card:

In this card the color icon change

entities:
  - entity: light.lettura
  - entity: light.mobile
  - entity: light.sonoff_10009912dd
  - entity: media_player.jack
title: Soggiorno
type: entities

In this card the color icon NOT change

cards:
  - entity: light.lettura
    hold_action:
      action: more-info
    icon: 'mdi:lamp'
    show_icon: true
    show_name: true
    tap_action:
      action: toggle
    type: button
  - entity: light.mobile
    hold_action:
      action: more-info
    icon: 'mdi:lamp'
    show_icon: true
    show_name: true
    tap_action:
      action: toggle
    type: button
  - entity: light.sonoff_10009912dd
    hold_action:
      action: more-info
    icon: 'mdi:led-strip'
    state_color: true
    show_icon: true
    show_name: true
    tap_action:
      action: toggle
    type: button
type: horizontal-stack

With or without “state_color: true" not change

Graziano Melzi

Please consider the environment before printing this e-mail notice
Il 21 giu 2020, 10:39 +0200, Alex X <notifications@github.com>, ha scritto:

**Comment by AlexxIT** [comment]
It's better to ask in Hass community
