### ISSUE TITLE
Sonoff RF Bridge Listens Each Rf Button Press as Double Event.

### ISSUE THREAD

**Issue by BigHomie90** [AlexxIT/SonoffLAN#166]
Hello. I am facing this wierd issue. I paired though ewelink app different kinds of remotes (keychain fob, the new sonoff remote with 8 buttons etc.)

The problem i am facing is that when i press an rf button the event listener in home assistant or node red catches it as double pressed. The only difference between the 2 events are some miliseconds and "id". My rf remotes have new batteries. Tried removing device and re pair it again but this problem persits. Sonoff Bridge Version : 3.4.1

Example of my event listener when i short press or long press a button on my rf remote.

Event 1 fired 2:43 AM:
```
{
    "event_type": "sonoff.remote",
    "data": {
        "entity_id": "remote.sonoff_1000bd680f",
        "command": 0,
        "ts": "2020-06-18T23:43:36.000Z",
        "name": "Button1"
    },
    "origin": "LOCAL",
    "time_fired": "2020-06-18T23:43:35.604709+00:00",
    "context": {
        "id": "477270c419c54ef19e144ea0aaa002ec",
        "parent_id": null,
        "user_id": null
    }
}
```
Event 0 fired 2:43 AM:
```
{
    "event_type": "sonoff.remote",
    "data": {
        "entity_id": "remote.sonoff_1000bd680f",
        "command": 0,
        "ts": "2020-06-18T23:43:36.000Z",
        "name": "Button1"
    },
    "origin": "LOCAL",
    "time_fired": "2020-06-18T23:43:35.561452+00:00",
    "context": {
        "id": "fe85cb6447a145e4b91e2dd4bec4b63b",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by BigHomie90** [comment]
Found a work around using node red. Placing an RBE node between event listener and switch node. Blocks always the first message, so i receive only one command.

**Comment by AlexxIT** [comment]
This problem fixed in https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.0.4
Which version do you use?

**Comment by BigHomie90** [comment]
Hello and sorry for the late reply. I am using the beta version dd02267.

**Comment by AlexxIT** [comment]
dd02267 - 2020-05-22
2.0.4 - 2020-05-28

You need to upgrade.
