### ISSUE TITLE
No Sonoff devices show up

### ISSUE THREAD

**Issue by PcOnline2004** [AlexxIT/SonoffLAN#171]
I did install all steps as your guide. But have no device appear on hass.

**Comment by patrondumitru** [comment]
i did also all instalation like in description, and also i have the same issues.
i have updated firmware on sonoff mini up to 3.5, but I didnt see any sonoff devices

**Comment by menno99** [comment]
I had a working system...but it hasn't worked since the last Home Assistant update. (Sonoff.json is being created) only there is no entity available anymore. model Sonoff Basic

**Comment by PcOnline2004** [comment]
Wow, everything works perfect now. Thanks
