### ISSUE TITLE
Essential Oils Diffuser support

### ISSUE THREAD

**Issue by Thrasher2020** [AlexxIT/SonoffLAN#173]
eWeLink Diffuser - details :

manufacturer SHINGHUNG
model YB-01
sw versson PSF-BTA-GL v2.9.0
cloud online
rssi -66

If you need anything from me to get this working just let me know. Currently I can only turn it on/off but it has a light and fan and also a water sensor. Thanks.

**Comment by AlexxIT** [comment]
Please, share it to my account sonofflan@gmail.com in eWeLink app.
This may not work, depending on your country.

**Comment by Thrasher2020** [comment]
I've shared it with you.

**Comment by AlexxIT** [comment]
Got. Can I turn it on for a short time at any time?

**Comment by Thrasher2020** [comment]
Of course, feel free :)

**Comment by AlexxIT** [comment]
Please send link to device. Can't google it.

**Comment by Thrasher2020** [comment]
https://www.amazon.co.uk/dp/B07WF7MQ17?ref=ppx_pop_mob_ap_share

**Comment by AlexxIT** [comment]
Check https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.2.1

**Comment by Thrasher2020** [comment]
Working perfectly. Thank you for getting this to work :)
