### ISSUE TITLE
Add friendly names for children buttons and sensors

### ISSUE THREAD

**Issue by jonrberg** [AlexxIT/SonoffLAN#18]
Hi
I can see the sonoff bridge in HA and have added this with correct id to the configuration.yaml file, but I does not get any alarms from the door sensors in HA. Should this work with DW1 sensor?
automation:
- alias: Test RF
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      command: 0
  action:
    service: homeassistant.toggle
    entity_id: remote.sonoff_1000abcdefg

**Comment by AlexxIT** [comment]
Have you something like this `remote.sonoff_xxx` in entities list?

Go to http://localhost:8123/developer-tools/event (use your IP).
Listen to events => `sonoff.remote` => Start Listening

**Comment by jonrberg** [comment]
Hi and thanks for answare

I now also have added a TX0 switch, and its works perfect. I see nothing in the eventlog for sonoff remote, just for the sonoff switch. I entities list remote.sonoff_xxx (bridge) and switch.sonoff_xxx 
Regards

**Comment by AlexxIT** [comment]
@jonrberg enable debug log and look there.

**Comment by jonrberg** [comment]
Hi Alex
I do not know why, but no I see updates in the log for my sensors. The only problem is that there is no unique key say what sensor is triggered. The id in the message I include change every time. 
This is a logg message where the id change every time for det same sensor.

{
    "event_type": "sonoff.remote",
    "data": {
        "entity_id": "remote.sonoff_xxxxxx",
        "command": 2,
        "ts": "2020-02-15T19:39:39.000Z"
    },
    "origin": "LOCAL",
    "time_fired": "2020-02-15T19:39:39.400406+00:00",
    "context": {
        "id": "96468bf512104d17baf37c1f443606e7",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by AlexxIT** [comment]
@jonrberg please look friendly_name for DW1 in file sonoff.json
Are they there?

**Comment by jonrberg** [comment]
Hi Alex
No friendly_name for my DW1 sensors, just for my Tx0 swithes. For DW1 sensors I just see this ID pr sensor

:[{"rfChl":0,"rfVal":"309801Xxxxxxx"},{"rfChl":1,"rfVal":"304xxxxxxxxx"},{"rfChl":2,"rfVal":"31CE01Xxxxxxxxx"},{"rfChl":3,"rfVal":"312401Xxxxxxxx"},{"rfChl":4,"rfVal":"3188xxxxxxxxxxxx"},{"rfChl":5,"rfVal":"316A0xxxxxxx"}],

**Comment by AlexxIT** [comment]
I heard https://github.com/peterbuga/HASS-sonoff-ewelink somehow support sensors. Don't know how.

**Comment by AlexxIT** [comment]
@jonrberg I looked at the implementation of Peterbuga.
Add friendly names in future versions.

**Comment by jonrberg** [comment]
Hi Alex
Thanks for your respond and help. I`m new to hassio so the problem was not with your integration. Everything works now. The friendly names is just a wish, makes it more easy when look in logs.
Thanks!

**Comment by miketree1** [comment]
I too am having problems with RF bridge. Not sure if it's because I just don't understand.
I tried 'Listen to events => sonoff.remote_xxxxxx => Start Listening' , but nothing when I operate sensors.

**Comment by jonrberg** [comment]
Hi
You have to listen for *
Then you see everything. First you need to configure file configuration.yaml as desctiption says.

**Comment by miketree1** [comment]
What do I need in configuation.yaml 
The only stuff I can see specific to remote. is automation: and scripts:

**Comment by AlexxIT** [comment]
@miketree1 @jonrberg event name `sonoff.remote`! Not `sonoff.remote_xxxxxx`!

**Comment by miketree1** [comment]
mine is called  remote.sonoff_10007c517b  
I tried remote.sonoff too.  still nothing.
Do I need to add anything to configuration.yaml specifically for the RF bridge?

**Comment by AlexxIT** [comment]
@miketree1 if remote.sonoff_10007c517b is already in the entities list, you should already receive events from it.

The name of the event is `sonoff.remote`. No need to write entity name there.

**Comment by miketree1** [comment]
I've enabled debug logs in configuration.yaml. Where are they found?

**Comment by AlexxIT** [comment]
@jonrberg @miketree1 latest update for RF Bridge
