### ISSUE TITLE
POW R2 not load consumption

### ISSUE THREAD

**Issue by serlinGi** [AlexxIT/SonoffLAN#181]
Hi Alex,

among the many sonoff devices used thanks to your custom, I can't get out the consumption values and the relative history of the POW R2. the "consumption" attribute does not appear in the list of device attributes
I am attaching images of how I configured the sensors and the results in the template.
I used the sonoff.update_consumption service call

I did the tests both in "local" and in "legacy" mode

where am i wrong?

![attriuti sonoff](https://user-images.githubusercontent.com/63103970/86501612-ca028f00-bd9a-11ea-8e7a-b426921b6855.JPG)
![sensori](https://user-images.githubusercontent.com/63103970/86501615-d1299d00-bd9a-11ea-90be-ac316f29d974.JPG)
![valori nel template](https://user-images.githubusercontent.com/63103970/86501626-edc5d500-bd9a-11ea-90b5-d1e6f7b883e0.JPG)
![grafica](https://user-images.githubusercontent.com/63103970/86501634-f8806a00-bd9a-11ea-92c7-f774af8663b0.JPG)

**Comment by AlexxIT** [comment]
Hi. Consumption get update from the cloud. You need to use auto mode.

**Comment by serlinGi** [comment]
thank you
