### ISSUE TITLE
can't select sonoff switches as devices in automation

### ISSUE THREAD

**Issue by hausnummer** [AlexxIT/SonoffLAN#187]
my sonoff switches show up as entities (under configuration) but not as devices. therefore in automation they can be used as triggers but not as actions. Switching via Lovelace UI works fine. any suggestions?

**Comment by Skuzmitoo** [comment]
I have the same issue. Please help !

**Comment by hewwoworld** [comment]
In automations, you do not use them as devices. Go to call service, and then whatever type of device you have. For example, if it is a light, click toggle.light, and you can select your switch. I had the same issue; it's not very clear at first.

**Comment by hausnummer** [comment]
Thanks hewwoworld, it works! 
BTW my zigbee devices do show up as devices under actions. That apparently confused me. Thanks again.
