### ISSUE TITLE
Support WiFi Smart Circuit Breaker and Sonoff Hum

### ISSUE THREAD

**Issue by kuradi** [AlexxIT/SonoffLAN#19]
some outputs:

`[
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "",
    "brandName": "ITEAD",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceStatus": "",
    "deviceUrl": "",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "55e00a982ed643527f31425d",
        "description": "",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
        "model": "PSA-BTA-GL",
        "modelInfo": "57e4e659ae0f76857b1603ae",
        "ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
        "uiid": 19
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": false,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "fwVersion": "2.0.2",
      "mode": "normal",
      "password": "",
      "rssi": -60,
      "ssid": "",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "state": 0,
      "switch": "off",
      "water": 1
    },
    "productModel": "Sonoff Hum",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 19
  },
  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "",
    "brandName": "WDYK",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "deviceUrl": "",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "5b97ab4db4f633024aa10e4f",
        "chipid": "00C1F9C5",
        "description": "20181226006",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6d59\u6c5f\u601d\u521b\u7535\u529b\u79d1\u6280\u80a1\u4efd\u6709\u9650\u516c\u53f8",
        "model": "PSF-B01-GL",
        "modelInfo": "5b99ce654854868a31c35364",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u5355\u901a\u9053\u5f00\u5173",
        "uiid": 6
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "fwVersion": "3.0.0",
      "init": 1,
      "pulse": "off",
      "pulseWidth": 500,
      "rssi": -55,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "startup": "stay",
      "switch": "on",
      "version": 8
    },
    "productModel": "ZJSB9-80",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedTo": [],
    "showBrand": true,
    "type": "10",
    "uiid": 6
  }
]`

more outputs for hum:

`//////////////////////////////
water shortage, switch off
//////////////////////////////
{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 3,
"switch": "off",
"timers": [],
"water": 0
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}

//////////////////////////////
water shortage, switch on, position 1
//////////////////////////////
{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\ u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 1,
"switch": "on",
"timers": [],
"water": 0
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}

//////////////////////////////
water shortage, switch on, position 2
//////////////////////////////
{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 2,
"switch": "on",
"timers": [],
"water": 0
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}

//////////////////////////////
water shortage, switch on, position 3
//////////////////////////////

{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 3,
"switch": "on",
"timers": [],
"water": 0
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}

//////////////////////////////
water normal, switch off
//////////////////////////////
{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 3,
"switch": "off",
"timers": [],
"water": 1
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}

//////////////////////////////
water normal, switch on, position 1
//////////////////////////////
{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 1,
"switch": "on",
"timers": [],
"water": 1
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}

//////////////////////////////
water normal, switch on, position 2
//////////////////////////////
{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 2,
"switch": "on",
"timers": [],
"water": 1
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}

//////////////////////////////
water normal, switch on, position 3
//////////////////////////////
{
"__v": 0,
"_id": "[hidden]",
"apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"brandLogoUrl": "",
"brandName": "ITEAD",
"createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
"deviceStatus": "",
"deviceUrl": "",
"deviceid": "[hidden]",
"devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"extra": {
"_id": "[hidden]",
"extra": {
"apmac": "xx:xx:xx:xx:xx:xx",
"brandId": "55e00a982ed643527f31425d",
"description": "",
"mac": "xx:xx:xx:xx:xx:xx",
"manufacturer": "\u6df1\u5733\u521b\u6613\u667a\u80fd\u7cfb\u7edf\u6709\u9650\u516c\u53f8",
"model": "PSA-BTA-GL",
"modelInfo": "57e4e659ae0f76857b1603ae",
"staMac": "xx:xx:xx:xx:xx:xx",
"ui": "\u4e09\u6863\u52a0\u6e7f\u5668",
"uiid": 19
}
},
"group": "",
"groups": [],
"ip": "[hidden]",
"location": "",
"name": "[hidden]",,
"offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"online": true,
"onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
"params": {
"fwVersion": "2.7.0",
"mode": "normal",
"password": "",
"rssi": -47,
"sledOnline": "on",
"ssid": "",
"staMac": "xx:xx:xx:xx:xx:xx",
"state": 3,
"switch": "on",
"timers": [],
"water": 1
},
"productModel": "Sonoff Hum",
"settings": {
"alarmNotify": 1,
"opsHistory": 1,
"opsNotify": 0
},
"sharedTo": [],
"showBrand": true,
"type": "10",
"uiid": 19
}`

circuit breaker link:
https://www.aliexpress.com/item/3P-WiFi-Smart-Circuit-Breaker-Automatic-Switch-overload-short-circuit-protection-for-Amazon-Alexa-and-Google/32954500280.html?spm=a2g0s.9042311.0.0.27424c4d2e8iCD

**Comment by AlexxIT** [comment]
I see Sonoff Hum have firmware version 2.7.0.
Devices of this version either do not work with the local protocol or only work when the Internet is off.
Can you turn on debug logs, block the device Internet and check if there are messages from device in the logs?

I see WiFi Smart Circuit Breaker have firmware version 3.0.0.
It should already work.

**Comment by AlexxIT** [comment]
Here #31

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by AlexxIT** [comment]
@kuradi you still here?

**Comment by AlexxIT** [comment]
No feedback
