### ISSUE TITLE
How To config Smart color Light ?

### ISSUE THREAD

**Issue by Tykwondo1** [AlexxIT/SonoffLAN#194]
Hello , after several hours of reading again lol and because I'm new with HA. I did not manage to have the same configuration with the color bulbs(i have the setting in ewelink app for color, not in HA) as with the LEDs(come whit like it on sonoff config).
I tried more, but I still have errors.
How to do ?
What is the easiest way?

thank you

![Color 1](https://user-images.githubusercontent.com/66892028/87678023-7142d700-c748-11ea-84d7-61e03a5a638f.jpg)
![color 2](https://user-images.githubusercontent.com/66892028/87678046-76a02180-c748-11ea-90e5-8b33ea6ef139.jpg)

**Comment by AlexxIT** [comment]
Please show logs https://youtu.be/Lt5fT4N5Pm8

**Comment by Tykwondo1** [comment]
it works with the last update, thanks to @Alexxit for the work and the incredible support
thank you
