### ISSUE TITLE
3-Gang Switch - Unable to Define Device Class

### ISSUE THREAD

**Issue by rronni** [AlexxIT/SonoffLAN#196]
I have a 3 Gang KTNNKG Light Switch, which is detected and working fine. SonoffLAN finds it as 10002b0b6d, with the 3 individual switches coming up as: 10002b0b6d_1, 10002b0b6d_2, and 10002b0b6d_3.

Despite defining the device class as device_class: light for these three entities, they still show up as switches.

Code:
```
  devices:
    10001d9395:
      device_class: light
      name: Living Room Lamp
    100024bfcf:
      device_class: fan
      name: Living Room Fan    
    1000709623:
      device_class: light
      name: Living Room Main Light
    10002b0b6d_1:
      device_class: light
      name: Kitchen Light 1
    10002b0b6d_2:
      device_class: light
      name: Kitchen Light 2
    10002b0b6d_3:
      device_class: light
      name: Garden Floodlight
    100014b175:
     device_class: light
     name: Xmas Tree Lights
```

Device_IDs from Developer tools:
![image](https://user-images.githubusercontent.com/66040518/87831699-21fdc300-c87c-11ea-8910-e8b4a263cd0f.png)

From Lovelace - Showing Item detail and status under switches:
![image](https://user-images.githubusercontent.com/66040518/87831393-4b6a1f00-c87b-11ea-950c-8bce8070c340.png)

Same code working for Other Light switches:
![image](https://user-images.githubusercontent.com/66040518/87831452-73598280-c87b-11ea-897c-ac004b60a6cd.png)

Any suggestions on how i can update this so it shows as a "light" entity, with the bulb icon etc?

Many Thanks
R

**Comment by rronni** [comment]
Is this down to not having full support for the 3 Gang KTNNKG Light Switch? i.e The Naming convention, (-1, -2, and -3 at the end of the device ID for the three light switches).

Obviously it picks them up as sockets, but not light switches..... Any suggestions?

Thanks!
R

**Comment by AlexxIT** [comment]
```yaml
  devices:
    10002b0b6d:
      device_class: [light, light, light]
```

**Comment by rronni** [comment]
How can i name them after defining the 3 devices as lights?
