### ISSUE TITLE
Question about support Sonoff RF

### ISSUE THREAD

**Issue by miketree1** [AlexxIT/SonoffLAN#20]
Will support for Sonoff RF be implemented?

**Comment by AlexxIT** [comment]
Do you have one? Does not work?

**Comment by miketree1** [comment]
I do have one. It doesn't work.
I think I can see the device in .sonoff.json but nothing in HA.

**Comment by AlexxIT** [comment]
What version of firmware? Is it the last?

**Comment by miketree1** [comment]
I tried it with (i think) 2.6. didn't work, so I updated it to 3.3. Still no joy.

**Comment by AlexxIT** [comment]
3.3 should work. There may be problems with the multicast in the network.

**Comment by miketree1** [comment]
I have other switches that work, mostly sonoff mini

FYI I previously had it working with this....
https://github.com/peterbuga/HASS-sonoff-ewelink 
but I have since removed that.

**Comment by AlexxIT** [comment]
Try on / off device with physical button.
Are all devices connected to the same router?
I have Sonoff Basic without RF. It works.

**Comment by miketree1** [comment]
yes. All to same router.
The device works fine with ewelink.
like I said, it shows in .sonoff.json

**Comment by maciak** [comment]
Hi,
I seem to have a similar issue. It shows I think in HA under remote.rf but don't know what to do with it? none of the buttons or sensors connected to it via ewelink app got transferred.

**Comment by AlexxIT** [comment]
@miketree1 try power on/off your device. And switch on/off with button or RF remote.

**Comment by AlexxIT** [comment]
@maciak Go to this issue #18

**Comment by miketree1** [comment]
I've just added a TH16 to ewelink, and that show in HA.

**Comment by miketree1** [comment]
"@miketree1 try power on/off your device. And switch on/off with button or RF remote."

Tried that. Still nothing.

**Comment by miketree1** [comment]
The device details are definitely in the .sonoff.json file. But somehow not being pulled trough to Entities

**Comment by miketree1** [comment]
Is there any debugging I can do?

**Comment by miketree1** [comment]
This does not appear to be working. I wish I could tell you what I did, but I can't. Maybe it was working all along and I was getting confied with IDs.

Anyway, thanks for your help.

**Comment by AlexxIT** [comment]
@miketree1 you can enable debug log and check your device there.
