### ISSUE TITLE
Sonoff Integration not found

### ISSUE THREAD

**Issue by JayJay-SmartHome** [AlexxIT/SonoffLAN#200]
Installed HACS
Installed Sonoff LAN Repository via HACS Custom components repo's

Sonoff folder is shown in config/custom_components

also added to configuration.yaml:

Sonoff:
  username: obsure@obsure.com
  password: obsure
  mode: cloud

and saved config file.

tried to reset HA but config validation says configuaration not valid.
Component error: Sonoff - Integration 'Sonoff' not found.

its for a Sonoff L! Led Strip light

Thanks

**Comment by AlexxIT** [comment]
`sonoff:` lower case important
