### ISSUE TITLE
TH16 "crazy Humidity" after update to v2.3.0

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#201]
Hi.
After the update to version 2.3.0, the humidity values went "crazy".
Attached screenshot and debug

![AlexxIT Sonoff Humidity problem v230](https://user-images.githubusercontent.com/65413059/87994931-8ad77c00-cac4-11ea-9661-efc1c266be2a.jpg)

[AlexxIT Sonoff Humidity problem v230.txt](https://github.com/AlexxIT/SonoffLAN/files/4950420/AlexxIT.Sonoff.Humidity.problem.v230.txt)

**Comment by Gferretta** [comment]
![Screenshot_20200720-234209_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/88006729-bcf7d680-cae2-11ea-9c1f-a526740de627.jpg)

**Comment by Gferretta** [comment]
![20200721_095453.jpg](https://user-images.githubusercontent.com/65413059/88057435-7634cb80-cb38-11ea-8c5e-f6a727f45a39.jpg)

**Comment by Tykwondo1** [comment]
I had the same problem, my setting was at 1 minute, I changed for 2 minutes, restart HA, and everything came back ok
![capture](https://user-images.githubusercontent.com/66892028/88065485-a7ae9680-cb3a-11ea-8549-172c11c69d0a.jpg)

**Comment by Gferretta** [comment]
> 
> I had the same problem, my setting was at 1 minute, I changed for 2 minutes, restart HA, and everything came back ok
> ![capture](https://user-images.githubusercontent.com/66892028/88065485-a7ae9680-cb3a-11ea-8549-172c11c69d0a.jpg)
> 

I will try
Thanks

**Comment by Gferretta** [comment]
Not work for me 😔
Modify to 2 minutes and restart HA

Humidity 0.81%  😲

![Screenshot_20200721-115726_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/88070829-80ab9100-cb49-11ea-93f2-549c50b5dc82.jpg)

**Comment by pdgithub78** [comment]
I also see some strange updates since the last version. For example the temperature reads 41 degrees, but for a moment it changes to 0.41, then goes back to 41.
<img width="366" alt="Screenshot 2020-07-22 at 08 01 06" src="https://user-images.githubusercontent.com/60198486/88145094-d20f5b00-cbf1-11ea-957c-bc6fcd60af5d.png">

**Comment by PcOnline2004** [comment]
> I also see some strange updates since the last version. For example the temperature reads 41 degrees, but for a moment it changes to 0.41, then goes back to 41.
> <img alt="Screenshot 2020-07-22 at 08 01 06" width="366" src="https://user-images.githubusercontent.com/60198486/88145094-d20f5b00-cbf1-11ea-957c-bc6fcd60af5d.png">

With mine, all Sonoff sensors gone after update to v2.3.0. Why do you still have sensors?

**Comment by hewwoworld** [comment]
I've had a similar issue with my humidity sensor since the update. Until a fix is released, I'd recommend reverting back to 2.2.3.
![Humidity Glitch](https://user-images.githubusercontent.com/42094954/88212007-7626ef80-cc4e-11ea-80b1-0ad7c63a2402.png)

**Comment by PcOnline2004** [comment]
Yeah, back to 2.2.3. Works again!

**Comment by Tykwondo1** [comment]
> > I had the same problem, my setting was at 1 minute, I changed for 2 minutes, restart HA, and everything came back ok
> > ![capture](https://user-images.githubusercontent.com/66892028/88065485-a7ae9680-cb3a-11ea-8549-172c11c69d0a.jpg)
> 
> I will try
> Thanks

this fix not work , is has temporise , i wait for new fix to.

**Comment by hewwoworld** [comment]
Bug is fixed now. Update to latest version
