### ISSUE TITLE
Sonoff L1 shown as Entity but not as a device

### ISSUE THREAD

**Issue by JayJay-SmartHome** [AlexxIT/SonoffLAN#204]
Hi Alex
Kudos for a great job and thanks your help on the last issue I raised - sorted👍

I can access the Sonoff L1 LED Strip via Lovelace dashboard but assigned to area : lights (See pic)
![30BE4BFB-037F-4851-9189-666966D814F5](https://user-images.githubusercontent.com/68328562/88278486-5fc67580-ccda-11ea-8068-abd7a73d4782.png)

I can’t seem to be able to move to a room and when I look at my device list to do this - it doesn’t exist yet it does under entity list. Is this right?

Sonoff L1 v2.7.0 firmware

Thanks again

**Comment by AlexxIT** [comment]
Duplicate #83
