### ISSUE TITLE
Add IP address information

### ISSUE THREAD

**Issue by cobradodo** [AlexxIT/SonoffLAN#205]
Hi, I wanted to ask if it was possible to add the ip address of the sonoff in the attributes of the entities (example Sonoff Mini).
Thank you

**Comment by issinsky** [comment]
Hi!
Same request.
I have different subnets for Wi-Fi 2GHz, Wi-Fi 5GHz and wired LAN devices.
Sonoff devices and HA server are in different subnets.
Multicast traffic is not routable
That's why mDNS doesn't work for me.

**Comment by AlexxIT** [comment]
@issinsky specifying the IP address will not help. All local protocol is built on mDNS. You need to use cloud control.

**Comment by issinsky** [comment]
If I know the IP address it is enough to send API commands to get the state and to switch it on/off. Firmware 3.5.0 doesn't request to send deviceid in request.

**Comment by AlexxIT** [comment]
Many devices with firmware less than 3.5.
They do not have a command to query the device status.
I have never seen it work.

But I'll check. I have a D1 on firmware 3.5 and a Mini on firmware 3.6
But getting a status using the pull method is not real-time. This will not work well.

**Comment by issinsky** [comment]
I see. Thank you for details.

**Comment by cobradodo** [comment]
The original request is another...
I need, if is possible, to get ip address information  for example in one switch attributes

**Comment by Gferretta** [comment]
> The original request is another...
> I need, if is possible, to get ip address information  for example in one switch attributes

Hi
You can add in Configuration.yaml

sonoff:
sensors: [ host ]

Reboot HA And you can see a New sensor with the IP of each devices.

Regards

**Comment by ammaralfarsi** [comment]
> > The original request is another...
> > I need, if is possible, to get ip address information  for example in one switch attributes
> 
> Hi You can add in Configuration.yaml
> 
> sonoff: sensors: [ host ]
> 
> Reboot HA And you can see a New sensor with the IP of each devices.
> 
> Regards

this works very well. thx

**Comment by AlexxIT** [comment]
Supported in latest version
