### ISSUE TITLE
scan interval in cloud mode

### ISSUE THREAD

**Issue by maxmib** [AlexxIT/SonoffLAN#207]
I use an ewelink plug‘s state to trigger an automation ，so I want to know how cloud mode works and the frequency that sonofflan  scan my devices when it works in cloud mode.Thanks.

**Comment by AlexxIT** [comment]
The devices send the new state immediately themselves. With local and cloud management.

**Comment by maxmib** [comment]
what about device's offline state detection ?

**Comment by AlexxIT** [comment]
Cloud and local modes send offline state after some time of device inactivity.
