### ISSUE TITLE
Devices without logo Sonoff do not work with SonoffLAN when update to v2.3

### ISSUE THREAD

**Issue by PcOnline2004** [AlexxIT/SonoffLAN#209]
I found that all devices (even made by Sonoff) but if do not have logo on eWelink app will be not works anymore with SonoffLAN. Here are Sonoff POW and tx3c...
![927A7C6E-13BB-42F5-AA94-E454C131517B](https://user-images.githubusercontent.com/63231585/89033779-c5ad9f80-d361-11ea-99f6-6589aaf55d7b.jpeg)
![46D85C68-ADEF-41B4-8D4F-6B1FBAFA6A22](https://user-images.githubusercontent.com/63231585/89033785-c80ff980-d361-11ea-8ec2-4e3d8be4a27d.jpeg)

**Comment by PcOnline2004** [comment]
More photos.
![EE65FABD-4C63-47B1-8D44-DAC368BE9743](https://user-images.githubusercontent.com/63231585/89090434-10183600-d3cd-11ea-9888-31c2a474aaee.jpeg)
![BD2256A3-F087-463C-87D8-7AD75C8A02E4](https://user-images.githubusercontent.com/63231585/89090438-14445380-d3cd-11ea-8f94-c617c9ec25cd.jpeg)

**Comment by ianfretwell** [comment]
I have 9 devices - not one of which is made by Sonoff (and none of which show a Sonoff logo in eweLink) - they all work absolutely fine in SonoffLAN for me...so perhaps you're doing something wrong ?

**Comment by PcOnline2004** [comment]
> I have 9 devices - not one of which is made by Sonoff (and none of which show a Sonoff logo in eweLink) - they all work absolutely fine in SonoffLAN for me...so perhaps you're doing something wrong ?

@ianfretwell All of my devices work very from beginning. This issuse just only happen when I upgrade HACS and SonoffLAN to v2.3.0. I dont know why. I try to reinstall couple times but no luck.

**Comment by tjhiwa** [comment]
Possibly you are on LAN mode, with reload option disabled or set to once. Try deleting the .json file, or put reload: always, then restart HA. You can revert back after that.

**Comment by frma71** [comment]
I'm seeing the exact same thing:

I've got a sonoff pow (not R2). It works fine in cloud mode, but doesn't show up at all in local mode. I've tried nuking .sonoff.json and I've got:

sonoff:
username: fredrik.markstrom@gmail.com
password: YOURGUESS
mode: local
reload: always
force-update: [temperature, power]

in my configuration.yaml

The eWelink app says:

Name: Sonoff pow
Current Version: 2.6.1
Manufacturer: Maker
Model: Sonoff Pow
FW Name: PSC-B01-GL

**Comment by AlexxIT** [comment]
Is problem still actual?
