### ISSUE TITLE
Install two sonoff component

### ISSUE THREAD

**Issue by elserge82** [AlexxIT/SonoffLAN#21]
Hey Alexx

Sorry for my newbie question,I have a problem with the installation the folder sonoff already exist from a previous custom component . I want to install yours without deleting the other one . For testing and migrating slowly without losing some automatons and so on is there anyway I can do that ? 

Thank you

**Comment by AlexxIT** [comment]
You should:
- rename the folder to `sonoff2`
- rename line in `__init__.py` => `DOMAIN = 'sonoff2'`
- raname line in `configuration.yaml` => `sonoff2:`

**Comment by miketree1** [comment]
oooooh. That's interesting. Wish I'd seen that earlier

**Comment by elserge82** [comment]
Well Thanks Alex for your quick reply. My old component was https://github.com/peterbuga/HASS-sonoff-ewelink I only changed the folder name of the old component for backup. Your component is using the same device IDs and param.. so I had to do minor changes and now I am using only your component.

**Comment by AlexxIT** [comment]
Peterbuga also has a cool component

**Comment by Vladyno** [comment]
When I change your Sonoff domain to Sonoff2, so stop receiving update messages. How do I keep the alert going? Thanks.
