### ISSUE TITLE
RF Bridge Sensor - Generate unique_id

### ISSUE THREAD

**Issue by ThomasGorisse** [AlexxIT/SonoffLAN#210]
In RFBridgeSensor no unique_id is generated. Issuing a none customizable entity in HA UI.
I there any way to use something like {BridgeDeviceId}{sensor_name} as unique_id ?

**Comment by AlexxIT** [comment]
I don't understand about what sensor you speaking?

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
