### ISSUE TITLE
Sonoff RFR3 no longer being detected by Hassio

### ISSUE THREAD

**Issue by boydfields** [AlexxIT/SonoffLAN#211]
Hello,

I had a RFR3 setup and working through Hass.io but as of today the entity was showing as unavailable.  Reboots have achieved nothing.  I deleted the Sonoff device from the entities list in the hope it would be detected as new and reappear.

The device works with Alexa, the light is solid blue.  I've also run a constant ping test to the device to see if it was disconnecting from my wireless network but it never missed a beat.

How best should I proceed?

Are there logs I can export off for you to review?

Would really welcome any support.

My stats are:
Home Assistant 0.113.2
HACS 1.3.0b1
Sonoff LAN 2.30

Kind regards
Boyd

**Comment by AlexxIT** [comment]
Please show config

**Comment by PcOnline2004** [comment]
Same like me. I have couple devices did not show up anymore. All SONOFF POW v2.6.1.

**Comment by AlexxIT** [comment]
Config?

**Comment by AlexxIT** [comment]
Closed because no response
