### ISSUE TITLE
После перезагрузки НА sonoff mini все время со статусом "unavailable"

### ISSUE THREAD

**Issue by conrad66** [AlexxIT/SonoffLAN#212]
НА 0.113.3 + последнее обновление SonoffLAN
Sonoff Mini в режиме DIY с прошивкой 3.х
Ранее сразу залетал в НА после перезагрузки. Сейчас все время unavailable. 
Приходится запускать их программу tool_01DIY85(3.3.0).exe.
Она находит Sonoff и он сразу появляется НА.
Что то можно поправить ?

**Comment by AlexxIT** [comment]
Попробуйте 2.3.1, может поможет.

**Comment by conrad66** [comment]
Поставил обновление... несколько раз перезагружал НА.
Непредсказуемо... может объявится через пару минут, а может через 10минут.
Ну хоть появляться стало. Хотя раньше моментально залетало.

**Comment by AlexxIT** [comment]
Поэтому я рекомендую использовать `mode: auto`, где облачное управление является резервным. Но преимущественно используется локальное.

**Comment by conrad66** [comment]
К сожалению sonoff в трудно доступном месте расположен. Не смогу его из DIY вывести.
Ни чего нельзя более сделать ?

**Comment by AlexxIT** [comment]
К сожалению локальный протокол работает не супер стабильно. Можно добавить ручное обновление состояний, но это не просто и не быстро

**Comment by AlexxIT** [comment]
Вероятно больше нет вопросов по этой issue
