### ISSUE TITLE
Sonoff zigbee button SNZB-01 issue

### ISSUE THREAD

**Issue by mabusdogma** [AlexxIT/SonoffLAN#216]
Hello, I have two zigbee SNZB-01, one is in LAN, connected to Home Assistant directly (with a CC2531) and it works just fine, I control 3 different devices with single click, double click and long lasting click.
Another SNZB-01 is connected on the cloud, trough a sonoff bridge, and HA considers it not a device, just a binary_sensor... so I cant use double click or long lasting click, It's just "on" and "off"... and it takes ages (sometimes 3-4 minutes) since the click to change state.

I see the proble is not the button, when it goes directly on LAN without the bridge/cloud, it works as the first button.

**Comment by Tykwondo1** [comment]
@mabusdogma   
I know that this does not have room for the post to ask this question but, I take this opportunity because I am just looking for how to do the programming of zigbee smart switch.

"it works just fine, I control 3 different devices with single click, double click and long lasting click."

thank you

**Comment by mabusdogma** [comment]
What do you want to do?

I mean, explain a bit what you have (Home assistant, bridge or CC2531) and
what do you want to happen when you press the button.

**Comment by Tykwondo1** [comment]
https://community.home-assistant.io/t/sonoff-zigbee-button-snzb-01-issue-only-in-cloud-mode/217906

I transferred the question to the HA forum, so as not to pollute the Alexx page. thank you and sorry Alexx

**Comment by wishie** [comment]
Proper recognition of the Zigbee button is in the latest release of this custom component. It now supports single, double, long press.

**Comment by AlexxIT** [comment]
`'single', 'double', 'hold'` for SNZB-01 fixed in latest release
