### ISSUE TITLE
не появляется новые устройства при добавлении

### ISSUE THREAD

**Issue by denveronly** [AlexxIT/SonoffLAN#217]
Здравствуйте, вот проблема такая, установил настроил, в первый раз все взлетело все круто
Проблема - при добавлении нового устройства в hassio оно не появляется, ни через 5 ни 10 ни через 10 часов
пробовал и разные mode: auto local cloud
пробовал удалять интеграцию и удалить все обьекты сонофф и установить заново интеграцию
обьекты старые появляются норм, а новый не видно
пробовал это с двумя разными ранее не подключенными сонофф реле 1канальными

что тут может быть

**Comment by denveronly** [comment]
короче сам разобрался!
надо или  писать reload: always что бы обновляло список сонофф устройств
или удалить файл sonoff.json в корневой папке что бы интеграция обновилась

**Comment by AlexxIT** [comment]
В `mode: auto` или `mode: cloud` устройства должны обновляться. `reload: always` нужен только для `mode: local`
