### ISSUE TITLE
CLI and API

### ISSUE THREAD

**Issue by alexandre-mbm** [AlexxIT/SonoffLAN#219]
Like the pysonofflan[r3].
**How to do?**

**Comment by AlexxIT** [comment]
I do not plan to make a console version. Home Assistant has REST API

**Comment by fsalomon** [comment]
:+1: 

I too would like to see a CLI. HASS is completely overblown and ill-suited for my use case. 

What would be the steps required to decouple this from HASS?

**Comment by AlexxIT** [comment]
@fsalomon someone need to write same logic in separate cli project.
