### ISSUE TITLE
Support Smart Light Dimmer Switch

### ISSUE THREAD

**Issue by thib5** [AlexxIT/SonoffLAN#22]
Hi, I just installed the component and it did not work ... in  fact I Just can't find the device in my state page but I have no error in the log ...

May be my device is not compatible ? it a Chinese dimmer ... something like that :
https://fr.aliexpress.com/item/4000160868402.html?spm=a2g0o.productlist.0.0.2bac3e79qv3cSF&s=p

Thanks

**Comment by AlexxIT** [comment]
What version of firmware is in the ewelink application?

**Comment by thib5** [comment]
Version 2.7.0 firmware PSF-BTA-GL

**Comment by AlexxIT** [comment]
Support 2+ in development. I do not have devices of this version.
You can use this component
https://github.com/peterbuga/HASS-sonoff-ewelink
it works with cloud servers and support all firmwares

**Comment by AlexxIT** [comment]
Here #31

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by thib5** [comment]
it kinda work ... I it switch on off witch was not working before ! but no dimmer ... I try to force it like a light but it does not work...

**Comment by AlexxIT** [comment]
@thib5 Write to me on Telegram or Discord (AlexxIT#0816). And share this device to my acc.

**Comment by thib5** [comment]
I added you on discord

**Comment by AlexxIT** [comment]
KING-M4 supported
