### ISSUE TITLE
Non HACS installation method?

### ISSUE THREAD

**Issue by polyvalens** [AlexxIT/SonoffLAN#221]
Requiring HACS for installing SonoffLAN makes things unnecessarily complicated. Why not provide a direct add-on install for Home Assistant? https://developers.home-assistant.io/docs/add-ons/repository/ I am sure it would be greatly appreciated by new or wanabee users (like me).

**Comment by LW-Ho** [comment]
https://github.com/AlexxIT/SonoffLAN#install-with-hacs
here "Or manually copy sonoff folder from latest release to custom_components folder in your config folder."

**Comment by AlexxIT** [comment]
Because addons and custom components are completely different things.
