### ISSUE TITLE
Sensors state after restart

### ISSUE THREAD

**Issue by camui-alexandru** [AlexxIT/SonoffLAN#222]
I have 4 door sensors with on off states connected to sonoff rf bridge. When i restart HA, all The Doors are shown as closed even if they are opened. How can i make them to restore to Last state before restart?

**Comment by sym0nd0** [comment]
You could try setting up an automations using scene create, when the state of the doors changes. Then have another automation setup to run on a startup event of HA to apply the last created scenes. It's not perfect but it's a workaround.

**Comment by camui-alexandru** [comment]
10x but i dont know the data that i have to put on scene create. I m New în this. Coud you explain me? The code?

**Comment by camui-alexandru** [comment]
I figured ouț how to make what You said. If the door changed status, the scene is created. But when i m restarting the HA, the scene is gone and i cant apply it.

**Comment by sym0nd0** [comment]
Sorry, only just seen the notifications. I, wrongly, assumed that scene create would be persistent.

You could try to use a file node, to capture the state change(s), and then use a file in node on restart as the payload for a call service.

I'm point guessing though, you'd probably be better to ask on the HA forum, Discord or the Reddit sub, as people there are way smarter and more knowledgeable with automations than I will ever be.

**Comment by AlexxIT** [comment]
Better to replace the RF-sensors with something modern
