### ISSUE TITLE
How to see 'live' energy usage on Sonoff POW R2?

### ISSUE THREAD

**Issue by Di3mex** [AlexxIT/SonoffLAN#224]
Is it possible to see the live energy usage as in the eWeLink App?
I find this useful especially to see what single devices connected to a powerstrip are using by switching them on and off and comparing the delta.

**Comment by mtosin** [comment]
yes, you can but you need to call the service to get fresh data

**Comment by desigan321** [comment]
Yes, go to Home - Click on + and then add an entity. Select your POW as the device and add the power attribute you want displayed:

![image](https://user-images.githubusercontent.com/61461675/92386854-e01f2980-f114-11ea-9296-20928bf44521.png)

**Comment by alexdj71** [comment]
Hi guys. I am new to HA and trying to learn.
How do i call a service???
Thanks

**Comment by desigan321** [comment]
What are you trying to do? To display live power usage follow my instructions in my previous post above.

**Comment by AlexxIT** [comment]
@alexdj71 There is no need to call the service for live energy. Service is needed for consumption.

**Comment by mtosin** [comment]
> @alexdj71 There is no need to call the service for live energy. Service is needed for consumption.

without calling the service wasn-t able to get fresh data.
in the documentation is also reported to do that. @AlexxIT can you check it?

moreover seems working only if you have Sonoff Cloud active in the HA

**Comment by AlexxIT** [comment]
@mtosin live energy works only with cloud (or lan+cloud) connection.

**Comment by mtosin** [comment]
> @mtosin live energy works only with cloud (or lan+cloud) connection.
> 
> https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.3.1

it's fine but is not mentioned here and check below... is requiring to call the service to pull data...not sure if you implemented that 

Sonoff Pow Power Consumption
For update power consumption of all your Pow devices you can call sonoff.update_consumption service.

The device attributes will display data for the last 100 days. The first element is today's data. It's up to you how often to call updates and what to do with this data later.

**### Remember, without calling the service, there will be no values. Use automation.**

**Comment by AlexxIT** [comment]
I think the question is about live (instant) energy usage - power param.

Consumptions is about the total energy consumption over a period of time.

**Comment by alexdj71** [comment]
@AlexxIT I am facing the following problem with POW R2.
I have 2 devices in HA that only start showing current and power when I open the ewlink app on my cell phone.
For example.
at 8am, everyday I turn on a certain equipment and I wait for the feedback from the power/current status bagde on my home panel to update. unfortunatelly it doesn't so I open the ewlink app on my phone and voilà it starts showing, and only then it records on the graph.

what am I doing wrong?

**Comment by AlexxIT** [comment]
@alexdj71 I this you use `mode: local`

**Comment by alexdj71** [comment]
> @alexdj71 I think you use `mode: local`

Yes I do, should I change it back to cloud? I thought cloud and local was only responsible for switch and toggle directly from HA, so know you tell me it also interferes with the power/amp status?
Is there a way to overcome this limitation?
Thanks for your prompt answer,

**Comment by alexdj71** [comment]
> @alexdj71 I think you use `mode: local`

and this is my yaml

#SonOff
sonoff:
  username: veseaprende.ne@gmail.com
  password: kosher5781
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  mode: local
  reload: always  # update device list every time HA starts
  sensors: [temperature, humidity, power, current, voltage]
  devices: 
    1000bd9199:
      name: Resistencia
      force_update: True
    1000bd95ce:
      name: Ventoinha
      force_update: True

**Comment by alexdj71** [comment]
> @alexdj71 I think you use `mode: local`

And this is my YAML file

#SonOff
sonoff:
  username: "username"
  password: "pass"
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  mode: local
  reload: always  # update device list every time HA starts
  sensors: [temperature, humidity, power, current, voltage]
  devices: 
    1000bd9199:
      name: Resistencia
      force_update: True
    1000bd95ce:
      name: Ventoinha
      force_update: True

**Comment by AlexxIT** [comment]
You need `mode: auto`

**Comment by mohssinDR** [comment]
hey @AlexxIT i did several tries over the past 2 weeks, but i didn't figured it out yet, my pow r2 didn't send a consumption attribute like so : 
![image](https://user-images.githubusercontent.com/32648814/104947125-8cbec100-59bb-11eb-9fae-ee0fcaad84d0.png)
thank you for this amazing hacs integration 👍

**Comment by AlexxIT** [comment]
@mohssinDR you need to get consumption manually by calling service as said in readme.

**Comment by mohssinDR** [comment]
sorry for my misunderstanding, im newbie here, what do you mean by calling a service manually? isn't that what i already did when i add (service: sonoff.update_consumption) to my yaml config ?

**Comment by AlexxIT** [comment]
@mohssinDR no. Your YAML wrong
