### ISSUE TITLE
Sonoff Mini DIY mode with firmware 3.5, 3.6 

### ISSUE THREAD

**Issue by sergeysaley** [AlexxIT/SonoffLAN#229]
Hi!
Sonoff mini in DIY mode with firmware 3.5 and 3.6 do not detected by Home Assistant.
Is there any hope that these devices will be included in the list of tested devices?
Thank You!

**Comment by desigan321** [comment]
Check this:

https://github.com/itead/Sonoff_Devices_DIY_Tools/issues/75#issuecomment-609449006

**Comment by sergeysaley** [comment]
Thank You!
