### ISSUE TITLE
Sonoff Mini State not changing in HA

### ISSUE THREAD

**Issue by cmjennnings21** [AlexxIT/SonoffLAN#23]
I've installed SonoffLan and connected a Sonoff Mini to Home Assistant, however the state can't be changed in HA either in developer or in Lovelace Entity card. I can however change the state when I control using Node red, so the addon is communication to the device, Is this a know issue, I can't see anything in the issues log?

**Comment by AlexxIT** [comment]
Some problems with HA. Is there an error in the logs?

**Comment by cmjennnings21** [comment]
So nothing in the log but I noticed that the ha switch would switch the device on, but the switch was acting as a momontery switch and I couldn't switch off from ha. Found a fix, I updated sonoff mini to firmware 3.3, deleted the json file from ha, and restarted the ha server. It's all working as it should now. Thanks

**Comment by AlexxIT** [comment]
Sonoff Mini has a very buggy default firmware.
