### ISSUE TITLE
Sonoff RF Receive not work if use script on button

### ISSUE THREAD

**Issue by devison1932** [AlexxIT/SonoffLAN#230]
When setting up an RF opening script.
When the turn on or turn off button is pressed.
Make the automation that assigned RF Receive to work all.

Causing automation problems

[Pic 1](https://ibb.co/0FYBVGG)
[Pic 2](https://ibb.co/XY1G848)
[Pic 3](https://ibb.co/h8qvxQG)

Sorry, I'm not good at English.
Thank all.

**Comment by AlexxIT** [comment]
Your pictures no longer open. Is problem still actual?

**Comment by AlexxIT** [comment]
Closed because no response
