### ISSUE TITLE
Integration doesn't seem install properly

### ISSUE THREAD

**Issue by stevewrightnz** [AlexxIT/SonoffLAN#235]
**Background**
Home Assistant installed on Ubuntu 18.04 in Docker 19.03.12, build 48a66213fe using:-
`sudo curl -sL "https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh" | bash -s`
SonoffLAN installed by copying files from the zip file here:-
`https://github.com/AlexxIT/SonoffLAN/archive/v2.3.1.zip` to here:- `/usr/share/hassio/homeassistant/custom_components`

NB: If it's copied to `/usr/share/hassio/config/custom_components` then nothing loads.

configuration.yaml looks like:-
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Sonoff Configuration
sonoff:

  username: <username>
  password: <password>
  reload: always
  debug: true
```

Reload to be commented out and debug set to false when I get everything working properly.

Sonoff devices are all there but end up under "Entities".

**Issue.**  
There is no "Integration" and no "Devices" created which makes automation difficult.

NB:  Its possible that I'm totally missing something :)

Steve

**Comment by wishie** [comment]
You have it inside custom_components/sonoff/ yes?

**Comment by stevewrightnz** [comment]
Yes,  homeassistant/custom_components/sonoff

Sent from my mobile device.

________________________________

**Comment by AlexxIT** [comment]
SonoffLAN support only entities. No integration and devices for now.
