### ISSUE TITLE
Sonoff26 can't access homeassistant

### ISSUE THREAD

**Issue by js-yangjiabao** [AlexxIT/SonoffLAN#238]
Hello, Mr. AlexxIT!
I'm a new homeassistant from China. I have a smart plug with a model of sonoff26. I want to connect it to the homeassistant. I copied the latest version of the sonoff folder to the custom_components folder according to your steps, and completed the configuration of the information to be configured in configuration.yaml However, I made an unexpected error. I didn't know what the problem was when I consulted the materials. I didn't know the concept of creating integration very clearly, and I consulted a lot of materials. However, it was a bit difficult for me who was not good at English, but I wanted to be a developer of homeassistant.

The configuration configuration file is as follows:
```
sonoff:
  username: .....
  password: ....
  #reload: always
  #default_class: switch
  devices: 
    1000abcdef:
      apikey: ... 
```
Errors are reported as follows:
```
2020-09-17 15:51:40 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration sonoff - received exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/setup.py", line 68, in async_setup_component
    return await task  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/setup.py", line 137, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/setup.py", line 322, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/requirements.py", line 77, in async_get_integration_with_requirements
    await async_process_requirements(
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/requirements.py", line 124, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/local/lib/python3.8/dist-packages/homeassistant/util/package.py", line 54, in is_installed
    return version(req.project_name) in req
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2978, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
Looking forward to your reply, I am very grateful！

**Comment by wishie** [comment]
Is the device setup and working in the eWeLink application?

If so, the only lines you need to really add to the configuration.yaml are (and yes, spacing is important):

```
sonoff:
  username: your@email.com
  password: yourpassword
```

**Comment by js-yangjiabao** [comment]
Thank you for your reply, but I still can't succeed.
Problem description:
1.My mobile app can control the switch of the device and take effect. There is no. sonoff.json in the same directory of my configuration
2.This is my sonoff configuration information:
sonoff:
  username: +86159XXXXXXXX
  password: XXXXXXXX
  reload: always
  default_class: switch
  devices: 
    1000b11cfa:
      devicekey: f439bd2d-d8e4-4027-87f2-XXXXXXXXXXXX
      device_class: switch 
There is nothing wrong with the format.
3.I downloaded the latest /custom_components/sonoff from Mr. AlexxIT and put it in my custom_components folder, and now I report a new error:
2020-09-21 09:18:21 ERROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Unable to import component: cannot import name 'get_random_bytes' from 'Crypto.Random' (/usr/local/lib/python3.8/dist-packages/Crypto/Random/__init__.py)
I tried to find the information, but I still couldn't solve it.I didn't download the Crypto package, but all py files in it are empty. I don't know what to do.

**Comment by AlexxIT** [comment]
@js-yangjiabao How is HA installed? venv?

**Comment by js-yangjiabao** [comment]
@AlexxIT With command python3 -m pip install homeassistant in ubuntu

**Comment by js-yangjiabao** [comment]
@AlexxIT 
I found that there are Crypto and pycryptodome-3.9.8.dist-info in the /.homeassistant/deps/lib/ ... path, which seems to work. The py files in Crypto and pycryptodome-3.9.8.egg-info under my usr/local/lib ... path are empty.
Therefore, I wonder if I can call Crypto under /.homeassistant instead of usr/local/lib when running [homeassistant.setup]. If so, what should I do?

**Comment by AlexxIT** [comment]
pycryptodome from deps should be used with priority. You have a difficult setup. The easiest way is to use hassio. Everything always works well there. As a last resort venv.

**Comment by js-yangjiabao** [comment]
I have two questions:
First, I have two identical smart plugs. I want to configure them to HA. The first one has been successfully configured with the user name and password. Since the second one also wants to use the same user name and password as the first one, how can I modify my configuration file?
Second question: I want to realize that entering the username password in the HA front-end interface can achieve the same result as the configuration in the configuration file. Is this OK? How to achieve it? My configuration of the first smart plug is as follows. There may be some minor problems, but it succeeded.
Settings in the configuration file:
sonoff:
  username: 'input_text.texta'
  password: 'input_text.textb'
  default_class: switch
Settings in package:
input_text:
  texta:
    name: username
  textb:
    name: password
    mode: password 
Then, in the front-end interface, add information that the user can input: user name and password, etc. It succeeded, but I don't know what to do with the second plug.
Looking forward to your reply, thank you very much.

**Comment by js-yangjiabao** [comment]
@AlexxIT 
 I have two questions:
First, I have two identical smart plugs. I want to configure them to HA. The first one has been successfully configured with the user name and password. Since the second one also wants to use the same user name and password as the first one, how can I modify my configuration file?
Second question: I want to realize that entering the username password in the HA front-end interface can achieve the same result as the configuration in the configuration file. Is this OK? How to achieve it? My configuration of the first smart plug is as follows. There may be some minor problems, but it succeeded.
Settings in the configuration file:
sonoff:
username: 'input_text.texta'
password: 'input_text.textb'
default_class: switch
Settings in package:
input_text:
texta:
name: username
textb:
name: password
mode: password
Then, in the front-end interface, add information that the user can input: user name and password, etc. It succeeded, but I don't know what to do with the second plug.
Looking forward to your reply, thank you very much.

**Comment by AlexxIT** [comment]
Config with GUI in development
