### ISSUE TITLE
Cannot install SonoffLAN

### ISSUE THREAD

**Issue by AndyZaa** [AlexxIT/SonoffLAN#244]
Hi,
I'm hoping to install SonoffLAN so I can compare my Tasmota flashed Sonoff switches with my unflashed. However, I cannot get it to install and don't know if I'm doing something wrong or if it is my particular setup.
I'm running on an Intel NUC.
Home Assistant 0.115.3 (from Configuration/Info)
Home Assistant version: 3.5.0
Operating system: Ubuntu 20.04.1 LTS
Docker version: 19.03.13

When I add the repository in HACS it doesn't look like it installs properly because I get the screen shown below with a couple of "unknowns".

I've also tried to install it manually by placing the files from the zip into:
/home/user/docker/hassio/homeassistant/custom_components/sonoff

No matter what I try I don't see SonoffLAN or any of my unflashed modules showing up anywhere. Does anyone have some kind advice? Thanks!
 
![Add_Repository 1](https://user-images.githubusercontent.com/55149357/94323084-79966a00-ff62-11ea-918c-cff63a88e562.png)

**Comment by AlexxIT** [comment]
You install hassio add-on, not HACS custom content.

**Comment by gregf888** [comment]
Like this in my installation:

![image](https://user-images.githubusercontent.com/71629711/94330323-e6fbd680-0006-11eb-8b70-e5e73104fab2.png)

**Comment by AndyZaa** [comment]
Sorry Alex, I must be thick. I'm following the section in the README.md titled Install with HACS. 
I more correctly should have said I'm adding the repository in the Add-on store (not HACS).

In Home Assistant I'm going to Supervisor / Add-on store. Then I click on the three vertical dots and then Repositories. There in Manage add-on repositories I click on Add repository. I enter https://github.com/AlexxIT/SonoffLAN then ADD. That screen will not take AlexxIT/SonoffLAN because it throws an error "expected a URL @ data['addons_repositories'][2]. Got 'AlexxIT/SonoffLAN'".

But I've also tried the "manually copy sonoff folder from latest release to custom_components folder in your config folder" method (as below) and get nothing that way either.

Appreciate your help and comments already!
 
![Screenshot from 2020-09-26 01-14-22](https://user-images.githubusercontent.com/55149357/94330973-1d9a0880-ff97-11ea-899f-f7145707193f.png)

**Comment by jus101** [comment]
@AndyZaa having the same trouble. From what I can tell you need to install [HACS](https://hacs.xyz/) into your Home Assistant installation, then you can install this add on via HACS.

**Comment by AndyZaa** [comment]
Yep, that's what I have been trying to do. I installed HACS quite a while ago, and now I've just been trying to add SonoffLAN through the Add a custom repository feature. I haven't been able to figure out what version of HACS I have, or if HACS updates itself. But the rest of HACS works fine.

**Comment by AndyZaa** [comment]
Turned out that my HACS installation must have been outdated - I reinstalled HACS and then was able to install SonoffLAN.
