### ISSUE TITLE
Sonoff TH16 update intervals (newbie - sorry)

### ISSUE THREAD

**Issue by dcassar73** [AlexxIT/SonoffLAN#245]
Hey everyone,

Just installed everything and things seem to be going good, the only problem I think I am having is the update for my TH16 temperature probe.  The Jacuzzi temp is saying "3 hours ago as per below"

![image](https://user-images.githubusercontent.com/71876179/94335961-991fa800-ffdf-11ea-8f61-c0973233155b.png)

If I wrote everything right below it should be checking every 2 m - so why am I getting updates hours apart?

sonoff:
  username: dcass
  password: longlive AlexxIT
  force_update: [temperature, humidity, power, current, voltage]
  scan_interval: '00:02:00'
  sensors: [temperature, humidity, power, current, voltage]

**Comment by AlexxIT** [comment]
HA shows the time when the value changed. It can be requested every 2 minutes, but it does not change
