### ISSUE TITLE
Can't set Micro USB to device_class: light

### ISSUE THREAD

**Issue by DanielStoelzner** [AlexxIT/SonoffLAN#246]
The Micro USB works just fine with its default device_class. 
When I change the device_class to light via 
```
    1000d4c2a4:
      device_class: light
```
a new entity, light.sonoff_1000d4c2a4, appears but is shown as unavailable. Furthermore the original entity switch.sonoff_1000d4c2a4 also becomes unavailable.

The debug logs in both cases look pretty much the same. 
I noticed however that the micro differs quite significantly from other devices, such as the S26

S26:
`2020-09-26 21:18:43  DEBUG    sonoff_local  100071edd3 <= Local1 | {'switch': 'off', 'startup': 'stay', 'pulse': 'off', 'sledOnline': 'on', 'pulseWidth': 500, 'rssi': -54, 'ssid': 'Daniel', 'bssid': '...'} | 114`

Micro USB:
`2020-09-26 21:18:43  DEBUG    sonoff_local  1000d4c2a4 <= Local1 | {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}], 'configure': [{'startup': 'stay', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 2000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '...', 'rssi': -46} | 21`

And then there's this in the Home Assistant log:
```
 Error while setting up sonoff platform for light 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 201, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 310, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 481, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/sonoff/switch.py", line 44, in async_added_to_hass
    device = self._init()
  File "/config/custom_components/sonoff/sonoff_main.py", line 235, in _init
    self._update_handler(state, attrs)
  File "/config/custom_components/sonoff/switch.py", line 51, in _update_handler
    self._is_on = any(self._is_on_list(state))
  File "/config/custom_components/sonoff/sonoff_main.py", line 252, in _is_on_list
    return [state['switch'] == 'on']
KeyError: 'switch'
```

**Comment by wishie** [comment]
I saw somewhere that the MICRO shows up as 4 switches in things like Tasmota too.. perhaps its an issue related to that? Your debug log for the MICRO shows outlets 0-3

**Comment by AlexxIT** [comment]
Inside micro firmware 4 channel relay. So `device_class` should set for multi devices

```
device_class: [light]
```

**Comment by DanielStoelzner** [comment]
> 
> 
> Inside Micro firmware 4ch relay. So `device_class` should set for multi-channel devices:
> 
> ```
> device_class: [light]
> ```

That worked. It's now behaving as expected. Thank you!
