### ISSUE TITLE
Momentary switch - problem

### ISSUE THREAD

**Issue by stefancvetkovic** [AlexxIT/SonoffLAN#248]
Hello,
I implemented this LAN solution to my HA, I can see entity, but I have a problem when I add momentary switch to my sonoff device. It's ON while Im hoilding the switch pressed, when I release it the switch goes to off.
Is there any option to change this to when I push and release switch then to turn on/off the lights?
In tasmota I was able to do this through settings.

Thanks

**Comment by AlexxIT** [comment]
You want to hold swith in HA GUI? As far as I know, HA can't do that.

**Comment by stefancvetkovic** [comment]
No, its not HA switch, it's a hardware switch connected with wires to sonoff device. Like this: 
![image](https://user-images.githubusercontent.com/13699747/94425095-9c579700-018b-11eb-804d-ccda59157024.png)

**Comment by dmutpuul** [comment]
Maybe you have to do some automation that toggle lights every time when system receive message that switch goes ON.

**Comment by AlexxIT** [comment]
Which sonoff do you use? Sonoff mini should work fine.

**Comment by dmutpuul** [comment]
@stefancvetkovic from [https://www.itead.cc/sonoff-mini.html](https://www.itead.cc/sonoff-mini.html ) "" Support the rocker light switch to control devices (self-return switch not included). ""   So momentary switch is not compatible with original firmware . Maybe that can be adjusted in tasmota, but i am using original sonoff devices and rocker switch. Every time when i toggle switch then toggles current state of sonoff mini. I mean that switch can be turned off but light turned on))
