### ISSUE TITLE
No Devices listed in the UI

### ISSUE THREAD

**Issue by grixtil** [AlexxIT/SonoffLAN#25]
Just installed the package with HACS, got a .sonoff.json file with 74kb of data in it, but nothing shows up as devices in the UI of the Home Assistant.
Got a mix of Sonoff devices, EU wall switches, 4 Channel, 4 Channel Pro, etc.

**Comment by AlexxIT** [comment]
Problems with multicast. Two routers, docker with port forwarding, virtual machine, linux firewall, linux net driver, etc.

**Comment by grixtil** [comment]
> Problems with multicast. Two routers, docker with port forwarding, virtual machine, linux firewall, linux net driver, etc.

Yeah, have WiFi repeaters, and using HSS through Virtual Machine on MacOS.. any pointers on the way around this issue and how to resolve it please?

**Comment by AlexxIT** [comment]
I don't know if repeaters block multicast. I heard about problems with multicast in VirtualBox.

**Comment by jeffl78** [comment]
So this won't work with docker and port forwarding?  I there something extra I can do to get it to work with docker?

**Comment by AlexxIT** [comment]
@jeffl78 don't work with docker port forwarding! You need to use **docker network host**

**Comment by orionrst** [comment]
> Just installed the package with HACS, got a .sonoff.json file with 74kb of data in it, but nothing shows up as devices in the UI of the Home Assistant.
> Got a mix of Sonoff devices, EU wall switches, 4 Channel, 4 Channel Pro, etc.

you managed to find a solution to show them up in the device list?

**Comment by djneoo** [comment]
I've just run into the same issue. My docker uses host network mode already. Json is there but sensors are not listed. Any idea?
@jeffl78 have you found a solution?

**Comment by AlexxIT** [comment]
@djneoo common problems described here
https://github.com/AlexxIT/SonoffLAN#common-problems

**Comment by djneoo** [comment]
@AlexxIT I'll check that out, especially potential multicast issue - thanks!

**Comment by djneoo** [comment]
Just to make others aware - the issue was related to multicast. Make sure your sonoff devices are in the same subnet as the machine/container running Hassio. Then it works as a charm.
@AlexxIT awesome job!
