### ISSUE TITLE
Zigbee Door sensor unavailable for 45 minutes on cycle

### ISSUE THREAD

**Issue by mdeakin99** [AlexxIT/SonoffLAN#250]
Hi

I am using your integration in Cloud mode and I see the Door Sensor goes unavailable for 45 minutes and then comes back online.

Wondering if it’s a ewelink thing, bridge thing of an integration thing.

**Comment by wishie** [comment]
I had a few issues with a Zigbee door sensor that kept going 'unavailable'. The first problem was it was simply 'too far' from my hub (solved by installing a BASICZBR3 in between the hub and the door sensor. The second issue is the ZB Door Sensor will 'sleep' if not opened frequently enough, and HA will see it as 'unavailable'.

**Comment by mdeakin99** [comment]
I was wondering if it’s a faulty unit too.  I have purchased an innr sp220 plug to see if that fixes it.

Mark

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by patrickgmail** [comment]
Hi
Check the battery support of your door sensor. On the last 4 that I received, I had the same problem and worth for the ones I sticked with horizontal position.
Just release the battery, push on the big back plate (wich is the negative plug) for to make that it press a bit more the battery when you put it again. Then put back the battery in the sensor and let see if your problem disapears.

**Comment by AlexxIT** [comment]
This problem is probably related to the ewelink cloud
