### ISSUE TITLE
Can't put Sonoff S26 in LAN only / DIY mode

### ISSUE THREAD

**Issue by rousveiga** [AlexxIT/SonoffLAN#254]
Hello, this is more of a device-related question, I'm asking because I didn't get a satisfactory response from the Itead support forums. Please delete if or close if not allowed. 

I have a Sonoff S26 that I'd like to put in LAN only / DIY mode to use with this integration; these are the steps I've followed:

1. Press button until LED starts to blink in Compatible Pairing mode (two short blinks and one long).
2. Release button, then press again until it blinks in Soft AP mode (continuous short blinks).
3. Soft AP appears and I connect to it on my phone (Samsung S8+ with Android 9).
4. Once connected, access http://10.10.7.1 on Chrome version 85.0.4183.101.
5. Chrome displays error page with either ERR_CONNECTION_RESET or ERR_SOCKET_NOT_CONNECTED. Sometimes the "loading" bar hangs indefinitely.

Has anyone else encountered this error? Am I doing something wrong?
Thank you for your time and help.

**Comment by AlexxIT** [comment]
Integration works with any ewelink devices. They only need to be added to the ewelink app. If the device is on firmware 3+ it will work in local mode.

**Comment by rousveiga** [comment]
So you absolutely need to use the ewelink app to configure the Wi-Fi, right? I thought it'd display some kind of web portal while in soft AP mode, where you could configure the Wi-Fi and perhaps other settings (the classic ESP8266 Wi-Fi Manager; akin to how the Shelly devices work). I found some documentation and forum posts supporting this, but the web doesn't load for me.

Firmware of my S26 is 3.5.0. (Forgot to add that in the original question, sorry.)

**Comment by AlexxIT** [comment]
Sonoff devices do not have a friendly wifi setup page. S26 does not have DIY mode for LAN only. But all devices on firmware 3+ can work using the local protocol and this component supports it.

**Comment by rousveiga** [comment]
Oh, I see. So you really can't get rid of the app or the Sonoff cloud, which was my goal. Thank you for your time and help!
