### ISSUE TITLE
fan02 no speed choose

### ISSUE THREAD

**Issue by david78455** [AlexxIT/SonoffLAN#257]
Hi
I have fan02 installed
I install the component, I fount the name for Fan and the name for light.
but I cant fine name for the speed of the fan 
for example 

switch.sonoff_10005b26e9_1 is light 
switch.sonoff_10005b26e9_2 is Fan
switch.sonoff_10005b26e9_3 is medium speed of the fan
switch.sonoff_10005b26e9_4 is fast speed
but with your component I only see   no: 1, 2  cant see no 3,4
please help
Regards
David

**Comment by AlexxIT** [comment]
Show your entities

**Comment by david78455** [comment]
Hi Thanks
sorry for the late response
here are my entities
light.sonoff_10005b26e9_1   this one works it is the light
fan.sonoff_10005b26e9         this one works it is the fan

But I can't find the speed entities of the fan
van you help ?  the fan is Fan02

Regards
David

**Comment by AlexxIT** [comment]
Oh. I mean show config

**Comment by david78455** [comment]
sonoff:
  username: !secret ewelink_username 
  password: !secret ewelink_password
  scan_interval: 60 
  grace_period: 99999
  api_region: 'as' 
  entity_prefix: True 
  debug: False 
  devices:
    10005b26e9_1:
      device_class: fan
      name: Sonoff fan02

**Comment by david78455** [comment]
please answer

**Comment by AlexxIT** [comment]
Please show this fan in `.sonoff.json` file. It should be in your config folder

**Comment by david78455** [comment]
```
...
"100066cd9e": {
    "settings": {
      "opsNotify": 0,
      "opsHistory": 1,
      "alarmNotify": 1
    },
    "family": {
      "id": "5ed544d3f2daaa0008e9f740",
      "index": 3
    },
    "group": "",
    "online": false,
    "groups": [],
    "devGroups": [],
    "_id": "5ca616fce09a08b990da467f",
    "name": "Temperature Sensor ",
    "type": "10",
    "deviceid": "100066cd9e",
    "apikey": "bc216930-8b84-4365-ba08-20bb78daa84e",
    "extra": {
      "extra": {
        "uiid": 15,
        "description": "WO1882004",
        "brandId": "58e5f344baeb368720e25469",
        "apmac": "d0:27:00:cd:98:8d",
        "mac": "d0:27:00:cd:98:8c",
        "ui": "恒温恒湿改装件",
        "modelInfo": "5a2e1ad90cf772f92c342ef3",
        "model": "PSA-BHA-GL",
        "manufacturer": "深圳松诺技术有限公司",
        "staMac": "80:7D:3A:32:98:89",
        "chipid": "00329889"
      },
      "_id": "5bf3b76e7e41f93e431bcfe0"
    },
    "params": {
      "deviceType": "normal",
      "init": 1,
      "currentTemperature": "24.9",
      "staMac": "80:7D:3A:32:98:89",
      "rssi": -35,
      "targets": [
        {
          "targetHigh": "40",
          "reaction": {
            "switch": "on"
          }
        },
        {
          "targetLow": "30",
          "reaction": {
            "switch": "off"
          }
        }
      ],
      "switch": "off",
      "bindInfos": {
        "gaction": [
          "bc216930-8b84-4365-ba08-20bb78daa84e_ewelink-google-home-v1"
        ]
      },
      "mainSwitch": "on",
      "startup": "off",
      "currentHumidity": "unavailable",
      "sensorType": "DS18B20",
      "fwVersion": "3.4.0",
      "partnerApikey": "22a273b7-a741-439e-b5e4-102c4d7e5e2f",
      "version": 8,
      "sledOnline": "on",
      "pulse": "off",
      "pulseWidth": 500
    },
    "createdAt": "2019-04-04T14:38:52.365Z",
    "__v": 0,
    "onlineTime": "2020-06-12T08:38:44.965Z",
    "ip": "5.102.222.76",
    "location": "",
    "offlineTime": "2020-06-12T16:16:25.245Z",
    "deviceStatus": "",
    "sharedBy": {
      "email": "david78455@walla.co.il",
      "apikey": "bc216930-8b84-4365-ba08-20bb78daa84e",
      "permit": 15,
      "shareTime": 1571392057221
    },
    "devicekey": "5716e628-d0b6-44bf-a9fb-019c84ba2e5c",
    "deviceUrl": "https://as-api.coolkit.cc/api/detail/5a2e1ad90cf772f92c342ef3_en.html",
    "brandName": "Sonoff",
    "showBrand": true,
    "brandLogoUrl": "https://as-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png",
    "productModel": "TH16",
    "devConfig": {},
    "uiid": 15
  },
...
```

**Comment by AlexxIT** [comment]
All looks fine. You should have fan with speed control. Are you sure use using my integration? Because config not from my integration.

**Comment by david78455** [comment]
Hi,
of course I am using your great integration. I was using Peterbuga integration till he stop to support it.
It is very frustrating I can see only **fan.sonoff_10005b26e9**   witch is the fan, and  **light.sonoff_10005b26e9_1** which is the light, but no other switches for the speed/
Please help 
Regards
David

**Comment by AlexxIT** [comment]
Speed should be in the fan

**Comment by david78455** [comment]
Hi Alex,
Thanks but I really did not understand your answer
Let me elaborate please .  with **Peterbuga** integration, I was able to control the fan speed also from the HA thanks to the fact that I saw four different switches:
**switch.sonoff_10005b26e9_1 is light
switch.sonoff_10005b26e9_2 is Fan
switch.sonoff_10005b26e9_3 is medium speed of the fan
switch.sonoff_10005b26e9_4 is fast speed**
with your Integration I can only turn the fan on and off and in order to control the fan speed to, I must do it from the Ewelink app/ that because I can see only 2 switches from the HA

**light.sonoff_10005b26e9_1  -  light
fan.sonoff_10005b26e9           -  fan on/off**

Please help
Regards
David

**Comment by AlexxIT** [comment]
![image](https://user-images.githubusercontent.com/511909/123548280-cf57a700-d76c-11eb-8682-f75ef7b949e7.png)

**Comment by david78455** [comment]
Thanks 💯 at last I understood :) working !!
