### ISSUE TITLE
TH16 temperature and humidity status unavailable 

### ISSUE THREAD

**Issue by mstumpel** [AlexxIT/SonoffLAN#258]
Hi, I integrated sonoff and initially everything worked fine for the TH16 device. After a restart of HA the staus of the two sensors are unavailble. The switch part however is working just fine. I can turn it on and off in the HA overview. So the connection to the device seems to be okay. In ewLink the state of the sensors indicates the correct values for temp and humidity so there is no HW issue.

Any idea what can be wrong?

Regards

**Comment by AlexxIT** [comment]
Please enable debug mode (readme) and send logs

**Comment by mstumpel** [comment]
Issue is solved. thx
