### ISSUE TITLE
Use without Home assistant from command line

### ISSUE THREAD

**Issue by leopucci** [AlexxIT/SonoffLAN#259]
Is there some way to use it from command line?

Home assistant is a heavy sw if you think embedded. 

I can´t use with openwrt for instance. 

But if it is a shell command it can spread over several devices, even on linux machines, windows, etc. 

Is this possible? 

Something like

sonofflan -i eth0 -d DeviceID -c ON

Something more command line mode. It would spread heavly on several systems. 
If it is not possible, do you know some similar software developed for command line?

Thanks for your help
Pucci

**Comment by leopucci** [comment]
Found something similar, but it says that you have to block internet access to use it
https://pysonofflan.readthedocs.io/en/latest/readme.html

**Comment by AlexxIT** [comment]
I don't plan to add cli. Check this project:
https://github.com/mattsaxon/pysonofflan
