### ISSUE TITLE
Support King Art - King Q4 Cover

### ISSUE THREAD

**Issue by sergioa77** [AlexxIT/SonoffLAN#26]
Hi, first, thanks for your work on this.
Do your component have compatibility with the Kingart king-q4 blinds controller? 
I'm using peterbuga's component but althoug I can open and close the blinds, it is not possible to have control of the percentage.
Thanks!

**Comment by AlexxIT** [comment]
What version of firmware in ewelink app?

**Comment by sergioa77** [comment]
> What version of firmware in ewelink app?

Versio 2.7.0.... Firmware PSF-BTA-GL

**Comment by AlexxIT** [comment]
Here #31

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by sergioa77** [comment]
Hi,
first, thanks for your awesome work on the Sonof stuff.
The King Art - King Q4 is still detected as a normal switch in HA supporting only power off or on.
This is the entity:
manufacturer: KingArt
model: KING-Q4
sw_version: PSF-BTA-GL v2.7.0
connection: cloud
rssi: -69
friendly_name: Persiana Terraza
supported_features: 0
icon: 'mdi:window-shutter'

No up - stop - down buttons neither slider.... :( 

Am I missing something in the setup?

Thanks,

**Comment by AlexxIT** [comment]
@sergioa77 you can write me in Discord or Telegram.
And share devices to my acc. I need it for debugging.

**Comment by sergioa77** [comment]
Thanks for you hard work @AlexxIT . We have now available this King Q4 Cover device fully working with slider and up, stop, down buttons. Magic!

**Comment by AlexxIT** [comment]
Done

![download-3](https://user-images.githubusercontent.com/511909/81735229-672cff80-949d-11ea-9a47-db0df8d6a0be.png)

**Comment by riorao** [comment]
Здравствуйте!
Дайте пример конфигурации.

**Comment by AlexxIT** [comment]
@riorao https://github.com/AlexxIT/SonoffLAN#config-examples

**Comment by Olivaref** [comment]
Hi @AlexxIT,
I've installed the last release 3.0.5 and the king art cover is not working properly. It worked ok with 2.4.7. It is KING-Q4 Fw: 3.4.3
Is there something to change / configure or is it something to be fixed?

**Comment by Fornball** [comment]
Is it possible to use this cover over LAN only? Right now it just goes offline when switching the integration to local mode
