### ISSUE TITLE
DW2 not being detected from cloud

### ISSUE THREAD

**Issue by carlosCastro99** [AlexxIT/SonoffLAN#260]
Hi have 6 devices, but integration only detects 5. DW2 not being detected from cloud

my config:
sonoff:
  username: xxx
  password: xxx
  force_update: [temperature, power]
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  debug: True

(I have POW, POWr2, TH)

**Comment by AlexxIT** [comment]
Show debug logs

**Comment by AlexxIT** [comment]
Closed because no response
