### ISSUE TITLE
About APPID

### ISSUE THREAD

**Issue by coolkit-carl** [AlexxIT/SonoffLAN#262]
Hello,

I'm the technical staff of CoolKit eWeLink, how did you get our APPID and APP Secret?

**Comment by Gferretta** [comment]
it is a shame that you make this inquiry as a coolkit staff.  
Better worry about providing better products as my 4CH Pro R2 had problems after a firmware update and no one gave me an answer.  
Go ahead Alexx 👏👏

**Comment by coolkit-carl** [comment]
> it is a shame that you make this inquiry as a coolkit staff.
> Better worry about providing better products as my 4CH Pro R2 had problems after a firmware update and no one gave me an answer.
> Go ahead Alexx 👏👏

Regarding this issue, please contact Sonoff customer service staff directly

URL: https://itead.freshdesk.com/support/home

Email: support@itead.cc

Best regards.

**Comment by cfgroenewald** [comment]
Hi AlexIT

I am totally new to the HA environment. How do I use a Sonoff PIR sensor
and botton?

Cat seem to get it right?

Knd regards

**Comment by AlexxIT** [comment]
@coolkit-carl Hi. Somewhere in similar projects.
