### ISSUE TITLE
Whether it is possible for the user to input information at the front end to replace the configuration such as user name and password in the configuration file.

### ISSUE THREAD

**Issue by js-yangjiabao** [AlexxIT/SonoffLAN#264]
There is such a demand because, for example, to produce these sonoff26 plugs and sell them to customers, not all customers want to enter the configuration file and add information such as user name and password. Therefore, an input box can be added at the front end so that customers can set this information at the front end to achieve the effect of configuration file. This is just a guess. Can it be realized?

**Comment by AlexxIT** [comment]
Users can set user/pass in `secrets.yaml` file
