### ISSUE TITLE
Sonoff SNZB-03 Motion Sensor needs Zigbee Bridge?

### ISSUE THREAD

**Issue by MaestroMet** [AlexxIT/SonoffLAN#265]
Hi, I'm interested in buying the Motion Sensor SNZB-03 and integrate in in HA. I've seen under tested devices that it says "Tested ZigBee (only Cloud)". Does this mean that i can integrate it in HA only via the SONOFF ZBBridge - Smart Zigbee Bridge?
Thanks.

**Comment by heikkikitt** [comment]
Yes it needs a bridge. I would suggest to buy a zigbee transmitter like Conbee II (I have that, works with SNZB-03 and other sonoff zigbee devices) or similar to give your HA zigbee capability and integrate devices directly.

**Comment by AlexxIT** [comment]
You need gateway or stick to work with zigbee devices
https://www.itead.cc/cc2531-usb-dongle.html
