### ISSUE TITLE
Installed HACS but custom repositories AlexxIT/SonoffLAN doesn't show

### ISSUE THREAD

**Issue by Plaatjesdraaier** [AlexxIT/SonoffLAN#266]
Unfortunately the AlexxIT/SonoffLAN is not present in de HACS integration section.
Is there any other way to install this ?

arch | x86_64
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.72
python_version | 3.8.5
supervisor | 2020.10.0
timezone | Europe/Brussels
version | 0.116.4
virtualenv | false

HACS v 1.6.0 (709 repositories)

**Comment by heikkikitt** [comment]
You have to add a custom repository by the name AlexxIT/SonoffLAN as shown here: https://github.com/AlexxIT/SonoffLAN#install-with-hacs

**Comment by Plaatjesdraaier** [comment]
The gif differs from my setup;
![Hacs custom repository 2](https://user-images.githubusercontent.com/25374760/97609485-f7dba580-1a13-11eb-80d9-940142c94fd6.png)
![Hacs custom repository](https://user-images.githubusercontent.com/25374760/97609490-f90cd280-1a13-11eb-8db3-b8361237bf0a.png)

Hacs updated today v1.6.1

**Comment by Plaatjesdraaier** [comment]
I found it.... I had to select the three dots in the upper right corner, choose 'Custom Repositaries'and then add the AlexxIT/SonoffLAN repositary! Thanks!
