### ISSUE TITLE
No devices showing 

### ISSUE THREAD

**Issue by aidan1010** [AlexxIT/SonoffLAN#275]
Installed as per DrZzs's video, but not devices are showing up, any ideas to fix this?

**Comment by AlexxIT** [comment]
Devices are not supported

**Comment by aidan1010** [comment]
Okay, I'm confused are Sonoff Basic2 switches not supported?
They showed up initially but then I deleted an entititie because 2 showed up and now none show up after rebooting Home Assistant?

**Comment by AlexxIT** [comment]
Entities supported. And should show after reboot.

**Comment by aidan1010** [comment]
Unfortunately nothing showing up after reboot. is Sonoff basic2 firmware 3.5 supported?

**Comment by AlexxIT** [comment]
Show your config and check logs for errors
