### ISSUE TITLE
Cannot find sonoff devices in HASS, but in Google Home App

### ISSUE THREAD

**Issue by TrommlerHH** [AlexxIT/SonoffLAN#276]
Hi,
after installing the AlexxIT/SonoffLAN-integration via HACS I cannot find these devices in the homeassistant.

But - surprisingly to me - they are shown and can be used within the Google Home app.

I use a two-channel wall-switch. With "Decke A" and "Decke B" I can toggle both parts of the lamp and with "Deckenlampe" I can switch both channels in one go.

The .sonoff.json looks like this:

{"10001e3495":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1},"family":{"id":"5ee50b303f21b800082f19de","index":0},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5b409e4862bfca1cc3758dad","name":"Deckenlampe","type":"10","deviceid":"10001e3495","apikey":"8d7b0a46-36de-4fca-aa84-92b7e55a3754","extra":{"extra":{"description":"20171020003","brandId":"592502ed6ea4362d4399fe58","apmac":"d0:27:00:3c:66:7b","mac":"d0:27:00:3c:66:7a","ui":"双通道开关","modelInfo":"59707e4348b2ec2c22a02330","model":"PSF-B04-GL","manufacturer":"深圳科信嘉联科技有限公司","uiid":7,"staMac":"60:01:94:98:42:51","chipid":"00984251"},"_id":"59e9a73a1413ecb529a97c84"},"createdAt":"2018-07-07T11:04:40.965Z","__v":0,"onlineTime":"2020-11-08T04:48:15.967Z","ip":"77.1.42.210","location":"","params":{"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"lock":0,"init":1,"sledOnline":"on","version":8,"bindInfos":{"gaction":["8d7b0a46-36de-4fca-aa84-92b7e55a3754_ewelink-google-home-v1","8d7b0a46-36de-4fca-aa84-92b7e55a3754_ewelinkGoogleHome"]},"configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"fwVersion":"3.4.1","switches":[{"switch":"on","outlet":0},{"switch":"off","outlet":1},{"switch":"on","outlet":2},{"switch":"on","outlet":3}],"staMac":"60:01:94:98:42:51","rssi":-29},"tags":{"ck_channel_name":{"0":"Decke A","1":"Decke B"},"m_3754_trom":"on"},"offlineTime":"2020-11-06T04:50:26.842Z","deviceStatus":"","sharedTo":[],"devicekey":"407e4c24-b83a-41a6-ab3f-ef9ef8a076ca","deviceUrl":"","brandName":"KESEN","showBrand":true,"brandLogoUrl":"","productModel":"KS-601-2","devConfig":{},"uiid":7}}

The sonoff-part in my config-yaml looks like this:
sonoff:
  username: !secret ewelink_user
  password: !secret ewelink_pwd

So as I see the sonoff-devices within the google home app and as the .sonoff.json-file has been setup I do not understand, how to use the switch as a homeassistant-device.

Any idea, what is missing?

**Comment by KevinKTM** [comment]
I am having similar problem that mine does not show up as a device - but I do see it in developer tools - state, however 
mine lists as supported_features: 0  Does this mean I have an unsupported device. I too can see my device in google home
![Screenshot 2020-11-08 113638](https://user-images.githubusercontent.com/28842153/98482543-fc901e80-21b6-11eb-9765-fc7e7c3e13e8.png)

**Comment by TrommlerHH** [comment]
Oh, yes, same for me. I also see them the developer states:
![image](https://user-images.githubusercontent.com/73431052/98482688-4acb0f00-2203-11eb-8a5d-8a51b91ff091.png)

**Comment by KevinKTM** [comment]
Although my garage door does not show up as a device, I added a card in lovelace and it seems to be working.

**Comment by KevinKTM** [comment]
Any comments on why my sonoff garage door device does not show up in my device list?

**Comment by AlexxIT** [comment]
Devices don't supported #83 
Read pinned issues.

**Comment by TrommlerHH** [comment]
Ok, understood ... somehow ...

So although it is not available as device, it is nevertheless possible to create a lovelace-button to toggle it off an on (that works!), but it is not possible to use it as an action in an automation?

**Comment by AlexxIT** [comment]
@TrommlerHH Read linked issue. You don't need device to use automation.

**Comment by TrommlerHH** [comment]
Perfect, AlexxIT!

Now I got it!

Thanks a lot!
