### ISSUE TITLE
WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_sonweb!

### ISSUE THREAD

**Issue by tadthies** [AlexxIT/SonoffLAN#277]
I am seeing the following in the system log under the supervisor.  Is this anything to worry about?

20-11-11 14:32:21 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_sonweb!
20-11-11 14:32:21 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_a0d7b954_sonweb application
20-11-11 14:32:22 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on hassioaddons/sonweb-aarch64 with version 0.13.1
20-11-11 14:32:25 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_sonweb
20-11-11 14:32:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_sonweb!
20-11-11 14:32:52 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_sonweb application
20-11-11 14:32:53 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on hassioaddons/sonweb-aarch64 with version 0.13.1
20-11-11 14:32:57 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_sonweb
20-11-11 14:33:23 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with a0d7b954_sonweb!
20-11-11 14:33:24 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_a0d7b954_sonweb application
20-11-11 14:33:25 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on hassioaddons/sonweb-aarch64 with version 0.13.1
20-11-11 14:33:28 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_sonweb

**Comment by AlexxIT** [comment]
I don't know what sonweb is.

**Comment by tadthies** [comment]
ok, I will do some more digging, I thought it was related to this.

**Comment by tadthies** [comment]
sonweb is what is now TasmoAdmin

I will close this
