### ISSUE TITLE
KingArt KING-M4 compability

### ISSUE THREAD

**Issue by nilsenen93** [AlexxIT/SonoffLAN#28]
Hi, thanks for very nice work,

i have an wall dimmer switch in eweelink app, that does not appear in HA, any chance there is a way to intergrate it?

KingArt, model KING-M4, firmware: 2.7.0 (PSF-BTA-GL)

**Comment by AlexxIT** [comment]
Duplicate #26

**Comment by AlexxIT** [comment]
Supported
