### ISSUE TITLE
sonoff.update_consumption missed

### ISSUE THREAD

**Issue by rkiller2006** [AlexxIT/SonoffLAN#283]
Hello Alex,

The sonoff.update_consumption service missed.
What is wrong?

**My configuration:**
  username: !secret ewelink_username
  password: !secret ewelink_password
  mode: local
  force_update: [power, current, voltage]
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  sensors: [power, current, voltage]

**Comment by AlexxIT** [comment]
Only in auto or cloud mode

**Comment by rkiller2006** [comment]
it is clear, works in cloud

**Comment by noesbwi** [comment]
Thanks. It answered.

**Comment by andersongulao** [comment]
> Only in auto or cloud mode

I am running the 2.4.6 version and the service sonoff.update_cosumption is not available even in cloud or auto mode. It stopped working few days ago.

**Comment by AlexxIT** [comment]
A few days ago there were problems with the ewelink cloud
