### ISSUE TITLE
Sonoff 4CH PRO R2 with 2 Roller shutters

### ISSUE THREAD

**Issue by acuadulza** [AlexxIT/SonoffLAN#285]
I am using a Sonoff 4CH PRO with 2 roller shutters, 

Any way to configure the "**cover**" entity ?

I tried to adapt the examples of the standard documentation, but unfortunately it doesn't work....

sonoff:
    devices:
        1000baabdb:
         device_class:
            - cover [1, 2]  # open/close shutter 1
             - cover [3, 4]  # open/close shutter 2
      name: Sonoff 4CH PRO R2

Thanks in advance !

**Comment by AlexxIT** [comment]
Check #78
