### ISSUE TITLE
404 error when trying to add to HACS

### ISSUE THREAD

**Issue by SPYUK** [AlexxIT/SonoffLAN#290]
HACS : 1.6.2
Home Assistent: 0.117.6
When attempting to add custom repositories I get following error:

![image](https://user-images.githubusercontent.com/28460074/100231934-9548cd00-2f1f-11eb-9f83-cf0cf138318a.png)

Can anyone help please or is it possible to install without HACS?

**Comment by AlexxIT** [comment]
You have a typo
