### ISSUE TITLE
Sonoff devices no longer working

### ISSUE THREAD

**Issue by jkottier** [AlexxIT/SonoffLAN#291]
I noticed this evening (~21:00 GMT+1) that I cannot control my Sonoff devices anymore via HA. 

This afternoon everything was still working like a charm.
Perhaps this has something todo with the hass.io / AWS outtage of this afternoon?
Unfortunately after this has been resolved my problem remains.

Next, the Ewelink app is still working normally.

Things I've tried zo far:
1. Rebooting HA
2. Removing the SonoffLan integration + all entities (that were no longer working) and add the Sonoff Lan integration again
3. Downgrade SonoffLan to an older 2.x version
4. Restore a snapshot when the devices were working

All scenario's have the same result: no Sonoff enitities available :(

After a reboot my debug log looks like this:
```
2020-11-25 22:48:07  DEBUG    main          SysInfo: {'version': '0.118.3', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.8.6', 'docker': True, 'arch': 'aarch64', 'os_name': 'Linux', 'os_version': '4.19.127-v8', 'supervisor': '2020.11.0', 'host_os': 'HassOS 4.17', 'docker_version': '19.03.12', 'chassis': 'embedded'}
2020-11-25 22:48:07  DEBUG    main          LOCAL mode start
2020-11-25 22:48:11  DEBUG    sonoff_cloud  5 devices loaded from the Cloud Server
```

So 5 devices have been found, however non of these are available as an entity

Config: 
```
sonoff:
  default_class: light
  username: !secret sonoff_username
  password: !secret sonoff_password
  mode: local
  reload: always
  debug: True
```

Home assistant: 0.118.3
HACS: 1.6.2
SonoffLan: 2.3.2

**Comment by AlexxIT** [comment]
Try remove `mode` from config

**Comment by jkottier** [comment]
@AlexxIT, thanks this worked! Is mode "local" no longer supported?

**Comment by AlexxIT** [comment]
I think you have some problems in local network with multicast/mdns/zeroconf.
No mode is auto mode. It uses local and cloud connection simultaneously.

**Comment by jkottier** [comment]
Oké, strange I didn't encounter this issue before. Perhaps my modem/router has been updated.
Thanks again for your support!
