### ISSUE TITLE
Sonoff BasicR2 Unavailable

### ISSUE THREAD

**Issue by joshfeingold** [AlexxIT/SonoffLAN#295]
Hi there.  Running latest version of HA and connecting to Sonoff BasicR2 switch (Current Version 3.5.0).   I set up an automation that when the temperature goes below freezing, it turns on this switch.  Here is the YAML:

service: switch.turn_on
data: {}
entity_id: switch.sonoff_1000b7c24d

I noticed that whenever this automation happens, it results in the switch becoming "Unavailable" in HA, and in ewelink it shows as offline.

Any idea what is happening?  Is there a different way to turn the switch on and off in the automation that won't knock it offline?  Thanks!

**Comment by AlexxIT** [comment]
Maybe some problems with your wifi
