### ISSUE TITLE
Sonoff RF Bridge 433 does not work in local mode

### ISSUE THREAD

**Issue by gribouk** [AlexxIT/SonoffLAN#299]
Today was discovered through, the experimental approach, that Sonoff RF Bridge 433 does not work in local mode. The set up was the default local\cloud mode. The internet went off this morning and the bridge started blinking not sending the signal to HA. After rebooting in local mode nothing has changed. The fw is 3.5.0. None of the 3 bridges I have is accessible at the moment...

**Comment by tech-freak** [comment]
rf bridge don't have lan mode, this component won't help you to get lan support 
ask ewelink

**Comment by tech-freak** [comment]
rf bridge don't have lan mode, this component won't help you to get lan support 
ask ewelink

if you need local support then flash it with tasmota firmware

**Comment by gribouk** [comment]
I know that by now, but in component docs it is listed with local/cloud modes supporting devices...

**Comment by AlexxIT** [comment]
RF Bridge works in local mode!

**Comment by gribouk** [comment]
Proved by experiment - no!

**Comment by tech-freak** [comment]
> RF Bridge works in local mode!

it's work in cloud mode only sir , not sure if it came in recent update as i switched to tasmota 2 weeks back only because of this reason

**Comment by orthobots** [comment]
Hi everyone. I'm a little lost here. Sorry for asking again, but does this mean that the RF Bridge works locally without the cloud or it has to have an active cloud connection in order to work, 

My reason for asking is because I can't get it to work offline as well

**Comment by AlexxIT** [comment]
My 433 works locally. Don't know why it doesn't work for some users

**Comment by orthobots** [comment]
may i ask what firmware is your 433 on, @AlexxIT

**Comment by jk7gr** [comment]
@AlexxIT, mate you have done excellent work but I can confirm as well offline mode is not working on the bridge. I know this first hand because all my RF switches gone bad when there was a disconnection from the sonoff server.
Maybe we need some custom configuration? Please help. Thank you!

**Comment by AlexxIT** [comment]
I think RF with latest firmware have problems with local mode. Mine RF has old firmware.
