### ISSUE TITLE
Sonoff IFan03 support

### ISSUE THREAD

**Issue by wirelessworries** [AlexxIT/SonoffLAN#30]
Hi, First off thank you for your work on this integration it is going to be awesome! I thought I would try out the new Sonoff IFan3 even though it wasn't on the tested list. Couldn't get it to work but saw this in the log so thought I would pass along.

WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] Please, send this device type to developer: fan_light

Thank you!

**Comment by AlexxIT** [comment]
Hi. Enable debug logs (described in readme) and send it to me.
Here or in Discord AlexxIT#0816

**Comment by ginge78** [comment]
Here is an example of an iFan03

Properties: {'txtvers': '1', 'id': 'xxx', 'type': 'fan_light', 'apivers': '1', 'seq': '1', 'encrypt': True, 'iv': 'xxx', 'data1': 'xxxxx'}
State: {'sledOnline': 'on', 'light': 'off', 'fan': 'off', 'speed': 3, 'startup_light': 'on', 'startup_fan': 'off'}

**Comment by ginge78** [comment]
Here is an iFan02 for reference. The iFan02 works as 4 switchs, 
_1 light 
fan off: _2: off, _3: any, _4: any
fan 1: _2: on, _3: off, _4: off
fan 2: _2: on, _3: on, _4: off
fan 3: _2: on, _3: off, _4: on

So _2 controls if the fan is on and _3,_4 control the speed.

Properties: {'txtvers': '1', 'id': 'xxx', 'type': 'strip', 'apivers': '1', 'seq': '75', 'encrypt': True, 'iv': 'xxx', 'data1': 'xxx', 'data2': 'xxx', 'data3': 'xxx'}
State: {'sledOnline': 'on', 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'switch': 'off', 'outlet': 3}]}

**Comment by AlexxIT** [comment]
@ginge78 it will help. I will add support, not a problem.

**Comment by AlexxIT** [comment]
@ginge78 you have iFan02 and iFan03?
With version 2 everything is clear, it works like a 4 channel switch.
But version 3 already has options - light, fan and speed.

**Comment by ginge78** [comment]
I have both, so if you need someone to test and verify.

The version 2 works the same as the previous integrations I had for HASS, peterbuga/HASS-sonoff-ewelink, and I then created scripts and switchs so that I could set the fan speed, to off, speed 1, 2, or 3. Version2 is usable, but requires some additional work to contol the fan, I can share the scripts, and swith templates that I use.

The iFan03 properties look the same as they are presented in the ewelink app, as you select if the light is on or off, fan on or off, and a fan speed 1,2,or 3.

**Comment by wirelessworries** [comment]
Thank you. Let me know if you need anything else I would be happy to provide more logs if still needed.

**Comment by AlexxIT** [comment]
@ginge78 @wirelessworries all information from sonoff.json will help. You can delete private data.

**Comment by ginge78** [comment]
First two are the iFan02

{
"xxxx":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"xxxx","name":"iFan02","type":"10","deviceid":"xxx","apikey":"xxx-xxx","extra":{"extra":{"uiid":34,"description":"WO18690","brandId":"58e5f344baeb368720e25469","apmac":"xxxxx","mac":"xxxx","ui":"智能风扇灯","modelInfo":"59dc87a65c1af3a660ca6b53","model":"PSF-B04-GL","manufacturer":"深圳松诺技术有限公司","staMac":"xxxxxxx","chipid":"xxx"},"_id":"xxxxx"},"createdAt":"2019-01-08T08:53:29.415Z","__v":0,"onlineTime":"2020-02-18T07:16:30.167Z","ip":"xxxxx","location":"","params":{"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"lock":0,"sledOnline":"on","version":8,"bindInfos":{"gaction":["xxxx-google-home-v1"]},"partnerApikey":"xxxx","configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"fwVersion":"3.3.0","pulse":"off","switches":[{"switch":"off","outlet":0},{"outlet":1,"switch":"off"},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"pulseWidth":0,"staMac":"xxxxx","rssi":-83,"init":1},"deviceStatus":"","offlineTime":"2020-02-18T07:16:11.551Z","sharedTo":[],"devicekey":"xxxx","deviceUrl":"https://us-api.coolkit.cc/api/detail/xxxx_en.html","brandName":"Sonoff","showBrand":true,"brandLogoUrl":"https://us-ota.coolkit.cc/logo/KRZ54OifuGmjoEMxT1YYM3Ybu2fj5K2C.png","productModel":"iFan02","devConfig":{},"uiid":34},
"xxxx":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"xxxx","name":"iFan02","type":"10","deviceid":"xxxx","apikey":"xxxx","extra":{"extra":{"uiid":34,"description":"WO18487","brandId":"58e5f344baeb368720e25469","apmac":"xxxx","mac":"xxx","ui":"智能风扇灯","modelInfo":"59dc87a65c1af3a660ca6b53","model":"PSF-B04-GL","manufacturer":"深圳松诺技术有限公司","staMac":"xxxx","chipid":"0047ACC3"},"_id":"xxxx"},"createdAt":"2019-01-23T08:00:13.843Z","__v":0,"params":{"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"lock":0,"sledOnline":"on","version":8,"bindInfos":{"gaction":["xxxx_ewelink-google-home-v1"]},"partnerApikey":"xxxx","pulseWidth":0,"pulse":"off","staMac":"xxxxx","rssi":-83,"fwVersion":"3.3.0","configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"switches":[{"outlet":0,"switch":"off"},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"init":1,"fan":"on"},"onlineTime":"2020-02-15T14:28:46.712Z","ip":"xxxx","location":"","offlineTime":"2020-02-15T14:28:32.619Z","deviceStatus":"","sharedTo":[],"devicekey":"xxxx","deviceUrl":"https://us-api.coolkit.cc/api/detail/xxxx_en.html","brandName":"Sonoff","showBrand":true,"brandLogoUrl":"https://us-ota.coolkit.cc/logo/xxx.png","productModel":"iFan02","devConfig":{},"uiid":34},
"xxxx":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"xxxxx","name":"xxxx bedroom light","type":"10","deviceid":"xxxxxx","apikey":"xxxxx","extra":{"extra":{"uiid":34,"description":"20190611031","brandId":"5c4c1aee3a7d24c7100be054","apmac":"xxxxx","mac":"xxxx","ui":"智能风扇灯","modelInfo":"5ca1f6d0b5210ca205adf0fc","model":"PSF-BFB-GL","manufacturer":"深圳松诺技术有限公司","chipid":"xxxx","staMac":"xxxx"},"_id":"xxxx"},"params":{"partnerApikey":"xxxxx","switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"on","outlet":3}],"configure":[{"startup":"on","outlet":0},{"startup":"off","outlet":1},{"startup":"stay","outlet":2},{"startup":"stay","outlet":3}],"rssi":-78,"staMac":"xxxx","fwVersion":"3.4.0","init":1,"sledOnline":"on","version":8,"bindInfos":{"gaction":["xxxxxx_ewelink-google-home-v1","xxxxx_ewelink-google-home-v1"]}},"createdAt":"2019-08-15T05:20:17.997Z","__v":0,"onlineTime":"2020-02-18T07:44:54.619Z","ip":"xxxx","location":"","offlineTime":"2020-02-18T07:43:40.222Z","deviceStatus":"","sharedTo":[],"devicekey":"xxxx","deviceUrl":"","brandName":"SONOFF","showBrand":true,"brandLogoUrl":"https://us-ota.coolkit.cc/logo/xxx.png","productModel":"iFan","devConfig":{},"uiid":34},
"xxxx":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"xxxxx","name":"xxxxx","type":"10","deviceid":"xxxxxx","apikey":"xxxxx","extra":{"extra":{"uiid":34,"description":"20190611031","brandId":"xxxxx","apmac":"xxxxx","mac":"xxxxx","ui":"智能风扇灯","modelInfo":"xxxxx","model":"PSF-BFB-GL","manufacturer":"深圳松诺技术有限公司","chipid":"xxxxx","staMac":"xxxx"},"_id":"xxxxx"},"params":{"partnerApikey":"xxxxx","switches":[{"outlet":0,"switch":"off"},{"switch":"off","outlet":1},{"switch":"on","outlet":2},{"switch":"off","outlet":3}],"configure":[{"startup":"on","outlet":0},{"startup":"off","outlet":1},{"startup":"stay","outlet":2},{"startup":"stay","outlet":3}],"rssi":-49,"staMac":"xxxx","fwVersion":"3.4.0","init":1,"sledOnline":"on","version":8,"bindInfos":{"gaction":["xxxxx_ewelink-google-home-v1","xxxx_ewelink-google-home-v1"]}},"createdAt":"2019-08-15T07:37:50.340Z","__v":0,"onlineTime":"2020-02-18T07:43:03.029Z","ip":"xxxx","location":"","offlineTime":"2020-02-18T07:41:51.861Z","deviceStatus":"","sharedTo":[],"devicekey":"xxxx","deviceUrl":"","brandName":"SONOFF","showBrand":true,"brandLogoUrl":"https://us-ota.coolkit.cc/logo/xx.png","productModel":"iFan","devConfig":{},"uiid":34}
}

**Comment by wirelessworries** [comment]
Here is what is in my sonoff.json file. I currently only have the one iFan03 device. Thank you.

{"xxxx":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0,"appDoorbellNotify":1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"xxxx","name":"xxxx","type":"10","deviceid":"xxxx","apikey":"xxxx","extra":{"extra":{"uiid":34,"description":"xxxx","brandId":"xxxx","apmac":"xxxx","mac":"xxxx","ui":"智能风扇灯","modelInfo":"xxxx","model":"PSF-BFB-GL","manufacturer":"深圳松诺技术有限公司","chipid":"xxxx","staMac":"xxxx"},"_id":"xxxx"},"createdAt":"2020-02-17T20:30:57.705Z","__v":0,"onlineTime":"2020-02-18T17:08:55.485Z","params":{"bindInfos":{"alexa":["xxxx"]},"switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"on","outlet":2},{"switch":"off","outlet":3}],"configure":[{"startup":"on","outlet":0},{"startup":"off","outlet":1},{"startup":"stay","outlet":2},{"startup":"stay","outlet":3}],"rssi":-55,"staMac":"xxxx","fwVersion":"3.4.0","init":1,"sledOnline":"on","version":8,"partnerApikey":"xxxx"},"ip":"xxxx","location":"","offlineTime":"2020-02-17T21:03:02.184Z","deviceStatus":"","sharedTo":[],"devicekey":"xxxx","deviceUrl":"","brandName":"SONOFF","showBrand":true,"brandLogoUrl":"https://us-ota.coolkit.cc/logo/xxxx.png","productModel":"iFan","devConfig":{},"uiid":34}}

**Comment by AlexxIT** [comment]
@ginge78 @wirelessworries I added more debugging features in the latest version.

Now your ifan03 should display as binary_sensor. And you can see all the changes in the properties that happen to it.

The `send_command` service also appeared. You can check what commands it is controlled. And tell them to me.

I think you need to try all 3 examples from the readme file.

And maybe something like that:

```yaml
device: 1000123456
command: switches
light: 'on'
fan: 'on'
speed: 3
```

**Comment by ginge78** [comment]
The following works.

device: 1000xxxx
command: fan
fan: "on"
speed: 3

device: 1000xxxxx
command: light
light: "off"

**Comment by AlexxIT** [comment]
@ginge78 @wirelessworries I add support iFan02 and iFan03 in a separate branch:
https://github.com/AlexxIT/SonoffLAN/tree/fan

Device type ifan03 should be detected automatically anyway.
Device type ifan02 is read from sonoff.json file.

Tell me if everything works fine.

**Comment by wirelessworries** [comment]
Hi, sorry Im late to reply here. I copied over the files from the other branch to my custom_components sonoff directory and rebooted. I can see the light and fan entities now for the iFan03 but they show constantly on in HA even though off and I cant control them. I'm checking to make sure I didnt miss anything or do something wrong now. Thank you!

**Comment by ginge78** [comment]
I am still trying to test and debug the ifan2 and fan controls

This will fix the light state for iFan02

class SonoffFan03Light(EWeLinkToggle):
    def _update(self, device: EWeLinkDevice):
        # яркость прилетает не всегда
        ison = device.state.get('light') == 'on'
        _LOGGER.debug(f"Light on: {ison}")
        self._is_on = ison

**Comment by AlexxIT** [comment]
@ginge78 my bad. I fixed it in latest version:
https://github.com/AlexxIT/SonoffLAN/tree/fan

You mean iFan03? SonoffFan03Light it's about v3.

You can write me to Discord (AlexxIT#0816) or Telegram for a quicker response.

**Comment by cmjennnings21** [comment]
> The following works.
> 
> device: 1000xxxxx
> command: light
> light: "off"
> 
> device: 1000xxxx
> command: fan
> fan: "on"
> 
> device: 1000xxxx
> command: fan
> fan: "on"
> speed: 3

@ginge78 how have you implemented this is HA? I can see the bianary sensor and see the changes when I use  the Ewelink app, but cant get my head round how to control from HA?

**Comment by ginge78** [comment]
@cmjennnings21 

The test was through the developer tools, services other, in Hass. It was intially unknown how this device worked as the data in the state was completely different from other Sonoff devices, As @AlexxIT does not have an iFan03 he required someone to test. 

@AlexxIT is doing currently implementing this so it will automatically add the device to HA as a light and fan. Great job @AlexxIT. This modification is in the fan branch if you want to test and assist

**Comment by wirelessworries** [comment]
I can successfully control the light and fan when it is a binary senor. When I copy in the files in your fan branch in GitHub and reboot HA the Ifan03 device comes in as fan and light entities but I can not control it from the HA UI. Is this what you needed tested with your fan branch in GitHub? Thanks again for all your work on this. Hope I'm helping.

**Comment by ginge78** [comment]
I have altered files of the fan brach locally, and have both fan types working.

I will send the changes to @AlexxIT via discord, later today.

**Comment by ginge78** [comment]
Hi All,

I have got both fans iFan02, and iFan03 to work by

1. Altering utils.py and changing the UIIDS setting as the current one stalled when adding an iFan02 to HA

34: ['light', 'fan'],  # Sonoff iFan02 and iFan03

2.  Added the logger to fan.py

3. Change the seup_platfom so it looks at the device type, also included debugging incase there is another sonoff device that controls a fan.

def setup_platform(hass, config, add_entities, discovery_info=None):
    if discovery_info is None:
        return

    deviceid = discovery_info['deviceid']
    channels = discovery_info['channels']
    device = hass.data[DOMAIN][deviceid]
    
    if device.config['type'] == 'fan_light':
        _LOGGER.debug("Detected iFan03-device id '{deviceid}' type '{device.config['type']}' channels '{channels}'")
        add_entities([SonoffFan03(device)])
    elif device.config['type'] == 'strip':
        _LOGGER.debug("Detected iFan02-device id '{deviceid}' type '{device.config['type']}' channels '{channels}'")
        add_entities([SonoffFan02(device)])
    else:
        _LOGGER.debug("Detected Other-device id '{deviceid}' type '{device.config['type']}' channels '{channels}'")
        add_entities([EWeLinkToggle(device, channels)])

4. Added set_speed for each device type

-- in SonoffFan02 class
    def set_speed(self, speed: str) -> None:
        _LOGGER.debug(f"Speed {speed}")
        if speed == SPEED_OFF:
            self.device.turn_off([2])
        elif speed == SPEED_LOW:
            self.device.turn_on([2])
            self.device.turn_off([3])
            self.device.turn_off([4])
        elif speed == SPEED_MEDIUM:
            self.device.turn_on([2])
            self.device.turn_on([3])
            self.device.turn_off([4])
        elif speed == SPEED_HIGH:
            self.device.turn_on([2])
            self.device.turn_off([3])
            self.device.turn_on([4])
        else:
            return

-- in SonoffFan03 class
    def set_speed(self, speed: str) -> None:
        if speed:
            params = {'fan': 'on', 'speed': self.speed_list.index(speed)}
        else:
            return
        self.device.send('fan', params)

I can send the full files via discord if required @AlexxIT . 

Can retest once the changes are in the branch to confirm that I have not missed anything.

**Comment by wirelessworries** [comment]
Things seem to be working perfectly on the ifan03 with the latest release. Thank you!

**Comment by feddemm** [comment]
Hi after the last update ifan03 stop working (8d7e51c) please tell me what do you need to check it

**Comment by AlexxIT** [comment]
@feddemm I hope fixed this problem in the latest update.

In case of problems, you need to look for errors in the logs.

**Comment by feddemm** [comment]
Thanks its working back again!

**Comment by AlexxIT** [comment]
iFan 2 and 3 support added in latest release.

**Comment by wirelessworries** [comment]
Hi, I really hate to bother you but the light portion of the Ifan03 integration broke with update c6a064c. Is it possible for me to revert back to a working version? Thank you!

**Comment by AlexxIT** [comment]
@wirelessworries not a problem. The changes did not apply to this part. How doesn’t work? Are there any errors in the logs?

**Comment by wirelessworries** [comment]
@AlexxIT when I turn the light on in HA it doesnt turn on and and will also turn itself back off in the HA UI. The fan part works as perfectly it is just the light part that broke. I just turned my log level back up and will reboot. Once my wife is up I will try it out again and grab logs if any. Just in case it does come on I dont want to wake her up. Thank you!

**Comment by AlexxIT** [comment]
@wirelessworries Errors should be shown without additional log level settings

**Comment by wirelessworries** [comment]
@AlexxIT I wanted to see if I was getting any warnings as well. I dont get any errors but I do get a warning 
WARNING (MainThread) [custom_components.sonoff] Error when send switch to xxxx
Also when viewing the entity in the developer tools it shows supported_features: 0 for the light entity now. Please let me know if there is something else I can try. Thank you again!

**Comment by AlexxIT** [comment]
@wirelessworries I hope fixed this problem in the latest update.

**Comment by wirelessworries** [comment]
@AlexxIT it appears to be working from the UI. I will test again when I get home so I can see in person but it appears to be resolved. Thank you!

**Comment by wirelessworries** [comment]
@AlexxIT, Sorry for the delay. I verified in person and everything is working perfect again. Thank you!

**Comment by AlexxIT** [comment]
Try new version #99 
Preferably in only local mode. And only in cloud mode. It is important to understand if something has broken.

**Comment by cmjennnings21** [comment]
All appears to be working for me. I’ve also just received the Sonoff 4CHR3 and this is working as expected. Chris Sent from Mail for Windows 10 From: Alex XSent: 11 May 2020 15:01To: AlexxIT/SonoffLANCc: cmjennnings21; MentionSubject: Re: [AlexxIT/SonoffLAN] Sonoff IFan03 support (#30) Try new version #99Preferably in only local mode. And only in cloud mode. It is important to understand if something has broken.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by AlexxIT** [comment]
iFan03 users please check new version https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.1.4

Does everything continue to work in local mode?

**Comment by wirelessworries** [comment]
Hi @AlexxIT,
The fan appears to work fine but after updating I lost the light entity of the Sonoff iFan03 device. I will have to look into it more when I have some time. Right now in HA UI it says "This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.
If the entity is no longer in use, you can clean it up by removing it." for the light entity. Thank you.

**Comment by AlexxIT** [comment]
@wirelessworries could change entity id. Try search with device ID
