### ISSUE TITLE
 ERROR (MainThread) [supervisor.store] https://github.com/AlexxIT/SonoffLAN is not a valid add-on repository

### ISSUE THREAD

**Issue by userosos** [AlexxIT/SonoffLAN#302]
Hi! I install the repo use HACKS. But if i pressed to the repo i have endless loading/ In logs i can see it:
20-12-06 20:40:45 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/AlexxIT/SonoffLAN repository
20-12-06 20:40:51 ERROR (MainThread) [supervisor.store] https://github.com/AlexxIT/SonoffLAN is not a valid add-on repository
20-12-06 20:40:51 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/7ae7dbc6/repository.json: [Errno 2] No such file or directory: '/data/addons/git/7ae7dbc6/repository.json'
20-12-06 20:40:51 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/7ae7dbc6/repository.json
20-12-06 20:40:51 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
20-12-06 20:40:52 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 7ae7dbc6
20-12-06 20:40:52 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/AlexxIT/SonoffLAN
20-12-06 20:40:52 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
20-12-06 20:40:52 INFO (MainThread) [supervisor.resolution.check] System checks complete
20-12-06 20:41:30 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 0.118.5

**Comment by AlexxIT** [comment]
This is not addon

**Comment by userosos** [comment]
@AlexxIT Where i do the error?

**Comment by userosos** [comment]
> 
> 
> @AlexxIT Where i do the error?

Ok. I reinstall. It work ok. But i can`t use it i add in configuration.yaml:
sonoff:
  username: email
  password: password
  mode: local
  reload: always 
I can`t see it in objects.
I use Sonoff S26.

**Comment by userosos** [comment]
> 
> 
> > @AlexxIT Where i do the error?
> 
> Ok. I reinstall. It work ok. But i can't use it i add in configuration.yaml:
> 
> ```
> sonoff:
>   username: email
>   password: password
>   mode: local
>   reload: always 
> ```
> 
> I can`t see it in objects.
> I use Sonoff S26.
```
sonoff:
  username: email
  password: password

Works OK! Thx!
```
