### ISSUE TITLE
Sonoff Mini with light switch 

### ISSUE THREAD

**Issue by agustusbotti** [AlexxIT/SonoffLAN#303]
Hello, my English is not good so I'm going to use the Google translator, sorry.
I have a Sonoff Mini connected to a light switch to turn on a light bulb.
What happens is that when I turn off the light from the switch in HA it does not reflect this change.
In the Ewelink app it works perfectly

Can you help me with this? 
Thank you

**Comment by AlexxIT** [comment]
Show your config

**Comment by agustusbotti** [comment]
<img width="276" alt="Captura de Pantalla 2020-12-07 a la(s) 13 37 06" src="https://user-images.githubusercontent.com/70614796/101378178-88b66400-3891-11eb-84d7-baea9fa5f59c.png">

**Comment by agustusbotti** [comment]
<img width="420" alt="Captura de Pantalla 2020-12-07 a la(s) 13 51 17" src="https://user-images.githubusercontent.com/70614796/101379720-56a60180-3893-11eb-9131-4b8d5eae33b4.png">

**Comment by AlexxIT** [comment]
This config not from my component

**Comment by agustusbotti** [comment]
I don't understand then what configuration you mean.
Where can I get it from?

**Comment by AlexxIT** [comment]
Scan interval, grace period, API region not from my company. Are you sure you using my component?

**Comment by agustusbotti** [comment]
AlexxIT thanks for the reply.
As I mentioned, my English is not very good, I put those parameters by watching videos on YouTube and watching guides of all kinds, which in the end did not work either.
After rereading the documentation I found the following part
https://github.com/AlexxIT/SonoffLAN#common-problems-in-only-lan-mode
My HA is in a VM with ESXI after changing the parameters to It was solved

sonoff:
  username: xxxxxxxxxx
  password: xxxxxxxx
  mode: cloud
  
  devices:
    1000ad1101:
      device_class: [light, light]
      name: Sonoff T1 2C
    1000abcde0:
      device_class: light
      name: Sonoff Basic
    1000ea6c7d:
      device_class: light
      name: Sonoff Mini

Thanks for everything
