### ISSUE TITLE
Switch of Sonoff TH16 not responding to switch toggle

### ISSUE THREAD

**Issue by Peter915671** [AlexxIT/SonoffLAN#305]
I recently changed a Sonoff S26 to a Sonoff TH16 i already used for the temperature.

From the Ewelink app, I can switch it on and off, just as expected.
Unfortunately, in Home Assistant the TH16 switch doesn't respond to a state change, even though it shows up in an identical manner as the S26.

Any thoughts on how to get it working as a switch?

firmware on the TH16 is 3.4.1
Sonoff LAN: v2.3.2
HA core: 0.118.4

**Comment by AlexxIT** [comment]
Show your config

**Comment by Peter915671** [comment]
It solved itself.
Restarting HA probably did the trick.
