### ISSUE TITLE
Support for 1 channel Inching/Self-locking Switch 5V 12V

### ISSUE THREAD

**Issue by Roberto6969** [AlexxIT/SonoffLAN#308]
Hello!

Thank you for your great work - integration works fantastic! The only problem I have is support for https://ewelink.coolkit.cc/?p=143 1 channel Inching/Self-locking Switch 5V 12V. I can't get entity of this device.
Is this device supported? How can I integrate it?

Thank You!
![image](https://user-images.githubusercontent.com/21200507/101748950-7163ba80-3acd-11eb-9a7f-fda56411657f.png)

**Comment by AlexxIT** [comment]
It should be supported. Show debug logs.

**Comment by Roberto6969** [comment]
Yes, but please let me know how can I filter log events - is this the right way:

logger:
  default: debug
  logs:
    custom_components.sonoff: debug

Or do you want complete log?

**Comment by AlexxIT** [comment]
Check debug mode in readme

**Comment by Roberto6969** [comment]
Here it is. Problematic device is:
Device ID: 100002ca68
FW Name: PSA-B01-GL
In log: 2020-12-12 10:33:44  INFO     sonoff_local  100002ca68 <= Local1 | No devicekey for device
[Log.txt](https://github.com/AlexxIT/SonoffLAN/files/5682834/Log.txt)

**Comment by Roberto6969** [comment]
Actually, this is a problem:
**DEBUG    sonoff_cloud  8 devices loaded from the Cloud Server**
It should load 9 devices, 9th is missing in HA.

When trigger device, this INFO happens:
**INFO     sonoff_local  100002ca68 <= Local1 | No devicekey for device**

Also find out:
**DEBUG    sonoff_local  Zeroconf Removed: eWeLink_100002ca68._ewelink._tcp.local.**

If it is useful: Alex can control this device; device is connected via WiFi range extender (no NAT, getting IP from the same DHCP server). I can PING it. Device is shred with another user. LAN control doesn't change anything.

**Comment by Roberto6969** [comment]
Does anyone have an idea, what is the meaning of **_No devicekey for device_** message?
So far I have found out:
1. Local or Cloud mode: no effect, same error all the time
2. file .sonoff.json has definitions for all devices except for the missing one
I have devicekey but I have no idea how can I force HA to detect the device?

**Comment by AlexxIT** [comment]
Maybe device have been added to other ewelink account?

**Comment by Roberto6969** [comment]
Of course ... many thanks for magic word "other ewelink account"!
Since transition from Peter's project to your's, I have connect N1 in other network segment. I have blamed this change, but in fact I just forget to share N1 device from phone's account to HA's account.

Thank You again!
