### ISSUE TITLE
Support firmware 2.7 and 2.6.1

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/SonoffLAN#31]
Hi everyone!

The current version supports **only firmware 3**.
Firmware 2 has **completely different API**!

**In my free time** I plan to add work with cloud servers to support 2nd firmware.

You can currently use this component [@peterbuga](https://github.com/peterbuga/HASS-sonoff-ewelink), it works with cloud servers and support firmware 2 and 3.

Known devices on the 2nd firmware version:

- Sonoff POW (first) v2.6.1
- Sonoff L1 (LED strip) v2.7.0
- Sonoff Hum (humidifier) v2.7.0
- King Art - King Q4 Cover v2.7.0
- Sonoff SC (sensor)

**Comment by nilsenen93** [comment]
Hi, is there a way to intergrate both urs and peterbuga's code. they both need to have a "sonoff" folder in the config, i tried useing peterbuga's code, and that work for my one King art dimmer (no dimmer function thou..) , but it didnt pick up any of the other switches... 

thanks

**Comment by AlexxIT** [comment]
@nilsenen93 #21

**Comment by neomvll** [comment]
Sonoff B1 need too, not working here :(
Sonoff B1(bullb) model: B1_R2
Firmware: 2.6

But I can't help you, all you need I cant change or even access in my router.

Can I dream you'll make my B1 working?

**Comment by AlexxIT** [comment]
@neomvll send please sonoff.json with B1. You can remove all private data.

**Comment by neomvll** [comment]
@AlexxIT is this?

`
	"*******": {
		"settings": {
			"opsNotify": 0,
			"opsHistory": 1,
			"alarmNotify": 1
		},
		"group": "",
		"online": true,
		"shareUsersInfo": [],
		"groups": [],
		"devGroups": [],
		"_id": "*****",
		"name": " rgb",
		"type": "10",
		"deviceid": "*****",
		"apikey": "******",
		"extra": {
			"extra": {
				"uiid": 22,
				"description": "****",
				"brandId": "****",
				"apmac": "****",
				"mac": "****",
				"ui": "RGB五色球泡灯",
				"modelInfo": "*****",
				"model": "PSF-BLB-GL",
				"manufacturer": "深圳松诺技术有限公司",
				"staMac": "******"
			},
			"_id": "******"
		},
		"params": {
			"state": "on",
			"channel4": "0",
			"channel3": "0",
			"channel2": "0",
			"channel1": "0",
			"channel0": "255",
			"staMac": "*****",
			"rssi": -53,
			"fwVersion": "2.6.0",
			"bindInfos": {
				"gaction": [
					"*****_ewelink-google-home-v1"
				]
			},
			"type": "cold",
			"zyx_mode": 1,
			"timers": [],
			"sledOnline": "on",
			"uiActive": 60
		},
		"createdAt": "2019-05-11T16:58:38.279Z",
		"__v": 0,
		"onlineTime": "2020-02-29T20:52:18.903Z",
		"ip": "******",
		"location": "",
		"offlineTime": "2020-02-29T20:37:55.409Z",
		"deviceStatus": "",
		"sharedBy": {
			"email": "*****",
			"apikey": "****",
			"nickname": "****",
			"permit": 15,
			"shareTime": ****
		},
		"devicekey": "******",
		"deviceUrl": "https://us-api.coolkit.cc/api/detail/******.html",
		"brandName": "Sonoff",
		"showBrand": true,
		"brandLogoUrl": "https://us-ota.coolkit.cc/logo/*****.png",
		"productModel": "B1_R2",
		"devConfig": {},
		"uiid": 22
	}`

**Comment by neomvll** [comment]
@AlexxIT can you confirm if what I sent is right? I've put "****" a lot there haha

**Comment by xrust83** [comment]
Sonoff 4CH (no Pro) fw 3.3.0 PSF-B04_GL - работает

**Comment by Markgit-dev** [comment]
I hope you will solve this issue.

For tempary solution. 
Is ir possible to use both components (component @peterbuga and your component) at once?

**Comment by AlexxIT** [comment]
@Markgit-dev you need to rename:
-  folder
- `DOMAIN` in `init.py` file
- `domain` in `manifest.json` file
to something else, eg `sonoff3`

**Comment by scubi** [comment]
Hi
Please can you help me with my Sonoff B1, the sonoff.json file is created but still does not show in Home assistant? 
What other info do I add to configuration.yaml to get the B1 to work besides username & password
Thanks

**Comment by AlexxIT** [comment]
@scubi what firmware does B1 have?

**Comment by neomvll** [comment]
> @scubi what firmware does B1 have?
Hi @AlexxIT 
My B1 is 2.6. My sonoff.json is up here, I sent it before.

**Comment by AlexxIT** [comment]
@neomvll sorry, too much issues in my projects. 2nd firmware is not yet supported in my component.

**Comment by neomvll** [comment]
> @neomvll sorry, too much issues in my projects. 2nd firmware is not yet supported in my component.

I really understand. Now, let me cry a bit :(

**Comment by AlexxIT** [comment]
Try new version #99
