### ISSUE TITLE
Support for Joshnese bulbs

### ISSUE THREAD

**Issue by Netatout** [AlexxIT/SonoffLAN#313]
These wifi bulbs are recognized in cloud mode only : 
https://a.aliexpress.com/_BUd4E7
It is possible to turn it on and off but not to modulate the intensity or color.

Is this device going to be implemented?

**Comment by juacas** [comment]
I have fixed it by changing two lines:
 lights.py: 44
`elif uiid == 104 or uiid == 103:`

utils.py:79 insert
`103: 'light',  # RGB+CCT color bulb`

It would be great to include it in the next update. Please!

**Comment by juacas** [comment]
This issue is addressed in "B02 Filament CCT bulb added (UIID:103)" #286

**Comment by Netatout** [comment]
Hello,

I installed the latest version V2.4b2. Unfortunately, this version doesn't detect this light bulb in cloud mode anymore (and it's not better in local mode).

I'm at your disposal if you need.

**Comment by AlexxIT** [comment]
You can try to share it to my account sonofflan@gmail.com

**Comment by AlexxIT** [comment]
Is problem fixed in latest release?

**Comment by Netatout** [comment]
As in v1.4b1, v1.4.0 no longer detects bulbs.
I stay on v1.4b0 which allows me at least to turn on and off these bulbs.

**Comment by Netatout** [comment]
I have the config/.sonoff.json, what information do you need from there?
This is the extra and param sections:
"extra":{
         "extra":{
            "uiid":103,
            "description":"2020-09-16 王斌成 编号：202009161401000519262\n",
            "brandId":"5e7a14d748af4f7140874c97",
            "apmac":"d0:27:01:f5:61:07",
            "mac":"d0:27:01:f5:61:06",
            "ui":"双色冷暖灯_支持随调及场景",
            "modelInfo":"5f606f23a2d4f5a009b429b0",
            "model":"BOL-ZHI-DL",
            "manufacturer":

**Comment by AlexxIT** [comment]
So you have some errors in log?

**Comment by Netatout** [comment]
Sorry, I didn't see that my entities had switched from 'switch' to 'light'. Which is logical.
They appear but only in cloud mode. Will local access be possible in the future?

However, there is a big bug:
you can turn off the bulb but not turn it back on. When going into eweelink after this action, you can see that the temperature color applied exceeds the maximum value (see screenshot).

![Screenshot_20210314-221948_eWeLink](https://user-images.githubusercontent.com/18377466/111084914-1949b380-8515-11eb-9fa2-e4d83ac98dcc.jpg)

There is another less annoying bug in HA when you apply a temperature color, it is well applied but the selection slider remains stuck on the left.

**Comment by AlexxIT** [comment]
Color temp is known bug. Will fix it

**Comment by juacas** [comment]
Hi,
Version 2.4.1 does not work propertly with QMS-2C-CW bulbs. The changes in #441 fixed all the issues for me. I hope it will be useful.

**Comment by Netatout** [comment]
I did the test with your corrections.  I confirm it works! good job! Thanks

**Comment by juacas** [comment]
I think this issue can be closed. Thank you to everyone
