### ISSUE TITLE
Problème d'intégration custom repositories

### ISSUE THREAD

**Issue by Thibo0752** [AlexxIT/SonoffLAN#314]
Bonjour,
Merci pour votre travail, et mes excuses par avance pour mon niveau débutant.
Je tente d'installer votre ad on pour connecter à mon Hass.IO mes périphériques sonoff.
A l'installation du custom repositories par l'intermédiaire de HACS j'ai le message d'erreur suivant 
_Repository 'alexxit/sonofflan' exists in the store_  en rouge et je ne peux pas aller plus loin...

Merci de prendre le temps de m'expliquer comment remédier..
Coridalement

**Comment by jonasCr** [comment]
Bonjour Thibo,
Ce message indique que tu n'a pas besoin de le rajouter comme un repo custom. Tu peux le rechercher directement dans le store de HACS (HACS > Intégration > + Explore & Add Repositories et la tu peux chercher sonoff LAN)

PS: tu devrais t'habituer a faire les demandes en anglais :).

J'espère avoir pu t'aider 😊

**Comment by Thibo0752** [comment]
Hello JonasCr,

Merci pour ton message. J'avais trouvé SonOff Lan dans HACS, juste je ne le cherchais pas au bon endroit. Désolé, je débute, je ne maîtrise pas HomeAssistant et sa puissance (je ne maîtrise pas non plus très bien l'anglais ;-) ), je ne maîtrise pas non plus GitHub. Je découvre tout ça en même temps, le challenge est difficile, aussi est-il bien agréable de recevoir des messages et de compter sur la bienveillance de leur auteur. On se sent moins seul.
Merci pour le conseil sur mes demandes en anglais, je vais essayer.
Pour l'instant ce problème avec l'intégration de SonOff est réglé pour moi.
Depuis j'ai beaucoup d'autres interrogations, mais je continue mon apprentissage.
Merci encore et de très bonnes fêtes.
Bien cordialement

**Comment by jonasCr** [comment]
De rien 😊.
Il y a toujours beaucoup a apprendre avec Home Assistant et on ne s'ennuie jamais 😊.
Si ton problème est réglé tu devrais pouvoir l'indiquer dans ton commentaire. Normalement de cette manière (mais pas sur a 100%, 2 ans de github et je ne connais pas tout non plus 😄  ):
![image](https://user-images.githubusercontent.com/33930352/102990710-2196e180-4518-11eb-9cc6-973ce5d592c4.png)

**Comment by Thibo0752** [comment]
Merci encore, jonasCr.
Je clique pour indiquer que mon problème est réglé.
Bonne journée.

**Comment by AlexxIT** [comment]
@jonasCr thanks. SonoffLAN already in HACS defaults. I need to fix docs

**Comment by jonasCr** [comment]
@AlexxIT If it help I can make a PR. It would be the first one but if I can help a few projects that helps me a lot... Why not...
