### ISSUE TITLE
Sonoff Mini devices stop responding in Home Assistant

### ISSUE THREAD

**Issue by itbrl99** [AlexxIT/SonoffLAN#315]
Sonoff Mini devices stop responding in Home Assistant. I need to reboot the sonoff device to get it working in HA again. The device will still work in eWlink with no issue compared to HA where the device will show offline (greyed out). This happens randomly and is not device dependent  I have 9 sonoff mini's in my setup.

**Comment by AlexxIT** [comment]
Please show your config

**Comment by itbrl99** [comment]
I have only one mini in DIY mode for testing. The rest is running normal in cloud mode. The issue will happen in DIY mode and in cloud mode. After a hard reset the device will work again for a day or two. Resetting HA will have no affect.


 # Unflashed SONOFF devices
sonoff:
#  username: ******
#  password: *******
  mode: local
  reload: always
  sensors: temperature
  devices:
   1000e56bfe:
        device_class: light
        name: Sonoff Mini

**Comment by itbrl99** [comment]
The device was config to use DHCP. I have moved them over to a static IP profile. Will this make a difference?

**Comment by itbrl99** [comment]
My setup is a Raspberry Pi and make use of a docker system for HA.

**Comment by AlexxIT** [comment]
Check docs about problems in local mode. Auto mode without DIY works best

**Comment by itbrl99** [comment]
Thanks I use now local and Cloud mode
