### ISSUE TITLE
sonoff pow r2 consumption

### ISSUE THREAD

**Issue by paulorafael68** [AlexxIT/SonoffLAN#316]
Hi. I have my HA working with several sonoff's. everything works fine. on my POW R2 I can sometimes see consumption several days. I have 4 devices but I only saw one of them but now I don’t see any of them ... I didn't change anything. I just restarted the home assistant

**Comment by AlexxIT** [comment]
Show your config

**Comment by paulorafael68** [comment]
Hello Alex. 

I put the code in the configuration file and loaded the consumptions in all my pow r2.  I called the service carrying consumption with a routine and it's top .... thanks.  now it was cool to be able to load for days and make monthly charts .... hug and you are one of my heroes
