### ISSUE TITLE
Basic R3 Issue with fw 3.5.0 and 3.6.0 in DIY mode 

### ISSUE THREAD

**Issue by Joao-Sousa-71** [AlexxIT/SonoffLAN#317]
First let me thanks for the incredible integration done here. Great job!
I have several Basic R3RF with original FW 3.3.0 which work without any issues configured DIY mode.
The latest units that I’ve acquired with latest firmware versions (3.5.0 and 3.6.0) are not recognized by HA and stay unavailable every time that the server restarts and even after many hours.

On the HA log this is message after restart.
“ (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.sonoff_100086f2ab”

 I found two ways that workaround this and return the devices to available mode which are.
- disconnect the power to the sonoffs and connect again ( for some devices which are not accessible this not feasible)
- Send a http post with the “on” or “off” json and then immediately they stay available in HA returning to normal state.

As an additional information I find out that these sonoffs with version 3.5.0 and 3.6.0 have the same behavior and issue with the “tool_01DIY85_v330.exe” from sonoff which might linked with changes in the Multicast DNS implementation on the latest versions and I’m openning an issue on the Sonoff tool repository as well.
Can you help and try to replicate the issue?
For information I’m running Home Assistant container (docker) version 0.118.5

**Comment by caco3** [comment]
@Joao-Sousa-71 Did you get any forther?

I just got my Sonoff RFR3 and switched it to `DIY mode`.
I can successfully access it through POST requests, so I believe it is in the right mode.
Eg. a POST with data `{ "deviceid": "", "data": { } }` to http://192.168.1.122:8081/zeroconf/info returns following response:
```
{
  "seq": 24,
  "error": 0,
  "data": {
    "switch": "off",
    "startup": "off",
    "pulse": "off",
    "pulseWidth": 500,
    "ssid": "***",
    "otaUnlock": false,
    "fwVersion": "3.6.0",
    "deviceid": "1000ed7348",
    "bssid": "74:83:c2:b1:8d:5e",
    "signalStrength": -22
  }
}
```

I then installed HACS and the `AlexxIT/SonoffLAN` plugin which both seems to have successed.
I am unsure what to add to the `configuration.yaml`, so I tried the following: 
```
sonoff:
    devices:
        1000ed7348:
            device_class: switch
            name: Sonoff R3
```

Now I do not understand to continue further. There is no device, no entity and nothing in the log...

I am not sure how to proceed further.

Any ideas?

P.S. Note that the firmware is on `3.6.0`, but I don't think that this should break it.

@Joao-Sousa-71 how does your config look like?

@AlexxIT, @vmannoor, @R34LR4m80 I CC you in since you have it somehow working according to https://github.com/AlexxIT/SonoffLAN/issues/77

Note: Since I never linked it to the eWelink account, I don't have a `sonoff.json` file.

**Comment by Joao-Sousa-71** [comment]
@caco3 my configuration is pretty simple. I have the following on the configuration.yaml:

Sonof:
#reload: always 

For the reload I only remove the # everytime that I need to add a device since that force the update of the cache file.
You don't need to add nothing for the BasicR3(RF)since by default it will be added as a switch. By the way, I have an issue with the Sonoff D1 in DIY since is also added a switch and the dimmable controls are not available and I'm for some guidance from Alex (Issue #318)
Your HA is in the same network of ten Sonoffs? And they are reachable through mDNS?

**Comment by caco3** [comment]
Thanks for the quick reply!

I changed now the config to 
```
sonoff:
    reload: always
```

and restarted HA.

Then I toggled the device state several times using POST requests (Postman).

Still I do not see any entry in the log or a new device/entity.

I am in the same subnet and I can ping the device. I use a docker container and ping also works from with there.

I first have to find out how to check if mDNS works.

**Comment by Joao-Sousa-71** [comment]
You docker container is in bridge mode or host network? Bridge mode doesn't work straight with mDNS.

**Comment by caco3** [comment]
> You docker container is in bridge mode or host network? Bridge mode doesn't work straight with mDNS.

Good point! Indeed it was `bridged`. I changed it now to `host` => HA now found the device and it is working as expected!

**Thank you very much!**

Let me know if I can now help you somehow on your issue. I will test my setup further and give a comment if I see some issues like you have.

**Comment by Joao-Sousa-71** [comment]
Welcome, I'm glad to help. I would like to have the Sonnof D1 as a light device but in DIY mode is not recognized like and therefore is just a switch. If I force as light device ten dimmable option is not available. Hopefully @AlexxIT can help me here.

**Comment by caco3** [comment]
Now as I checked, there actually is a note about this in the readme, how ever I did not understand it. @AlexxIT I improved it a bit, please merge if it is ok: https://github.com/caco3/SonoffLAN/pull/1

**Comment by caco3** [comment]
@Joao-Sousa-71 If this issue is solved for you as well, please close the issue.
