### ISSUE TITLE
Current number kW consumed in the day

### ISSUE THREAD

**Issue by 04hcb** [AlexxIT/SonoffLAN#32]
Hi AlexxIT

I have shown numbers V, A and W
I want to display the number kW consumed in the day, how will I do?
For example: Today - 124kW

Thank you

![ảnh](https://user-images.githubusercontent.com/59406543/74723086-905a3d00-526c-11ea-8fc9-0cc013f9e738.png)

**Comment by AlexxIT** [comment]
This is not part of the component logic.
You should look for a solution in the community:
https://community.home-assistant.io/search?q=power%20consumed%20per%20day

**Comment by AlexxIT** [comment]
Now supported load power consumption from cloud
