### ISSUE TITLE
Click

### ISSUE THREAD

**Issue by H2opolo** [AlexxIT/SonoffLAN#322]
hello I would like to make an automation that provides as a trigger the pressing of the button on sonoff basic r2, can this be done?

**Comment by HVK500** [comment]
Yes, you would need to create an automation in HA that calls the "sonoff.send_command" with the relevant payload, refer to documentation - https://github.com/AlexxIT/SonoffLAN#component-debug-mode

**Comment by H2opolo** [comment]
thanks for your answer. unfortunately I'm not an expert. I report an automation done with shelly. Is it possible to do the same with basic r2?

- alias: "Toggle living room light"
  trigger:
    platform: event
    event_type: shelly.click
    event_data:
      device: shellyswitch25-AABBCC
      channel: 1
      click_type: single
  action:
    service: light.toggle
    entity_id: light.living_room

**Comment by AlexxIT** [comment]
The button should toggle R2 state. Yes?

**Comment by H2opolo** [comment]
yes the idea is that with a click R2 is activated for one minute with
two clicks for two minutes with long click 3 minute

Thanks


Il mer 23 dic 2020, 10:20 Alex X <notifications@github.com> ha scritto:

**Comment by H2opolo** [comment]
hello you haven't answered my question anymore. is there a procedure to read the type of click on the sonoff basic r2?

**Comment by AlexxIT** [comment]
Component can't read button click of devices. You need flash your device with ESPHome.

**Comment by H2opolo** [comment]
Ok, thanks.

Il gio 31 dic 2020, 07:13 Alex X <notifications@github.com> ha scritto:
