### ISSUE TITLE
Error msg. Cannot find the device it is related to.

### ISSUE THREAD

**Issue by gribouk** [AlexxIT/SonoffLAN#326]
For several days I am getting the following message in the log, but cannot identify the problem device:

```
2020-12-25 20:58:35 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Cloud WS exception: {'action': 'update', 'deviceid': '1000bcc9d5', 'apikey': 'd4f1de5b-0156-49b9-9a1d-6a3e60035f0f', 'userAgent': 'device', 'sequence': '1608922714140', 'params': {'sledOnline': 'on'}, 'from': 'device', 'seq': '275648'}
```

Is there a list of devices with IP matching apikey table so I could understand where is a problem?

**Comment by AlexxIT** [comment]
Device ID should be in entity_id

**Comment by gribouk** [comment]
Hmmm... That's how general device card looks in my system. How to correspond it to the data in the log?
![scr1](https://user-images.githubusercontent.com/72703085/103157572-19af9980-47c5-11eb-87b4-d2cf74a2d5b9.jpg)

**Comment by AlexxIT** [comment]
You already has renamed entity_id. Check .sonoff.json file in config folder

**Comment by jrho2** [comment]
After installing hacs, and the ewelink integration, i have got these errors in the logs and i cant find the sonoff ewelink device anywhere in home assistant:

custom-components/sensor.rpi_power - Repository is archived.
16.20.21 – HACS (ERROR)
Error serializing light.kokkenhaven
16.20.20 – google_assistant (ERROR)
Setup failed for default_config: Could not set up all dependencies.
16.20.11 – setup.py (ERROR)
Unable to set up dependencies of default_config. Setup failed for dependencies: automation
16.20.11 – setup.py (ERROR)
Error during setup of component automation
16.20.11 – components/device_automation/__init__.py (ERROR)

I run hassio on a pc!

**Comment by AlexxIT** [comment]
This is problems from other components.

**Comment by AlexxIT** [comment]
Is problem still actual?

**Comment by gribouk** [comment]
No, thanks for the tip!
