### ISSUE TITLE
No devicekey for device firmware 3.6.0 (Sonoff Basic R3)

### ISSUE THREAD

**Issue by pongdevelop** [AlexxIT/SonoffLAN#328]
Sonoff Basic R3
sonoff_local  1000909a3f <= Local1 | No devicekey for device
sonoff_local  1000b8e530<= Local1 | No devicekey for device

**Comment by Roberto6969** [comment]
Did you find a solution for this issue? I have the same problem ...

**Comment by pongdevelop** [comment]
haha it was my mistake
In homeassistant I use another email In the app use another email.
don't must share, The solution is to share the device.
