### ISSUE TITLE
Light group

### ISSUE THREAD

**Issue by mennovf** [AlexxIT/SonoffLAN#338]
I would like to control multiple LED lightbulbs (sonoff B05) as if they were a single one. I can toggle them at once using an entity group, but I'm not able to control their color or other effects as a single unit.
The Light Group is supposed to do this, but I got the multiple components warning and no bulbs worked after that, not even as a single entity.
Is there a way to achieve this?

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
