### ISSUE TITLE
Light turns "ON" randomly

### ISSUE THREAD

**Issue by maciej-szalaj** [AlexxIT/SonoffLAN#339]
I'm using several switches controlled by eWeLink and from time to time it starts to turn "ON" by no reason. Any idea what is going on? Does anyone faced similar issue with this integration?

**Comment by AlexxIT** [comment]
What device model do you using?

**Comment by maciej-szalaj** [comment]
Most of my switches are:

Manufacturer: AoYan touch
Model: M601-1
Sw version: PSF-B01-GL v3.5.0

**Comment by AlexxIT** [comment]
You need reset RF 433.
Hold button 5 sec. Beep. Keep holding. Beep, beep. Release. Click button.

**Comment by maciej-szalaj** [comment]
Those are not RF switches but WiFi.

**Comment by AlexxIT** [comment]
This switches support RF 433 learning! I have more than 10 switches exact this model more than year. All works fine.
