### ISSUE TITLE
SonOff não funciona 

### ISSUE THREAD

**Issue by MoisesSilva2020** [AlexxIT/SonoffLAN#343]
sonoff não funciona mais. eu ligo a luz no celular é no homeassistant não muda o estado

**Comment by AlexxIT** [comment]
Ничего непонятно

**Comment by JiriKursky** [comment]
Hello, maybe I have similar issue. I will try to explain in English even I understand Russian :) 
I am talking about default mode "cloud - local".
Everything work well if you do not use that frequently turn_on/turn_off. In some cases it stops to read real state of device.
I have about 9 devices. 
If I use service turn_on, turn_off via HA service - it works but state is wrong and it is not possible to control that via standard switch.py

How I was investigated in your code system suddenly stops calling proc _zeroconf_handler  in module sonoff_local.py and therefore switch.py is receiving wrong info about state. 
As I saw they made some changes and changed ServiceBrowser to HaServiceBrowser and others imports. Maybe it is root case.

Kind regards, Jiri

**Comment by diazwatson** [comment]
🤣

**Comment by AlexxIT** [comment]
Would you describe the problem in more detail?
