### ISSUE TITLE
Addon refuses to update

### ISSUE THREAD

**Issue by PierreScerri** [AlexxIT/SonoffLAN#35]
Hi 
The addon refuses to update or reinstall to 6ab1899

**Comment by AlexxIT** [comment]
There may be errors in the logs?
I had no problems updating with my hacs.

**Comment by PierreScerri** [comment]
It seems that other addons are behaving the same.

**Comment by PierreScerri** [comment]
It's the change from hassio to homeassistant in the latest update that was cusing the problem.  Situation seems resolved.  Thank you.
