### ISSUE TITLE
All sonoff devices showing unavailable in HA

### ISSUE THREAD

**Issue by bertiebeez** [AlexxIT/SonoffLAN#350]
Running home assistant core-2021.1.3
All Sonoff devices that were all working are now showing as unavailable.  I tried deleting the json file which is mentioned in DrZZs video thinking that it would download the devices again. It did not download the file. I do get this notification at restarting HA.
Invalid config
The following integrations and platforms could not be set up:
zeroconf
sonoff
discovery
default_config

These are in the log file.

Setup failed for sonoff: Could not set up all dependencies.
6:03:46 PM – setup.py (ERROR) - message first occurred at 6:03:38 PM and shows up 2 times
Unable to set up dependencies of sonoff. Setup failed for dependencies: zeroconf
6:03:46 PM – setup.py (ERROR) - message first occurred at 6:03:38 PM and shows up 2 times
Error during setup of component zeroconf
6:03:39 PM – components/zeroconf/__init__.py (ERROR) - message first occurred at 6:03:37 PM and shows up 2 times

**Comment by AlexxIT** [comment]
Zeroconf is a part of Home Assistant. I don't know why it can't start for you. Or other integrations can't start because of that.

**Comment by domoticaiescalbo** [comment]
I have the same problem and Im running home assistant core-2021.1.4.   Is strange.

**Comment by bertiebeez** [comment]
I have even loaded up a snapshot of back when it worked and it still would not work. I tried adding a line in the configuration.yaml of zeroconf. Nothing I have tried so far works.
Another symptom is that my Alexa notification has stopped working. The logs indicate that zeroconf is not able to setup. This is a discovery program and may be why it can not find any of my devices. I can verify that all devices work via their own app, ewelink and amazon. 

Sent from Mail for Windows 10

**Comment by domoticaiescalbo** [comment]
Yes, you're right, I have done the same (load a snapshot, adding line in configuration.yaml of zeroconf, check if all devices work in ewelink) and same results like you.  I wait for news in internet, I supose is an internal problem of HA.

**Comment by bertiebeez** [comment]
I just posted in the home assistant forum to see what they say.
https://community.home-assistant.io/t/issue-with-zeroconf-setup-now-sonoff-devices-are-unavailable/269607


Sent from Mail for Windows 10

**Comment by domoticaiescalbo** [comment]
Thank you very much, bertiebeez, we'll see.

**Comment by bertiebeez** [comment]
Did you do anything that triggered it? I did not do anything that I can remember. What I had noticed is that one of my heat mats that is plugged into a sonoff outlet stopped working. I then found the outlet was off. When I tried to turn it back on , I see all devices are now unavailable.  Alexa is not announcing my rain events either. And my newly installed AD2PI alarm system is not connected anymore either.

Sent from Mail for Windows 10

**Comment by domoticaiescalbo** [comment]
No, I didn't.  I only installed a new device (a shelly) and I noticed that
sonoff were unavailable.

**Comment by bertiebeez** [comment]
Read this page and then try to add the lines below to your configuration.yaml
It worked for me.

https://community.home-assistant.io/t/zeroconf-error/153883/4

zeroconf:
  default_interface: true



Sent from Mail for Windows 10

**Comment by gerthjan** [comment]
Hi, I had the same problem, sonoff devices not showing. The strange thing was that after restarting HA 3 or 4 times. They worked again.
Not really a technical sollution, but one worth trying maybe.

**Comment by bertiebeez** [comment]
I had re-booted numerous times. 
The fix was adding this to the configuration .yml
Zeroconf:
  default_interface: true


Sent from Mail for Windows 10

**Comment by AlexxIT** [comment]
If you has zeroconf error - you can try add this to config as said [here](https://github.com/AlexxIT/SonoffLAN/issues/350#issuecomment-761900597):

```
zeroconf:
  default_interface: true
```

In other cases - just use default config without `mode: local`.

**Comment by JiriKursky** [comment]
I played with that and devices disappeared totally.
What only helped is defined them with deviceid and devicekey.

**Comment by AlexxIT** [comment]
Probably not relevant in latest Hass versions
