### ISSUE TITLE
A little help pulling a part of a string from sqlite for Sonoff voltaje

### ISSUE THREAD

**Issue by guaro2k** [AlexxIT/SonoffLAN#355]
Im using DW2 WIFI and im pulling last state from the database. Got the states fo the doors and created a template.

For te battery is a little more complicated. It only outputs the voltage (3volt max) so here we go:

Im using this for the voltage percent:
- platform: template
    sensors:
      iron_door_battery:
        friendly_name: "iron_door_battery"
        unit_of_measurement: '%'
        value_template: "{{ (state_attr('binary_sensor.sonoff_1000e0e51a', 'battery')|float/0.03)|round(1) }}"
        icon_template: mdi:battery

Problem is, that it also goes away when the sensors go offline, so I went to sqlite to pull the last state also for the battery with this:

- name: Sonofflock_GetbatteryState
      query: "SELECT substr(attributes, instr(attributes, 'battery')+10,5) FROM states WHERE entity_id like '%binary_sensor.sonoff_1000e0e51a%' AND state NOT IN ('unavailable') ORDER BY Last_Updated desc LIMIT 1"
      column: 'attributes'

Now I've tried different string organization and I have tested it in the sqlite add-on and it pulls the voltage value, but when I go to the entity it says state unknown

Does anybody see what im doing wrong?

**Comment by AlexxIT** [comment]
Usual nobody loads data from db. It's wrong way. You need fix your device for persist online.

**Comment by guaro2k** [comment]
You mean change the device? those ones i think go offline to save battery

**Comment by AlexxIT** [comment]
Zigbee devices works without problem for years on one battery

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
