### ISSUE TITLE
The L1 lightstrips can only turn on/off one at the time

### ISSUE THREAD

**Issue by coffedahl** [AlexxIT/SonoffLAN#356]
Ive tested to put the lightstrips in groups and when i try turning on multiple lightstrips with one command the command only turn on one at a time... I have multiple other smart home devices that dosent have a problem with turning them on and off. I sadly dont have any more sonoff devices to try with, have tested setting the application to online only. I have successfully recreated the same error (i think) when i try to automate the strips to turn on and set the brightness at the same time...

**Comment by AlexxIT** [comment]
Duplicate #338
