### ISSUE TITLE
Sonoff S26 Support

### ISSUE THREAD

**Issue by tayakin** [AlexxIT/SonoffLAN#36]
Hai Allex.

Thanks for your work on this integration. It is so awesome for the newbies that did not have any background on programming and knowledge on PCB modification or hacking. 

This integration gives me a great relived due to no heavy programming and modification but I found that there is no Sonoff S26 device supported on the detail description or guide.

It is very helpful that you can provide the additional S26 device into the supported list.

Best regard.

**Comment by AlexxIT** [comment]
What version of firmware?

**Comment by rhgiter** [comment]
it works with s26     (firmware3)

you have done a really good job ..THANKS

**Comment by AlexxIT** [comment]
Thanks, I will add to the list of tested. 👍
