### ISSUE TITLE
DUALR2

### ISSUE THREAD

**Issue by shummo** [AlexxIT/SonoffLAN#360]
Hi. I would like to ask, if the SONOFF DUALR2 will have integration?

I tried to add it to the HA, but unfortunatelly  it wasn't succesfull.
I don't see this entities.

**Comment by AlexxIT** [comment]
I think this model already supported

**Comment by shummo** [comment]
I tried it more time. I delete the sonoff.json. After that the knew dualr2 not showed.

I saw only the dual in the list, dualr2 not. 
Maybe user error. I just want to be sure.
