### ISSUE TITLE
Unable to update status from device

### ISSUE THREAD

**Issue by pothirak** [AlexxIT/SonoffLAN#369]
Logger: root
Source: custom_components/sonoff/sonoff_local.py:178
First occurred: 5:22:12 AM (1 occurrences)
Last logged: 5:22:12 AM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1755, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1513, in fire
    h(**kwargs)
  File "/config/custom_components/sonoff/sonoff_local.py", line 178, in _zeroconf_handler
    if data.startswith(b'{"rf'):
AttributeError: 'NoneType' object has no attribute 'startswith'

Additional information
core-2021.2.1
Home Assistant OS 5.10

my configuration
sonoff:
  username: !secret mail_ewelink
  password: !secret pass_ewelink
  mode: local
  force_update: [temperature, power]
  sensors: [temperature, humidity, power, current, voltage]

**Comment by pothirak** [comment]
I tried downgrading the core version to 2021.1.5 There is still a problem

**Comment by pothirak** [comment]
I solved the problem
I deleted the files in the folder custom_components / sonoff Then clone the files from the hub to place them instead.
And I also deleted the .sonoff.json file in the custom_components folder, after removing the file, restart HA.

Additional: Sonoff Micro firmware version 3.7.1 cannot use Lan Control.

**Comment by AlexxIT** [comment]
It fixed in latest beta
