### ISSUE TITLE
Sonoff RF Bridge 433

### ISSUE THREAD

**Issue by ranski1999** [AlexxIT/SonoffLAN#37]
Hi Allex, thank you for working on the integration it is awesome.  I not getting the RF Bridge 433 . I have  3 RF plugs and they are in the ewelink app. I can see the   ( sonoff.remote )   in home assistant. am I be able to make a on and off switch for them in home assistant or a door sensor.

**Comment by AlexxIT** [comment]
You can receive signals from RF Buttons and RF Sensors through an event sonoff.remote. And send signals using the service remote.send_command.

It is written in readme.

**Comment by evilone68** [comment]
hi also having problems with rf bridge 
I can manually send event sonoff.remote but where do I get answer to this from?

**Comment by gsdovali** [comment]
Hello Alex; I am trying to use your component, but I can't figure out how to use my door/windows Sensors; I want them to be shown as binay_sensors on home assistant and be able to use them on my Alarm, if they open, then fire up the alarm if it is armed. 
I can see the events when my sensors open/close but is there a way to use them as binary sensors?

**Comment by AlexxIT** [comment]
@gsdovali they don't have "off" signal, only "on" signal. How they can be a sensor?

**Comment by evilone68** [comment]
If any one is still struggling have a look at this video
https://youtu.be/QD1K7s01cak
