### ISSUE TITLE
Flashing WiFi Sign on Devices

### ISSUE THREAD

**Issue by colethegamer123** [AlexxIT/SonoffLAN#377]
Hello again Alex,

This is only a question, after the answer you can close it of course.

I would like to ask is it possible to somehow disable the blinking LED on the devices to avoid the LED blinking the whole day when using it in LOCAL mode? If I turn off in ewelink it doesnt matter, if I disable Internet Access it will blink again.

Im using Sonoff Light Switches and Sonoff Smart Plugs. 
On the Light Switches there is a blue WiFi sign what is blinking with blue light.
On the Smart Plugs there is a Green button what is blinking between red/green light.

I dont really want to solder out the LEDs, if its not necessary.

Thank you very much as always :)
Have a nice day.

**Comment by AlexxIT** [comment]
![image](https://user-images.githubusercontent.com/511909/107686005-b8c91b80-6cb5-11eb-9c23-8ec9568f75cf.png)

**Comment by colethegamer123** [comment]
You are the best!

**Comment by AlexxIT** [comment]
I don't know if it works with disabled Internet. But it works with usual Internet.

**Comment by colethegamer123** [comment]
It does not work :( Im asking because if its not possible with the integration everybody has to desolder the leds, because its really annoying with a light switch for example.

**Comment by AlexxIT** [comment]
I have tried with my sonoff mini with usual Internet. So it led is on all the time. And this command works with it.

**Comment by colethegamer123** [comment]
Yes with internet is working, but with local mode its not :( Thanks for your comments. What do you think will be it possible in the future do make this work with local mode? so we can turn off cloud mode.

**Comment by AlexxIT** [comment]
I don't think it possible with default sonoff firmware. You may flash it, if you want not default behavior of this devices.
