### ISSUE TITLE
S31 Switch Working but no Powe/Current/Voltage reported

### ISSUE THREAD

**Issue by johnjoemorgan** [AlexxIT/SonoffLAN#38]
[S31.txt](https://github.com/AlexxIT/SonoffLAN/files/4234910/S31.txt)

Config.yaml:

sonoff:
  username: johndoe@gmail.com
  password: johndoe@washere.com
  reload: always 

Switch loads and is available soon after HAS reboot but no sensor data is seen in the logs and no sensors can be created.

Note: S31 sensor data can be seen and used with the  peterbuga/HASS-sonoff-ewelink component

**Comment by AlexxIT** [comment]
In this component, sensors are not created automatically. Use template sensor.
