### ISSUE TITLE
Zigbee Bridge in local mode ?

### ISSUE THREAD

**Issue by raulddan** [AlexxIT/SonoffLAN#385]
Any chance we will be spoiled in the future with local mode for Zigbee bridge ?
Thanks Alex,
Best regards

**Comment by AlexxIT** [comment]
This depends on itead developers. I can't do anything if firmware don't support local mode.

You can flash this gateway with Tasmota. Or buy cc2531 from sonoff. Or buy Xiaomi Gateway 3 from Xiaomi.

**Comment by raulddan** [comment]
Thanks Alex for your quick reply. I think that the best solution from those listed is a tasmotized bixbee bridge. I really like the sonoff design of the bridge rather then the cc2531.

**Comment by AlexxIT** [comment]
For now I'm using Xiaomi Gateway 3 + Sonoff cc2531
