### ISSUE TITLE
Enhancement :: https://eu-api.coolkit.cc:8080/ is no longer working with me

### ISSUE THREAD

**Issue by OriginalCREart** [AlexxIT/SonoffLAN#386]
Hi,

https://eu-api.coolkit.cc:8080/ is no longer working with me, but when tried to https://eu-api.coolkit.cc/ without port, it worked and my devices in sync again.

![image](https://user-images.githubusercontent.com/34885143/107881163-c4058c80-6eeb-11eb-871b-30b6aeb7b72a.png)

BTW, this causes a slowness to my HA instance after restart.

Can we have this URL as a configuration?

Finally, thank you for this integration. It is definitely brilliant.

Regards.

**Comment by AlexxIT** [comment]
What is your country? And what is country of your server in ewelink app?

**Comment by coelholm** [comment]
Same issue here. I have used +55 when I created my account.  Remove :8080 made it discover devices and create the .sonoff.json.

**Comment by OriginalCREart** [comment]
> What is your country? And what is country of your server in ewelink app?

My country is Jordan. And for the server's country in ewelink app, I cannot determine how to get it!

**Comment by coelholm** [comment]
I have same issue here. I did some tests and looks like there are some ranges of ips (CIDR) been blocked.  From my home network I can't connect, from both HA and eWeLink, but is I switch to 4G network it works. I believe it is a block rule on their side, because it is possible to open connections to different port at eu-api.coolkit.cc.

**Comment by Cippo2019** [comment]
HI @AlexxIT 
in case of problem do you suggest to rename _baseurl value as indicated in that forum right ?
is this conf in file sonoff_cloud.py only right ?
In that file I see reference to port 8080 in 4 line.. 
should we change all 4 or just as indicated in the line at the beginning of this post?
and of course we need to restart HA .

wbr
Tz

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
