### ISSUE TITLE
Can I convert 1000e3fecf to 'valve_two' type with twoSwitch?

### ISSUE THREAD

**Issue by mikeinblue** [AlexxIT/SonoffLAN#397]
hi，Alex. Thank for the nice job. Recently, I need a valve to put into my homekit. So I am wondering if you can help me. Thanx again.

**Comment by AlexxIT** [comment]
I don't understand what you trying to do

**Comment by mikeinblue** [comment]
![Screenshot_20210222-231446](https://user-images.githubusercontent.com/62834868/108727749-daeb5500-7563-11eb-8670-810565c326eb.jpg)
can yiu understand?I am trying simulate a sonoff swith into a 'valve' then connect to my homekit.

**Comment by bwp91** [comment]
Looks like this is an “issue” for the homebridge-ewelink page, not this page.

Also, @mikeinblue in your screenshot you have unfortunately exposed some sensitive information at the top. Perhaps a change of password is needed?

**Comment by AlexxIT** [comment]
Thanks @bwp91.

This issue not about this component.
