### ISSUE TITLE
Q-touch WIFI dimmer switch

### ISSUE THREAD

**Issue by dastamu** [AlexxIT/SonoffLAN#398]
Hi,

I have wireless WIFI dimmer switch LX-WIFI-03O(EU) manufacturer by KFJIA branded by Q-touch with sw_version="PSF-BTA-GL v3.4.0" in app eWeLink works well.

But in HA with custom_components AlexxIT/SonoffLAN :) I can only turn off switch, I can't turn on and dimm.

I noticed that in dev services from "sonoff.send_command" it's not working good sending commands: "bright: 0" and "switch: 'on/off'" together in one message.

From logs shows that In app eWeLink or from device this commands are sent separately.

The logs also show that my switch is using 'uiid=36' so in source file 'light.py' class SonoffDimmer is used to serve this switch, so when on ending of class I changed the line from:

`await self.registry.send(self.deviceid, {'switch': 'on', 'bright': br})`

to two lines:

`await self.registry.send(self.deviceid, {'switch': 'on'})`
`await self.registry.send(self.deviceid, {'bright': br})`

that it's works better :)

I don't know why the commands 'switch' and 'bright' cannot be sent together in one message.

BR

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
