### ISSUE TITLE
Sonoff DualR3 support - any plans

### ISSUE THREAD

**Issue by ksiwy87** [AlexxIT/SonoffLAN#399]
Hello,

Thank you for a great work!

Are you planning to add a support for a new Sonoff DualR3?

**Comment by AlexxIT** [comment]
Do you have it?

**Comment by lucoluco** [comment]
Hello, if it can help, I have one Dual R3

**Comment by ksiwy87** [comment]
Right now I am waiting for shipping. I've ordered 2 DualR3's.

**Comment by AlexxIT** [comment]
@lucoluco is it works fine?

**Comment by lucoluco** [comment]
> @lucoluco is it works fine?

I received it yesterday, I just enrolled to ewelink and now I have to test it, it would be great if you can make it works in HA...

Anyway Thank you for your work!

**Comment by AlexxIT** [comment]
I think it should work without any update to component

**Comment by ksiwy87** [comment]
I will also test it once I receive a package.

**Comment by lucoluco** [comment]
I can see it in sonoff.json

"brandName":"SONOFF","showBrand":true,"brandLogoUrl":"https://eu-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png","productModel":"DUALR3","devConfig":{},"uiid":126}}

but I cannot see any new entity in HA

**Comment by AlexxIT** [comment]
Show full info from json about this device. You can hide all private data.

**Comment by lucoluco** [comment]
[DUALR3.txt](https://github.com/AlexxIT/SonoffLAN/files/6048931/DUALR3.txt)

**Comment by AlexxIT** [comment]
Try to search `1001220163` in entities list. There should be 4 entity.

**Comment by lucoluco** [comment]
sorry cannot find nothing
![image](https://user-images.githubusercontent.com/31472304/109317571-209e6b00-784d-11eb-83bf-472228b29ff7.png)

**Comment by lucoluco** [comment]
after some restarts now I can see 3 entities: 2 switch and 1 binary sensor, but added toa card they are unusable. The DUALR3 is configured as motor.
I tried also to configure it as switch and in that case I see 4 switches entity, but I can use just two to control the two relais.

**Comment by AlexxIT** [comment]
What do you mean "configured as motor"?

**Comment by ksiwy87** [comment]
DualR3 can be configured as a "Motor" (to control roller shutter) and as a switch (for standard double switch).

**Comment by AlexxIT** [comment]
Please show `sonoff.json` when R3 configures as motor. Delete this file before Hass restart to ensure if it loaded again.

**Comment by lucoluco** [comment]
the file I attached was already in motor mode, anyway i deleted .sonoff.json and rebooted HA.
Here you are.
[DUALR3motor.txt](https://github.com/AlexxIT/SonoffLAN/files/6054227/DUALR3motor.txt)

**Comment by AlexxIT** [comment]
This device should shown as 4 entities/switches. And after my fix it should shown as 2 entities/switches.

**Comment by lucoluco** [comment]
ok it works as a 2 way switch, but is there any plan to use it as roller shutter controller, just like a shelly2.5?
Thank you.

**Comment by shummo** [comment]
I only have the binary entity. :(

**Comment by bob-tm** [comment]
Dualr3 is discovered, but switch states not syncing. When I click switch in HA it turns on for several seconds and then back to off (visual, because state reported off). Switch state always reported off. 

The same thing with s26 socket. 

I'm using latest HA version and Latest Master version.
On 2.4b1 syncing is working for s26, but dualr3 channels is not discovered.

**Comment by AlexxIT** [comment]
@bob-tm show your config

**Comment by bob-tm** [comment]
sonoff:
  username: xxxx
  password: xxxx
  mode: local
  reload: always  # update device list every time HA starts

it's strange, but I installed master again (after 2.4b1) and now all works as expected. 

[master.sonoff.txt](https://github.com/AlexxIT/SonoffLAN/files/6108413/master.sonoff.txt)
[2.4b1_sonoff.txt](https://github.com/AlexxIT/SonoffLAN/files/6108414/2.4b1_sonoff.txt)

**Comment by AlexxIT** [comment]
@bob-tm you have some problems with local network config. I have added warning to this situation in latest master version

**Comment by marianobntz** [comment]
`  {
    "settings": {
      "opsNotify": 0,
      "opsHistory": 1,
      "alarmNotify": 1,
      "wxAlarmNotify": 0,
      "wxOpsNotify": 0,
      "wxDoorbellNotify": 0,
      "appDoorbellNotify": 1
    },
    "group": "",
    "online": true,
    "groups": [],
    "devGroups": [
      {
        "groupId": "DDD",
        "type": 1
      }
    ],
    "relational": [],
    "name": "Velador Mariano",
    "type": "10",
    "extra": {
      "extra": {
        "uiid": 103,
        "description": "20200921003",
        "brandId": "5c4c1aee3a7d24c7100be054",
        "modelInfo": "5e7a146548af4f7140874c8e",
        "model": "WTW-SNL-02",
        "manufacturer": "深圳松诺技术有限公司"
      },
      "_id": "XXXx"
    },
    "params": {
      "bindInfos": {
        "gaction": [
          "XXXX"
        ],
        "alexa": [
          "XXXX"
        ]
      },
      "version": 7,
      "switch": "off",
      "ltype": "nightLight",
      "white": {
        "br": 21,
        "ct": 125
      },
      "fwVersion": "1.3.2",
      "sequence": "123456789",
      "selfApikey": "",
      "read": {
        "br": 50,
        "ct": 0
      },
      "nightLight": {
        "br": 5,
        "ct": 0
      },
      "state": "off",
      "computer": {
        "br": 20,
        "ct": 255
      },
      "bright": {
        "br": 100,
        "ct": 255
      }
    },
    "createdAt": "2021-02-01T13:34:45.576Z",
    "__v": 0,
    "onlineTime": "2021-03-10T12:39:27.874Z",
    "ip": "181.166.92.212",
    "location": "",
    "offlineTime": "2021-03-10T11:42:18.366Z",
    "deviceUrl": "",
    "brandName": "SONOFF",
    "showBrand": true,
    "brandLogoUrl": "https://us-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png",
    "productModel": "B02",
    "devConfig": {},
    "uiid": 103
  }
`

**Comment by zigomatichub** [comment]
Hello, I just receive the DualR3 and I'm interested by keeping the original firmware as there is this :http://developers.sonoff.tech/sonoff-diy-mode-api-protocol.html

My question are:  
This sonoffLan is using this API ?
To be able to manage the device under HA, what is the best solution ? 

FYI: My switches are momentary switch to command the lamp and I saw a solution with this device. So I will do some experimentation.

**Comment by bob-tm** [comment]
For simple turn on/off it works really good with this integration. No problems from last release. 
But If you want to remap buttons,  long press, double click, and other features - I'm waiting when sonoff releases DIY enabled firmware for DualR3 and will flash tasmota over wifi, like I do with sonoff mini :)

**Comment by zigomatichub** [comment]
@bob-tm I don't understand your sentence "waiting when sonoff releases DIY enabled firmware for DualR3" 
and "will flash tasmota over wifi".  
DIY enabled firmware is available with may be not all features as you mention.
If you put tasmota, you flash completely the official firmware. You can may be do it if you open the device and find all pins needed. On tasmota project, I didn't see yet a support of this device. I didn't open yet the device to look into it but I found some info (ESP32 inside) https://youtu.be/qQ9Pxl4KAGw?t=426

**Comment by zigomatichub** [comment]
@AlexxIT 
After integrate into HA. I see some issues with configuration as momentary switch (switch with trigger Pulse mode in ewelink).
HA don't keep the state of the lamp where it's kept in Ewelink.

**Comment by AlexxIT** [comment]
@zigomatichub I don't understand problem

**Comment by ksiwy87** [comment]
I've got mine. I've configured it in Motor Mode (for roller shutter) and it doesn't work. HA detects it as simple 2 switches - when I press it - it doesnt do anything.

**Comment by ksiwy87** [comment]
Okay - I have set device_class to "cover" and now the entity shows properly, but it still not responding to any action.

**Comment by zigomatichub** [comment]
> @zigomatichub I don't understand problem

Real switch are push-button like. Normaly open - Normaly close - Normaly open are the 3 states to have the lamp ON.
In this configuration, the integration is not working. The lamp state is HA is ON and go to OFF after some seconds where the lamp is still ON.

**Comment by MPinto55** [comment]
@AlexxIT 
![Sonoff Dual R2](https://user-images.githubusercontent.com/78357655/111529466-1a1f5700-875a-11eb-994c-35e2d1709caf.jpg)
Thank you very much for your work. I have several sonoff mini R2 working perfectly.
I just installed 2 sonoff duall R3 as a shutter, and I have exactly the same problem reported by @Ksiwy87.
Each appears as 2 switches and not as a shutter, and does not communicate with the module.

**Comment by AlexxIT** [comment]
Shutter mode don't supported for this model. You can share it to my ewelink account sonofflan@gmail.com. I'll see what I can do when I have some free time

**Comment by MPinto55** [comment]
Thank you very much.
shared as requested.

I set up another Sonoff Dual R3 as a light switch to test, and it works perfectly. I also shared this with you.

Thanks again

**Comment by fr33soul** [comment]
> Shutter mode don't supported for this model. You can share it to my ewelink account [sonofflan@gmail.com](mailto:sonofflan@gmail.com). I'll see what I can do when I have some free time

i am also interested in shutter mode! I will buy some R3 just for that purpose..

**Comment by ksiwy87** [comment]
@AlexxIT - did you managed to look at this issue? It will be fantastic when we will be able to connect R3 in roller shutter mode.

**Comment by AlexxIT** [comment]
Not yet. Check my github. I have a lot of components. Should spend time to all of them...

**Comment by zigomatichub** [comment]
For the shutter mode, I switched to tasmota, all works great.

**Comment by fr33soul** [comment]
> Not yet. Check my github. I have a lot of components. Should spend time to all of them...

can i support you with a donation to achive shutter mode?!

**Comment by alnavasa** [comment]
> Shutter mode don't supported for this model. You can share it to my ewelink account [sonofflan@gmail.com](mailto:sonofflan@gmail.com). I'll see what I can do when I have some free time

I'll wet one son off R3 I currently have laying around and share it with you so you can achieve the cover setup, I have that one mind for next month.

**Comment by jbarranca** [comment]
Hi Alex. Thanks for your great work.
I have 3 DualR3 working as Meter and none of them shows up on HA as sensors. All as switch and that is not what i need.

Any help will be appreciated.

**Comment by vramich** [comment]
Thank you very much for your work. I just installed 2 sonoff duallR3 as a shutter, and I have same problem as @ksiwy87 and @MPinto55. 

Очень очень хочется управлять им из HA. 
Спасибо

**Comment by ksiwy87** [comment]
@AlexxIT - there will be a lot of people which will use DualR3 as roller shutter, because of his price and small size. When it will be publicly available you will have a lot more requests :)
When are you planning to look at this?

**Comment by marcoevcom** [comment]
There is something else that I noticed.  The Dual R3 has power monitoring, and the values are not available through this integration.

**Comment by ksiwy87** [comment]
@AlexxIT - is there any news in our case?

**Comment by fr33soul** [comment]
> @AlexxIT - is there any news in our case?

no sign of life..

**Comment by fr33soul** [comment]
@AlexxIT bought some coffe for improving the DualR3 shutter mode and power measuring! https://www.buymeacoffee.com/AlexxIT

**Comment by bwp91** [comment]
With regards to the shutter mode, perhaps I can add some input.

When the device is in shutter mode, `params.workMode == 2`.

The device needs to be already calibrated for the following to work:

`params.currLocation` provides the current location as an integer between `0` and `100`, `0` being fully closed and `100` being fully open.

You can send `params.location` (again, integer between `0` and `100`) to set a target location. Whilst the device is moving, ewelink will send the new `params.currLocation` every few seconds, and when the shutter has reached the target location, ewelink will send both `params.location` and `params.currLocation` together in one web socket message (they will obviously be the same value).

Another param of interest is `params.motorTurn` (integer) 1==OPENING, 0==STOP, 2==CLOSING. But i'm not sure if this is a param that can be sent to ewelink to control the device. Perhaps it is just a param that ewelink sends as informative.

Perhaps this could help. I have managed to implement this shutter mode into my homebridge plugin using just `params.workMode`, `params.location` and `params.currLocation`.

**Comment by AlexxIT** [comment]
@bwp91 thanks for docs
@MPinto55 thank for sharing device, I played with it for a while
@fr33soul thanks for coffee

You can check cover mode in latest master version. You can install it with HACS reinstall option

**Comment by fr33soul** [comment]
@AlexxIT for cover Mode you mean shutter? What about the other parameters current location as mentioned by @bwp91 and power measuring? I hope you will improve those!

**Comment by AlexxIT** [comment]
@fr33soul what about current location? Component already uses it.

**Comment by ksiwy87** [comment]
@AlexxIT - thanks, but It still detects it as a dual switch.

**Comment by ksiwy87** [comment]
I had an update of Sonoff LAN today and it stopped working. HA can read the status (opened/closed), but I cannot open nor close the cover from lovelance:
![image](https://user-images.githubusercontent.com/72941699/118032741-4c1ef500-b368-11eb-8b38-2a7457ca5218.png)

**Comment by paulius2k** [comment]
@AlexxIT thank you for the new version of the integration!

I have the same issue as @ksiwy87 - I can see the status of the cover when it is being controlled from the eWeLink app, but there are no buttons to open/close/stop from Lovelace:

<img src="https://user-images.githubusercontent.com/24705262/118156276-d9725000-b421-11eb-91d7-980aebf4b0bb.png" width="50%" height="50%">

Should I change something in the `.sonoff.json`?

**Comment by alnavasa** [comment]
I currently have it working, though my awing is collapsed when its is up and extended when it is down. Is there a way to reverse the arrows? is this more of a HA issue to solve. In the ewe link it looks properly. It is just that it is "closed" when it is up. And to "open" it, arrow should point down

**Comment by ksiwy87** [comment]
I've updated to 2.4.6 and now it's working fine.

**Comment by dmutpuul** [comment]
@AlexxIT  Hello. I want to order dualR3, is it supported by your integration at this moment ? I mean current, power, voltage  sensor + 2 switch ? or that enhancement in future plans ?

**Comment by AlexxIT** [comment]
Current, power and voltage doesn't supported yet.

**Comment by paulius2k** [comment]
@dmutpuul - I am using the Sonoff DualR3 with AlexxIT integration for my shades and I must say I like it more than Shelly 2.5 for one reason - it shows the actual progress of the motion of shades/cover: i.e. it changes in real-time 0-->2-->5-->7-->etc. I am not sure if this is the merit of AlexxIT's integration or the DualR3 unit itself though.

**Comment by AlexxIT** [comment]
This is the merit of both :)
R3 has target value and current value. I decided use current value. Because Hass can show only one of them.

**Comment by shummo** [comment]
Is there any info about dual r3 power/current consumption support?
I would be really happy, if i can check this, because I can only set an input_boolean for ON/OFF status with current check.
Thanks

**Comment by AlexxIT** [comment]
You can try to use this code before I implement it in main version
https://github.com/AlexxIT/SonoffLAN/pull/506

**Comment by AlexxIT** [comment]
Dual R3 power data in latest master version

**Comment by dmitkam** [comment]
Updates data (power, curren, voltage, rssi) tonly after HA reboot. After the data is not updated.

**Comment by lnpbr** [comment]
Using latest version, but (power, voltage, current) values do not update.

**Comment by seppelw** [comment]
> Using latest version, but (power, voltage, current) values do not update.

You need to use the master, not the latest version :-( however for me it's not working correctly. It creates the sensors but only updates them every now and then.

**Comment by lnpbr** [comment]
> > Using latest version, but (power, voltage, current) values do not update.
> 
> You need to use the master, not the latest version :-( however for me it's not working correctly. It creates the sensors but only updates them every now and then.

I'm using the last one, named as "Adds power data to Dual R3". I've downloaded all the sonoff directory and replaced the one in my Hassio.

Just show the first measurement. If I plug it to 127v and later to 220v, it stucks showing 127v and no other updates.

What's the update interval are you getting in your ha? 

Thanks.

**Comment by Protoncek** [comment]
Hello!
My dual also doesn't update any data... using master version. 
contents of configuration.yaml is:
`sonoff:
  username: pavel.veider@gmail.compassword: Lory6pes.
  reload: always
  force_update: [power, current, voltage]
  scan_interval: "00:01:00" # (optional) default 5 minutes
  sensors: [power, current, voltage]`
> sonoff:
    username: xxxx
    password: yyyy
    reload: always
    force_update: [power, current, voltage]
    scan_interval: "00:01:00" # (optional) default 5 minutes
    sensors: [power, current, voltage]

**Comment by bwp91** [comment]
(i’d advise changing your ewelink password immediately!)

**Comment by Protoncek** [comment]
hm...my password is not "yyyy", if that's what you mean,  that's only my way of masking real password...  or did i miss something?

**Comment by lnpbr** [comment]
> hm...my password is not "yyyy", neither is my username "xxxx", if that's what you mean, that's only my way of masking real password... or did i miss something?

We are able to see your password in the history, so, change it.

**Comment by Protoncek** [comment]
oh... that "mistake" i made by accidentally hitting "publish" when i tried to input code in correct form... ok, many thanks for warning. It's already changed.

**Comment by lnpbr** [comment]
> Hello!
> My dual also doesn't update any data... using master version.
> contents of configuration.yaml is:
> 
> > sonoff:
> >   username: xxxx
> >   password: yyyy
> >   reload: always
> >   force_update: [power, current, voltage]
> >   scan_interval: "00:01:00" # (optional) default 5 minutes
> >   sensors: [power, current, voltage]

I’m using the same configuration, probably it’s necessary some code improvement to support dual r3. POWR2 updates all the data instantly.

**Comment by bwp91** [comment]
> oh... that "mistake" i made by accidentally hitting "publish" when i tried to input code in correct form... ok, many thanks for warning. It's already changed.
> EDIT: i also deleted my first post above... if it helps....

Because… even if you edit a comment on here, anyone can still see the original comment and history of edits 😬

**Comment by Protoncek** [comment]
Yeah, i didn't know that...  thanks again for warning!

**Comment by AlexxIT** [comment]
Power measurement fixed in latest master

**Comment by lnpbr** [comment]
> Power measurement fixed in latest master

Great, it's working perfectly now, like POW R2.
I had the opportunity to test the POW R3, it appear to be working, as well.

Thanks a lot for this.

**Comment by neilhowieson** [comment]
> > Power measurement fixed in latest master
> 
> Great, it's working perfectly now, like POW R2.
> I had the opportunity to test the POW R3, it appear to be working, as well.
> 
> Thanks a lot for this.

Could you share your configuration.yaml? I have installed the latest master, but i am only getting a reading on HA startup. Does the Dual R3 need to be in "Meter" working mode, or can I leave it in switch mode?

**Comment by lnpbr** [comment]
> > > Power measurement fixed in latest master
> > 
> > 
> > Great, it's working perfectly now, like POW R2.
> > I had the opportunity to test the POW R3, it appear to be working, as well.
> > Thanks a lot for this.
> 
> Could you share your configuration.yaml? I have installed the latest master, but i am only getting a reading on HA startup. Does the Dual R3 need to be in "Meter" working mode, or can I leave it in switch mode?
> 
> My configuration.yaml is below:
> 
> ```
> sonoff:
>   username: username@username.com
>   password: pw
>   force_update: [power, current, voltage]
>   scan_interval: "00:01:00"
>   sensors: [power, current, voltage]
> ```

I’m using the standard configuration, like yours.
But I added “reload: always” and deleted the file “/config/.sonoff.json” before restart home assistant. After restart you can remove the config “reload: always”

Click to check configuration before restart to avoid problem.

About Dual R3, you can use SWITCH MODE, it works well. That’s the mode I’ve tested here.

**Comment by neilhowieson** [comment]
> > > > Power measurement fixed in latest master
> > > 
> > > 
> > > Great, it's working perfectly now, like POW R2.
> > > I had the opportunity to test the POW R3, it appear to be working, as well.
> > > Thanks a lot for this.
> > 
> > 
> > Could you share your configuration.yaml? I have installed the latest master, but i am only getting a reading on HA startup. Does the Dual R3 need to be in "Meter" working mode, or can I leave it in switch mode?
> > My configuration.yaml is below:
> > ```
> > sonoff:
> >   username: username@username.com
> >   password: pw
> >   force_update: [power, current, voltage]
> >   scan_interval: "00:01:00"
> >   sensors: [power, current, voltage]
> > ```
> 
> I’m using the standard configuration, like yours.
> I noted you are using “00:01:00” instead ‘00:01:00’ (double quotes instead single ones).
> 
> I added “reload: always” and deleted the file “/config/.sonoff.json” before restart home assistant. After restart you can remove the config “reload: always”
> 
> Click to check configuration before restart to avoid problem.
> 
> About Dual R3, you can use SWITCH MODE, it works well. That’s the mode I’ve tested here.

I added "reload: always", deleted the .sonoff.json file, changed the quotes to singles and rebooted and no luck. Power and Current Sensors remain at 0 for both channels, and voltage is static.

**Comment by lnpbr** [comment]
> > > > > Power measurement fixed in latest master
> > > > 
> > > > 
> > > > Great, it's working perfectly now, like POW R2.
> > > > I had the opportunity to test the POW R3, it appear to be working, as well.
> > > > Thanks a lot for this.
> > > 
> > > 
> > > Could you share your configuration.yaml? I have installed the latest master, but i am only getting a reading on HA startup. Does the Dual R3 need to be in "Meter" working mode, or can I leave it in switch mode?
> > > My configuration.yaml is below:
> > > ```
> > > sonoff:
> > >   username: username@username.com
> > >   password: pw
> > >   force_update: [power, current, voltage]
> > >   scan_interval: "00:01:00"
> > >   sensors: [power, current, voltage]
> > > ```
> > 
> > 
> > I’m using the standard configuration, like yours.
> > I noted you are using “00:01:00” instead ‘00:01:00’ (double quotes instead single ones).
> > I added “reload: always” and deleted the file “/config/.sonoff.json” before restart home assistant. After restart you can remove the config “reload: always”
> > Click to check configuration before restart to avoid problem.
> > About Dual R3, you can use SWITCH MODE, it works well. That’s the mode I’ve tested here.
> 
> I added "reload: always", deleted the .sonoff.json file, changed the quotes to singles and rebooted and no luck. Power and Current Sensors remain at 0 for both channels, and voltage is static.

Hi, you are right.

I found it update only when open the power information in eWeLink, then, the data update on eWeLink and update in Home Assistant at the same time.

So, in summary, it only update in Home Assistant if keep eWeLink opened.

In fact, not working like POW R2.

**Comment by andreabaroni** [comment]
> I currently have it working, though my awing is collapsed when its is up and extended when it is down. Is there a way to reverse the arrows? is this more of a HA issue to solve. In the ewe link it looks properly. It is just that it is "closed" when it is up. And to "open" it, arrow should point down

Any news on that ?

**Comment by evaliukonis** [comment]
How to get consumption from DualR3?

**Comment by Simonz82** [comment]
news for DUAL R3 ? is impossibile read WATT in lovelace ?
thanks

**Comment by gnicita** [comment]
Hi AlexxIT

A huge THANK YOU for developing this SONOFF suit. To support DualR3 in cover mode, it doesn't work correctly as it sees me 2 swich (xxxxx_3, xxxxx_4) am I can't control them. The version is v2.4.6. I enclose a copy of the json.

Thank a lot Giuseppe
[DualR3 JSON.txt](https://github.com/AlexxIT/SonoffLAN/files/7807485/DualR3.JSON.txt)

**Comment by gnicita** [comment]
This is log error: 
2022-01-04 17:14:21 WARNING (MainThread) [custom_components.sonoff.sonoff_local] 10014924fc => Local4 | {'switches': [{'outlet': 2, 'switch': 'on'}]} <= {'sequence': '', 'seq': 301, 'error': 400, 'encrypt': True}
2022-01-04 17:17:09 WARNING (MainThread) [custom_components.sonoff.sonoff_local] 10014924fc => Local4 | {'switches': [{'outlet': 3, 'switch': 'on'}]} <= {'sequence': '', 'seq': 301, 'error': 400, 'encrypt': True}

**Comment by voron** [comment]
Is anyone aware of Zero Cross Detection Support on a stock firmware of DualR3?

**Comment by EvilItalianK** [comment]
Trying to set on the entity "device_class: shutter" (to change the icon depending on the position of the shutter) seems to crash the extension:

`2022-03-11 00:53:52 DEBUG (MainThread) [custom_components.sonoff.sonoff_cloud] Start refresh task for 1 POW
2022-03-11 00:53:52 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=sonoff, service=update_consumption>
2022-03-11 00:53:52 INFO (MainThread) [homeassistant.setup] Setup of domain sonoff took 2.8 seconds
2022-03-11 00:53:52 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=sonoff>
2022-03-11 00:53:52 INFO (MainThread) [homeassistant.components.cover] Setting up cover.sonoff
2022-03-11 00:53:52 INFO (MainThread) [homeassistant.components.cover] Setting up cover.sonoff
2022-03-11 00:53:52 DEBUG (MainThread) [homeassistant.bootstrap] Waiting for startup to wrap up
2022-03-11 00:53:52 ERROR (MainThread) [homeassistant.setup] Setup failed for shutter: Integration not found.
2022-03-11 00:53:52 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; title=Invalid config, friendly_name=Invalid config, message=The following integrations and platforms could not be set up:
- shutter
Please check your config and [logs](/config/logs). @ 2022-03-11T00:53:52.493800+01:00>>
2022-03-11 00:53:52 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event persistent_notifications_updated[L]>
2022-03-11 00:53:52 DEBUG (MainThread) [zeroconf] offsets = questions=0, answers=0, authorities=0, additionals=0
2022-03-11 00:53:52 DEBUG (MainThread) [zeroconf] lengths = questions=1, answers=0, authorities=0, additionals=0
2022-03-11 00:53:52 DEBUG (MainThread) [zeroconf] now offsets = questions=1, answers=0, authorities=0, additionals=0`

Config used:

`username: me@gmail.com
password: mypassword
devices:
  yadayada:
    device_class: shutter`

**Comment by AlexxIT** [comment]
You shouldn't use `device_class: shutter`. It's not supported

**Comment by benjR** [comment]
hello! just tried to setup a freshly received dualr3 (configured in motor mode and inverted in the ewelink app)), unfortunately it crashes home assistant when using the switches through HA, did nothing fancy yet, just username/password in the config.

**Comment by AlexxIT** [comment]
Probably device should work fine in latest master-version

**Comment by AlexxIT** [comment]
@EvilItalianK `device_class: shutter` supported in latest master-version

**Comment by MartynEnova** [comment]
I have problem connecting my Sonoff Dual R3. For some reason I cannot make scenes with the dual R3 on the eWeLink Web, but I can make scenes on the mobile app. I can also not pick up the Dual R3 on the HA I made following your instructions (I can pick up a MINIR3, so I believe the HA works).
Any help would be appreciated.
