### ISSUE TITLE
Can I use this without HASS.IO?

### ISSUE THREAD

**Issue by agoralive** [AlexxIT/SonoffLAN#40]
How do I set this up without Hass.io?

**Comment by crozo5** [comment]
> How do I set this up without Hass.io?

yes, install HACS

**Comment by AlexxIT** [comment]
@agoralive what would you like? Install on a regular Home Assistant?

**Comment by agoralive** [comment]
I use node-red for my home automation, and I do not use HASS but "just" MQTT via Mosquitto. So I would like to run it without having to install HASS.io

**Comment by AlexxIT** [comment]
This code won't work without HA
