### ISSUE TITLE
Удаленная перезагрузка роутера (Remote reboot of the router)

### ISSUE THREAD

**Issue by sergey-1976** [AlexxIT/SonoffLAN#402]
Спасибо за супер компонент.

У меня mini стоит перед роутером. Для удаленной перезагрузки роутера использую 2 таймера в приложении eWelink: 1) выключить через минуту, 2) включить через 2 минуты.

Можно ли как-то управлять таймерами из HA?

**Comment by Masterz69** [comment]
Таймерами Ewelink-а из HA управлять нельзя - пока, по крайней мере.
Делай таймеры в HA - например: Scheduler Integration - супер-штука.
Создание и управление таймерами прямо из карт Lovelace.

https://github.com/nielsfaber/scheduler-card

**Comment by sergey-1976** [comment]
Это понятно. Но у меня роутер=свич (один девайс), т.е. если роутер выключить первой командой, то нет и связи между ХА и мини. Как включить обратно? :)

**Comment by sergey-1976** [comment]
Видимо нужно в тасмоту перешивать. Там вроде можно через json таймеры настраивать...

**Comment by AlexxIT** [comment]
В стандартной прошивке есть функция inching. Но она работает только на включение. Не на выключение.

**Comment by sergey-1976** [comment]
Такое устройство возможно интегрировать?
https://aliexpress.ru/item/1005001292469801.html
У него есть inching и NC|NO, идеально подходит для удаленной перезагрузки...

**Comment by AlexxIT** [comment]
Да абсолютно любой выключатель на прошивке eWeLink будет работать.

**Comment by AlexxIT** [comment]
Полагаю больше нет вопросов по этой issue
