### ISSUE TITLE
SA-026 Door Bell is working

### ISSUE THREAD

**Issue by enigmaspb** [AlexxIT/SonoffLAN#408]
Tested SA-026 door bell - 
Working god in cloud mode 

![sa-026](https://user-images.githubusercontent.com/1804979/109837386-2e415f80-7c56-11eb-83d6-785809e438f7.png)

https://aliexpress.ru/item/4000843727333.html

**Comment by enigmaspb** [comment]
But small issue 
Sensor state in push button - off (this state change on enabled paring mode ?)
In push button change only RfTrig0 
Configure this as RFBridge ?

**Comment by enigmaspb** [comment]
Working automation (send to telegram and notification in HA)
Thks for help 4pda user 470258

automation:
- alias: DoorBell
  trigger:
    - platform: state
      entity_id:  binary_sensor.sonoff_!!!!ID!!!!!!
      attribute: rfTrig0

  action:
    - service: notify.telegram
      data_template:
          message: DoorBell "{{as_timestamp(state_attr('binary_sensor.sonoff_!!!!ID!!!!!!', 'rfTrig0')|regex_replace(find='"', replace='', ignorecase=False)) | timestamp_custom('%Y-%m-%d %H:%M:%S')}}"
    - service: persistent_notification.create
      data_template:
          message: DoorBell "{{as_timestamp(state_attr('binary_sensor.sonoff_!!!!ID!!!!!!', 'rfTrig0')|regex_replace(find='"', replace='', ignorecase=False)) | timestamp_custom('%Y-%m-%d %H:%M:%S')}}"

**Comment by AlexxIT** [comment]
It's just a sensor for unsupported devices. Can you share it to my account? sonofflan@gmail.com

**Comment by enigmaspb** [comment]
>Can you share it to my account?

Shared
