### ISSUE TITLE
'EWeLinkToggle' object has no attribute 'async_turn_on_compat'

### ISSUE THREAD

**Issue by evaliukonis** [AlexxIT/SonoffLAN#409]
Not working fan turn on calling service on Home Assistant 2021.3.0
turn_on - not working
turn_off - working
toggle - working

**Comment by VoyteckPL** [comment]
I can confirm that error.

**Comment by TTLucian** [comment]
Same here. Same error message.

**Comment by azbix** [comment]
Same for me

**Comment by MarekSax** [comment]
Same problem here. It's strange because I have 5 sonoff minis and only one have this problem.

**Comment by pablorlopes** [comment]
Same here

**Comment by pablorlopes** [comment]
I updated fan.py and it worked perfectly. Thank you so much! :)

**Comment by VoyteckPL** [comment]
> I updated fan.py and it worked perfectly. Thank you so much! :)

I did the same and it works! Thanks!

**Comment by AlexxIT** [comment]
Fixed in latest release
