### ISSUE TITLE
Question: identify ifan03 restarts

### ISSUE THREAD

**Issue by chemelli74** [AlexxIT/SonoffLAN#418]
As ifan03 has a default power-on state, when there is a power outage you find the light always on.
Confirmed by Sonoff that it's a limit of current firmware implementation.

How would be the best option to identify such situation and fire a `light.turn_off` via automation ?

Thx in advance,

Simone

**Comment by AlexxIT** [comment]
Maybe it reset sequence ID of messages. Need to check difference between messages right after device restart.

**Comment by chemelli74** [comment]
Found a way to handle it via HA automation.

Simone
