### ISSUE TITLE
Sonoff B02 is not updating color temperature properly on v2.4.0

### ISSUE THREAD

**Issue by marianobntz** [AlexxIT/SonoffLAN#422]
After installing version 2.4.0 I can turn on and off correctly. Also adjusting brightness and presets/effects.
The slider do not change
I believe it is related to the range values for the temp. Let me give you values edge values for them:
(this is what HA informs as color_temp attribute, but now I see that values informed in color_temp change if I change brightness)
-- red : 153 
-- white: -148
I believe the problem is when I change brightness from HA to 255, the color_temp goes to -256. Actually it keeps growing up and down, it seems that you are adding to the existing value somewhere.

I made some tests... Steps:
- set the effect to "Bright" - brightness 255, color_temp: -148
- set brightness to 1: - brightness: 4, color_temp: -449
- set brightness to 100: - brightness: 255, color_temp: -750
- set brightness to 1: - brightness: 4, color_temp: -1051
- set brightness to 100: - brightness: 255, color_temp: -1352
- set brightness to 1: - brightness: 4, color_temp: -1653

Also I found this error message
`Logger: homeassistant.components.google_assistant.trait
Source: components/google_assistant/trait.py:412
Integration: google_assistant (documentation, issues)
First occurred: 4:36:10 PM (4 occurrences)
Last logged: 4:56:11 PM

Entity light.sonoff_1000fcd9ba has incorrect color temperature 0`

**Comment by Perlnx** [comment]
Me also have problem, moreover call-service: light.turn_on not working anymore with B02.

**Comment by AlexxIT** [comment]
@Perlnx do you use 2.4.0?

**Comment by Perlnx** [comment]
> 
> 
> @Perlnx do you use 2.4.0?

Yes

**Comment by AlexxIT** [comment]
@Perlnx what is exact model of your bulb?

**Comment by Perlnx** [comment]
It's B02-F with firmware WTW-SNL-02 version1.3.2
Before 2.4.0 I'm able to call-service: light.turn_on, light.turn_off with this bulb
(by change device_class: from switch to light in configuration.yaml)

After update 2.4.0 since it support B02 I remove custom device_class from configuration.yaml and let it detect automatically.
However I found it able to call-service: light.turn_off but not work with light.turn_on.

With other Sonoff device call-service: on & off still functional.

**Comment by minskmail** [comment]
same problem in other topic  "Sonoff Bulb B-02-B-A60 doesnt have attributes" 

https://github.com/AlexxIT/SonoffLAN/issues/394#issuecomment-796889291

**Comment by AlexxIT** [comment]
Fixed?

**Comment by minskmail** [comment]
Fixed. Спасибо. :)

**Comment by marianobntz** [comment]
Yes, fixed. Working fine. You can close it

**Comment by Perlnx** [comment]
Confirm fixed. Include my issue.
Thank you.
