### ISSUE TITLE
Cloud mode cannot work simultaneously with two copies of component. Read more:

### ISSUE THREAD

**Issue by gideonklein** [AlexxIT/SonoffLAN#427]
Sonoff Warning
Cloud mode cannot work simultaneously with two copies of component. Read more: https://github.com/AlexxIT/SonoffLAN#config-examples

Good morning, I have the same problem but I have 2 sonoff account. In the second account I shared all devices and I use this sonoff account in home assistant. I am connected by my mobil phone only in the principal account (with different email and password). How is possible I continue to have the same alert? I checked the sonoff.json and the saw 2 time the email of the principal account ("sharedBy":{"email":"xxxxxxxx@gmail)

**Comment by AlexxIT** [comment]
Maybe you using this account with other software (not Home Assistant)?

**Comment by gideonklein** [comment]
> Maybe you using this account with other software (not Home Assistant)?

Hi AlexxIT, I have home assistant in my pc and also I have home assistant in my phone and in my tablet (both by app: https://play.google.com/store/apps/details?id=io.homeassistant.companion.android&hl=it&gl=US)
I use sometime ewelink but in the first account. All devices all shared in the second account and I never use it. What other software are there?

**Comment by gideonklein** [comment]
Hi AlexxIT,  could be the problem my internet connection? I have connection by LTE (with sim card) and without public ip, maybe can be this my problem?

**Comment by AlexxIT** [comment]
Notification appears when connection to cloud breaks very often. Usual it happens when users use two connection to cloud from different devices simultaneously.

**Comment by PierreScerri** [comment]
I’ve had this addon since it was first launched. This warning has come up for the first time today. Why is this happening now?

**Comment by AlexxIT** [comment]
Nothing changes. You using your account from two devices/services simultaneously.

**Comment by PierreScerri** [comment]
I have the Home assistant open on my iPhone, iPad and iMac at the same time.  No error.

**Comment by AlexxIT** [comment]
Home Assistant generate only one connection for all client devices

**Comment by PierreScerri** [comment]
By 'devices' do you mean 'sonoff devices' or something else (eg iPhone, iPad, etc)?

**Comment by AlexxIT** [comment]
Device - phone with ewelink app. Service - Home Assistant or NodeRED or etc

**Comment by PierreScerri** [comment]
Ah OK.  The ewelink app is no longer installed on any of my devices.

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
