### ISSUE TITLE
Model S20GCN cannot be supported. This socket uses SIM card!

### ISSUE THREAD

**Issue by a120578270** [AlexxIT/SonoffLAN#428]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 529, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/sonoff/switch.py", line 44, in async_added_to_hass
    device = self._init()
  File "/config/custom_components/sonoff/sonoff_main.py", line 235, in _init
    self._update_handler(state, attrs)
  File "/config/custom_components/sonoff/switch.py", line 51, in _update_handler
    self._is_on = any(self._is_on_list(state))
  File "/config/custom_components/sonoff/sonoff_main.py", line 252, in _is_on_list
    return [state['switch'] == 'on']
KeyError: 'switch'

**Comment by AlexxIT** [comment]
Please show this model section from sonoff.json file from config folder. You can hide all private data

**Comment by a120578270** [comment]
{"1000a3c329":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":1,"wxDoorbellNotify":0},"family":{"id":"5ece97d7935195000","index":0},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5e720ac1ff5fd900","name":"路由电源","type":"10","deviceid":"1000a3c329","apikey":"b5bfacb0-dea7-49fd-9b44-1eec183e98e1","extra":{"extra":{"model":"GSB-D04-GL","ui":"GSM单通道插座-无流量版本","uiid":81,"description":"20190904010","manufacturer":"深圳松诺技术有限公司","mac":"d0:27:01:47:83:a2","apmac":"d0:27:01:47:83:a3","modelInfo":"5d0b83f5a070b08a18a6586c","brandId":"5d0b49baa070b08a18a6585f","chipid":"863744048243587"},"_id":"5d6f6651475"},"createdAt":"2020-03-18T11:49:21.897Z","__v":0,"offlineTime":"2021-03-12T13:46:29.952Z","onlineTime":"2021-03-12T13:46:52.364Z","params":{"version":8,"switches":[{"switch":"on","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"configure":[{"startup":"stay","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"iccid":"898604590419C0061319","imsi":"460047961601319","imei":"863744048243587","sledOnline":"on","lock":0,"fwVersion":"3.4.0","rssi":-73,"offlineReason":"ser w read err","bindInfos":{"miot":["b5bfacb0-dea7-49fd-9b44-1eec183e98e1_ewelink-miot-v1"]},"gsmInfo":{"status":10500,"statusMsg":"未知","tradeMark":""}},"ip":"10.20.0.65","location":"","deviceStatus":"","sharedTo":[],"devicekey":"2418b8c1-b3e8-4b5c-9472-0c4b7b907240","deviceUrl":"","brandName":"嵩诺","showBrand":true,"brandLogoUrl":"","productModel":"S20GCN","devConfig":{},"uiid":81},"1000a3c31f":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0},"family":{"room":{"id":"5ece97d79351950008bed714"},"id":"5ece97d79351950008bed715","index":-1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5ee8ea3d8bc2e500085d75ed","deviceid":"1000a3c31f","name":"我的智能设备","type":"10","apikey":"b5bfacb0-dea7-49fd-9b44-1eec183e98e1","extra":{"extra":{"model":"GSB-D04-GL","ui":"GSM单通道插座-无流量版本","uiid":81,"description":"20190904010","manufacturer":"深圳松诺技术有限公司","mac":"d0:27:01:47:83:8e","apmac":"d0:27:01:47:83:8f","modelInfo":"5d0b83f5a070b08a18a6586c","brandId":"5d0b49baa070b08a18a6585f","chipid":"863744048229057"},"_id":"5d6f66"},"createdAt":"2020-06-16T15:50:21.492Z","__v":0,"offlineTime":"2021-02-27T00:25:00.662Z","onlineTime":"2021-03-13T16:25:44.998Z","params":{"bindInfos":{"miot":["b5bfacb0-dea7-49fd-9b44-1eec183e98e1_ewelink-miot-v1"]},"offlineReason":"gprs not active","timers":[{"do":{"outlet":0,"switch":"off"},"enabled":1,"coolkit_timer_type":"repeat","at":"0 19 * * 6,0,1,2,3,4,5","type":"repeat","mId":"00fc00c3-e7ed-c40b-680b-39ff071e092c"},{"do":{"outlet":0,"switch":"on"},"enabled":1,"coolkit_timer_type":"repeat","at":"45 9 * * 0,1,2,3,4,5,6","type":"repeat","mId":"6ca35354-72b4-da1f-1183-8cc21a732511"},{"do":{"outlet":0,"switch":"on"},"enabled":1,"coolkit_timer_type":"repeat","at":"0 22 * * 6,0,1,2,3,4,5","type":"repeat","mId":"8d0828b8-ce94-e080-0276-8b835e811d28"},{"do":{"outlet":0,"switch":"off"},"enabled":1,"coolkit_timer_type":"repeat","at":"30 23 * * 6,0,1,2,3,4,5","type":"repeat","mId":"53404227-a9cb-315b-0224-e82ebbbbf647"}],"rssi":-69,"fwVersion":"3.3.5","lock":0,"sledOnline":"on","imei":"863744048229057","imsi":"460047961601389","iccid":"898604590419C0061389","pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"configure":[{"startup":"stay","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"switches":[{"switch":"on","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"version":8,"gsmInfo":{"status":10500,"statusMsg":"未知","tradeMark":""}},"ip":"10.20.11.172","location":"","sharedTo":[],"devicekey":"1f2d4d38-71cb-4d34-b8a2-1e77edde7d51","deviceUrl":"","brandName":"嵩诺","showBrand":true,"brandLogoUrl":"","productModel":"S20GCN","devConfig":{},"uiid":81}}

**Comment by AlexxIT** [comment]
Check latest master version
