### ISSUE TITLE
How to use RF bridge with Node Red

### ISSUE THREAD

**Issue by miketree1** [AlexxIT/SonoffLAN#43]
I can see the events in developers tool.

How do use my PIR as a trigger in node red?

**Comment by miketree1** [comment]
I've worked this out. Here's the sequence I used...

[{"id":"7e7226e1.761438","type":"server-events","z":"5955021.4b3367c","name":"Sonoff Remote","server":"a3fbfc9b.5957e","event_type":"sonoff.remote","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"x":140,"y":260,"wires":[["64fc2b37.d4273c"]]},{"id":"64fc2b37.d4273c","type":"function","z":"5955021.4b3367c","name":"Extract device","func":"\nvar message=msg.payload.event.name\nmsg={payload:message,topic:msg.topic}\nif (message==\"bell\"){\n    return [msg,null];\n}\nif (message==\"pir\"){\n    return [null,msg];\n}\nreturn msg;","outputs":2,"noerr":0,"x":360,"y":260,"wires":[["2698ae74.7011d2"],["3e38337b.8e8524"]]},{"id":"2698ae74.7011d2","type":"debug","z":"5955021.4b3367c","name":"bell","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":690,"y":400,"wires":[]},{"id":"3e38337b.8e8524","type":"debug","z":"5955021.4b3367c","name":"pir","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":690,"y":440,"wires":[]},{"id":"a3fbfc9b.5957e","type":"server","z":"","name":"Home Assistant"}]

**Comment by miketree1** [comment]
I also discovered you can reference the name in nodes like this.... msg.payload.event.name

**Comment by AlexxIT** [comment]
Yes, I recently added button / sensor names
