### ISSUE TITLE
One device - different status for entities

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#431]
Sonoff TH16 was disconnected.

But only switch entity become Unavailable. 
Sensors still "available"...

![image](https://user-images.githubusercontent.com/15225823/111115115-d61b2f00-856c-11eb-854b-7c13cc843bf2.png)

![image](https://user-images.githubusercontent.com/15225823/111115221-fa770b80-856c-11eb-851f-220437baa022.png)

**Comment by AlexxIT** [comment]
Not actual in latest master-version
