### ISSUE TITLE
Sonoff D1

### ISSUE THREAD

**Issue by shawwellpete** [AlexxIT/SonoffLAN#433]
Firstly thank you for this fantastic Integration, it has been  really useful and I am very grateful!

I added a couple of Sonoff D1s into my system and am using sonoff lan to control them. 

The on/off function seems to work fine but they do not dim from Home Assistant.

Any ideas?

**Comment by AlexxIT** [comment]
What firmware does your device have?

**Comment by shawwellpete** [comment]
Hi Alex, it has 3.5.0. I have noticed some phantom Light turn ons with the D1 too. I'm tempted to switch them to Sonoff basics that seem more reliable.

**Comment by AlexxIT** [comment]
Phantom turn on because RF433. This radio protocol sucks. You need to reset the binding to RF433 and control D1 only from HA.

**Comment by shawwellpete** [comment]
Thanks Alex, I didn't even realise the D1 could be controlled by RF, I've tried googling without luck, can you point me to instructions on how to reset the binding to RF433?

**Comment by theonlysinjin** [comment]
I know this is old but might help someone... I experience phantom turn on's after loadshedding (here in South Africa) messes with the power.
I have the RF remote featured here https://sonoff.tech/product/smart-lighting/d1/
I have to unpair and repair the remote and the problem subsides for a bit.

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
