### ISSUE TITLE
In new release 2.4.1 lost in temperature sensors zigbee attribute "battery_level"

### ISSUE THREAD

**Issue by enigmaspb** [AlexxIT/SonoffLAN#437]
I update to new release 
Change my config in lovelace  from "battery" to "battery_level"
and in all temperature sensors (SNZB-02 zigbee device) not show atribute  "battery_level" (only cloud - online)
Zigbee button (SNZB-01) is show only battery level and not show "cloud" 

![image](https://user-images.githubusercontent.com/1804979/112267221-2dfd1880-8c86-11eb-857f-d366cce36658.png)
![image](https://user-images.githubusercontent.com/1804979/112267283-44a36f80-8c86-11eb-8524-e45eb9ca255f.png)

**Comment by dtalens** [comment]
Same issue.

**Comment by TheSilentOn3** [comment]
Same here.

**Comment by i81** [comment]
Простите. Я в этом форуме новенький. Не могу понять - исправили-ли проблему с исчезновением атрибута battery из датчиков температуры ZigBee SonOff?

**Comment by Siggy101** [comment]
Same here.
I will need to stay on 2.4.0 until this is resolved.
![Screenshot_20210330-143028_Home Assistant](https://user-images.githubusercontent.com/41893936/112989388-28f80780-9165-11eb-9576-26c89a1fc7d6.jpg)
![Screenshot_20210330-142936_Home Assistant](https://user-images.githubusercontent.com/41893936/112989395-2ac1cb00-9165-11eb-98ba-6cc01a644148.jpg)

**Comment by Siggy101** [comment]
> Fix was posted for this. Worked for me.

I missed that.  Can you share the link?

**Comment by TheSilentOn3** [comment]
https://github.com/AlexxIT/SonoffLAN/commit/2653908b47ebb996de753d56feecc4cc2268af44

**Comment by Siggy101** [comment]
Thanks.
I am not sure how it works though.  Do we need to edit the config ourselves now to add that?  I would have expected 2.4.2 to be released with that fix.  Is that what we should wait for or edit something manually?  
Sorry if it's a dumb question but I prefer to update the package using HACS rather than go fishing under the hood myself.

**Comment by Siggy101** [comment]
I see now.  Maybe we need to manually edit custom_components/sonoff/sensor.py

**Comment by Siggy101** [comment]
> [2653908](https://github.com/AlexxIT/SonoffLAN/commit/2653908b47ebb996de753d56feecc4cc2268af44)

OK, I took a brave pill and edited sensor.py in nano.
All is working perfectly and the battery readings are visible once again.  Thanks for the gentle encouragement @TheSilentOn3

**Comment by AlexxIT** [comment]
You can install master version via HACS reinstall option

**Comment by enigmaspb** [comment]
Some temperature sensors in 2.4.2 work good , i see battery level , and some temperature not show battery .
In zigbee button show only battery and not show cloud status

**Comment by Siggy101** [comment]
I confirm that 2.4.2 is showing the battery level again normally for my temp/humidity and door open/closed sensors.
I cannot comment on button because I do not have one.

**Comment by dtalens** [comment]
I confirm battery level is showing in button device.

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.4.2
