### ISSUE TITLE
Is this library usable separate from home assistant?

### ISSUE THREAD

**Issue by supagu** [AlexxIT/SonoffLAN#439]
I stumbled across this to control sonoff devices: https://github.com/beveradb/pysonofflan but this library seems old and no longer developed. Through further research I have landed here but see that this is a home assistant component.

Can I use this library to control sonoff devices apart from home assistant? If so, can someone post a snippet of code as to where I can get started on say, connecting to a switch and turning it on/off.

**Comment by AlexxIT** [comment]
Duplicate #219 #259
