### ISSUE TITLE
Sonoff PowR2 showed only as entity but not as device

### ISSUE THREAD

**Issue by FabioBioffa** [AlexxIT/SonoffLAN#440]
Hi Alex,
I have this strange behaviour where my PowR2 is presented only as entity and because of this I'm not able to set up an automation that involves it.
I'm able to create a button in the dashboard to switch it on and off and it's working perfectly but during the automation creation wizard only devices are shown so I'm stuck. Is there something I'm doing wrong or is it a bug?
Config file is super simple and I'm using v 2.4.1 of your integration on HA 2021.3.4:

sonoff:
  username: mymail@gmail.com
  password: 'mypassword'
  reload: always
  sensors: [power, current, voltage]
  debug: True

Thanks for all your effort!

**Comment by AlexxIT** [comment]
Duplicate #83
