### ISSUE TITLE
Error 422 on Hass Startup

### ISSUE THREAD

**Issue by TheFonix** [AlexxIT/SonoffLAN#442]
I've been getting a large amount of these error and when they come in a large ammount none of my devices respond for a period of time. I cant find anybody else with this issue so im hoping not to have made a duplicate issue.

`
Core
Version
core-2021.3.4
`
`
Supervisor
Version
supervisor-2021.03.6
`
`
Operating System
Home Assistant OS 5.12
`
`
Deployment
production
`
`
Sonoff LAN v2.4.1
`
Config:
```
username: !secret_sonoff_un
password: !secret_sonoff_ps
reload: always
sensors: [temperature, humidity]
force_update: [temperature, humidity]
scan_interval: "00:00:50"
```
![Insignificant_Herring](https://user-images.githubusercontent.com/21180093/112912278-17741880-90ef-11eb-9a33-5c1e9b4f2239.png)

**Comment by TheFonix** [comment]
Just as a quick update, I notice the only devices throwing these errors are my TH10's all my TH16's run without any errors. 

Just to throw into the mix if I enable local mode the two TH10's report the temperature and humidity but don't let me change the power state. (Both TH10s are on 3.4.1v). So I'm forced to use cloud mode

**Comment by AlexxIT** [comment]
What firmware on your TH10?

**Comment by TheFonix** [comment]
3.4.1

**Comment by bwp91** [comment]
it was my understanding that the TH10/16 devices send out their temperature and humidity values locally but the switch can only be controlled via the cloud? Perhaps I am wrong.

I own a Th16 and have never been able to control the switch via local method.

**Comment by TheFonix** [comment]
I can disable cloud on all my TH16's and have the ability to control them still, and i stopped them phoning home on my firewall so they defiantly do not communicate

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
