### ISSUE TITLE
New Supervisor core-2021.4.0b0 breaks EWeLinkToggle light/turn_on

### ISSUE THREAD

**Issue by Hhavoc** [AlexxIT/SonoffLAN#444]
Device: Sonoff RFR3 inline switch with RF
Firmware: PSF-BD1-GL v3.6.0 (using local & cloud)
SonoffLAN v.2.4.2

When switching on via Home Assistant, it fails, and I get message,
Failed to call service light/turn_on. 'EWeLinkToggle' object has no attribute 'supported_color_modes'

https://github.com/home-assistant/core/commit/5f2326fb5756b85255cec27d3b2172c44bc66058
 indicates SUPPORT_COLOR is now deprecated, replaced by "color modes". Below is rundown of new attribute for color modes.

# Color mode of the light
ATTR_COLOR_MODE = "color_mode"
# List of color modes supported by the light
ATTR_SUPPORTED_COLOR_MODES = "supported_color_modes"
# Possible color modes
COLOR_MODE_UNKNOWN = "unknown"  # Ambiguous color mode
COLOR_MODE_ONOFF = "onoff"  # Must be the only supported mode
COLOR_MODE_BRIGHTNESS = "brightness"  # Must be the only supported mode
COLOR_MODE_COLOR_TEMP = "color_temp"
COLOR_MODE_HS = "hs"
COLOR_MODE_XY = "xy"
COLOR_MODE_RGB = "rgb"
COLOR_MODE_RGBW = "rgbw"
COLOR_MODE_RGBWW = "rgbww"

**Comment by mcinnes01** [comment]
I’m also getting this issue

**Comment by camui-alexandru** [comment]
Same problem here. Pls update ASAP

**Comment by huuub** [comment]
Same problem :(

**Comment by alloro72** [comment]
please fix it, the same with core-2021-4.0

**Comment by acolmano** [comment]
Same problem with sonoff basic2 firmware 3.5 and sonoff touch US firmware 3.5
Anyone is working on that bug?

**Comment by zorankrnjajic** [comment]
i Have same problem with sonoff mini and firmware 3.6

**Comment by craigthompson** [comment]
Same problem with same error.

**Comment by camui-alexandru** [comment]
Looks like SUPPORT_COLOR is now deprecated, replaced by "color modes"

**Comment by andyz68** [comment]
Same for me, someone has find a solution?

**Comment by maverik80** [comment]
same for me, wait a update

**Comment by michielton** [comment]
Ran into the same problem. Made some minor changes to `switch.py` to get it working again while we wait for an update.

At `switch.py` `line 75` replace this:

```
    @property
    def state_attributes(self):
        return self._attrs
```

with this:

```
    @property
    def state_attributes(self):
        # return self._attrs
        return {
            **self._attrs,
            "supported_color_modes": "onoff"
        }

    @property
    def supported_color_modes(self):
        return "onoff"
```

Restart Home Assistant and you should be good to go!

Cheers!

**Comment by andyz68** [comment]
> Ran into the same problem. Made some minor changes to `switch.py` to get it working again while we wait for an update.
> 
> At `switch.py` `line 75` replace this:
> 
> ```
>     @property
>     def state_attributes(self):
>         return self._attrs
> ```
> 
> with this:
> 
> ```
>     @property
>     def state_attributes(self):
>         # return self._attrs
>         return {
>             **self._attrs,
>             "supported_color_modes": "onoff"
>         }
> 
>     @property
>     def supported_color_modes(self):
>         return "onoff"
> ```
> 
> Restart Home Assistant and you should be good to go!
> 
> Cheers!

Works! Thank you.

**Comment by maverik80** [comment]
> Mi sono imbattuto nello stesso problema. Ho apportato alcune piccole modifiche per `switch.py`farlo funzionare di nuovo in attesa di un aggiornamento.
> 
> A `switch.py` `line 75`sostituire questo:
> 
> ```
>     @property
>     def state_attributes(self):
>         return self._attrs
> ```
> 
> con questo:
> 
> ```
>     @property
>     def state_attributes(self):
>         # return self._attrs
>         return {
>             **self._attrs,
>             "supported_color_modes": "onoff"
>         }
> 
>     @property
>     def supported_color_modes(self):
>         return "onoff"
> ```
> 
> Riavvia Home Assistant e dovresti essere pronto per partire!
> 
> Saluti!

Thanks man

**Comment by michielton** [comment]
Updated to `v2.4.3` and this also fixed the problem, so no need for the manual changes to `switch.py` anymore.

Thanks @AlexxIT

**Comment by luccyo** [comment]
Updated to 2.4.3, very fast to react  ! Thanks a lot @AlexxIT .

**Comment by dtalens** [comment]
Thanks @AlexxIT

**Comment by acolmano** [comment]
This patch works for me
Thanks

**Comment by mcinnes01** [comment]
Awesome work thanks :)
