### ISSUE TITLE
Sonoff consumption in HA

### ISSUE THREAD

**Issue by wowulavega** [AlexxIT/SonoffLAN#450]
Can anybody explain me, how the consumptions can be displayed in a HA card?
I see all consumptions in the „Developer Tools“ -Attributes .... I just can’t find a solution to display them in a Card.
Thanks for every help.

**Comment by AlexxIT** [comment]
Read docs
https://github.com/AlexxIT/SonoffLAN#sonoff-pow-power-consumption

**Comment by wowulavega** [comment]
Unfortunately that paper includes no answer to my question.
It just tells how to receive the data’s but not how to display them in an orderly manner.

**Comment by FelisucoVFR** [comment]
I think this one fits what you are looking for:
[](https://community.home-assistant.io/t/sonoff-sensor-attributes-problem/182716/2)

**Comment by wowulavega** [comment]
Probably I have expressed myself misunderstood, but It is not about retrieving the "consumption" values, this already works, but to integrate the 100 values per retrieval into a representation (card).
Unfortunately, I am not a programmer who can create a card myself, so I would be grateful for hints that lead to such a representation of the 100 consumption values.
