### ISSUE TITLE
Motor hinges eWelink

### ISSUE THREAD

**Issue by pepe59** [AlexxIT/SonoffLAN#456]
In the forum, I mentioned creating an entity to control the hinges. Includes Binthen outboard engine and eWelink support.
After installation I managed to create an entity and it is possible to control HA.
The error is that it does not detect the correct open, closed states, but the eWlink application works well.
As you typed, I share a device in your account.

**Comment by AlexxIT** [comment]
I'll check it when have time

https://community.home-assistant.io/t/control-sonoff-devices-with-ewelink-original-firmware-over-lan-and-or-cloud/167567/189

**Comment by pepe59** [comment]
I would just like to add a finding:
When the opening is complete, the status remains:
opens up.
When closed, it is the same, the status remains:
it closes.
There is probably no real-time status query.
The status is displayed correctly only after restarting HA. The component is likely to reload.

**Comment by pepe59** [comment]
After upgrading to version 2.4.5, you cannot control the curtains.
Before the update, the control worked and I patiently waited for the correct display of the open and closed status.

**Comment by pepe59** [comment]
Thank you very much. After update 2.4.6, the hinge control works again in automation. I will wait patiently if you can add the correct loading of open, closed states.

**Comment by AlexxIT** [comment]
Is device works fine in latest master-version?

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
