### ISSUE TITLE
Only work right after restart

### ISSUE THREAD

**Issue by tyjtyj** [AlexxIT/SonoffLAN#46]
I got a switch using ewelink not sonoff. 

It work switch on/off right after home assistant reboot. After that it would throw
WARNING (MainThread) [custom_components.sonoff] Can't send switches to 1000xxxxxx

It works again after about 15 / 30 mins .... then stop again after switching. 

Beside, the device only have 1 gang but it shows 4 in home assistant. 

If i switch via ewelink app, home assistant shows correct stat.

**Comment by AlexxIT** [comment]
What is your device?

**Comment by tyjtyj** [comment]
This one

#Aliexpress SG$ 19.30  20%OFF | eWelink UK 1/2/3 Gang Wifi Smart Single Fire Wire Wall Light Switch RF433 Remote Control No Neutral Line Switch App Control
https://a.aliexpress.com/_dUEMmRv

**Comment by AlexxIT** [comment]
Can you send sonoff.json with info about this switch? You can delete all private data.

**Comment by tyjtyj** [comment]
I use localapi only


sonoff:
  reload: always
  devices:
    1000bf503a: #corridor light
      devicekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


> 2020-02-27 22:24:47 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Update service eWeLink_1000bf503a._ewelink._tcp.local.
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Properties: {'data3': 'piMw4/If92xTSF5ASc5jVGCH2VHnDn0/U1eBwfv3NKouQ4nnsmL4nBlrbr2ak30FN18z5cJec2VyPIG2pizypqOpZwT9JGx
> bUFWvPQWt1aazIlq6k4/GFQRGY8cVn0ML94PGJenE1ZdToz631dvambdw86XO6CG2/uJ7tSqQ==', 'data2': '6jlSbtPXrtK0IpOGupgI0t8EE5oIECgBPrfkPwANXphF/TNye5VpIfQFF4EJ3Noeti3g9zSdMz2FM8DrMUxCup2sgoaFDlb1NVuj7JVHU74hWy4SK7ksxy5Lrxsua2GoUeoUG9Ey+vRh0CCMtAYHp
> RgOpJdbiAIZ7d6md//xenL8NbcSbQf4wIisBivwp3bHwGDD+Tn4NeQ2slP2ZPGN7U/aEByrPw4JDwpVeg42q211KJ/Znns7f1M', 'data1': '4CrZafyZyzgXxIZgTE1FxHoMBIcvvwlRUNiCwddpye7lUep3OST7x0+tWy3Lx/7P/c7pVmHCBiqwbMPBSBf6N8jN+9igGabFmweWDnNJPzn2BLwWYdyK5JGmzPoVJh
> v0qZO1laJDqN2IyOF8j+4k+HEWqvbNKi159W1fzLzMwTqsD1flsl5a3paSs8ClzJ5WdC7va+VY70BOEHjkWvcJcKQ2IhMJRgqLozTo9qJNm9Q0n44iPJoL9ZJ', 'seq': '45', 'iv': 'MDEyMzQ1Njc4OTAxMjM0NQ==', 'encrypt': True, 'apivers': '1', 'type': 'strip', 'id': '1000bf503
> a', 'txtvers': '1'}
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] State: {'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'on', 'outlet': 1}, {'switch': 'off', 'outlet': 2}, {'s
> witch': 'on', 'outlet': 3}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}, {'startup': 'off', 'outlet': 2}, {'startup': 'off', 'outlet': 3}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pu
> lse': 'off', 'width': 1000, 'outlet': 1}, {'pulse': 'off', 'width': 1000, 'outlet': 2}, {'pulse': 'off', 'width': 1000, 'outlet': 3}], 'sledOnline': 'on', 'staMac': '44:5D:5E:40:AA:30', 'rssi': -63}
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Update service eWeLink_1000bf503a._ewelink._tcp.local.
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Properties: {'data3': 'piMw4/If92xTSF5ASc5jVGCH2VHnDn0/U1eBwfv3NKouQ4nnsmL4nBlrbr2ak30FN18z5cJec2VyPIG2pizypqOpZwT9JGx
> bUFWvPQWt1aazIlq6k4/GFQRGY8cVn0ML94PGJenE1ZdToz631dvambdw86XO6CG2/uJ7tSqQ==', 'data2': '6jlSbtPXrtK0IpOGupgI0t8EE5oIECgBPrfkPwANXphF/TNye5VpIfQFF4EJ3Noeti3g9zSdMz2FM8DrMUxCup2sgoaFDlb1NVuj7JVHU74hWy4SK7ksxy5Lrxsua2GoUeoUG9Ey+vRh0CCMtAYHp
> RgOpJdbiAIZ7d6md//xenL8NbcSbQf4wIisBivwp3bHwGDD+Tn4NeQ2slP2ZPGN7U/aEByrPw4JDwpVeg42q211KJ/Znns7f1M', 'data1': '4CrZafyZyzgXxIZgTE1FxHoMBIcvvwlRUNiCwddpye7lUep3OST7x0+tWy3Lx/7P/c7pVmHCBiqwbMPBSBf6N8jN+9igGabFmweWDnNJPzn2BLwWYdyK5JGmzPoVJh
> v0qZO1laJDqN2IyOF8j+4k+HEWqvbNKi159W1fzLzMwTqsD1flsl5a3paSs8ClzJ5WdC7va+VY70BOEHjkWvcJcKQ2IhMJRgqLozTo9qJNm9Q0n44iPJoL9ZJ', 'seq': '45', 'iv': 'MDEyMzQ1Njc4OTAxMjM0NQ==', 'encrypt': True, 'apivers': '1', 'type': 'strip', 'id': '1000bf503
> a', 'txtvers': '1'}
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Update service eWeLink_1000bf503a._ewelink._tcp.local.
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Properties: {'data3': 'piMw4/If92xTSF5ASc5jVGCH2VHnDn0/U1eBwfv3NKouQ4nnsmL4nBlrbr2ak30FN18z5cJec2VyPIG2pizypqOpZwT9JGx
> bUFWvPQWt1aazIlq6k4/GFQRGY8cVn0ML94PGJenE1ZdToz631dvambdw86XO6CG2/uJ7tSqQ==', 'data2': '6jlSbtPXrtK0IpOGupgI0t8EE5oIECgBPrfkPwANXphF/TNye5VpIfQFF4EJ3Noeti3g9zSdMz2FM8DrMUxCup2sgoaFDlb1NVuj7JVHU74hWy4SK7ksxy5Lrxsua2GoUeoUG9Ey+vRh0CCMtAYHp
> RgOpJdbiAIZ7d6md//xenL8NbcSbQf4wIisBivwp3bHwGDD+Tn4NeQ2slP2ZPGN7U/aEByrPw4JDwpVeg42q211KJ/Znns7f1M', 'data1': '4CrZafyZyzgXxIZgTE1FxHoMBIcvvwlRUNiCwddpye7lUep3OST7x0+tWy3Lx/7P/c7pVmHCBiqwbMPBSBf6N8jN+9igGabFmweWDnNJPzn2BLwWYdyK5JGmzPoVJh
> v0qZO1laJDqN2IyOF8j+4k+HEWqvbNKi159W1fzLzMwTqsD1flsl5a3paSs8ClzJ5WdC7va+VY70BOEHjkWvcJcKQ2IhMJRgqLozTo9qJNm9Q0n44iPJoL9ZJ', 'seq': '45', 'iv': 'MDEyMzQ1Njc4OTAxMjM0NQ==', 'encrypt': True, 'apivers': '1', 'type': 'strip', 'id': '1000bf503
> a', 'txtvers': '1'}
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Update service eWeLink_1000bf503a._ewelink._tcp.local.
> 2020-02-27 22:24:48 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Properties: {'data3': 'piMw4/If92xTSF5ASc5jVGCH2VHnDn0/U1eBwfv3NKouQ4nnsmL4nBlrbr2ak30FN18z5cJec2VyPIG2pizypqOpZwT9JGx
> bUFWvPQWt1aazIlq6k4/GFQRGY8cVn0ML94PGJenE1ZdToz631dvambdw86XO6CG2/uJ7tSqQ==', 'data2': '6jlSbtPXrtK0IpOGupgI0t8EE5oIECgBPrfkPwANXphF/TNye5VpIfQFF4EJ3Noeti3g9zSdMz2FM8DrMUxCup2sgoaFDlb1NVuj7JVHU74hWy4SK7ksxy5Lrxsua2GoUeoUG9Ey+vRh0CCMtAYHp
> RgOpJdbiAIZ7d6md//xenL8NbcSbQf4wIisBivwp3bHwGDD+Tn4NeQ2slP2ZPGN7U/aEByrPw4JDwpVeg42q211KJ/Znns7f1M', 'data1': '4CrZafyZyzgXxIZgTE1FxHoMBIcvvwlRUNiCwddpye7lUep3OST7x0+tWy3Lx/7P/c7pVmHCBiqwbMPBSBf6N8jN+9igGabFmweWDnNJPzn2BLwWYdyK5JGmzPoVJh
> v0qZO1laJDqN2IyOF8j+4k+HEWqvbNKi159W1fzLzMwTqsD1flsl5a3paSs8ClzJ5WdC7va+VY70BOEHjkWvcJcKQ2IhMJRgqLozTo9qJNm9Q0n44iPJoL9ZJ', 'seq': '45', 'iv': 'MDEyMzQ1Njc4OTAxMjM0NQ==', 'encrypt': True, 'apivers': '1', 'type': 'strip', 'id': '1000bf503
> a', 'txtvers': '1'}
> 2020-02-27 22:24:49 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Update service eWeLink_1000bf503a._ewelink._tcp.local.
> 2020-02-27 22:24:49 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Properties: {'data3': 'piMw4/If92xTSF5ASc5jVGCH2VHnDn0/U1eBwfv3NKouQ4nnsmL4nBlrbr2ak30FN18z5cJec2VyPIG2pizypqOpZwT9JGx
> bUFWvPQWt1aazIlq6k4/GFQRGY8cVn0ML94PGJenE1ZdToz631dvambdw86XO6CG2/uJ7tSqQ==', 'data2': '6jlSbtPXrtK0IpOGupgI0t8EE5oIECgBPrfkPwANXphF/TNye5VpIfQFF4EJ3Noeti3g9zSdMz2FM8DrMUxCup2sgoaFDlb1NVuj7JVHU74hWy4SK7ksxy5Lrxsua2GoUeoUG9Ey+vRh0CCMtAYHp
> RgOpJdbiAIZ7d6md//xenL8NbcSbQf4wIisBivwp3bHwGDD+Tn4NeQ2slP2ZPGN7U/aEByrPw4JDwpVeg42q211KJ/Znns7f1M', 'data1': '4CrZafyZyzgXxIZgTE1FxHoMBIcvvwlRUNiCwddpye7lUep3OST7x0+tWy3Lx/7P/c7pVmHCBiqwbMPBSBf6N8jN+9igGabFmweWDnNJPzn2BLwWYdyK5JGmzPoVJh
> v0qZO1laJDqN2IyOF8j+4k+HEWqvbNKi159W1fzLzMwTqsD1flsl5a3paSs8ClzJ5WdC7va+VY70BOEHjkWvcJcKQ2IhMJRgqLozTo9qJNm9Q0n44iPJoL9ZJ', 'seq': '45', 'iv': 'MDEyMzQ1Njc4OTAxMjM0NQ==', 'encrypt': True, 'apivers': '1', 'type': 'strip', 'id': '1000bf503
> a', 'txtvers': '1'}
> 2020-02-27 22:24:49 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Update service eWeLink_1000bf503a._ewelink._tcp.local.
> 2020-02-27 22:24:49 DEBUG (zeroconf-ServiceBrowser_eWeLink_1000bf503a._ewelink._tcp.local.) [custom_components.sonoff] Properties: {'data3': 'piMw4/If92xTSF5ASc5jVGCH2VHnDn0/U1eBwfv3NKouQ4nnsmL4nBlrbr2ak30FN18z5cJec2VyPIG2pizypqOpZwT9JGx
> bUFWvPQWt1aazIlq6k4/GFQRGY8cVn0ML94PGJenE1ZdToz631dvambdw86XO6CG2/uJ7tSqQ==', 'data2': '6jlSbtPXrtK0IpOGupgI0t8EE5oIECgBPrfkPwANXphF/TNye5VpIfQFF4EJ3Noeti3g9zSdMz2FM8DrMUxCup2sgoaFDlb1NVuj7JVHU74hWy4SK7ksxy5Lrxsua2GoUeoUG9Ey+vRh0CCMtAYHp
> RgOpJdbiAIZ7d6md//xenL8NbcSbQf4wIisBivwp3bHwGDD+Tn4NeQ2slP2ZPGN7U/aEByrPw4JDwpVeg42q211KJ/Znns7f1M', 'data1': '4CrZafyZyzgXxIZgTE1FxHoMBIcvvwlRUNiCwddpye7lUep3OST7x0+tWy3Lx/7P/c7pVmHCBiqwbMPBSBf6N8jN+9igGabFmweWDnNJPzn2BLwWYdyK5JGmzPoVJh
> v0qZO1laJDqN2IyOF8j+4k+HEWqvbNKi159W1fzLzMwTqsD1flsl5a3paSs8ClzJ5WdC7va+VY70BOEHjkWvcJcKQ2IhMJRgqLozTo9qJNm9Q0n44iPJoL9ZJ', 'seq': '45', 'iv': 'MDEyMzQ1Njc4OTAxMjM0NQ==', 'encrypt': True, 'apivers': '1', 'type': 'strip', 'id': '1000bf503
> a', 'txtvers': '1'}
>

**Comment by tyjtyj** [comment]
Anyway, 
I moved to cloud login and it works.. 
It shows other 4 switch instead of 1 but I have fine with that.

Thanks for great solution.

**Comment by AlexxIT** [comment]
@tyjtyj Can you send sonoff.json with info about this switch? It should already appear. I will fix 4 switches.

**Comment by tyjtyj** [comment]
Not sure if there is sensitive data if so let me know.


`{"1000bf503a":{"settings":{"opsNotify":1,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0,"appDoorbellNotify":1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5e5368a0138fe30009076296","name":"My devicesbf503a","type":"10","deviceid":"1000bf503a","apikey":"6bbb90ae-8119-4181-aa36-dc07a934eb08","extra":{"extra":{"uiid":77,"description":"WO183733","brandId":"59e0dbc25c1af3a660cc1ac0","apmac":"d0:27:01:7e:9d:c5","mac":"d0:27:01:7e:9d:c4","ui":"单通道插座-多通道版","modelInfo":"5c6666aaa6a42aaf2032d552","model":"CKA-D01-GL","manufacturer":"深圳酷宅科技有限公司","chipid":"395539343115189dffffffffffffffff","staMac":"44:5D:5E:40:AA:30"},"_id":"5dc02415aa968450c2ddffe9"},"createdAt":"2020-03-02T09:58:31.552Z","__v":0,"onlineTime":"2020-03-02T09:58:31.426Z","params":{"version":8,"switches":[{"switch":"on","outlet":0},{"switch":"on","outlet":1},{"switch":"off","outlet":2},{"switch":"on","outlet":3}],"configure":[{"startup":"stay","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"lock":0,"sledOnline":"on","staMac":"44:5D:5E:40:AA:30","rssi":-39,"fwVersion":"3.3.2","selfApikey":"123","timers":[]},"ip":"45.114.7.235","location":"","offlineTime":"2020-03-02T09:13:03.786Z","deviceStatus":"","sharedTo":[],"devicekey":"1e79d6b0-4319-4597-ac29-6f19408d5d9a","deviceUrl":"","brandName":"coolkit","showBrand":false,"brandLogoUrl":"","productModel":"CKW04-1C","devConfig":{},"uiid":77}}`

**Comment by tyjtyj** [comment]
Using Cloud 4 switch appear and only 1 works. Other 3 shows unavailable .

Using Local LAn 4 switch appear and 1 work 1st time. Other 3 give random on/off status

**Comment by AlexxIT** [comment]
@tyjtyj you need to manually remove the extra switches: http://ip:8123/config/entities
They will no longer appear.

The device has firmware from a multi-channel switch. Only cloud login can understand it.

DrZzs had the same problem with Sonoff Micro in this video:
https://www.youtube.com/watch?v=DsTqOlrQQ1k

**Comment by tyjtyj** [comment]
Thanks for checking.. as long as it works now ..
This device cannot be flash with tasmota, it is using same chip as sonoff usb

**Comment by tyjtyj** [comment]
my Bad, it stop working after sometimes again.. i am lost now .. not sure what cause it to work and what not .
