### ISSUE TITLE
CNSKOU WiFi Dimmer and Curtain switch support

### ISSUE THREAD

**Issue by berzezo** [AlexxIT/SonoffLAN#461]
Hello,

First of all, thanks for your great work with SonoffLAN.

We have CNSKOU brand switches, and the 1-2-3 gang switches working well with the integration.

Unfortunatelly I can see the Dimmer and Curtain switch in the sonoff.json file, but the entity in Home Assistant is not exist.

For example, here is the Dimmer's sonoff.json:

```json
{"10009e76b5":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0,"appDoorbellNotify":1},"family":{"room":{"id":"606dd49ac630f50008940ef4"},"id":"606dd49ac630f50008940ef5","index":-1},"group":"","online":false,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"606e11cda2f66600086467f9","relational":[],"deviceid":"10009e76b5","name":"Wifi Dimmer Teszt","type":"10","apikey":"adfd559b-1602-4518-86e7-52c3ba838727","extra":{"extra":{"uiid":36,"description":"20190802006","brandId":"5abcad2c20a9c73c4804ba0e","apmac":"*******","mac":"***********","ui":"单路调光开关","modelInfo":"5cbd3e054cae8c2473fa4c8d","model":"PSF-BTA-GL","manufacturer":"乐清市三口电子科技有限公司","staMac":"***********","chipid":"00A8C897"},"_id":"5d44105564a2ae23f10c6b5d"},"params":{"rssi":-61,"fwVersion":"3.4.0","staMac":"2C:F4:32:A8:C8:97","switch":"off","bright":28,"version":8,"sledOnline":"on","ssid":"TP-Link_E072","bssid":"*************"},"createdAt":"2021-04-07T20:10:53.222Z","__v":0,"onlineTime":"2021-04-07T21:09:43.446Z","ip":"87.97.28.163","location":"","offlineTime":"2021-04-07T22:19:29.150Z","sharedTo":[],"devicekey":"44845a10-5331-4f76-a488-b6386f28cfd5","deviceUrl":"","brandName":"CNSKOU","showBrand":true,"brandLogoUrl":"","productModel":"SK-A801T","devConfig":{},"uiid":36}}
```

Dimmer model Nr.: SK-A801T
Curtain model Nr.: SK-A801CY

Do you have any idea why the entities don't appear in HA? Are Dimmer and Curtain switches supported?

Thanks in advance.

**Comment by AlexxIT** [comment]
HA should create entity for this dimmer (as switch).

**Comment by berzezo** [comment]
I can't see any interesting in the logs. Seems to be OK everything, but the entity is not appeared.

Do you have any suggestion about the problem?

Thanks in advance.

**Comment by berzezo** [comment]
Hello,

I realised that only works in cloud mode. (Multicast is OK.)
Is there any plan for supporting LAN mode as well?

Thanks in advance.

**Comment by AlexxIT** [comment]
Show your config, you may remove private data

**Comment by berzezo** [comment]
I tried all the configuration to achieve local mode operation.
The last one:

```
sonoff:
  username: *********
  password: *********
  mode: local
  reload: always
  debug: True
```

**Comment by AlexxIT** [comment]
You can share these devices with my ewelink account - sonofflan@gmail.com
I don't promise quick results. I'll see when I have time off from other projects

**Comment by berzezo** [comment]
I've just shared the dimmer device.
I can power it on in about 4 hours when I arrive home.

Thanks for your help.

**Comment by AlexxIT** [comment]
I won't be able to check today.

**Comment by josephus** [comment]
I also have a curtain switch which lacks LAN Control. @AlexxIT is this something that needs to be solved on device side?

Model no: SK-A801C
FW Name: PSF-BTA-GL
FW Version: 3.4.2 

The eWLink app does not offer "Lan Control" in settings and on the main screen only cloud icon is visible next to the device.

All TCP ports on the device are closed, while UDP 67, 137, 138 are open. I haven't investing in sniffing the HTTPS traffic to the cloud.

**Comment by AlexxIT** [comment]
Dimmer UIID 36 supported
