### ISSUE TITLE
Sonoff devices offline after 2021.4 update

### ISSUE THREAD

**Issue by lancer73** [AlexxIT/SonoffLAN#462]
Since the update to the last version of HA Core (2021.4) all Sonoff devices are offline after restart of HA. Only when I force the Sonoff components to reconnect to the lan (I do not need to restart them), or when the Sonoff component roams to a different access point, the devices become available. 

So far I have not seen any errors in the logs and this could be due to changed behaviour of HA Core itself (I can find no relevant changes to HA though).

I use local mode (2 devices connected to Ewelink, others are in dev mode; all behave the same) to connect to the devices and my HA virtual machine is connected directly to 3 different VLAN's (one untagged, 2 tagged). The Sonoff devices are in one of the tagged VLANs and were working properly until the last HA update.

**Comment by AlexxIT** [comment]
Use default auto mode

**Comment by lancer73** [comment]
OK, thanks. That solved the problem with the cloud connected devices.
