### ISSUE TITLE
My Sonoff Switches dont show up in devices

### ISSUE THREAD

**Issue by PlutoPlayz** [AlexxIT/SonoffLAN#463]
My Sonoff Switches dont show up in devices which means i cant add them to automations. Please Help

**Comment by pepe59** [comment]
You don't need switches as devices.
Use an entity and call the service, example switch.turn_on.

**Comment by PlutoPlayz** [comment]
oh thanks. Im new to home assistant and still learning.

**Comment by PlutoPlayz** [comment]
Ok im in automations and select call service under actions and they dont show up. What am i doing wrong?

**Comment by AlexxIT** [comment]
Duplicate pinned issue
