### ISSUE TITLE
UIIDs not correct for DIY mode

### ISSUE THREAD

**Issue by MarcoV-git** [AlexxIT/SonoffLAN#464]
A Sonoff D1 with v3.5.0 running in DIY mode returns a 'new' UIID: **diylight**

![image](https://user-images.githubusercontent.com/61657258/114316087-484a4980-9b02-11eb-975e-d36f42058b5a.png)

And although it reports API v1 it actually does implement api v2:

`$ curl -d '{"deviceid":"", "data":{}}' -H "Content-Type: application/json" -X POST http://x.x.x.x:8081/zeroconf/info

{"seq":25,"error":0,"data":{"deviceid":"1000xxxxxx","switch":"on","startup":"on","brightness":25,"brightMin":0,"brightMax":255,"mode":0,"otaUnlock":false,"fwVersion":"3.5.0","ssid":"xxxxxx","bssid":"x:x:x:x:x:x","signalStrength":-62}}
$`

Also a BASICR3 in DIY mode returns a 'new' UIID: **diy_plug**:

![image](https://user-images.githubusercontent.com/61657258/114316264-1685b280-9b03-11eb-99f5-6b9253fd0bb9.png)

;-))

**Comment by Joao-Sousa-71** [comment]
These are exactly the DIY models that I have in my setup so be glad to help testing if it helps.

**Comment by Joao-Sousa-71** [comment]
@MarcoV-git do you see any reason to add the new UIID of the BASICR3 with the latest firmware? The fact that is not identified properly, will add it by default as switch which is what the BASICR3 does. Any comment is more than welcome. Thank you!

**Comment by AlexxIT** [comment]
Thanks! Fixed in latest master-version. Will be in next release.
