### ISSUE TITLE
Nothing happen...

### ISSUE THREAD

**Issue by ralocar** [AlexxIT/SonoffLAN#469]
Hi, after installing HACS with mi github account and SONOFFLAN repository ... I cannot see any of the devices I have in ewelink.  I have reinstalled the HACS and SonoffLAN twice, also changed the configuration yaml with different options and restarting the HA but nothing happen. It seems so simple and easy to work, but I do not know why it is not working for me. My Devices are:
DualR2
BasicR2
Mini

Thanks

**Comment by AlexxIT** [comment]
You need to learn more about Home Assistant
https://www.youtube.com/watch?v=DsTqOlrQQ1k

**Comment by ralocar** [comment]
Hi Alexx, I saw that video before my post and I followed the instructions. Now Hacs is installed in a different way. All seems properly installed and configured. But it does not work. 
Believe me, I tried everything. Should I reinstall again HACs or your repository? Should I create other ewelink account? Thanks

**Comment by AlexxIT** [comment]
Component don't support devices. May be your try to find entities not in right place?

**Comment by ralocar** [comment]
Not sure if I understand your question.
Video you share and others I saw seem very easy: plug and play! HACS and SonoffLAN are well installed in HA... and I just changed my configuration.yaml with cloud or local as per your instructions but nothing happen. I have removed my duckdns for accessing locally. My ewelink app is v4... not sure if this matters. I have not found even hidden .sonoff.json that supposedly is created in local mode.

Thanks a lot
Br



Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
De: Alex X ***@***.***>
Enviado: martes, 13 de abril de 2021 20:34
Para: AlexxIT/SonoffLAN
Cc: ralocar; Author
Asunto: Re: [AlexxIT/SonoffLAN] Nothing happen... (#469)


Component don't support devices. May be your try to find entities not in right place?

**Comment by FelisucoVFR** [comment]
Sorry about this idiot remembering... but...
Did you restart HA after installing them?
Did you write correctly the user and password? Try not using !secret the first time until you see it working.

**Comment by ralocar** [comment]
Thanks for your support Felisuco.
Yes. I did! No success.
I will create other ewelink account and I will check
Thanks
BR

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by FelisucoVFR** [comment]
It has been really easy for me. As we say, I have two left hands but it worked seamlessly following a couple of tutorials.
Did you try to find them by the name you wrote into eWeelink at Developer tools?

**Comment by ralocar** [comment]
Hi Felisuco,
Yes, I tried... thanks
Do you know which version of ewelink app you have? I have v4.10
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by FelisucoVFR** [comment]
V4.10 too on iPhone. I don’t think the eWeLink is the issue if you can see them there.

I would point more to the credentials if you don’t see any or to any other issue if you don’t see just some of the devices.

 

Regards

**Comment by ralocar** [comment]
Solved with shame...
I put user instead username in the configuration .. f**k!!!
Today I will sleep better!
Thanks Alexx and Felisuco
See you in the next issue


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
