### ISSUE TITLE
my sonoff TH16 has stopped giving me temperature since update to 2.4.2

### ISSUE THREAD

**Issue by user514** [AlexxIT/SonoffLAN#471]
The unit has firmware version: sw_version: PSA-BHA-GL v3.4.1
I think update sonoff lan 2.4.2 and stopped giving temps. Today I updated to 2.4.3 and keep online/online and giving linkquality of the device in dB, but not temperature.

  Any one with same problem?...

**Comment by AlexxIT** [comment]
Find out which version works. You can roll back the version via HACS

**Comment by user514** [comment]
I have tried rolling back to four different previous versions and stopped at v2.3.2, to see if I get temperature data again, and now I'm on 2.3.2 after testing three or four other versions and I don't get temperature. Maybe I'm doing something wrong, but it was working not long ago. Now when I enter this in dev-tools -> template:

`{{ states.switch.sonoff_1000bd1541 }}`

...and I get:

`<template TemplateState(<state switch.sonoff_1000bdXXXX=off; manufacturer=SONOFF, model=TH16, sw_version=PSA-BHA-GL v3.4.1, local=online, cloud=online, rssi=-50, friendly_name=XXXXX, supported_features=0 @ 2021-04-26T17:34:32.881330+02:00>)>`

  I think there should be temperature attribute somewhere there... because I used to have a sensor with the template platform with this value: {{ state_attr('switch.sonoff_1000bdXXXX', 'temperature') }} and it used to give me temps. Thanks.

**Comment by AlexxIT** [comment]
What about ewelink? Application works fine?

**Comment by user514** [comment]
Alex... if ewelink should show temperature of th16 with temp adapter plugged... then I must have some problem, because it is not showing temperature or humidity. It could be that my temp adapter has loose conection or is faulty, and probably the problem is not related with the addon. Tht will explain that rolling back to previous versions it is not working neither.

  I will confirm as soon as I can reach to the sensor which is a bit hidden on the ceiling. Thanks for your help. You could close this issue.

**Comment by Megachip** [comment]
Same here... but just started now with TH16 an HA, so no idea if its ever worked. 
Everything fine with ewelink app

**Comment by FelisucoVFR** [comment]
Note the jack needs to be fully in.
First time it seems is going to break but the connector must touch the TH case to work

**Comment by Megachip** [comment]
> Note the jack needs to be fully in.
> First time it seems is going to break but the connector must touch the TH case to work

As I wrote, temperature is shown in ewelink app ... so can't be an hardware issue.

Maybe API?

```
        "params": {
            "bindInfos": {
                "miot": [
                    "xxx_ewelink-miot-v1"
                ]
            },
            "version": 8,
            "sledOnline": "on",
            "init": 1,
            "switch": "off",
            "fwVersion": "3.4.1",
            "rssi": -57,
            "staMac": "A4:CF:12:xxx",
            "startup": "off",
            "pulse": "off",
            "pulseWidth": 500,
            "sensorType": "ERROR_TYPE",
            "currentHumidity": "unavailable",
            "currentTemperature": "unavailable"
        },
```
Thats what i've found in `.sonoff.json`
