### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/html 

### ISSUE THREAD

**Issue by mohssinDR** [AlexxIT/SonoffLAN#472]
Hey Alexx, Thank you for this awesome integration.

the past 7 days all my devices stop sending values to the cloud, and i want to verify if the local mode is OK, but i dont have the .sonoff.json under my hidden files, like if he never been generated before, then i found this error in the log :

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:150
Integration: Sonoff (documentation, issues)
First occurred: 23:21:48 (3 occurrences)
Last logged: 23:22:04

Coolkit API error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc/dispatch/app')
Traceback (most recent call last):
  File "/config/custom_components/sonoff/sonoff_cloud.py", line 150, in _api
    return await r.json()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://eu-api.coolkit.cc/dispatch/app')

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
