### ISSUE TITLE
Smart WiFi Circuit Breaker eWelink 

### ISSUE THREAD

**Issue by I2LSoftwares** [AlexxIT/SonoffLAN#476]
Hi Alexx, Thank you for this awesome integration.

Alexx, 
Can I integrate this device with HA through SonoffLan?

https://www.aliexpress.com/item/32993147980.html?spm=a2g0s.8937460.0.0.25a62e0eYWVCHz

**Comment by AlexxIT** [comment]
This is simple switch device. Should work without any additional development
