### ISSUE TITLE
Lovelace 'Uncaught Error'

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#479]
With Last versión of WebRTC

![Screenshot_20210423-020320_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/115821167-a87d9d00-a3d8-11eb-9521-8bfdf8b91736.jpg)

**Comment by AlexxIT** [comment]
1. Wrong github
2. Try reinstall component via HACS

**Comment by Gferretta** [comment]
Hi Alex
I Uninstalled everything, both in **HACS** and in **Configuration -> Integrations.**
Clear the cache.
Restart my HA
Install WebRTC only in **HACS** and the error was does NOT appear in log.
When I install the integration in **Configuration -> Integrations**., without even putting the card in with video, only with a refresh of screen, the error already appears in Lovelace.



I leave you a video that may help you to determine what is happening to me.
https://photos.app.goo.gl/kQdqTa5eWLkgkFw66

Regards

PS Sorry for posting into Sonoff and not the WebRTC repository.
