### ISSUE TITLE
4CH PRO R2 with error message in log

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#480]
Hi Alex

It is happening to me that the 4CH PRO R2 is automatically detected as a switch, all devices are created, but then I receive a recurring error, although they work fine.

My configuration.yaml is basic:

```
sonoff:
   username: !Secret
   password: !Secret
   reload: always
   scan_interval: '00: 02: 00 '
   force_update: [temperature, humidity]
   mode: auto
```

Any idea why?
Attached capture.

Greetings

![114406723-25f61180-9b7e-11eb-9421-c19431cca5be.jpg](https://user-images.githubusercontent.com/65413059/115821761-c4ce0980-a3d9-11eb-8bf6-39a4c6a6d6a5.jpg)

![114406732-27bfd500-9b7e-11eb-9cd6-b708ad086028.jpg](https://user-images.githubusercontent.com/65413059/115821778-cdbedb00-a3d9-11eb-8459-c38e9ecf64e2.jpg)

![114449756-86e80e80-9bab-11eb-913b-fd443c84cc75.jpg](https://user-images.githubusercontent.com/65413059/115821808-da433380-a3d9-11eb-9f80-34a6d69b8e41.jpg)

**Comment by AlexxIT** [comment]
Because you using `send_command` service with wrong device ID
