### ISSUE TITLE
Sonoff Dual R3 can't display "power,voltage,current" state

### ISSUE THREAD

**Issue by superman110** [AlexxIT/SonoffLAN#482]
because keyword not "power,voltage,current"

it's:
 
"current_00":1,"voltage_00":23118,"actPow_00":160,"reactPow_00":262,"apparentPow_00":308,"
"current_01":0,"voltage_01":23004,"actPow_01":0,"reactPow_01":0,"apparentPow_01":0

**Comment by AlexxIT** [comment]
This is local data or cloud or both?

**Comment by superman110** [comment]
maybe both

**Comment by seppelw** [comment]
It's both.

I copied the Init string from my DualR3 Also please notice that there is a factor on those Value. Power is /100 to get A same for Amps and Volts

`10012730ba` == Init   | {'uiid': 126, 'extra': {'manufacturer': 'SONOFF', 'model': 'DUALR3', 'sw_version': 'E32-2SW-P0 v1.2.0'}, 'params': {'bindInfos': {'alexa': ['...']}, 'version': 7, 'workMode': 1, 'motorSwMode': 2, 'motorSwReverse': 0, 'outputReverse': 0, 'motorTurn': 0, 'calibState': 0, 'currLocation': 0, 'location': 0, 'sledBright': 100, 'staMac': '3C61054B49C8', 'rssi': -79, 'overload_00': {'minActPow': {'enabled': 0, 'value': 10}, 'maxVoltage': {'enabled': 0, 'value': 24000}, 'minVoltage': {'enabled': 0, 'value': 10}, 'maxCurrent': {'enabled': 0, 'value': 1500}, 'maxActPow': {'enabled': 0, 'value': 360000}}, 'overload_01': {'minActPow': {'enabled': 0, 'value': 10}, 'maxVoltage': {'enabled': 0, 'value': 24000}, 'minVoltage': {'enabled': 0, 'value': 10}, 'maxCurrent': {'enabled': 0, 'value': 1500}, 'maxActPow': {'enabled': 0, 'value': 360000}}, 'oneKwhState_00': 0, 'startTime_00': '2021-04-27T08:49:39.321Z', 'endTime_00': '2021-04-27T08:49:42.129Z', 'oneKwhState_01': 0, 'startTime_01': '', 'endTime_01': '', 'oneKwhData_00': 0, 'oneKwhData_01': 0, 'current_00': 14, 'voltage_00': 23397, 'actPow_00': 1529, 'reactPow_00': 2641, 'apparentPow_00': 3052, 'current_01': 0, 'voltage_01': 23738, 'actPow_01': 0, 'reactPow_01': 0, 'apparentPow_01': 0, 'fwVersion': '1.2.0', 'timeZone': 2, 'swMode_00': 2, 'swMode_01': 2, 'swReverse_00': 0, 'swReverse_01': 0, 'zyx_clear_timers': True, 'switches': [{'switch': 'on', 'outlet': 0}, {'switch': 'off', 'outlet': 1}], 'configure': [{'startup': 'off', 'outlet': 0}, {'startup': 'off', 'outlet': 1}], 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}], 'uiActive': {'outlet': 0, 'time': 60}, 'getKwh_00': 2, 'getKwh_01': 2, 'cloud': 'online'}}``

**Comment by AlexxIT** [comment]
Fixed in latest master version
