### ISSUE TITLE
RF Bridge - more info

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#483]
Available attributes for Sonoff RF Bridge:
![image](https://user-images.githubusercontent.com/15225823/115910697-d06f0e00-a475-11eb-914c-2036a613d84b.png)

Would be nice to have also network-related attributes, including LOCAL connection status.
As for now RF Bridge have LAN mode.

example:
```
cloud: online
local: online
rssi: -73
```

**Comment by AlexxIT** [comment]
Not actual in latest master-version
