### ISSUE TITLE
Question: remote or local?

### ISSUE THREAD

**Issue by boelle** [AlexxIT/SonoffLAN#484]
Can i have the sonoff on a remote network and control it from my local home assistant?

I will use it to control heating of a pool that is placed at mother in law so on a different network, hence the question if the sonoff need to be on the same network as the HA

or will i be forced to use the sonoff app for this purpose?

**Comment by AlexxIT** [comment]
If the device will be on a different network, it will be controlled via the cloud. You can continue to control it from the ewelink app and from HA. Just create a second ewelink account for this purpose, as described in the readme

**Comment by boelle** [comment]
i dont have HA cloud as it cost me money and "controlled via the cloud" mean different things

there is no HA install where the sonoff will be so i just assume that either HA cloud is needed but that also means that a HA install is needed where the sonoff will be. and then HA cloud would not be needed

so thinking of it if i dont want HA where the sonoff is i would need the ewelink app

**Comment by boelle** [comment]
ooh, i did not think that was possible
let me read again, i did not understand the examples in readme very well

**Comment by boelle** [comment]
is this as simple as using the Cloud Only mode?
https://github.com/AlexxIT/SonoffLAN#cloud-only-mode
