### ISSUE TITLE
Make sence with sensor door of xiaomi and switch sonoff

### ISSUE THREAD

**Issue by V101011111100** [AlexxIT/SonoffLAN#485]
Hi!
Please, Can you help to me. How can i connect sensor door of xiaomi and switch sonoff ?. For example when i open door, switch will turn on. Thank you so much!.

**Comment by AlexxIT** [comment]
This is usual Home Assistant question. Ask it in community. No need to ask something like this in this component.

**Comment by V101011111100** [comment]
thanks
