### ISSUE TITLE
Sonoff Device DW2 WiFi unavailable after restart

### ISSUE THREAD

**Issue by provinzio** [AlexxIT/SonoffLAN#488]
My Sonoff window sensor DW2 WiFi shows as unavailable on home assistant startup, e.g. after a system restart, I use a raspberrypi with Home Assistant Supervisor (or whatever it is named right now :D).

The value is only updated after the first opening / closing of the sensor. Is it supposed to work like this or a bug? It would be nice, to fetch the value from the cloud on startup.

**Comment by AlexxIT** [comment]
Duplicate #232
