### ISSUE TITLE
SonoffLAN doesn't work on 2021.5.0

### ISSUE THREAD

**Issue by kokesh** [AlexxIT/SonoffLAN#489]
The integration doesn't work at all on release 2021.5.0

**Comment by dougiteixeira** [comment]
I also have a similar problem.  I use local mode.

Every time the home assistant is restarted, the sonoff devices are not available in the home assistant (offline).

However, if I access the eWeLink application and perform a command on each device, they are now available on the home assistant.

**Comment by flixlix** [comment]
Can confirm, doesn't toggle switches. Only fix for me now was to return to old snapshot of 2021.04.6 version

**Comment by AlexxIT** [comment]
I don't see any problems in 2021.5.0. Are there any errors in the logs?

@dougiteixeira don't use local mode

**Comment by kokesh** [comment]
Found this:
2021-05-06 12:39:26 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sonoff. Setup failed for dependencies: zeroconf
2021-05-06 12:39:26 ERROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Could not set up all dependencies.

**Comment by AlexxIT** [comment]
Well problem with [zeroconf](https://www.home-assistant.io/integrations/zeroconf/) integration. SonoffLAN can't work without it

**Comment by kokesh** [comment]
I know, but I've done nothing to my machine except the HA release update. I'm on your Windows portable HA.

**Comment by flixlix** [comment]
![image](https://user-images.githubusercontent.com/61006057/117297871-9f77db80-ae6e-11eb-8ae3-6956762897ba.png)
This is what appears in my situation

**Comment by flixlix** [comment]
Just updated the custom component from HACS, it now works! Sorry, I should've checked before.

**Comment by AlexxIT** [comment]
@kokesh Try disabling unnecessary network adapters in windows. They are the causes of zeroconf problems

**Comment by kokesh** [comment]
Thanks! Disabling NextDNS adapter on my sever helped.
