### ISSUE TITLE
The latest HA update breaks my bulb setup

### ISSUE THREAD

**Issue by tonyhkg852** [AlexxIT/SonoffLAN#493]
The brightness slider and color wheel have disappeared after I updated to HA 2021.5.0.
Bulb models: B01, B05
Please take a look. Thanks a lot!

**Comment by andyz68** [comment]
Same for me, thank you.

**Comment by CJMarais** [comment]
Same here, for all my Sonoff led strips and B05's.

**Comment by tatzu** [comment]
Same problem for me with a l1 lightstrip

**Comment by peetereczek** [comment]
Indeed, Sonoff lights are wrongly recognised now

![Screenshot_20210510-182153_Home Assistant.png](https://user-images.githubusercontent.com/42431204/117691834-9fecdb00-b1bc-11eb-9c87-a1ba642d2659.png)

**Comment by Netatout** [comment]
Same  problem for me too.

**Comment by kobusdbr** [comment]
Same Issue here

**Comment by AlexxIT** [comment]
Check latest master version. If all works fine - I'll make release

**Comment by peetereczek** [comment]
I have pulled from master, looks good with L1 LED strip

![Screenshot_20210512-210052_Home Assistant.png](https://user-images.githubusercontent.com/42431204/118030172-3cea7800-b365-11eb-98e6-e28293d3ba6e.png)

**Comment by tatzu** [comment]
working good here also, thank you AlexxIT

**Comment by Netatout** [comment]
Thank you! It works for me too.

**Comment by CJMarais** [comment]
My B05 and L1 strips are all working again. (Did not notice anything else break when updating with master)
Thank you AlexxIT

![image](https://user-images.githubusercontent.com/64300645/118071414-02ee9580-b3a8-11eb-9ff8-5c3f8829292c.png)

**Comment by kobusdbr** [comment]
Hey all. When you guys say pulling from master I am assuming that you are getting the latest code here and then copying it to HA. Is there a simple guide on what exactly I need to do?

**Comment by tonyhkg852** [comment]
Both my B01 and B05 are working nicely again. Thanks AlexxIT for bringing my bulbs back to life!

**Comment by CJMarais** [comment]
> Hey all. When you guys say pulling from master I am assuming that you are getting the latest code here and then copying it to HA. Is there a simple guide on what exactly I need to do?

I took the easy route via HACS:
Searched for the Sonoff LAN integration
-  Select "Reinstall" from the menu
-  Select "master" at the bottom of the version list

![image](https://user-images.githubusercontent.com/64300645/118098122-cfc1fb80-b3d3-11eb-8573-18a067d697ed.png)

![image](https://user-images.githubusercontent.com/64300645/118098282-fc761300-b3d3-11eb-833e-274a34984134.png)

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
