### ISSUE TITLE
Hassio support

### ISSUE THREAD

**Issue by Orayi** [AlexxIT/SonoffLAN#5]
I've tried to add your repository to the hassio addon store but respository.json is missing.

Are you able to add it please.

https://github.com/home-assistant/addons-example/blob/master/repository.json

**Comment by AlexxIT** [comment]
It's not hassio addon. It's custom component. It cannot be installed as hassio addon.
Component can be installed via hass as shown in this video:
https://www.youtube.com/watch?v=DsTqOlrQQ1k

**Comment by Orayi** [comment]
Thanks for the clarification, I'm a bit new to all this
