### ISSUE TITLE
upgrade to 0.106.2

### ISSUE THREAD

**Issue by miketree1** [AlexxIT/SonoffLAN#50]
upgrading to 0.106.2 config checker shows...  
General Errors: 
    - Component error: sonoff - No module named 'zeroconf'

**Comment by sekydig** [comment]
upgrading to 0.106.5 config checker shows same error:
  General Errors: 
    - Component error: sonoff - No module named 'zeroconf'

Although no problem in running on 0.106.2 :)

**Comment by AlexxIT** [comment]
I hope fixed in **v1.10.2**
