### ISSUE TITLE
Lights won't turn on

### ISSUE THREAD

**Issue by DragonNZ** [AlexxIT/SonoffLAN#500]
I have had the following configuration working for a few years, but after an update today to the latest
the lights will turn off, but not on.
When trying to turn on, I get the message

Failed to call service light/turn on. 'EWeLinkToggle' object has no attribute 'supported _color_modes'

Do I need to change something in my config now?

sonoff:
  username: ..@.com
  password: xxxxxxxxx
  reload: once
  devices:
    10008343ff: # lounge lights light (double switch, one light entity)
      device_class:
      - light
      - light

**Comment by AlexxIT** [comment]
Duplicate #444

**Comment by DragonNZ** [comment]
Thanks @AlexxIT working now. I didn't search well enough in the open issues to find the original issue. Sorry about that. Cheers.

**Comment by AlexxIT** [comment]
You just need to update integration
