### ISSUE TITLE
Cover King Art No more commands

### ISSUE THREAD

**Issue by djk314** [AlexxIT/SonoffLAN#502]
King Art - King Q4 Cover appear but can't open or position, just visible entity on 2.4.5, revert back to 2.4.0 and it's ok.

**Comment by pepe59** [comment]
It's the same here. Problem # 456, where I patiently wait for the correct state of open, closed. The control of the hinges worked and after the update 2.4.5 the control is not possible even by automation.

**Comment by miguelpucela** [comment]
Same here. Reverted to v2.4.3 and they worked again.

**Comment by pepe59** [comment]
Thank you very much. After update 2.4.6, the hinge control works again in automation.

**Comment by djk314** [comment]
Yes ! It's working good now ;) Thank's Alexx
