### ISSUE TITLE
Sonoff S31 current/voltage

### ISSUE THREAD

**Issue by barajasfernando** [AlexxIT/SonoffLAN#509]
Hi, I'm a newbie in Home Assistant, but learning fast :)

I'm using an S31 switch, that gives me current and voltage:

Manufacturer. Sonoff
Model: S31
Sw version: PSC-B67-GL v3.5.0
Cloud: online
Rssi: -35
Power: 0
Current: 0
Voltage: 121.01
Local: online
(yes, it's "off"now, but I'm recieving the "Voltage" variable.  Other variables change when I turn it on).

I have used your SonoffLAN plugin, and it's working beautifully, but I want to know how can I graph voltage or current on a card on Lovlace, since it only appears as an "on/off" switch.

What should I do?

Greetings from Mexico.

**Comment by AlexxIT** [comment]
You need sensors
https://github.com/AlexxIT/SonoffLAN#sensors-from-device-attributes
