### ISSUE TITLE
Статус sonoff mini после перезагрузки НА

### ISSUE THREAD

**Issue by conrad66** [AlexxIT/SonoffLAN#51]
После перезагрузки НА статус sonoff mini не отображается, вернее "неизвестно" пока не попингуешь устройство или не передернешь выключатель.
SonOff Mini в DIY MODE
Это как то можно вылечить ?

**Comment by AlexxIT** [comment]
Так бывает со всеми устройствами Sonoff после перезапуска HA. Иногда появляются за доли секунды, иногда через несколько минут. Так работает обнаружение через Multicast. Не знаю, можно ли программно поправить эту проблему.

**Comment by Gan2020** [comment]
Здравствуйте! к сожалению эта проблема не много раздражает :). Подскажите перевод в DIY режим тоже не решит эту проблему?
в вашей инструкции не совсем понятно написано как получить ключ :(

**Comment by Gan2020** [comment]
Здравствуйте! к сожалению эта проблема немного раздражает. Перевод в ручной режим (без облако)тоже не решит эту проблему?

**Comment by AlexxIT** [comment]
Это не зависит от способа настройки устройсв в ХА. Нет никакого "ручного режима".

**Comment by Gan2020** [comment]
Спасибо, за ответ.

**Comment by AlexxIT** [comment]
Попробуйте новую версию #99

**Comment by conrad66** [comment]
Отлично, спасибо, сейчас статус моментально определяется при перезагрузки НА
