### ISSUE TITLE
cost of consumption 

### ISSUE THREAD

**Issue by umarmeo** [AlexxIT/SonoffLAN#510]
Hello,

First, thank you for this great tool to manage Sonoff devices. Its ready time saving. I am using this customization for a couple of days now. I need to do following which I have not found in documentation and closed cases. 

1. Cost of consumption like today consumption is showing but the cost amount is not. I want to calculate cost as per used kwh.
2.  Consumption of last x number of days can be displayed but I am not able to get current month consumption. I have added last week consumption for per day using the code I found in closed case, which is great, but I want current month consumption.
3. cost of kwh consumed in current month.
4.  Average consumption and cost of
-  Current month
- X number of days.

Please add these features, it would be amazing if done early and it will give very insightful data directly in HA.

**Comment by AlexxIT** [comment]
Hass can do it all out of the box. Just read the manuals in the community and on the Hass website. It works with any component, not just SonoffLAN

**Comment by umarmeo** [comment]
Hello
I am newbie to these things and have no idea. I have just copied configurations from here to add consumption data for my POW R2 devices. 
Can you please share any example code here so I can dig further. 
Like what I have to add in configuration to get current month KWh?

**Comment by AlexxIT** [comment]
https://www.home-assistant.io/integrations/utility_meter/

**Comment by umarmeo** [comment]
Thanks for response, But I have already tried this. I am confused that how to use it. 
I have tried following code but getting 0.
# Example configuration.yaml entry
utility_meter:
  daily_energy:
    source: switch.sonoff_xxxxxx 
    cycle: daily
  monthly_energy:
    source: switch.sonoff_xxxxxx
    cycle: monthly

my following configuring giving me values of current usage in watts and today etc used in kwh. 

sonoff:
  username: xxxxxx@gmail.com
  password: xxxxxx
  force_update: [temperature, power]
  scan_interval: '00:00:10'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]


sensor:
- platform: template
  sensors:
    today_consumption:
      friendly_name: Today consumpion
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.sonoff_xxxxxx', 'consumption').0 }}"
    yesterday_consumption:
      friendly_name: Yesterday consumption
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.sonoff_xxxxxx', 'consumption').1 }}"
    ten_days_consumption:
      friendly_name: 10 days consumpion
      unit_of_measurement: kWh
      value_template: "{% set p=state_attr('switch.sonoff_xxxxxx', 'consumption') %}{{ p[:10]|sum if p }}"
    thirty_days_consumption:
      friendly_name: 30 days consumpion
      unit_of_measurement: kWh
      value_template: "{% set p=state_attr('switch.sonoff_xxxxxx', 'consumption') %}{{ p[:30]|sum if p }}"


Now I don't know how to calculate current month kwh usage and average usage of current month in kwh. 
Plus, I want to add electricity cost to it so I can get daily, monthly costs and average per day costs etc.

**Comment by AlexxIT** [comment]
Check answers in community. There are a thousands of people
