### ISSUE TITLE
Strange bug sonoff mini usb - auto off

### ISSUE THREAD

**Issue by enigmaspb** [AlexxIT/SonoffLAN#514]
I have two sonoff mini usb 
In last time all of mini not work correctly in HA then SonoffLAN
Then set on in web on HA - in some time (3-5 min) is switch off 
I not have any automation for this device 
I see logs and see HA is switch off device  
Then disable access HA for mini - all work good in native ewelink app in mobile. 

![image](https://user-images.githubusercontent.com/1804979/119236435-159f6200-bb40-11eb-8a53-27b81a207010.png)

![image](https://user-images.githubusercontent.com/1804979/119236451-2cde4f80-bb40-11eb-9334-9b973f9a0711.png)

**Comment by grasbeisser** [comment]
I have the same issue with Sonoff RE5V1C.

If I switch on the device in ewelink it stays on. If I switch it on via an automation it turns off after 3 mins even though it shouldn't.
A rollback to the old version solved the issue.

**Comment by AlexxIT** [comment]
You can reopen issue if it's still relevant
