### ISSUE TITLE
Repo not showing on integrations

### ISSUE THREAD

**Issue by marcos-acpc** [AlexxIT/SonoffLAN#515]
Hi, have been trying to find this repo on my integrations but no success. I tried to install the repo by HACS and manually but no success.  I'm using HA core. tried to re-install HA plug-in dozen times but still no chance.
![image](https://user-images.githubusercontent.com/47359588/119242999-d599a880-bb5a-11eb-8a99-082bb85d2879.png)
![image](https://user-images.githubusercontent.com/47359588/119243013-fe21a280-bb5a-11eb-9151-034bef2d0550.png)
![image](https://user-images.githubusercontent.com/47359588/119243025-26110600-bb5b-11eb-82dc-2c24fc23cf97.png)

**Comment by AlexxIT** [comment]
Component doesn't support integrations
