### ISSUE TITLE
Failed to call service light/turn_on. 'SonoffDimmer' Object has no attribute 'supported_colour_modes'

### ISSUE THREAD

**Issue by lazy-slob** [AlexxIT/SonoffLAN#516]
Hi All,

For some reason now from home assistant I can only turn off dimmer switch and not turn it back on because the following message appears:

Failed to call service light/turn_on. 'SonoffDimmer' Object has no attribute 'supported_colour_modes'

Any suggestions?

Dave

![Screenshot_20210523_232912_edit_227310672872085](https://user-images.githubusercontent.com/49363541/119278788-705bbb00-bc1f-11eb-84f0-f1cbd4f7c377.jpg)

**Comment by AlexxIT** [comment]
Duplicate #444
