### ISSUE TITLE
Sonoff TH firmware 3.4.0 don't work!!!

### ISSUE THREAD

**Issue by RusHome** [AlexxIT/SonoffLAN#52]
После обновления прошивки на sonoff th10 получаю такую ошибку:
 WARNING (MainThread) [custom_components.sonoff] Error when send switch to 10008ce99f

**Comment by RusHome** [comment]
Прошивка обновилась до 3.4.0

**Comment by AlexxIT** [comment]
Можно DEBUG логи и sonoff.json для этого выключателя (предварительно удалить его, чтоб он обновился)? Всю приватную информацию можно стереть.

**Comment by AlexxIT** [comment]
Fixed in **v1.10.2**
