### ISSUE TITLE
Sonoff TH10/16 doesn't show temperature with firmware version 3.4.1

### ISSUE THREAD

**Issue by vdbosch** [AlexxIT/SonoffLAN#522]
Recently bought Sonoff TH10/16 (TH16/R2), however delivered with firmware 3.4.1
At the identies in home assistant only the Switch is seen, not the temperature.

**Comment by AlexxIT** [comment]
Maybe you don't read docs?
https://github.com/AlexxIT/SonoffLAN#sensors-from-device-attributes

**Comment by vdbosch** [comment]
Sorry,


Thanks for fast feedback.


Regards,


Rob


Outlook voor Android downloaden
