### ISSUE TITLE
Noobie: Unable to connect to EweLink Cloud

### ISSUE THREAD

**Issue by alanpilz** [AlexxIT/SonoffLAN#523]
Hello,

I have installed Sonoff LAN from HACS, and updated my configuration.yaml file with my ewelink credentials. After restarting Home Assistant I am getting the following error in the logs:

Can't connect to eWeLink Cloud
1:34:54 PM – (WARNING) Sonoff (custom integration)
Login error: {'error': 404, 'msg': 'user is not exit'}
1:34:54 PM – (ERROR) Sonoff (custom integration)

Have I missed a step or is there a problem?

**Comment by tuxamat** [comment]
you need to create a new account and give full access through ewelink app
'user is not exit' - you use the same account

**Comment by alanpilz** [comment]
Thanks. I already created a new ewelink account specifically for home assistant and using that for the integration.
Update: my SonOff basic switches have appeared but my zigbee hub is shown but classes as unavailable? Still get the errors in the logs as previously described?

**Comment by tuxamat** [comment]
What hub are you using for zigbee?

**Comment by alanpilz** [comment]
SonOff Zigbee hub

**Comment by tuxamat** [comment]
It must be work without tasmota, on original flash. I'm using zigbee stick.. maybe someone else help you

**Comment by alanpilz** [comment]
Thanks… I’ve ordered a USB TTL stick to get ready to tasmotize the SonOff zigbee hub.. but surprised it didn’t pick up from my ewelink. Actually detected but as I said not available for some reason.

**Comment by AlexxIT** [comment]
I think you have some mistake in user name

**Comment by alanpilz** [comment]
Thanks Alex... I have double and triple checked my user credentials. They are correct. I created a new ewelink account specifically for Home Assistant, and verified it works using the app.
Is the Sonoff Zigbee Hub supported by this integration? The situation as of now, is that the Sonoff basic switches are now showing and working, but the Zigbee and it's children are showing but listed as unavailable.


This is my current  configuration yaml file for reference: -

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sonoff:
  username: my ewelink second account username
  password: mypassword
  force_update: [temperature]
  scan_interval: '00:05:00'
  sensor: [temperature, humidity]
 # mode: local
  reload: always  # update device list every time HA starts

**Comment by AlexxIT** [comment]
You don't have this error anymore? You may have other errors

**Comment by tuxamat** [comment]
Я так понял у него wi-fi ные устройства заработали после добавления отдельного аккаунта, а зигбишные через эвеленковский хаб нет

**Comment by alanpilz** [comment]
So I have started over with a brand new install of Home Assistant. installed HACS and the first and only integration added is SonoffLAN. And I still have exactly the same errors in my logs? Maybe I am doing something consistently wrong each time?

"Definition of insanity = doing the same thing over and over and expecting different results"

And until now I have no devices detected. I used the exact same config as last time as shown in the previous reply.
![image](https://user-images.githubusercontent.com/85150538/121438362-7dfe9800-c9b6-11eb-8084-fa91fcf6b825.png)

![image](https://user-images.githubusercontent.com/85150538/121437731-53600f80-c9b5-11eb-9540-647dc8ac0d69.png)

**Comment by alanpilz** [comment]
Additional Info

We have three ewelink accounts. One master, and two additional accounts. One for HA and one for another family member.

I am using ewelink on iOS version 4.12.0. And the Master and HA account was created using iOS. The additional family members account was created using Android version of ewelink.

I have deliberately used incorrect login credentials as a debug approach, and get the same error as if the login credentials were correct, same errors as above in the logs. (perhaps this is the clue)

Attached configuration.yaml
[configuration.zip](https://github.com/AlexxIT/SonoffLAN/files/6627391/configuration.zip)



Devices associated to the master ewelink are:

SONOFF BASICR2 with 3.5.0 Firmware x 5 Devices
SONOFF ZBBridge with 1.4.0 Firmware x 1
SONOFF Temperature and Humidity Sensors x 2 linked to the ZBBridge

**Comment by alanpilz** [comment]
Update:

After some trial and error, I used my original Master account as login credentials to access ewelink cloud and it works! The question now is why doesn't the new account that all devices are shared to work. This seems to be the root cause to my problem.
Has anyone any suggestions?
debug enabled, logs below:
![image](https://user-images.githubusercontent.com/85150538/121446678-a2627080-c9c6-11eb-9813-a6d6cef7fedd.png)

**Comment by alanpilz** [comment]
Fixed... I reverted my account settings to the secondary account and EVERYTHING is working perfectly. Even the ZBBridge and sensors are now available in HA!

Not exactly sure why and how there was a problem. Adding debug: true certainly gives useful feedback for tracing errors.

**Comment by Nowaker** [comment]
I'm having the same problem: 

```
2021-06-10 20:38:46  ERROR    sonoff_cloud  Login error: {'error': 404, 'msg': 'user is not exit'}
```

I'm not stupid, I didn't make a mistake in my login or password.

**Comment by alanpilz** [comment]
Hi.. A couple of things to check or try:

1. Have you created a new ewelink account to be used for Home Assistant?
2. If you have done the above and are using this account, try using the original account that was used when pairing the devices, but make sure you sign out of the ewelink app before trying.
3. Enable debug: true in the configuration.yaml file as follows:

`sonoff:
  username: !secret ewelink_cloud_username
  password: !secret ewelink_cloud_password
  debug: true'

4. With debug mode enabled you will get a notification badge that allows you to see what's going on in the backend.
![image](https://user-images.githubusercontent.com/85150538/121619714-9a283500-ca9b-11eb-9f2c-c735537515fc.png)

5. Start with a simple configuration and build up the configuration once you get the connection working.
`sonoff:
  username: !secret ewelink_cloud_username
  password: !secret ewelink_cloud_password`

(I am using !secrets you need to replace with your actual login credentials unless you are also using !secrets?)

6. Using terminal check to see if you have a .sonoff.json file. This file is hidden by default and cannot be seen from the file editor. Using "ls -al" in the terminal window with allow you to see the file. This file is a kind of local cache downloaded from ewelink cloud. 
7. If you have this file, try renaming it to something like .sonoff.json.bak then reboot HA and see if a new .sonoff.json file gets created. (Renaming it will force it to be re-created, that is if you are able to connect.)
8. Despite being absolutely certain your log in credentials are correct, try deleting them from the configuration file, and sign in with the intended account you plan to use with ewelink... just to make sure your account doesn't have any issues! (I believe this may have been the root cause for my problem, I was also insistent that there was no way on earth did I get this step wrong.. but will never know!)
Hope this is useful.. let me know how you get on, and good luck

**Comment by Nowaker** [comment]
> Have you created a new ewelink account to be used for Home Assistant?

That was the issue. I figured it out like 20 minutes ago. I think we need to improve README.md to better articulate the need for a second account.

**Comment by alanpilz** [comment]
Great... congrats! glad you have it sorted.. I am not sure where I read about the account info. 

@AlexxIT perhaps you can put this as a first line... e.g. "IMPORTANT : xxxxxxxxx" so this step is not missed by others.

**Comment by Nowaker** [comment]
@alanpilz @AlexxIT I'll prepare a PR tomorrow that improved README.md and makes this easily visible.

**Comment by odjhl88** [comment]
I'm going to give a newbie answer to this, but it worked for me. I wasn't able to link to HA for this same reason. I however was successful at linking eWe Link to SmartThings. I use a ST hub anyway for my Z-Wave devices. That link in-turn allowed me to see my eWe Link device in HA. Hope that helped.
