### ISSUE TITLE
4Ch PRO

### ISSUE THREAD

**Issue by zee-shany** [AlexxIT/SonoffLAN#525]
Hello,

I just wanted to check if this integration will work for 4Ch Pro version 3.4.1 ?

I have following config on my home assistant but I don't see any entities pulled from cloud. 

sonoff:
  username: example@gmail.com
  password: 123456
  mode: local
  reload: always  # update device list every time HA starts 

thanks for your response.

**Comment by zee-shany** [comment]
Edit: after a while when I switched on the relays on ewelink app the entities appeared in Home assistant, sorry for the question..

**Comment by zee-shany** [comment]
I've noticed, every time I restart Home assistant server, I have to switch on one channel from ewelink app before the switches on HA will be enabled, anyone facing similar issue. Appreciate your advise.

thanks.

**Comment by AlexxIT** [comment]
Remove line mode local from config
