### ISSUE TITLE
Sonoff S26 without devicekey

### ISSUE THREAD

**Issue by ravid007** [AlexxIT/SonoffLAN#529]
Hi,
I'm unable to setup Sonoff S26 device (1000e437da)
I keep getting 'No devicekey for device' , Appreciate any assistance here.

> 2021-06-14 09:33:09  DEBUG    main          SysInfo: {'version': '2021.6.4', 'dev': False, 'hassio': False, 'virtualenv': False, 'python_version': '3.8.9', 'docker': True, 'arch': 'armv7l', 'os_name': 'Linux', 'os_version': '5.10.17-v7+'}
> 2021-06-14 09:33:09  DEBUG    main          LOCAL mode start
> 2021-06-14 09:33:09  DEBUG    sonoff_local  10004ed795 <= Local1 | {'switch': 'off', 'startup': 'stay', 'pulse': 'off', 'pulseWidth': 500, 'rssi': -54, 'ssid': '...', 'bssid': '...'} | 7
> 2021-06-14 09:33:09  DEBUG    main          10004ed795 == Init   | {'uiid': 1, 'extra': {'manufacturer': 'coolkit', 'model': '0186', 'sw_version': 'PSA-B01-GL v3.5.0'}, 'params': {'switch': 'off', 'startup': 'stay', 'pulse': 'off', 'pulseWidth': 500, 'rssi': -54, 'ssid': '...', 'bssid': '...', 'local': 'online'}}
> 2021-06-14 09:33:09  INFO     sonoff_local  1000e437da <= Local1 | No devicekey for device
> 2021-06-14 09:42:27  DEBUG    sonoff_local  Zeroconf Removed: eWeLink_1000e437da._ewelink._tcp.local.

configuration.yaml:
```sonoff:
  mode: local
  reload: always
  debug: true
  devices:
    1000e437da:
      device_class: light
      name: mosquito
    10004ed795:
      device_class: light
      name: light
```

Thanks!
Ravid

**Comment by AlexxIT** [comment]
This device not in your account. Or you didn't restart HA after ad adding device to account

**Comment by ravid007** [comment]
If I added the device to eWelink, is that means its in the account?
That's exactly what I did with the second device.
And I also tried restarting.
Thanks.

**Comment by AlexxIT** [comment]
Do you use one or two ewelink account?

**Comment by ravid007** [comment]
One account with 2 devices

**Comment by AlexxIT** [comment]
Have you ewelink username and password in config?

**Comment by ravid007** [comment]
No, the only details in the configuration file is what I wrote.

**Comment by AlexxIT** [comment]
So integration can't get your device key from cloud

**Comment by ravid007** [comment]
But if I use LAN and not cloud? like the other device that working?
Do you have any other solution for me to try?

**Comment by AlexxIT** [comment]
You need to read docs
https://github.com/AlexxIT/SonoffLAN#config-examples

**Comment by ravid007** [comment]
I just added username and password and now both devices are working.
I don't understand why one device needs a username and password and the other doesn't, but the main thing is that both devices are working now. Thank you very much!

**Comment by AlexxIT** [comment]
Devices with enabled DIY mode works without encryption. All over devices encrypts traffic with device key. Component loads this keys automatically from cloud
