### ISSUE TITLE
Uodtae 1.10.1 with Hacs 

### ISSUE THREAD

**Issue by alesoft73** [AlexxIT/SonoffLAN#53]
Hi,
in the ultimate release after update hacs continuos It proposes the same upgrade.
Many thanks

**Comment by AlexxIT** [comment]
Not understood...

**Comment by alesoft73** [comment]
After update ver 1.10.1 with hacs (and manual) I receive notification to upgrade another version..
But is the same version.

THX!

**Comment by alesoft73** [comment]
Now work....
Many thanks
