### ISSUE TITLE
Zigbee snzb-02 sensors battery state no longer exists

### ISSUE THREAD

**Issue by popovr** [AlexxIT/SonoffLAN#531]
Hi!

After updating hass(5.4->6.5), hacs(?? -1.12.4) and sonoff lan(2.4.2->2.4.6) there is no more battery state for zigbee sensors snzb-02. Reinstalled from master - no luck.

**Comment by olibanez54** [comment]
Hi!, I also have issues with battery states, then I found that I had to include the 'battery' option inside the 'sensors' field in my /configuration.yaml as follows:

![image](https://user-images.githubusercontent.com/815460/124640638-b2e9f780-de5b-11eb-89cd-b415fb3ca2af.png)

Now I have all my Sonoff battery states

![image](https://user-images.githubusercontent.com/815460/124640849-fb091a00-de5b-11eb-8212-bc5fcd7012da.png)

**Comment by AlexxIT** [comment]
There is new name for attribute - `battery_level`
https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.4.1
