### ISSUE TITLE
fan02 speed problem

### ISSUE THREAD

**Issue by david78455** [AlexxIT/SonoffLAN#532]
Hi
I have fan02 installed
I install the component, I found the name for Fan and the name for light.
but I cant find name for the speed of the fan
for example

switch.sonoff_10005b26e9_1 is light
switch.sonoff_10005b26e9_2 is Fan
switch.sonoff_10005b26e9_3 is medium speed of the fan
switch.sonoff_10005b26e9_4 is fast speed
but with your component I only see no: 1, 2 cant see no 3,4
please help
Regards
David

**Comment by AlexxIT** [comment]
Duplicate #153
