### ISSUE TITLE
TH16 Temperature

### ISSUE THREAD

**Issue by stevewrightnz** [AlexxIT/SonoffLAN#533]
Hi
Upgraded TH16 firmware to Version 3.5.0 and Home Assistant no longer recognizes the sensor?
I've restarted, the TH16, reloaded the HACS integration and restarted HA.

![TH16](https://user-images.githubusercontent.com/2554268/123370478-e9aa4d00-d5d3-11eb-872f-61c8fed43d53.PNG)

**Comment by alesoft73** [comment]
Change the mode to start the addon on configuration.yaml to cloud...
After restart.

**Comment by stevewrightnz** [comment]
> Change the mode to start the addon on configuration.yaml to cloud...
> After restart.

Nope,  sonoff config looks like:-

sonoff:
  username: !secret email1
  password: !secret sonoff_password
  mode: cloud
  reload: always
  sensors: [temperature, power]
  force_update: [temperature, power]
  scan_interval: "00:01:00"

**Comment by stevewrightnz** [comment]
Can confirm that a quick and dirty fix seems to be detailed in issue #527 Sonoff TH 3.5.0 don't read Temperature or Humidity HA in MODE:LOCAL .

I guess @AlexxIT will fix it in an upcoming version.

Steve

**Comment by Gferretta** [comment]
> Can confirm that a quick and dirty fix seems to be detailed in issue #527 Sonoff TH 3.5.0 don't read Temperature or Humidity HA in MODE:LOCAL .
> 
> I guess @AlexxIT will fix it in an upcoming version.
> 
> Steve

Reinstall master version and fix this.

**Comment by AlexxIT** [comment]
Duplicate #527
