### ISSUE TITLE
Sonoff 433 Bridge not working in offline mode. 

### ISSUE THREAD

**Issue by orthobots** [AlexxIT/SonoffLAN#534]
Hi everyone. I'm new to Home assistant, and Sonofflan. 
 I am on the latest version of Sonofflan and i've gotten most of my sonoff devices working offline. 
My current issue is trying to get the 433mhz Bridge working when i'm in offline mode.

I've added the following to my automations.yaml

- id: '1621138990255'
  alias: Sonoff RF Receive
  trigger:
    platform: event
    event_type: sonoff.remote
  action:
    service: persistent_notification.create
    data_template:
      title: Sonoff RF Receive
      message: "Name: {{ trigger.event.data.name }} \nCommand: {{ trigger.event.data.command\
        \ }} \nTime: {{ trigger.event.data.ts }}"

- id: '1621138990256'
- alias: Consultation Maglock
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      command: 1
  action:
    service: persistent_notification.create
    data:
      message: CONSULTATION MAGLOCK PRESSED

- id: '1624855470614'
  alias: Consultation Door Offline
  description: ''
  trigger:
  - platform: event
    event_type: sonoff.remote
    event_data:
    command: 1
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.sonoff_100109d302_3
  mode: single

The first entry is to generate a notification each time a button is pressed on my RF remote.
The second entry is to generate a specific notification for a specific button on the remote to trigger a message
Third entry is for the button press to turn on a switch. 

Somehow, none of these work when the network is disconnected from the internet, ie offline mode, while the rest of the switches work fine. 

Am i doing something wrong?

**Comment by AlexxIT** [comment]
Duplicate #299
