### ISSUE TITLE
Stopped working after latest update

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [AlexxIT/SonoffLAN#546]
Home Assistant core-2021.6.4
supervisor-2021.06.8

HACS shows no error for the Sonoff integration. It loads properly I believe.

However it can't give orders to the sonoffs (can't turn a switch on, for example)

Let me know if more info is needed.

**Comment by AlexxIT** [comment]
Show your config

**Comment by Fernando-A-Rocha** [comment]
@AlexxIT I'm sorry for false information: actually only 2 of my sonoffs stopped working and they happen to have low wifi connection, so with Ewelink app I can control them but it's slow response. With HA I try to control them but it gives up and I can't on/off.

**Comment by AlexxIT** [comment]
Show your config

**Comment by AlexxIT** [comment]
Closed because no response
