### ISSUE TITLE
'version' key still missing in the manifest

### ISSUE THREAD

**Issue by Ghostbuster64** [AlexxIT/SonoffLAN#548]
STILL NOT FIXED.
" ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'sonoff' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details"
Home Assistant version 2021.7.3

**Comment by chemelli74** [comment]
This component was updated long time ago:
https://github.com/AlexxIT/SonoffLAN/blob/11c6a748404caa6435ca08fe5198bd378188187c/custom_components/sonoff/manifest.json#L9

Are yo usure you are suing SonoffLAN ?

Simone

**Comment by AlexxIT** [comment]
Fixed long time ago
