### ISSUE TITLE
iFan04 Supported?

### ISSUE THREAD

**Issue by splerman** [AlexxIT/SonoffLAN#550]
Is the iFan04 supported? Was about to order cables to flash either ESPHome or Tasmota when I discovered SonoffLAN which looks like an easier process if the device is supported. IFan04 is allegedly identical to ifan03 except it has caps for 110v fans and improved rf range.

**Comment by AlexxIT** [comment]
I don't know

**Comment by AlexxIT** [comment]
Supported
