### ISSUE TITLE
Sonoff Dual R3 Not showing Power Usage

### ISSUE THREAD

**Issue by neilhowieson** [AlexxIT/SonoffLAN#553]
Hi,

I have installed the latest files from here to enable the power reporting, but i don't pick up any power updates on the entities within HA. They are appearing, but not showing actual power usage. 

Configuration.yaml contains the below:
`sonoff:
  username: <myusername>
  password: <mypassword>
  force_update: [power]
  sensors: [power, current, voltage]`

Any guidance would be appreciated...

**Comment by guciopl** [comment]
Just to be sure - is Your device in metering mode? Dual R3 can work only as meter or only as switch. There is no option to do both simultaneously as in POW. If You are able to switch it on and off then You are NOT in metering mode.

**Comment by satyajitmishra93** [comment]
Actually in the eWeLink app we can use the DualR3 in switch mode & see the power consumption of the indivisual channels. BTW in my HA there are no Power related entities assocaited with my DualR3s. There is another big issue with DualR3 & that is; it's indivisual channels can't be controlled by Amazon Alexa voice command as the indivisual channels are not recognised as indivisual entities in the Amazon Alexa app. I was able to control the indivisual channels using Alexa Routines, but recently that has also stopped working. Also recently their power status is also not being accurately updated & the only way to update the power state is to restart HA.

**Comment by AlexxIT** [comment]
Fixed in latest master version
