### ISSUE TITLE
HA 2021.8 devices become unavailable after HA reboot

### ISSUE THREAD

**Issue by DirkMu** [AlexxIT/SonoffLAN#557]
I installed HA core 2021.8b and figured out that all of my sonoff devices are unavailable when I reboot HA. 

![image](https://user-images.githubusercontent.com/53949754/127765358-a41abdaa-e7f5-4d3e-9270-bd67902cd9de.png)

Devices: 4CHPROR3
FW 3.41

I 2021.7 and it worked fine. 
In 2021.8b the devices become available immediately when I start the eWeLink app. 

Config: 

``
sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_pass
  mode: local
  reload: always  # update device list every time HA starts
``

**Comment by AlexxIT** [comment]
Remove mode local from config

**Comment by DirkMu** [comment]
Thanks. However, I wonder why I should change my config. It worked perfectly for more than a year. It also works with HA 2021.7. Something must have changed in HA 2021.8 since the issue only occurs in this release.

**Comment by AlexxIT** [comment]
Maybe it's just a coincidence. I'll check when 2021.0 will be released. LAN protocol mDNS/zeroconf can behave very unpredictably.

**Comment by DirkMu** [comment]
Tested it with final HA 2021.8. The issue still persist.

**Comment by tuxamat** [comment]
Подтверждаю, после обновы, все, что прокинуто через Sonoff LAN отвалилось.

**Comment by tuxamat** [comment]
с облачным режимом работает

**Comment by sgbossinga** [comment]
Same here. Back to 2021.7.4 and all is fine

**Comment by urielz** [comment]
Having the same issue with 2021.8, was working fine with 2021.7.4

**Comment by IgorAga** [comment]
This is definitely mDNS issue, I had same problem after 2021.8.0 upgrade and solved it by restarting umdns daemon every minute on my OpenWRT router and all access points. However, I would appreciate to have some more simple and reliable solution.

**Comment by Ivan-Dobro** [comment]
Same issue here on 2021.8, had  to remove 
mode: local

**Comment by SunilKhusal** [comment]
I am now on 2021.8.1. I have the same issue after every restart, but noticed that after some time (about an hour), most become available, except one or two.

**Comment by IgorAga** [comment]
That's exactly the reason why I guessed to set up forced mDNS resolution on OpenWRT router. Unfortunately, you need to have an open IP infrastructure to do that, proprietary routers firmware usually does not support cron. However, if your router supports SSH or Telnet access, you may give a try.

**Comment by SunilKhusal** [comment]
@IgorAga, I have no knowledge on any of what you mentioned. All I know is it only started after the 2021.8 upgrade. My last devise became available after 2 hours.

**Comment by sgbossinga** [comment]
what to do now?

**Comment by tuxamat** [comment]
with cloud mode ok
`sonoff:
  username: mymail@gmail.com
  password: mypassword
  mode: cloud`

**Comment by jddipqd** [comment]
I'm using local only mode for DIY devices (only sonoff: in config), and it's not working with 2021.8.1
Rolled back to 2021.7.4 and it works again.

**Comment by EntingChou** [comment]
It same problem for me, back to 2021.7.4 now. ...

**Comment by EntingChou** [comment]
> It same problem for me, back to 2021.7.4 now. ...

After being upgraded to 2021.8.2, the issue is resolved.

**Comment by j0ker13** [comment]
2021.8.2 not working in local mode. Log empty

**Comment by EntingChou** [comment]
> 2021.8.2 not working in local mode. Log empty

After restart, also not working for me now...

**Comment by DirkMu** [comment]
I installed 2021.8.2 and it did not solve the issue.

**Comment by dreem2001** [comment]
The same problem with Sonoff POW. Workaround is to open eWelink app on phone. Once the app is open HA at once starts seeing the device. Magic.

**Comment by EntingChou** [comment]
> The same problem with Sonoff POW. Workaround is to open eWelink app on phone. Once the app is open HA at once starts seeing the device. Magic.

I've tried to open the app, HA load entities again. Weird.

**Comment by stevewrightnz** [comment]
Yeah, mine didn't find them until I opened the app on my phone too.  Seems a bit odd - almost like the HA login doesn't retrieve the info.   Is it actually logging in at all anymore?

Removing "mode: local" from the config seems to have fixed it for now but that is kind of beside the point if you want to run it without the cloud after the initial setup.  Maybe the entity_id name is not being stored locally anymore?

SteveW

**Comment by AlexxIT** [comment]
No any magic here. Zeroconf (mDNS) was broken in 2021.8.0
Check 2021.8.2 and 2021.8.3 with fixes
https://github.com/home-assistant/core/releases

**Comment by dreem2001** [comment]
It was just irony obviously.
Btw, 8.3 didn't bring resolution.
Not sure if ticket makes sense because nothing to fix on component side.

**Comment by AlexxIT** [comment]
mDNS problems can persist for several hours.

It's better not use `mode: local` as recommended in readme. So your devices can be controlled via cloud when you have some problems with zeroconf.

To speed up mDNS recovery you may try reboot: WiFi router, Hass server and Sonoff devices. But it's not necessary if you remove `mode` setting from integration config.

**Comment by DigitalFeonix** [comment]
I am not using the `mode: local` in my configuration and have been experiencing this issue with my S31 with all versions of 2021.8 so far.

```
sonoff:
  sensors: [power, current, voltage]
  force_update: [power, current, voltage] # trying to get info when on
  scan_interval: 00:01:00 # default 5 minutes
  devices:
    1000ff0472:
      devicekey: 99244547-add4-43e4-969a-xxxxxxxxxxxx
```

**Comment by Dutchstyler** [comment]
Same issue here on 2021.8,4 with 2 S26 sockets
Had to remove mode: local to make it work as suggested here.

**Comment by AlexxIT** [comment]
@DigitalFeonix you don't have username and password in config. So you using only LAN mode

**Comment by DigitalFeonix** [comment]
> @DigitalFeonix you don't have username and password in config. So you using only LAN mode

Isn't that a major feature of this integration? That we can use the LAN and avoid the cloud. It is in the name, Sonoff**LAN**.

**Comment by EntingChou** [comment]
updated to 2021.8.5 seems to be resolved

**Comment by ashirchkov** [comment]
I confirm, after updating to 2021.8.5 the problem was solved for me

**Comment by MichielioZ** [comment]
> 
> 
> > @DigitalFeonix you don't have username and password in config. So you using only LAN mode
> 
> Isn't that a major feature of this integration? That we can use the LAN and avoid the cloud. It is in the name, Sonoff**LAN**.

It IS a major feature for a lot of people using this, but it's actually not recommended in the readme.
@AlexxIT was just saying that by not having username and password in your config you are using the local mode, what did you think "mode: local" means ?
Also, please remember community add-ons like SonoffLAN, however great they may be, come with no guarantees and can be alpha or beta level software. I would never recommend using a community add-on for critical stuff in your house...
(and if it's not critical, you can usually wait until it's fixed, 'cause it usually will be fixed)

**Comment by DirkMu** [comment]
Resolved with 2021.8.5 and the latest zeroconf changes

**Comment by AlexxIT** [comment]
@DigitalFeonix by default all devices controls via LAN and cloud simultaneously. So if don't have internet - LAN mode so work. If you have problem with local connection (zeroconf bug in Hass 2021.8.0 - 2021.8.4) - cloud control will work.

But the choice is always yours.

**Comment by AlexxIT** [comment]
@MichielioZ what gantries you have with core addons? Official Hass release broke all zeroconf dependent integrations...

**Comment by MichielioZ** [comment]
> 
> 
> @MichielioZ what gantries do you have with core addons? Official Hass release broke all zeroconf dependent integrations...

I never said core add-ons come with guarantees, I just said community add-ons come without them.
The only guarantee an official add-on will give you is that a person other than the developer has looked at the code, which can't always be said for community add-ons.
It is not that I question how capable you are as a developer, I believe you're very capable, but literally **anyone** can make a community add-on and get it on HACS, so yes, a lot of them are not that stable and well written...

**Comment by Tamsy** [comment]
This seems to be related: 
- https://github.com/home-assistant/core/issues/54434
- https://community.home-assistant.io/t/latest-update-with-new-error/328719

**Comment by AlexxIT** [comment]
@Tamsy disabling ipv6 for the network card helps with this error. Or wait when core developers fix this problem.

**Comment by Tamsy** [comment]
> @Tamsy disabling ipv6 for the network card helps with this error. Or wait when core developers fix this problem.

Thank you for the hint @AlexxIT. Disabling ipv6 on Debian 10 for all network cards by adding "net.ipv6.conf.all.disable_ipv6 = 1" to /etc/sysctl.conf still brings up the error message although I have restarted the system. I suspect that there is still a ipv6 system call inside a docker container:

```
Logger: zeroconf
Source: /usr/local/lib/python3.9/site-packages/zeroconf/_logger.py:74
First occurred: 19:29:58 (1 occurrences)
Last logged: 19:29:58
Error with socket 39 (('fe80::5ba:f4eb:c053:4448', 5353, 0, 2))): [Errno 101] Network unreachable

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 101] Network unreachable
```

Anyway, I can live with the error in the logs until the core developers have fixed this problem. Most important is that SonoffLAN is working in local mode which it does flawlessly.

**Comment by AlexxIT** [comment]
@Tamsy Maybe you didn't apply the settings? It seems that ipv6 is still in use.

**Comment by Tamsy** [comment]
@AlexxIT, I did switch off ipv6 globally on the OS-level by adding 

```
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1

```
to /etc/sysctl.conf and commanding:

`sudo sysctl -p`

thereafter.

I will dig deeper into this matter.
