### ISSUE TITLE
Sonoff POW R3 compability

### ISSUE THREAD

**Issue by guciopl** [AlexxIT/SonoffLAN#561]
Hi,
Do You have plans to implement Sonoff POW R3 compability? It's switch which can handle 25A so it is good enough for my Air Conditioning at home. I will install it soon, but have already plugged it to network so if You want I can share device for some testing.

**Comment by bwp91** [comment]
POWR3 has exactly the same uiid and data formats as POWR2, so should work straight away

**Comment by guciopl** [comment]
Confirmed, using since few days, working like charm.
