### ISSUE TITLE
sonoff devices should appear in home assistant as what type?

### ISSUE THREAD

**Issue by glegge1** [AlexxIT/SonoffLAN#563]
hello.
Sorry for what may be a stupid question, but should sonoff devices appear as devices or entities?

alexxIT/SonoffLAN has found all my devices but added them all as entities, not devices, which makes it difficult to write automations etc that require the ability to detect switch changes (finger touching touch panel) as well as the current switch state (light on or off which this toggle touch switch operates in real life).

devices all off 'wish' as below:
Manufacturer KingArt
Model KING-N2
Sw version PSF-B04-GL v3.4.1
Cloud online
Rssi -68
Local online
thank you very much for your assistance.

config:
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sonoff:
    username: <correct gmail email address>
    password: <correct password>

**Comment by AlexxIT** [comment]
Duplicate #83
