### ISSUE TITLE
🐛 HASS won't pick up Light State

### ISSUE THREAD

**Issue by Gnaj** [AlexxIT/SonoffLAN#564]
So i have this difusser  light.sonoff_100080411b up and running on HASS but even when the light ON, the entity state remain OFF, ive been told this could be a bug on the integration side so i think this would help.

im new so i dont know what i'm doing but if need more intel about it, im happy to assist o/

**Comment by AlexxIT** [comment]
Show your Hass version, integration version and integration config

**Comment by Gnaj** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/20749038/128477354-d0813ef7-eae2-4859-a631-fefa3d75fbe4.png)
![Screenshot_6](https://user-images.githubusercontent.com/20749038/128477368-53efc4d9-a9c0-4ead-aee9-46cc81f8a747.png)

idk what do you mean by integration config? any particular file or he one with the device code?

**Comment by AlexxIT** [comment]
Is problem still actual?
