### ISSUE TITLE
Sonoff Light Strip not changing state

### ISSUE THREAD

**Issue by bogdanungureanu89** [AlexxIT/SonoffLAN#565]
Hello, 

So I have the following issue here: when working from the Lovelace Entity Card, the light strip changes brightness and color. The Brightness bar works as expected, as well as the Color Picker.

If I try to change the state using a scene, it does not work.
- id: "1628238444699"
  name: test
  entities:
    light.sonoff_1001017a80:
      effect_list:
        - Colorful
        - Colorful Gradient
        - Colorful Breath
        - DIY Gradient
        - DIY Pulse
        - DIY Breath
        - DIY Strobe
        - RGB Gradient
        - DIY Gradient
        - RGB Breath
        - RGB Strobe
        - Music
      supported_color_modes:
        - hs
      color_mode: hs
      brightness: 255
      hs_color:
        - 0
        - 100
      rgb_color:
        - 255
        - 255
        - 0
      xy_color:
        - 0.157
        - 0.05
      effect: Colorful
      manufacturer: SONOFF
      model: L1
      sw_version: PSF-BTA-GL v3.4.0
      cloud: online
      rssi: -69
      friendly_name: LivingStrip1
      supported_features: 21
      state: "on"

If I try to change the state from Developer Tools -> States, it does not work either.
![image](https://user-images.githubusercontent.com/45429109/128492160-0f564efc-be37-41e6-9fd1-7b325085f09b.png)

![image](https://user-images.githubusercontent.com/45429109/128492026-56d24d54-e82e-474b-984c-a3b6220346c4.png)

Any idead or suggestions on how I could change the state from other places aside from the UI?

Thank you!

**Comment by w1tw0lf** [comment]
Having similar issue with the light strip.  Turning it on and setting color and brightness doesn't work. It seems to work if you 1st turn the strip on and then change to what you want the effect or color to be.

**Comment by bogdanungureanu89** [comment]
I have this issue even when the lights are on.

If the lights are off I don't see the color attributes of the state. Once I turn it on and refresh, I can also see the color and brightness settings.

When the light strip is on, I try calling it like described above, and nothing happens.

A step by step tutorial on how to call it would be awesome.

**Comment by bogdanungureanu89** [comment]
So for now it seems the only way to do this is to call the lights on service with parameters. 

![image](https://user-images.githubusercontent.com/45429109/129188221-a8ce3e5c-6e59-4baf-a93f-008a0fe8d70f.png)

First you need to turn on the strip, then call it again to change it's parameters. No other way that I found.

**Comment by w1tw0lf** [comment]
That is same way I have my automation running. Turn it on, flashes for few ms, then switches to what you want it.

Don't think you can switch it via "set state"

I tried the exact same automation on a sonoff bulb that has esphome on and works exactly as needs. I believe it is because it is view the cloud that it needs to be switched on 1st. Might be wrong...

**Comment by AlexxIT** [comment]
Duplicate #513
