### ISSUE TITLE
SNZB-01 Wireless Button battery level

### ISSUE THREAD

**Issue by wishie** [AlexxIT/SonoffLAN#566]
I seem to be able to fetch the "battery_level" attribute for all of my battery powered sonoff devices, except for the SNZB-01.. is this a hardware limitation, or an issue with this integration?

**Comment by AlexxIT** [comment]
I think this is a bug. Because I can see battery level here:
https://github.com/AlexxIT/SonoffLAN/issues/223#issuecomment-699874934
Will check it.

**Comment by wishie** [comment]
I've noticed the other devices I have now seem to use ''battery_level' instead of 'battery'.

**Comment by wishie** [comment]
My wireless buttons have now started showing battery level.. out of nowhere.. very odd.

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
