### ISSUE TITLE
Stop working after update hassio 2021.8

### ISSUE THREAD

**Issue by adryzzts** [AlexxIT/SonoffLAN#570]
All device are off line after update 2021.8 and 2021.8.1, 2, 3, 4, 5 and today 2021.8.6
config is 
sonoff:
  username: !secret username
  password: !secret sonoff_password
  reload: always
  mode: local
I've changed nothing from 2021.5 or 2021.6 or 2021.7 and all working fine before version 8
Thanks

**Comment by Gferretta** [comment]
Try removing the line "mode: local"

**Comment by adryzzts** [comment]
if i remove mode local, it use cloud ? , it's important for me that system works sometimes without internet connection.

**Comment by Gferretta** [comment]
> if i remove mode local, it use cloud ? , it's important for me that system works sometimes without internet connection.
> 
> 

It's automatic
Try and comment

**Comment by adryzzts** [comment]
It's works perfect now, i remove mode local, reboot system and all is online, thank you very much

**Comment by rokam** [comment]
@adryzzts close the issue to keep it clean
