### ISSUE TITLE
Instabilities SNZB-04

### ISSUE THREAD

**Issue by rfromano** [AlexxIT/SonoffLAN#575]
Good afternoon,
I'm having some instabilities just with zigbee sensors especially the SNZB-04, that sometimes it doesn't show that the door was opened or that it was closed. At this same moment I open the eWelink app and it shows the correct status, it happens every now and then. Anyone else with this problem? Anything I can do?

**Comment by AlexxIT** [comment]
Enable debug logs and check there

**Comment by rfromano** [comment]
Thanks for the feedback, I really admire your work.

With Debug active I discovered the problem, the moment it appears "Cloud WS retrying" is the moment it doesn't register the sensor state change.
What can I do to fix this loss of communication with the cloud. This takes an average of 3 to 5 minutes.

Thank you very much.

2021-08-17 17:55:45  DEBUG    sonoff_cloud  Cloud WS retrying in 0 seconds
2021-08-17 17:55:48  DEBUG    sonoff_cloud  Cloud init: {'error': 0, 'apikey': '...', 'config': {'hb': 1, 'hbInterval': 145}, 'sequence': '1629233747998'}

**Comment by rfromano** [comment]
> Enable debug logs and check there

Thanks for the feedback, I really admire your work.

With Debug active I discovered the problem, the moment it appears "Cloud WS retrying" is the moment it doesn't register the sensor state change.
What can I do to fix this loss of communication with the cloud. This takes an average of 3 to 5 minutes.
Or after this failure it updates the status of all sensors.

Thank you very much.

```
2021-08-17 17:55:45 DEBUG sonoff_cloud Cloud WS retrying in 0 seconds
2021-08-17 17:55:48 DEBUG sonoff_cloud Cloud init: {'error': 0, 'apikey': '...', 'config': {'hb': 1, 'hbInterval': 145}, 'sequence': '1629233747998'}
```

**Comment by AlexxIT** [comment]
Have you created second ewelink account for Hass?

**Comment by AlexxIT** [comment]
Closed because no response
