### ISSUE TITLE
sonoff Ch4 switch not functioning with the integration

### ISSUE THREAD

**Issue by david78455** [AlexxIT/SonoffLAN#576]
Hi
from today the integration is not working with Sonoff ch4 . please help
I cant turn on or off the switches. I restored my home assist back one week, and the same problem
I checked with the ewelink software and the switch is ok
![ch4](https://user-images.githubusercontent.com/54178299/129877128-41dea0aa-552a-488a-9978-c0ba156a7b4b.png)
Please help
Best regards
David

**Comment by AlexxIT** [comment]
Are you using recommended config?

**Comment by david78455** [comment]
Hi,
Yes here is my configuration
sonoff:
  username: !secret ewelink_username 
  password: !secret ewelink_password
  mode: cloud
 
It was working perfect for half a year till yesterday
Regards
David

**Comment by david78455** [comment]
All other devices  are working well except the 4CH   ( FW NAME  PSF-B04-GL)

**Comment by david78455** [comment]
Please answer

**Comment by AlexxIT** [comment]
Maybe you have some errors in HA logs?

**Comment by david78455** [comment]
Hi
This is all the error log after reboot


Error doing job: Task exception was never retrieved
9:15:57 AM – (ERROR) components/upnp/device.py
Template variable warning: 'mappingproxy object' has no attribute 'distance' when rendering '{{ states.sensor.to_work.attributes.distance }}'
9:15:57 AM – (WARNING) helpers/template.py - message first occurred at 9:15:57 AM and shows up 8 times
Response Error 404: Not Found
9:15:49 AM – (WARNING) /usr/local/lib/python3.9/site-packages/pyavanza/__init__.py
Config entry 'HL-1210W E74222M9N493632' for brother integration not ready yet: Bad IPv4/UDP transport address BRN4023439D05CE.local@161: [Errno -2] Name does not resolvecaused by <class 'socket.gaierror'>: [Errno -2] Name does not resolve; Retrying in background
9:15:49 AM – (WARNING) config_entries.py - message first occurred at 9:15:46 AM and shows up 3 times
Platform systemmonitor does not generate unique IDs. ID swap_use already exists - ignoring sensor.swap_use
9:15:46 AM – (ERROR) Sensor
Your Waze configuration has been imported into the UI; please remove it from configuration.yaml as support for it will be removed in a future release
9:15:46 AM – (WARNING) Waze Travel Time - message first occurred at 9:15:46 AM and shows up 2 times
The rpi_power platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
9:15:45 AM – (ERROR) Binary sensor
The 'entity_id' option near /config/configuration.yaml:398 is deprecated, please remove it from your configuration
9:15:45 AM – (WARNING) Template - message first occurred at 9:15:45 AM and shows up 2 times
The 'unit_of_measurement' option near /config/configuration.yaml:390 is deprecated, please remove it from your configuration
9:15:45 AM – (WARNING) uptime
The 'entity_id' option near /config/configuration.yaml:561 is deprecated, please remove it from your configuration
9:15:44 AM – (WARNING) Template
Please remove extra_html_url from your frontend config. It is no longer supported
9:15:40 AM – (ERROR) Home Assistant Frontend
Lovelace is running in storage mode. Define resources via user interface
9:15:40 AM – (WARNING) Lovelace

**Comment by david78455** [comment]
Hi Alex I think I found a clue that will help you to solve that case . At the eWeLink log I see that no matter what channel of the ch4 I try to turn on via HA it says that I press “ All chaotic” see attached picture 
![Uploading 1ED8BAE0-E289-451A-96A7-C42E58D54910.png…]()

**Comment by david78455** [comment]
![B33EB44D-FCE4-4D2F-B13B-14001F42ADE4](https://user-images.githubusercontent.com/54178299/131289322-b8df8ffc-d8c4-44f3-bb22-a4693881f216.png)

**Comment by AlexxIT** [comment]
You can enable component debug logs and check something interesting there

**Comment by david78455** [comment]
Thanks Alex 
I operate the debug mode for sonoff component and you can find  the relevant error log  at the attached link 
the 4CH mac code is  100046bb67
Regards
David

https://paste.ofcode.org/35VQsDvi7nz8Qhfaq9Rf9Ej

**Comment by AlexxIT** [comment]
Oh, you have some bug in your relay. Try to reset it. Maybe remove and add again to account.

**Comment by david78455** [comment]
Alex you are a genius.  It solved my problem.  How do I invite you for a cup of coffee?  🙂

**Comment by AlexxIT** [comment]
All links in github :)
