### ISSUE TITLE
All sonoff bridge buttons get executed continuously.

### ISSUE THREAD

**Issue by iotinkognito** [AlexxIT/SonoffLAN#578]
Having a strange intermittent issue with my Sonoff bridge integrated via SonoffLAN. 
2 times this week all my remote buttons (16 of them) are getting triggered by home assistant pretty much all at once. Problem is I have learnt my alarm, aircons, lights to this and they continually turn off in a loop. Only way to fix is turn off bridge and restart home assistant. Lost where to begin!

**Comment by iotinkognito** [comment]
ShutterAllReceiverDown turned on by Automation Remote Button 3
6:45:45 PM - 1 hour ago
ShutterAllReceiverDown started by Automation Remote Button 3
6:45:45 PM - 1 hour ago
Alarm - Disarm alarm when remote or keypad has been triggered by state of binary_sensor.alarmdisarm by AlarmDisarm
6:45:45 PM - 1 hour ago
Alarm - Arm alarm when remote has been triggered by state of binary_sensor.alarmarm by AlarmArm
6:45:45 PM - 1 hour ago
AlarmDisarm turned on
6:45:45 PM - 1 hour ago
AlarmArm turned on
6:45:45 PM - 1 hour ago
AlarmHome turned on
6:45:45 PM - 1 hour ago
Automation Remote Button 8 has been triggered by event 'sonoff.remote'
6:45:45 PM - 1 hour ago
Automation Remote Button 7 has been triggered by event 'sonoff.remote'
6:45:45 PM - 1 hour ago
Automation Remote Button 6 has been triggered by event 'sonoff.remote'
6:45:45 PM - 1 hour ago
Automation Remote Button 5 has been triggered by event 'sonoff.remote'
6:45:45 PM - 1 hour ago
Automation Remote Button 2 has been triggered by event 'sonoff.remote'
6:45:45 PM - 1 hour ago
Automation Remote Button 3 has been triggered by event 'sonoff.remote'
6:45:45 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:45:45 PM - 1 hour ago
SW Doorbell turned off by Automation - Doorbell Switch Off after Timeout
6:45:44 PM - 1 hour ago
Automation - Doorbell Switch Off after Timeout has been triggered by state of switch.sw_doorbell by Automation - Doorbell Button Pressed
6:45:44 PM - 1 hour ago
Script - Doorbell On turned off by Automation - Doorbell Button Pressed
6:45:44 PM - 1 hour ago
SW Living Dining_1 turned on
6:45:44 PM - 1 hour ago
AlarmDisarm turned off
6:45:43 PM - 1 hour ago
AlarmArm turned off
6:45:43 PM - 1 hour ago
AlarmHome turned off
6:45:43 PM - 1 hour ago
SW Living Dining_1 turned off
6:45:43 PM - 1 hour ago
Script - Doorbell On turned on by Automation - Doorbell Button Pressed
6:45:43 PM - 1 hour ago
Script - Doorbell On started by Automation - Doorbell Button Pressed
6:45:43 PM - 1 hour ago

**Comment by iotinkognito** [comment]
The cycle repeated this many times across anything Sonoff. 

Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:48:05 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:48:03 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:59 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:56 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:54 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:50 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:47 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:45 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:42 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:38 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:35 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:31 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:28 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:25 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:22 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:19 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:17 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:14 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:11 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:07 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:47:02 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:59 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:57 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:54 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:50 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:48 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:45 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:42 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:40 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:37 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:32 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:30 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:26 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:23 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:22 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:18 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:15 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:13 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:10 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:07 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:46:03 PM - 1 hour ago
Automation Remote Button 1 has been triggered by event 'sonoff.remote'
6:45:59 PM - 1 hour ago

**Comment by AlexxIT** [comment]
Show your automations

**Comment by iotinkognito** [comment]
What ones the only one relevant that contains Sonoff or is used is door bell..  this just listens for door bell alarm learnt in Sonoff and turns on portico light between certain hours of day and plays a message on Google hub.

**Comment by iotinkognito** [comment]
None are related to the alarm buttons or 'blank' remote buttons.

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version
