### ISSUE TITLE
Almost Sonoff devices has been getting error when click to turn On/Off

### ISSUE THREAD

**Issue by PcOnline2004** [AlexxIT/SonoffLAN#579]
Most of Sonoff devices getting this error. I am using cloud mode.
I also downgrade to lower version but get the same (2.4.3).
My Hass is core-2021.8.8 and supervisor-2021.06.8

![SonoffLAN Error](https://user-images.githubusercontent.com/63231585/130316382-ce49d38d-d770-4482-a296-f8bf6da5d5cb.png)
 Error is "E#COS":
![SonoffLAN Error 0](https://user-images.githubusercontent.com/63231585/130316394-d150f1e8-ad4a-4ba9-972d-9c41e2e288f8.png)
Then change status to offline:
![SonoffLAN Error 1](https://user-images.githubusercontent.com/63231585/130316398-005b874c-2507-474b-a460-fe76b7fb7e8a.png)

**Comment by PcOnline2004** [comment]
I've change to local mode, the error changed to "timeout".

![SonoffLAN Error 2](https://user-images.githubusercontent.com/63231585/130317065-b2c67f22-6638-4ad5-8ddc-672f0302b978.png)

**Comment by PcOnline2004** [comment]
Convert all to Tasmota :)
Thank you AlexxIT

**Comment by AlexxIT** [comment]
Oh. It's best to use auto mode. Works fine local+cloud
