### ISSUE TITLE
No input from switches

### ISSUE THREAD

**Issue by marktillo** [AlexxIT/SonoffLAN#58]
Noob to Ha, installed configured and able to see sonoff rf bridge in entities, i've set up the automation as per the instructions, and within the Ewelink app, however when i open a door or press my doorbell nothing is fired in ha. Am i missing something simple? Help me Obi Wan you're my only hope

**Comment by AlexxIT** [comment]
The bridge card displays the last message received. First look there. May the force be with you!
![download-2](https://user-images.githubusercontent.com/511909/76556828-5830cd80-64ab-11ea-87ed-abccb7cb29fd.png)

**Comment by marktillo** [comment]
Ok so I have no idea where to go now 🙌🏻 Hold my hands up in over my head. All I want is my doorbell to ring. I hope the force is strong with you 😉 ![6C9ED867-586D-4D8E-97DE-8F52A8F95D7D](https://user-images.githubusercontent.com/32182400/76570130-95e22600-64ac-11ea-80d6-81b5d4ad108d.jpeg)
![4C2B58ED-38A6-42C6-AAE4-CD37597CD9ED](https://user-images.githubusercontent.com/32182400/76570133-98448000-64ac-11ea-94e9-2624c6ec16be.png)

**Comment by AlexxIT** [comment]
Check this video, maybe it will help.
https://www.youtube.com/watch?v=QD1K7s01cak
