### ISSUE TITLE
Лампочки ewelink

### ISSUE THREAD

**Issue by 4tomson** [AlexxIT/SonoffLAN#583]
Приветствую! Во первых, спасибо за прекрасную работу!
А вот вопрос про лампочки, они сейчас самые дешёвые из аналогов, проблема только в интеграции. Родная через аддон ставится, Алиса их не видит через смартхоум
А если через эту интеграцию, то видит. Но нету цветного режима! Только эффекты. В ХА тоже само собой нету переключения цвета. Можно добавить? Спасибо!

**Comment by 4tomson** [comment]
В общем, даже не так. Поддержка всего есть. Но через режим. Обычно лампочка сразу видится как белая и ргб одновременно. А тут в режиме white регулируется цветовая температура, в режиме color цвет. Что характерно, Алиса тоже видит ее как белую ИЛИ цветную, в зависимости от режима в хоум ассистант. Мелочи какой то не хватает! Как ее сделать И белой И цветной для программ?

**Comment by AlexxIT** [comment]
Лампочка не может быть белой и цветной одновременно. Белый режим для цветной лампочки создан искуственно

**Comment by 4tomson** [comment]
Ну так не одна такая лампочка, от туи по другому выглядят. Вот сразу оба режима. И алиса умеет и цвет и температуру менять. 
![IMG_20210831_202733](https://user-images.githubusercontent.com/75882358/131548660-49125ef1-f182-44ed-af0b-3b8c0bd01f3e.jpg)

**Comment by 4tomson** [comment]
Как сделать лампочки от евелинк в таком же варианте? Это же наверняка не сложно?

**Comment by AlexxIT** [comment]
Что-то новенькое, видимо недавно появилась такая поддержка в ХА, посмотрю по возможности

**Comment by 4tomson** [comment]
И да, лампочка и белая и цветная. У нее 5 наборов светодиодов. Белые холодные, белые теплые, красные синие и зелёные

**Comment by 4tomson** [comment]
И тогда и Алиса умеет лампочку крутить в любой режим. А иначе только в том, что выбрано в хоум ассистант. А когда можно ждать и надеяться на изменения?)
![IMG_20210831_203438](https://user-images.githubusercontent.com/75882358/131549773-889b698e-c127-4ad4-bd3f-6ba8d4b777bc.jpg)

**Comment by AlexxIT** [comment]
Ой не скоро. Десятки неотвеченных issue по всем проектам. Зашиваюсь :)

**Comment by 4tomson** [comment]
> Ой не скоро. Десятки неотвеченных issue по всем проектам. Зашиваюсь :)

Я соображаю в программировании, может подскажешь, куда копать, помогу?

**Comment by AlexxIT** [comment]
Ну как куда. Смотреть чем отличает `light.py` в компоненте Tuya от компонента SonoffLAN

**Comment by 4tomson** [comment]
Подозреваю, что https://developers.home-assistant.io/docs/core/entity/light/
Надо ему сказать что то типа
supported_color_modes
COLOR_MODE_WHITE
COLOR_MODE_RGB
COLOR_MODE_COLOR_TEMP

Пока только начал читать

**Comment by 4tomson** [comment]
def supported_features(self):
        if self._mode == 'color':
            return SUPPORT_BRIGHTNESS | SUPPORT_COLOR | SUPPORT_EFFECT
        elif self._mode == 'white':
            return SUPPORT_BRIGHTNESS | SUPPORT_COLOR_TEMP | SUPPORT_EFFECT

А если вот тут вот так
elif self._mode == 'mix':
            return SUPPORT_BRIGHTNESS | SUPPORT_COLOR_TEMP | SUPPORT_EFFECT | SUPPORT_COLOR

**Comment by 4tomson** [comment]
<html>
<body>


SUPPORT_COLOR | Controls the color a light source shows. This is deprecated and will be removed in Home Assistant 2021.10.
-- | --
SUPPORT_COLOR_TEMP | Controls the representation a light source shows based on temperature. This is deprecated and will be removed in Home Assistant 2021.10.


</body>
</html>

**Comment by 4tomson** [comment]
В общем, ничего не понимая в питоне и ХА, замутил наугад  так и все заработало:
        if self._mode == 'color':
            return SUPPORT_BRIGHTNESS | SUPPORT_COLOR | SUPPORT_EFFECT  | SUPPORT_COLOR_TEMP 
        elif self._mode == 'white':
            return SUPPORT_BRIGHTNESS | SUPPORT_COLOR_TEMP | SUPPORT_EFFECT | SUPPORT_COLOR 


  if ATTR_HS_COLOR in kwargs:
            mode = 'color'
        if ATTR_COLOR_TEMP in kwargs: 
            mode = 'white'
        br = kwargs.get(ATTR_BRIGHTNESS) or self._brightness or 1
        hs = kwargs.get(ATTR_HS_COLOR) or self._hs_color or (0, 0)
        rgb = color.color_hs_to_RGB(*hs)

        ct = kwargs.get(ATTR_COLOR_TEMP) or self._temp or 153

        payload['ltype'] = mode
        payload[mode] = {
            'br': int(round((br - 1.0) * (100.0 - 1.0) / 254.0 + 1.0)),
            'ct': int(round((500.0 - ct) / (500.0 - 153.0) * 255.0)),
            'r': rgb[0],
            'g': rgb[1],
            'b': rgb[2]
        }


Если норм, может внедрить в код?

**Comment by 4tomson** [comment]
if 'ct' in state:
                # 0..255 => 500..153
                ct = state['ct']
                self._temp = round(500.0 - ct / 255.0 * (500.0 - 153.0))
             **#   self._hs_color = None**

            if 'r' in state or 'g' in state or 'b' in state:
                self._hs_color = color.color_RGB_to_hs(
                    state.get('r', 0),
                    state.get('g', 0),
                    state.get('b', 0)
                )
            **#    self._temp = None**

**Comment by 4tomson** [comment]
В принципе, ключевое тут: 
if self._mode == 'color':
return SUPPORT_BRIGHTNESS | SUPPORT_COLOR | SUPPORT_EFFECT | SUPPORT_COLOR_TEMP
elif self._mode == 'white':
return SUPPORT_BRIGHTNESS | SUPPORT_COLOR_TEMP | SUPPORT_EFFECT | SUPPORT_COLOR

и тут:
if ATTR_HS_COLOR in kwargs:
mode = 'color'
if ATTR_COLOR_TEMP in kwargs:
mode = 'white'

**Comment by 4tomson** [comment]
но в следующей уже получается версии, работать не будет? 
@property
    def supported_color_modes(self):
        return  {COLOR_MODE_HS, COLOR_MODE_COLOR_TEMP}

Вот так надо?

**Comment by AlexxIT** [comment]
Если есть рабочий фикс, просьба сделать pull request.

**Comment by 4tomson** [comment]
А как это сделать?
