### ISSUE TITLE
Best way to automate turning sonoff devices on and off?

### ISSUE THREAD

**Issue by sddgit** [AlexxIT/SonoffLAN#584]
This is down to my beginner status, but what's the best way to control sonoff devices using scripts or automations? Using the Scripts and Automations GUI, when I pick an Action Type of Device, the sonoff devices don't appear. Why is this? I can, however, pick an Action Type of "Call service", use the generic Home Assistant Turn On service, and find them under Entity. Can anyone help out my understanding as to why this is? Is this the best way to control them? Thank you.

**Comment by AlexxIT** [comment]
Duplicate #83

**Comment by sddgit** [comment]
Apologies I didn’t find this duplicate. Should have searched harder!
