### ISSUE TITLE
Consumption attribute problem, when disabled the switch entity

### ISSUE THREAD

**Issue by sipimokus** [AlexxIT/SonoffLAN#585]
Dear Alex!

Thank you very much this project, very helpfully and cool! :)

I have a power meter from Aliexpress (PSF-X67), work everything good, I see these sensors, and all have a "consumption" attribute:
- sensor.sonoff_1000xxxxxx_current
- sensor.sonoff_1000xxxxxx_power
- sensor.sonoff_1000xxxxxx_voltage
- switch.sonoff_1000xxxxxx

This device is my home main power meter.
I want to disable this switch entity in HASS under "Config -> Entities", because of "security reasons", mainly for possible power off accidents... :)

Problem:
If I disable this entity, the last 100 days "consumption" attribute is disappear from all sensors.
Can I use the consumption attribute without this switch entity, or no way?

Best regards,
Sipi

**Comment by AlexxIT** [comment]
I think latest beta-version helps with your problem:
https://github.com/AlexxIT/SonoffLAN/releases

**Comment by sipimokus** [comment]
Thank you the update, very cool the new working method, but i have problem.

After update (master or 3-beta releases) i lost my devices, did not found in devices list.
Error messages:
1. ERROR: `E-welink Power Meter Update: Error executing script. Service not found for call_service at pos 1: Unable to find service sonoff.update_consumption` (Similar: #765)

2. ERROR: `UNKNOWN cloud device: {'action': 'update', 'deviceid': '1000fcxxxx', 'apikey': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx', 'userAgent': 'device', 'params': {'power': '890.50', 'voltage': '231.97', 'current': '4.26'}, 'from': 'device'}`

3. ERROR: `UNKNOWN cloud msg: {'action': 'reportSubDevice', 'deviceid': '100103xxxx', 'apikey': 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx', 'userAgent': 'device', 'd_seq': 46868, 'params': {'state': 0, 'subDevices': [{'subDevId': '6626ce2400xxxxxx', 'uiid': '1770', 'deviceid': 'a48000xxxx', 'online': True}, {'subDevId': '6626ce2400xxxxxx', 'uiid': '1009', 'deviceid': 'a48000xxxx', 'online': True}, {'subDevId': '6626ce2400xxxxxx', 'uiid': '1770', 'deviceid': 'a48001xxxx', 'online': True}, {'subDevId': '6626ce2400xxxxxx', 'uiid': '1770', 'deviceid': 'a4800xxxx', 'online': True}, {'subDevId': '6626ce2400xxxxxx', 'uiid': '1770', 'deviceid': 'a48001xxxx', 'online': False}]}}`

4. WARN: `Source: custom_components/sonoff/__init__.py:15` - `Can't login: , mode: auto`

5. WARN: `Config entry 'xxxx@gmail.com' for sonoff integration not ready yet: None; Retrying in background`

**Comment by AlexxIT** [comment]
1 deprecated

Other errors because some problems with login to cloud servers. How many Sonoff integrations on your configuration > integration page?

**Comment by sipimokus** [comment]
1. I used this to watch live data, is there a solution instead?

I have only one Sonoff integration on the site.

Now I removed old configuration, disable update_consumption automation, and do these steps: 
remove integration -> restart hass -> add integration -> restart hass, but I got these log-s:
```
Logger: homeassistant.config_entries
Source: config_entries.py:366
First occurred: 15:42:37 (1 occurrences)
Last logged: 15:42:37

Config entry 'siposcsalad16@gmail.com' for sonoff integration not ready yet: None; Retrying in background
```
---
```
Logger: custom_components.sonoff
Source: custom_components/sonoff/__init__.py:150
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 15:42:37 (1 occurrences)
Last logged: 15:42:37

Can't login: , mode: auto
```
---

Info: working other sensors (button, temperature, 4ch switch), but these are only ZB devices, I don't have Wifi devices except this power meter.

**Comment by AlexxIT** [comment]
Maybe you have more detail error in full Hass log?

**Comment by sipimokus** [comment]
I was made a mistake, I logged with one account in same time with mobile app and hass. 
With shares and different users it is looks like good, the power meter works! :)

The login errors reamined:
```
2022-04-25 18:24:53 INFO (MainThread) [homeassistant.setup] Setting up sensor
2022-04-25 18:24:53 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds
2022-04-25 18:24:54 WARNING (MainThread) [custom_components.sonoff] Can't login: , mode: auto
2022-04-25 18:24:54 WARNING (MainThread) [homeassistant.config_entries] Config entry 'new-address-xxxx@gmail.com' for sonoff integration not ready yet: None; Retrying in background
```

Later no repeated the problems, it's work:
```
2022-04-25 18:25:05 DEBUG (MainThread) [custom_components.sonoff] 15 devices loaded from Cache
...
2022-04-25 18:25:19 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] Connected to cloud
2022-04-25 18:25:19 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] 1000fcfb9f => Cloud4 | {'uiActive': 7200} | 1650903919000
2022-04-25 18:25:20 DEBUG (MainThread) [custom_components.sonoff.core.ewelink] 1000xxxxxx <= Cloud3 | {'power': '502.40', 'voltage': '234.04', 'current': '2.40'} | None
...
```
