### ISSUE TITLE
Device not shown for automations

### ISSUE THREAD

**Issue by SirMartin** [AlexxIT/SonoffLAN#586]
Hi,

I tried to search for this issue, but couldn´t find anything here, but sorry if someone has asked for that before.

I have a plug that I use to control my TV, and I want to make some automation to turn off when I disconnect my phones wifi. The issue, is that I cannot find the device on the automation page, in developer tools I can see the entity (I used in other cards in the Lovelace), and I can see that is under a device (I think, see the attached pictures), but this one does not appear in the list of devices inside automation.

Inside developer tools, I can find the sonoff entity (under the Plug_Salon_TV device?)
![image](https://user-images.githubusercontent.com/854646/131979193-8e6251d2-8291-45b1-9629-8ea5d29bd520.png)

Here in automation´s device list, nothing is visible.
![image](https://user-images.githubusercontent.com/854646/131979330-081fd102-55fa-49a7-af4a-5e539a45c6d2.png)

Is this normal behaviour? Any idea?

Thanks in advance for your great work!

**Comment by AlexxIT** [comment]
Pinned issue... #83
