### ISSUE TITLE
Virtualbox still not good for local mode?

### ISSUE THREAD

**Issue by sddgit** [AlexxIT/SonoffLAN#589]
I have Hassio running under Virtualbox  on a Mac, and am about to install some Sonoff switches. I’m thinking about using DIY mode (no real need for cloud control), but I’ve read here that VB has problems with Multicast. Is that still the case?

If I go for a default cloud+local config instead, how does this integration accomplish communication across the LAN? Does it still use Multicast? Would VB still be a problem in this configuration, and therefore all communication would end up being via the cloud?

Excuse the newbie questions…

**Comment by AlexxIT** [comment]
If the integration detects devices in the local network - they will be managed locally. Otherwise - via the cloud

**Comment by sddgit** [comment]
Thanks. My concern is that local communication would need Multicast, and I've read that Virtualbox gets in the way of that. Any thoughts on that front?

**Comment by AlexxIT** [comment]
I'm not using VirtualBox, but heard about problems with Multicast with it. But cloud connection usual works fast and fine

**Comment by sddgit** [comment]
OK, thank you.
