### ISSUE TITLE
POW2

### ISSUE THREAD

**Issue by rhgiter** [AlexxIT/SonoffLAN#59]
it only show voltage / current / power   when i turn it off?

**Comment by wiktorvip** [comment]
For me it's refreshing voltage / current / power attributes only when I login to app, in other case value are static and are not refreshing dynamically.

**Comment by rhgiter** [comment]
ok thanks for info
maybe you could write it in the documentation?
/René


Den fre. 13. mar. 2020 kl. 12.10 skrev wiktorvip <notifications@github.com>:

**Comment by AlexxIT** [comment]
I think problem similar #14

**Comment by oncleben31** [comment]
Same problem here. POW attributes are not updated after switch go to off.

**Comment by alesoft73** [comment]
I cofirm i have the same problem vesion 1.10.3
Sonoff firmware 3.4.0

**Comment by AlexxIT** [comment]
The solution is here #14

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#refresh-interval-for-th-and-pow
