### ISSUE TITLE
problem with TH16 I can't create automation with relay.

### ISSUE THREAD

**Issue by Whastie** [AlexxIT/SonoffLAN#592]
I have a sonoff with temperature probe and if I can see the status of the temperature and switch the relay from the lovelye.
The problem is that when I want to generate an automation that activates the relay depending on the temperature, it won't let me. Why the relay does not appear in the list of devices.
The sonoff relay does not appear in the list of automation devices
Could you help me?
![foto1](https://user-images.githubusercontent.com/89639919/133152888-8f07ecff-443a-4ac5-acc5-a073be29a96e.JPG)
![foto2](https://user-images.githubusercontent.com/89639919/133153127-6244432c-f579-4aa7-a2fe-bc13d958c9b7.JPG)
![foto3](https://user-images.githubusercontent.com/89639919/133153135-6001dc59-c8d0-4e37-aa62-ef335ede9a20.JPG)

**Comment by Gferretta** [comment]
Use the "Numeric Value" for temperature sensor and switch.turn_on to switch

**Comment by Whastie** [comment]
excuse me,
can you give me an example?
I do not get the switch in the list of devices

**Comment by Gferretta** [comment]
[https://user-images.githubusercontent.com/89639919/133152888-8f07ecff-443a-4ac5-acc5-a073be29a96e.JPG](https://user-images.githubusercontent.com/89639919/133152888-8f07ecff-443a-4ac5-acc5-a073be29a96e.JPG)

1st is relay and can use with switch.turn_on services

**Comment by Gferretta** [comment]
alias: Acuarium ON
description: ''
trigger:
  - below: '14.99'
    entity_id: sensor.10012a24c9_1
    for: '00:00:30'
    platform: numeric_state
condition: []
action:
  - data: {}
    entity_id: switch.10012a24c9
    service: switch.turn_on
initial_state: true

**Comment by AlexxIT** [comment]
Duplicate #83

**Comment by Whastie** [comment]
Thank you very much, problem solved !!
