### ISSUE TITLE
One device - some entities local:online, others local:offline

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#596]
Please help to troubleshoot - why entities from SAME device have different local communication status:
![image](https://user-images.githubusercontent.com/15225823/134547548-ebbb0c11-38e8-4f10-8d08-12d02d589948.png)

This is not for a short moment, it stays so for an hours already. Temperature and humidity reading arrives in HA fine.

**Comment by Gferretta** [comment]
I has the same issue

**Comment by Masterz69** [comment]
Now TH16 device is powered OFF. In that case:
- switch.TH16 entity is unavailable;
- sensor.TH16 _temperature & _humidity still cloud:online & local:timeout.

**Comment by Masterz69** [comment]
Sensors become unavailable only after HA core restart.
If/when device become offline - sensor entities does not reflect this change & still "available".

**Comment by amaciuc** [comment]
> Sensors become unavailable only after HA core restart. If/when device become offline - sensor entities does not reflect this change & still "available".

Why is that?

I checked the `.config.json` file updated by `sonoff` integration and there can be found some infos like `onlineTime` & `offlineTime`. 
![image](https://user-images.githubusercontent.com/19391765/136914532-753496b4-da90-46da-a8b2-9559b9780d3b.png)

Therefore, the status of the entity in HA should be reflected. Maybe, this can be a feature request?

**Comment by AlexxIT** [comment]
This is bug in sonoff firmware. It blocks local requests. Usually helps reboot device with cut off power. Sometimes helps Hass reboot or/and WiFi router reboot

**Comment by AlexxIT** [comment]
The problem is not relevant in the new version
