### ISSUE TITLE
Devices unavailable after upgrade from 2021.9.6 to 2021.9.7

### ISSUE THREAD

**Issue by whalik** [AlexxIT/SonoffLAN#597]
After upgrading Home Assistant to 2021.9.7, few devices became unavailable.  I believe sonoff v3.5 and 3.6 were the ones affected. They worked again soon after restoring 2021.9.6.  The device acted normally from native ewelink.
Is this a new incompatibility issue?

**Comment by AlexxIT** [comment]
Is problem still actual?

**Comment by whalik** [comment]
I skipped that version (i.e. 2021.9.7) and I have not encountered this
problem since then. Im now at 2021.11.3 without any issues.
