### ISSUE TITLE
sonoff, S26

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [AlexxIT/SonoffLAN#598]
hi, thankds for your jobs nice work !

i'm trying to use my s26 sonoff over my shell with a simple post request from lan, can you say me why nothing happen with this request ?

` wget -O- --post-data='{"sequence": $(date +%s%3N), "selfApikey": "this-is-my-api-key","deviceid":"646545qsd","data":{"switch":"on"}}' --header=Content-Type:application/json "http://192.168.100.2:8081/zeroconf/switch"
--2021-09-26 14:51:05--  http://192.168.100.2:8081/zeroconf/switch
Connecting to 192.168.100.2:8081... connected.
HTTP request sent, awaiting response...`

seems to be stuck on "awaiting response"

**Comment by AlexxIT** [comment]
Because your requests should be encrypted with device secret key
