### ISSUE TITLE
Sonoff Dual R3 current/voltage/power 01 mixed with 02

### ISSUE THREAD

**Issue by sctale** [AlexxIT/SonoffLAN#599]
I have two dual r3 switches, and I set both of them in switches mode. As you know, dual r3 has power sensor, but hass could not show the power sensors now, will it be fixed in future versions?

**Comment by sctale** [comment]
Hello Alex, just ignore it, I reinstalled the master version, and it works well. Thank you for your good work.

**Comment by sctale** [comment]
![Snipaste_2021-09-26_22-51-23](https://user-images.githubusercontent.com/18475722/134814931-c2d96ad8-4b85-4853-ab97-f15a9090fb92.png)
Work strangely.

**Comment by sctale** [comment]
After I removed "mode: local", it works well. But can I still control them locally?

**Comment by AlexxIT** [comment]
If you can see local online in device info - you can control them locally.
