### ISSUE TITLE
Cannot login with my phone

### ISSUE THREAD

**Issue by ebattulga** [AlexxIT/SonoffLAN#6]
My eWeLink user name is not a email. It is phone number with country code. 
I'm trying to set my phone number to username field in configuration. But don't work.

**Comment by AlexxIT** [comment]
Login with phone discussed here #3 
I don't know how create ewelink account with phone. And can't test by myself.

**Comment by afsi27766** [comment]
hi alexxit
i jave 2 question about home assistant :
1- how to enable guard for zndmwg02lm?
2- when getway added in home assistant , after discore tempture and humid sensor buy it couldnt show another sensor foe xiaomi module ?

**Comment by AlexxIT** [comment]
1. This is wrong repo
2. Guard is activated via the alarm entity
3. Didn't understand about the sensor
