### ISSUE TITLE
SONOFF without LAN issue on reboot

### ISSUE THREAD

**Issue by mikebargauan** [AlexxIT/SonoffLAN#60]
I have installed HA(0.107.1) + SonoffLan + floorplan with n 3 sonoff and 3 coolkit 4ch devices - work fine! - no internet and no other devices.
But if HA (raspberry3+) reboots, all devices are unavailable.
I need to turn on some android with eWeLink app, let the app refresh and all devices work again.
Or power cycle (power off/on) all devices after HA is ready, but usually we do have same power source for all.

Any suggestion? 
I can setup VPN/remote connection or send config directory if needed.

Thanks
Mike

**Comment by elektrostarek** [comment]
I have same problem with sonoff basic after upgrade to 3.4.0 firmware.

**Comment by Monacoslo** [comment]
I have similar problem with iFan02. Devices after a while become unawailable untill I turn them manually on in eWelink app. I have different account (shared devices) for HA to avoid logout.

**Comment by AlexxIT** [comment]
Multicast works very badly if devices change IP address.

**Comment by mattsaxon** [comment]
@AlexxIT hopefully latest version of zeroconfg here https://pypi.org/project/zeroconf/ (0.26.0) addresses this issue.

It's not been merged into HA yet, but hopefully will be shortly

**Comment by AlexxIT** [comment]
@mattsaxon excellent. I'll wait until the library is updated in HA.

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by AlexxIT** [comment]
Version 2 should handle all the problems.
