### ISSUE TITLE
Sonoff cloud-connected devices becomes unavailable every couple of minutes 

### ISSUE THREAD

**Issue by AlessandroTischer** [AlexxIT/SonoffLAN#607]
I have some sonoff devices connected to my home assistant. Some of them are locally connected, and they work flawlessly. I also have two other networks (away from home) where I have a 4g modem router and some sonoff in each one.
These are cloud connected to my home assistant at home.
Everything works fine, except that all my cloud-connected devices keep becoming unavailable for a couple of seconds.
~~I don’t think it’s a network problem, since they are always on in the ewelink app (using the main account which shares the devices to a secondary one that's used by HA).~~ (**Edit 2:** I found out that the devices go offline on ewelink too.)
I would have no problem with this situation, but I can’t have reliable automations.

Would it be possible to keep last state if device becomes unavailable for less than a minute?

**Comment by AlexxIT** [comment]
I think you did not create a second ewelink account as described in the readme

**Comment by AlessandroTischer** [comment]
> I think you did not create a second ewelink account as described in the readme

I did!

**Comment by AlexxIT** [comment]
Are you sure no one and no other soft using this credential?

**Comment by AlessandroTischer** [comment]
> Are you sure no one and no other soft using this credential?

100%. I created it just for HA

**Comment by AlexxIT** [comment]
There may be some problems with your Internet

**Comment by AlessandroTischer** [comment]
> There may be some problems with your Internet

To both my 4g connections (300km apart one from the other)? I doubt...😓

**Comment by AlexxIT** [comment]
> I found out that the devices go offline on ewelink too

So this is not a problem with integration
