### ISSUE TITLE
Fan not compatible with new "preset_mode" API

### ISSUE THREAD

**Issue by piticent123** [AlexxIT/SonoffLAN#608]
As it turns out, `fan.py` uses some [deprecated properties](https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties) that are going away soon. It is currently functional, but there are some caveats. Mainly that at some point™️, the old API will go away (at the earliest, 2022), and will cease to function entirely.

The reason I ran into this is because I was trying to use [this LoveLace widget](https://github.com/finity69x2/fan-mode-button-row), and because this integration doesn't implement the new API, it wasn't working. 

So, naturally, I went poking around the filesystem and found the python file for the fan entity in there and started tinkering until it worked. I would be happy to either make a pull request (feedback is of course welcome - I haven't looked at the rest of the repo, so there are probably conventions I broke) or supply my working code in a comment here for you to integrate however you'd like. Or, of course, you can say you won't migrate. That's always an option :)

**Comment by bdraco** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/621

**Comment by AlexxIT** [comment]
Fixed in latest release https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.4.7
