### ISSUE TITLE
Sonoff RF Bridge events as Sensors

### ISSUE THREAD

**Issue by maciak** [AlexxIT/SonoffLAN#61]
Hi,
Is there any way I could show events from my bridge sensors like motion and door/window to show as entities in lovelace? So I could just see if motion is triggered by sensor as an icon there.

**Comment by greengo1** [comment]
I would also be interested how to implement it!

**Comment by AlexxIT** [comment]
#37 They don't have "off" signal, only "on" signal. How they can be a sensor?

**Comment by maciak** [comment]
Yeah, that's a good one ;)They could fire for 1sec or specified period and then go auto-off

**Comment by AlexxIT** [comment]
This is called an event. And now bridge fire events.

But there are so many such requests - I will think about the implementation of sensors.

**Comment by maciak** [comment]
Thank you so much! :)

**Comment by Viper2666** [comment]
Hello, alexxit.
Thanks a lot for your works. 
I have a problem:
I perectly used your system send/receive whith sonoff bridge. 
But from yesterday sonoff.remote doesn't work. What can I do?

**Comment by AlexxIT** [comment]
@Viper2666 check https://github.com/AlexxIT/SonoffLAN/releases/tag/v1.10.3
I fixed the receive. But did not test sending.
Let me know if the problem remains.

**Comment by Viper2666** [comment]
Great!!!!
Now it's working!!
Thanks a lot!!

**Comment by Viper2666** [comment]
doesn't work again😔😔😔

**Comment by horus61** [comment]
Hi everyone. I am a novice and I wanted to ask you for help with the application in question. I developed this automation that turns on a lamp as a test when the sensor detects water on the floor. I would like to display the dry or wet status of the sensors on a card with icons for each sensor and possibly display the alarm timestamp. Thanks for the tip and good evening

**Comment by AlexxIT** [comment]
@horus61 there is how-to video in readme

**Comment by AlexxIT** [comment]
Supported RF sensors in latest release https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.2.0

**Comment by narcisrazvanpopescu** [comment]
Hi Alexxit, I have this error in configuration.yaml:
Invalid config for [sonoff]: expected a dictionary for dictionary value @ data['sonoff']['rfbridge']['PIR sensor']. Got 'PIR_01'
expected a dictionary for dictionary value @ data['sonoff']['rfbridge']['device_class']. Got 'motion'
expected a dictionary for dictionary value @ data['sonoff']['rfbridge']['timeout']. Got 60. (See /config/configuration.yaml, line 74). 
And I don't understand why. In configuration.yaml I have:
sonoff:
  username: <email>
  password: <password>
  reload: always
  force_update: [temperature, power]
  scan_interval: '00:05:00'
  sensors: [temperature, humidity, power, current, voltage]
  debug: true
  rfbridge:
    PIR sensor: PIR_01
    device_class: motion
    timeout: 60

Hassio v.0.111.4 on RPI 3+
I try to create sensors for DW1 and PIR but can't figure out how to use your example. Please help! Thank you!

**Comment by AlexxIT** [comment]
@narcisrazvanpopescu 

```yaml
sonoff:
  username: <email>
  password: <password>
  reload: always
  force_update: [temperature, power]
  scan_interval: '00:05:00'
  sensors: [temperature, humidity, power, current, voltage]
  debug: true
  rfbridge:
    PIR_01:
      device_class: motion
      timeout: 60
```

If `PIR_01` is the name in eWeLink app

**Comment by narcisrazvanpopescu** [comment]
Thank you for your kindness and patience!
Now I understand the sentence.
Thank you again!
