### ISSUE TITLE
Brightness adjustment missing for GU10 Led bulbs

### ISSUE THREAD

**Issue by ferbulous** [AlexxIT/SonoffLAN#613]
Hi, I'm not really sure what happened, but when I first setup these sets of 5 gu10 wifi bulbs, I was able to adjust brightness
(on the master bedroom lights card there was percentage for brightness level)
But recently the brightness option is no longer available, and I can only toggle on/off only
I'm not quite sure the logs  output I should place here, anyone could guide me on that?

![image](https://user-images.githubusercontent.com/24526737/137948133-f5cef87c-78ba-4c01-b967-ccf8a1ef56b6.png)

![7B810FA6-2DE1-47C3-8E1F-187FEC4D5835](https://user-images.githubusercontent.com/24526737/137949173-7cdfcdec-72d6-4996-afc3-a5fbba2818ce.png)

**Comment by AlexxIT** [comment]
Show this devices in sonoff.json file

**Comment by AlexxIT** [comment]
Closed because no response
