### ISSUE TITLE
Different modes for different devices

### ISSUE THREAD

**Issue by booroondookZ** [AlexxIT/SonoffLAN#616]
Is it possible to use different modes for different devices?
I have one Sonoff POW R2 relay and want to get power consumption of it.
As far as I know, this is only possible in cloud mode, and I want to use cloud mode for this relay only, but for the rest of my devices I want to use **forced** local mode.

**Comment by AlexxIT** [comment]
> New features in version 2.0: can manage both local and cloud control at the same time!

This is not clear?
