### ISSUE TITLE
No seq in updates

### ISSUE THREAD

**Issue by guyyar89** [AlexxIT/SonoffLAN#62]
i have version 0.104.3

home assistant bug
image
![image](https://user-images.githubusercontent.com/43018733/77306003-ad68ac80-6cff-11ea-8b50-f1269dd28b44.png)

image
![image](https://user-images.githubusercontent.com/43018733/77306018-b194ca00-6cff-11ea-899c-8dd77794d21c.png)

how to fix it?

**Comment by guyyar89** [comment]
?

**Comment by AlexxIT** [comment]
Check device firmware update in ewelink app

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v1.10.3
