### ISSUE TITLE
Fan model change

### ISSUE THREAD

**Issue by bdraco** [AlexxIT/SonoffLAN#621]
https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties

This integration is using the old fan entity model.  Backwards compatibility will be disappearing soon.  Let me know if you need help updating to the new model.

Thanks 👍

**Comment by AlexxIT** [comment]
Thanks for point. I'll try to find time to fix it in the near future

**Comment by bdraco** [comment]
Quick reminder on this as backwards compatibility will be gone in tomorrow's beta.

**Comment by AlexxIT** [comment]
Thank you. I think I'm getting close to taking my time with all the fixes to this component

**Comment by YuvalWS** [comment]
Hi, I think the solution will be to implement the "converting speed"
https://developers.home-assistant.io/docs/core/entity/fan/

**Comment by AlexxIT** [comment]
Fixed in latest release https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.4.7
