### ISSUE TITLE
Consider switching to AsyncZeroconf

### ISSUE THREAD

**Issue by bdraco** [AlexxIT/SonoffLAN#622]
It looks like you might be able to save some jumps between sync and async context now that zeroconf is async under the hood.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/zeroconf/__init__.py#L99

**Comment by AlexxIT** [comment]
Added to new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases

Thanks!
