### ISSUE TITLE
Create 4 duplicate entities

### ISSUE THREAD

**Issue by sasukebinbin** [AlexxIT/SonoffLAN#623]
Today add new Sonoff basic. 
HA creates 4 duplicate entyties with postfix _1, _2,_3,_4.
And unable to delete those entities. 
Only first entity _1 working. The rest on and off no response.

**Comment by sasukebinbin** [comment]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:477
First occurred: 02:33:09 (3 occurrences)
Last logged: 02:33:09

Entity switch.sonoff_100137ae09_2 is incorrectly being triggered for updates while it is disabled. This is a bug in the sonoff integration
Entity switch.sonoff_100137ae09_3 is incorrectly being triggered for updates while it is disabled. This is a bug in the sonoff integration
Entity switch.sonoff_100137ae09_4 is incorrectly being triggered for updates while it is disabled. This is a bug in the sonoff integration

**Comment by AlexxIT** [comment]
Show you device in `sonoff.json` file

**Comment by AlexxIT** [comment]
Closed because no response

**Comment by jmayoralas** [comment]
Same problem here with a Sonoff MINIR3:

![imagen](https://user-images.githubusercontent.com/20075656/209660984-0fdbae4c-ae74-4912-b68d-ef596033c955.png)

Device in sonoff.json:

`
{
      "name": "MINIR3",
      "deviceid": "100169ba04",
      "apikey": "*************************************",
      "extra": {
        "uiid": 138,
        "description": "20220228004",
        "brandId": "5c4c1aee3a7d24c7100be054",
        "apmac": "d0:27:02:**:**:**",
        "mac": "d0:27:02:**:**:**",
        "ui": "单通道插座_支持2.4G轻智能",
        "modelInfo": "607cfe884afac4bfbe8a0701",
        "model": "BL1-S04-01",
        "manufacturer": "深圳松诺技术有限公司",
        "chipid": "7CB94C8562E7"
      },
      "brandName": "SONOFF",
      "brandLogo": "https://eu-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png",
      "showBrand": true,
      "productModel": "MINIR3",
      "devConfig": {},
      "settings": {
        "opsNotify": 0,
        "opsHistory": 1,
        "alarmNotify": 1,
        "wxAlarmNotify": 0,
        "wxOpsNotify": 0,
        "wxDoorbellNotify": 0,
        "appDoorbellNotify": 1
      },
      "devGroups": [],
      "family": {
        "familyid": "62f8e4a271e3400009ff381d",
        "index": -1,
        "members": []
      },
      "shareTo": [],
      "devicekey": "*************************************",
      "online": true,
      "params": {
        "bindInfos": {},
        "version": 8,
        "rssi": -49,
        "fwVersion": "1.4.1",
        "switches": [
          {
            "switch": "off",
            "outlet": 0
          },
          {
            "switch": "off",
            "outlet": 1
          },
          {
            "switch": "off",
            "outlet": 2
          },
          {
            "switch": "off",
            "outlet": 3
          }
        ],
        "configure": [
          {
            "startup": "off",
            "outlet": 0
          },
          {
            "startup": "off",
            "outlet": 1
          },
          {
            "startup": "off",
            "outlet": 2
          },
          {
            "startup": "off",
            "outlet": 3
          }
        ],
        "pulses": [
          {
            "pulse": "off",
            "switch": "on",
            "outlet": 0,
            "width": 0
          },
          {
            "pulse": "off",
            "switch": "on",
            "outlet": 1,
            "width": 0
          },
          {
            "pulse": "off",
            "switch": "on",
            "outlet": 2,
            "width": 0
          },
          {
            "pulse": "off",
            "switch": "on",
            "outlet": 3,
            "width": 0
          }
        ],
        "locks": [],
        "sledOnline": "on",
        "ssid": "JL-WRT",
        "bssid": "c4:2b:44:**:**:**",
        "bleScene_0": {},
        "bleScene_1": {},
        "bleScene_2": {},
        "bleScene_3": {},
        "bleScene_4": {},
        "bleScene_5": {},
        "bleScene_6": {},
        "bleScene_7": {},
        "bleScene_8": {},
        "bleScene_9": {},
        "bleScene_10": {},
        "bleScene_11": {},
        "bleScene_12": {},
        "bleScene_13": {},
        "bleScene_14": {},
        "bleScene_15": {},
        "bleScene_16": {},
        "bleScene_17": {}
      },
      "denyFeatures": [
        "localCtl",
        "upgradeFirmwareReminder",
        "remoteControl",
        "remoteSupport",
        "extSwitchMode_with_relay",
        "lightScene",
        "startupWithDelay",
        "extSwitchMode",
        "pluse_with_hour"
      ],
      "isSupportGroup": true,
      "isSupportedOnMP": true,
      "deviceFeature": {}
    }
`

**Comment by AlexxIT** [comment]
@jmayoralas fixed in master version. Will be in next release

**Comment by kedzo777** [comment]
Hi!
I have the same problem with M5 switches
![Screenshot 2024-08-29 173120](https://github.com/user-attachments/assets/b484c809-a3d2-4a67-92f7-f01a4edd878d)

Device in sonoff.json:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.8.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Zagreb",
    "os_name": "Linux",
    "os_version": "6.6.46-haos",
    "supervisor": "2024.08.0",
    "host_os": "Home Assistant OS 13.1",
    "docker_version": "26.1.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.7.3",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "codeowners": [
      "AlexxIT"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.7.3",
    "is_built_in": false
  },
  "setup_times": {},
  "data": {
    "version": "e240aaf",
    "cloud_auth": true,
    "config": null,
    "options": {},
    "errors": [],
    "device": {
      "uiid": 161,
      "params": {
        "bindInfos": "***",
        "version": 7,
        "remoteCtrlList": [
          {
            "outlet": 0,
            "addr": []
          },
          {
            "outlet": 1,
            "addr": []
          },
          {
            "outlet": 2,
            "addr": []
          },
          {
            "outlet": 3,
            "addr": []
          }
        ],
        "switches": [
          {
            "switch": "off",
            "outlet": 0
          },
          {
            "switch": "off",
            "outlet": 1
          },
          {
            "switch": "off",
            "outlet": 2
          },
          {
            "switch": "off",
            "outlet": 3
          }
        ],
        "configure": [
          {
            "startup": "off",
            "outlet": 0
          },
          {
            "startup": "off",
            "outlet": 1
          },
          {
            "startup": "off",
            "outlet": 2
          },
          {
            "startup": "off",
            "outlet": 3
          }
        ],
        "pulses": [
          {
            "pulse": "off",
            "switch": "off",
            "width": 500,
            "outlet": 0
          },
          {
            "pulse": "off",
            "switch": "off",
            "width": 500,
            "outlet": 1
          },
          {
            "pulse": "off",
            "switch": "off",
            "width": 0,
            "outlet": 2
          },
          {
            "pulse": "off",
            "switch": "off",
            "width": 0,
            "outlet": 3
          }
        ],
        "sledOnline": "on",
        "staMac": "***",
        "rssi": -39,
        "offBrightness": 25,
        "fwVersion": "1.2.3",
        "only_device": {
          "ota": "success",
          "ota_fail_reason": 0
        }
      },
      "model": "M5-2C",
      "online": true,
      "local": null,
      "localtype": null,
      "host": null,
      "deviceid": "10015befd5"
    }
  }
}

**Comment by AlexxIT** [comment]
M5-2C supported in master version
