### ISSUE TITLE
Ewelink device - it only detects me switch I do not consume

### ISSUE THREAD

**Issue by jouking** [AlexxIT/SonoffLAN#625]
I have bought this device that works perfectly in ewelink but in Home Assistant it only detects the switch, I do not see any consumption data: https://es.aliexpress.com/item/1005003083993737.html?spm=a2g0s.9042311.0.0.108c63c0tKAr3u

**Comment by AlexxIT** [comment]
Show this device in `sonoff.json` file

**Comment by AlexxIT** [comment]
Closed because no response
