### ISSUE TITLE
Sonoff minis in DIY mode unavailable on startup

### ISSUE THREAD

**Issue by gennadys72** [AlexxIT/SonoffLAN#626]
Hello,

With recent updates of HA, all my Sonoff minis are marked as unavailable following HA restart.
Strangely, if I run a discovery tool (tool_01DIY85(3.3.0).exe) on another system in the same WiFi segment, all the devices  immediately come back online.
HA runs on barebone PC under Debian. One thing worth to note, that the system has two network adapters, one wired ethernet, and another is the WiFi adapter.
So, I believe that it could be related somehow to broadcast being sent to a wrong network segment.
Any help in solving this issue would be appreciated.

**Comment by AlexxIT** [comment]
Fix you network or don't use DIY mode or flash you devices
https://github.com/AlexxIT/SonoffLAN#common-problems-in-only-lan-mode
