### ISSUE TITLE
Smoke Alarm Fire Event on Home Assistant Restart

### ISSUE THREAD

**Issue by jjtleon** [AlexxIT/SonoffLAN#632]
First, thank you so much for your time and efforts. I am happily using your Sonoff LAN integration (2.4.6) with Home Assistant (2021.11.4). Inspired by the HOWTO video by @KPeyanski featured in the documentation, I have a RF Bridge with several 433 MHz smoke alarms. Every time I restart Home Assistant, one of the smoke alarms fires an event. Here is the excerpt from the debug log:

`2021-11-18 10:56:22  DEBUG    remote        Fire event sonoff.remote: {'command': 4, 'ts': '2021-11-05T20:37:26.000Z', 'name': 'Small Bedroom Smoke Detector', 'entity_id': 'remote.pepper_ann'}`

The event originates from Sonoff LAN. The eWeLink app does not show any update from the RF Bridge or Small Bedroom Smoke Detector. The significance of the Small Bedroom Smoke Detector vs the others is that it was added and tested last. You can see that here in the state attributes from the HA Developer Tools:

```
manufacturer: SONOFF
model: RFBridge
sw_version: PSF-BRA-GL v3.5.0
local: online
command: 4
ts: '2021-11-05T20:37:26.000Z'
name: Small Bedroom Smoke Detector
friendly_name: Pepper Ann
supported_features: 1
```

Notice that the last command over a couple weeks ago. Any help would be greatly appreciated.

**Comment by lucamargoni** [comment]
Same issue, the last event is randomly triggered

**Comment by DexDell** [comment]
Hello
Is there any solution to this topic ..
greetings

**Comment by DexDell** [comment]
Hello
Is there any solution to this topic ..
greetings

**Comment by AlexxIT** [comment]
Fixed in latest master-version. Will be in next release.
