### ISSUE TITLE
Home Assistant core-2021.11.5

### ISSUE THREAD

**Issue by aferraz** [AlexxIT/SonoffLAN#634]
Hi @AlexxIT 
 integration does not work anymore after upgrade HA at core-2021.11.5.
In my case I use magnetothermic with firmware version 3.5.0

Best Regards
 Alessandro

**Comment by AlexxIT** [comment]
Any details?

**Comment by aferraz** [comment]
Hi @AlexxIT,
 I give you more details as soon as possible, at the moment I reverted to the previous version of HA

Thanks
 Alessandro

**Comment by aferraz** [comment]
Hi @AlexxIT,
 i tried again and it worked, yesterday all sensors were NaN also after HA restarts.

Thank you.
