### ISSUE TITLE
Constant Errors on Bootup in Logs

### ISSUE THREAD

**Issue by thorrrr** [AlexxIT/SonoffLAN#636]
HI Guys 
I got a Sonoff Zigbee Bridge which i flashed wit Tasmota ncp-uart-sw_6.7.6_115200.ota.
From the Github
Archived versions
ncp-uart-sw_6.7.6_115200.ota - OLD: Original version for EZSP v8 compatible hosts, (contains a bug that can cause battery of IKEA and Philips remotes to drain).

I did try to update  6 months ago must have been 6.7.7 but it kept crashing and i was told many users had issues. so i had to revert.
Is the latest stable 6.7.8 ok to update to now?

Also i ran a debug on booting up to try and grab the errors see log [here](https://0bin.net/paste/0nl6YEqL#XlXdWfYIUvMS5Y0efQg4dnehZnztiA3PZo3IpUo1vZT)

Please can you advice on how to fix this issue and can i upgrade safely now?

**Comment by AlexxIT** [comment]
Your issue not related to this component

**Comment by thorrrr** [comment]
Could you point me in the correct direction?

**Comment by AlexxIT** [comment]
Maybe Tasmota github, I don't know
