### ISSUE TITLE
B02-B and B05-B no control

### ISSUE THREAD

**Issue by Alkuimista** [AlexxIT/SonoffLAN#637]
Hello, both lamps work great, but after a while HA stops controlling them. If I turn them on or adjust any parameter in Ewelink they will update in Lovelace but no control. To re-gain control I always have to restart HA and sometimes this is not enough. Anyone facing the same?

Thanks

**Comment by minskmail** [comment]
Same thing. B02 stops control. Even HA restart doesnt help. Status updated in HA if I change it in Ewelink, but no reactions on HA switch toggle

**Comment by garywilson4** [comment]
my B05 bulbs came into HA as a switch not a bulb so no brightness or colour control

**Comment by Dyltong** [comment]
I see there is a history of this, but B05-BL-A60 only turns on and off and does not dim or change colour.

I have changed their state to light but doesn't help.

I'm running 2.4.6 Sonoff LAN (from choosing master) and Home Assistant 2022.2.6

**Comment by xbrianjasonx** [comment]
Just adding to @Dyltong's comments.  Got my B05-BL-A60 and same thing happened.  Upon pairing, the current version of the bulb's firmware is 1.4.0 and I upgraded to 1.4.1.  Both are just detected as switches as mentioned even with the manual light configuration.

Sonoff LAN version 2.4.6 running on Home Assistant 2022.3.3.

On another note, my B05-B works perfectly.  

The B05's have different FW names and might help in troubleshooting:
B05-B:  WTW-SNL-05
B05-BL-A60: BL1-ALL-LED

Thank you.

**Comment by AlexxIT** [comment]
Probably fixed in latest master-version

**Comment by capitanui** [comment]
Is this fixed ? I just added a Sonoff B02-BL light and it is seen as a switch by the integration. I can change it to light by using device class config, but stil, I can only switch it on and off. 

Thanks!
