### ISSUE TITLE
Switch does not turn on or off

### ISSUE THREAD

**Issue by gdistasi** [AlexxIT/SonoffLAN#638]
I am trying to write an automation. The action part is as follows:
    - service: switch.turn_off
      entity_id: switch.sonoff_scaldino

It simply does not work. No change of state from the switch. If I go on the HA main page, I can switch it on and off with no issues.

**Comment by AlexxIT** [comment]
Are you sure you using right entity_id?

**Comment by AlexxIT** [comment]
Closed because no response
