### ISSUE TITLE
Dual R3 consumption

### ISSUE THREAD

**Issue by andreasc1** [AlexxIT/SonoffLAN#639]
Hello, i have noticed that consumption of Dual r3 cannot be used in the energy monitor of home assistant. can we somehow support this? i have even changed the working mode to "meter" and still cannot be used in energy.

**Comment by cesarlaforetcoelho** [comment]
Same problem, only the switch part is available in HA, all the energy monitoring sensors are missing :(

**Comment by AlexxIT** [comment]
#580
