### ISSUE TITLE
PIR2 Sensor not triggering sonoff.remote event

### ISSUE THREAD

**Issue by c-scoot** [AlexxIT/SonoffLAN#64]
Hi,

I have an RF Bridge and paired a PIR2 sensor. This is working as the ewelink app is sending me notifications. My HA instance has detected my bridge ok, but when the PIR2 sensor triggers no sonoff.remote event is generated.

What am I doing wrong ? :)

Thanks,

Craig

**Comment by maciak** [comment]
Well, I have a door sensor from sonoff and that stopped working for me too probably 3-4 days ago.

**Comment by AlexxIT** [comment]
@c-scoot check RF Bridge GUI window or its attributes. The last triggered event gets there.

**Comment by c-scoot** [comment]
Hi @AlexxIT - Cant see anything there (do you mean the GUI window in HA), but it does show in the ewelink app as triggered. Just doesn't seem to be picking it up in HA. There is only one attribute too and that doesn't seem to be last triggered event

**Comment by maciak** [comment]
Alex probably meant in ewelink app. And events do show there for me.

**Comment by AlexxIT** [comment]
This window #58

**Comment by c-scoot** [comment]
Hi Alex, this is all I see:

![image](https://user-images.githubusercontent.com/49865324/77666021-54577d80-6f78-11ea-9409-a36eb6b07ae3.png)

**Comment by AlexxIT** [comment]
@c-scoot do you have only one RF device - PIR Sensor? Check other if you have.

**Comment by c-scoot** [comment]
Hi Alex,

Just added another PIR sensor and that doesn’t show up either, unfortunately I only have PIR devices I think so can’t try anything else.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by akrasnodebski** [comment]
Hi Alex,
    You have done great job, I have TX light switches  and they work great.
I have also bought bridge and PIR sensor, Bridge is recognised, but I have the same problem with PIR senor and using sonoff.remote event. I have tried it to register it as a button, also no luck.
I cannot see sonoff.remote event in the event page in home assistant?

**Comment by AlexxIT** [comment]
I, unfortunately, do not have PIR sensors to check. RF buttons only.

**Comment by AlexxIT** [comment]
Issue #65 fixed in https://github.com/AlexxIT/SonoffLAN/releases/tag/v1.10.3

Please, check your problem again.

**Comment by c-scoot** [comment]
Hi Alex,

That works great! Thank you :)

**Comment by akrasnodebski** [comment]
It is working.
Well done!
