### ISSUE TITLE
SONOFF BRIDGE 433

### ISSUE THREAD

**Issue by estudioewig** [AlexxIT/SonoffLAN#646]
Hello, I am having a problem receiving notifications when pressing a button on the control 433. I only receive notifications when I am connected to the internet. I am using the following example. Anyone know how I could solve this problem. Thank you!

automation:
- alias: Sonoff RF Receive
  trigger:
    platform: event
    event_type: sonoff.remote  # this is NOT entity_id, don't change it!
  action:
    service: persistent_notification.create
    data_template:
      title: Sonoff RF Receive
      message: |-
        Name: {{ trigger.event.data.name }}
        Command: {{ trigger.event.data.command }}
        Time: {{ trigger.event.data.ts }}

**Comment by AlexxIT** [comment]
RF bridge with latest firmware may have problems with local mode

**Comment by AlexxIT** [comment]
Show your config

**Comment by AlexxIT** [comment]
Closed without response
