### ISSUE TITLE
Instructions for "Getting devicekey manually" doesn't apply for Sonoff Micro

### ISSUE THREAD

**Issue by kylehase** [AlexxIT/SonoffLAN#647]
The instructions for [Getting devicekey manually](https://github.com/AlexxIT/SonoffLAN#getting-devicekey-manually) doesn't work for the [Sonoff Micro Smart USB Adapter](https://sonoff.tech/product/diy-smart-switch/micro/). 

If you put the device in pairing mode, connect to the WiFi SSID and browse to `http://<device IP>/device` it will return a long JSON string as below, not the expected devicekey. _note: the SSID and pairing mode IP on this device also differs from the documentation. `http://10.10.7.1/device` results in timeout_

```{"data":"D+JsM5lCJRA7ntdGjue74kqRt0e+YdmJynJI9hfmEYSARk/y7h6j3Xpewsqzyzd/3BjRXOyU23Ou6K1zmUKFBAk2WrWTDasdfMvdb/WXbZas9Cq6eGXykhH5ixsmEolyv2uihV5oAHMetQy7hu5n6Q9ewT7XGjkCKqqu2phtyoj/Yxpew"}```

[Sonoff's developer site](http://developers.sonoff.tech/sonoff-diy-mode-api-protocol.html) doesn't mention this device at all, so I'm not sure if there's another URL which provides the devicekey. `http://<device ip>` returns nothing.

The only way to get the devicekey for local use was to create a eWeLink account, add the device in the app, and load a cloud config in this component which writes the key to .sonoff.json, but at that point there's no need for the key in yaml.

I'll be glad to submit a PR on [README.md](https://github.com/AlexxIT/SonoffLAN/blob/master/README.md) to update the documentation if this is confirmed by anyone else.

This was tested on:
- Sonoff Micro firmware 3.7.1
- Home Assistant 2021.11.5
- SonoffLAN v2.4.6 - 2021-05-14

**Comment by AlexxIT** [comment]
Getting local keys makes no sense. Integration can load all useful data automatically.

**Comment by ilgarmehmetali** [comment]
@AlexxIT Hi, I had the same problem with kylehase. After many trials while searching on the web I came across this issue. Info in the readme would have been quite useful. May I ask why did you remove that part from readme? 

As a reply to your comment above: I didnt want to install and register to another automation app. It was nice to see alternative setup process.

**Comment by AlexxIT** [comment]
This information is not needed for my users. I make solutions for people who like plug and play :)
