### ISSUE TITLE
Нельзя установить в Home Assistant 2021.11.5

### ISSUE THREAD

**Issue by GenkaOk** [AlexxIT/SonoffLAN#649]
При ручной загрузке интеграции и при загрузке через HACS ничего не происходит и интеграция не появляется в списках.

В консоли выводится предупреждение, что HASC и Sonoff не были проверены разработчиками, но никаких ошибок нет

Версия | core-2021.11.5
-- | --
Тип установки | Home Assistant Core
Среда разработки | false
Supervisor | false
Docker | false
Пользователь | homeassistant
Виртуальное окружение | true
Версия Python | 3.9.1
Семейство операционных систем | Linux
Версия операционной системы | 4.19.0-17-amd64
Архитектура ЦП | x86_64
Часовой пояс | Europe/Moscow

**Comment by AlexxIT** [comment]
Интеграции и не должно появиться в списках. Читайте документацию
