### ISSUE TITLE
Sonoff RF Bridge update 3.4.0 stopped working

### ISSUE THREAD

**Issue by allunix2k** [AlexxIT/SonoffLAN#65]
Hello, first praise for the excellent work, after updating sonoff bridge rf 433 to version 3.4.0 by the ewelink app, it stopped working on the home assistant, there is some correction for the problem, thanks.

**Comment by GozuMezu** [comment]
Same problem here... :-/
Thanks for the wonderful work, I was so pleased to get all of this working. Unfortunately, since the firmware update on sonoff bridge it all stopped working...
Thanks anyone who can look into this!

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v1.10.3
