### ISSUE TITLE
How to put the ptz icon on the top when I am in fullscreen

### ISSUE THREAD

**Issue by Joynaruto2nd** [AlexxIT/SonoffLAN#657]
camera brand: Sonoff
camera type: GK-200MP2-B

As the title: How to put the ptz icon on the top when I am in fullscreen?
The ptz icon only showed with the default size. When I enter to a fullscreen mode, the icon was gone. 
Any idea??

**Comment by AlexxIT** [comment]
This component don't control any icons and fullscreen for Sonoff cameras.
