### ISSUE TITLE
Feature request: Support for Sonoff SPM with device_type: diy_meter

### ISSUE THREAD

**Issue by rpimeekle** [AlexxIT/SonoffLAN#658]
### Support for Sonoff Smart Stackable Power Meter (Sonoff SPM)
I have read through the docs and issues, and even went through the python code, but couldn't find anything relating to this device.  The closest I could see was in reference to `diy_plug`.
Can support please be added for this device: [Sonoff SPM](https://itead.cc/product/sonoff-smart-stackable-power-meter/).

The API docs for the device_type: `diy_meter` can be found here: http://developers.sonoff.tech/spm-main-http-api.html

### Some testing I have done with the API docs: 
I have been able to test the device in DIY mode using the suggested POST methods and almost everything works.  The only thing I have had trouble with is the [Real-Time Monitoring setup](http://developers.sonoff.tech/spm-main-http-api.html#Set-up-Real-time-Monitoring-Related-Information).  While all the other POST only use the device ID and sub-device IDs, this option requires setting an ambiguous url and port.  Whether that is the ip-address and port for the device itself, or a real-time monitoring application external to the device, I haven't been able to determine.  If I have a random url and port, it responds but without any data, and if i drop the url and port, the http POST request fails to connect.

Regardless, it would be amazing if this device could be added to this custom_component.

Let me know if you need further information.

**Comment by AlexxIT** [comment]
I can't promise anything. There is not enough time to add new devices at the moment

**Comment by imeekle** [comment]
> I can't promise anything. There is not enough time to add new devices at the moment

That's fair.

I might do some more digging then.  I'll fork the project and see what I can do to add the component myself (I've been wanting to sink my teeth into something like this, so this seems like a good opportunity).

**Comment by thomasfowler** [comment]
Hi All

I know this is an old thread, but I would be quite keen to contribute here as well. I've now installed a bunch of these SPM units now and am super keen to get the power consumption data into hassio.

@rpimeekle did you make any progress?

@AlexxIT I did a quick scan of the repo - is there a contributors guide or guide to getting a local dev env setup or something like that to get me started and moving in the right direction?

**Comment by rpimeekle** [comment]
> Hi All
> 
> I know this is an old thread, but I would be quite keen to contribute here as well. I've now installed a bunch of these SPM units now and am super keen to get the power consumption data into hassio.
> 
> @rpimeekle did you make any progress?
> 
> @AlexxIT I did a quick scan of the repo - is there a contributors guide or guide to getting a local dev env setup or something like that to get me started and moving in the right direction?

@thomasfowler I didn't make any progress with this side of things, however, I did get the device working with Node Red and feeding back to Home Assistant.

See my blog post [here](https://blog.dvshem.com/2022/02/sonoff-spm-diy_mode-and-nodered/).

**Comment by AlexxIT** [comment]
@thomasfowler there is no contributors guide. I have started developing new version but the war crushed some plans.

**Comment by AlexxIT** [comment]
Can it be added to ewelink app? I need a debug logs from this device

**Comment by thomasfowler** [comment]
@AlexxIT yes, it can be added to ewelink. I can provide these logs if needed.

I also have my device here hooked up being polled using the mDNS service, so I can provide a view of the objects returned. Let me know how I can help and am happy to pitch in here.

**Comment by AlexxIT** [comment]
First of all I'm interesting in debug logs with cloud protocol. You can add device to cloud and collect this logs via this Integration (in debug mode)

**Comment by Yocee84** [comment]
In V2.4.6 the smp is worked fine. Ampere, Watt, Volt, i seen everything. I upgrade to 3.0.1, and disappered lot stuff. Only show swiches for SPM cannels.

**Comment by AlexxIT** [comment]
You need to go to device page and click download diagnostics

**Comment by AlexxIT** [comment]
@thomasfowler thanks. Adds support to latest master version. I'm not sure if all fine with control sub-device. And not sure if all fine with online power measurements.

Unfortunately devices not working locally in your network. So I can't support LAN protocol.

**Comment by thomasfowler** [comment]
@AlexxIT not sure what you mean about "Unfortunately devices not working locally in your network" - is there something else you need me to do?

I have simply added them using the eWelink App and then loaded the diagnostic information from the UI. Is there something else that needs to be done?

**Comment by AlexxIT** [comment]
Your devices have empty localtype. That means they can't be found locally in your network
https://github.com/AlexxIT/SonoffLAN#mode

**Comment by thomasfowler** [comment]
@AlexxIT I've been looking into this. FWIW, I have upgraded the firmware on the SPM to the latest version offered by the eWeLink app (version 1.5.0) and I have update my SonoffLAN integration to use the laster version in `master` branch.

I have confirmed that the SPM is connected to my LAN and I can consistently ping it. It is on the same LAN as my Home Assistant instance (no VLANS or other segments).

I don't have any other issues with Multicast on my network - mDNS is working for all my other devices.

By way of example, I have another 33 Sonoff devices on my network (plugs and light switches) and they dont seem to have a problem with `localtype`.

By way of example, a `BASICRF_R3` has `"localtype": "plug"` and a `TX2C` has `"localtype": "strip"`.

So the problem with discovering the SPM locally on my network seems to be isolated to only the SPM and not other Sonoff devices.

I've also been able to work with device using mDNS in DIY mode, and didn't have any discovery problems then.

Any advice on where to go next?

**Comment by jebeke65** [comment]
does someone know how to setup the service the Sonoff SPM needs to connect to to send the energy measurements ?

**Comment by nicofamdj** [comment]
Im trying to get the SPM-MAIN with 3 sub devices (4RELAY) to get to work in DIY mode.

In HASS im getting in the overview Unknown DIY

  "data": {
    "version": "5406fa7",
    "cloud_auth": false,
    "config": {
      "mode": "local",
      "reload": "always",
      "debug": true,
      "devices": {
        "100015661b1": {
          "name": "DUCOSPMLOCAL",
          "host": "192.168.51.117:8081"
        },
        "ab300004cf": {
          "device_class": [
            {
              "switch": [
                1,
                2,
                3,
                4
              ]
            }
          ],
          "name": "DUCOU1LOCAL",
          "host": "192.168.51.117:8081"
        }
      }
    },
    "options": {},
    "errors": [],
    "devices": {
      "6732474c3831310c45373439": {
        "uiid": 0,
        "params": {
          "switches": [
            {
              "switch": "off",
              "outlet": 2
            }
          ]
        },
        "model": "diy_meter",
        "online": null,
        "localtype": "diy_meter",
        "host": "192.168.51.117:8081"
      }
    }
  }
}

**Comment by AlexxIT** [comment]
Sonoff SPM connected to eWeLink cloud should work fine via cloud and local protocols in the latest master version.

I think I can't add it as DIY device, because don't have it. I would recommend using it with a connection to the cloud.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.1
