### ISSUE TITLE
Question on Sonoff Pow R1

### ISSUE THREAD

**Issue by martinfitzg** [AlexxIT/SonoffLAN#66]
Hi, I have a number of Sonoff Pow r1 on my network, and I was unable to get them into Home Assistant with this plugin, which has really simplified the integration of the other Sonoff devices I have.  Looking at your supported devices I see the Pow R2, but not the R1.  Is there a way I can get the the R1 versions to to be registered or is it just not supported right now. Thanks for any help on this, and my compliments on the plugin.

**Comment by martinfitzg** [comment]
Sorry for wasting your time, just saw the comment here  
https://github.com/AlexxIT/SonoffLAN/issues/31
stating that this device is on V2 of the firmware, thus not currently supported

**Comment by AlexxIT** [comment]
fw 2 now supported
