### ISSUE TITLE
Latest Home Assistant 2021.12.3- broke power monitoring integration

### ISSUE THREAD

**Issue by bluestar888** [AlexxIT/SonoffLAN#660]
Power /Current/ Voltage monitoring does not work anymore until eWeLink app is started at which point it pushes the data.  I have 2 X S31 switches with default firmware and all worked well before.

**Comment by Ungov77** [comment]
same problem here with 4 different S31 (just bought them from amazon)

**Comment by bluestar888** [comment]
I have switched to Tasmota for the monitored devices.  It was fairly easy,a lot easier than expected.  The rest of the plugs and mini relays are working fine with the LAN integration. I believe it is a Sonoff issue as even the Ewelink  official integration (or the app for that matter) only updates when the app starts.CheersSent from my Galaxy
-------- Original message --------From: Ungov77 ***@***.***> Date: 2021-12-26  12:41 a.m.  (GMT-08:00) To: AlexxIT/SonoffLAN ***@***.***> Cc: bluestar888 ***@***.***>, Author ***@***.***> Subject: Re: [AlexxIT/SonoffLAN] Latest Home Assistant 2021.12.3- broke power monitoring integration (Issue #660) 
same problem here with 4 different S31 (just bought them from amazon)

**Comment by bencrazy** [comment]
Same problem here, with 6 different devices. I can manually refresh from within eWeLink, but otherwise they do not automatically refresh anymore.

**Comment by GaryOkie** [comment]
This is my first rodeo with Sonoff and wanted to start off trying Alex's LAN integration to see how well it works with switches and power monitoring.   Not seeing any power updates either in HASS. unless the eWeLink app is running, and as bluestar commented, even the app is not always updating.

So looking like I'll need to order one of those ftdi usb gizmos and start flashing.

**Comment by Raul-7-7** [comment]
I am on 2021.12.8 and have no issue with seeing power consumption on S31 and POW R2.
I dont recall the last time I opened the eWeLink!

**Comment by GaryOkie** [comment]
@Raul-7-7 - what is your configuration?   I'm also on the very latest HASS OS and did manage to get current and power to update in HASS without using the ewelink app by adding:
```
  force_update: [current, power]
  scan_interval: '00:00:30'
```
This is a polling mechanism that I hoped to avoid.  My understanding is that HASS should receive push updates from Sonoff but that isn't working for me (and others) unless the app is used to trigger these push updates.  Alex said this back in Feb 2020...
> Devices themselves send updates in this version of the component.

If that is always the case, then there wouldn't be a need for this force_update option.   It's not documented anywhere that I can find what situations it is required.   Maybe Alex can comment here so we can understand this better?

**Comment by GaryOkie** [comment]
@bluestar888 - in searching for related issues to this, I found that this problem had been [reported twice before ](https://github.com/AlexxIT/SonoffLAN/issues/69 )in 2020.   To work around the issue, Alex added the force_update option.    

It appears to be network related problem with zeroconf/multicast/mDNS within HASS that Alex has no control over, so the workaround was necessary.   

Given that there are 124 open issues for this integration and this same issue was closed twice before, I suggest that you consider trying the force update (if you haven't already), and close this issue.   We still have the option to flash the Sonoff if the support for this integration ends or is unusable.

**Comment by bluestar888** [comment]
Sounds good thank you.Maybe we can document this option somewhere as I searched a lot for a solution and wasn't able to find this force update option. I wouldn't have bothered with Tasmota otherwise as I still run Alex's integration for all of the other Sonoff's I have ( a whole bunch of mini R2 and a few S26 ).RegardsSent from my Galaxy
-------- Original message --------From: GaryOkie ***@***.***> Date: 2022-01-08  9:26 a.m.  (GMT-08:00) To: AlexxIT/SonoffLAN ***@***.***> Cc: bluestar888 ***@***.***>, Mention ***@***.***> Subject: Re: [AlexxIT/SonoffLAN] Latest Home Assistant 2021.12.3- broke power monitoring integration (Issue #660) 
@bluestar888 - in searching for related issues to this, I found that this problem had been reported twice before in 2020.   To work around the issue, Alex added the force_update option.
It appears to be network related problem with zeroconf/multicast/mDNS within HASS that Alex has no control over, so the workaround was necessary.
Given that there are 124 open issues for this integration and this same issue was closed twice before, I suggest that you consider trying the force update (if you haven't already), and close this issue.   We still have the option to flash the Sonoff if the support for this integration ends or is unusable.

**Comment by GaryOkie** [comment]
@bluestar888 - the force update is documented quite nicely... see: https://github.com/AlexxIT/SonoffLAN#refresh-interval-for-th-and-pow

It just doesn't say what circumstances it's needed, but it must be something like - "if power doesn't update automatically, add this".  :)

**Comment by FiTekno** [comment]
Hi, I have the same problems as the previous ones.
Device: Sonoff TH320 (TH ORIGIN 320). It works fine as long as the ewelink app is on in my phone. In local mode, the sensors and everything are unavailable, does not work at all. in cloud mode, updates stop completely if the phone with app is not on.

I tried force update -automation, it doesn't help.

alias: Force_update_alakerta
description: ""
trigger:
  - platform: time_pattern
    minutes: "3"
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.sonoff_100number_temperature


I also defined my device to configuration.yaml just to be sure but no difference.

sonoff:
  devices:
    100number:
      name: THR320_alakerta  # optional rewrite device name
      host: 192.168.1.166  # optional force device IP-address
      #devicekey: xxx  # optional encription key (downloaded automatically from the cloud)


Any help? thank you.
