### ISSUE TITLE
Import as device instead of separate entities

### ISSUE THREAD

**Issue by stu1811** [AlexxIT/SonoffLAN#668]
I have a S31 and it imports as 4 unrelated entities. It would be great if they imported a single device with 4 attributes (switch, voltage, current,  power) 
![Screenshot_20220109-153644_Home Assistant.jpg](https://user-images.githubusercontent.com/12236842/148699861-e8e69ed8-16fe-4bfa-aab3-c5119e50321c.jpg)

**Comment by AlexxIT** [comment]
By default there is no sensor entities. You create them with config

**Comment by stu1811** [comment]
They could be created and disabled. Then enabled via ui.
