### ISSUE TITLE
Lost devices after reboot with reload: once

### ISSUE THREAD

**Issue by LennyLip** [AlexxIT/SonoffLAN#68]
I lost my device after HA server reboot if reload option is not specified ("once" by default).

Is that behavior by default?

**Comment by LennyLip** [comment]
Can't make it work at all now. 

```
The following integrations and platforms could not be set up:
sonoff
Please check your config.

```

**Comment by LennyLip** [comment]
it does not work with email & pass at all now. :(

**Comment by LennyLip** [comment]
@AlexxIT How can I get configuration, that automatically loaded from ewelink servers and save it in configuration.yml?

**Comment by AlexxIT** [comment]
All devices unavailable after restart. It does not depend on reload once / always setting.
Devices are automatically detected in the local network after each restart.
If this does not happen, there are some problems with the multicast / router.

**Comment by mantaalex** [comment]
> All devices unavailable after restart. It does not depend on reload once / always setting.
> Devices are automatically detected in the local network after each restart.
> If this does not happen, there are some problems with the multicast / router.

i had this to look below:
i had the problem as soon as i restarted my Home assistant
all my sonoff things where unavailable 
i tryed alot not working things 
but i have found my solution as this:
i was using an Netgear R7000 Router
running standard netgear firmware
someone told me maybe it was mDNS but wasn't sure
so i tought maybe i flash that crappy netgear ;)
i'm using Advanced Tomato now (because i didn't get my USB working on Fresh Tomato)
and now it works i can restart as many as i want directly sonoff is available and working
Maybe it could help someone grz alex

**Comment by LennyLip** [comment]
> If this does not happen, there are some problems with the multicast / router.

Ok. So logic:
1st run:
1) load_devices (from ewelink servers)
2) multiscan devices.
works ok
2st run:

**Comment by AlexxIT** [comment]
@mantaalex yes, everything works through mDNS.
My devices also unavailable after restart!
Sometimes they appear instantly. Sometimes after a few minutes.

**Comment by AlexxIT** [comment]
@LennyLip multicast work is difficult to predict.
With my router not everything works perfectly after a reboot.
But within a few minutes the work is getting better.

**Comment by mantaalex** [comment]
> @mantaalex yes, everything works through mDNS.
> My devices also unavailable after restart!
> Sometimes they appear instantly. Sometimes after a few minutes.

for me to after reboot it could be unavailable it needs some time
strange that things like smart_life tuya are faster i don't have the problem there

**Comment by LennyLip** [comment]
> But within a few minutes the work is getting better.

Хорошо, тогда потестирую еще ;)
