### ISSUE TITLE
Sensor TH not reading the temperature

### ISSUE THREAD

**Issue by ZancaAngelo** [AlexxIT/SonoffLAN#681]
![Immagine 2022-01-17 095945](https://user-images.githubusercontent.com/50366331/149739059-985f84ec-f036-47f6-89ea-bbcc8620404e.png)

**Comment by ZancaAngelo** [comment]
HA 2021.12.8
Component 2.4.6

**Comment by HybridRCG** [comment]
I followed this... Link > https://github.com/AlexxIT/SonoffLAN/issues/527
Seems to work, but have other issues when is set mode: local... :(
