### ISSUE TITLE
Introduce ability to filter out clearly wrong readings.

### ISSUE THREAD

**Issue by krzysztof-gzocha** [AlexxIT/SonoffLAN#683]
Temperature history of one of my sonoff TH16 is sometimes experiencing a weird bug. The temperature rises to 288 degrees or goes down even below 0 Kelvin. It's clearly a wrong read, which does not happen very often, but when it does it messes up the graph a lot.

The sonoff is attached closely to a heat pump, so there could be a lot of vibrations on both sonoff and the thermometer and probably a lot of others interferences. 

I have over 6 different sonoffs connected to my HA setup, but only this one is having issues like that (and it's only about temperature, humidity is fine)

![Screenshot from 2022-01-17 14-26-59](https://user-images.githubusercontent.com/3098559/149785344-ae6c4e2f-17d4-4b36-b471-7c38eaf5f2e7.png)

I'm pretty sure that's about bad reading from the sensor, because I've replaced the thermometer and even used different sonoff with Supla installed in cloud mode and even then Supla's MQTT broker was sending me those bad readings, but supla did some filtering and when the temperature is below 0 Kelvin they force it to -273 (as they should I think). 
![Screenshot from 2022-01-17 14-18-00](https://user-images.githubusercontent.com/3098559/149785828-a3391aa4-a201-446f-a856-5310ed549597.png)

I would love to get back to my original sonoff in LAN mode, but I'd need to add some temperature filtering in the integration.
One solution would be to log this kind of situation as an error and don't event send such a read to HA.

For that I'd try to add this piece of code in `sonoff_local.py`
```python
            # TH bug in local mode https://github.com/AlexxIT/SonoffLAN/issues/110
            if state.get('temperature') == 0 and state.get('humidity') == 0:
                del state['temperature'], state['humidity']

#### START OF MY CHANGE
            if state.get('temperature') <= -100 or state.get('temperature') > 100:
                _LOGGER.error(f"Temperature read outside of probable range")
                del state['temperature'], state['humidity']
### END OF MY CHANGE

            if 'temperature' in state and self.sync_temperature:
                # cloud API send only one decimal (not round)
                state['temperature'] = int(state['temperature'] * 10) / 10.0
```

I guess even better approach would be to allow end user to configure those parameters in config file or read previous states for that sensor and check if the difference between those aren't too big.

I'm using newest HA on RaspberryPI and latest SonoffLAN integration. 

Did try:
- multiple HA/plugin/raspberry/sonoff restarts
- changing thermometer
- changing sonoffs
- using supla with MQTT via cloud
- looking through HA logs around the time that bad reading were happening

Nothing helped.

I'm not sure if my code would do the trick _yet_, but I'd love to hear your comments or any other idea about how to fix this.

Thank you.

**Comment by AlexxIT** [comment]
Added to latest master-version. Will be in next release.
