### ISSUE TITLE
S31 other sensor measurements

### ISSUE THREAD

**Issue by gargan26** [AlexxIT/SonoffLAN#687]
Is there any way to get power factor, reactive power, apparent power or any other measurements from a Sonoff S31 device?  As far as I can tell only power, voltage and current is available at the moment.  Is that all there is?

**Comment by AlexxIT** [comment]
It this info provided in ewelink app?

**Comment by gargan26** [comment]
No. That is all that eWeLink shows as well.

**Comment by AlexxIT** [comment]
If this info isn't displayed in ewelink app, this component also can't display it
