### ISSUE TITLE
S31 attributes only show when ewelink is open

### ISSUE THREAD

**Issue by Jgil10** [AlexxIT/SonoffLAN#69]
In Home Assistsnt the Sonoff S31 plug power on or off work fine without ewelink on the phone. The attributes work as expected only while the ewelink app is open and connected on the phone. Otherwise the previous state shows.

**Comment by thedesp** [comment]
+1
same here.

**Comment by Jgil10** [comment]
I have tried adding the keys to the configuration.yaml under sonoff, also just leaving the /config/.sonoff.json file which also retrieves the keys. No difference either way. It works as a switched outlet just fine both ways. The attributes only work right if the ewelink is app is open and connected on the phone

**Comment by AlexxIT** [comment]
Unfortunately I do not have devices that transmit data constantly.
To debug this situation.

**Comment by Jgil10** [comment]
It would be good to have this working to save opening the device. For now, since I need to use it, I have opened the S31, flashed it with tasmota and configured it with their S31 template. It is integrated with Home Assistant and working fine. Thanks.

**Comment by whyitsbob** [comment]
I have the same issue with a Sonoff POW2 and a couple of S31's.  The attributes only get updated when the app is open.

**Comment by AlexxIT** [comment]
Try new version #99
Perhaps updates via the cloud will come more often. Local mode will continue to work

**Comment by rledwa2** [comment]
I have the same problem.  It seems the attributes are not pulled regularly (at all), unless you trigger the S31 by turning it on/off --OR-- have the Ewlink app open..

@AlexxIT I'd be happy to donate the money for you to get one or ship one to you to integrate better.  Just let me know how. 

Cheers,Rob

**Comment by AlexxIT** [comment]
@rledwa2 try this advice https://github.com/AlexxIT/SonoffLAN/issues/14#issuecomment-625789198

**Comment by rledwa2** [comment]
@AlexxIT Works perfectly!  It's not elegant but it works.  Perhaps you could add a refresh option within the component so it automatically gets the update (Every X seconds/minutes, if ON set state to ON, if OFF, set state to OFF) which will get the current attributes...

**Comment by AlexxIT** [comment]
@rledwa2 I plan to do it someday

**Comment by AlexxIT** [comment]
I found time for your problem (in latest master beta version):
https://github.com/AlexxIT/SonoffLAN#refresh-interval-for-th-and-pow
