### ISSUE TITLE
Mode: local, Ewelink works

### ISSUE THREAD

**Issue by xwsjfx** [AlexxIT/SonoffLAN#692]
Hello. I have a strange situation. I set the mode to Local and restarterd HA. Then I disabled my mobile's and one Sonoff switch's access to the interned in my router (IP parental control).
My mobile immediately showed "no internet", however when I swithed to mobile data I could operate that switch from Ewelink.
So neither the SonoffLAN local mode, nor the parental control does not work. 

I am confused...

Any ideas? :) 
Thanks

**Comment by AlexxIT** [comment]
Why you ask in Hass component project about problems with your router?

**Comment by xwsjfx** [comment]
Because I cannot verify that it is a router problem. Normally the wifi LED on the switch automatically starts blinking if the device cannot connect to the cloud, but so far noone mentioned that it is blinking after setting the mode to local. How did you disable the blinking?

**Comment by AlexxIT** [comment]
If you have any problems with device, you always can flash custom firmware. Example ESPHome

**Comment by serlinGi** [comment]
hi  @xwsjfx ,
I you confirm that with the new official integration version if the device does not have internet access, even if it is used only in local mode, the led blinking.
This happens starting with the new BIG Version 3.0 not yet supported on HA. ;)

**Comment by AlexxIT** [comment]
LED always blinking without access to cloud

**Comment by serlinGi** [comment]
> LED always blinking without access to cloud

Yes, sure....
but just now, after new version.
My devices have always been withouth internet (and Cloud) connection with your custom and before not blinking....
this not issue for me.
THX for your work 👍

**Comment by AlexxIT** [comment]
There was a bug that enable LED on all devices. Maybe this is related. You need to disable LED on your devices again
