### ISSUE TITLE
No unique ID of Sonoff RF sensor connected to Sonoff RF bridge

### ISSUE THREAD

**Issue by huishizhao** [AlexxIT/SonoffLAN#693]
I connectted some RF sensors on Sonoff RF bridge through Sonofflan, the only issue is could not customize entity for no unique ID.
how could set Unique ID in HASS？

![Screenshot 2022-01-25 230321](https://user-images.githubusercontent.com/80588197/151002633-d237b9da-3b19-43fb-9216-7b85a338f906.jpg)

**Comment by AlexxIT** [comment]
This component don't support unique_id for RF sensors
