### ISSUE TITLE
sonoff.update_consumption not a recognised service

### ISSUE THREAD

**Issue by IanAdd** [AlexxIT/SonoffLAN#696]
Using HA 2021.12.10

The log reports that it cannot find the 'sonoff.update_consumption' service.

I have POW device and your documentation makes it clear that I need to get the sonoff to update_consumption to be able to read the info.

Is the documentation out of date, perhaps?

**Comment by AlexxIT** [comment]
Service only exist if you using auto or cloud mode

**Comment by IanAdd** [comment]
Thanks, so the local mode does not **need** to stimulate the update ?

**Comment by AlexxIT** [comment]
This consumption data collects by cloud. But you can collect consumption data with Hass:
https://www.home-assistant.io/integrations/utility_meter/
