### ISSUE TITLE
Sonoff zigbee window/door sensor not working correct

### ISSUE THREAD

**Issue by nelsonamen** [AlexxIT/SonoffLAN#698]
![IMG_20220130_180934](https://user-images.githubusercontent.com/5807434/151712022-71ffbe9c-c6fb-47f3-9ea3-7e31700d77d3.jpg)

**Comment by nelsonamen** [comment]
maybe related to ewelink or sonoff servers

**Comment by AlexxIT** [comment]
Duplicate #250
