### ISSUE TITLE
Support Sonoff L1 LED Strip

### ISSUE THREAD

**Issue by ebattulga** [AlexxIT/SonoffLAN#7]
It would be awesome with [Sonoff LED](https://www.itead.cc/sonoff-l1-smart-led-light-strip.html) strip. I'm sorted by most requested functions.
 - On/Off
 - Change color
 - Brightness
 - Mode 
   - Coloful
   - Sync to music
   - Coloful Gradient
   - ...

**Comment by AlexxIT** [comment]
@ebattulga I don't have this one. Could you send some debug logs?

**Comment by AcidSleeper** [comment]
From another Sonoff-integration that I tried.

Mode 1: Colorful
Mode 2: Colorful gradient
Mode 3: Colorful Breath
Mode 4: DIY Gradient
Mode 5: DIY Pulse
Mode 6: DIY Breath
Mode 7: DIY Strobe
Mode 8: RGB Gradient
Mode 9: RGB Pulse
Mode 10: RGB Breath
Mode 11: RBG Strobe
Mode 12: Sync to music

[sonoff.L1.txt](https://github.com/AlexxIT/SonoffLAN/files/4208484/sonoff.L1.txt)
[sonoff-debug.txt](https://github.com/AlexxIT/SonoffLAN/files/4208485/sonoff-debug.txt)

Hope it can help!

**Comment by AlexxIT** [comment]
@AcidSleeper I see firmware version 2.7.0.
Devices of this version should work in local mode only with the Internet turned off.
Have you blocked your device Internet?
Is there a newer firmware version?

**Comment by AcidSleeper** [comment]
No newer version in eWeLink app.

After installing integration in Home assistant via HACS and putting minimum requirements in configuration.yaml the device dont appear. 

The .sonoff.json file that gets created indicates it downloads the Sonoff L1 from server but dont appear in Home assistant

**Comment by AlexxIT** [comment]
@AcidSleeper can you:
- enable debug log
- block Internet
- restart device and HA
- switch strip through remote
- check your logs

**Comment by AcidSleeper** [comment]
Code for debug you want?

Block internet for Sonoff L1?

Switch strip? On/Off?

**Comment by AlexxIT** [comment]
1. Enable debug logs:
```logger:
  default: info
  logs:
    custom_components.sonoff: debug```

2. Yes. Block Internet for Sonoff L1?

3. Yes. On/Off

**Comment by AcidSleeper** [comment]
Nothing happens!

HA dont produces a log!

**Comment by AlexxIT** [comment]
@AcidSleeper do you have telegram? Can you write to me there?

**Comment by AcidSleeper** [comment]
Discord?

**Comment by AcidSleeper** [comment]
This is whats get created in .sonoff.json

`{"1000990af7":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0},"group":"","online":false,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5d85d8ec8ff123e94fe13da9","name":"Sonoff Led1","type":"10","deviceid":"1000990af7","apikey":"REDACTED","extra":{"extra":{"uiid":59,"description":"20190703002","brandId":"5c4c1aee3a7d24c7100be054","apmac":"REDACTED","mac":"REDACTED","ui":"律动灯带","modelInfo":"5c700fabcc248c47441fd241","model":"PSF-BTA-GL","manufacturer":"深圳松诺技术有限公司","staMac":"REDACTED"},"_id":"5d1c529c2fb3e272ea638b13"},"createdAt":"2019-09-21T08:01:48.995Z","__v":0,"onlineTime":"2020-02-10T11:02:54.221Z","ip":"185.168.242.179","location":"","params":{"sledOnline":"on","rssi":-67,"fwVersion":"2.7.0","staMac":"REDACTED","switch":"on","light_type":1,"colorR":255,"colorG":255,"colorB":255,"bright":100,"mode":2,"speed":100,"sensitive":10},"offlineTime":"2020-02-15T15:20:44.294Z","deviceStatus":"","sharedTo":[],"devicekey":"REDACTED","deviceUrl":"https://eu-api.coolkit.cc/api/detail/5c700fabcc248c47441fd241_en.html","brandName":"SONOFF","showBrand":true,"brandLogoUrl":"https://eu-ota.coolkit.cc/logo/Q4RJzznuKEeDgFXbgyS9OClbyEDR7gXd.png","productModel":"L1","devConfig":{},"uiid":59}}`

**Comment by AlexxIT** [comment]
@AcidSleeper Discord: `AlexxIT#0816`

**Comment by AlexxIT** [comment]
Here #31

**Comment by jyz0501** [comment]
Is there any new progress in the project? I have an L1 light strip. What do I need to do?

**Comment by jyz0501** [comment]
{"1000a2ac7d":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0,"appDoorbellNotify":1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5db6cd68eafb2786263c3515","name":"主卧灯带","type":"10","deviceid":"1000a2ac7d","apikey":"8c236797-5fa2-4854-ae0b-c8101facadd4","extra":{"extra":{"model":"PSF-BTA-GL","ui":"律动灯带","uiid":59,"description":"20190814007","manufacturer":"深圳市阳溢电子商务有限公司","mac":"d0:27:01:45:56:4a","apmac":"d0:27:01:45:56:4b","modelInfo":"5ba1dcf777db4c0c7324041a","brandId":"5a03b77c6ed24cfc5975198e","staMac":"D8:F1:5B:8C:24:70"},"_id":"5d54ff6613451dda060dd489"},"createdAt":"2020-02-01T10:40:11.679Z","__v":0,"onlineTime":"2020-04-12T07:33:45.952Z","ip":"119.189.70.98","location":"山东","params":{"sledOnline":"on","rssi":-69,"fwVersion":"2.7.0","staMac":"D8:F1:5B:8C:24:70","switch":"off","light_type":1,"colorR":255,"colorG":183,"colorB":0,"bright":57,"mode":1,"speed":30,"sensitive":2,"bindInfos":{"aligenie":["8c236797-5fa2-4854-ae0b-c8101facadd4_33d17855f659bbea8279ac74a01f24f196a929bb"],"miot":["8c236797-5fa2-4854-ae0b-c8101facadd4_ewelink-miot-v1"]},"timers":[],"partnerApikey":"55b441f6-f692-438d-82f0-3338da3baef8"},"offlineTime":"2020-04-12T07:33:21.599Z","deviceStatus":"","sharedTo":[],"devicekey":"4c9bf94b-a7a8-4368-be46-c1a04dbbd857","deviceUrl":"","brandName":"ABC","showBrand":false,"brandLogoUrl":"","productModel":"2.0-led","devConfig":{},"uiid":59}}

**Comment by jyz0501** [comment]
2020-04-15 22:40:00 DEBUG (MainThread) [custom_components.sonoff.utils] Init zeroconf singleton
2020-04-15 22:40:00 DEBUG (MainThread) [custom_components.sonoff] Update device config 1000a2ac7d
2020-04-15 22:40:00 DEBUG (MainThread) [custom_components.sonoff.utils] Generate zeroconf singleton
2020-04-15 22:40:02 DEBUG (SyncWorker_17) [custom_components.sonoff.utils] Use zeroconf singleton

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by AlexxIT** [comment]
Supported

![download-1](https://user-images.githubusercontent.com/511909/81735457-be32d480-949d-11ea-94df-826b20806451.png)
