### ISSUE TITLE
How to add device in DIY mode? 

### ISSUE THREAD

**Issue by oskarscholander** [AlexxIT/SonoffLAN#70]
Hi!

I can not get DIY mode devices to work. They wont show up as entity in HA after adding them to the config. What do u recommend to do?

/ Oskar

**Comment by AlexxIT** [comment]
Hi. They should appear automatically. If they are in the same wifi network.
Do you have other sonoff devices?
At least one has appeared in HA?

**Comment by oskarscholander** [comment]
All my non-flashed devices appears!

`sonoff:
  username: oskar.scholander@gmail.com
  password: Mainroot12!
  reload: always
  devices: 
    10009b7442: # Light 1
      device_class: light
    10008fdbae: # Light 2
      device_class: light
    10009bb1e6: # Light 3
      device_class: light`

Light 2 is flashed and does not show up. At least not as a entity! I got at least another three devices (also flashed) that does not show up!

**Comment by AlexxIT** [comment]
1. Remove password from comment.
2. You can enable debug log (read readme) and check DIY device_id there.
3. DIY devices do not need to be added to the config. They work automatically

**Comment by oskarscholander** [comment]
Thanks!

- I've removed all Sonoff related entities from HA
- Edited config to only have "sonoff:"
- Restarting HA
- Checking entity list and only the two non-flashed devices shows up

Sorry but I try my best here :)

**Comment by AlexxIT** [comment]
What do you mean by non-flashed?
Sonoff without DIY mode added via ewelink account or via devicekey.
Sonoff in DIY mode added automatically if they are on the same network.
Flashed Sonoff (esphome, tasmota, etc.) don't support.

**Comment by oskarscholander** [comment]
Non-flashed = Original firmware!

Well that explains everything. I thought "DIY mode" included custom firmware! My bad! Maybe include that in the readme?

Thank you for great support!
