### ISSUE TITLE
Question: Sonoff TX3C switches with zigbee lights

### ISSUE THREAD

**Issue by alexdelprete** [AlexxIT/SonoffLAN#704]
Hi @AlexxIT,

I know this is not strictly related to your component, which is working flawlessy in local + cloud list import mode, but I thought it would be good to have your feedback.

I installed 11 Sonoff TX3C wall switches. In some rooms I use zigbee lights. In order to control the zigbee light from the button of the TX3, I would like not to cut its power off switching the internal relay, but keeping the relay always on (powering the zigbee light) and just inercept the press of the button (I use Home Assistant) to turn on/off the zigbee light via HA and zigbee.

So the question is: is it possible to configure the switch to keep the internal relay always on and still send the press button event?

Thanks for your help,

Alex

**Comment by AlexxIT** [comment]
You can't do it with default firmware. You need to flash some custom firmware, example https://esphome.io/
