### ISSUE TITLE
Support EntityCategory in new Hass versions

### ISSUE THREAD

**Issue by sddgit** [AlexxIT/SonoffLAN#705]
Getting a lot of these in the HA log:

```
WARNING (MainThread) [homeassistant.helpers.frame] Detected code that uses str (config) for entity category
```
I see that you have addressed a similar problem in one of your other components at [https://github.com/AlexxIT/XiaomiGateway3/issues/631](url). Would something like that apply to the Sonoff component too, since that’s the one I use?

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases
