### ISSUE TITLE
TH10 POWR2 on Local mode cannot toggle switch

### ISSUE THREAD

**Issue by TommisGR** [AlexxIT/SonoffLAN#707]
Both are on 3.5.0
Tried the 158 fix (https://github.com/AlexxIT/SonoffLAN/issues/158)
by changing the self._is_th_3_4_0 with self._is_th_3_5_0 (3 times)
worked for   day (at the time only the th10 was not toggling) after restart same issue to both TH10 and POWR2
Now I am back at auto mode 
# mode: local
any Ideas on how to troubleshoot?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#common-problems-in-only-lan-mode
