### ISSUE TITLE
Sonoff availability not stable with docker

### ISSUE THREAD

**Issue by david78455** [AlexxIT/SonoffLAN#708]
Hi Alex,
I recently have installed HA on docker with the supervisor installation. But most of the sonoff switch are not available and in gray icons for then more they apears to be available for one second and they go back to be not available 
When this happens they are not available even in eWeLink apps
I tried do disable lab mode in eWeLink app, the same problem 
My docker installed on raspberry pi 4
With the regular instructions on pi it doesn’t happen 
Please help 
Regards 
David

**Comment by AlexxIT** [comment]
If they don't work in eWeLink, you have a WiFi router problem
