### ISSUE TITLE
Несколько RF Bridge

### ISSUE THREAD

**Issue by Markgit-dev** [AlexxIT/SonoffLAN#71]
Добрый день.

У меня возник вопрос. 
Если у меня в ewelink несколько RF Bridge

Когда я согласно примеру пишу 
event_type: sonoff.remote

Что происходит? 
Нужный сенсор найдётся по имени или мне как-то нужно уточнит про какой именно Brigde идёт речь?

**Comment by AlexxIT** [comment]
Добрый. Все мосты будут генерировать событие `sonoff.remote`.
В событии есть `entity_id`. Опционально вы можете по нему фильтровать, если есть такая необходимость.
