### ISSUE TITLE
Sonoff RGB Bulb domain is switch instead of light B05-BL

### ISSUE THREAD

**Issue by HBP-REZZ** [AlexxIT/SonoffLAN#712]
I have some sonoff bulbs, the B05-B works fine, while the B05-BL is recognised as a switch instead of light and cant be customized on home assistant, only turned on or off.

**Comment by HBP-REZZ** [comment]
solved it by deleting bulb, adding the class to config with default device ID which can then be changed to a friendly name.

**Comment by HBP-REZZ** [comment]
I managed to change domain from switch to light by adding "device_class: light" but it only has on/off still.

**Comment by thanhcun1205** [comment]
i had same problem.Please help.
B05-B-A60

**Comment by thanhcun1205** [comment]
it worked !
add :    ```
elif uiid == 136:
        add_entities([SonoffB05(registry, deviceid)]) to light.py
```
and add `136: 'light',  # Sonoff B05BL RGB+CCT color bulb to ultils.py`

**Comment by HBP-REZZ** [comment]
thanks!!

**Comment by xbrianjasonx** [comment]
Thank you for this!

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1
