### ISSUE TITLE
Warning log

### ISSUE THREAD

**Issue by hn315** [AlexxIT/SonoffLAN#713]
Logger: homeassistant.setup
Source: /usr/local/lib/python3.9/asyncio/events.py:80
First occurred: 2022年2月21日 19:20:57 (1 occurrences)
Last logged: 2022年2月21日 19:20:57

Setup of sonoff is taking over 10 seconds.

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1
