### ISSUE TITLE
Sonoff Basic with Firmware 3.5.1 Integration error

### ISSUE THREAD

**Issue by MmeHulot** [AlexxIT/SonoffLAN#715]
I am using a Sonoff Switch-Wf with firmware 1.2.0 which is working perfect. The second Sonoff Basic Switch Firmware 3.5.1 is causing this error:
`
```
Logger: homeassistant.components.switch
Source: custom_components/sonoff/sonoff_main.py:260
Integration: Schalter (documentation, issues)
First occurred: 21:47:21 (1 occurrences)
Last logged: 21:47:21

Error adding entities for domain switch with platform sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 781, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/sonoff/switch.py", line 44, in async_added_to_hass
    device = self._init()
  File "/config/custom_components/sonoff/sonoff_main.py", line 243, in _init
    self._update_handler(state, attrs)
  File "/config/custom_components/sonoff/switch.py", line 51, in _update_handler
    self._is_on = any(self._is_on_list(state))
  File "/config/custom_components/sonoff/sonoff_main.py", line 260, in _is_on_list
    return [state['switch'] == 'on']
KeyError: 'switch'
```
The behaviour is strange because despite this error the switch is responding BUT it takes a million years that the state changes. Same behaviour with the eWlink Smart Home Addon.
Home Assistant 2022.2.9, Home Assistant OS
Control over eWeLink Android App with both switches no Problem. .sonoff.json generated correct.
Config:

```
sonoff:
  username: tritratrallala
  password: tritratrallala
   mode: local
  reload: always
  default_class: light  # (optional), default switch
  devices:
   100143a1db:
    device_class: switch
    name: Sonoff_Switch1
   1000b235b3:
    device_class: switch
    name: Sonoff_Switch2
```

**Comment by AlexxIT** [comment]
Show me debug logs
https://github.com/AlexxIT/SonoffLAN#component-debug-mode

**Comment by MmeHulot** [comment]
I tried several configurations and finally I got _both_ switches working beside the fact, that only one is in the comfiguration.yaml. The file .sonoff.json is generated correct.

```
sonoff:
 username: blahblub
 password: blahlbah
 reload: always
 default_class: light  # (optional), default switch
 debug: true # Look at the notification section, a debug link will appear
 devices:
#  100143a1db:
#   device_class: switch
#   name: Sonoff_HZ
#   unique_id: 123light123
  1000b235b3:
   device_class: switch
   name: Sonoff_Switch2
```
The first switch which I commented out was found by HA as entity light.sonoff_100143a1db_1 Using this is working. 
By the way HA found four entities light.sonoff_100143a1db_1, light.sonoff_100143a1db_2, light.sonoff_100143a1db_3 and light.sonoff_100143a1db_4
I checked the debugs in the in the notifications: no log there. I also checked the logs.

Result: with only one switch in the configuration.yaml as quoted above  _both_ switches are working! No idea why. But it  works. 

Thank you for your great work and help!

**Comment by AlexxIT** [comment]
Because `100143a1db` has multichannel firmware. You shouldn't set single channel `device_class` to it.
