### ISSUE TITLE
Sonoff Switch not getting detected in Home Assistant 2021.12.10

### ISSUE THREAD

**Issue by karthikvsamy** [AlexxIT/SonoffLAN#719]
**Not Working Setup**
Running Home Assistant (2021.12.10) in RaspberryPi 4, in which Sonoff Switches were not getting detected. 

**Working Setup**
Running Home Assistants (0.100.3) in RPi 3B+, which is working fine and able to detect switches well.

**The problem**
I have upgraded by setup from RPi3 to RPi4, earlier I was running HA version 0.100.3 in which Sonoff was working well.
But in Home Assistant 2021.12.10 those switches were not getting detected at all.
Is there any known changes to be considered?
I am using https://github.com/AlexxIT/SonoffLAN custom component

**What version of Home Assistant Core has the issue?**
2021.12.10

**What was the last working version of Home Assistant Core?**
0.100.3

**What type of installation are you running?**
Home Assistant Core

**Integration causing the issue**
Upgrade of HA

**Diagnostics information**
No obvious error reported in log

**Example YAML snippet**
```
sonoff:
    username: !secret sonoff_username
    password: !secret sonoff_password
    scan_interval: 60
    grace_period: 600
    mode: local
    reload: 'once'
    debug: True
```

**Anything in the logs that might be useful for us?**
2022-02-27 22:52:21 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2022-02-27 22:52:21 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.1 seconds

2022-02-27 22:52:22 INFO (MainThread) [homeassistant.setup] Setting up sonoff
2022-02-27 22:52:22 INFO (MainThread) [homeassistant.setup] Setup of domain sonoff took 0.0 seconds

2022-02-27 22:52:28 INFO (MainThread) [homeassistant.components.zeroconf] Starting Zeroconf broadcast

**Comment by karthikvsamy** [comment]
Update: I missed to inform that my RPi is connected to Wlan0 (NW1) as well as eth0 (NW2). Priority is set to WIFI.
SONOFF devices are present in eth0 (NW2). When I disabled Wlan0 network in RPi then Home assistant identified Switches well.
So it is something to do with priority in which zeroconf is setup with Wlan0 & eth0

**Comment by karthikvsamy** [comment]
Update: I couldn't get it working with latest Home assistant core with both LAN and WIFI networks active in Raspberry Pi. 
Someone mentioned that SonOff integration works until HA Core version 2021.7.4, so I have downgrade my HA core. Boom!!! Integration works without any issue.
So something changed in HA core after 2021.7.4
You may concluded this issue for now.

**Comment by Fannangir** [comment]
I can see the same issue.
I do see just one of the three available sonoff devices (I see only the device which was there for a long time ago, can't add new devices).
I have tried to delete the json file, reload from the server, does not help.
Is there any solution for the issue?

Thanks.

**Comment by AlexxIT** [comment]
Don't use mode local if you can't setup your local network correctly

**Comment by Fannangir** [comment]
@AlexxIT could you please elaborate?
Could you please explain what is configured incorrectly? What should I look for?
I can see one device out of three.
Thanks.

**Comment by Fannangir** [comment]
BTW, my config includes username and password only, nothing more.

**Comment by AlexxIT** [comment]
@Fannangir you need to check how many devices in your json file. Maybe you added devices to wrong account

**Comment by qbikez** [comment]
@karthikvsamy I had a similar issue on windows and what helped me was to change zeroconf interface choice to `All` in [homeassistant/components/zeroconf/__init__.py](https://github.com/qbikez/home-assistant-core/commit/5971eebb7823651128dd84b310d3d5dd392d91ea):
```python
zc_args["interfaces"] = InterfaceChoice.All
```
