### ISSUE TITLE
Sonoff does not update at midnight (00:00)

### ISSUE THREAD

**Issue by hsdutra** [AlexxIT/SonoffLAN#722]
![image](https://user-images.githubusercontent.com/2472470/156952678-97447a26-351e-4478-9bc6-890845acf798.png)

Does anyone know why the sonoff pow r2 is not updating the data at midnight (00:00)?

In the printscreen it was already past midnight on the 07/03th, but the sonoff was still counting the day 06/03 and I can't understand why it hadn't started counting the new day.

This impacts all calculations in the daily and monthly consumption reports.

Note:
this happened when sonoff reached 100 lines in consumption logs

**Comment by AlexxIT** [comment]
This data from ewelink cloud. Maybe they using different timezone

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1

It has new consumption sensor
