### ISSUE TITLE
Not a BUG - Recover accidentally deleted device

### ISSUE THREAD

**Issue by alnavasa** [AlexxIT/SonoffLAN#723]
Hi,
How can I recover an accidentally deleted device, 
I think it is by deleting the ```/config/.sonoff.json```file, but I am not sure and I don't want to messy my config file,

Thanks!!!

**Comment by AlexxIT** [comment]
Please show your config

**Comment by alnavasa** [comment]
> Please show your config

’’’

Sonoff configuration:
  sonoff:
  username:! secret sonoff username
  password: !secret sonoff password
  force update: [temperature, power]
  scan interval: "00:02:00" # (optional) default 5 min
  sensors: [temperature, humidity, power, current, voltage]
  reload: always

’’’

**Comment by AlexxIT** [comment]
You just need to restart Home Assistant. Device list will be loaded from cloud
