### ISSUE TITLE
Sonoff Mini R2 3.6.0 not working local

### ISSUE THREAD

**Issue by Decolinow** [AlexxIT/SonoffLAN#724]
I bought 4 Sonoff Mini R2 and configured on home assistant all the same.
3 of them are running under 3.5.0 sw version and works locally pretty nice.

The one that came on version 3.6.0 never show up local working. It's always with cloud.
Does anyone got any problem like this?

I turned debug on and the only thing that shows different in the json data is
'swCtrlReverse': 'off'

**Comment by Joao-Sousa-71** [comment]
You can configure in DYI mode, I have many with fw version 3.6.0 and they work flawlessly with this component.

**Comment by AlexxIT** [comment]
@Decolinow you can check debug logs. Maybe there is something useful there
https://github.com/AlexxIT/SonoffLAN#component-debug-mode

**Comment by AlexxIT** [comment]
Closed because no response
