### ISSUE TITLE
Update fan support for HomeAssistant 2022.4.0

### ISSUE THREAD

**Issue by chemelli74** [AlexxIT/SonoffLAN#725]
Fan platform is changed: <https://developers.home-assistant.io/docs/core/entity/fan>

Version 2022.4.0, release date Aprile 6th, will throw an error:

`
2022-03-18 22:50:35 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonoff.fan: Platform not found (cannot import name 'SPEED_LOW' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).
`

Simone

**Comment by DravenSA** [comment]
> Fan platform is changed: https://developers.home-assistant.io/docs/core/entity/fan
> 
> Version 2022.4.0, release date Aprile 6th, will throw an error:
> 
> `2022-03-18 22:50:35 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sonoff.fan: Platform not found (cannot import name 'SPEED_LOW' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).`
> 
> Simone

Is there a way to fix this?

I have been to the link, but i dont know what to do to get it working

**Comment by ikrowni** [comment]
looking for a fix for this

**Comment by AlexxIT** [comment]
Fixed in v2.4.7
