### ISSUE TITLE
No devicekey

### ISSUE THREAD

**Issue by prosymnus** [AlexxIT/SonoffLAN#73]
hi, i got some error in log file
WARNING (zeroconf-ServiceBrowser__ewelink._tcp.local.) [custom_components.sonoff] No devicekey for device 10006XXXXX. and the device also not listed on STATES.
can someone help

**Comment by AlexxIT** [comment]
@prosymnus do you use login password in config?
Check this section in README:
https://github.com/AlexxIT/SonoffLAN#work-with-cloud-servers

**Comment by prosymnus** [comment]
Yes, using login n password as ewelink apps.
By the way i try to setup for T1 light switch

**Comment by prosymnus** [comment]
ok, problem solve after turning LAN mode off on my T1 switch. now it working
