### ISSUE TITLE
Sonoff Integration isn't showing up in home assistant even though it's downloaded through HACS

### ISSUE THREAD

**Issue by TheMountainburgh** [AlexxIT/SonoffLAN#730]
I've downloaded the repository through HACS and I've made sure that it's also in my custom components folder. I've also looked at the logs, restarted HA and even completely switched it off and on. 

I can't find any reason for why I can't install the integration. It just doesn't show up. I know it works because I've used it about a month ago.
![Screenshot 2022-03-24 185503](https://user-images.githubusercontent.com/44556407/159969493-4fafbb10-b6a8-474a-a78b-bc0ef5107252.png)
![Screenshot 2022-03-24 185528](https://user-images.githubusercontent.com/44556407/159969511-105fad5f-4a0a-4a3b-8d8f-8086e42409b4.png)

**Comment by AlexxIT** [comment]
Because Integration GUI not supported yet.
Issue related to https://github.com/AlexxIT/SonoffLAN/issues/83

**Comment by dmutpuul** [comment]
@AlexxIT  Thank you for all updates) yaml config will still work or i should go to gui setup ?

**Comment by AlexxIT** [comment]
YAML automatically migrate to GUI
