### ISSUE TITLE
The new R5 and S-mate devices sensor status unknow 

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/SonoffLAN#731]
Hello 

I tested the 2 new devices R5 and the S-mate over the integration booth devices are discovered as a binary sensor. But the status of the sensor is always unknow as you can view in the picture bellow 

![image](https://user-images.githubusercontent.com/47602733/160354249-cbc15ed7-c290-49bb-909c-19868d823233.png)

Is there any way to solve this issue ? 

Thank you

**Comment by AlexxIT** [comment]
Can you send link to this device?

**Comment by MiAutomations** [comment]
> Can you send link to this device?

yes 

**The R5** 

 [https://pt.aliexpress.com/item/1005004071821172.html?gatewayAdapt=glo2bra&aff_fcid=df7fa840509a4338b88f2077d609bc8b-1648910574411-03725-_98XYup&tt=CPS_NORMAL&aff_fsk=_98XYup&aff_platform=portals-tool&sk=_98XYup&aff_trace_key=df7fa840509a4338b88f2077d609bc8b-1648910574411-03725-_98XYup&terminal_id=de129cc55f0a4703bb24e070136d88fe&afSmartRedirect=y](url)
 
 **And the the S-MATE** 
 
 https://pt.aliexpress.com/item/1005003682523854.html?gatewayAdapt=glo2bra&aff_fcid=856e8d10cba44e81863ad3f2450346a7-1648910455868-08489-_AUfcid&tt=CPS_NORMAL&aff_fsk=_AUfcid&aff_platform=portals-tool&sk=_AUfcid&aff_trace_key=856e8d10cba44e81863ad3f2450346a7-1648910455868-08489-_AUfcid&terminal_id=de129cc55f0a4703bb24e070136d88fe&afSmartRedirect=y
 
 **Both needed the Mini R3 as a Gateway/HUB**
 
 https://pt.aliexpress.com/item/1005003682523854.html?gatewayAdapt=glo2bra&aff_fcid=7f754a0df5f84d5db1fcd50a3fa523a7-1648910657471-09543-_9vTc9L&tt=CPS_NORMAL&aff_fsk=_9vTc9L&aff_platform=portals-tool&sk=_9vTc9L&aff_trace_key=7f754a0df5f84d5db1fcd50a3fa523a7-1648910657471-09543-_9vTc9L&terminal_id=de129cc55f0a4703bb24e070136d88fe&afSmartRedirect=y

Thank you

**Comment by AlexxIT** [comment]
Can you collect debug logs?

**Comment by MiAutomations** [comment]
> Can you collect debug logs?

Yes please let me know how to do this and I will send you the Log

**Comment by AlexxIT** [comment]
Just check readme
https://github.com/AlexxIT/SonoffLAN#component-debug-mode

**Comment by MiAutomations** [comment]
> Just check readme https://github.com/AlexxIT/SonoffLAN#component-debug-mode

Can you please check if is this info that you need? 

**S-mate**
2022-04-11 14:58:46  DEBUG    main          abd8000082 == Init   | {'uiid': 177, 'extra': None, 'params': {'bindInfos': {'alexa': [], 'gaction': ['...', '...'], 'scene': 1}, 'subDevId': 'f4de0570', 'parentid': '1001439431', 'bleAddr': 'F4DE0570', 'outlet': 0, 'key': 0, 'count': 50, 'actionTime': '2022-04-03T10:19:04.444Z', 'cloud': 'online'}}

**R5** 
2022-04-11 14:58:46  DEBUG    main          a480029c0a == Init   | {'uiid': 174, 'extra': None, 'params': {'bindInfos': {'alexa': [], 'gaction': ['...', '...'], 'scene': 1}, 'subDevId': '7007ad75', 'parentid': '1001439431', 'bleAddr': '7007AD75', 'outlet': 3, 'key': 0, 'count': 181, 'actionTime': '2022-04-11T13:51:08.986Z', 'cloud': 'online'}}

Thank you

**Comment by AlexxIT** [comment]
Can you see something in log when you interact with device? Example button click.

**Comment by AlexxIT** [comment]
PS. Useful [logs](https://github.com/AlexxIT/SonoffLAN/discussions/734#discussioncomment-2548928)

**Comment by MiAutomations** [comment]
> see something in log when you interact with device? Exa

I will try to verify, can you please let me know what is supposed  to see ?

**Comment by AlexxIT** [comment]
@satyajitmishra93 already collected the logs

**Comment by AlexxIT** [comment]
Supported in latest master-version. Will be in next release
