### ISSUE TITLE
Release 2.4.6 does not exist in "Releases"

### ISSUE THREAD

**Issue by bjptwist** [AlexxIT/SonoffLAN#733]
Latest release 2.4.6 does not exist in releases section of the repo. There is only the git tag. This causes confusion to HACS in homeassistant:

![Screen Shot 2022-03-30 at 10 40 09](https://user-images.githubusercontent.com/956797/160802213-4ee48e77-93b4-42b6-9fc5-01ad81a2c41d.png)

**Comment by AlexxIT** [comment]
Yes. This is big GitHub bug. Many repositories are missing the latest release

**Comment by AlexxIT** [comment]
Fixed with new release v2.4.7
