### ISSUE TITLE
Sonoff DualR3 becomes unavailable within Homeassistant

### ISSUE THREAD

**Issue by bosmanrja** [AlexxIT/SonoffLAN#736]
Since a few days my Sonoff DualR3 is unavailable within Home assistant. It was before. Firmware of dual R3 is 1.4.0. 
It worked before, all other Sonoff devices are working within Home assistant. Within Ewelink all devices are working. Who can help?

**Comment by pii** [comment]
Same with my Dual R3

**Comment by AlexxIT** [comment]
Maybe you have errors in Hass log? Also you can enable debug mode.

**Comment by bosmanrja** [comment]
I found 2 interesting messages in the log, perhaps someone can advise:

2022-04-10 21:54:22 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> Running checks against v2.4.3
2022-04-10 21:54:23 DEBUG (MainThread) [custom_components.hacs] 'states' is undefined
2022-04-10 21:54:28 DEBUG (MainThread) [custom_components.hacs] 'trigger' is undefined

**Comment by pii** [comment]
No logs at all. The old cover entity got unavailable and changed to two separate switches.
![image](https://user-images.githubusercontent.com/34744672/162807471-37ed8c8e-a609-4a4c-a10b-90cfec2edbfa.png)

**Comment by bosmanrja** [comment]
> No logs at all. The old cover entity got unavailable and changed to two separate switches. ![image](https://user-images.githubusercontent.com/34744672/162807471-37ed8c8e-a609-4a4c-a10b-90cfec2edbfa.png)

I noticed the same, I also have 2 separate switches. Any suggestion how to solve?

**Comment by Simonz82** [comment]
Hi,
I too have a dualR3 sonoff and in home assist I only ever see 2 separate switches, but I don't see the power measurements in WATT, is there any configuration to do to make the 2 new entities appear?

Thanks

**Comment by bosmanrja** [comment]
I installed the latest version of Sonoff and now it works again! Thanks!

**Comment by Simonz82** [comment]
I have the latest sonoff lan 2.4.7 version made by you.
device sw version 1.4.0
latest ewelink version on the smartphone 4.20.0 (android)
but in Home assistant i only see the 2 switches, i don't see the power ampere and voltage.

**Comment by pii** [comment]
> I installed the latest version of Sonoff and now it works again! Thanks!

What's the version you are using for your Dual R3?

**Comment by AlexxIT** [comment]
Problems only with DualR3 in cover mode? Please show debug logs

**Comment by pii** [comment]
The Dual R3 shows as a cover after the 2.4.7 update. For me personally, everything is fixed.

**Comment by felipebraz** [comment]
I'm on 2.4.7 Sonoff Lan too and I have a DualR3 in measurement mode with 1.4.0 firmware, having the same problem. All sensors unknown or unavailable.

![image](https://user-images.githubusercontent.com/14303499/164305777-9c5be71e-bbca-4bf6-b182-75b2faf3b511.png)

![image](https://user-images.githubusercontent.com/14303499/164305857-c98455cc-786c-4739-bbf2-8d56fee03ffb.png)

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1

**Comment by felipebraz** [comment]
Problems keeps the same...

![image](https://user-images.githubusercontent.com/14303499/164911112-bf65611f-07e8-4bc7-921c-1457f510de6a.png)

And now I have some new ones, other sensors wich usually works fine now has problems too:

![image](https://user-images.githubusercontent.com/14303499/164911167-570e0467-62c5-426a-bd55-6470518cfd4f.png)

And my switches are unresponsive:

![image](https://user-images.githubusercontent.com/14303499/164911208-c2493b22-dc29-488f-bcfe-a4da5a64aa78.png)

I fully removed the Integration (removed the configuration, removed all entities, removed Hacs files and folders and removed the integration from Hacs) and then reinstalled again doing the configuration from zero. Keeps the same issue.

Also I have this error on HA log:

`Logger: homeassistant
Source: custom_components/sonoff/__init__.py:191
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 11:45:44 (1 occurrences)
Last logged: 11:45:44

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 212, in internal_cache_setup
    registry.setup_devices(devices)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 52, in setup_devices
    entities = [cls(self, device) for cls in spec]
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 52, in <listcomp>
    entities = [cls(self, device) for cls in spec]
  File "/config/custom_components/sonoff/switch.py", line 36, in __init__
    XEntity.__init__(self, ewelink, device)
  File "/config/custom_components/sonoff/core/entity.py", line 96, in __init__
    self.internal_update(params)
  File "/config/custom_components/sonoff/core/entity.py", line 112, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/switch.py", line 47, in set_state
    params = next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 191, in internal_normal_setup
    await internal_cache_setup(hass, entry, devices)
RuntimeError: coroutine raised StopIteration`

**Comment by AlexxIT** [comment]
Fixed in v3.0rc2

**Comment by Simonz82** [comment]
> Check new beta-version: https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1

hello, i have just updated to BETA version v3.0rc1 all the sonoff entities are not detected anymore (only some zigbee temometers), there is a problem i don't see anything anymore, if i install 2.4.7 again everything works fine as before.

**Comment by Simonz82** [comment]
> Fixed in v3.0rc2

now work all sonoff
and i read the power from DUALR3

TOP !!!!

**Comment by brucehatherell** [comment]
I had the same and unfortunately never invested further but chose to go the tasmota route which is stable…. Had I been able to get the power metrics within HA rather than in the EWeLink frame I would not have done the Tasmota flashing.

On 06 Apr 2022, at 12:51, NotHappy ***@***.***> wrote:

﻿

Same with my Dual R3
