### ISSUE TITLE
HA 0.108 error?

### ISSUE THREAD

**Issue by rhgiter** [AlexxIT/SonoffLAN#74]
I get this 👍 
Failed config
  General Errors: 
    - Component error: sonoff - No module named 'Crypto'

when I use : Check Home Assistant configuration add-on

?  what is it ?

**Comment by mattlward** [comment]
I am seeing this as well.  Latest of everything installed, 0.107.7.

**Comment by NicoSomerwil** [comment]
Thanks for your great component! I love it.

Since 0.108.0 my Sonoff Remote control usb devices are not working anymore. Hopefully you can solve this. No errors noticed, they are just not available anymore since the update from 0.107.7 to 0.108.0. Tried several restarts, no luck. Greetings!!

**Comment by auredor** [comment]
I get the same error message with Check configuration add-on.
But this is not a real issue as I can use the devices (sonoff S26) after update to HA 108.1

**Comment by auredor** [comment]
### The problem
Check Home Assistant configuration v3.2.0 returns an error for custom SONOFF integration  (see [https://github.com/AlexxIT/SonoffLAN](https://github.com/AlexxIT/SonoffLAN)) :

**Component error: sonoff - No module named 'Crypto**

### Environment

Home Assistant Core release with the issue: 0.108.1
Last working Home Assistant Core release (if known):
Operating environment (Home Assistant/Supervised/Docker/venv): HassOS 3.12
Integration causing this issue: Check Home Assistant configuration 3.2.0
Link to integration documentation on our website:

### Problem-relevant configuration.yaml

### Traceback/Error logs
[[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[16:23:13] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:23:13] INFO: Setup udev devices
[16:23:13] INFO: Don't worry, this temporary installation is not overwriting your current one.
[16:23:13] INFO: Installing Home Assistant: latest...
[16:23:13] INFO: Please be patient, this might take a few minutes...
[16:23:35] INFO: Installed Home Assistant 0.108.5
[16:23:35] INFO: Making a copy of your configuration for checking...
[16:23:35] INFO: Checking your configuration against this version...
[16:25:05] ERROR: The configuration check did not pass!
[16:25:05] ERROR: See the output below for more details.
INFO:homeassistant.util.package:Attempting install of colorlog==4.1.0
Testing configuration at /tmp/config
INFO:homeassistant.util.package:Attempting install of xknx==0.11.2
INFO:homeassistant.util.package:Attempting install of hbmqtt==0.9.5
INFO:homeassistant.util.package:Attempting install of paho-mqtt==1.5.0
INFO:homeassistant.util.package:Attempting install of aiohttp_cors==0.7.0
INFO:homeassistant.util.package:Attempting install of flux_led==0.22
INFO:homeassistant.util.package:Attempting install of ha-philipsjs==0.0.8
INFO:homeassistant.util.package:Attempting install of pysonos==0.0.25
INFO:homeassistant.util.package:Attempting install of defusedxml==0.6.0
INFO:homeassistant.util.package:Attempting install of netdisco==2.6.0
INFO:homeassistant.util.package:Attempting install of python-forecastio==1.4.0
INFO:homeassistant.util.package:Attempting install of google-api-python-client==1.6.4
INFO:homeassistant.util.package:Attempting install of httplib2==0.10.3
INFO:homeassistant.util.package:Attempting install of oauth2client==4.0.0
INFO:homeassistant.util.package:Attempting install of speedtest-cli==2.1.2
INFO:homeassistant.util.package:Attempting install of wakeonlan==1.1.6
INFO:homeassistant.util.package:Attempting install of mutagen==1.43.0
INFO:homeassistant.util.package:Attempting install of gTTS-token==1.1.3
INFO:homeassistant.util.package:Attempting install of google-cloud-texttospeech==0.4.0
INFO:homeassistant.util.package:Attempting install of hass-nabucasa==0.32.2
INFO:homeassistant.util.package:Attempting install of home-assistant-frontend==20200407.2
INFO:homeassistant.util.package:Attempting install of PyNaCl==1.3.0
INFO:homeassistant.util.package:Attempting install of distro==1.4.0
INFO:homeassistant.util.package:Attempting install of sqlalchemy==1.3.15
INFO:homeassistant.util.package:Attempting install of HAP-python==2.8.2
INFO:homeassistant.util.package:Attempting install of aiofiles==0.4.0
INFO:homeassistant.util.package:Attempting install of aiogithubapi==0.5.0
INFO:homeassistant.util.package:Attempting install of hacs_frontend==20200309184730
INFO:homeassistant.util.package:Attempting install of integrationhelper==0.2.2
INFO:homeassistant.util.package:Attempting install of semantic_version==2.8.4
INFO:homeassistant.util.package:Attempting install of influxdb==5.2.3
INFO:homeassistant.util.package:Attempting install of WazeRouteCalculator==0.12
INFO:homeassistant.util.package:Attempting install of psutil==5.7.0
**Failed config
  General Errors: 
    - Component error: sonoff - No module named 'Crypto'**
Successful config (partial)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

### Additional information

**Comment by mantaalex** [comment]
hopefully someone could fix it i had troubles with 108.5 to had to downgrade back

**Comment by mariusherta** [comment]
i get this too:

2020-04-20 20:28:59 ERROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Unable to import component: No module named 'Crypto'

**Comment by mattlward** [comment]
I forgot to post... I went ahead with the 0.108.1 and subsequent updates and it seems to be working for me.

**Comment by mantaalex** [comment]
i don't know why but i had to manual click all the switches in the ewelink app before they where all found in home assistant.
it all worked before it was just after the updates

**Comment by bpark47** [comment]
I have the same problem but the module named alternates between Crypto and Zerconf.
I went ahead and tried running HA and both my new eWelink switches were found and appear to operate correctly.
They are not Sonoff but these from Amazon UK: https://www.amazon.co.uk/gp/product/B07WYV4GHH/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

**Comment by newstler** [comment]
> ROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Unable to import component: No module named 'Crypto'

Had the same issue. Had to `pip install pycryptodome` in HA virtual env.

**Comment by mantaalex** [comment]
i had the problem as soon as i restarted my Home assistant
all my sonoff things where unavailable 
i tryed alot not working things 
but i have found my solution as this:
i was using an Netgear R7000 Router
running standard netgear firmware
someone told me maybe it was mDNS but wasn't sure
so i tought maybe i flash that crappy netgear ;)
i'm using Advanced Tomato now (because i didn't get my USB working on Fresh Tomato)
and now it works i can restart as many as i want directly sonoff is available and working
Maybe it could help someone grz alex

**Comment by AlexxIT** [comment]
#93 Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v1.10.4

**Comment by auredor** [comment]
Thank you.

I've just checked and so far there is no warning anymore with the check
congig tool.

Thanks.

**Comment by mantaalex** [comment]
many thanks for the fix i updated my version looks ok ;) keep up the good work !
