### ISSUE TITLE
Cannot Update via HACS 2022.4

### ISSUE THREAD

**Issue by TommisGR** [AlexxIT/SonoffLAN#743]
Cannot update via HACS 
error mesage
check the network on the host running Home Assistant. This is not a problem with HACS but how your host communicates with GitHub.
Any ideas on what to check.

All other updates etc. work with no issues.
This happens on 2 different installs 
Raspberry pi 3B+ and a VirtualBox VM

**Comment by AlexxIT** [comment]
This component is not related to HACS functionality.

If you have any problem - you may install it manually
https://github.com/AlexxIT/SonoffLAN#install-with-hacs

Or with my Updater
https://github.com/AlexxIT/Updater
