### ISSUE TITLE
unsupported for device_class power

### ISSUE THREAD

**Issue by Raul-7-7** [AlexxIT/SonoffLAN#745]
Hi guys, 
After the latest update, I get this error on HA Logs on all my Sonoff S31 switches, (I also got POWR2 and they dont have this issue)

sensor.sonoff_xyz_voltage has unit V which is unsupported for device_class power
sensor.sonoff_xyz_current has unit A which is unsupported for device_class power

Everything works as normal, just wondering if its something on my side and OK to ignore? 
Cheers,
HA: Home Assistant 2022.4.3
SonoffLAN: v2.4.7

**Comment by TommisGR** [comment]
I am having same issue with POWR2 
POWR3 no issues
HA: Home Assistant 2022.4.3
SonoffLAN: v2.4.7
HACS: 1.24.5 (this solved my cannot upgrade via HACS)

**Comment by ninlee** [comment]
having the same issue with POWr2

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1

**Comment by Raul-7-7** [comment]
Hi @AlexxIT Still seeing this in the log as of the latest version, everything works, but just an FYI.
