### ISSUE TITLE
Light part works, Fan part gives me error:

### ISSUE THREAD

**Issue by Naro90029** [AlexxIT/SonoffLAN#748]
"Unable to prepare setup for platform sonoff.fan: Platform not found (cannot import name 'SPEED _LOW from homeassistent.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/_init_.py))."

It works in older versions of HA such as core_2022.3.3, but not in recent versions such as core_2022.4.4

**Comment by AlexxIT** [comment]
Fixed in latest release. 2.4.7

**Comment by Naro90029** [comment]
It works however it doesn't work with the Lovelace slider to gradually increase the speed of the fan. It jumps to on or off.

**Comment by Naro90029** [comment]
> Fixed in latest release. v2.4.7

It works however it doesn't work with the Lovelace slider to gradually increase the speed of the fan. It jumps to on or off.

**Comment by AlexxIT** [comment]
What device do you using as fan?

**Comment by Naro90029** [comment]
> What device do you using as fan?

In the details it clearly says SonOff, but the issue is fixed with an update; and Lovelace slider might be fixed later on so I'm using another slider for now.
