### ISSUE TITLE
Dimmer Sonoff D1 turn ON randomly

### ISSUE THREAD

**Issue by Markgit-dev** [AlexxIT/SonoffLAN#75]
У меня иногда включаеться Dimmer Sonoff D1

При этом время включения совподает с такой ошибкой в логах
Log Details (ERROR)
Logger: homeassistant.core
Source: custom_components/sonoff/__init__.py:237
First occurred: 7:51:49 PM (2 occurrences)
Last logged: 7:51:49 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 237, in state_listener
    new_state = event.data['state']
KeyError: 'state'

Что это значит? Как это исправить?

**Comment by Markgit-dev** [comment]
?

**Comment by AlexxIT** [comment]
А это не мой компонент ругается
https://github.com/peterbuga/HASS-sonoff-ewelink/blob/master/sonoff/__init__.py#L237

**Comment by Markgit-dev** [comment]
Да. Спасибо. Тоже заметил, что это не Ваш компонент. 

Но самое интересное, что Dimmer Sonoff D1 подключен у меня к Вашему компонету. 
Я вернул предыдушую версию v1.10.2. Прошло уже больше суток и ошибки пока не было.
С версией 1.10.3 ошибка появлялась 1-2 раза в день.

**Comment by AlexxIT** [comment]
Версии 1.10.2 и 1.10.3 отличаются минимальным кодом. Точно не должны влиять на D1.
Возможно диммер включается вообще не из-за HA.

**Comment by Markgit-dev** [comment]
Хорошо.
Спасибо. Буду наблюдать, думать и искать причину.
