### ISSUE TITLE
Looking for some help with "Error while setting up sonoff platform for switch"

### ISSUE THREAD

**Issue by MeanderingWanderer** [AlexxIT/SonoffLAN#758]
Hi, was looking for some help with some errors that are appearing in my logs.  They have been appearing for a while, but typically i ignore cuz it doesn't seem to affect any other devices, all work as expected.

I have a Sonoff Micro USB that I rarely use, and just found it isn't appearing in HA.  Perhaps these errors stem from that.
(Documentation says Micro USB works with firmware 3.4.0, and my micro fw is 3.7.1.)

I'm not the best at reading error logs, and not really sure how to fix this error.
Appreciate any help.

```Logger: homeassistant.components.switch
Source: custom_components/sonoff/sonoff_main.py:284
Integration: Switch (documentation, issues)
First occurred: 7:51:42 AM (2 occurrences)
Last logged: 7:51:42 AM

Error adding entities for domain switch with platform sonoff
Error while setting up sonoff platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 798, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/sonoff/switch.py", line 44, in async_added_to_hass
    device = self._init()
  File "/config/custom_components/sonoff/sonoff_main.py", line 267, in _init
    self._update_handler(state, attrs)
  File "/config/custom_components/sonoff/switch.py", line 51, in _update_handler
    self._is_on = any(self._is_on_list(state))
  File "/config/custom_components/sonoff/sonoff_main.py", line 284, in _is_on_list
    return [state['switch'] == 'on']
KeyError: 'switch'```

**Comment by AlexxIT** [comment]
Show your config

**Comment by MeanderingWanderer** [comment]
sorry about that.   also attached debug log

sonoff:
  username: !secret sonoffLAN_UN
  password: !secret sonoffLAN_PW
  
  debug: true  # to get a link for debug log
  reload: always  #update device list when HA starts

  default_class: light
  devices:
    1000b1e722:
      device_class: [light, fan]
      name: Chad/Nick Bedroom Ceiling
    10011fd2db:
      device_class: light
      name: Barn Wall Lights
    10012ae8c1:
      device_class: switch
      name: 5v Power - Kitchen Display
    10012c7ee8:
      device_class: switch
      name: 5v Power - CN Display
    10013abf16_1:
      device_class: light
      name: Bathroom Upstairs
    10013abf16_2:
      device_class: light
      name: Upstairs Bathroom Ceiling
   rfbridge:
    SmokeDetector_basement:
      name: Smoke Detector Basement
      device_class: smoke
      timeout: 30
    SmokeDetector_mainfloor:
      name: Smoke Detector Main Floor
      device_class: smoke
      timeout: 30
    SmokeDetector_upstairs:
      name: Smoke Detector Upstairs
      device_class: smoke
      timeout: 30


Thanks Alexx-

[sonoffLANdebug.txt](https://github.com/AlexxIT/SonoffLAN/files/8556798/sonoffLANdebug.txt)

**Comment by AlexxIT** [comment]
10013abf16_1, 10013abf16_2 - shouldn't work

Sonoff Micro should have `device_class: [switch]`. This is stupid because micro has multichannel firmware...
