### ISSUE TITLE
Sonoff TH16 Changed from °F to °C

### ISSUE THREAD

**Issue by johnfuller5** [AlexxIT/SonoffLAN#760]
I noticed a few days ago my 2 Sonoff TH16 Temperature and Humidity sensors changed from °F to °C.  I first tried changing this in settings.  It could select °F but it wouldn't take - just stayed with °C. I then tried custom configuration.  The units changed but the value from sensor was still C.  in eWeLink, the units are °F and the values are in °F.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/718#issuecomment-1107450157
