### ISSUE TITLE
Installed Via HACS but not showing in Devices

### ISSUE THREAD

**Issue by MasterCATZ** [AlexxIT/SonoffLAN#763]
Can not work out how to Configure this only option is update ? 

![Screenshot from 2022-04-24 13-35-23](https://user-images.githubusercontent.com/1857824/164955392-1140bfd6-7111-4e5a-b7c3-52a00df2ced9.png)
![Screenshot from 2022-04-24 13-35-52](https://user-images.githubusercontent.com/1857824/164955396-6d655eb8-85e6-4e66-b7d4-011a9868b1a8.png)
![Screenshot from 2022-04-24 13-35-37](https://user-images.githubusercontent.com/1857824/164955397-7dca035a-fa16-4eb3-8b43-91517169bb09.png)

```
Version | core-2022.4.6
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.103-v8
CPU Architecture | aarch64

```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/83
