### ISSUE TITLE
 Feature request , can we have a update button for going Beta 

### ISSUE THREAD

**Issue by MasterCATZ** [AlexxIT/SonoffLAN#764]
Not too sure how to get Home Assistant to install beta version 

as their is an update button that seems to only do version 2 is their a way to choose a Beta V3 version ?

**Comment by AlexxIT** [comment]
HACS > Sonoff LAN > Redownload > you can select beta-versions or master-version.

**Comment by MasterCATZ** [comment]
https://www.buymeacoffee.com/AlexxIT

Coffee's sent :D
