### ISSUE TITLE
Not able to change bulb brightness back to white

### ISSUE THREAD

**Issue by shakier21** [AlexxIT/SonoffLAN#766]
I finally managed to get my Sonoff B05 Bulbs to change colors and brightness in home assistant due to this fix "Sonoff RGB Bulb domain is switch instead of light B05-BL #712" i can set colors and scenes but setting back to white mode doesnt work, you can change it in the ewelink app to white mode then it will appear in home assistant but cannot do this change from home assistant itself

**Comment by AlexxIT** [comment]
What integration version do you using?

**Comment by shakier21** [comment]
i am using version 2.4.7

**Comment by bwp91** [comment]
I don't know if this info can help, this is for @AlexxIT knowledge:

* **For UIID 104 (B02-B-A60, B05-B-A60, GTLC104)**
  * I found that when changing brightness the `ltype` param is not needed
  * I found that when changing colour, the `ltype` param is only needed when it is being changed between color or white

However

* **For UIID 136 (B05-BL-A19)**
  * The `ltype` param is required every time you want to change brightness (even if the type is the same as before)
  * The `ltype` param is required for every colour/colour temperature change (even when changing between the same mode)

Also the UIID 136 supports LAN mode I can help with the endpoints and params if you want :)

**Comment by AlexxIT** [comment]
Oh. Support so many different bulbs is really painful.

**Comment by AlexxIT** [comment]
@bwp91 Thanks!
@shakier21 please check latest master version with both bulb models. If you have any trouble - please collect debug logs
https://github.com/AlexxIT/SonoffLAN#debug-page

**Comment by mohitg11** [comment]
Thanks for the great work @AlexxIT, as @bwp91 mentioned, the BL version supports LAN control, in your latest commit top master, has the BL version been configured to prefer LAN over Cloud?

**Comment by AlexxIT** [comment]
@mohitg11 every device prefer LAN over cloud, but it will work only if commands same.

**Comment by bwp91** [comment]
For lan mode these bulbs UIID 136,

* on and off using only `switch` param can be sent to `/zeroconf/switch` path
* brightness and colour using existing full payload can be sent to `/zeroconf/dimmable` path

**Comment by AlexxIT** [comment]
@bwp91 thanks. I have added `dimmable` to all lights if they have LAN protocol

**Comment by shakier21** [comment]
@AlexxIT i have updated to the latest master version, works well now, thank you for your great work

**Comment by bwp91** [comment]
@AlexxIT do you have discord? feel free to add me bwp91#2158 could be useful to chat sometimes?

**Comment by emeyedeejay** [comment]
Firstly - love your work ... so useful!

I got 4x B05-BL bulbs today and changing form color to white and setting white temp is not working. FW is BL1-ALL-LED. 

Can I supply any other info to assist in you adding support?

`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Africa/Johannesburg",
    "os_name": "Linux",
    "os_version": "5.15.74",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.28.4",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "edge_tts": {
      "version": "0.0.1",
      "requirements": [
        "edge-tts==5.0.6"
      ]
    },
    "webrtc": {
      "version": "v2.3.1",
      "requirements": []
    },
    "dwains_dashboard": {
      "version": "3.3.0",
      "requirements": []
    },
    "nodered": {
      "version": "1.1.2",
      "requirements": []
    },
    "daily_schedule": {
      "version": "1.4.1",
      "requirements": []
    },
    "irrigation_unlimited": {
      "version": "2022.11.0",
      "requirements": []
    },
    "browser_mod": {
      "version": "2.1.2",
      "requirements": []
    },
    "google_home": {
      "version": "1.9.15",
      "requirements": [
        "glocaltokens==0.6.8"
      ]
    },
    "hass_agent_notifier": {
      "version": "2022.10.25.1",
      "requirements": []
    },
    "mass": {
      "version": "2022.11.0",
      "requirements": [
        "music-assistant==1.8.7",
        "git+https://github.com/music-assistant/databases@fix-breaking-sqlalchemy-cursor-changes#databases==0.6.2"
      ]
    },
    "coct_loadshedding": {
      "version": "1.0.5",
      "requirements": [
        "aiohttp-retry==1.0"
      ]
    },
    "sonoff": {
      "version": "3.3.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "ytube_music_player": {
      "version": "20220205.01",
      "requirements": [
        "ytmusicapi==0.24.0",
        "pytube==10.5.1",
        "integrationhelper==0.2.2"
      ]
    },
    "localtuya": {
      "version": "4.1.1",
      "requirements": []
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "eskom_loadshedding": {
      "version": "1.1.2",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "/api/sonoff/b4f2f5e8-3f9d-4d9a-9fab-2639a87547e1",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.3.1",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "b20e33c",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": true
    },
    "errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud processing error"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/light.py",
          379
        ],
        "timestamp": 1669990852.709916,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 286, in run_forever\n    await self._process_ws_msg(resp)\n  File \"/config/custom_components/sonoff/core/ewelink/cloud.py\", line 346, in _process_ws_msg\n    self.dispatcher_send(SIGNAL_UPDATE, data)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/ewelink/__init__.py\", line 188, in cloud_update\n    self.dispatcher_send(did, params)\n  File \"/config/custom_components/sonoff/core/ewelink/base.py\", line 59, in dispatcher_send\n    handler(*args, **kwargs)\n  File \"/config/custom_components/sonoff/core/entity.py\", line 108, in internal_update\n    self.set_state(params)\n  File \"/config/custom_components/sonoff/light.py\", line 379, in set_state\n    state = params[effect]\nKeyError: 'white'\n",
        "count": 1,
        "first_occurred": 1669990852.709916
      },
      {
        "name": "custom_components.sonoff.core.ewelink.local",
        "message": [
          "1001603ea8 => Local4 | {'cmd': 'dimmable', 'ltype': 'white', 'white': {'br': 100, 'ct': 239}} <= {'sequence': '1669990886000', 'encrypt': True, 'seq': 16, 'error': 400}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/local.py",
          274
        ],
        "timestamp": 1669990886.7053304,
        "exception": "",
        "count": 1,
        "first_occurred": 1669990886.7053304
      },
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud ERROR: {'error': 400, 'deviceid': '1001603ea8', 'apikey': '6778f9ef-219a-432a-9b95-c17d53892e1d', 'sequence': '1669990886000', 'uid': '6778f9ef-219a-432a-9b95-c17d53892e1d'}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          286
        ],
        "timestamp": 1669990887.6776404,
        "exception": "",
        "count": 1,
        "first_occurred": 1669990887.6776404
      }
    ],
    "devices": {
      "1001603ea8": {
        "uiid": 136,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "rssi": -62,
          "fwVersion": "1.5.1",
          "switch": "on",
          "ltype": "white",
          "white": {
            "br": 100,
            "ct": 71
          },
          "remoteCtrlList": [],
          "lightScenes": [],
          "ssid": "***",
          "bssid": "***",
          "mac": "***",
          "color": {
            "br": 100,
            "r": 0,
            "g": 255,
            "b": 0
          },
          "only_device": {
            "ota": "success",
            "ota_fail_reason": 0
          },
          "colorful": {
            "br": 100,
            "r": 255,
            "g": 0,
            "b": 0,
            "tf": 1,
            "sp": 1
          },
          "bright": {
            "br": 100,
            "ct": 100
          },
          "goodNight": {
            "br": 5,
            "ct": 0
          },
          "nightLight": {
            "br": 1,
            "ct": 0
          },
          "party": {
            "br": 45,
            "r": 254,
            "g": 132,
            "b": 0,
            "tf": 1,
            "sp": 1
          },
          "soft": {
            "br": 20,
            "r": 38,
            "g": 254,
            "b": 0,
            "tf": 1,
            "sp": 1
          },
          "addSubDevState": "off",
          "addTimeOut": 10
        },
        "model": "B05-BL",
        "online": true,
        "localtype": "light"
      },
      "10012daff2": {
        "uiid": 1,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "on",
          "switch": "on",
          "fwVersion": "3.6.0",
          "rssi": -60,
          "staMac": "***",
          "startup": "off",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500,
          "swMode": 2,
          "swCtrlReverse": "off"
        },
        "model": "BASIC_R3",
        "online": false,
        "localtype": null
      },
      "1000f06bdf": {
        "uiid": 1,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "on",
          "switch": "on",
          "fwVersion": "3.5.1",
          "rssi": -57,
          "staMac": "***",
          "startup": "on",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500,
          "only_device": {
            "ota": "success"
          },
          "ssid": "***",
          "bssid": "***"
        },
        "model": "BASICR2",
        "online": false,
        "localtype": null
      },
      "100026bb20": {
        "uiid": 14,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "off",
          "ssid": "***",
          "bssid": "***",
          "switch": "off",
          "fwVersion": "3.5.0",
          "rssi": -67,
          "staMac": "***",
          "startup": "off",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500,
          "timers": "***"
        },
        "model": "Sonoff",
        "online": true,
        "localtype": "plug"
      },
      "100107fd2d": {
        "uiid": 32,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "on",
          "ssid": "***",
          "bssid": "***",
          "fwVersion": "3.5.0",
          "staMac": "***",
          "rssi": -76,
          "init": 1,
          "alarmType": "pcv",
          "alarmVValue": [
            -1,
            -1
          ],
          "alarmCValue": [
            -1,
            -1
          ],
          "alarmPValue": [
            -1,
            -1
          ],
          "switch": "off",
          "startup": "off",
          "pulse": "off",
          "pulseWidth": 500,
          "power": "0.00",
          "voltage": "232.27",
          "current": "0.00",
          "oneKwh": "start",
          "uiActive": 60,
          "hundredDaysKwh": "get",
          "endTime": "",
          "startTime": "2022-08-08T09:51:58.374Z",
          "timers": "***",
          "timeZone": 2,
          "onKwh": "start",
          "demNextFetchTime": 1661637600000
        },
        "model": "POWR2",
        "online": false,
        "localtype": null
      },
      "10003c8f6e": {
        "uiid": 14,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "on",
          "ssid": "***",
          "bssid": "***",
          "switch": "off",
          "fwVersion": "3.5.0",
          "rssi": -60,
          "staMac": "***",
          "startup": "off",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500
        },
        "model": "Basic",
        "online": true,
        "localtype": "plug"
      },
      "1000f64b5e": {
        "uiid": 1,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "on",
          "switch": "off",
          "fwVersion": "3.5.1",
          "rssi": -67,
          "staMac": "***",
          "startup": "off",
          "init": 1,
          "pulse": "on",
          "pulseWidth": 500,
          "only_device": {
            "ota": "success"
          },
          "ssid": "***",
          "bssid": "***"
        },
        "model": "RE5V1C",
        "online": true,
        "localtype": "plug"
      },
      "10003da47f": {
        "uiid": 14,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "on",
          "ssid": "***",
          "bssid": "***",
          "switch": "off",
          "fwVersion": "3.5.0",
          "rssi": -56,
          "staMac": "***",
          "startup": "off",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500
        },
        "model": "Basic",
        "online": true,
        "localtype": "plug"
      },
      "10003c1db0": {
        "uiid": 14,
        "params": {
          "bindInfos": "***",
          "switch": "off",
          "fwVersion": "3.5.0",
          "rssi": -83,
          "staMac": "***",
          "startup": "on",
          "version": 8,
          "sledOnline": "off",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500,
          "timers": "***",
          "only_device": {
            "ota": "success"
          },
          "ssid": "***",
          "bssid": "***"
        },
        "model": "Basic",
        "online": true,
        "localtype": "plug"
      },
      "10003f32a2": {
        "uiid": 14,
        "params": {
          "bindInfos": "***",
          "switch": "off",
          "fwVersion": "3.5.0",
          "rssi": -72,
          "staMac": "***",
          "startup": "off",
          "version": 8,
          "sledOnline": "on",
          "ssid": "***",
          "bssid": "***",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500,
          "timers": "***"
        },
        "model": "Basic",
        "online": true,
        "localtype": "plug"
      },
      "10003c3524": {
        "uiid": 14,
        "params": {
          "switch": "on",
          "fwVersion": "3.5.0",
          "startup": "on",
          "staMac": "***",
          "rssi": -77,
          "timers": "***",
          "bindInfos": "***",
          "sledOnline": "on",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500,
          "version": 8,
          "only_device": {
            "ota": "success"
          },
          "ssid": "***",
          "bssid": "***"
        },
        "model": "Basic",
        "online": true,
        "localtype": "plug"
      },
      "100026b9a1": {
        "uiid": 14,
        "params": {
          "bindInfos": "***",
          "version": 8,
          "sledOnline": "on",
          "switch": "off",
          "fwVersion": "3.5.0",
          "rssi": -94,
          "staMac": "***",
          "startup": "on",
          "init": 1,
          "pulse": "off",
          "pulseWidth": 500,
          "timers": "***",
          "only_device": {
            "ota": "success"
          },
          "ssid": "***",
          "bssid": "***"
        },
        "model": "Sonoff",
        "online": true,
        "localtype": null
      }
    }
  }
}`
