### ISSUE TITLE
Light B05-B Not Working in New version

### ISSUE THREAD

**Issue by fabiobrolo** [AlexxIT/SonoffLAN#767]
The sonoff light B05-B was working fine in the previous version, however is not working any more.
This light appears as a device, however its controls are wrong and does not work.

**Comment by AlexxIT** [comment]
What exact version do you using? Maybe you have some errors in Hass log.

**Comment by fabiobrolo** [comment]
Version 3.0rc2.

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:299
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 15:07:06 (1 occurrences)
Last logged: 15:07:06

UNKNOWN cloud msg: {'action': 'reportSubDevice', 'deviceid': '10013db2b5', 'apikey': 'XXXXXXX', 'userAgent': 'device', 'd_seq': 24685, 'params': {'state': 1, 'subDevices': [{'subDevId': 'f1b42125004b1200', 'uiid': '3026', 'deviceid': 'a44000d982', 'online': True}]}}

**Comment by AlexxIT** [comment]
Probably the same problem #766
