### ISSUE TITLE
Sonoff 4ch Pro one channel not matching channel state or ewelink

### ISSUE THREAD

**Issue by Victripper** [AlexxIT/SonoffLAN#771]
I have a 4ch Pro which I have one channel which won't turn off, was previously channel 4 but now channel 2 that won't turn off in HA, when I turn it off it reverts to on within a second or two.  I have reinstalled HA two weeks ago due to a seperate issue and still the same issue.  The unit shows off along with off on the ewelink app.

The only thought of a trigger was a loop triggered in my node red setup and then after this it seems to be locked up but the rebuild of HA, removing and reinstalling sonoff LAN didn't make any difference.  I have power cycled the unit and previously I reset the 4ch pro to default and rebuilt but still has the mismatch.

I am running the latest HA core-2022.4.7 and supervisor-2022.04.0, nothing seen in logs

**Comment by Victripper** [comment]
I just changed over from cloud connection to local and cloud.  Seems channel 2 can now be turned off from HA but I can't turn it on.   I have turn on and off the other channels but channel 2 only flicks the screen

**Comment by AlexxIT** [comment]
What version of Integration do you using? Show debug logs

**Comment by Victripper** [comment]
2.4.7 and I have emailed you the debug log as not sure what info should be posted in public or not

**Comment by AlexxIT** [comment]
Try to reset your device and add again to ewelink app. It has some internal bug.

**Comment by Victripper** [comment]
Thanks for you help confirming  the reset was one of the first ways I attempted to correct it after I power reset the device. 

When I saw  the Welcome back! Message I thought it might of done a panic reset
