### ISSUE TITLE
RSSI Sensor

### ISSUE THREAD

**Issue by milandzuris** [AlexxIT/SonoffLAN#775]
Hi, i have 6 Sonoff devices 2-Sonoff Switch 2TX, 1-Sonoff 1TX, 1-Outside Outlet, 1-Sonoff Mini, i have only for mini outlet and one of switch 2TX rssi sensor, where is the problem?.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#debug-page

**Comment by milandzuris** [comment]
This error originated from a custom integration.

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:301
Integration: Sonoff (documentation, issues)
First occurred: April 27, 2022, 21:43:45 (1 occurrences)
Last logged: April 27, 2022, 21:43:45

Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '100086cab6', 'apikey': '946b871a-1b84-421f-9d01-607d03f2f89b', 'sequence': '1651088619001'}
