### ISSUE TITLE
Delays on/off

### ISSUE THREAD

**Issue by bulava92** [AlexxIT/SonoffLAN#777]
In the last couple of days, delays on various sonoff Wi-Fi relays have often begun to appear. Both through home assistant and through Alice/HomeKit, configured on the basis of home assistant. At the same time, through the standard ewelink application, control is still instantaneous. What can be checked, what could be the problem?

Other Wi-Fi devices - yeelight, xiaomi and so on, also connected to home assistant work perfectly, the network is not overloaded. The problem is with this integration and sonoff relay.

**Comment by AlexxIT** [comment]
What Integration version do you use?

**Comment by AlexxIT** [comment]
Closing issue without answer
