### ISSUE TITLE
SonoffLAN integration doesn't show up in ha

### ISSUE THREAD

**Issue by dguihal** [AlexxIT/SonoffLAN#778]
Hello, sorry maybe my issue is quite obvious but really I don't get what's happening

1. installed custom component v2.4.7 though hacs :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/4045744/165709984-dd37b433-0148-4068-a929-767d15a66db7.png)
2. Restarted HA :heavy_check_mark: 
3. HA logs tells it sees custom component :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/4045744/165710339-8d79e628-ef96-43a0-b1c2-f2f93d3a2285.png)
4. Try to load integration into HA nothing found
![image](https://user-images.githubusercontent.com/4045744/165710577-56a5d92b-c1dc-4400-9ff4-3d640ada7002.png)

Home Assistant 2022.4.7

I don't have issue with my other hacs component, so I think there might be something wrong with this one (tried with master version, nothing show up also)

**Comment by edu24x** [comment]
Hello!!
You need at least [v3.0rc1](https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0rc1), or enable betas in HACS.

Greetings.

**Comment by AlexxIT** [comment]
@edu24x thanks!

**Comment by dguihal** [comment]
Hello, sorry but still same with 3.0-rc4

> bash-5.1# cat manifest.json 
> {
>   "domain": "sonoff",
>   "name": "Sonoff",
>   "config_flow": true,
>   "documentation": "https://github.com/AlexxIT/SonoffLAN",
>   "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
>   "codeowners": ["@AlexxIT"],
>   "dependencies": ["http", "zeroconf"],
>   "requirements": ["pycryptodome>=3.6.6"],
>   "version": "3.0rc4",
>   "iot_class": "local_push"
> }

**Comment by dguihal** [comment]
OK for the record, managed to make this work with adding

> sonoff:
>   username: xxxxx
>   password: yyyyyyy

to ha configuration.yaml file

**Comment by AlexxIT** [comment]
@dguihal you just need to clear your browser cache
