### ISSUE TITLE
Binary sensors not getting Device class on v3.0rc4

### ISSUE THREAD

**Issue by ShvetsovZE** [AlexxIT/SonoffLAN#779]
Firstly wanted to say thank you for the great job you've done!
I used v2 before but was missing the ability to track battery level for **ZigBee** motion/door sensors. decided to try rc version and boom it's there! Thank you one more time. 
what I've noticed tho that the device class is not being automatically populated anymore which creates a bit of tension with other addons as they pull devices based on their class. Obviously, it could be easily fixed by manually assigning classes via UI, but would be wonderful if that possible to return the behavior from the previous version.
**Motion sensor**: snzb03
**Door sensor**: snzb04
Please let me know if you need any more information.

**Comment by ShvetsovZE** [comment]
![Capture](https://user-images.githubusercontent.com/20457349/166167287-5988fdc9-eb04-4e2d-9c27-844bacde6ed0.PNG)
Yes, i'm sure it was rc4. I have more devices to connect I'll going to upgrade to 3.0.1 and give you an update later today about how it went.

**Comment by ShvetsovZE** [comment]
Hey @AlexxIT it's still the same even for version 3.0.1
![Capture2](https://user-images.githubusercontent.com/20457349/166345486-ff084fca-955b-43dd-9d2e-397e60d89ae2.PNG)

**Comment by Ih8rain2** [comment]
The DW2 door sensor does have that issue too. I guess something is not going well with assigning the device class for binary sensors ..

**Comment by AlexxIT** [comment]
Fixed in latest master version
