### ISSUE TITLE
Device_class: Cover - please?

### ISSUE THREAD

**Issue by 8illy8o8** [AlexxIT/SonoffLAN#78]
I would really like to be able to set the device_class to cover instead of switch so that home assistant and google assistant assign the door properties.
Is there a way I can do this or if not could you please make that option available?
Thanks

**Comment by AlexxIT** [comment]
What is your sonoff device?
Switch can: on / off.
Cover: can open / closed / opening / closing.

**Comment by 8illy8o8** [comment]
The Sonoff controlling the garage door is a Sonoff SV (low voltage version). However I could also use a Sonoff Basic or Sonoff Mini as I have those. In the sonoff: configuration I have set the device class as 'switch'. I have tried every way I can think to set it manually to a 'cover' without success.
The reason I want to make the device a 'cover' is that Google assistant will then assign it door security and require a PIN. Otherwise anyone can open the door as Google thinks it is just a switch.

Also is it possible to set the device name to something meaningful? I have many sonoff_1000xxxx that it is making the code really confusing.

**Comment by AlexxIT** [comment]
You can change device name from GUI (gear icon in device info window).

How does your switch work?
When it turns on - the gates open, when it turns off - the gate closes?

**Comment by 8illy8o8** [comment]
When switch turns to on, sonoff inches for 1 sec (turns on for 1 sec) and garage door opens
When switch turns off, sonoff inches for 1 sec and garage door closes.
There is a magnetic sensor that shows when the door is closed and another that shows when the door is open. When both sensors are open then the door is opening or closing.

**Comment by AlexxIT** [comment]
I think it's better to use this https://www.home-assistant.io/integrations/cover.template/
And exclude this sonoff from Google.

**Comment by 8illy8o8** [comment]
Yes that is a great tip. I wasn't aware there was such a thing. Looks like that should be exactly what I need.

I looked at the name change you suggested but that is just the displayed name. My problem is that lots of devices caledd switch.sonoff1000xxxxx in the YAML code is confusing. I wish I could manually define switch.sonoff_kitchenlight so the YAML code is easier to read. I am happy to manually define it from the deviceID

**Comment by AlexxIT** [comment]
You can safely change Display Name and/or Entity ID from GUI info window.

**Comment by 8illy8o8** [comment]
Thanks AlexxIT, I guess I should have found that myself. Great work on the Sonoff integration. It is all much appreciated. Almost all working beautifully now.
