### ISSUE TITLE
iFan04 shows Speed as High for both 67% & 100%

### ISSUE THREAD

**Issue by astrovern64** [AlexxIT/SonoffLAN#780]
When an iFan04 is running at Medium speed, the entity settings show:
Percentage: 67
Speed: high

and when running at High speed:
Percentage: 100
Speed: high

Attached snapshots for 0%, 33%, 67% & 100%

![Screenshot 2022-04-27 at 17 37 48](https://user-images.githubusercontent.com/101368551/165760306-48344669-a13a-4d09-a3d1-cfed833c0478.png)
![Screenshot 2022-04-27 at 17 37 58](https://user-images.githubusercontent.com/101368551/165760310-6123c077-8c88-407e-987b-d8a496716586.png)
![Screenshot 2022-04-27 at 17 38 06](https://user-images.githubusercontent.com/101368551/165760312-4eb13999-30b0-4404-ad94-5b9260cf717b.png)
![Screenshot 2022-04-27 at 17 38 19](https://user-images.githubusercontent.com/101368551/165760314-96169606-433e-43f3-886e-bb813ccae943.png)

**Comment by AlexxIT** [comment]
What Integration version do you using?

**Comment by AlexxIT** [comment]
Fixed in latest master-version
