### ISSUE TITLE
Set initial states of sonoffs on every boot. ¿It's ok?

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#781]
Hi
I am testing v3.0.4rc
I am noticing that, in addition to missing the "local" and "cloud" attributes already reported in #770 and that in my case, I used them a lot to check for possible outages in my Wi-Fi network and now I have many binary automations/sensors, etc. without use, **in each reboot of my Rpi3+ the values of each sonoff equipment are set.**
In the previous version this did not happen.
The issue is that I have some automations that check the status and they are being fired unjustifiably for this reason.
I can modify everything, but I would like to know if it is okay to save the initial value in the history after each boot or this may have been something new, done like this for something else, or it is directly an error and can be eliminated in future releases.
Thank you
Regards

![ha boot](https://user-images.githubusercontent.com/65413059/165840466-2bab2beb-c54b-40c1-bc6b-8669acac4e7c.jpg)

**Comment by Gferretta** [comment]
Another "strange" thing that I just realized .... last night there was a general power outage, all the devices were turned off (obviously) except the HA that I have with a UPS.
The strange thing is that in the history of all the devices I don't see the "unavailable" for the shutdown and then the "on" at the time of going online.
In v2.4.7 in these cases it was reflected in the history of the device.
I hope it helps to determine what may be happening in these 2 cases that I mention (state on reboots).
Regards

**Comment by AlexxIT** [comment]
Unavailable for LAN fixed in latest master

**Comment by Idneus** [comment]
Hi @AlexxIT 

First I would like to congratulate you for the integration, know that my questions and arguments here are just to try to understand how it works, they are not critical.

AlexxIT, in the last update when you extended the timeout for cloud login, it solved the problem almost 100%. Alex, this situation is uncomfortable for those who use sonoff devices as a trigger for automations, see, the unavailability by itself does not cause damage, as it only lasts for seconds, but when returning the device launches a new event, as if the change was happening in that At the moment, if the sensor is off, it returns creating an off event, all automations that are waiting for the payload off of this device are started.

Friend, I have 3 suggestions, I promise I won't touch the subject again.

1st Provide more time limit for login, or even allow the user to set the time limit according to their region or situation.

2nd Even if the login has not been successful, do not change the status of the device, keeping it with the same position it was when connected to the cloud.

3rd Or, if possible, create an event for the return to availability, which is not on or off, for example from “unavailable” to “Available”.

Thank you very much in advance.

**Comment by AlexxIT** [comment]
@Idneus you need to ignore unavailable state in your automations

**Comment by AlexxIT** [comment]
Initial state fixed in latest master version
