### ISSUE TITLE
User interface integration

### ISSUE THREAD

**Issue by LeandroIssa** [AlexxIT/SonoffLAN#784]
I believe that many have already noticed that the Home Assistant team has been working to put in the UI several integrations that it was mandatory to add code in the configuration.yaml. I would like to know if this is possible to be done with SonoffLan.
I believe it would be easier for new users in Home Assistant. I believe the less we need to use configuration.yaml the better for everyone.

**Comment by AlexxIT** [comment]
Duplicate #778
