### ISSUE TITLE
V3.0 ignores "default_class: light" config option

### ISSUE THREAD

**Issue by WildRat** [AlexxIT/SonoffLAN#787]
V3.0 ignores "default_class: light" config option

**Comment by ALERTua** [comment]
I second this.
Maybe this is because of the migration of settings to the UI. Anyway, even the UI must have this selection.
Thank you.

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.0.1
