### ISSUE TITLE
Do RF devices work (with RF bridge) when internet is offline?

### ISSUE THREAD

**Issue by ZainAjam** [AlexxIT/SonoffLAN#789]
Is it possible to trigger RF alarms through RF bridge when internet is offline? I assumed it would be possible, but I cannot get it to work when my internet is offline.

**Comment by AlexxIT** [comment]
Yes. RF Bridge works without Internet. But some users have troubles with it
https://github.com/AlexxIT/SonoffLAN/issues/299

**Comment by ZainAjam** [comment]
I have a Google WiFi mesh system which my 4 sonoff RF bridges connect to over wi-fi. I then have sonoff RF remote controls paired as alarms in the RF bridges to control lights and aircon settings through home assistant automations. When the internet is down, the RF bridges blue light flickers indicating no internet access and then the RF remote controls don't work either. Any thoughts on how to handle this? It is frustrating to have my remote controls disabled when internet goes down
