### ISSUE TITLE
Not Temperature attribute in termostat control In 3.0 

### ISSUE THREAD

**Issue by enigmaspb** [AlexxIT/SonoffLAN#790]
Update to version 3.0 - all other work great 
And in termostat not show temperature 
Device GTTA127 AltoBeam https://aliexpress.ru/item/1005001836346668.html

In old version i use in HA 

  - type: attribute
    entity: switch.sonoff_100120d49e
    attribute: temperature
    unit: с
    suffix: c

**Comment by AlexxIT** [comment]
You need to provide debug logs
https://github.com/AlexxIT/SonoffLAN#debug-page

**Comment by AlexxIT** [comment]
Fixed in latest master-version
