### ISSUE TITLE
RF Bridge updating wrong sensor status

### ISSUE THREAD

**Issue by ammaralfarsi** [AlexxIT/SonoffLAN#796]
i have a RF bridge and connected 3 devices : 

1. Smoke Alarm Sensor RF
2. Door Sensor RF
3. Motion Sensor RF

The problem is the motion sensor updates the status of Door sensor!

am using the latest version of SonoffLan. v3.01

please let me know what further details you require

**Comment by AlexxIT** [comment]
You need to collect debug-logs
https://github.com/AlexxIT/SonoffLAN#debug-page

**Comment by ammaralfarsi** [comment]
it worked fine now. door sensor was paired as motion sensor as i was moving when i paired the sensor and it looks like it deducts the motion signal rather than the door sensor signal.

appreciate your continues development and support
