### ISSUE TITLE
DW2-Wi-Fi unavailable until triggered

### ISSUE THREAD

**Issue by TTLucian** [AlexxIT/SonoffLAN#799]
All DW2-Wi-Fi are unavailable after HA reboot. They come online only after the sensors are triggered once or after some time (30 mins to 1 hour maybe).
They work fine in both eWeLink app and eWeLink addon (all online).
Addon version v3.0.1.
HA version 2022.4.7

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/232

**Comment by AlexxIT** [comment]
Online status disabled for this device (it's don't work)
