### ISSUE TITLE
Feedback for your ADD ON

### ISSUE THREAD

**Issue by alesoft73** [AlexxIT/SonoffLAN#8]
For your information, the addon work with:

5 V 12 V Sonoff WiFi Smart Switch Wireless  
Sonoff S55

Many thanks for your work!

**Comment by AlexxIT** [comment]
@alesoft73 could you send link to "5 V 12 V Sonoff"?

**Comment by RDoull** [comment]
This works well with the  [T4eu1c](https://m.banggood.com/SONOFF-T4EU1C-WIFI-Wall-Touch-Switch-1-Gang-EU-No-Neutral-Wire-Required-Switches-Smart-Single-Wire-Wall-Switch-Works-With-Alexa-Google-Home-p-1555204.html?utm_source=google&utm_medium=cpc_ods&utm_content=arvin&utm_campaign=arvin-bw-sds-bw-all-content-m&ad_id=372637999674&gclid=CjwKCAiAhJTyBRAvEiwAln2qBysxYCDaOa58mQs5ba6qOjCLeLF_cEgYJ_btjTWXwmkMfUibRUXVGBoCFAAQAvD_BwE)Wall switch. Great work!

Is it possible to add the ability to control the brightness of the led back-light?

Great work though.. Keep it up 😁👍

**Comment by alesoft73** [comment]
> 
> 
> @alesoft73 could you send link to "5 V 12 V Sonoff"?
Sure,
https://it.aliexpress.com/item/32818293817.html?spm=a2g0s.9042311.0.0.27424c4dH3GFvS

**Comment by AlexxIT** [comment]
@RDoull led back-light it is Sonoff L1?

**Comment by alesoft73** [comment]
> 
> 
> @RDoull led back-light it is Sonoff L1?

Excuseme,
if i would you send a beer for ypur work ?? ;)
Bye Sir.

**Comment by AlexxIT** [comment]
@alesoft73 There is a donation button at the beginning of the readme 😄

**Comment by alesoft73** [comment]
> 
> 
> @alesoft73 There is a donation button at the beginning of the readme 😄

Do you have a paypal link for donation ? 
Thanks!

**Comment by AlexxIT** [comment]
@alesoft73 sorry, paypal donation does not work in my country 😢

**Comment by AlexxIT** [comment]
@alesoft73 I hope this should work :)
https://www.buymeacoffee.com/AlexxIT

**Comment by alesoft73** [comment]
> 
> 
> @alesoft73 I hope this should work :)
> https://www.buymeacoffee.com/AlexxIT

I send you a present ;) superman@m*******.it  💃

**Comment by AlexxIT** [comment]
@alesoft73 Thank you!
