### ISSUE TITLE
Network indicator Led

### ISSUE THREAD

**Issue by wokkeltje13** [AlexxIT/SonoffLAN#800]
Is it possible the new 3.x version has impact in the network indicator led even if the switch is (by default) disabled in HA? After the upgrade I noticed that some Sonoff devices had their network indicator led back on, I switched them off in the eWelink app and this morning, some were back on.

Tnx (version 3 looks great by the way)

**Comment by Gioway** [comment]
Same here!

**Comment by AlexxIT** [comment]
Duplicate #795
