### ISSUE TITLE
Sonoff devices not working from the dashboard since the last update

### ISSUE THREAD

**Issue by omaramin-2000** [AlexxIT/SonoffLAN#802]
Cannot control devices via HA dashboard, the toggle buttons work but the devices can't be controlled.

**Comment by AlexxIT** [comment]
You need to provide more useful info

**Comment by mdanilohome** [comment]
I made the last published Sonoff Lan update and the devices that worked normally stopped working. They are unavailable!

**Comment by nbexiga** [comment]
Hello.
Good afternoon.
I started with the same issue.
Allsonoff stopped working. :(

Kindly see below
This error originated from a custom integration.

Logger: custom_components.sonoff.core.entity
Source: custom_components/sonoff/cover.py:44
Integration: Sonoff (documentation, issues)
First occurred: 7:09:38 PM (15 occurrences)
Last logged: 7:16:51 PM

Can't init device: {'name': 'Estore Quarto', 'deviceid': '1000de105c', 'apikey': '64b3ea2e-3c9c-45e5-a613-26e9706a62cb', 'extra': {'uiid': 11, 'description': '20200317004', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:01:bc:1e:09', 'mac': 'd0:27:01:bc:1e:08', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00CEF211', 'staMac': 'C8:2B:96:CE:F2:11'}, 'brandName': 'KingArt', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5ee80f28a8645d00082c9d69', 'index': -14, 'members': [], 'roomid': '5ee894e4e58c420007d868c1'}, 'shareTo': [], 'devicekey': '43713608-d3b3-49a1-8489-a57454360967', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'sledOnline': 'off', 'ssid': 'JHACloudDevices', 'bssid': 'f4:92:bf:24:db:30', 'rssi': -71, 'fwVersion': '3.4.2', 'staMac': 'C8:2B:96:CE:F2:11', 'switch': 'pause', 'setclose': 18}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Can't init device: {'name': 'Estore Esquerdo Sala', 'deviceid': '1000de1d9a', 'apikey': '64b3ea2e-3c9c-45e5-a613-26e9706a62cb', 'extra': {'uiid': 11, 'description': '20200317004', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:01:bc:38:85', 'mac': 'd0:27:01:bc:38:84', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00CEF0A2', 'staMac': 'C8:2B:96:CE:F0:A2'}, 'brandName': 'KingArt', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5ee80f28a8645d00082c9d69', 'index': -13, 'members': [], 'roomid': '5ee894ebe58c420007d868c8'}, 'shareTo': [], 'devicekey': '803197e1-2b92-45ed-9932-83438dd92b17', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'sledOnline': 'off', 'ssid': 'JHACloudDevices', 'bssid': '98:da:c4:73:b5:69', 'rssi': -65, 'fwVersion': '3.4.2', 'staMac': 'C8:2B:96:CE:F0:A2', 'switch': 'pause', 'setclose': 57}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Can't init device: {'name': 'Estore Direito Sala', 'deviceid': '1000de1047', 'apikey': '64b3ea2e-3c9c-45e5-a613-26e9706a62cb', 'extra': {'uiid': 11, 'description': '20200317004', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:01:bc:1d:df', 'mac': 'd0:27:01:bc:1d:de', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00CEF298', 'staMac': 'C8:2B:96:CE:F2:98'}, 'brandName': 'KingArt', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5ee80f28a8645d00082c9d69', 'index': -12, 'members': [], 'roomid': '5ee894ebe58c420007d868c8'}, 'shareTo': [], 'devicekey': '5b636664-232f-4f34-bf96-84664a579a4d', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'sledOnline': 'off', 'ssid': 'JHACloudDevices', 'bssid': '98:da:c4:73:b5:69', 'rssi': -71, 'fwVersion': '3.4.2', 'staMac': 'C8:2B:96:CE:F2:98', 'switch': 'pause', 'setclose': 24}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Can't init device: {'name': 'Estore Escritório', 'deviceid': '1000de19f6', 'apikey': '64b3ea2e-3c9c-45e5-a613-26e9706a62cb', 'extra': {'uiid': 11, 'description': '20200317004', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:01:bc:31:3d', 'mac': 'd0:27:01:bc:31:3c', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00CEF32B', 'staMac': 'C8:2B:96:CE:F3:2B'}, 'brandName': 'KingArt', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5ee80f28a8645d00082c9d69', 'index': -11, 'members': [], 'roomid': '5ef4fe8831703900072b9da3'}, 'shareTo': [], 'devicekey': '59a4c8a7-0f84-46f1-b019-1d8f09c01d68', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'sledOnline': 'off', 'ssid': 'JHACloudDevices', 'bssid': 'f4:92:bf:24:db:30', 'rssi': -59, 'fwVersion': '3.4.2', 'staMac': 'C8:2B:96:CE:F3:2B', 'switch': 'pause', 'setclose': 76}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Can't init device: {'name': 'Estore Cozinha', 'deviceid': '1000de1035', 'apikey': '64b3ea2e-3c9c-45e5-a613-26e9706a62cb', 'extra': {'uiid': 11, 'description': '20200317004', 'brandId': '59ba53ad86b3ab5e3ae68596', 'apmac': 'd0:27:01:bc:1d:bb', 'mac': 'd0:27:01:bc:1d:ba', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00CEF310', 'staMac': 'C8:2B:96:CE:F3:10'}, 'brandName': 'KingArt', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5ee80f28a8645d00082c9d69', 'index': -10, 'members': [], 'roomid': '5ee894d5e58c420007d868bc'}, 'shareTo': [], 'devicekey': 'dfd47567-93c1-433e-a343-33fd6d711c99', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'sledOnline': 'on', 'ssid': 'JHACloudDevices', 'bssid': 'f4:92:bf:24:db:30', 'rssi': -88, 'fwVersion': '3.4.2', 'staMac': 'C8:2B:96:CE:F3:10', 'switch': 'pause', 'setclose': 9}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__
    self.internal_update(params)
  File "/config/custom_components/sonoff/core/entity.py", line 100, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/cover.py", line 44, in set_state
    self._attr_is_closing = pos < self._attr_current_cover_position
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by nbexiga** [comment]
I am using 2022.4.7

**Comment by nbexiga** [comment]
Hello.
Good afternoon.
I started with the same issue.
Allsonoff stopped working. :(

An example of one device:
Can't init device: {'name': 'Estore Quarto', 'deviceid': '1000de105c', 'apikey': '64b3ea2e-3c9c-45e5-a613-26e9706a62cb', 'extra': {'uiid': 11, 'description': '20200317004', 'brandId': '59ba53ad86b3ab5e3ae68596',  'mac': 'd0:27:01:bc:1e:08', 'ui': '电动窗帘', 'modelInfo': '5b83d2114a6b22f51544b4d5', 'model': 'PSF-BTA-GL', 'manufacturer': '深圳市彪王科技有限公司', 'chipid': '00CEF211', 'staMac': 'C8:2B:96:CE:F2:11'}, 'brandName': 'KingArt', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/w9sMg5WxAWp0o9OBeqyH0rcOJKEVKaKi.png', 'showBrand': True, 'productModel': 'KING-Q4', 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5ee80f28a8645d00082c9d69', 'index': -14, 'members': [], 'roomid': '}, 'shareTo': [], 'devicekey': '43713608-d3b3-49a1-8489-a57454360967', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'sledOnline': 'off', 'ssid': 'xxx' 'bssid': 'xxxx', 'rssi': -71, 'fwVersion': '3.4.3', 'staMac': 'C8:2B:96:CE:F2:11', 'switch': 'pause', 'setclose': 18, 'only_device': {'ota': 'success'}}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'deviceFeature': {}}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__
    self.internal_update(params)
  File "/config/custom_components/sonoff/core/entity.py", line 100, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/cover.py", line 44, in set_state
    self._attr_is_closing = pos < self._attr_current_cover_position
TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by mdanilohome** [comment]
To normalize, I had to restore a HA backup to the latest version prior to the Sonoff Lan update. Now it's working but developers need to check, and fix what's causing the integration to fail.

**Comment by vitali84** [comment]
can confirm @nbexiga same error for kingart shutters module.
Plus all my SNZB-01 zigbee buttons appear offline

**Comment by nbexiga** [comment]
Hi
Thanks for the update.
Yes..
I also have a garage door sensor , that is showing same info.
Can't be recognized in HA.
But to restore from previous HA version its not so easy for me.
Maybe wait for a next release to fix this?
It depends of the time of the fix..
If not I will have to revert the last HA update that I have.
Any more comments on this?

**Comment by nbexiga** [comment]
Hello.
I had to restore to the last HA backup, now it's working fine.
I have reconfigured some things that I did not have until last backup. 
But definitely something with the latest Sonoff Lan update.
When possible please advise on this and o  the working update when you did it.
Thank you for all the efforts until now ❤️ 
Thank you @AlexxIT !

**Comment by AlexxIT** [comment]
Duplicate #792 
Fixed in latest master version

**Comment by omaramin-2000** [comment]
The issue still exists, I have my iFan device not working!

**Comment by AlexxIT** [comment]
@omaramin-2000 So. Another duplicate #786
