### ISSUE TITLE
S26 devices greyed out since 3.0.0-3.0.2

### ISSUE THREAD

**Issue by sgbossinga** [AlexxIT/SonoffLAN#804]
My S26 outlets are not working in 3.0.0-3.0.2. I reverted back to 2.4.7.
I saw an earlier post about this marked as bug but I cannot find it anymore.

**Comment by AlexxIT** [comment]
You need to provide debug logs

**Comment by sgbossinga** [comment]
> You need to provide debug logs

how?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#debug-page

**Comment by sgbossinga** [comment]
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.sonoff.sonoff_cloud
Source: custom_components/sonoff/sonoff_cloud.py:289
Integration: Sonoff (documentation, issues)
First occurred: 10:52:33 (1 occurrences)
Last logged: 10:52:33

Login error: {'error': 401, 'msg': 'pwd err'}

Logger: async_upnp_client.aiohttp
Source: /usr/local/lib/python3.9/site-packages/async_upnp_client/aiohttp.py:247
First occurred: 10:52:32 (2 occurrences)
Last logged: 10:54:28

Failed to create HTTP server at fe80::6c98:585a:efca:6b20:0: [Errno 22] error while attempting to bind on address ('fe80::6c98:585a:efca:6b20', 0, 0, 0): invalid argument

**Comment by AlexxIT** [comment]
Your ewelink password wrong

**Comment by sgbossinga** [comment]
> Your ewelink password wrong

how can that be
I am now on 2.4.7 and it works fine

**Comment by AlexxIT** [comment]
Delete `.sonoff.json` from config folder and it will be broken too

**Comment by sgbossinga** [comment]
can I change the password in HACS/integration somewhere?

**Comment by sgbossinga** [comment]
> Search it on integration page

sorry I don't understand what/where

**Comment by sgbossinga** [comment]
thanks AlexxIT, it works
