### ISSUE TITLE
RF Bridge general On/Off control doesn't work after v.3 update

### ISSUE THREAD

**Issue by alexodn** [AlexxIT/SonoffLAN#806]
Service remote/turn_on and remote/turn_off fails
![Screenshot 2022-05-03 130742](https://user-images.githubusercontent.com/67309148/166436790-f0f72ff9-6362-4e47-9624-b0c2c327a1e0.png)

**Comment by AlexxIT** [comment]
Do you used it? I thought it's useless

**Comment by alexodn** [comment]
Yes I do. 
I need alarm system armed (disarmed) with this control.

**Comment by AlexxIT** [comment]
What is alarm system? Never used it.

**Comment by alexodn** [comment]
Not alarm system per se but RF door and move sensors need to be muted (disarmed) all at once with RF Bridge control

**Comment by AlexxIT** [comment]
Is it some button in ewelink app for that?

**Comment by alexodn** [comment]
No. There is no such a button in ewelink. It's a perk of HA I love it for.

**Comment by AlexxIT** [comment]
It works in integration v2?

**Comment by alexodn** [comment]
Yes it worked perfectly until v3 arrived

**Comment by AlexxIT** [comment]
Oh. Entity just stops to receive events. I didn't know what anyone used this.

**Comment by pieterhill** [comment]
Not sure if it is related - the status of the RF bridge is also no longer available. I use this to monitor health/power state of the bridge.

**Comment by AlexxIT** [comment]
Fixed in latest master version. Will be in next release
