### ISSUE TITLE
Dual state RF door sensors problem

### ISSUE THREAD

**Issue by camui-alexandru** [AlexxIT/SonoffLAN#807]
After V3 update, the Rf Bridge - door sensors does not work anymore. It used to work  as they have 2 states - open/close. So i used the old payload off function. Now i only see 2 entities as button (door_open / door_closed).

**Comment by AlexxIT** [comment]
Show your yaml config

**Comment by camui-alexandru** [comment]
sonoff:
  username: xxxxxxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxxx
  force_update: [temperature, humidity]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  mode: cloud
  reload: always
  rfbridge:
    living_d:  # button name in eWeLink application (open signal)
      name: Usa Living  # optional, you can change sensor name
      device_class: door # e.g. door, window
      timeout: 0  # disable auto close timeout
      payload_off: living_i  # button name in eWeLink application (close signal)

**Comment by AlexxIT** [comment]
Oh. In new version it works only if you setup turn on signal in ewelink app as sensor, not as button :(

**Comment by camui-alexandru** [comment]
I don't understand. How can i do that ? In ewelink, on rf bridge, when i press Add, i have: 1 button, 2, 3, 4 button, Curtain and Alarm. What shoud I do ?

**Comment by AlexxIT** [comment]
alarm

**Comment by Kejszijo** [comment]
Hi,

In my case in the eWelink APP the alarm option doesn't have dual state, only single.

**Comment by AlexxIT** [comment]
The button also has no dual state...

**Comment by camui-alexandru** [comment]
So, in that case, we can't use dual sensors anymore.

**Comment by thayerfox** [comment]
So you are stating we have to add an alarm device for the open state and another for the closed, instead of using a two button device as before.

This really sucks, as the bridge only allows 16 devices.  Before if I had 16 two button remotes, I now need 32 alarms, and would need a new hub.

**Comment by thayerfox** [comment]
I have never tried the four buttons, but I currently have 24 dual state sensors configured as 24 two button remotes, across two rf bridges.  (So 48 buttons.) This had been working up until the update.

**Comment by AlexxIT** [comment]
Latest master-version has new features:
- Adds (restore) support buttons as sensors
- Sync RFBridge childs available with bridge
- Adds restore function to RFBridge sensors

**Comment by AlexxIT** [comment]
Also updated docs. All changes will be in next release
https://github.com/AlexxIT/SonoffLAN#sonoff-rf-bridge-433

**Comment by thayerfox** [comment]
Thank you!
