### ISSUE TITLE
Door sensor DW2 has no battery level

### ISSUE THREAD

**Issue by Ih8rain2** [AlexxIT/SonoffLAN#808]
The DW2 door sensor used to have a battery level in Volts. This seems to have disappeared. I converted it to % level as I have with some of the other sensors. The attribute is gone and it would be nice to have it back.

**Comment by AlexxIT** [comment]
Do you have formula?

**Comment by rcarnevalli** [comment]
Hi,
As the way as I saw in HASS, there is no formula. The voltage is the value presented, about 3 Vdc (2 batteries of 1,5 Vdc). It is very usefull for see the batteries consumption (indeed, very high!). I don't know how, but, if possible, the correction will be only correct the units, from % to Vdc. Thanks!

**Comment by AlexxIT** [comment]
Reworked in master version. Will be in next release

**Comment by rcarnevalli** [comment]
Ops, good news! Thanks a lot!

**Comment by TTLucian** [comment]
They appear as sensors. Shouldn't they be shown in the diagnostic category? ![Screenshot_2022-05-05-22-28-57-53_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/1855276/167011271-71611b39-033d-46b6-b5a4-044e5f0ea796.jpg)

**Comment by hiagocosta** [comment]
my DW2 sensor is recognized as a relay now.... How can I turn it back on door sensor?
![image](https://user-images.githubusercontent.com/22087481/186989898-df865ed9-8740-4569-9968-51bfae25fb34.png)

**Comment by AlexxIT** [comment]
@hiagocosta show device diagnostics

**Comment by hiagocosta** [comment]
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.8.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Sao_Paulo",
    "os_name": "Linux",
    "os_version": "5.15.60",
    "supervisor": "2022.08.5",
    "host_os": "Home Assistant OS 8.5",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "yi_hack": {
      "version": "0.3.9",
      "requirements": []
    },
    "localtuya": {
      "version": "4.0.2",
      "requirements": []
    },
    "dwains_dashboard": {
      "version": "3.2.0",
      "requirements": []
    },
    "favicon": {
      "version": "10.4",
      "requirements": []
    },
    "mikrotik_router": {
      "version": "0.0.0",
      "requirements": [
        "librouteros>=3.2.0",
        "mac-vendor-lookup>=0.1.12"
      ]
    },
    "nodered": {
      "version": "1.0.9",
      "requirements": []
    },
    "sonoff": {
      "version": "3.2.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hass_agent_notifier": {
      "version": "2022.3.15",
      "requirements": []
    },
    "ble_monitor": {
      "version": "10.0.0",
      "requirements": [
        "pycryptodomex>=3.14.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.13",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "alexa_media": {
      "version": "4.1.0",
      "requirements": [
        "alexapy==1.26.1",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.1.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "3871c0b",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": true,
      "homes": 1
    },
    "errors": [],
    "device": {
      "uiid": 154,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "init": 1,
        "fwVersion": "1000.2.1130",
        "mac": "***",
        "chipid": "2",
        "type": 4,
        "switch": "off",
        "rssi": -63,
        "battery": 25,
        "defense": 0,
        "actionTime": 1661998237000,
        "pulse": "off",
        "sledOnline": "off"
      },
      "model": "DW2-Wi-Fi-L",
      "online": true,
      "localtype": null,
      "deviceid": "10016c7745"
    }
  }
}`

**Comment by hiagocosta** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.8.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Sao_Paulo",
    "os_name": "Linux",
    "os_version": "5.15.60",
    "supervisor": "2022.08.5",
    "host_os": "Home Assistant OS 8.5",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "yi_hack": {
      "version": "0.3.9",
      "requirements": []
    },
    "localtuya": {
      "version": "4.0.2",
      "requirements": []
    },
    "dwains_dashboard": {
      "version": "3.2.0",
      "requirements": []
    },
    "favicon": {
      "version": "10.4",
      "requirements": []
    },
    "mikrotik_router": {
      "version": "0.0.0",
      "requirements": [
        "librouteros>=3.2.0",
        "mac-vendor-lookup>=0.1.12"
      ]
    },
    "nodered": {
      "version": "1.0.9",
      "requirements": []
    },
    "sonoff": {
      "version": "3.2.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hass_agent_notifier": {
      "version": "2022.3.15",
      "requirements": []
    },
    "ble_monitor": {
      "version": "10.0.0",
      "requirements": [
        "pycryptodomex>=3.14.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.13",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "alexa_media": {
      "version": "4.1.0",
      "requirements": [
        "alexapy==1.26.1",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.1.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "3871c0b",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": true,
      "homes": 1
    },
    "errors": [],
    "device": {
      "uiid": 154,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "init": 1,
        "fwVersion": "1000.2.1130",
        "mac": "***",
        "chipid": "2",
        "type": 4,
        "switch": "off",
        "rssi": -63,
        "battery": 25,
        "defense": 0,
        "actionTime": 1661998237000,
        "pulse": "off",
        "sledOnline": "off"
      },
      "model": "DW2-Wi-Fi-L",
      "online": true,
      "localtype": null,
      "deviceid": "10016c7745"
    }
  }
}

**Comment by AlexxIT** [comment]
Check latests master version

**Comment by hiagocosta** [comment]
still the same

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.8.7",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Sao_Paulo",
    "os_name": "Linux",
    "os_version": "5.15.60",
    "supervisor": "2022.08.5",
    "host_os": "Home Assistant OS 8.5",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "yi_hack": {
      "version": "0.3.9",
      "requirements": []
    },
    "localtuya": {
      "version": "4.0.2",
      "requirements": []
    },
    "dwains_dashboard": {
      "version": "3.2.0",
      "requirements": []
    },
    "favicon": {
      "version": "10.4",
      "requirements": []
    },
    "mikrotik_router": {
      "version": "0.0.0",
      "requirements": [
        "librouteros>=3.2.0",
        "mac-vendor-lookup>=0.1.12"
      ]
    },
    "nodered": {
      "version": "1.0.9",
      "requirements": []
    },
    "sonoff": {
      "version": "3.2.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "hass_agent_notifier": {
      "version": "2022.3.15",
      "requirements": []
    },
    "ble_monitor": {
      "version": "10.0.0",
      "requirements": [
        "pycryptodomex>=3.14.1",
        "janus>=1.0.0",
        "aioblescan>=0.2.13",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "alexa_media": {
      "version": "4.1.0",
      "requirements": [
        "alexapy==1.26.1",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "fullykiosk": {
      "version": "1.1.0",
      "requirements": [
        "python-fullykiosk==0.0.11"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "/api/sonoff/a904975b-53ee-4887-b3cf-d50c5c0a5b6a",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.2.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "38856d1",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": true,
      "homes": 1
    },
    "errors": [],
    "device": {
      "uiid": 154,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "init": 1,
        "fwVersion": "1000.2.1130",
        "mac": "***",
        "chipid": "2",
        "type": 4,
        "switch": "off",
        "rssi": -63,
        "battery": 25,
        "defense": 0,
        "actionTime": 1661998237000,
        "pulse": "off",
        "sledOnline": "off"
      },
      "model": "DW2-Wi-Fi-L",
      "online": true,
      "localtype": null,
      "deviceid": "10016c7745"
    }
  }
}

**Comment by AlexxIT** [comment]
Because you not using latest master version.

**Comment by hiagocosta** [comment]
i'm using the latest (today) 3.2.0 version, is this the latest version already?

**Comment by AlexxIT** [comment]
This is not a master version.

**Comment by yusrimathews** [comment]
Actually using the master version works - specifically (re)download the “master” branch.

@AlexxIT what’s the advised approach to get the battery as %? Should I create a template sensor with a formula based on battery voltage, or is this something to be included in a future release?

**Comment by AlexxIT** [comment]
@yusrimathews I don't have the formula.

@hiagocosta seems your sensor sends another battery value then original DW2. What info shows ewelink app about your battery level?

**Comment by hiagocosta** [comment]
after download the master version (last option on HACS version's list) it worked perfectly, but It shows 0 to 100 voltage info.

I guess that percentage numbers, isn't it?

**Comment by yusrimathews** [comment]
@hiagocosta that would make sense - in the eWeLink app I see "High" and in Hass it shows 47 volts, with your logic that is 47% instead of volts? I thought I needed to use that value to calculate battery %.

**Comment by hiagocosta** [comment]
yeah, I guess that integration brings battery level in percentages, we only need to convert from volts.
I'm using rechargeable batteries, and I think that will not start with 100%, beacause these kind of batteries is not 1.5V

**Comment by yusrimathews** [comment]
In case this helps anyone, I am customising the sensor as follows:

1. Include `customize.yaml` in `configuration.yaml`:
```
homeassistant:
  customize: !include customize.yaml
```
2. Customise the sensor in `customize.yaml`:
```
sensor.your_sensor_id:
  unit_of_measurement: '%'
  device_class: battery
```
and replace `sensor.your_sensor_id` with your sensor entity id.
