### ISSUE TITLE
Sonoff integration: problem with climate entity

### ISSUE THREAD

**Issue by zanna1972** [AlexxIT/SonoffLAN#812]
Hi, I have just installed the last version of the Sonoff integration in my Home Assistant.
Now my NSPANEL is shown as a climate, two switches and an outdoor temperature sensor.
There isn't an indoor temperature sensor...
![image](https://user-images.githubusercontent.com/92396381/166475300-42234926-b3b1-40e5-abd8-f78c81d09fde.png)

I added the climate control in my dashboard but it doesn't work.
Probably the problem is that the current temperature attribute isn't detected as you can see in the following screenshot of my device:
![image](https://user-images.githubusercontent.com/92396381/166475102-ae7d65db-6d92-4b71-aa41-9e9aefd8d8a0.png)
The current temperature is null.

I have other climate in my home and these are the attributes:
![image](https://user-images.githubusercontent.com/92396381/166475828-02c0d0c0-cd6c-4ef2-aaae-f1cb344143ba.png)
Also min_temp and max_temp are different, 16-31 in NSPanel versus 7-35 in my climate. It should be great if these values are the same.
Thanks for your help

**Comment by AlexxIT** [comment]
Install latest master version and get integration diagnostics (Hass v2022.2 and more):

Configuration > Integrations > Sonoff > 3 dots > Download diagnostics

**Comment by ianfretwell** [comment]
The thermostat temp IS the indoor temperature now isn't it?   I thought that was why the other 'indoor' temperature had been removed ?

**Comment by AlexxIT** [comment]
`current_temperature: 21`

**Comment by zanna1972** [comment]
This is the screenshot of the thermostat in my HA dashboard:
![image](https://user-images.githubusercontent.com/92396381/166482877-97479b56-0bea-4448-b4b1-bdedf1c638a9.png)

As you can see there is the setpoint temperature (16°) there isn't the current temperature (show in the middle of the picture).
The status "Heat" is also not correct.

**Comment by ianfretwell** [comment]
Looks like this for me:-

![image](https://user-images.githubusercontent.com/52041704/166483838-a07681dc-e8da-4084-a399-09ffcc3b1518.png)

**Comment by zanna1972** [comment]
Hi ianfretwell, could you please upload the screenshot of the attributes of your NSPanel from the "Developer Tool" of Home Assistant?

**Comment by ianfretwell** [comment]
Here you go:-

![image](https://user-images.githubusercontent.com/52041704/166485109-46ea89de-254d-40f2-94bb-eb2ef624542d.png)

**Comment by zanna1972** [comment]
Not that, from the Developer tool. This kind of screenshot:
![image](https://user-images.githubusercontent.com/92396381/166485504-55d683dd-cbfa-49c8-b08f-2b8c4e395306.png)

This is my NSPanel and after restart I don't have current_temperature: null anymore...

**Comment by ianfretwell** [comment]
Exactly the same thing, I just had it selected at the top of the page instead:-

![image](https://user-images.githubusercontent.com/52041704/166486017-363c46a2-c976-4fb6-b749-862684026c85.png)

**Comment by AlexxIT** [comment]
HACS > SonoffLAN > Reinstall > master

**Comment by zanna1972** [comment]
I have removed and reinstalled SonoffLAN integration from HACS but nothing has changed.

**Comment by Vaioraner** [comment]
my TH 16 sensors also doesnt work with the new update :(

**Comment by ianfretwell** [comment]
@Vaioraner    Try disabling just the thermostat element of the TH16's - does everything else then appear fine?

**Comment by Vaioraner** [comment]
@ianfretwell in the ewelink app directly?

**Comment by ianfretwell** [comment]
@Vaioraner 

No, in HA circled in red here:-

![image](https://user-images.githubusercontent.com/52041704/166514475-cac8283f-961f-4dbc-88af-2065f0fe1b7f.png)

**Comment by Vaioraner** [comment]
hmm, no its disabled! crazy

**Comment by AlexxIT** [comment]
Well. Without diagnostics your problem won't be fixed

**Comment by zanna1972** [comment]
Please, give me the instructions to obtain diagnostics...

**Comment by zanna1972** [comment]
This error originated from a custom integration.

Logger: custom_components.sonoff.core.entity
Source: custom_components/sonoff/climate.py:163
Integration: Sonoff (documentation, issues)
First occurred: 6:56:56 PM (2 occurrences)
Last logged: 8:48:48 PM

Can't init device: {'name': 'NSPanel', 'deviceid': '100156adce', 'apikey': '647f9a26-a71f-4250-934c-e28e8f3d2c39', 'extra': {'uiid': 133, 'description': '20211109002', 'brandId': '5c4c1aee3a7d24c7100be054', 'apmac': 'd0:27:02:ad:58:ed', 'mac': 'd0:27:02:ad:58:ec', 'ui': 'HMI墙面开关', 'modelInfo': '5f73390defe12b0b619e66d5', 'model': 'E32-MSW-NX', 'manufacturer': '深圳松诺技术有限公司', 'chipid': '4417937DF820'}, 'brandName': 'SONOFF', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png', 'showBrand': True, 'productModel': 'NSPanel', 'tags': {'m_2c39_andr': 'on'}, 'devConfig': {'timerCount': '16/16'}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '622f0ea41f26e80009a4517b', 'index': 0, 'members': [], 'roomid': '622f0ea41f26e80009a45179'}, 'shareTo': [], 'devicekey': '0672011f-a698-4475-84f1-a1a51b47e55a', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}], 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}], 'configure': [{'startup': 'stay', 'outlet': 0}, {'startup': 'stay', 'outlet': 1}], 'lock': 0, 'fwVersion': '1.2.0', 'temperature': 19, 'humidity': 50, 'tempUnit': 0, 'HMI_outdoorTemp': {'current': 21, 'range': '13,21'}, 'HMI_weather': 7, 'cityId': '1549617', 'dst': 1, 'dstChange': '2022-10-30T01:00:00.000Z', 'geo': '44.459,10.969', 'timeZone': 1, 'only_device': {'ota': 'success', 'ota_fail_reason': 0}, 'HMI_ATCDevice': {'ctype': 'device', 'id': '100156adce', 'outlet': 1, 'etype': 'hot', 'precision': 1}, 'ctype': 'device', 'id': '100156adce', 'resourcetype': 'ATC', 'ATCEnable': 0, 'ATCMode': 0, 'ATCExpect0': 16, 'error': 0, 'HMI_dimEnable': 1, 'HMI_dimOpen': 1}, 'isSupportGroup': True, 'isSupportedOnMP': False, 'deviceFeature': {}}
Can't init device: {'name': 'Termostato cameretta', 'deviceid': '100156adce', 'apikey': '647f9a26-a71f-4250-934c-e28e8f3d2c39', 'extra': {'uiid': 133, 'description': '20211109002', 'brandId': '5c4c1aee3a7d24c7100be054', 'apmac': 'd0:27:02:ad:58:ed', 'mac': 'd0:27:02:ad:58:ec', 'ui': 'HMI墙面开关', 'modelInfo': '5f73390defe12b0b619e66d5', 'model': 'E32-MSW-NX', 'manufacturer': '深圳松诺技术有限公司', 'chipid': '4417937DF820'}, 'brandName': 'SONOFF', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png', 'showBrand': True, 'productModel': 'NSPanel', 'tags': {'m_2c39_andr': 'on', 'ck_channel_name': {'0': 'Inutilizzato', '1': 'Testina termostato'}}, 'devConfig': {'timerCount': '16/16'}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '622f0ea41f26e80009a4517b', 'index': 0, 'members': [], 'roomid': '622f0ea41f26e80009a45179'}, 'shareTo': [], 'devicekey': '0672011f-a698-4475-84f1-a1a51b47e55a', 'online': True, 'params': {'bindInfos': {}, 'version': 8, 'pulses': [{'pulse': 'off', 'width': 1000, 'outlet': 0}, {'pulse': 'off', 'width': 1000, 'outlet': 1}], 'switches': [{'switch': 'off', 'outlet': 0}, {'switch': 'off', 'outlet': 1}], 'configure': [{'startup': 'stay', 'outlet': 0}, {'startup': 'stay', 'outlet': 1}], 'lock': 0, 'fwVersion': '1.2.0', 'temperature': 20, 'humidity': 50, 'tempUnit': 0, 'HMI_outdoorTemp': {'current': 18, 'range': '13,20'}, 'HMI_weather': 6, 'cityId': '1549617', 'dst': 1, 'dstChange': '2022-10-30T01:00:00.000Z', 'geo': '44.459,10.969', 'timeZone': 1, 'only_device': {'ota': 'success', 'ota_fail_reason': 0}, 'HMI_ATCDevice': {'ctype': 'device', 'id': '100156adce', 'outlet': 1, 'etype': 'hot', 'precision': 1}, 'ctype': 'device', 'id': '100156adce', 'resourcetype': 'ATC', 'ATCEnable': 1, 'ATCMode': 0, 'ATCExpect0': 16, 'error': 0, 'HMI_dimEnable': 1, 'HMI_dimOpen': 1}, 'isSupportGroup': True, 'isSupportedOnMP': False, 'deviceFeature': {}}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/entity.py", line 82, in __init__
    self.internal_update(params)
  File "/config/custom_components/sonoff/core/entity.py", line 103, in internal_update
    self.set_state(params)
  File "/config/custom_components/sonoff/climate.py", line 163, in set_state
    cache["temperature"] + cache["tempCorrection"]
KeyError: 'tempCorrection'

**Comment by AlexxIT** [comment]
Fixed in latest master version. Will be in next release

**Comment by zanna1972** [comment]
Thank you AlexxIT. Just installed version 3.0.3. and the main problem is solved.
There is another small problem. here below the screenshot of two of my thermostats, both of them are actually in "Idle" status but the NSPANEL (in the right side of the screenshot) shows "Heat" instead of "Idle".
![image](https://user-images.githubusercontent.com/92396381/166654950-52dff005-c567-48e5-95eb-93d53febd239.png)
Here below the attributes I can see in the "Developer Tool" of Home Assistant:
![image](https://user-images.githubusercontent.com/92396381/166655063-d9b7c9c5-953c-4ab4-b7b1-310abb7ccaa9.png)
As you can see, the climate.termostato_cameretta (the NSPANL) dosen't have the attribute: hvac_action: idle
The other thermostat has this attribute. I suppose this could be the reason I see "Heat" instead of "Idle".
I think this attribute changes its value according to the status of the thermostat.
I have changed the setpoint of the thermostat (not the NSPANEL, the other) and the attribute changes to: heating
![image](https://user-images.githubusercontent.com/92396381/166655936-c54da6ab-a72c-4271-b8dc-44c729cb0267.png)
This mean that the attribute hvac_action is the current status of the thermostat.
Is it possible to add also this attribute to the NSPANEL?
Thanks

**Comment by AlexxIT** [comment]
Only if you show what param means action for NSPanel. You can see all params in your log above.

**Comment by zanna1972** [comment]
Sorry AlexxIT I don't understand your message. The parameter I refere to is hvac_action.

**Comment by StAR-ArMa** [comment]
Dear all,
new to HA... Added Sonoff LAN and among other devices I also see the NSPanel. But this only shows a Sensor (Temoerature) and no "Controls". hence I do not see the Thermostat and the respective "climate" entity. 
WHat do I do wrong? What other info you need to help? Thanks.
