### ISSUE TITLE
The 'unit' option near /config/sensors.yaml:103 is deprecated, please remove it from your configuration

### ISSUE THREAD

**Issue by edu24x** [AlexxIT/SonoffLAN#813]
Hi!!

From documentation:
![2022-05-04_7-53-50](https://user-images.githubusercontent.com/67578427/166629564-2da7c069-c2d2-437a-ac85-220a58608196.png)
![2022-05-04_7-55-53](https://user-images.githubusercontent.com/67578427/166629566-3bdeacc6-3e23-4d98-b569-35e3900a1cda.png)

**Comment by AlexxIT** [comment]
Thanks, fixed
