### ISSUE TITLE
 updating to home assistant core Version: core-2022.4.7 no devices available

### ISSUE THREAD

**Issue by d4rkdpg** [AlexxIT/SonoffLAN#816]
updating to home assistant core Version: core-2022.4.7 no devices available

all devices shows as orphaned devices. im on version 3.0.3 tried removing and other versions no joy.
Supervisor
Version
supervisor-2022.05.0
Newest Version
supervisor-2022.05.0

Core
Version
core-2022.4.7
Newest Version
core-2022.4.7

**Comment by d4rkdpg** [comment]
Thanks for that, I just restored back to  2022.2.2 core and everything is working - could you look at this maybe a bug with new core.

**Comment by AlexxIT** [comment]
For debugging, reading the documentation at the link above will help. All latest core include beta versions supported

**Comment by BrassDome** [comment]
OK Solved it - simple issue.  Just had to re-enter the entities on my dashboard using actual addresses.  Not sure why this happened.
What was  previously - entity: binary_sensor.pirgang and stopped working....
Is now - entity: binary_sensor.1000cdxxxxx_1

Thanks for an awesome integration!!! Works like a charm.
