### ISSUE TITLE
Basic and Basic2 switches unavailable after update to v3

### ISSUE THREAD

**Issue by roelof-47** [AlexxIT/SonoffLAN#817]
This is to reopen #809. The reported issue has not been solved.
[config_entry-sonoff-807f1440c52b59e2675ad6451304e34b.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8626875/config_entry-sonoff-807f1440c52b59e2675ad6451304e34b.json.txt)

After the update one of the error messages has been solved, but the following error message still exists.
I send you also the download of the diagnostics.

```
Logger: homeassistant
Source: custom_components/sonoff/core/ewelink/__init__.py:44
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 20:54:54 (1 occurrences)
Last logged: 20:54:54
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 201, in internal_normal_setup
    await internal_cache_setup(hass, entry, devices)
  File "/config/custom_components/sonoff/__init__.py", line 222, in internal_cache_setup
    registry.setup_devices(devices)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 44, in setup_devices
    _LOGGER.debug(f"{deviceid} UIID {uiid:04} | %s", device["params"])
KeyError: 'params'
```

**Comment by AlexxIT** [comment]
Have you installed master version? Check this code there
https://github.com/AlexxIT/SonoffLAN/blob/6741f9bdc3b3935f63fb6dddcceecb94c89d7efb/custom_components/sonoff/core/ewelink/__init__.py#L54

**Comment by roelof-47** [comment]
Checked line 54 after download master.
Line content is identical.

**Comment by AlexxIT** [comment]
So `_LOGGER.debug...` can't be on line 44. It's on line 45. You showing error from old version

**Comment by roelof-47** [comment]
I repeated the procedure: load master, download diagnostics...
This is the result:

Error message from logbook

Logger: homeassistant
Source: custom_components/sonoff/core/ewelink/__init__.py:44
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 11:30:46 (1 occurrences)
Last logged: 11:30:46
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 201, in internal_normal_setup
    await internal_cache_setup(hass, entry, devices)
  File "/config/custom_components/sonoff/__init__.py", line 222, in internal_cache_setup
    registry.setup_devices(devices)
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 44, in setup_devices
    _LOGGER.debug(f"{deviceid} UIID {uiid:04} | %s", device["params"])
KeyError: 'params'
[config_entry-sonoff-807f1440c52b59e2675ad6451304e34b.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8630086/config_entry-sonoff-807f1440c52b59e2675ad6451304e34b.json.txt)

**Comment by roelof-47** [comment]
To be complete: 
Of course, I restarted the system before creating the files

**Comment by roelof-47** [comment]
Surprise.
I did download the master version again this afternoon.
This message appear after restart. It includes the line 45

Logger: custom_components.sonoff.core.ewelink
Source: custom_components/sonoff/core/ewelink/__init__.py:45
Integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 16:29:25 (1 occurrences)
Last logged: 16:29:25
10007daa68 !! can't setup device

Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 45, in setup_devices
    _LOGGER.debug(f"{did} UIID {uiid:04} | %s", device["params"])
KeyError: 'params'

**Comment by roelof-47** [comment]
The switches are actif again. I think the problem is solved !!!
Thank you  Alex for your help and your actions.

**Comment by AlexxIT** [comment]
You will continue receive this warning because problem with device should be solved. But integration will continue work with other devices.
