### ISSUE TITLE
V3.0.3 dissapear from HACS after upgrade to 2022.5

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#818]
I has installed v3.0.3 and now only view 3.0.0 and Master, after HA upgrade to 2022 5
No way to re install 3.0.3

Now install Master versión 
🤷‍♂️

![Screenshot_20220505-003332_Home Assistant.jpg](https://user-images.githubusercontent.com/65413059/166860168-b943ef22-45b3-4ab5-b827-3143705d3b72.jpg)

**Comment by AlexxIT** [comment]
This is GitHub bug. It has been around for a few months and happens in different repositories of different projects
https://t.me/AlexxIT_SmartHome/642
