### ISSUE TITLE
RF Bridge On/Off control is always in On position after update 3.0.3

### ISSUE THREAD

**Issue by alexodn** [AlexxIT/SonoffLAN#819]
If slider moved Off it spontaneously returns to On position a second later

![Screenshot 2022-05-05 140943](https://user-images.githubusercontent.com/67309148/166913237-df0d84e9-3b36-47d7-9b30-c71af249c15b.png)
[sonoff-e9c6a82d4abde0901e607d9e3268bf70-Alarm&Wicket-b9d079c8b024fcda07f8395928abdbb2.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8630718/sonoff-e9c6a82d4abde0901e607d9e3268bf70-Alarm.Wicket-b9d079c8b024fcda07f8395928abdbb2.json.txt)

**Comment by AlexxIT** [comment]
Fixed in latest version
