### ISSUE TITLE
Pow R3 with Firmware 1.0.0 power, current and voltage meter not work

### ISSUE THREAD

**Issue by ssrsmart** [AlexxIT/SonoffLAN#820]
Sonoff Pow3 with Firmware 1.0.0 not work properly, i can turn on & off the switch but power, voltage and current reading work only when i open ewelink app in my phone and when i close the app the reading get jam in home assistant

**Comment by AlexxIT** [comment]
Download diagnostics on device page

**Comment by ssrsmart** [comment]
[sonoffdd-320a5ef5bc5a22913de48a5ef0237d93-POWR3-596f76c06ece06006fc7a64785d067ec.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8635550/sonoffdd-320a5ef5bc5a22913de48a5ef0237d93-POWR3-596f76c06ece06006fc7a64785d067ec.json.txt)

**Comment by ssrsmart** [comment]
also when i tried t disconnected  internet cable from my network, home assistant loss the control of sonoff devices, i run home assistant on vm and lan control is enable in all devices !

**Comment by AlexxIT** [comment]
Go to System Health page to check if you have working local devices.

Can you share this device with my account? sonofflan@gmail.com
Can you update its firmware?

**Comment by ssrsmart** [comment]
all devices have latest version, 3.5.0 on switches and sensors and 1.0.0 on pow R3, also all devices LAN control enable

I checked health page and that what i got :

Version | 3.0.3
Cloud devices online | 3 / 3
Local devices online | 0 / 0

also I tried to share the device with your account but i got this message :
![20210515_004520-01-01](https://user-images.githubusercontent.com/102299247/167106066-1cc34170-5b46-4124-b0bd-f1cbffba58eb.jpeg)

**Comment by ssrsmart** [comment]
all devices have latest version, 3.5.0 on switches and sensors and 1.0.0 on pow R3, also all devices LAN control enable

I checked health page and that what i got :

Version | 3.0.3
Cloud devices online | 3 / 3
Local devices online | 0 / 0

also I tried to share the device with your account but i got this message :
![20220506_122804](https://user-images.githubusercontent.com/102299247/167106387-41e71108-8e2f-412f-8f3a-1985a06c0af8.jpg)

**Comment by AlexxIT** [comment]
Can you try share home function? You can create home with only one device.

App > profile > homes > invite

**Comment by ssrsmart** [comment]
i got the same message, may be there is a problem with your account
![Uploading 20220507_130244.jpg…]()

**Comment by ssrsmart** [comment]
i got the same message, may be there is a problem with your account
![20220507_130244](https://user-images.githubusercontent.com/102299247/167249877-8c4abb47-d0d7-4dc1-b175-90d0cb9eb08b.jpg)

**Comment by AlexxIT** [comment]
In Hass community you show stats: Local devices online 0 / 3
But here you have 0/0. Something changed in your setup?

**Comment by AlexxIT** [comment]
I've made a new way of sharing. You can use it if you want
https://github.com/AlexxIT/SonoffLAN/wiki/Token

**Comment by ssrsmart** [comment]
I tasmotized the pow r3, for now i have th-16 and 2switches device with rf remote control with 3.0.5 firmware, I have no poblem to invite you for both devices if you want

**Comment by ssrsmart** [comment]
also the last update seems that solved the issue, i checked system health now and found :


Version 3.0.5 (200f243)

Cloud devices online   2 / 2
Local devices online   2 / 2
Debug page  – more info

**Comment by AlexxIT** [comment]
There is no problem with support simple switches
