### ISSUE TITLE
Sonoff RF Bridge lost the usage of toggle button (set to off) greyed out

### ISSUE THREAD

**Issue by aperr69** [AlexxIT/SonoffLAN#822]
Upgraded from v303 to v304 and toggle on/off button greyed out in the off position on HA card.

**Comment by AlexxIT** [comment]
Maybe your bridge offline?

**Comment by aperr69** [comment]
Rolled back to v303 without touching the bridge and full functionality restored

**Comment by aperr69** [comment]
[V304 - sonoff-c0bf6e744bd247c21ef9d22a87b93999-RFBridge433-51e361f38be731590c6189f94c27a544.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8638212/V304.-.sonoff-c0bf6e744bd247c21ef9d22a87b93999-RFBridge433-51e361f38be731590c6189f94c27a544.json.txt)
[V303 - sonoff-c0bf6e744bd247c21ef9d22a87b93999-RFBridge433-51e361f38be731590c6189f94c27a544.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8638213/V303.-.sonoff-c0bf6e744bd247c21ef9d22a87b93999-RFBridge433-51e361f38be731590c6189f94c27a544.json.txt)
![Screenshot 2022-05-06 074245](https://user-images.githubusercontent.com/83909627/167084107-81397eb7-8443-4bbe-b9b4-dcc20d4d646a.jpg)
![Screenshot 2022-05-06 080713](https://user-images.githubusercontent.com/83909627/167084118-d7813523-21ed-40b6-bb73-644fb1380f06.jpg)

**Comment by AlexxIT** [comment]
The device turns gray when it is offline

**Comment by aperr69** [comment]
Absolutely, but it wont switch on.

**Comment by aperr69** [comment]
Hi Alex, I'm having this same issue with 3.0.5. RFBridge device is online in all cases, working fine with 3.0.3. However the RFBridge button is greyed out in 3.0.4 and with 3.0.5 all of the card is greyed out, including all the remote buttons.  I'm starting to think that maybe my configuration is somehow incorrect or maybe I need to include something else with these later releases? So my configuration.yaml has this in it:

sonoff:
  username: myewelinkregisteredmail@email.com
  password: mypassword
  reload: always

After upgrading to 3.0.5 as mentioned above, the whole card is greyed, yet the RFBridge is online. Restoring the full system backup with 3.0.3 included, the RFBridge, which remains in the online state throughout, operates perfectly.

**Comment by aperr69** [comment]
Ok fixed. De-installed V3.0.3 completely and restarted HA. Installed a fresh copy of V3.0.5.  Using the same segment in the configuration.yaml as above. Re-added the card, button and switch. All is working.
