### ISSUE TITLE
Consumption history data SonoffLAN 

### ISSUE THREAD

**Issue by caitotheonlypotato** [AlexxIT/SonoffLAN#823]
Hi.

Until recently I have always been able to extract historic consumption data in kWh from practiacally any SONOFF device with power monitoring with the following code.

`      today_consumption_shed_breaker_1_1:
        friendly_name: Today consumption shed Breaker 1
        unit_of_measurement: kWh
        value_template: "{{ state_attr('switch.sonoff_yournumberhere', 'consumption').0 | round(1) }}"
      month_consumption_shed_breaker_1_1:
        friendly_name: 30 days consumption shed Breaker 1
        unit_of_measurement: kWh
        value_template: "{% set p=state_attr('switch.yournumberhere', 'consumption') %}{{ p[:30]|sum if p }}"`

I also used to be able to view the history in a list in developer options, it no longer shows.
I'm unsure as to whether this is an issue with the integration or the HA core.

I'm happy to raise it there if that's indeed the right place to start :) 

regards
Greg

**Comment by caitotheonlypotato** [comment]
![image](https://user-images.githubusercontent.com/57476695/167080489-92ba980f-1042-47e3-ae7b-e876a967ee16.png)

**Comment by alidsd** [comment]
Hi Alex , I am having the same issue. Historical Power consumption in kwh as attribute is no longer there on latest integration version.

**Comment by msemenkin** [comment]
I have the same issue. Consumption attribute is not available anymore:(

**Comment by AlexxIT** [comment]
Adds history data to latest master-version. Will be in next release
https://github.com/AlexxIT/SonoffLAN#sonoff-pow

**Comment by alidsd** [comment]
Hi Alex, Updated to latest update (3.0.5), after refresh/restart, I am unable to find the consumption history  as attribute (100 days comma separated values), Before it used to display in bottom of Power dialog. maybe I am missing something.

![image](https://user-images.githubusercontent.com/1798225/167925975-b94f552a-d25c-4f57-adae-5580c498e7b5.png)

**Comment by AlexxIT** [comment]
@alidsd by default history disabled
https://github.com/AlexxIT/SonoffLAN#sonoff-pow

**Comment by alidsd** [comment]
Hi Alex,
It is already there and enabled (sorry I forgot to mention this), but there is no 'attributes' dropdown where daily consumption history used to be shown as comma seperated string. 
here is my config.

sonoff:
  username: !secret sonoff_usr
  password: !secret sonoff_pwd
  #mode: auto
  reload: always
  sensors: [power, current, voltage]
  force_update: [power, current, voltage]
  scan_interval: '00:05:00'  # (optional) default 5 minutes
  energy: [300, 15]  # update interval (seconds), history size (days)

**Comment by caitotheonlypotato** [comment]
I don't use this YAML config any more, I configured mine through the integration iteslf, and commented the old code off

**Comment by AlexxIT** [comment]
@alidsd your config wrong

**Comment by caitotheonlypotato** [comment]
This code for me returns historic consumption for 10 days as a single total, not a day by day breakdown.  Does that help you @alidsd

![image](https://user-images.githubusercontent.com/57476695/168207223-59a2834e-dbf5-4e0c-bbb1-9ba08cee317d.png)

**Comment by alidsd** [comment]
> This code for me returns historic consumption for 10 days as a single total, not a day by day breakdown. Does that help you @alidsd
> 
> ![image](https://user-images.githubusercontent.com/57476695/168207223-59a2834e-dbf5-4e0c-bbb1-9ba08cee317d.png)

Hi @caitotheonlypotato , 
I assume that old YAML config is still supported because there is no error produced.
Secondly even if I configure through integration and put energy: [3600, 10] in YAML, then It is not what was a few release ago.
Having total energy in single variable is not as previous. 
Previously it used to have Attribute dropdown where along with all properties, a consumption with comma separated values for 100 days was there. It used to give breakdown of each day consumed energy that can be used in graphs, template and integration sensors. 
Having total of either 10 or 30 days in a single total is not I needed.  Previous feature was fantastic.
I request Alex to enable that feature again for pow devices.
Thanks.

**Comment by AlexxIT** [comment]
Feature supported. Your config wrong.

**Comment by caitotheonlypotato** [comment]
> > This code for me returns historic consumption for 10 days as a single total, not a day by day breakdown. Does that help you @alidsd
> > ![image](https://user-images.githubusercontent.com/57476695/168207223-59a2834e-dbf5-4e0c-bbb1-9ba08cee317d.png)
> 
> Hi @caitotheonlypotato , I assume that old YAML config is still supported because there is no error produced. Secondly even if I configure through integration and put energy: [3600, 10] in YAML, then It is not what was a few release ago. Having total energy in single variable is not as previous. Previously it used to have Attribute dropdown where along with all properties, a consumption with comma separated values for 100 days was there. It used to give breakdown of each day consumed energy that can be used in graphs, template and integration sensors. Having total of either 10 or 30 days in a single total is not I needed. Previous feature was fantastic. I request Alex to enable that feature again for pow devices. Thanks.

Hi @alidsd 

If you drop the legacy YAML which is now configurable in the integration and follow the code precisely, you should see this result in developer options, which I presume you can adapt to suit your needs, the daily totals are not comma separated in the output, there is a line break instead.

Here is the code I used to generate the output in developer options, by using the _energy compnent of the entity eg for this code, the entity in developer options was "sensor.sonoff_10012c4e9b_energy"

`sonoff:
  devices:
    10012c4e9b:
      reporting:
        energy: [3600, 30]  # update interval (seconds), history size (days)   `

`- sensor:

##############################
#     SONOFF HISTORY TEST    #
##############################
    - name: "House Solar Breaker 1 of 3, 30 days consumption"
      unit_of_measurement: "kWh"
      state: "{{ states('sensor.sonoff_10012c4e9b_energy') | float(0) | round(1) }}"`

![image](https://user-images.githubusercontent.com/57476695/168291498-4492c86e-6ec8-4f07-8eee-eb79b1f2bb48.png)

**Comment by alidsd** [comment]
HI @AlexxIT & @caitotheonlypotato ,
Really appreciate you help and guidance, Now it is solved but thanks for pointer. I am an old user of Alex sonoff integration so thats why having old way to configure this integration, When Alex was saying that your configuration is wrong then I was not able to understand that what was wrong because all the other things were working except consumption history. But now it is there. 
So yes I entirely removed config from Yaml , deleted integration from Hacs, restarted HA, and then again added from Hacs and only put the relevant energy attribute (with device id) in Yaml, and it started working. Now I am back to future again as my lot of automation and calculation depends on it.
I really appreciate the time and effort that were spent by Alex on this integration, I wish that I could contribute in coding and in new features but due to extremely busy in multiple projects , I can not . 

Thanks.


![image](https://user-images.githubusercontent.com/1798225/168302652-0337a901-6266-4f27-9d05-3493c569efc4.png)

**Comment by fariddergal** [comment]
Hi Guys,

I am still struggling with this issue, I have tried all the suggestions described here, and can find the problem, I can not get the consumption data from the pow switches. 
Here is what I get.
![image](https://user-images.githubusercontent.com/60364206/168484298-8465e1b5-a5d1-481a-a8df-5ad1fa64eb3b.png)
![image](https://user-images.githubusercontent.com/60364206/168484511-090d7107-65d2-4beb-b3e3-533b6b6cae9e.png)


This is my configuration:

![image](https://user-images.githubusercontent.com/60364206/168484428-4f5ceaed-c384-48b7-ae2d-5d6ad6633402.png)
![image](https://user-images.githubusercontent.com/60364206/168484455-b3b088c3-ebfb-4b2b-b38e-180a118b7d7d.png)

Any idea? 

Thanks a lot.

**Comment by alidsd** [comment]
Hi ,
Consumption history is only available under the energy entity. First you need to enable it, then you will be able to see it  and its attributes in dev screen. By default, this entity is hidden, you need to enable it from Devices page.



![image](https://user-images.githubusercontent.com/1798225/168490634-c2d47882-9f8e-40e9-894f-f9cac5af1002.png)


> Hi Guys,
> 
> I am still struggling with this issue, I have tried all the suggestions described here, and can find the problem, I can not get the consumption data from the pow switches. Here is what I get. ![image](https://user-images.githubusercontent.com/60364206/168484298-8465e1b5-a5d1-481a-a8df-5ad1fa64eb3b.png) ![image](https://user-images.githubusercontent.com/60364206/168484511-090d7107-65d2-4beb-b3e3-533b6b6cae9e.png)
> 
> This is my configuration:
> 
> ![image](https://user-images.githubusercontent.com/60364206/168484428-4f5ceaed-c384-48b7-ae2d-5d6ad6633402.png) ![image](https://user-images.githubusercontent.com/60364206/168484455-b3b088c3-ebfb-4b2b-b38e-180a118b7d7d.png)
> 
> Any idea?
> 
> Thanks a lot.

**Comment by fariddergal** [comment]
Thank you, I made it,  it was unabled, I think this is hiden and was i little difficult to find,   Thanks a lot

**Comment by debug7878** [comment]
> HI @AlexxIT & @caitotheonlypotato , Really appreciate you help and guidance, Now it is solved but thanks for pointer. I am an old user of Alex sonoff integration so thats why having old way to configure this integration, When Alex was saying that your configuration is wrong then I was not able to understand that what was wrong because all the other things were working except consumption history. But now it is there. So yes I entirely removed config from Yaml , deleted integration from Hacs, restarted HA, and then again added from Hacs and only put the relevant energy attribute (with device id) in Yaml, and it started working. Now I am back to future again as my lot of automation and calculation depends on it. I really appreciate the time and effort that were spent by Alex on this integration, I wish that I could contribute in coding and in new features but due to extremely busy in multiple projects , I can not .
> 
> Thanks.
> 
> ![image](https://user-images.githubusercontent.com/1798225/168302652-0337a901-6266-4f27-9d05-3493c569efc4.png)
> 
> Update: Integration working flawlessly just like before.
> 
> ![image](https://user-images.githubusercontent.com/1798225/168320162-6db026b4-0895-4131-a04f-c6f4e144e74e.png)

Hi [alidsd](https://github.com/alidsd)

Would it be possible to share your code to pull the data to generate the info in the image.

Thanks in advance

**Comment by alidsd** [comment]
Please let me know which image code you are referring to .

**Comment by debug7878** [comment]
> Please let me know which image code you are referring to .

Hi
The image below.

![image](https://user-images.githubusercontent.com/62151544/168610376-2246d2f5-5c6b-44b8-b804-4dc24e24f64d.png)

**Comment by alidsd** [comment]
BTW , this thread is only for feature/bug related communication so it should be used only this purpose.
FYI, the graph are made with mini graph card (Home Assistant HACS), you can find the details and sample code on HA forum.

**Comment by paulorafael68** [comment]
I @alidsd i put this but I only have 1 day only actual day:
![Screenshot 2022-05-18 at 09-26-40 File editor – Home Assistant](https://user-images.githubusercontent.com/70241810/168994269-6fce29fa-d29a-41aa-ab8a-e2824cd7eb11.png)
![Screenshot 2022-05-18 at 09-28-37 File editor – Home Assistant](https://user-images.githubusercontent.com/70241810/168994386-dcd61bb4-41fc-486a-9d51-edfb0a1b7744.png)

the result only 1 daY:


![Screenshot 2022-05-18 at 09-32-49 Ferramentas de Programação – Home Assistant](https://user-images.githubusercontent.com/70241810/168995069-ec093f60-5e42-49d2-90b9-caa0ca033908.png)

**Comment by alidsd** [comment]
here it is :

**Comment by caitotheonlypotato** [comment]
@AlexxIT 

Is there any way to default all Sonoff devices with the energy entity enabled to a different update frequency, or must each device be specified individually in configuration.yaml?
Case in point as per the example supplied in the release documentation is 3600 seconds (1 hour) for one specified device, how do we make this all devices for say 300 seconds please?

**Comment by AlexxIT** [comment]
@caitotheonlypotato there is no group setting

**Comment by ari-za** [comment]
> > Please let me know which image code you are referring to .
> 
> Hi The image below.
> 
> ![image](https://user-images.githubusercontent.com/62151544/168610376-2246d2f5-5c6b-44b8-b804-4dc24e24f64d.png)

Looks good. How do you create multiple sensors for 15, 30, 60, 90, 100 days?

I have used this 

`sonoff:
  devices:
    1000xxxxxx:
      reporting:
        energy: [3600, 10]  # update interval (seconds), history size (days)

template:
  - sensor:
      - name: "10 days consumpion"
        unit_of_measurement: "kWh"
        state: "{{ (state_attr('sensor.sonoff_1000xxxxxx_energy', 'history') or [])|sum }}"`

However how would I create multiple sensors for the same device with different history days?

Thanks
