### ISSUE TITLE
Some Zigbee devices connected to ZBBridge stopped working

### ISSUE THREAD

**Issue by princzkeljanos** [AlexxIT/SonoffLAN#825]
After upgrading to v3.0.4 some sensors connected to ZBBridge stopped working and showing unavailable state. Mainly Motion and open sensors are affected.

Tried to restart the HA, tried to reload integration, but non of them solved the issue.
Devices are online and working in eWelink app.
Tried to restart the bridge, and it did not solve the problem.

![image](https://user-images.githubusercontent.com/6016442/167106617-964dbb62-cc0a-4d9a-b881-62913d171416.png)
![image](https://user-images.githubusercontent.com/6016442/167106738-b161671f-d7a4-401a-a396-6716b9daaf34.png)

**Comment by AlexxIT** [comment]
Download diagnostics on device page

**Comment by AlexxIT** [comment]
Maybe you using multiple homes in ewelink app. Because in your log only one cloud device
