### ISSUE TITLE
iFan03 not working (e.g., light, fan and speed)

### ISSUE THREAD

**Issue by circa1741** [AlexxIT/SonoffLAN#826]
iFan03 has not been working since 3.0.0. Tried all point releases including 3.0.4 and still not working. Light and fan show "unavailable" in Developer Tools.

Attached is the downloaded diagnostics.

[config_entry-sonoff-c8ea9e7624e4c87182c40c7acfa6f78f.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8639967/config_entry-sonoff-c8ea9e7624e4c87182c40c7acfa6f78f.json.txt)

[sonoff-6cde0f08de42f08d2696070ec62a66a7-Master Room Fan-0c0ddef3abb7ef0c2d5577269e872046.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8640104/sonoff-6cde0f08de42f08d2696070ec62a66a7-Master.Room.Fan-0c0ddef3abb7ef0c2d5577269e872046.json.txt)

.

**Comment by AlexxIT** [comment]
Can you show screen from device page? Your log looks fine

**Comment by circa1741** [comment]
Please disregard. I will close this ticket.

I was able to turn on/off the light and fan from the Devices page. Now, everything seems to be in order.

Thanks.
