### ISSUE TITLE
Can't login with mode: auto

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/SonoffLAN#829]
Hi
This is new for me.

<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Sonoff</h3></div>

Version | 3.0.4 (8a202d5)
-- | --
Cloud devices online | 8 / 11
Local devices online | 8 / 8

</body>
</html>

<html>
<body>

Versión | core-2022.5.2
-- | --

</body>
</html>

_Este error se originó a partir de una integración personalizada.

Logger: custom_components.sonoff
Source: custom_components/sonoff/core/ewelink/cloud.py:124
Integration: Sonoff (documentation, issues)
First occurred: 12:07:32 (1 occurrences)
Last logged: 12:07:32

Can't login with mode: auto
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 156, in async_setup_entry
    await registry.cloud.login(username, password)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 124, in login
    r = await self.session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError_

**Comment by AlexxIT** [comment]
Well. I have increased timeout from 10 to 30 seconds. But anyway this is not good
