### ISSUE TITLE
Support Devices and Areas

### ISSUE THREAD

**Issue by Tahutipai** [AlexxIT/SonoffLAN#83]
This is amazing, thankyou! Much better than flashing firmware.

I have this successfully set up, and can control my Sonoff S31 smartplugs from Home Assistant.

But I can not figure out how to add these devices to a "Room" within Home Assistant. E.g set one plug to "Living room", and another to "Bedroom" etc.

Any tips on how to do this?

**Comment by AlexxIT** [comment]
Hey. I have not implemented "devices" yet. As far as I know, only devices can be placed in rooms.

**Comment by darkpwny** [comment]
+1 Bump.  Required for some automation tasks.

**Comment by AlexxIT** [comment]
You don't need devices to set up automation.

**Comment by mrulke** [comment]
Would really love this as i am using https://github.com/thomasloven/lovelace-auto-entities
and making cards based on Area. cant so this with entities.
so would love to see this added.

**Comment by mstumpel** [comment]
You say in one of your comments that You don't need devices to set up automation. Do you have some sample config of such eh an automation to turn on a sonoff switch at a certain time?

**Comment by AlexxIT** [comment]
```yaml
service: homeassistant.turn_on
entity_id: switch.sonoff_0123456789
```

**Comment by mstumpel** [comment]
Thx for your very fast support

Regards

Marcel Stumpel

**Comment by HansHM** [comment]
I am switching from Tuya to Sonoff and can confirm that https://www.aliexpress.com/item/4001174956201.html Tuya Temperature Humidity Sensor Alarm System Devices Intelligent Home Automation for Alexa Amazon Google Support General APP

Is working with de Sonoff Zigbee Gateway and Hassio.

**Comment by AndyZaa** [comment]
> Would really love this as i am using https://github.com/thomasloven/lovelace-auto-entities
> and making cards based on Area. cant so this with entities.
> so would love to see this added.

Thank you very much for this excellent capability, AlexxIT. However, adding my Sonoff AlexxIT integrations to Areas is the one thing that I am missing as well. Mostly for auto-entities but also for general organization of components.

**Comment by Wumfie** [comment]
Yes this would be very helpful as it would require not having to go into advanced mode for scenes

**Comment by AlexxIT** [comment]
Latest HA support Areas for entities. Not only for Devices

**Comment by AlexxIT** [comment]
Check new beta-version:
https://github.com/AlexxIT/SonoffLAN/releases
