### ISSUE TITLE
error rf bridge and state blinds KingArt

### ISSUE THREAD

**Issue by JJoaquinrl** [AlexxIT/SonoffLAN#830]
First thank you for your work.
I have been a user of sonoffland for more than 2 years, I have about 220 devices and so far everything is perfect, but....

I have 14 KingArt blind devices, the handling works, but the status never changes, it only changes if the % bar is moved, if it is moved from ewelink it doesn't, if an automation is executed either.
there they are closed and continue to indicate open and never change
The automations that depend on the state do not work, because the condition is... if xxx is closed, open it, but since it is believed to be open it does not open it
![1](https://user-images.githubusercontent.com/72837971/167312665-5aca60ae-c06a-4410-93b0-fa6cc7d18990.png)

I have 3 rf bridge, if I create any binary sensor from bridge number 1 perfect, if I create it from bridge number 2 all the rf devices disappear, if I create it from bridge 3 all devices also disappear.
I use the latest version, 3.0.4
thanks for all greetings

**Comment by wackla33** [comment]
I have also observed the same problem that the colleague has described.  Even when I updated the integration to the latest version, the blind stopped working completely for me, but after a pending update in ewelink, it worked again, although with the error of the percentages.

**Comment by wackla33** [comment]
I also have the same problem described by the colleague with sonoff bridges

**Comment by AlexxIT** [comment]
For blinds, this is duplicate #792 

For RFBridge you need to download diagnostics from device page

**Comment by AlexxIT** [comment]
I still need to see your diagnostics info

**Comment by JJoaquinrl** [comment]
> Todavía necesito ver su información de diagnóstico

this is the register of the rf bridge that disappears

[sonoff-9e1b94693f64bd9b7b2bb51248580199-Bridge Volumétrico-f239e5ea497aaddf2d6c69d66f5bd1b4.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8653242/sonoff-9e1b94693f64bd9b7b2bb51248580199-Bridge.Volumetrico-f239e5ea497aaddf2d6c69d66f5bd1b4.json.txt)

It happens when creating the last sensor, the first 3 belong to brige 1, which copies the signals to it to solve the problem momentarily
![son](https://user-images.githubusercontent.com/72837971/167448959-1c74bfb6-a291-4df7-91a0-4ab98690862c.png)

**Comment by AlexxIT** [comment]
Component can't find some of your payload_off. I have added an warning to latest master version. You can find problem payload there
