### ISSUE TITLE
Reverting back to v 2.4.7 - how to?

### ISSUE THREAD

**Issue by RTouris** [AlexxIT/SonoffLAN#831]
Seeing that I've lost all my sonoff devices upon updating to 3.0.4 and none of the 3.x versions seem to do the trick for me - free time being incredibly scarce as of late and debugging not being an option due to lack of time - what would be the easiest way of reverting back to 2.4.7 since it's not available under HACS / Integrations / Sonoff LAN / Select version field anymore? I'm running the latest HA on a Oracle VM - never had any issue with my setup so far...Thanks for any replies

**Comment by AlexxIT** [comment]
You need to ask about HACS in HACS repo. Or just go to HACS integration options
