### ISSUE TITLE
Cannot configure component authorization after installation

### ISSUE THREAD

**Issue by iPavliQ** [AlexxIT/SonoffLAN#833]
After component installation and rebooting HA, I did next steps:
navigated to 'Configuration' -> 'Integrations' -> '+' and searched for 'Sonoff', exact component have appeared and after click on it I have getting 'error failed to load configuration wizard' message, so i went to configuration.yaml and tried to add credentials manually:
'sonoff:
 username: Yyyyyy@xxxxxx.org
 password: Xxxxxx1234' 
So after script check I have got: `Component error: sonoff - cannot import name 'BinarySensorDeviceClass' from 'homeassistant.components.binary_sensor' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/binary_sensor/__init__.py)`
What i'm doing wrong?

**Comment by AlexxIT** [comment]
I think you using old unsupported Hass version. Minimal supported v2021.12

**Comment by iPavliQ** [comment]
Thank you so much!
