### ISSUE TITLE
Unable to find service sonoff.update_consumption

### ISSUE THREAD

**Issue by jbeardon** [AlexxIT/SonoffLAN#835]
Have not been able to pull in historical consumption in either the current or previous version.
Operation mode is set to auto (as it has been for over a year).

Have reinstalled the main branch within HACS.

sonoff.update_consumption still does not exist.

Any help appreciated.
Thanks, John

**Comment by emonteroe** [comment]
I updated to latest release and i saw that the service is present on services.yaml but it doesn't show in the UI:
send_command:
  description: Sends a command to a device.
  fields:
    device:
      description: Device ID to send command to.
      example: '1000123456'
    cmd:
      description: A single command to send.
      example: 'switch'

**update_consumption:
  description: Power consumption update of all Pow devices.**

**Comment by AlexxIT** [comment]
This service deprecated and removed from readme. Just forgot to remove it from yaml
