### ISSUE TITLE
Zigbee devices no longer show battery charge remaining

### ISSUE THREAD

**Issue by Siggy101** [AlexxIT/SonoffLAN#836]
I used to have a sensor set up showing the battery % remaining in my Sonoff Zigbee devices (eg:  SNZB-02, SNZB-04 etc) but since about 1 month or so, no attributes show for these devices.
Can the attributes please be added back in.

![image](https://user-images.githubusercontent.com/41893936/168391134-95f838e5-46ef-41ca-a83e-503d66c5ebf0.png)

**Comment by AlexxIT** [comment]
Download diagnostics from device page

**Comment by Siggy101** [comment]
Sorry it has taken a very long time but here is the diagnostics file from one of my many temp/humidity sensors which I cannot get the battery % from anymore.
[sonoff-7a1134d77e68a1326c959ec3b329a471-Armoury-e38468ddc4e04197cec61999090325bd.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8908961/sonoff-7a1134d77e68a1326c959ec3b329a471-Armoury-e38468ddc4e04197cec61999090325bd.json.txt)

**Comment by AlexxIT** [comment]
Oh. You shouldn't look it in temp attributes. It's separate sensor now.

**Comment by Siggy101** [comment]
> 

Thanks.  I worked that out now and have them working again.
