### ISSUE TITLE
Cannot get device list in HA

### ISSUE THREAD

**Issue by fudu** [AlexxIT/SonoffLAN#84]
Configured as indicated with username and pw, want to use only through ewelink cloud
Log does not show errors.
Sonoff.json created with all device inside
But I cannot views any sonoff device in HA .....

[config.zip](https://github.com/AlexxIT/SonoffLAN/files/4563316/config.zip)

**Comment by tkotz8105** [comment]
Having same problem... migrated from HA .99 to .109 and sonoff device not showing in HA .109 states... using v1.10.3 of SonoffLAN.

**Comment by seradm** [comment]
Having same problem... HA version 0.109.2 and v1.10.3 of SonoffLAN.

**Comment by benputman** [comment]
having same issue. anyone able to figure out fix?

**Comment by AlexxIT** [comment]
Hi. I tested version 0.109.2 in two servers. All works fine.
Did my component work for you before?
Maybe you have problems with multicast? They are described in readme.

**Comment by seradm** [comment]
> Hi. I tested version 0.109.2 in two servers. All works fine.
> Did my component work for you before?
**Mine is a new installation of devices.**

> Maybe you have problems with multicast? **They are described in readme.
The Sonoff.json is created with all device inside. Could there be the same multicast problems?**

**Comment by fudu** [comment]
> Hi. I tested version 0.109.2 in two servers. All works fine.
> Did my component work for you before?
> Maybe you have problems with multicast? They are described in readme.

I installed from new in 0.109.xx.

Perhaps I didn't understand how plugin works, but working only with sonoff cloud, how could be a multicast problem ?

**Comment by barto64** [comment]
First thanks a lot Alex for thus brand new wonderful component. As pointed out for Dr Zzs willing to see it as a native component. I am using it via HACS now.

I had an issue with my connection to the cloud to download my info devices which disappear when I moved the sonoff component entries in the configuration file from the bottom of it to an earlier position on it. Sounds strange bu it made it work, connect t cloud and give m all the nfo of my devices.


спасибо

**Comment by AlexxIT** [comment]
@fudu component ONLY controls devices via LAN. The cloud is used to automatically obtain device encryption keys.

**Comment by AlexxIT** [comment]
I plan to add cloud control in future updates.
This will help users with multicast problems and users of 2nd firmware.
It's a lot of work, I don’t know when I will have time.

**Comment by michelsc75** [comment]
@AlexxIT I'm having the same issue. I think the problem started after the update to Release 0.109.2 - May 1 of HA. Thanks man ! Thanks a lot !

**Comment by AlexxIT** [comment]
Works for me in 0.109.2 on:
- Windows
- Ubuntu x64 + hassio

What is your environment?

**Comment by michelsc75** [comment]
> Works for me in 0.109.2 on:
> 
> * Windows + ha (not venv)
> * Ubuntu x64 + hassio
> 
> What is your environment?

running Ubuntu x64 + hassion on VirtualBox 6.1 (win10).

**Comment by michelsc75** [comment]
Even setting devices manually, they still unavailable.

**Comment by michelsc75** [comment]
I restored a backup with previous version and the sonoff devices were still unavailable then I tried restarting all systems (rebooting the physical server) and now it works !

**Comment by seradm** [comment]
> > Hi. I tested version 0.109.2 in two servers. All works fine.
> > Did my component work for you before?
> > **Mine is a new installation of devices.**
> 
> > Maybe you have problems with multicast? They are described in readme.
> > **The Sonoff.json is created with all device inside. Could there be the same multicast problems?**
> 
> I also tried to manually configure the 'configuration.yaml' file, but i cannot views any sonoff device in HA.

thanks Alex.
I solved. The problem was actually a multicast error.
I have moved the server to the same ip class and everything works.

**Comment by tkotz8105** [comment]
@AlexxIT I was running .99 on a RPi with HASSIO and it was working.  I wanted to test out .109 on a Linux box running Debian and docker.  Thank you for mentioning about Multicast and possible problems with docker.  I did not use --net=host but just forwarded port 8123 with the -p option .... so I'm going to investigate further.  

If anyone has .109 running in docker with SonoffLAN working... if you don't mind sharing your docker run statement or docker-compose file... that may help me out..

**Comment by fudu** [comment]
> @fudu component ONLY controls devices via LAN. The cloud is used to automatically obtain device encryption keys.

Ah, ok, so now I understand because it doesn't work: my sonoff devices are on different vlan/subnet  ....

**Comment by AlexxIT** [comment]
@michelsc75 I heard about problems with multicast in virtualbox. Write about it in readme.

**Comment by AlexxIT** [comment]
@tkotz8105 https://docs.docker.com/network/network-tutorial-host/

**Comment by benputman** [comment]
my problem was with being on different subnets. Bridged the two routers and seems to be working now.

**Comment by enes123** [comment]
Hi, i'm runing hass.io on windows with vmdk file(vmware). Sorry for my bad english but i dont understand, how can i fix multicast error? Thank You.

**Comment by AlexxIT** [comment]
@enes123 Usually you should configure the virtual network on the bridge. Not on NAT!

**Comment by enes123** [comment]
> 
> 
> @enes123 Usually you should configure the virtual network on the bridge. Not on NAT!

OMG, thank you so much. It Worked.

**Comment by Nerijus1984** [comment]
hello done everything as it says, json file is there. restarted HA few times, done a couple of switches on lan mode with ewelink but can't get them to appear in the device list of HA. no clue about the multicast networks. What shall I try next? I'm very new to HA probably I'll have to give up :)

**Comment by brandon-page** [comment]
Same issue here.  Only device is a Micro (firmware 3.4.0) which I see in the json but does not show up in my devices.  hassio 0.109.5 running on Ubuntu Server 20.04. Installed through hacs.  No errors in logs.

**Comment by AlexxIT** [comment]
@Nerijus1984 what does two networks mean? The second case is not a "guest" with disabled communication between devices?

**Comment by AlexxIT** [comment]
@brandon-page try turning on / off the device through the mobile application

**Comment by Nerijus1984** [comment]
> @Nerijus1984 what does two networks mean? The second case is not a "guest" with disabled communication between devices?

@AlexxIT just recently I've upgraded to new isp and obviously I'll have the new router. Didn't wanted to reconnect couple of my iot devices to the new ssid (because some people having issues rexonectig them to the new SSID) so I've logged in to the router and setup new ssid with the old isp credentials though I'll have a separate network for Iot. My laptop with HA virtual machine is connected to the same network as sonoff devices so it should pick up as per instructions on YouTube I suppose.

**Comment by AlexxIT** [comment]
@Nerijus1984 do not forget to enable bridge mode in the network settings of the virtual machine.
I heard VirtualBox has problems with multicast traffic anyway

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by brandon-page** [comment]
After switching to master cloud setup works, so overall success.  However, when I try to use devicekey (with or without cloud) I get the following error:

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/sonoff/__init__.py", line 134, in async_setup
    v['params']['connection'] = 'cloud'
KeyError: 'params'

**Comment by AlexxIT** [comment]
@brandon-page please show config for this error (hide private data)

**Comment by AlexxIT** [comment]
@brandon-page fixed in latest master version

**Comment by Tkthsride** [comment]
I installed the new master release, now it runs only in cloud. If I force local mode all devices disappear

**Comment by AlexxIT** [comment]
@Tkthsride don't understand. Whats mean force local mode?

**Comment by Nerijus1984** [comment]
@AlexxIT sweet all my sonoff devices finally are here in HA. Thanks for a great job @AlexxIT. Just can't get my TH and POW to show the measurements on the main screen (probably is my lack of skills) but eventually I'll find that as well. Great job @AlexxIT really appreciate what you do.

**Comment by AlexxIT** [comment]
@Nerijus1984 TH and POW don't show automatically. You need to create template sensors as it described in readme.

**Comment by Tkthsride** [comment]
> @Tkthsride don't understand. Whats mean force local mode?

Sorry I try to be more clear. I used this code in config:
sonoff:
  username: mymail@gmail.com
  password: mypassword
  mode: local
  reload: always 
With this configuration I see J.son including devices but I don't find them as entities.
If I put the row "mode: local" after # and restart I find them and can configure them in the interface, they run and are indicated as connected in cloud.
If I 'de-comment" the row "mode: local" I go back to original configuration, the entities result "disconnected".
It seems that I cannot connect to them in local mode.
Anyway thanks for your great job

**Comment by AlexxIT** [comment]
@Tkthsride one of the reasons why I added cloud mode. I wrote possible problems with local connection in the readme. But not all users manage to defeat them.
There is no problem with a cloud connection :)

**Comment by arahag** [comment]
I have a Sonoff 4CH Pro R2, like others here I did everything in the instructions:
added the config in YAML, HA recognizes the sonoff component, creates the JSON file with the correct info inside, but HA never creates the entity. My HA is on a VLAN that can access the IoT VLAN where the Sonoff device is.

**Comment by AlexxIT** [comment]
@arahag try new beta version #99

**Comment by arahag** [comment]
Thanks @AlexxIT , jus switched to Master in HACS and works like a charm!!
