### ISSUE TITLE
nspanel us

### ISSUE THREAD

**Issue by Gennyrino** [AlexxIT/SonoffLAN#840]
Ciao, ho un nspabel us ed ho aggiunto ad home assistant termosto nspanel dopo aver copiato in custom components la cartella sonoff, attivato il componente aggiuntivo. Termostato di default è disattivato, l ho attivato, se dalla app ewelink accendo il termostato, regolo la temperatura in home assistant vedo i cambiamwnti, se invece da home assistant accendo il termostato in questa interfaccia non accade nulla ma in ewelonk si accende, mentre se regolo la temperatura questa non viene aggiornata in ewelonk e dopo qualche sencondo si reimposta al valore iniziale.

**Comment by AlexxIT** [comment]
Nichego neponimat'

**Comment by Gennyrino** [comment]
Hi, I have a nspanel us and I added nspanel thermostat to home assistant after copying the sonoff folder in custom components, activated the add-on.  Default thermostat is off, the I activated if the app ewelink turn the thermostat, I set the temperature in the home assistant I see cambiamwnti if instead of home assistant turn the thermostat in this interface, nothing happens but ewelink comes on, while if rule the temperature is not updated in ewelink and after a few sencondo is reset to the initial value.Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Alex X ***@***.***> Data: 15/05/22  17:34  (GMT+01:00) A: AlexxIT/SonoffLAN ***@***.***> Cc: Gennyrino ***@***.***>, Author ***@***.***> Oggetto: Re: [AlexxIT/SonoffLAN] nspanel us (Issue #840) 
Nichego neponimat'

**Comment by AlexxIT** [comment]
Didn't really understand your problem
