### ISSUE TITLE
KingArt cover position status is not synchronized in UI

### ISSUE THREAD

**Issue by vitali84** [AlexxIT/SonoffLAN#845]
Hi
Both status (clositng, stopped etc ) and position (percent) of the covers is not synchronized with the ewelink app since version 3.0.5. Ewelink does show correct statuses
The control buttons themself from the HA do work.

attaching diagnostic

[sonoff-042212acd58924b2b48f59b3cd8e047b-Work room shutters-6aad7279115970f82934b79e51d2aeb4.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8698270/sonoff-042212acd58924b2b48f59b3cd8e047b-Work.room.shutters-6aad7279115970f82934b79e51d2aeb4.json.txt)

**Comment by AlexxIT** [comment]
Duplicate #792 
And already fixed in latest master version
