### ISSUE TITLE
Sonoff SPM with the Relay BUS module 

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/SonoffLAN#847]
I'm using this integration and I successfully integrate this device sonoff SPM but when I use the virtual buttons in the HA the device doesn't report de correctly states

And some times the status keeps wrong...

Is there any way to try solve this issue?

Thank you for your support and best regards

**Comment by AlexxIT** [comment]
You need to provide more useful info

**Comment by MiAutomations** [comment]
> You need to provide more useful info

Ok what more info do you need the logs? Or something to test like a task?

**Comment by luisassis** [comment]
I have the same problem. I'm using SPM integration, when I use HA control to turn ON, the devices turn on, but in a few seconds, the HA Buttons, return to off, and device still on. I think is some problem with synchronization status on entity. I try to use device button ( hardware button ), and status in HA about entity works fine.

**Comment by AlexxIT** [comment]
SPM support improved in the latest release https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.0
Please reopen the issue if there are still any problems
