### ISSUE TITLE
iFan03 is not working since 3.0.0 (e.g., light, fan and speed)

### ISSUE THREAD

**Issue by camnop** [AlexxIT/SonoffLAN#849]
iFan03 has not been working since 3.0.0. Tried all version releases after 3.0.0 and still not working. Light and fan look available in the Device Page, however, when I press the button, it shows a popup saying: "Failed to call service fan/turn_on" and "Failed to call service light/turn_off"

In the Ewelink app, it still works nice.

Sonoff LAN: v3.0.5
iFan03 Firmware: v3.5.0
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0
Kernel version 5.15.38
Agent version 1.2.1

Configuration.yaml:

sonoff:
  username: !secret email2
  password: !secret password1
  force_update: [temperature, power]
  scan_interval: "00:01:00" # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]

  devices:
    1000f6e441:
      device_class: [light, fan]
      name: Ventilador
      force_update: True
      mode: cloud

Attached is the downloaded diagnostics.

[sonoff-040a5976c1bd9aa6e9b2e31a8060d473-Ventilador-0263e9c0683442fdf5c4128d69aaa180.json (1).txt](https://github.com/AlexxIT/SonoffLAN/files/8712438/sonoff-040a5976c1bd9aa6e9b2e31a8060d473-Ventilador-0263e9c0683442fdf5c4128d69aaa180.json.1.txt)

![image](https://user-images.githubusercontent.com/4583389/168935658-c69194b4-bf8d-44f2-9700-63ee931e936e.png)

![image](https://user-images.githubusercontent.com/4583389/168935964-dd979d5c-84f0-4629-ae61-bdc9da1fd177.png)

**Comment by AlexxIT** [comment]
You shouldn't use this device setting for iFan

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
