### ISSUE TITLE
.sonoff.json file not updating 

### ISSUE THREAD

**Issue by qilza** [AlexxIT/SonoffLAN#850]
Hello Team,

I have a problem to get updated .sonoff.json file or get new one if i remove it - it is not creating back.

Version of my sonoff integtation 3.0.5 (200f243)

My configuretion in yaml 

sonoff:
  username: ********
  password: *******
  force_update: [temperature, power]
  scan_interval: '00:00:05'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  reload: always

**Comment by qilza** [comment]
Issue solved 
Found it in /config/.storage/sonoff/  folder with another name of file

**Comment by AlexxIT** [comment]
You may delete this file is using integration v3
