### ISSUE TITLE
Cannot connect to host v3.0.5

### ISSUE THREAD

**Issue by wolfonsetwastaken** [AlexxIT/SonoffLAN#855]
I can't add the integration, because I can't login into my eWeLink account. I receive the message:

**Cannot connect to host eu-apia.coolkit.cc:443 ssl:default [Try again]**

I've tried various different suggestions that I found, for what I understand the similar issue should have been resolved in the latest version. Also tried different versions with same result.

**Comment by amiaty** [comment]
I have the same issue

**Comment by amiaty** [comment]
> I can't add the integration, because I can't login into my eWeLink account. I receive the message:
> 
> **Cannot connect to host eu-apia.coolkit.cc:443 ssl:default [Try again]**
> 
> I've tried various different suggestions that I found, for what I understand the similar issue should have been resolved in the latest version. Also tried different versions with same result.

I have the same issue

**Comment by dufixas** [comment]
same also

**Comment by AndersOrt** [comment]
Had a similar problem and solved it by setting the DNS to one of Google's. You will need the "SSH & Web Terminal"  and the command is "ha dns options --servers dns://IP_ADDRESS ha dns restart", Google's DNS is 8.8.8.8 or 8.8.4.4. You can test it by pinging the server that cannot be reached before and after the change.

**Comment by AlexxIT** [comment]
Should be fixed in latest version

**Comment by gardero** [comment]
Hi @AlexxIT 
I just installed today the latest version and I am getting the same error here when trying to configure the integration.

**Comment by AlexxIT** [comment]
"Cannot connect to host eu-apia.coolkit.cc:443" it's just an your Internet problem. Integration can't do anything with it.

**Comment by gardero** [comment]
Sure, but it is a problem that blocks the integration. Maybe there is
something that can be done to solve it? No other integrations complain
about it.
