### ISSUE TITLE
Feature request: Support for new ITead “SONOFF Zigbee Bridge Pro” (ZBBridge-P) Zigbee Gateway to WiFi Bridge

### ISSUE THREAD

**Issue by Hedda** [AlexxIT/SonoffLAN#857]
"Itead SONOFF Zigbee Bridge Pro" (ZBBridge-P, a.k.a. "ZB Bridge-P") is available for purchase for $24.90 directly from ITead China:

https://itead.cc/product/sonoff-zigbee-bridge-pro/

FCC leak earlier in January this year showed inside with Epressif ESP32 MCU and WiFi + CC2652P Zigbee MCU and radio module:

[https://fccid.io/2APN5ZBBRIDGEP](https://fccid.io/2APN5ZBBRIDGEP)

Both tinkerer bloggers/vloggers [NotEnoughTech](https://github.com/NotEnoughTech) and [digiblur](https://github.com/digiblur) have received theirs and while neither of them has tried to flash/hack it yet they posted some early thoughts on the original eWeLink hub firmware and hardware board, confirming that the first retail version ITead's SONOFF Zigbee Bridge Pro with PCB board labelled "ZBBridge-P V1.1 2021.11.12" is indeed based on Espressiff  ESP32-DOWD-V3 (that ESP32 variant by the way also has integrated support for Bluetooth 4.2 including BLE), Texas Instruments CC2652P Zigbee module labelled "SM-031 V1.1 2021.07.28" (so probably manufactured by [CoolKit Technologies](https://github.com/CoolKit-Technologies/DevDocs/tree/master/Zigbee) like the Zigbee module for previous Sonoff bridge), with a cell-battery for the RTC (Real-Time-Clock), a built-in buzzer for chime or alarm-siren, and also an Espressiff branded PSRAM (ESP-PSRAM16H) with 2MB/16Mbit capacity. Internal pictures posted from FCC show using an unannounced Texas Intruments CC2652P (CC2652P1) MCU chip based “SM-031 v1.1” radio module which must be made by [CoolKit](https://github.com/CoolKit-Technologies/DevDocs/tree/master/Zigbee) (company that also makes their EFR32MG21 based “[SM-011 V1.0](https://www.coolkit.cn/product/sm-011/)” module).  

digiblurDIY also mention that he managed to backup original firmware from ESP32 without issue so suspect that it is not locked:

https://www.youtube.com/watch?v=P5op57y5i6k?t=920&ab_channel=digiblurDIY

https://notenoughtech.com/home-automation/sonoff-zigbee-bridge-pro/

https://www.youtube.com/watch?v=fsIjFxCPJLA&ab_channel=NotEnoughTECH

PS: The main downside the this new and the old Sonoff ZBBridge is that they only have Wi-Fi and not a wired Ethernet LAN (RJ45) port.

**Comment by AlexxIT** [comment]
Do you have it? It doesn't work?

**Comment by Hedda** [comment]
Yes it works if flash ESP32 with Tasmota, see -> https://github.com/arendst/Tasmota/discussions/14419

**Comment by AlexxIT** [comment]
I can't support it if you already flash it to Tasmota

**Comment by Hedda** [comment]
> I can't support it if you already flash it to Tasmota

I only meant that it is ”hackable”.

**Comment by AlexxIT** [comment]
So you have this device and it is connected to ewelink?

**Comment by Hedda** [comment]
Got the device but it is not connected ewelink any longer since flashed it with Tasmota.

Not asking for support for myself, just suggesting that you consider it for your project.

**Comment by bwp91** [comment]
@AlexxIT 

Zigbee bridge pro has uiid 168 and uses same params as original zigbee bridge.
If it helps you can see a template in the first post here https://github.com/bwp91/homebridge-ewelink/issues/408

Hope this helps

**Comment by AlexxIT** [comment]
@bwp91 thanks. I'll add only RSSI sensor for this device.

**Comment by vkolovos** [comment]
Sorry but I am a little bit confused. I purchased a new ZBBridge-P and registered two devices (SNZB01 & SNZB02). Which version will add support for the Pro variation in HA? I am currently running v3.3.1 and the Zigbee child devices are not yet available.

**Comment by Piipz** [comment]
> Sorry but I am a little bit confused. I purchased a new ZBBridge-P and registered two devices (SNZB01 & SNZB02). Which version will add support for the Pro variation in HA? I am currently running v3.3.1 and the Zigbee child devices are not yet available.

Does it work now? I'm running out of devices (max 32 in ZBBridge original) and thinking of getting the Pro, it supports over a hundred subdevices. But if it doesn't work with this, then I suppose I gotta be patient :) I'm adding a lot of sonoff motion sensors and buttons around the house.

**Comment by AlexxIT** [comment]
I think it's better to bye some stick for Hass, so your Zigbee devices will work locally. And won't depend on cloud

**Comment by AlexxIT** [comment]
I have added RSSI sensor for this device. Can't add anything more useful for it.

**Comment by RandomGithubUserX** [comment]
Beside rssi is there any way to add an entity to see in HA if zbbridge armed or not?
