### ISSUE TITLE
Power R2 not working?

### ISSUE THREAD

**Issue by Legsmaniac** [AlexxIT/SonoffLAN#86]
Just discovered your code after HA 0.109.x broke peterbuga's version I had been using for ages.  None of my Sonoff's would show at all.

All except my Power R2 shows with this code.  Anyone else with Power R2 problems?  My software version is 3.4.0.

**Comment by AlexxIT** [comment]
I don’t understand how my code could break something in @peterbuga.

**Comment by Legsmaniac** [comment]
> I don’t understand how my code could break something in @peterbuga.

No, not your code.  Upgrading to Home Assistant 0.109x from 0.108.x broke the ability to use peterbuga's Sonoff code.

So I had to uninstall peterbuga's code and install yours.

Your code, @AlexxIT,  works great except for my Power R2 device.

Apologies if I wasn't clear.

**Comment by AlexxIT** [comment]
What version of firmware does power R2 have?

**Comment by Legsmaniac** [comment]
> What version of firmware does Power R2 have?

PSC-B67-GL and software version 3.4.0, the latest current version.
Is that the correct info and does it help?

**Comment by Legsmaniac** [comment]
Update - It's now appeared. Sort of.
See my post here - https://github.com/peterbuga/HASS-sonoff-ewelink/issues/232#issuecomment-623012591

**Comment by AlexxIT** [comment]
Try manually switch sonoff via button or mobile app. This force to show in HA.

**Comment by Legsmaniac** [comment]
All is well.  Everything working fine.  Including my Power R2 and it's Power, Current and Voltage display and Sensors.

Thank you.
