### ISSUE TITLE
Can't close Dual r3 lite Cover 

### ISSUE THREAD

**Issue by kfirel** [AlexxIT/SonoffLAN#864]
Hi
The Cover is alloways at closed state so I can open It, But not colse it.
at dualr3(not lite) It work Ok, only the lite device makes problems, apparently because the 'lite' does't have the position detaction

**Comment by AlexxIT** [comment]
You need to provide integration debug logs

**Comment by kfirel** [comment]
[sonoff-adb1583c382e38c73d65a42f83febfa4-LivingRoomRight-87797fc8a3d3396a467ac6c48f4a9348.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9105844/sonoff-adb1583c382e38c73d65a42f83febfa4-LivingRoomRight-87797fc8a3d3396a467ac6c48f4a9348.json.txt)
attached.

10X

**Comment by rexopl** [comment]
Since about a month there is problem with reading status from Dual R3.
Running services works fine but status is not refreshed.
Only refresh addon triggers read state once, and than it stop refresh again

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
