### ISSUE TITLE
PowR3 - Relay & multimeter work, power usage unavailable

### ISSUE THREAD

**Issue by TaylorTWBrown** [AlexxIT/SonoffLAN#865]
Hi folks! I have 2x PowR3 devices acting as power meters.

I can see the relay state, volts, amps & current watts.

Is there any way I can view historical watt-hours as recorded by the device? E.G.: Power used in 30 days, etc.

These stats are available in the Ewelink app.

**Comment by AlexxIT** [comment]
You need to read docs
