### ISSUE TITLE
GK-200MP2-B Camera Not Working

### ISSUE THREAD

**Issue by iotinkognito** [AlexxIT/SonoffLAN#868]
GK-200MP2-B Camera is not working. No camera entity.
Calling 
      - service: sonoff.send_command
        data:
          device: '012345'  # use quotes, this is important
          cmd: left
gives green tick but nothing comes up on the camera. 

No way to view the camera stream also.

**Comment by wesleyroseno** [comment]
I have the same problem. I have identified that PTZ has stopped working for the cameras I recently added to eWeLink on the smartphone. For example, I had a camera that PTZ commands were working, but when I deleted it from eWeLink and added it again, PTZ commands in HA stopped working. But the cameras that are longer on eWeLink, PTZ commands work on HA. I believe it is a compatibility issue with some eWeLink update.

One could remove a GK-200MP2-B camera from eWeLink on smartphone, and remove from HA. And then add the same camera to see if the PTZ will stop working?

# eWeLink - Version: 4.23.0
# core-2022.6.7
# Home Assistant OS 8.2
# Sonoff - Version: 3.0.5 (200f243)

**Comment by wesleyroseno** [comment]
@iotinkognito Older versions of eWeLink are not running RTSP. With me RTSP is only working on version 4.23.0 (the latest one so far).
