### ISSUE TITLE
"Could not add this repository, make sure it is compliant with HACS."

### ISSUE THREAD

**Issue by NigelNooNoo** [AlexxIT/SonoffLAN#87]
When trying to add AlexIT/SonoffLAN in HACS 'Custom Repositories' it errors with;
GitHub returned 404 for https://api.github.com/repos/AlexIT/SonoffLAN
Unable to install AlexIT/SonoffLAN in HACS.  Following error reported in log. 

Log Details (ERROR)
Logger: hacs.repository.integration.AlexIT.SonoffLAN
Source: custom_components/hacs/helpers/validate_repository.py:36
First occurred: 3:25:34 PM (1 occurrences)
Last logged: 3:25:34 PM

Running;
1. RPi 3, 64MB
2. Home Assistant 0.109.2

I had the same issue with my previous HASS build, so rebuilt HASS from scratch to see if this system was at fault.

**Comment by AlexxIT** [comment]
Wrong repo URL. Check carefully readme

**Comment by NigelNooNoo** [comment]
Thank you Alexx, my typo.  Installed now.
