### ISSUE TITLE
Sonoff M5 switches

### ISSUE THREAD

**Issue by rickard2014** [AlexxIT/SonoffLAN#870]
I’ve been testing the integration with the Sonoff M5 family of light switches, and have noticed there’s a delay on home assistant for updating the current status of the entity.

Sometimes you’ll switch it on, the light will switch on but home assistant will timeout on waiting for the confirmation, so the state on the GUI will remain as off. That issue is particularly bad for setting up two way switches with automations.

I currently have a TX and M5 running a sync automation, it works perfectly when activating the keys on the TX, it sends its states and the other one updates accordingly, but not the other way around because the states don’t update on home assistant, which is weird because they do on the ewelink app. Anyway, as the M5 is not listed as tested, would like to know if its a limitation to the current version of the integration or if I’m missing something on my end.

**Comment by rickard2014** [comment]
This is what I could get from the System Health debug page, the entry shows up every time I flick the switch, wether if it is using the app or Home Assistant.
<img width="681" alt="Captura de Tela 2022-06-11 às 18 52 23" src="https://user-images.githubusercontent.com/20989990/173206136-73c37c2b-a6e6-425f-ae83-b34cff941164.png">

**Comment by petebanham** [comment]
Hi Sorry to comment on an old thread but is there any change in the no plan to support position on the  M5 switch please? Was thinking of getting some but no HA is a deal breaker
