### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by milandzuris** [AlexxIT/SonoffLAN#871]
everyday one of my device is unavailable when im turn on or off device

on older verion i dont have this problem

sonofflan version 3.0,5
core newest

**Comment by Tmin10** [comment]
Same issue, by Sonoff Basic with devicekey is unavailable but online in my network.

**Comment by ivohlavaty** [comment]
some issue here with premium account

**Comment by elchanly** [comment]
Same here. all my sonoff devices become unavailable.
Deleted account and started from 0, I can add a device to ewelink, but as soon as i add the integration to HA, it becomes unavailable.

Some relevant debug info:
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/local.py\", line 242, in send\n    resp = await r.json()\n  File \"/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py\", line 1103, in json\n    raise ContentTypeError(\naiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://192.168.0.135:8081/zeroconf/info')\n",

SOMETHING A LITTLE MORE STRANGE HAVING A LOOK AT THIS: my 0.135 device is a tasmotized plug, so IDK why it refers to it, as it's not related to the sonoff plug that becomes unavailable...

full debug info: 
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.0.5",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "200f243",
    "cloud_auth": true,
    "config": {
      "username": "***",
      "password": "***",
      "mode": "local",
      "reload": "always"
    },
    "options": {
      "mode": "local",
      "debug": true
    },
    "errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.local",
        "message": [
          "100087e2fa => Local4 | {'cmd': 'info'}"
        ],
        "level": "ERROR",
        "source": [
          "custom_components/sonoff/core/ewelink/local.py",
          242
        ],
        "timestamp": 1655559343.7152004,
        "exception": "Traceback (most recent call last):\n  File \"/config/custom_components/sonoff/core/ewelink/local.py\", line 242, in send\n    resp = await r.json()\n  File \"/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py\", line 1103, in json\n    raise ContentTypeError(\naiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://192.168.0.135:8081/zeroconf/info')\n",
        "count": 11,
        "first_occurred": 1655533515.1167233
      }
    ],
    "device": {
      "uiid": 1,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "sledOnline": "off",
        "ssid": "***",
        "bssid": "***",
        "switch": "off",
        "fwVersion": "3.5.1",
        "rssi": -50,
        "staMac": "***",
        "startup": "off",
        "init": 1,
        "pulse": "off",
        "pulseWidth": 500
      },
      "model": "0185",
      "online": true,
      "localtype": "plug",
      "deviceid": "100087e2fa"
    }
  }
}

**Comment by AlexxIT** [comment]
Close because no response

**Comment by milandzuris** [comment]
2 days ago have same issue, lights are unvaliable

**Comment by AlexxIT** [comment]
Show integration diagnostics.

**Comment by milandzuris** [comment]
[config_entry-sonoff-112f26700a25cda4c872ec69ba2bbda8.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9482570/config_entry-sonoff-112f26700a25cda4c872ec69ba2bbda8.json.txt)

**Comment by AlexxIT** [comment]
@milandzuris looks like all devices in your log available. But you using mode local. This is a bad idea for stability.
