### ISSUE TITLE
Sonoff NSPanel Temperature sensor does not update regularly

### ISSUE THREAD

**Issue by elrafar** [AlexxIT/SonoffLAN#872]
Hello SonoffLAN team!

have been using sonofflan with an nspanel and the temperature reading only updates when i restart HA alltoguether.

On the official ewelink integration, the temperature sensor appears to report live readings, but it does not offer this as a sensor to HA, only the switches are avaliable.

on the two pictures below are the nspanel tempersture sensor and a A/C sensor on the same room. on the device itself the displayed temp changes correctly.

![photo1654729450](https://user-images.githubusercontent.com/98990459/173631705-791eae3d-e6d5-4693-b286-b40ebd85c7c6.jpeg)
![photo1654729405](https://user-images.githubusercontent.com/98990459/173631710-fb249159-ed8d-41ab-a990-6fd93ecdb1e4.jpeg)

**Comment by elrafar** [comment]
The outdoor temperature reading does update normally

<img width="295" alt="image" src="https://user-images.githubusercontent.com/98990459/173632432-cb5a1a47-7ab6-4182-a70d-a560501fe052.png">

**Comment by jancoetzer** [comment]
I too am having this issue. Thanks SonoffLAN team vir this integration, as it works so much better than the official Sonoff add-on. But it would be nice if the temperature updates regularly. If I reload the integration it refreshes and gives the current temperature. Maybe an update that auto-reloads the integration every couple of minutes?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#force-update
