### ISSUE TITLE
Sonoff DUALR3 can switch ON but not OFF in local mode

### ISSUE THREAD

**Issue by alistairts** [AlexxIT/SonoffLAN#874]
When in local mode, I can switch ON either/both outputs on my DUALR3, but I cannot switch OFF either/both unless I do so via the eWeLink app or by changing the device back to cloud mode.
I have the latest 3.0.5 SonoffLAN version as well the latest 1.4.0 Sonoff firmware version, running HAOS via a Hyper-v VM.

The switch works as it should in local mode when using the older 3.0rc2 SonoffLAN version, but then I'm without the subsequent usable features.
[sonoff-c6a67de5b73100d44b28bc87f050748b-Pool Pump Station-0146242e50622e580427f15605ccf6c2.json.txt](https://github.com/AlexxIT/SonoffLAN/files/8934286/sonoff-c6a67de5b73100d44b28bc87f050748b-Pool.Pump.Station-0146242e50622e580427f15605ccf6c2.json.txt)

**Comment by Kejszijo** [comment]
With my 4chr3 relay has this problem. Sometimes if I turn on (or off) the switch with HA, the relay status does not change

**Comment by MiguelCosta** [comment]
Hi,

I have a similar issue when the DUALR3 is in the cover mode.
e.g.: when I click to close the cover, the status doesn't change, only if I restart the HA the cover appears closed

**Comment by AlexxIT** [comment]
Try latest release v3.1.0

**Comment by alistairts** [comment]
I have tried, but unfortunately it still does not work.
[sonoff-0031b9c48b79d4d3ecd126cf3f7a0001-DUALR3-0146242e50622e580427f15605ccf6c2.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9064337/sonoff-0031b9c48b79d4d3ecd126cf3f7a0001-DUALR3-0146242e50622e580427f15605ccf6c2.json.txt)

**Comment by crazyfacka** [comment]
@AlexxIT I have the same problem with all v3.x versions. I cannot set the position of the covers even. Everything works fine on v2.x.

Is there any way I could lend a helping hand in solving this? More than willing to code to help you :)

**Comment by crazyfacka** [comment]
If I'd have to guess:

https://github.com/AlexxIT/SonoffLAN/blob/86de124c093cb8e3ebad5d2feea12cdda4c6b215/custom_components/sonoff/cover.py#L113

Should be `currLocation` and not `location`.

If so, later on I could test and open a PR :)

**Comment by crazyfacka** [comment]
But now I am confused, as I updated again to this version, and everything is working properly. The only thing I changed, was start HA with the firewall open (allowing Cloud usage for the devices).

But locking again, after restart, did not reduce functionality. So, I am good on my side. I'm leaving my comments for reference.

Thanks for the hard work AlexxIT!

**Comment by crazyfacka** [comment]
Actually, noted that when using the physical switches, the UI wasn't updating.
I've opened a PR which hopefully helps.

https://github.com/AlexxIT/SonoffLAN/pull/910

**Comment by Masterz69** [comment]
For me it become issue after HA OS upgrade to 8.4 (from 7.6). Previously DUALR3 worked perfect.
Right now HA not receive/interpret/display ON status f DUALR3 switches.

When pressing on icon, device actually become ON, but in HA UI remains OFF.
So, ON state not displayed, thus not possible switch to OFF after.

When operating eWelink App - HA UI always show OFF regardless of actual DUALR3 state.

All was Ok on OS 7.6 till Core 2022.8.1, become broken on OS 8.4.

**Comment by Masterz69** [comment]
> 

And suddenly, after >30 minutes after HA upgrade & restart - DUALR3 fully operable again.
Both ON/OFF state displayed in HA UI.
Mystery.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
