### ISSUE TITLE
Sonoff TH elite THR320D or THR316D Sensors 

### ISSUE THREAD

**Issue by MiAutomations** [AlexxIT/SonoffLAN#876]
Hello 

I tested the device, is discovered and for now the only entitys available are the relay/Switch, LED and RSSI 

Can you please make the new device from Sonoff Sonoff TH elite THR320D or THR316D also reade and report the information about the sensors connected ? 

The Sensors available are the Temperature, humidity and also the Soil Moisture Sensor

Please let me know if you need any further information in order to get this implemented

Thank you for your work and best regards

**Comment by MiAutomations** [comment]
> I get time I'm going to try and take a closer look at what may be causing this issue myself, but I doubt that will happen this week.

Great thank you

**Comment by CyrielRct** [comment]
I'm looking for the same thing :) 
Thank you

**Comment by Glacjozo** [comment]
I'm waiting too.
Thanks.

**Comment by jeffallen** [comment]
The problem is a missing device definition in core/devices.py, for UUID 181. PR incoming.

**Comment by Glacjozo** [comment]
It works!!!
Many, many thanks!

**Comment by CyrielRct** [comment]
Worked for me also :) 
Thank you

**Comment by CyrielRct** [comment]
Edit : Looks like Temperature isn't refresh 
Mine stay stuck on the same initial temperature state

**Comment by Glacjozo** [comment]
For me it works ok.

**Comment by CyrielRct** [comment]
@Glacjozo are you Cloud or Local ?

**Comment by Glacjozo** [comment]
Auto

**Comment by CyrielRct** [comment]
Looks like finally it's updating but frequencies doesn't reflect the config 

![image](https://user-images.githubusercontent.com/4038285/177662176-e4105ad8-540c-43d9-8b46-08b97d10491b.png)

```
sonoff:
  username: !secret sonoff_usr
  password: !secret sonoff_pwd
  force_update: [currentTemperature, temperature, power]
  scan_interval: "00:00:30"
  sensors: [currentTemperature, temperature, power]
  mode: local
  reload: always
  debug: True
  devices:
    100172167c:
      device_class: switch
      name: TH Elite Piscine
```

Not sure how to check why

**Comment by AlexxIT** [comment]
@jeffallen Thanks!

**Comment by omenek159** [comment]
I've noticed that when there is AM2301 connected to THR316D it reports temperature, but humidity is 'unknown'. Looks like the problem is converting to integer in sensor.py at line 155. After changing 'int(value)' to 'float(value)' it works again. Can someone confirm this?

**Comment by mobizon16** [comment]
TH Elite (THR316D) + sensor Si7021 does not display humidity in home assistant. The temperature and humidity are displayed on the display of TH Elite itself, everything is fine in the eWeLink application as well.

**Comment by Masterz69** [comment]
> I've noticed that when there is AM2301 connected to THR316D it reports temperature, but humidity is 'unknown'. Looks like the problem is converting to integer in sensor.py at line 155. After changing 'int(value)' to 'float(value)' it works again. Can someone confirm this?

Confirm. After change to float(value) in sensor.py - HA display measured humidity same as on device display.

**Comment by Masterz69** [comment]
BUT, tempretaure & humidity being updated in HA ONLY WHILE eWelink app is running.
As soon I close eWelink app - nothing from TH Elite appears in HA :(

**Comment by Ankker** [comment]
> > I've noticed that when there is AM2301 connected to THR316D it reports temperature, but humidity is 'unknown'. Looks like the problem is converting to integer in sensor.py at line 155. After changing 'int(value)' to 'float(value)' it works again. Can someone confirm this?
> 
> Confirm. After change to float(value) in sensor.py - HA display measured humidity same as on device display.

It work for me (Sonoff THR316 + THS01 and FW: 1.0.2)
