### ISSUE TITLE
Config flow could not be loaded: undefined

### ISSUE THREAD

**Issue by FreedomTears** [AlexxIT/SonoffLAN#877]
Hey, i am using the docker version of homeassistant (Home Assistant Core 2022.6.7) and HACS.

I have found and added Sonoff LAN (v3.0.5) via HACS and restarted homeassistant. When i try to add the integration i can actually find it but i am unable to add it. Everytime i click on it i get the following error and nothing else:

![Screenshot 2022-06-28 212030](https://user-images.githubusercontent.com/14956850/176267546-146a240d-542e-4898-a170-f1eeaf797085.jpeg)

Digging through the logs i found this issue:

```
Logger: homeassistant.setup
Source: setup.py:136
First occurred: 21:29:49 (1 occurrences)
Last logged: 21:29:49

Unable to set up dependencies of sonoff. Setup failed for dependencies: zeroconf
```

i get a zeroconf warning everytime i start homeassistant but it was never an issue up until now ...

any idea on what to try?

**Comment by FreedomTears** [comment]
sovled, it really was just the zeroconf dependency ...

**Comment by Speedy2662** [comment]
Was having the same issue (without the zeroconf stuff) and sorted it by updating my Home Assistant

**Comment by mudmanrv** [comment]
just updated HA to 2025.3.3 and now sonoff lan gives this error - flow can't be loaded.  hung up on where to look to resolve
