### ISSUE TITLE
Can't login "sign verification failed"

### ISSUE THREAD

**Issue by ririck0** [AlexxIT/SonoffLAN#879]
Hello, 

Since this morning, I can no able longer connect in to my account anymore. See home assistant errors:
![image](https://user-images.githubusercontent.com/78958486/176433099-37d593c3-2b3e-4446-a677-84891d4c8d87.png)

But I can still use the mobile app with same username/password.

Do you have any idea of what's going on ?

Thanks in advance,

Best regards,

**Comment by warthog9** [comment]
Also seeing this:
```
Traceback (most recent call last):
 File "/path/to/homeassistant/custom_components/sonoff/__init__.py", line 156, in async_setup_entry
   await registry.cloud.login(username, password)
 File "/path/to/homeassistant/custom_components/sonoff/core/ewelink/cloud.py", line 150, in login
   raise AuthError(resp["msg"])
custom_components.sonoff.core.ewelink.cloud.AuthError: sign verification failed
WARNING (MainThread) [homeassistant.config_entries] Config entry '<email address>' for sonoff integration could not authenticate: sign verification failed
```

A little bit of digging gets me:

{'data': {}, 'error': 400, 'msg': 'sign verification failed'}

as the contents of `resp`

Home Assistant is coming straight from latest git, though I don't think that' particularly playing much of a part here, SonoffLan is the tagged 3.0.5.  I do have `mode: local` set in my configuration file

**Comment by albertruizalonso** [comment]
I have the same problem…

**Comment by jscherry** [comment]
After upgrading to newest beta it asked to to reconfigure. It won't accept my login credentials whic I'm positive are correct

**Comment by escobarin3** [comment]
Same here

**Comment by gateriderz** [comment]
Same here, I rolled back my home assistant to 2022.6.7, it worked properly.  This only happened when upgraded to 2022.7.0.b2 (beta).   Devices with local (LAN) sonoff enabled still works.

 ```
WARNING (MainThread) [custom_components.sonoff] Can't login with mode: auto
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 156, in async_setup_entry
    await registry.cloud.login(username, password)
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 150, in login
    raise AuthError(resp["msg"])
custom_components.sonoff.core.ewelink.cloud.AuthError: sign verification failed
```

**Comment by dreamtheater39** [comment]
I have the same issue on beta 2022.7.bxx

**Comment by csrc** [comment]
Downgraded. Same issue. Not only with this integration btw.

**Comment by dreamtheater39** [comment]
> Downgraded. Same issue. Not only with this integration btw.

Ended up downgrading too....many other components failed too (my vacbot and other sign in warnings)

**Comment by warthog9** [comment]
I thought this might be an expired app id + app secret, but I've swapped out a few that SEEM to be working elsewhere, and I'm continuing to run into the same problem with those.  I've double checked the calculation for the authentication and it looks right to me given the examples I can find.  Best guess, is there's something else required in the payload and it's complaining about the verification that way, unfortunately I don't see a way to get past that without some additional guidance on what's, now, missing.  I did take a look at the CoolKit ha-addon to see if I could see anything obvious, and so far my poking through the code from that isn't yielding anything (also unfortunately, that add-on plays havoc with trying to run it on core)

**Comment by hmmbob** [comment]
I've added two debug lines to capture what is sent and received upon login. I replaced username and password, and replaced 10 characters of the sign with xxxxxxxxxx, No other format changes to the output:

```py
2022-06-30 14:18:11 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] Hmmbob debug: Host: https://eu-apia.coolkit.cc/v2/user/login | json: {'password': '--contains my actual password--', 'countryCode': '+86', 'email': '--contains my actual email--'} | headers: {'Authorization': 'Sign 4vmH1ALSoy0BEmF/7yb/geaxxxxxxxxxxLaoo7aGe4k=', 'X-CK-Appid': 'oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq'}
2022-06-30 14:18:11 DEBUG (MainThread) [custom_components.sonoff.core.ewelink.cloud] Hmmbob debug: {'error': 400, 'msg': 'sign verification failed', 'data': {}}
```

**Comment by dreamtheater39** [comment]
Could someone try to delete integration (and clean up all traces of the component in ha folders) and re configure it to see if that works?

**Comment by gateriderz** [comment]
> Could someone try to delete integration (and clean up all traces of the component in ha folders) and re configure it to see if that works?

Deleted Sonoff LAN Integration
Removed folder custom_components/sonoff
Removed file .sonoff.json
Restarted hass 2022.7.0b0
Redownload from HACS the Sonoff LAN
Restarted hass 2022.7.0b0
Tried adding the Sonoff integration back

Same error:
```Sign verification failed```

**Comment by bdraco** [comment]
We did switch from python 3.9 to python 3.10 so that could be in play here

**Comment by bdraco** [comment]
Verified the json payload is exactly the same between 2022.6.6 and 2022.7 so not json

but I like the python version changing as a potential source since many of the encryption libs changed

**Comment by bdraco** [comment]
Headers are exactly the same between 2022.6.6 and 2022.7.0b0

2022.6.6 responds:
`2022-06-30 15:21:43 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] resp: {'error': 10004, 'msg': 'request redirection', 'data': {'region': 'us'}}`

2022.7.0.b0 responds:
`2022-06-30 15:22:54 WARNING (MainThread) [custom_components.sonoff.core.ewelink.cloud] resp: {'error': 400, 'msg': 'sign verification failed', 'data': {}}`

**Comment by bdraco** [comment]
Switching the payload order to the one shown on https://coolkit-technologies.github.io/eWeLink-API/#/en/DeveloperGuideV2 and removing the spaces in the separators fixed it for me

**Comment by hmmbob** [comment]
That error code is well known: https://github.com/AlexxIT/SonoffLAN/blob/c317407a09e5c5e9aaf2a95e044e5afb5a367dec/custom_components/sonoff/core/ewelink/cloud.py#L141

I guess it's part of successful logon flow (and you are probably not EU based)

**Comment by warthog9** [comment]
@bdraco do you have a quick patch I can toss on mine and check here?

**Comment by bdraco** [comment]
@warthog9 Can you test the linked PR?

**Comment by warthog9** [comment]
@bdraco yup, that sorted it for me

**Comment by gateriderz** [comment]
@bdraco, thanks it worked after modifying the cloud.py file

**Comment by hmmbob** [comment]
Yup, fixed

**Comment by Santanachia** [comment]
@bdraco Same here: fixed

additional question: why `countryCode` is a constant value?

**Comment by hmmbob** [comment]
Because it's not allowed to be empty:

https://coolkit-technologies.github.io/eWeLink-API/#/en/APICenterV2?id=login

**Comment by Santanachia** [comment]
@hmmbob shouldn't there be real value then? The one I give when logging in to the original eWeLink application?

**Comment by hmmbob** [comment]
The countrycode is used server side to determine which region you 'belong to'. This component actually doesn't use logic for that, but ensures that you're redirected automatically to the correct region, if your region is not China. 

So, "maybe" is the answer here ;-)

**Comment by oferbar** [comment]
I'm with HA 2022.6.6, and latest Sonoff integration, but I changed my eWelink password, both in the app and in HA config file.
Then I started getting the same error.
Copying over the cloud.py file didn't fix the issue, so I reverted to the previous password and got access again.

**Comment by VITCHEPF** [comment]
TPLINK integration and SONOFF integration report the same error "Sign Verification Failed"

**Comment by Swiftnesses** [comment]
The pull request above fixes it for me.

**Comment by hmmbob** [comment]
The availability of the maintainer to review and publish?

**Comment by VITCHEPF** [comment]
Thanks @AllexIT for your prompt support :)
