### ISSUE TITLE
Add optional disabling Fan presets

### ISSUE THREAD

**Issue by mouth4war** [AlexxIT/SonoffLAN#882]
Currently, Ifan entities have presets used for speeds (low, medium, high). While there is working speed control via fan speed percentage slider. 

Actual use case for presets is for modes (like Auto or Breeze) not for fan speeds.

Presets should not be used for fan speeds as this is unnecessary and against HA design.

**Comment by AlexxIT** [comment]
Some users asked me to add presets. They not break anything. Sonoff devices don't have real presets. So I don't see any problem here.

**Comment by mouth4war** [comment]
Can it at least be made optional via config? It clutters up homekit integration with unnecessary switches for each fan speed presey

**Comment by mouth4war** [comment]
Can you please link me to the issue where someone requested fan speeds to be shown as presets?

**Comment by AlexxIT** [comment]
Issue was accidentally deleted. I'll add a setting when have some free time

**Comment by azuretower** [comment]
This is still an on going issue. Can we get this bumped up a bit?

**Comment by AlexxIT** [comment]
Config will be:
```yaml
devices:
  1000xxxxxx:
    preset_mode: False
```

**Comment by azuretower** [comment]
Thank you for adding this but it didn't fix the real issue. When I add my ifan04 to Homekit it still shows up with 4 extra switches along with the speed slider. We would like it to only show up in Homekit with a speed selector.

**Comment by AlexxIT** [comment]
Can you see modes switch on the Hass GUI with this option?

**Comment by azuretower** [comment]
![IMG_4041](https://github.com/AlexxIT/SonoffLAN/assets/9751725/76213cf1-f1c0-472b-89cf-c2e66f509ad4)
It looks correct in HA. It removed the preset modes as expected. But in HomeKit it still looks like this. 
![IMG_4042](https://github.com/AlexxIT/SonoffLAN/assets/9751725/b82319e5-8977-467d-a819-eb8f9a9f3874)
The goal was to only have the fan speed slider without the extra switches.

**Comment by AlexxIT** [comment]
Check latest master version

**Comment by azuretower** [comment]
I downloaded the master version and it got rid of the extra homekit entities but now Home Assistant never thinks the fan is "on". if I use the speed control in home assistant it will turn the fan on but not show as on or show what speed it's set to. Also, Homekit should snap to 33% 66% and 100% on the speed slider.

**Comment by AlexxIT** [comment]
Don't think I have time to research HomeKit integration and this strange behaviour.
