### ISSUE TITLE
Door sensor unavailable after last update

### ISSUE THREAD

**Issue by antoweb** [AlexxIT/SonoffLAN#889]
After last update door sensor are uanvailable
![image](https://user-images.githubusercontent.com/32364871/177520030-a0d63528-517c-4614-898f-01b99e514e91.png)

**Comment by antoweb** [comment]
model dw2 wifi

**Comment by hadadil** [comment]
+1

**Comment by davidrpfarinha** [comment]
+1

**Comment by musachibr** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175913912

**Comment by AlexxIT** [comment]
Related to #887
