### ISSUE TITLE
error

### ISSUE THREAD

**Issue by teygeo** [AlexxIT/SonoffLAN#891]
![1657103281896](https://user-images.githubusercontent.com/81954558/177530285-62a64c99-aa60-427a-8559-9b31591162ee.jpg)

**Comment by djk314** [comment]
same....

**Comment by drthanwho** [comment]
Duplicate of #887

**Comment by tomadan1968** [comment]
Me too the same problem...

**Comment by simeon-simsoft** [comment]
me too.. happening here also

**Comment by peregrines2** [comment]
Here too, very annoying problem :(

**Comment by drthanwho** [comment]
@teygeo preferably close this issue and keep an eye on the other one instead as people now still comment here.

**Comment by teygeo** [comment]
Goto https://github.com/AlexxIT/SonoffLAN/issues/887
