### ISSUE TITLE
sign verification failed

### ISSUE THREAD

**Issue by numminorih-git** [AlexxIT/SonoffLAN#894]
after last update HA - sign verification failed

at the same time, device (sonoff micro) can be turned on (if it was turned off), but the device status returns back - to "off" after a few seconds, while the device turns on normally.

**Comment by formatBCE** [comment]
+, same issue

**Comment by numminorih-git** [comment]
Closed:

1.  this fix: https://github.com/AlexxIT/SonoffLAN/pull/881/files
(https://github.com/AlexxIT/SonoffLAN/pull/881#issuecomment-1176067573)
+
2. this fix:  https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175877543

**Comment by AlexKusnezov** [comment]
@numminorih-git does thta mean a fix will come with an update? I honestly don't feel well about editing those files myself.
I get **This account is already configured** when I try to reconfigure

**Comment by yesuaambros** [comment]
Good morning,
   Yesterday I had this same problem.
  Update following method 2: https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175877543      and the authorization problem is fixed. But the King Art - King Q4 Cover have stopped working, they remain as if they had no connection. Could you guide me how to solve it?

Thank you very much

**Comment by AlexKusnezov** [comment]
> Good morning, Yesterday I had this same problem. Update following method 2: [#887 (comment)](https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175877543) and the authorization problem is fixed. But the King Art - King Q4 Cover have stopped working, they remain as if they had no connection. Could you guide me how to solve it?
> 
> Thank you very much

Same here, I have two King Art - King Q4 Cover, which are not working, but the SANTTON_3 Switch is still working, even without the fix, so don't bother I guess ;)

**Comment by yesuaambros** [comment]
I think it's because the switches I have, camera, etc... are in LAN mode and the KingARTs only support CLOUD, so it's not connecting to the cloud, it doesn't show the error message, but it doesn't connect to the cloud and it's just working locally.

**Comment by arnoldpronobis** [comment]
+, same issue

**Comment by AlexxIT** [comment]
#879
