### ISSUE TITLE
Can't login with working ewelink credentials

### ISSUE THREAD

**Issue by RBSVader** [AlexxIT/SonoffLAN#895]
Reconfigured my HA setup yesterday, had to reinstall all components, but now i can't login within component. Entering correct credentials, checked them on phone ewelink app, but every time i try it in HA i get "sign verification failed". Tried email and phone number, tried to change password. Cloud.py fix didn't work either.

![Screenshot_1](https://user-images.githubusercontent.com/85674708/177720322-13ce7ea4-ecf0-4564-b700-b124f194ce5c.png)

**Comment by BatmanKuhn** [comment]
same here

**Comment by GuyKh** [comment]
Same

**Comment by davidlang42** [comment]
Same (and it happened when I upgraded to home assistant version 2022.7.0)

**Comment by kjelle392** [comment]
Same here after upgrading to 2022.7.0.

**Comment by aljubori** [comment]
Same issue after upgrading to 2022.7.0.

**Comment by olesj33** [comment]
Same here before and after 2022.7.0

**Comment by RoRoo1977** [comment]
Many issues here, not linked to HASS version. Probably the appid has been blacklisted? 
_appid is unauthorized! oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq_

**Comment by gastonmorixe** [comment]
also after upgrading...  "Attention required" "RECONFIGURE"  "This account is already configured"

<img width="364" alt="image" src="https://user-images.githubusercontent.com/637225/177732861-3244f8a0-6ddb-4998-93b3-a389309dc2e0.png">
<img width="457" alt="image" src="https://user-images.githubusercontent.com/637225/177733036-01cfa961-6727-40ef-a692-eb55361c5fea.png">

**Comment by koehntopp** [comment]
Same.

**Comment by jjjyyy01** [comment]
this fix: https://github.com/AlexxIT/SonoffLAN/pull/881/files
(https://github.com/AlexxIT/SonoffLAN/pull/881#issuecomment-1176067573)
plus
this fix: https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175877543

**Comment by RoRoo1977** [comment]
Thanks.. Edited the file with Fix 887. This will work until HACS pushes the update.

**Comment by maartenhbe** [comment]
Thanks! Edited the file with both 881 en 887. Works in 2022.7.0

**Comment by yesuaambros** [comment]
This fix seems to only correct the authorization problem, but the devices work in local mode. Devices that only work via the cloud, for example kingart covers, are also no longer available.

**Comment by mphysic** [comment]
> this fix: https://github.com/AlexxIT/SonoffLAN/pull/881/files ([#881 (comment)](https://github.com/AlexxIT/SonoffLAN/pull/881#issuecomment-1176067573)) plus this fix: [#887 (comment)](https://github.com/AlexxIT/SonoffLAN/issues/887#issuecomment-1175877543)

thanks! apply both fixes and it's work!

**Comment by AlexxIT** [comment]
#879

**Comment by urielz** [comment]
FYI this is unrelated to 2022.7.0. I'm still on 2022.6.x and have the same problem.
