### ISSUE TITLE
POW R2 Energy Meter not available

### ISSUE THREAD

**Issue by cris88** [AlexxIT/SonoffLAN#896]
Hello everyone,

I'm running HA v2022.6.7.
SonoffLan v3.0.5

Since I installed this version of HA and SonoffLan I'm with problems in having the energy stats. The entity is unnavailable.

My config:
![image](https://user-images.githubusercontent.com/1536899/177752143-90b0a1c8-5940-4145-8b9b-ce9dda0ff37a.png)

![image](https://user-images.githubusercontent.com/1536899/177752359-593c1efb-58dd-4370-b4e0-4f9ae2d4197c.png)

Thanks in advance.

**Comment by AlexxIT** [comment]
You need to enable it

**Comment by cris88** [comment]
> You need to enable it

And how can I do that?
