### ISSUE TITLE
Sonoff Bridge Devices Show Unavailable on HA but work on Ewelink after Core Update

### ISSUE THREAD

**Issue by duingsh** [AlexxIT/SonoffLAN#899]
My bridge is a default factory bridge. No flash of Tasmota. Immediately after I performed the latest core update, all bridge devices went to unavailable. I readded them to ewelink and verified they are all working. Went back to HA and still same issue. Please look into and find where the communication is failing.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.1.0
