### ISSUE TITLE
Is it possible to see the "rssi" signal level as an attribute of the sonoff entities ?

### ISSUE THREAD

**Issue by barto64** [AlexxIT/SonoffLAN#90]
Hi,

Maybe I am missing somehting, but I am not bel to read the rssi signal value of the various sonoff devices I use.

Thanks,
Barto

**Comment by AlexxIT** [comment]
Which devices have problems and what device_class do they have?

**Comment by barto64** [comment]
Both are switches, an "Dual R2" and "4CH PRO".

**Comment by AlexxIT** [comment]
I checked my 4ch pro. It does not send information about rssi. Mini sends. And the first sonoff sends. I do not have Dual.

**Comment by barto64** [comment]
In case it helps, this is what Sonoff Cloud download for each of those:

"10006fb002":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5d663d747a58220cb8a98f15","name":"Riego_1","type":"10","deviceid":"10006fb002","apikey":"23effe28-d521-4d8f-8a79-e23c97e5c9d9","extra":{"extra":{"model":"PSF-B04-GL","ui":"四通道插座","uiid":4,"description":"WO1882055","manufacturer":"深圳松诺技术有限公司","mac":"d0:27:00:df:5d:54","apmac":"d0:27:00:df:5d:55","modelInfo":"5a2e1af20cf772f92c342ef9","brandId":"58e5f344baeb368720e25469","staMac":"84:0D:8E:5A:0D:36","chipid":"005A0D36"},"_id":"5c0622d6e1c3c5076381e931"},"params":{"uiActive":60,"timers":[{"mId":"9b11db3a-724e-341e-c00c-11f641733c2d","do":{"outlet":0,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"2d67f67a-bfe4-32b2-c452-989150231e11","do":{"outlet":1,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"97ff4fa8-a000-666e-f1b0-26d7792a1e1f","do":{"outlet":2,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"6060cd52-fe83-7981-3657-49041f9a115d","do":{"outlet":3,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"32845954-68ae-4427-07c8-1f76395a928f","do":{"outlet":0,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"ec1d5078-ab69-311f-89f8-368da491522b","do":{"outlet":1,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"53d10825-b0ac-df07-1817-30b779654220","do":{"outlet":2,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"2ddca846-20a7-6411-395e-a3c0ab697bd2","do":{"outlet":3,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1}],"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"lock":0,"sledOnline":"on","version":8,"pulseWidth":0,"pulse":"off","staMac":"84:0D:8E:5A:0D:36","rssi":-70,"fwVersion":"3.4.0","configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"init":1,"bindInfos":{"alexa":["9d2a2ab1-cea3-40dd-ac3e-9ddb32cc9fc8_26ca1996a20e8bd63617ab272d4eeede1d2d8e32"]}},"createdAt":"2019-08-28T08:38:12.119Z","__v":0,"onlineTime":"2020-05-01T07:59:37.575Z","ip":"88.0.108.2","location":"","offlineTime":"2020-05-01T07:59:30.118Z","tags":{"m_c9d9_jime":"on"},"deviceStatus":"","sharedBy":{"email":"jimenbar@gmail.com","apikey":"23effe28-d521-4d8f-8a79-e23c97e5c9d9","nickname":"Barto","permit":0,"shareTime":1566982158148},"devicekey":"9d2a2ab1-cea3-40dd-ac3e-9ddb32cc9fc8","deviceUrl":"https://eu-api.coolkit.cc/api/detail/5a2e1af20cf772f92c342ef9_en.html","brandName":"Sonoff","showBrand":true,"brandLogoUrl":"https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png","productModel":"4CH Pro","devConfig":{},"uiid":4},

"1000250d42":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5adb71849b26e96c24d854a2","name":"Poza","type":"10","deviceid":"1000250d42","apikey":"23effe28-d521-4d8f-8a79-e23c97e5c9d9","extra":{"extra":{"mac":"d0:27:00:4a:17:d4","apmac":"d0:27:00:4a:17:d5","modelInfo":"597e9c6748b2ec2c22a085e8","brandId":"58e5f344baeb368720e25469","model":"PSF-B04-GL","ui":"双通道插座","description":"WWJG001148","manufacturer":"深圳创易智能系统有限公司","uiid":2,"staMac":"60:01:94:9E:7A:41","chipid":"009E7A41"},"_id":"59f9778d11a9dad75c699e69"},"createdAt":"2018-04-21T17:14:44.111Z","__v":0,"onlineTime":"2020-05-01T08:02:07.076Z","ip":"88.0.108.2","location":"","params":{"bindInfos":{"alexa":[]},"pulseWidth":0,"pulse":"off","init":1,"configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"fwVersion":"3.4.0","switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"controlType":4,"timers":[{"enabled":1,"coolkit_timer_type":"repeat","at":"5 6 * * 1,2,3,4,5,6,0","type":"repeat","do":{"switch":"off","outlet":1},"mId":"511e7310-69b7-99d6-03cf-83f7126d654f"}],"staMac":"60:01:94:9E:7A:41","rssi":-70,"partnerApikey":"ac0bcf13-23b8-1238-a3la-dc315408bcf6","version":8,"sledOnline":"on","lock":0,"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"uiActive":60},"tags":{"ck_channel_name":{"0":"Luz piscina","1":"Depuradora"},"disable_timers":[],"m_c9d9_jime":"on","m_a8ca_jime":"on"},"offlineTime":"2020-05-01T08:02:01.646Z","deviceStatus":"","sharedBy":{"email":"jimenbar@gmail.com","apikey":"23effe28-d521-4d8f-8a79-e23c97e5c9d9","nickname":"Barto","permit":0,"shareTime":1524509426859},"devicekey":"96cff2c2-7213-457a-a9d1-1f0951b95f21","deviceUrl":"https://eu-api.coolkit.cc/api/detail/597e9c6748b2ec2c22a085e8_en.html","brandName":"Sonoff","showBrand":true,"brandLogoUrl":"https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png","productModel":"Sonoff Dual R2","devConfig":{},"uiid":2},

In both the "rssi" appears ...

**Comment by barto64** [comment]
Not sure if this help, but "rssi" appears when the info is downloaded from the cloud.

"10006fb002":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5d663d747a58220cb8a98f15","name":"Riego_1","type":"10","deviceid":"10006fb002","apikey":"23effe28-d521-4d8f-8a79-e23c97e5c9d9","extra":{"extra":{"model":"PSF-B04-GL","ui":"四通道插座","uiid":4,"description":"WO1882055","manufacturer":"深圳松诺技术有限公司","mac":"d0:27:00:df:5d:54","apmac":"d0:27:00:df:5d:55","modelInfo":"5a2e1af20cf772f92c342ef9","brandId":"58e5f344baeb368720e25469","staMac":"84:0D:8E:5A:0D:36","chipid":"005A0D36"},"_id":"5c0622d6e1c3c5076381e931"},"params":{"uiActive":60,"timers":[{"mId":"9b11db3a-724e-341e-c00c-11f641733c2d","do":{"outlet":0,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"2d67f67a-bfe4-32b2-c452-989150231e11","do":{"outlet":1,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"97ff4fa8-a000-666e-f1b0-26d7792a1e1f","do":{"outlet":2,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"6060cd52-fe83-7981-3657-49041f9a115d","do":{"outlet":3,"switch":"off"},"type":"repeat","at":"0 22 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"32845954-68ae-4427-07c8-1f76395a928f","do":{"outlet":0,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"ec1d5078-ab69-311f-89f8-368da491522b","do":{"outlet":1,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"53d10825-b0ac-df07-1817-30b779654220","do":{"outlet":2,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1},{"mId":"2ddca846-20a7-6411-395e-a3c0ab697bd2","do":{"outlet":3,"switch":"off"},"type":"repeat","at":"0 9 * * 1,2,3,4,5,6,0","coolkit_timer_type":"repeat","enabled":1}],"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"lock":0,"sledOnline":"on","version":8,"pulseWidth":0,"pulse":"off","staMac":"84:0D:8E:5A:0D:36","rssi":-70,"fwVersion":"3.4.0","configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"init":1,"bindInfos":{"alexa":["9d2a2ab1-cea3-40dd-ac3e-9ddb32cc9fc8_26ca1996a20e8bd63617ab272d4eeede1d2d8e32"]}},"createdAt":"2019-08-28T08:38:12.119Z","__v":0,"onlineTime":"2020-05-01T07:59:37.575Z","ip":"88.0.108.2","location":"","offlineTime":"2020-05-01T07:59:30.118Z","tags":{"m_c9d9_jime":"on"},"deviceStatus":"","sharedBy":{,"permit":0,"shareTime":1566982158148},"devicekey":"9d2a2ab1-cea3-40dd-ac3e-9ddb32cc9fc8","deviceUrl":"https://eu-api.coolkit.cc/api/detail/5a2e1af20cf772f92c342ef9_en.html","brandName":"Sonoff","showBrand":true,"brandLogoUrl":"https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png","productModel":"4CH Pro","devConfig":{},"uiid":4},

"1000250d42":{"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1},"group":"","online":true,"shareUsersInfo":[],"groups":[],"devGroups":[],"_id":"5adb71849b26e96c24d854a2","name":"Poza","type":"10","deviceid":"1000250d42","apikey":"23effe28-d521-4d8f-8a79-e23c97e5c9d9","extra":{"extra":{"mac":"d0:27:00:4a:17:d4","apmac":"d0:27:00:4a:17:d5","modelInfo":"597e9c6748b2ec2c22a085e8","brandId":"58e5f344baeb368720e25469","model":"PSF-B04-GL","ui":"双通道插座","description":"WWJG001148","manufacturer":"深圳创易智能系统有限公司","uiid":2,"staMac":"60:01:94:9E:7A:41","chipid":"009E7A41"},"_id":"59f9778d11a9dad75c699e69"},"createdAt":"2018-04-21T17:14:44.111Z","__v":0,"onlineTime":"2020-05-01T08:02:07.076Z","ip":"88.0.108.2","location":"","params":{"bindInfos":{"alexa":[]},"pulseWidth":0,"pulse":"off","init":1,"configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"fwVersion":"3.4.0","switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}],"controlType":4,"timers":[{"enabled":1,"coolkit_timer_type":"repeat","at":"5 6 * * 1,2,3,4,5,6,0","type":"repeat","do":{"switch":"off","outlet":1},"mId":"511e7310-69b7-99d6-03cf-83f7126d654f"}],"staMac":"60:01:94:9E:7A:41","rssi":-70,"partnerApikey":"ac0bcf13-23b8-1238-a3la-dc315408bcf6","version":8,"sledOnline":"on","lock":0,"pulses":[{"pulse":"off","width":1000,"outlet":0},{"pulse":"off","width":1000,"outlet":1},{"pulse":"off","width":1000,"outlet":2},{"pulse":"off","width":1000,"outlet":3}],"uiActive":60},"tags":{"ck_channel_name":{"0":"Luz piscina","1":"Depuradora"},"disable_timers":[],"m_c9d9_jime":"on","m_a8ca_jime":"on"},"offlineTime":"2020-05-01T08:02:01.646Z","deviceStatus":"",","permit":0,"shareTime":1524509426859},"devicekey":"96cff2c2-7213-457a-a9d1-1f0951b95f21","deviceUrl":"https://eu-api.coolkit.cc/api/detail/597e9c6748b2ec2c22a085e8_en.html","brandName":"Sonoff","showBrand":true,"brandLogoUrl":"https://eu-ota.coolkit.cc/logo/m6N8zJB0O3EVvhCei6zCPStFeKYKAzSa.png","productModel":"Sonoff Dual R2","devConfig":{},"uiid":2},

**Comment by AlexxIT** [comment]
Will not help :(
You can turn on the debug logs and see what exactly the device sends.

**Comment by barto64** [comment]
Took a look and as you well said it is not there. 

Would it be fair to say that if Itead add this on their API your component would automatically get it ?

If so, I will raise a request to them on Github

большое спасибо

**Comment by AlexxIT** [comment]
Yes, you can raise a request.

**Comment by barto64** [comment]
Will do and thanks again for your super prompt response. If not I may flash to them the ESPHOME firmware which works like a charm :)

**Comment by AlexxIT** [comment]
Check latest beta. Sometimes rssi comes from cloud api
#99
