### ISSUE TITLE
403 error oauthClient enable invalid

### ISSUE THREAD

**Issue by Arasill** [AlexxIT/SonoffLAN#905]
After a reboot I am getting the following errors:

2022-07-10 23:55:22 ERROR (MainThread) [custom_components.sonoff.sonoff_cloud] Login error: {'error': 403, 'msg': 'Sign:oauthClient enable invalid'}
2022-07-10 23:55:22 WARNING (MainThread) [custom_components.sonoff] Can't connect to eWeLink Cloud

I have tried changing the eWeLink account/password without any success.
Setup file is:
sonoff:
    username: test
    password: test
    reload: always
    mode: cloud
    debug: True
    scan_interval: '00:00:10'  # (optional) default 5 minutes
    sensors: [temperature, humidity, power, current, voltage]
    force_update: [temperature, power, voltage, humidity]

**Comment by jnereu** [comment]
Same problem {'error': 403, 'msg': 'Sign:oauthClient enable invalid'}

**Comment by me-2k** [comment]
I had a similar error, appID auth was invalid.
Updating the Sonoff integration in HACS solved my issue.

**Comment by AlexxIT** [comment]
#887
