### ISSUE TITLE
Toggle Night Mode on Sonoff GK-200MP2-B Camera

### ISSUE THREAD

**Issue by Saboteur777** [AlexxIT/SonoffLAN#906]
Is it possible to toggle night mode on the Sonoff GK-200MP2-B Camera using `sonoff.send_command`?

**Comment by AlexxIT** [comment]
No

**Comment by Saboteur777** [comment]
I asked because this option became available in eWeLink, so I thought something changed regarding this feature.

**Comment by AlexxIT** [comment]
The camera controls are very different from all other ewelink devices. It takes a lot of time to support it. There is a separate issue about full support for this camera. #67

**Comment by Saboteur777** [comment]
Thanks for the explanation!
