### ISSUE TITLE
Sonoff switches unavailable 

### ISSUE THREAD

**Issue by RMLReis** [AlexxIT/SonoffLAN#907]
I have 31 Sonoff switches configured on homeassistant.
13 of this switches became unavailable at 7:00 am on 6th July on homeassistant.
All 31 Sonoff switches are working find on ewelink.
The only common issue is that the 13 switches that became unavailable are connect on the same WiFi router the other switches are in a different WiFi router.
But because al 31 sonoff switches work find with ewelink. I assume that the problem is with homeassistant and not the WiFi router.

**Comment by whalik** [comment]
Mine are erratically going unavailable and coming back online since July 7th updates. Running the latest versions of HA on Pi and HACS Sonoff LAN. My other non-Sonoff switches don't have any issues.
![2022-07-10 (4)](https://user-images.githubusercontent.com/49659732/178314921-56e14257-1bb4-463e-850c-b649c9357fd0.png)

**Comment by shifuoogway** [comment]
Same problem here with the latest 3.1.0. There are 15 sonoff switches in my system. The wifi network resets overnight and  in the morning 2 or 3 random switches are sometimes unavailable. But they are available in ewelink and become available in HA again after toggling using ewelink.

**Comment by whalik** [comment]
> Mine are erratically going unavailable and coming back online since July 7th updates. Running the latest versions of HA on Pi and HACS Sonoff LAN. My other non-Sonoff switches don't have any issues. ![2022-07-10 (4)](https://user-images.githubusercontent.com/49659732/178314921-56e14257-1bb4-463e-850c-b649c9357fd0.png)

This problem was resolved after increasing the DHCP server lease time from 1 minute to 30 minutes or higher. Don't know why this was problematic only for these switches.

**Comment by sleal77** [comment]
Same problem here:
I have 2 houses in HA. When sonoff is online in 1 home, it is offline in the other

**Comment by shifuoogway** [comment]
> > Mine are erratically going unavailable and coming back online since July 7th updates. Running the latest versions of HA on Pi and HACS Sonoff LAN. My other non-Sonoff switches don't have any issues. ![2022-07-10 (4)](https://user-images.githubusercontent.com/49659732/178314921-56e14257-1bb4-463e-850c-b649c9357fd0.png)
> 
> This problem was resolved after increasing the DHCP server lease time from 1 minute to 30 minutes or higher. Don't know why this was problematic only for these switches.

My unavailable problem is different from yours. DHCP lease time in my network and typically is 7 days. DHCP is initiated by a client rather than the router at client start up then refreshed at half the lease time so 1 minute is very short. Glad you found the solution for your situation.

**Comment by RMLReis** [comment]
I have the following warnings on my log.
Not sure if it is related but it seems that started at the same time as the unavailability problem.

Logger: homeassistant.components.number
Source: components/number/__init__.py:462
Integration: Number (documentation, issues)
First occurred: 13:25:22 (15 occurrences)
Last logged: 13:25:22

Entity sonoff.sonoff_100067fe11_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_1000b681c3_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_1000b6bb3a_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_1000b5f9f1_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_10008963e3_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.

Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number (documentation, issues)
First occurred: 13:25:18 (3 occurrences)
Last logged: 13:25:18

custom_components.sonoff.number::XNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.sonoff.number::XPulseWidth is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

**Comment by GuyKh** [comment]
#935

**Comment by RMLReis** [comment]
It is now all working again.
Thank you GuyKh.

**Comment by AlexxIT** [comment]
Is problem still actual?

**Comment by shifuoogway** [comment]
The problem has not been observed for sometime now. Not sure what did it as the installation is kept up to date so there has been a few updates since.  Thanks for your help. 


On 3 September 2022 5:51:24 am AEST, Alex X ***@***.***> wrote:
>Is problem still actual?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/AlexxIT/SonoffLAN/issues/907#issuecomment-1235846677
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TawfikDaim** [comment]
> It is now all working again. Thank you GuyKh.

Hello, I have same problem of sonoff devices become unavailable in HA, I was not able to understand what was the solution, I followed the link [GuyKh](https://github.com/GuyKh) commented [on Aug 4, 2022](https://github.com/AlexxIT/SonoffLAN/issues/907#issuecomment-1204948988)
https://github.com/AlexxIT/SonoffLAN/pull/935 but was not able to figure out, 
can you please explain what is the fix?

**Comment by heidricha** [comment]
It hasn't been a problem for me for quite a long period, but recently it is a serious issue again. Almost every day I have got alerts about the switches getting offline. I set up a "reload config" action earlier when the issue originally came up, but it was sleeping for a while. Now it is getting more and more annoying again. 
I use the switches for heating, so it is kind of important to have a stable connection, but currently, I cannot tell about the effect of the issue, since the heating is turned off

**Comment by RMLReis** [comment]
I am now controlling sonoff devices with sonoff integration on HA and it was working well up until upgrading HA core from 2023.6.3 to 2023.7.1 on 7th July.
With HA 2023.7.1 I lost connection with 9 devices.
I assume the problem is with HA 2023.7.1

**Comment by TawfikDaim** [comment]
From what I have seen not all versions of HA are compatible with the version of integration

So the easiest solution I found is to check compatibility and stick with these two versions and be careful when doing upgrades

Regards, Tawfik<https://aka.ms/o0ukef>
________________________________
