### ISSUE TITLE
TH Elite (THR316D) - not display humidity sensor information

### ISSUE THREAD

**Issue by mobizon16** [AlexxIT/SonoffLAN#908]
Hello. Sonoff THR316D does not display humidity sensor information
![555](https://user-images.githubusercontent.com/76066304/179062047-30ab6df2-d478-4ad3-b246-c7f7ed1dad73.jpg)
.

**Comment by omenek159** [comment]
#876

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/876#issuecomment-1184172702

**Comment by AlexxIT** [comment]
Fixed in v3.2.0
