### ISSUE TITLE
Sonoff B1 Bulb

### ISSUE THREAD

**Issue by klimisa** [AlexxIT/SonoffLAN#91]
Will it work with Sonoff B1 Bulb?
I can see the device in the .sonoff.json but it's not in the stage.
I'm new to home assistant and home automation.

**Comment by AlexxIT** [comment]
#31

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by klimisa** [comment]
I can confirm it's shown in the state now. Thanks. ❤
Q: Is it working locally now or through the internet?

BTW I'm keen to help if you give me a quick how you code works.

**Comment by AlexxIT** [comment]
2nd firmware works olny through the internet. It is displayed in the info window.
Does it can change the brightness and color?

**Comment by klimisa** [comment]
I've not tried it further. I'll let you know when I do. I have to understand how home assistant work first. It's all new to me at the moment. 😉

**Comment by klimisa** [comment]
That's what I'm seeing.

### State
![image](https://user-images.githubusercontent.com/1973636/81726234-b9672400-948f-11ea-999e-2e47cd810258.png)
### Devices
![image](https://user-images.githubusercontent.com/1973636/81726289-d0a61180-948f-11ea-898f-1fa4bbeb8732.png)

**Comment by AlexxIT** [comment]
Write to me on Telegram or Discord (AlexxIT#0816). And share this device to my acc.

**Comment by AlexxIT** [comment]
Supported

![download-12](https://user-images.githubusercontent.com/511909/81987332-13a7e680-9642-11ea-9ee1-3fdfaaf1e593.png)
