### ISSUE TITLE
Support for Phillips Hue LED Lights

### ISSUE THREAD

**Issue by mirekjany** [AlexxIT/SonoffLAN#911]
Hello there, is it possible to add support for ZigBee Phillips Hue LED Lights?

I've successfully added my ZigBee Hue dimmable Light (9.5W) to Sonoff ZigBee bridge and it's working properly inside eWelink app - I can dim and turn it on/off.

However it's not working properly inside HA using the SonoffLAN integration. I cannot see brightness control of the entity and its state is not resolving to on/off - it's randomly either on or off. Nor is an event being registered upon firing the switch.

It would be nice to get it working. Feel free to ask for any information you might need. Thanks.

**Comment by AlexxIT** [comment]
Can you provide device diagnostics?
