### ISSUE TITLE
Integration log error "using deprecated NumberEntity features"

### ISSUE THREAD

**Issue by Claudio1L** [AlexxIT/SonoffLAN#923]
Logger: homeassistant.components.number
Source: components/number/__init__.py:462
Integration: Number (documentation, issues)
First occurred: 22:04:21 (17 occurrences)
Last logged: 22:04:21

Entity sonoff.sonoff_10012573fa_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_100140b3bf_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_100140aa27_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_1000f98f74_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
Entity sonoff.sonoff_1000fa6945_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.

**Comment by AlexxIT** [comment]
#897
