### ISSUE TITLE
Failed to set up: sign verification failed

### ISSUE THREAD

**Issue by JossPer0** [AlexxIT/SonoffLAN#924]
Everything seems to be working but am getting a the above message, there is a reconfigure option "Attention required". I sign in there and then get the message "This account is already configured.
![Screenshot 2022-07-27 153147](https://user-images.githubusercontent.com/37881812/181259715-65788de3-830f-43b8-8b92-e5bd63fd4ca0.png)

**Comment by pops3449** [comment]
having the same issue

**Comment by vitoralvimb** [comment]
Same issue here!

**Comment by joelhauxwell** [comment]
Same issue here

**Comment by JGBlignault** [comment]
Same for me

**Comment by VdR1960** [comment]
And me

**Comment by NMichas** [comment]
Same here, note this is a duplicate of #878.

**Comment by pops3449** [comment]
After updating all, it's working fine

**Comment by VdR1960** [comment]
Same here. Update HA core and OS, now ok.

**Comment by joelhauxwell** [comment]
> Same here. Update HA core and OS, now ok.

My system is all up to date - I still have the issue

**Comment by Tchitan** [comment]
Same as above

**Comment by maxcim32** [comment]
Same as above - have two eWelink accounts in the same HA, one has this sign in problem the other does not. Most devices continue to work bur Zigbee may have a problem, still investigating.

**Comment by zheka24** [comment]
Since yesterday we have another problem. It is password error

**Comment by AlexxIT** [comment]
Can't reproduce problem on latest integration version.
Please reopen the issue if there are still any problems.
