### ISSUE TITLE
Cannot connect to host eu-apia.coolkit.cc:443 ssl:default [None]

### ISSUE THREAD

**Issue by y306702588** [AlexxIT/SonoffLAN#927]
![image](https://user-images.githubusercontent.com/11454725/181663506-dffa0d20-2a3b-4dc0-b35d-27dda9799635.png)

**Comment by AlexxIT** [comment]
Well. Your Hass server can't connect to ewelink cloud. You need to look for a problem with your network and Internet settings

**Comment by y306702588** [comment]
> Well. Your Hass server can't connect to ewelink cloud. You need to look for a problem with your network and Internet settings


OK, let me check my network
