### ISSUE TITLE
Invalid Configuration

### ISSUE THREAD

**Issue by drk-geek** [AlexxIT/SonoffLAN#93]
I installed HACS with instructions frm https://hacs.xyz/docs/installation/manual_cli and add CUSTOM REPOSITORIES [integration] AlexxIT/SonoffLAN
screenshots of errors are attached
![Screenshot_2020-05-05_01-54-41](https://user-images.githubusercontent.com/63916817/81012870-b8bd0500-8e73-11ea-9d99-dd19b0096a4b.png)
![Screenshot_2020-05-05_01-55-30](https://user-images.githubusercontent.com/63916817/81012892-bf4b7c80-8e73-11ea-9e3c-00b6fa1dc1a2.png)
![file](https://user-images.githubusercontent.com/63916817/81013511-ae4f3b00-8e74-11ea-94f4-9b296d551092.png)

**Comment by AlexxIT** [comment]
Look at the logs. There the error is described in more detail.

**Comment by drk-geek** [comment]
2020-05-05 01:06:03 ERROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Unable to import component: No module named 'Crypto'
![log1](https://user-images.githubusercontent.com/63916817/81084328-25d1a880-8f0f-11ea-88ed-cfb9e3def94b.png)

**Comment by AlexxIT** [comment]
Do you use HA in venv?

**Comment by drk-geek** [comment]
arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
os_version | 4.19.97-v7+
python_version | 3.7.3
timezone | Asia/Karachi
version | 0.109.2
virtualenv | true

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/SonoffLAN/releases/tag/v1.10.4

**Comment by drk-geek** [comment]
Thanks @AlexxIT it works now!!
