### ISSUE TITLE
 The "sonoff" devices of a remote network are available in ewelink but not in home assistant (after 3.0 update)

### ISSUE THREAD

**Issue by antoniofainella** [AlexxIT/SonoffLAN#930]

**Comment by AlexxIT** [comment]
Have you read the new README carefully?

**Comment by EvilItalianK** [comment]
I think I have the same issue, the devices are greyed out and shown as unavailable, i do not see a reason why in the logs and despite reading the README in the repo i don't see anything that tells why - can you clarify what part of the readme are you referring to?

**Comment by AlexxIT** [comment]
@DennyBevilaqua you need to read docs about problems with LAN

@antoniofainella do you have multiple Homes in ewelink app?

@EvilItalianK you need to provide any device or integration diagnostics

**Comment by EvilItalianK** [comment]
Mine decided to go back to work after the latest HA update

**Comment by AlexxIT** [comment]
You have problems with internet. And non of your device works locally. So both cloud and local not available

**Comment by EvilItalianK** [comment]
What is the problem exactly tho?

All outbound connections are allowed and this server is hosted in a datacenter, I'd not expect network issues and testing outbound connections seems to work fine

**Comment by AlexxIT** [comment]
`Cannot connect to host eu-dispa.coolkit.cc:443`, 27 times. Component can't do anything with this.

**Comment by dezza** [comment]
@AlexxIT which devices does not work local? I suspected this was an issue.

**Comment by AlexxIT** [comment]
`"localtype": null` means device doesn't work locally.
Please reopen the issue if it is still relevant
