### ISSUE TITLE
No more 'Debug page' as updated Core to 2022.8.0

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#936]
Just updated HA Core to 2022.8.0.

No more Sonoff integration Debug page available in Setting -> System -> Repairs -> System Information...
Debug checked in integration config.

See no related logs entries for Core or Supervisor.

![image](https://user-images.githubusercontent.com/15225823/182857967-c2de777b-2d6e-495a-8a5d-5cec6feb71e8.png)

![image](https://user-images.githubusercontent.com/15225823/182857842-78de98f4-1a07-41ea-bbdc-007fbc00e512.png)

**Comment by Masterz69** [comment]
Tried sequence: disable Integration debug in GUI, restart HA Core, enable debug in GUI.
Still no 'Debug page' available.

Removed ```debug: true``` from yaml config, do same as before ^^^ - no changes, no Debug page.

**Comment by Viper7000** [comment]
No debug page in core 7.7 and in core 8.7 too
![12](https://user-images.githubusercontent.com/96679981/188262092-824f1969-d9fe-4bca-9f8e-426753a14c9e.png)

**Comment by AlexxIT** [comment]
Place was changed.
