### ISSUE TITLE
sonoffLan lost connection to home assistant completely

### ISSUE THREAD

**Issue by Nerijus1984** [AlexxIT/SonoffLAN#94]
Hi I'm new to home assistant and was installing it with **Discord DrZzs - https://discord.me/drzzs** instructions on youtube once I've added a new repository and integration of SonoffLAN my home assistant lost connection completely. I've done everything as it said but.... Can't even restart the home assistant server.

**Comment by Nerijus1984** [comment]
sorted out restarting the virtual machine, now once I've done next steps I cant find any of my sonoff devices to add..

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues/84#issuecomment-623790707

**Comment by Nerijus1984** [comment]
Thanks  @AlexxIT  I'll  have a look tomorrow.  Sorry for opening issues. I'm  very new to the HA.
