### ISSUE TITLE
RF Motion Sensor timeout

### ISSUE THREAD

**Issue by camui-alexandru** [AlexxIT/SonoffLAN#940]
The motion sensor stays too long active, after motion detected. How can I decrese the timeout ? The sensors are automatically discovered by the integration, so I dont have them in the configuration.yaml.

**Comment by camui-alexandru** [comment]
![sonoff](https://user-images.githubusercontent.com/62066937/183052052-5493b6fc-2460-46b7-9e8d-c0da6a557ad6.png)

**Comment by AlexxIT** [comment]
Try to search timeout word in the docs.

**Comment by jssting** [comment]
I'm having the same issue with the binary sensors discovered by the integration staying on for two minutes. I have checked the eweLink side and it's not caused there are it picks up the state changes within 5-10 seconds. as we cannot control these binary sensors given they are automatically populated by the eweLink integration, is there a way to reduce the timeout in a file without needing to change code. It is not currently available on the sensor configuration or the eweLink integration configuration.

**Comment by jssting** [comment]
I have found the issue in the binary_sensor.py file under the XRemoteSensor function the standard timeout is set as 120 seconds. I changed it to 15 seconds, and restarted Hassio and it now times out in 15 seconds.

```
# noinspection PyAbstractClass
class XRemoteSensor(BinarySensorEntity, RestoreEntity):
    _attr_is_on = False
    task: asyncio.Task = None

    def __init__(self, ewelink: XRegistry, bridge: dict, child: dict):
        self.ewelink = ewelink
        self.channel = child["channel"]
        self.timeout = child.get("timeout", 120)
```
![image](https://user-images.githubusercontent.com/55811693/188251036-ee486077-2e19-4095-b8b1-c485b4ba121b.png))

**Comment by AlexxIT** [comment]
Nice. You can found timeout in sources, but can't find timeout in docs

<img width="857" alt="image" src="https://user-images.githubusercontent.com/511909/188254472-0676bb5c-1fbd-4742-ad50-436d216942ec.png">

**Comment by jssting** [comment]
Given it's a direct integration now I don't have manually created templates for the sensors any more, it's all done via UI

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlexxIT** [comment]
Anyway, timeout can be changed exact that way.
