### ISSUE TITLE
POW Elite (POWR320D) data scaled by 10 / 100 factor

### ISSUE THREAD

**Issue by fortunatomarzagalli** [AlexxIT/SonoffLAN#942]
Just installed 6 POWR320D. All show same issue:

Current (A) scaled up by 100
Power (W) scaled up by 100
Voltage (V) scaled up by 100
![Sonoff image](https://user-images.githubusercontent.com/91031894/183104853-399e513c-3a57-41aa-a28b-5c2bc0eb7f64.png)

Image show current reading, obviously right data should be 9.4 A, 1964 W, 211.3 V

Thanks for any advice on that

**Comment by riddle-stc** [comment]
Same behavior for the POWR316D

**Comment by popstas** [comment]
How to install it? I have only one working switch from POWR320D, and no sensors:

![image](https://user-images.githubusercontent.com/3027126/185757714-109b8f5a-9253-489a-b24e-9a98bfbd8e64.png)

**Comment by shift-del1** [comment]
> How to install it? I have only one working switch from POWR320D, and no sensors:
> 
> ![image](https://user-images.githubusercontent.com/3027126/185757714-109b8f5a-9253-489a-b24e-9a98bfbd8e64.png)

The same here [link](https://github.com/AlexxIT/SonoffLAN/issues/949) , so I'm also interested in the solurion.

**Comment by szunyog25** [comment]
> 

Did you set up sensors in configuration.yaml?
for example:
![image](https://user-images.githubusercontent.com/67189977/185852099-f850b708-9727-4924-9b53-9d3741060f60.png)
If you didn't, write in the power, current, voltage.

**Comment by shift-del1** [comment]
> > 
> 
> Did you set up sensors in configuration.yaml? for example: ![image](https://user-images.githubusercontent.com/67189977/185852099-f850b708-9727-4924-9b53-9d3741060f60.png) If you didn't, write in the power, current, voltage.

I only used the config flow, not the YAML. It is a bit weird it has to be set up manually in case of an energy monitoring device, but I will give it a go once I arrived home, thank you.
