### ISSUE TITLE
NS panel version 1.3.1

### ISSUE THREAD

**Issue by kenge1967** [AlexxIT/SonoffLAN#945]
Hi
I've updated my NS panel to 1.3.1, after that I,ve got som issues with the switches in Home Assistant, they are a little bit unresponsive, and switch in the GUI flips back to off after turning on.
And when I look in devices in HA so can I see tha that NS panel has version 1.2.1 but in reality it has 1.3.
![NS Panel](https://user-images.githubusercontent.com/57861452/183643325-c678e2c8-5d1a-4617-bc5d-75905f644029.JPG)

**Comment by kenge1967** [comment]
I've got this message in the log:
custom_components.sonoff.number::XNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by sipimokus** [comment]
Interesting, it's works fine for me. (v3.1.0)
Try reloading the integration settings [Integrations -> Sonoff -> ... -> Reload], maybe it will help.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/1633489/184242531-b71a8cba-c8cf-4439-9ca9-941e1b8a1f40.png">

XNumber issue here: #897

**Comment by AlexxIT** [comment]
Show device diagnostics

**Comment by kenge1967** [comment]
},
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.1.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "3871c0b",
    "cloud_auth": false,
    "config": null,
    "options": {},
    "errors": [],
    "device": {
      "uiid": 133,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "pulses": [
          {
            "pulse": "off",
            "width": 1000,
            "outlet": 0
          },
          {
            "pulse": "off",
            "width": 1000,
            "outlet": 1
          }
        ],
        "switches": [
          {
            "switch": "off",
            "outlet": 0
          },
          {
            "switch": "off",
            "outlet": 1
          }
        ],
        "configure": [
          {
            "startup": "stay",
            "outlet": 0
          },
          {
            "startup": "stay",
            "outlet": 1
          }
        ],
        "lock": 0,
        "fwVersion": "1.2.1",
        "temperature": 25,
        "humidity": 50,
        "tempUnit": 0,
        "HMI_outdoorTemp": {
          "current": 19,
          "range": "16,24"
        },
        "HMI_weather": 7,
        "cityId": "314929",
        "dst": 1,
        "dstChange": "2022-10-30T01:00:00.000Z",
        "geo": "59.314,18.069",
        "timeZone": 1,
        "HMI_resources": [
          {
            "ctype": "idle"
          },
          {
            "ctype": "idle"
          },
          {
            "ctype": "idle"
          },
          {
            "ctype": "idle"
          },
          {
            "ctype": "idle"
          },
          {
            "ctype": "idle"
          },
          {
            "ctype": "idle"
          },
          {
            "ctype": "idle"
          }
        ],
        "weather": 1,
        "tempRange": "-1.9,4",
        "only_device": {
          "ota": "success",
          "ota_fail_reason": 0
        },
        "tempCorrection": 1,
        "reset_reason": "ESP_RST_SW",
        "value": 3
      },
      "model": "NSPanel",
      "online": true,
      "localtype": "multifun_switch",
      "deviceid": "100156ad08"
    }
  }
}

**Comment by AlexxIT** [comment]
You have empty config. It's very strange...

**Comment by kenge1967** [comment]
Ok, I've had some issues even with the integration from Sonoff/ewelink as well so I think the problem is in the NS-panel
