### ISSUE TITLE
Sonoff THR316D - Humidity Sensor Unknown

### ISSUE THREAD

**Issue by denzelm5** [AlexxIT/SonoffLAN#947]
Good Day,

I have linked a Sonoff THR316D to HA. The temperature and rely is fine but the Humidity Sensor is Unknown. 
HA :  2022.8.4
![sonoff](https://user-images.githubusercontent.com/57428868/184531496-22fe27e3-7262-4466-b490-28511b3dbb8a.PNG)

**Comment by Masterz69** [comment]
If You want to fix immediately - see what to change in https://github.com/AlexxIT/SonoffLAN/issues/876#issuecomment-1184172702.
Otherwise PR already placed to fix in next verison.
