### ISSUE TITLE
Sonoff Door Sensor SNZB-04 

### ISSUE THREAD

**Issue by fahimi73** [AlexxIT/SonoffLAN#948]
Hi,
This device showing UNAVAILABLE 
<img width="791" alt="Screenshot 2022-08-15 at 2 54 06 PM" src="https://user-images.githubusercontent.com/81543657/184589937-c1bf118c-cd4e-4fc9-9b38-12991805af8b.png">
Not working anymore.
Please advice.
Thanks

**Comment by sipimokus** [comment]
I think in this case the SNZB-04 is discharged and the batteries need to be replaced, or [Integrations -> Sonoff -> ... -> Reload] maybe it will help.

**Comment by fahimi73** [comment]
> I think in this case the SNZB-04 is discharged and the batteries need to be replaced, or [Integrations -> Sonoff -> ... -> Reload] maybe it will help.

But in the ewelink its working and do function where it can detect open and closed...not working in HA

**Comment by AlexxIT** [comment]
Do you have other zigbee devices? Do they work in Hass?

**Comment by fahimi73** [comment]
> Do you have other zigbee devices? Do they work in Hass?

I solved th issue. I disabled and reinstall the plugin.

**Comment by AlexxIT** [comment]
Ok
