### ISSUE TITLE
POW Elite (POWR316D FW1.0.2) entity has 4 switches, but no power metering sensors

### ISSUE THREAD

**Issue by shift-del1** [AlexxIT/SonoffLAN#949]
1. Systeam Health page:
Sonoff
Version	3.1.0 (3871c0b)
Cloud devices online	1 / 2
Local devices online	1 / 1
Debug page	–

2. no warning or error in logs
3. no debug page despite it is enabled in the integration configuration
4. similar issue, but unknown solution:
https://github.com/AlexxIT/SonoffLAN/issues/820

![Screenshot_2022-08-15-16-58-52-625_io homeassistant companion android](https://user-images.githubusercontent.com/63366470/184660035-9535d979-12f2-46e8-bf93-a2c1dc508bad.jpg)

Diagnostics will be attached soon.

**Comment by AlexxIT** [comment]
#942
