### ISSUE TITLE
SONOFF T4EU1C - 1 Gang EU Wi-Fi Smart Single Wire Wall Switch shorted

### ISSUE THREAD

**Issue by smeg1** [AlexxIT/SonoffLAN#95]
I have 3 T4EU1C with the hardware hack installed been working fine for some time, I purchased 10 T4EU1C and setup in ewelink and home assistant and all working as expected from home assistant and ewelink, last night I needed to add the 10 new devices to apple HomeKit via homeassistant which was all ok they added to HomeKit fine, I pressed the bedroom switch from HomeKit and it blow the T4EU1C light bulb flashed and blue wifi and blue switch on T4EU1C went out so looks like thats now dead. I don't know if this of important, I delete all the switches from HomeKit just to be on the safe side.
T4EU1C is on the latest firmware 3.4.0 its now ghosted in home assistant and same in ewelink

**Comment by AlexxIT** [comment]
I don't think it's because of HA. Perhaps the switch is still operational. Need to try with another bypass or lamps.

I use 8 switches without zero line for a long time (with ewelink firmware):
https://www.aliexpress.com/item/33016227381.html

**Comment by smeg1** [comment]
going to remove tomorrow and test will update, thanks just thought you should know about it

**Comment by GarethC77** [comment]
I have 1 of these TX light switches and the same has happened. Smells like it's the relay last of the switch and not the touch panel but not been able to test.
