### ISSUE TITLE
pulseWidth

### ISSUE THREAD

**Issue by white1983** [AlexxIT/SonoffLAN#952]
Entity sonoff.sonoff_10004e47e4_pulseWidth (<class 'custom_components.sonoff.number.XPulseWidth'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom integration author.

**Comment by Merril-r** [comment]
Thanks for reporting. I also saw that in my logs and did not get around to reporting it.

**Comment by sipimokus** [comment]
Duplicate issue: https://github.com/AlexxIT/SonoffLAN/issues/897
