### ISSUE TITLE
DUALR3 Lite - continuous log records

### ISSUE THREAD

**Issue by Masterz69** [AlexxIT/SonoffLAN#956]
Example:
```
"100171fd9d => Local4 | {'sledOnline': 'on'} <= {'sequence': '1661027040000', 'seq': 60, 'error': 400, 'encrypt': True}",
```
[sonoff-a0656de0df0bb579aa4ece0459ab70e2-OverHang Entry-6e39fd01d7a396d47a5647178119c3c8.json.txt](https://github.com/AlexxIT/SonoffLAN/files/9387990/sonoff-a0656de0df0bb579aa4ece0459ab70e2-OverHang.Entry-6e39fd01d7a396d47a5647178119c3c8.json.txt)

**Comment by Masterz69** [comment]
BTW DUALR3 Lite behaves strange.
Sometimes it become unavailable, sometimes state in HA not the same as actual state, like message not received by HA.

Sharing device with You, may be it can help somehow.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
