### ISSUE TITLE
S31 not reporting power unless eWeLink app open

### ISSUE THREAD

**Issue by broyuken** [AlexxIT/SonoffLAN#957]
not sure when exactly this started, but in the last couple of HA releases my S31TPB no longer report power usage changes. If I open the eWeLink app, then the power changes show up in the app and also reflect in HA. Nothing in the logs from what I can see.

**Comment by broyuken** [comment]
I solved this by creating the automation in the main page to update the switch entity every 10 seconds. Now I get nice fast updates again

**Comment by coolspot18** [comment]
Hi @broyuken, I noticed my S31s not updating as well - can you explain a bit more about what you did?

Thanks.

**Comment by broyuken** [comment]
alias: "☑️ Misc: Update Sonoff Sensors"
description: ""
trigger:
  - platform: time_pattern
    seconds: /10
condition: []
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - switch.washing_machine_switch
        - switch.coffee_maker_plug
mode: single
