### ISSUE TITLE
Pulse mode

### ISSUE THREAD

**Issue by neives** [AlexxIT/SonoffLAN#96]
I have one Sonoff Mini, and I would like to use it to open my garage door, connecting it to gate controller.
The correct way to send signal to my gate controller is send a 24V pulse.

Whith ESPHome firmware it has a "momentary switch" option:

"switch:
  - platform: gpio
    pin: 25
    id: relay
  - platform: template
    name: "Gate Remote"
    icon: "mdi:gate"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay"

Is there any way to configure it with stock firmware?

**Comment by AlexxIT** [comment]
Yes! You can enable **inching** in eWeLink mobile app.
This works with the component. I checked with my mini
