### ISSUE TITLE
New Pow r3

### ISSUE THREAD

**Issue by VictoriousCupid** [AlexxIT/SonoffLAN#960]
Sonoff has a few pow r3 versions. I have the pow r316. They can be used but the data is a bit wrong. 

It shows 4 switches. 
![image](https://user-images.githubusercontent.com/1165160/186001457-f486ee28-ac96-4c51-9a9e-b61446c248b1.png)

the sensors are of by a factor of 100 or 10

![image](https://user-images.githubusercontent.com/1165160/185990741-15a0233e-f017-4439-8bba-a4283ece08e0.png)

current should be 0.68
power should be 121.97
voltage should be 227.18
Stamac should be something

LED and RSSI are fine

@AlexxIT I can share my pow r316 with you if that helps

**Comment by VictoriousCupid** [comment]
note: I see that the original POW R3 is not on the list of tested devices. I have several of these and they work identically to the POW R2 of which I have 1.
This issue is regarding the POW R316 and presumingly the POW R320D (I might get one of these soon.)

**Comment by shift-del1** [comment]
Did you enable the sensors via configuration.yaml? How do I know what are the names of the sensors? Thank you.

**Comment by VictoriousCupid** [comment]
> Did you enable the sensors via configuration.yaml? How do I know what are the names of the sensors? Thank you. 

I did. You can find the sensors (all the entities) in the device.

**Comment by shift-del1** [comment]
> > Did you enable the sensors via configuration.yaml? How do I know what are the names of the sensors? Thank you.
> 
> I did. You can find the sensors (all the entities) in the device.

Thanks for your confirmation. What do you mean I can find the entities in the device? I'm curious about the names I have to put in confirmation.yaml. How about the energy sensor, which is available via cloud only (as stated in the description)?

**Comment by AlexxIT** [comment]
#942

**Comment by AlexxIT** [comment]
That's because I haven't made a change to the list in 2 or 3 years.
Almost any relay will be supported without integration modifications.
