### ISSUE TITLE
Controlling S31 at different location with Home Assistant

### ISSUE THREAD

**Issue by PerfectBake420** [AlexxIT/SonoffLAN#963]
I have home assistant running on my main office. I have 2 satellite offices that are connected through vpn. I have this integration up and running and it appears to work locally at my main office. When I take smart plugs to a different location they do not follow the automation. I can not manually turn them on and off through home assistant but I can through the Ewelink app. Any thoughts of how I can make this work?

In HA, the error states;

Unable to find referenced entities switch.10016f291a
11:51:53 AM - (WARNING) helpers/service.py

**Comment by AlexxIT** [comment]
Do you reset devices for new wifi network of new ewelink account?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
