### ISSUE TITLE
Sonoff S31 power consuption not showing in energy tab 

### ISSUE THREAD

**Issue by DJAMIRSAM** [AlexxIT/SonoffLAN#965]
Device does not show here
![image](https://user-images.githubusercontent.com/78499690/187351048-a08e6148-6910-4fc9-b47a-c3080c056eba.png)
Acording to HA docs the integration need to let ha know that energy is and option
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by AlexxIT** [comment]
Show screen of Device page which you want to see here.

**Comment by VimalO** [comment]
@DJAMIRSAM you have to create a statistics sensor. Click on the link "Learn more about statistics"
Basically energy tab needs a cumulative sensor.

**Comment by coolspot18** [comment]
> Show screen of Device page which you want to see here.

This error shows up on the Energy Wizard, no Sonoff devices show up:

![image](https://user-images.githubusercontent.com/5160442/198517467-10734cdb-62a7-493b-bcde-f5b5049ed3db.png)

**Comment by DJAMIRSAM** [comment]
> @DJAMIRSAM you have to create a statistics sensor. Click on the link "Learn more about statistics"
> Basically energy tab needs a cumulative sensor.

This resolved my issue

**Comment by coolspot18** [comment]
> > @DJAMIRSAM you have to create a statistics sensor. Click on the link "Learn more about statistics"
> > Basically energy tab needs a cumulative sensor.
> 
> This resolved my issue

Do you have an example of your configuration?

**Comment by coolspot18** [comment]
For future reference, instructions are here:

https://github.com/AlexxIT/SonoffLAN/issues/562

Add a platform integration to your sensors.
