### ISSUE TITLE
After a while all cloud devices are lost

### ISSUE THREAD

**Issue by aguswiss** [AlexxIT/SonoffLAN#968]
Hi there
I have the problem that after a few days all cloud devices are lost and I need to restart to get them back.
I lately integrated 3x THR320D. I didn't do the change in sendor.py to get the humidity yet and I don't think it correlates with this integration

I always do all the updates and I'm using the latest of everything.

I am grateful for every hint

thanks

**Comment by AlexxIT** [comment]
You may enable debug logs and check there. Maybe the session is over.

**Comment by aguswiss** [comment]
> You may enable debug logs and check there. Maybe the session is over.

Many thanks for your quick response. unfortunately I don't know how to enable the debug mode. I know it's an option but I can't find the syntax. Sorry.
thanks for support.

**Comment by aguswiss** [comment]
> You may enable debug logs and check there. Maybe the session is over.

i found the "debug enable" lets see if there is a entry when it disconnects.

**Comment by aguswiss** [comment]
I think this is the error causing the problem

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:317
Integration: Sonoff (documentation, issues)
First occurred: 06:21:31 (1 occurrences)
Last logged: 06:21:31

Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 317, in connect
    if resp["error"] != 0:
KeyError: 'error'

**Comment by aguswiss** [comment]
again:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.sonoff.core.ewelink.cloud
Source: custom_components/sonoff/core/ewelink/cloud.py:317
Integration: Sonoff (documentation, issues)
First occurred: 18:21:39 (1 occurrences)
Last logged: 18:21:39

Cloud WS exception
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 317, in connect
    if resp["error"] != 0:
KeyError: 'error'

**Comment by AlexxIT** [comment]
Should be fixed #964
