### ISSUE TITLE
Local device discovery

### ISSUE THREAD

**Issue by ashwinikalantri** [AlexxIT/SonoffLAN#969]
I have 5 sonoff devices. These are always available online but only show up in the local mode after they are triggered once.

<img width="385" alt="Screenshot 2022-08-30 at 2 44 31 PM" src="https://user-images.githubusercontent.com/4697107/187399007-1061e3f5-9a87-4870-8b77-029bd55fa1e4.png">

I triggered the 1 unavailable device and now it becomes available locally also.

<img width="385" alt="Screenshot 2022-08-30 at 2 47 45 PM" src="https://user-images.githubusercontent.com/4697107/187399810-9fda533d-c3f3-47a7-bf5f-e7fef05f6a43.png">

Is this expected behaviour? Or should these devices get auto discovered without being triggered. Every time HA is restarted, this local devices becomes `0 / 0`. They start appearing as they get triggered.

**Comment by AlexxIT** [comment]
What model of devices do you have? There is bug with Micro and maybe with some other models. Will fix it

**Comment by ashwinikalantri** [comment]
Basic R2, iFan04, T1 2C
