### ISSUE TITLE
can't setup RFBridge

### ISSUE THREAD

**Issue by Marmoulak** [AlexxIT/SonoffLAN#973]
Hi, 
Thanks for your usefull integration. Would you please look at this?
info:
 Home Assistant 2022.9.2 Supervisor 2022.08.6 Operating System 8.5 Frontend 20220907.0 - latest 

log:
```
This error originated from a custom integration.

Logger: custom_components.sonoff.remote
Source: custom_components/sonoff/remote.py:86
Integration: Sonoff (documentation, issues)

None | can't setup RFBridge
Traceback (most recent call last):
  File "/config/custom_components/sonoff/remote.py", line 86, in __init__
    childs = rfbridge_childs(device["tags"]["zyx_info"], config)
KeyError: 'zyx_info'
```
best regard

**Comment by AlexxIT** [comment]
Are there devices attached to your Bridge?

**Comment by Marmoulak** [comment]
Hi
Yes. 16 devices.

**Comment by AlexxIT** [comment]
Show device diagnostics.

**Comment by Marmoulak** [comment]
[new 17.txt](https://github.com/AlexxIT/SonoffLAN/files/9641547/new.17.txt)

**Comment by AlexxIT** [comment]
Well. You have 4 RFBridges and only one has attached devices. It works fine.

**Comment by Marmoulak** [comment]
You are right. I have removed from ewelink and error is gone. I am just thinking I have other devices that are offline and there is no problem with them!
Thanks for good support

**Comment by AlexxIT** [comment]
This error is just notification. I should rename it to warning
