### ISSUE TITLE
POW Elite (POWR320D) not showing latest sensor data until eWeLink app is opened

### ISSUE THREAD

**Issue by Brix1330** [AlexxIT/SonoffLAN#976]
The power monitoring is delayed until I open the eWeLink app then it's updating more frequently but still not as fast as the app. 
That issue causes the power consumption meter (using reinmann helper) to be inaccurate, automations are delayed. Energy sensor is also showing unkown.

I'm running on auto mode.

Diagnostics below (I had to censor some digits for privacy):

```
{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.9.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Jakarta",
    "os_name": "Linux",
    "os_version": "5.10.0-17-amd64",
    "supervisor": "2022.08.6",
    "host_os": "Debian GNU/Linux 11 (bullseye)",
    "docker_version": "20.10.17",
    "chassis": "laptop",
    "run_as_root": true
  },
  "custom_components": {
    "sleep_as_android": {
      "version": "1.9.2",
      "requirements": [
        "pyhaversion"
      ]
    },
    "adaptive_lighting": {
      "version": "1.1.0",
      "requirements": []
    },
    "localtuya": {
      "version": "4.1.0",
      "requirements": []
    },
    "frigate": {
      "version": "2.3",
      "requirements": []
    },
    "hacs": {
      "version": "1.27.1",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "sonoff": {
      "version": "3.2.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.2.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "38856d1",
    "cloud_auth": true,
    "config": null,
    "options": {},
    "errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017xxxxx', 'apikey': '58b1eccd-8e49-4ecd-9fc4-xxxxxxxxxxx', 'sequence': '1663284040000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017xxxxx', 'apikey': '58b1eccd-8e49-4ecd-9fc4-xxxxxxxxxxx', 'sequence': '1663287641000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017xxxxx', 'apikey': '58b1eccd-8e49-4ecd-9fc4-xxxxxxxxxxx', 'sequence': '1663291241000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017xxxxx', 'apikey': '58b1eccd-8e49-4ecd-9fc4-xxxxxxxxxxx', 'sequence': '1663294841000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '10017xxxxx', 'apikey': '58b1eccd-8e49-4ecd-9fc4-xxxxxxxxxxx', 'sequence': '1663298441000'}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          286
        ],
        "timestamp": 1663298446.9745147,
        "exception": "",
        "count": 15,
        "first_occurred": 1663248043.7375088
      },
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud WS Connection error: Cannot connect to host as-pconnect4.coolkit.cc:8080 ssl:default [Try again]",
          "Cloud WS Connection error: Cannot connect to host as-pconnect1.coolkit.cc:8080 ssl:default [Try again]",
          "Cloud WS Connection error: Cannot connect to host as-dispa.coolkit.cc:443 ssl:default [Try again]"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          268
        ],
        "timestamp": 1663299891.9432628,
        "exception": "",
        "count": 4,
        "first_occurred": 1663239209.2964256
      }
    ],
    "device": {
      "uiid": 190,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "ssid": "***",
        "bssid": "***",
        "fwVersion": "1.0.6",
        "switches": [
          {
            "switch": "on",
            "outlet": 0
          }
        ],
        "configure": [
          {
            "startup": "stay",
            "outlet": 0
          }
        ],
        "pulses": [
          {
            "pulse": "off",
            "switch": "off",
            "outlet": 0,
            "width": 500
          }
        ],
        "rssi": -60,
        "threshold": {
          "actPow": {
            "min": 10,
            "max": 500000
          },
          "voltage": {
            "min": 18500,
            "max": 26400
          },
          "current": {
            "min": 10,
            "max": 2000
          }
        },
        "current": 421,
        "voltage": 23200,
        "power": 88382,
        "dayKwh": 281,
        "monthKwh": 281,
        "uiActive": 60,
        "timeZone": 7,
        "sledOnline": "on",
        "only_device": {
          "ota": "success",
          "ota_fail_reason": 0
        },
        "getHoursKwh": {
          "start": 4464,
          "end": 4535
        }
      },
      "model": "POWR320D",
      "online": true,
      "localtype": "plug",
      "deviceid": "10017xxxxx"
    }
  }
}
```

**Comment by VimalO** [comment]
I am also experiencing similar issues with POW & POWR2.
These were also inaccessible on HA when ewelink service went down over the past few days

**Comment by riddle-stc** [comment]
I have also this behaviour since (as far as I know) 16th of September.

**Comment by ocigam69** [comment]
Same issue:

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.9.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Madrid",
    "os_name": "Linux",
    "os_version": "5.15.67",
    "supervisor": "2022.09.1",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "climate_ip": {
      "version": "3.5.2",
      "requirements": [
        "requests>=2.21.0",
        "xmljson>=0.2.0"
      ]
    },
    "hacs": {
      "version": "1.27.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "formulaone_api": {
      "version": "0.1.5",
      "requirements": [
        "requests >=2.20"
      ]
    },
    "edge_tts": {
      "version": "0.0.1",
      "requirements": [
        "edge-tts==5.0.1"
      ]
    },
    "sonoff": {
      "version": "3.2.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "alexa_media": {
      "version": "4.1.2",
      "requirements": [
        "alexapy==1.26.3",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "alarmo": {
      "version": "v1.9.5",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "https://github.com/AlexxIT/SonoffLAN/issues",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.2.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "38856d1",
    "cloud_auth": true,
    "config": null,
    "options": {
      "mode": "auto",
      "debug": false,
      "homes": 1
    },
    "errors": [
      {
        "name": "custom_components.sonoff.core.ewelink.local",
        "message": [
          "100173850d => Local4 | {'switches': [{'outlet': 0, 'switch': 'on'}]} <= {'sequence': '1664015653000', 'seq': 5, 'error': 400, 'encrypt': True}",
          "100173850d => Local4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} <= {'sequence': '1664015656000', 'seq': 8, 'error': 400, 'encrypt': True}",
          "100173850d => Local4 | {'switches': [{'outlet': 0, 'switch': 'on'}]} <= {'sequence': '1664015657000', 'seq': 10, 'error': 400, 'encrypt': True}",
          "100173850d => Local4 | {'switches': [{'outlet': 0, 'switch': 'off'}]} <= {'sequence': '1664015663000', 'seq': 14, 'error': 400, 'encrypt': True}",
          "100173850d => Local4 | {'switches': [{'outlet': 0, 'switch': 'on'}]} <= {'sequence': '1664015992000', 'seq': 19, 'error': 400, 'encrypt': True}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/local.py",
          255
        ],
        "timestamp": 1664015992.4754107,
        "exception": "",
        "count": 10,
        "first_occurred": 1664014624.4797814
      },
      {
        "name": "custom_components.sonoff.core.ewelink.cloud",
        "message": [
          "Cloud ERROR: {'error': 400, 'deviceid': 'ab300001fe', 'apikey': 'acb441d7-1b57-48d8-8fd5-xxxxx', 'sequence': '1664014875000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '100173850d', 'apikey': 'acb441d7-1b57-48d8-8fd5-xxxxx', 'sequence': '1664018204000'}",
          "Cloud ERROR: {'error': 400, 'deviceid': 'ab300001fe', 'apikey': 'acb441d7-1b57-48d8-8fd5-xxxxx', 'sequence': '1664018475000'}",
          "Cloud ERROR: {'error': 504, 'reason': 'Request Timeout', 'deviceid': '100173850d', 'apikey': 'acb441d7-1b57-48d8-8fd5-xxxxx', 'sequence': '1664021804000'}",
          "Cloud ERROR: {'error': 400, 'deviceid': 'ab300001fe', 'apikey': 'acb441d7-1b57-48d8-8fd5-xxxxx', 'sequence': '1664022075001'}"
        ],
        "level": "WARNING",
        "source": [
          "custom_components/sonoff/core/ewelink/cloud.py",
          286
        ],
        "timestamp": 1664022076.1155539,
        "exception": "",
        "count": 8,
        "first_occurred": 1664014609.6192422
      }
    ],
    "device": {
      "uiid": 190,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "ssid": "***",
        "bssid": "***",
        "fwVersion": "1.0.6",
        "switches": [
          {
            "outlet": 0,
            "switch": "off"
          }
        ],
        "configure": [
          {
            "startup": "stay",
            "outlet": 0
          }
        ],
        "pulses": [
          {
            "pulse": "off",
            "switch": "off",
            "outlet": 0,
            "width": 500
          }
        ],
        "rssi": -56,
        "threshold": {
          "actPow": {
            "min": 10,
            "max": 500000
          },
          "voltage": {
            "min": 18500,
            "max": 26400
          },
          "current": {
            "min": 10,
            "max": 2000
          }
        },
        "current": 0,
        "voltage": 0,
        "power": 0,
        "dayKwh": 0,
        "monthKwh": 2,
        "uiActive": 60,
        "timeZone": 2,
        "getHoursKwh": {
          "start": 3720,
          "end": 4463
        },
        "sledOnline": "on",
        "only_device": {
          "ota": "success",
          "ota_fail_reason": 0
        },
        "operSide": 1
      },
      "model": "POWR320D",
      "online": true,
      "localtype": "plug",
      "deviceid": "100173850d"
    }
  }
}

**Comment by AlexxIT** [comment]
@Brix1330 you have problems with Internet. Cloud command used to force pow sensor updates. This is what ewelink app do when you open it. You can try to setup manual updates as described in readme

**Comment by ocigam69** [comment]
Hi, another problem. Entity energy is unknow.

![Screenshot_20220927-214115~2](https://user-images.githubusercontent.com/86184704/192620477-d99e171c-24d3-42a3-a0b3-a515ebf69841.png)

**Comment by amanbindalgit** [comment]
I have the same issue, Sonoff Local is showing Unknown Energy in Home Assistant when using Sonoff Local. Please share if anyone has any clue on how to fix this.

**Comment by Reibeiro2017** [comment]
![image](https://user-images.githubusercontent.com/109174594/223840048-3eb4825f-51dd-435b-b7e8-5e7719420307.png)
Eu tenho o mesmo problema, alguém conseguiu arrumar ?

**Comment by lbouriez** [comment]
I'm experiencing the same issue. Can anyone confirm whether it's possible to use the energy sensor in the energy dashboard?

**Comment by Reibeiro2017** [comment]
I did a search and after updating dp firmware 1.0.7 it stopped showing the values ​​in Energy

**Comment by lbouriez** [comment]
Ho ok, my bad luck ! I just received it with this firmware.
Any idea how to get an energy sensor for the energy dashboard using the other value ?

**Comment by AlexxIT** [comment]
Should be fixed in latest master version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.5.1

**Comment by Reibeiro2017** [comment]
sonoff POWR320D came back with a problem with the power button being turned off and it does not show the values and it fails, try again... is the same problem happening to you?

**Comment by Brix1330** [comment]
> sonoff POWR320D came back with a problem with the power button being turned off and it does not show the values and it fails, try again... is the same problem happening to you?

Yeah. If the switch is off it's detected as offline/unavailable, I have to manually turn it back on via eWeLink.

**Comment by Reibeiro2017** [comment]
So, not even activating it manually, it works again, it stays connected, only the blue and red lights are off and the internet is connected and the display with all the numbers, the on and off button only works to activate Wi-Fi[https://i.imgur.com/K2hJgI7.jpg](url) on/off button not working

**Comment by Reibeiro2017** [comment]
POW Elite (POWR320D) has stopped working?

**Comment by Brix1330** [comment]
I was having the similar problem as [yours](https://github.com/AlexxIT/SonoffLAN/issues/976#issuecomment-1540004288).
Started off like that last month, and then after a day or two, it became completely not responding. Even after turning the main breaker on/off still nothing... no led or showing anything on the display.

I have contacted Sonoff customer service and they said it could be hardware issue. My Sonoff is about a year old.

**Comment by Reibeiro2017** [comment]
so mine is working on ewelink it just doesn't work on Home assistant

**Comment by Reibeiro2017** [comment]
It worked normally again after the update, woohoo!
