### ISSUE TITLE
How to change control type for channels 2,3 and 4 on 4CHPROR3

### ISSUE THREAD

**Issue by DennyBevilaqua** [AlexxIT/SonoffLAN#977]
How can I change the control type for the channels 2-4 on a 4CHPROR3?
Channel 1 is a regular switch, but the others not. I want to have all channels like a regular switch (channel 1 - "Led Lateral").

"All channels" switch ("Iluminação da Sala1") is disabled in eWelink App.

![image](https://user-images.githubusercontent.com/6453346/190593171-4220448f-49d1-4ce0-b8c5-ed9ec1ce552d.png)

[sonoff-5bea912095e51c8c1bc44997d84de4ae-Iluminação da Sala-d119dd424d22b211510fa858cdfea863.json (2).txt](https://github.com/AlexxIT/SonoffLAN/files/9582177/sonoff-5bea912095e51c8c1bc44997d84de4ae-Iluminacao.da.Sala-d119dd424d22b211510fa858cdfea863.json.2.txt)

[debug.txt](https://github.com/AlexxIT/SonoffLAN/files/9582198/debug.txt)

**Comment by AlexxIT** [comment]
You need to reset your switch and add again to ewelink app.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
