### ISSUE TITLE
Switches not responding 

### ISSUE THREAD

**Issue by drk-geek** [AlexxIT/SonoffLAN#98]
everything was fine but one day switches become non responsive and found following 2 errors in log

Log Details (ERROR)
Logger: custom_components.sonoff
Source: custom_components/sonoff/__init__.py:154
Integration: Sonoff (documentation)
First occurred: 2:01:20 PM (1 occurrences)
Last logged: 2:01:20 PM

Device 1000123456 not found

Log Details (WARNING)
Logger: custom_components.sonoff
Source: custom_components/sonoff/__init__.py:378
Integration: Sonoff (documentation)
First occurred: 12:00:48 PM (13 occurrences)
Last logged: 2:00:08 PM

Can't send switches to 10005e888b

Home Assistant 0.109.6 installed on ven on RPI 3 Model B
Sonoff LAN  Installed: v1.10.4

**Comment by AlexxIT** [comment]
Try new version #99

**Comment by AlexxIT** [comment]
Version 2 should handle all the problems.
