### ISSUE TITLE
Issue with TX switch with multiple Gangs

### ISSUE THREAD

**Issue by msavazzi** [AlexxIT/SonoffLAN#980]
I have several sonoff switch with 3 gang each.
The issue I have is that the friendly name of the entity derived from either the sonoff original component or the sonoff lan component is not with the gang definition:

Entity ID	Name
switch.sonoff_1000fxxxxx_1	0.08
switch.sonoff_1000fxxxxx_2	0.08
switch.sonoff_1000fxxxxx_3	0.08

I need

Entity ID	Name
switch.sonoff_1000fxxxxx_1	0.08_1
switch.sonoff_1000fxxxxx_2	0.08_2
switch.sonoff_1000fxxxxx_3	0.08_3

Am I doing something wrong?

**Comment by msavazzi** [comment]
Here is the solution... but I cannot contribute it via Git, I get an error:
in entity.py

       if self.uid:
            self._attr_unique_id = f"{device['deviceid']}_{self.uid}"

            if not self.uid.isdigit():
                self._attr_entity_category = ENTITY_CATEGORIES.get(self.uid)
                self._attr_icon = ICONS.get(self.uid)

                s = NAMES.get(self.uid) or self.uid.title().replace("_", " ")
                self._attr_name = f"{device['name']} {s}"
            else:
                **self._attr_name = f"{device['name']}_{self.uid}"**

        else:
            self._attr_name = device["name"]
            self._attr_unique_id = device["deviceid"]

**Comment by AlexxIT** [comment]
You can set name for each channel in the ewelink app. It's better solution.
But I will add your solution without underscore. Thanks.
Also you can change name for any Hass entity at any time.

**Comment by msavazzi** [comment]
Thank you for adding the code. Ok with the non _ I will check that my automations does not get screwed up

For the name: yes :) but when you have 50 3Gang devices is really a headache :) so having it in the integration is far better!

**Comment by AlexxIT** [comment]
The name of the entity is usually not involved in automations. Only `entity_id`.

**Comment by msavazzi** [comment]
Correct but when you use the UI to create is uses the name, and is far easier :)

![image](https://user-images.githubusercontent.com/2660032/192096131-50d97be7-4435-416a-b85a-a6712f61965b.png)


:)

**Comment by AlexxIT** [comment]
Oh, I'm sorry. I've checked different situations. And these changes create more problems than they do benefits.

Problems has single channel devices with multichannel firmware, like Micro and many others. They get an unnecessary 1 to the name.

Also problems has multichannel devices, converted to single channel devices. They get an unnecessary numbers to the name.

**Comment by msavazzi** [comment]
Weird I have several mini, micro, R2 and TX an none of them got an issue

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlexxIT** [comment]
Micro should have 1 suffix with your fix

**Comment by msavazzi** [comment]
here is the outcome, all perfect on my side

![image](https://user-images.githubusercontent.com/2660032/192142317-f3040349-243b-4c24-a3f3-b91539620486.png)

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2660032/192142334-929e59bf-9f75-493d-a840-f4b4f977c0b5.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/2660032/192142350-5d23217d-0224-44aa-a7c8-e042f850c188.png">

<img width="630" alt="image" src="https://user-images.githubusercontent.com/2660032/192142372-7dfb77f0-6240-422d-989d-8a8d796fea41.png">

<img width="160" alt="image" src="https://user-images.githubusercontent.com/2660032/192142394-0cef2f43-71da-4125-94e3-368e55263f8e.png">

<img width="146" alt="image" src="https://user-images.githubusercontent.com/2660032/192142399-f1a83717-96a0-4f6e-bdef-40371dea9de0.png">

<img width="137" alt="image" src="https://user-images.githubusercontent.com/2660032/192142422-2088a39e-9741-4108-86ba-c377039ee9f8.png">

<img width="136" alt="image" src="https://user-images.githubusercontent.com/2660032/192142426-b331598d-48eb-4f4a-b745-1026c12afb0a.png">

<img width="124" alt="image" src="https://user-images.githubusercontent.com/2660032/192142432-075cc1ce-b125-4a2e-8bfc-48efb94c9b03.png">

<img width="136" alt="image" src="https://user-images.githubusercontent.com/2660032/192142448-45c5a7ae-b73f-4a26-8735-ec31a40ff94c.png">

<img width="117" alt="image" src="https://user-images.githubusercontent.com/2660032/192142439-de88b2a9-bad5-4c06-bd62-37468edfd560.png">

<img width="131" alt="image" src="https://user-images.githubusercontent.com/2660032/192142462-1440e355-e2d0-4536-b51a-3924417d5a68.png">

<img width="177" alt="image" src="https://user-images.githubusercontent.com/2660032/192142500-701ec6ff-dcf6-409a-b830-0192ff06e477.png">

<img width="165" alt="image" src="https://user-images.githubusercontent.com/2660032/192142505-2dc2b0b8-aeeb-4f13-bbe9-82187a022f7c.png">

<img width="152" alt="image" src="https://user-images.githubusercontent.com/2660032/192142509-c7259f10-12d2-43ec-a59a-65af1655462b.png">

<img width="130" alt="image" src="https://user-images.githubusercontent.com/2660032/192142520-4cae3f69-9749-4bb3-a8be-7db01c856fb1.png">

<img width="204" alt="image" src="https://user-images.githubusercontent.com/2660032/192142525-50e6b4d6-19ec-4899-8dce-e5599324e2ea.png">

**Comment by msavazzi** [comment]
here the entity.py I used

import logging

from homeassistant.helpers.device_registry import CONNECTION_NETWORK_MAC
from homeassistant.helpers.entity import DeviceInfo, Entity, EntityCategory

from .const import DOMAIN
from .ewelink import XRegistry, XDevice

_LOGGER = logging.getLogger(__name__)

ENTITY_CATEGORIES = {
    "battery": EntityCategory.DIAGNOSTIC,
    "battery_voltage": EntityCategory.DIAGNOSTIC,
    "led": EntityCategory.CONFIG,
    "rssi": EntityCategory.DIAGNOSTIC,
    "pulse": EntityCategory.CONFIG,
    "pulseWidth": EntityCategory.CONFIG,
}

ICONS = {
    "dusty": "mdi:cloud",
    "led": "mdi:led-off",
    "noise": "mdi:bell-ring",
}

NAMES = {
    "led": "LED",
    "rssi": "RSSI",
    "pulse": "INCHING",
    "pulseWidth": "INCHING Duration",
}


class XEntity(Entity):
    params: set = {}
    param: str = None
    uid: str = None

    # fix Hass v2021.12 empty attribute bug
    _attr_is_on = None
    _attr_should_poll = False

    def __init__(self, ewelink: XRegistry, device: XDevice) -> None:
        self.ewelink = ewelink
        self.device = device

        if self.param and self.uid is None:
            self.uid = self.param
        if self.param and not self.params:
            self.params = {self.param}

        if self.uid:
            self._attr_unique_id = f"{device['deviceid']}_{self.uid}"

            if not self.uid.isdigit():
                self._attr_entity_category = ENTITY_CATEGORIES.get(self.uid)
                self._attr_icon = ICONS.get(self.uid)

                s = NAMES.get(self.uid) or self.uid.title().replace("_", " ")
                self._attr_name = f"{device['name']} {s}"
            else:
                self._attr_name = f"{device['name']}_{self.uid}"

        else:
            self._attr_name = device["name"]
            self._attr_unique_id = device["deviceid"]

        # domain will be replaced in entity_registry.async_generate_entity_id
        self.entity_id = f"{DOMAIN}.{DOMAIN}_{self._attr_unique_id}"

        deviceid: str = device['deviceid']
        params: dict = device['params']

        connections = {(CONNECTION_NETWORK_MAC, params['staMac'])} \
            if "staMac" in params else None

        self._attr_device_info = DeviceInfo(
            connections=connections,
            identifiers={(DOMAIN, deviceid)},
            manufacturer=device.get('brandName'),
            model=device.get('productModel'),
            name=device["name"],
            sw_version=params.get('fwVersion'),
        )

        try:
            self.internal_update(params)
        except Exception as e:
            _LOGGER.error(f"Can't init device: {device}", exc_info=e)
        ewelink.dispatcher_connect(deviceid, self.internal_update)

    def set_state(self, params: dict):
        pass

    def internal_available(self) -> bool:
        return (self.ewelink.cloud.online and self.device.get("online")) or \
               (self.ewelink.local.online and "host" in self.device)

    def internal_update(self, params: dict = None):
        available = self.internal_available()
        change = False

        if self._attr_available != available:
            self._attr_available = available
            change = True

        if params and params.keys() & self.params:
            self.set_state(params)
            change = True

        if change and self.hass:
            self._async_write_ha_state()

    async def async_update(self):
        await self.ewelink.send(self.device)

**Comment by AlexxIT** [comment]
You don't have Micro in your list (model column).
Problems with 77,78,81,182,190 and all multichannel devices converted to single channel
https://github.com/AlexxIT/SonoffLAN/blob/master/custom_components/sonoff/core/devices.py

**Comment by msavazzi** [comment]
ops. I thought it was the RE5V1C. I do not have the USB one but should be the same

I think the issue is here
```
SPEC_SWITCH = [XSwitch, LED, RSSI, PULSE, PULSEWIDTH]
SPEC_1CH = [Switch1, LED, RSSI]
SPEC_2CH = [Switch1, Switch2, LED, RSSI]
SPEC_3CH = [Switch1, Switch2, Switch3, LED, RSSI]
SPEC_4CH = [Switch1, Switch2, Switch3, Switch4, LED, RSSI]
```

As THis works:
```
   1: SPEC_SWITCH,
```

while here you have an issue
```
    77: SPEC_1CH,  # Sonoff Micro
    78: SPEC_1CH,  # https://github.com/AlexxIT/SonoffLAN/issues/615
    81: SPEC_1CH,
    182: [
        Switch1, LED, RSSI,
        spec(XSensor, param="current"),
        spec(XSensor, param="power"),
        spec(XSensor, param="voltage"),
    ],  # Sonoff S40
    190: [
        Switch1, LED, RSSI,
        spec(XSensor100, param="current"),
        spec(XSensor100, param="power"),
        spec(XSensor100, param="voltage"),
        spec(XEnergySensor, param="hundredDaysKwhData", uid="energy",
             get_params={"hundredDaysKwh": "get"}),
    ],  # Sonoff POWR3
```

Why you use SPEC_1CH and Switch1 instead of SPEC_SWITCH, so XSwitch ?

**Comment by AlexxIT** [comment]
Because it is single channel device with multi channel firmware. I tried to explain it to you whole day :)
It show 4 channel via API, but only first channel works.

**Comment by msavazzi** [comment]
ops sorry :) now is clear :)

can we put an **if** in the code to create an exception for those ?

something like:
```
if ((self.device.uiid == 77) or (self.device.uiid == 78) or ((self.device.uiid == 81) or (self.device.uiid == 182) or (self.device.uiid == 190)) :
      self._attr_name = f"{device['name']}"
else:          
      self._attr_name = f"{device['name']} {s}"
```
