### ISSUE TITLE
New DW2-WiFi-L variant shows as Switch not binary sensor

### ISSUE THREAD

**Issue by ebonzl** [AlexxIT/SonoffLAN#981]
I believe this is newer variant of the DW2-WiFi - I have both, but new DW2-Wi-Fi-L version always shows up in Home Assistant as a Switch device, with no option to change to Door/Window

**Comment by AlexxIT** [comment]
Show device diagnostics.

**Comment by ebonzl** [comment]
Apologies - see below

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.9.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Pacific/Auckland",
    "os_name": "Linux",
    "os_version": "5.15.67",
    "supervisor": "2022.09.1",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "holidays": {
      "version": "1.8.0",
      "requirements": [
        "python-dateutil>=2.8.2",
        "holidays>=0.14.2"
      ]
    },
    "blueiris": {
      "version": "1.0.13",
      "requirements": []
    },
    "rpi_gpio": {
      "version": "2022.7.0",
      "requirements": [
        "RPi.GPIO==0.7.1"
      ]
    },
    "icloud3": {
      "version": "2.4.6",
      "requirements": []
    },
    "blitzortung": {
      "version": "1.0.1",
      "requirements": [
        "paho-mqtt>=1.5.0"
      ]
    },
    "clientraw": {
      "version": "2.2.4",
      "requirements": []
    },
    "sonoff": {
      "version": "3.2.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "alexa_media": {
      "version": "4.1.2",
      "requirements": [
        "alexapy==1.26.3",
        "packaging>=20.3",
        "wrapt>=1.12.1"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "alarmo": {
      "version": "v1.9.5",
      "requirements": []
    },
    "esxi_stats": {
      "version": "0.6.4",
      "requirements": [
        "pyvmomi==7.0.3"
      ]
    },
    "tapo": {
      "version": "1.2.15",
      "requirements": [
        "plugp100==2.1.18"
      ]
    },
    "bodymiscale": {
      "version": "3.0.3",
      "requirements": [
        "cachetools==5.1.0"
      ]
    },
    "garbage_collection": {
      "version": "4.8.3",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "hacs": {
      "version": "1.27.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "sonoff",
    "name": "Sonoff",
    "config_flow": true,
    "documentation": "https://github.com/AlexxIT/SonoffLAN",
    "issue_tracker": "/api/sonoff/f58130db-90e2-42bd-8546-82b5d163b358",
    "codeowners": [
      "@AlexxIT"
    ],
    "dependencies": [
      "http",
      "zeroconf"
    ],
    "requirements": [
      "pycryptodome>=3.6.6"
    ],
    "version": "3.2.0",
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "version": "38856d1",
    "cloud_auth": true,
    "config": {
      "username": "***",
      "password": "***"
    },
    "options": {
      "mode": "auto",
      "debug": true
    },
    "errors": [],
    "device": {
      "uiid": 154,
      "params": {
        "bindInfos": "***",
        "version": 8,
        "init": 1,
        "fwVersion": "1000.2.1122",
        "mac": "***",
        "chipID": "2",
        "type": "2",
        "switch": "on",
        "rssi": "-71",
        "battery": "100",
        "defense": 1,
        "actionTime": 1617825402000
      },
      "model": "DW2-Wi-Fi-L",
      "online": true,
      "localtype": null,
      "deviceid": "10016c9439"
    }
  }
}

**Comment by ebonzl** [comment]
Some more information: this version seems to have additional functionality

standard DW2-WiFi: 
![image](https://user-images.githubusercontent.com/43253454/192119770-4b1b860a-cd3c-452e-80f0-a589bce9864b.png)

DW2-WiFi-L: 
![image](https://user-images.githubusercontent.com/43253454/192119794-d7a49b8c-6060-415c-be00-b87ecb348a11.png)

**Comment by AlexxIT** [comment]
This is new device. It will be supported in next release. More info here #808

**Comment by AlexxIT** [comment]
This issue should be fixed in latest integration version
