### ISSUE TITLE
Sonoff reconfiguration notification 

### ISSUE THREAD

**Issue by davel4wa** [AlexxIT/SonoffLAN#983]
Recently, each time HA is restarted a notification is present that indicates that the Sonoff integration needs to be reconfigured. Entering the eWeLink credentials elicits 'account already configured' and does not dismiss the problem. I have used multiple email addresses including bogus accounts and in each case a new .json file is created with the email address name. I have tried deleting all of the associated .json files but each time the Sonoff integration is still somehow reflecting the original email address despite changing the configuration.yaml entry or even completely removing the sonoff configuration from the configuration.yaml file. This is driving me a bit crazy although the associated sensors continue to work as designed.

**Comment by AlexxIT** [comment]
#841
