### ISSUE TITLE
Adding support for Spider Z (a clone of L1)

### ISSUE THREAD

**Issue by Opontios** [AlexxIT/SonoffLAN#985]
@AlexxIT 
Thanks for the great job done once again with the latest version!
There has been a long time since I wanted to ask to add support for a clone of the L1 rgb controller called "Spider Z" that is distributed in some countries including Russia as the original L1. It's discovered as a plain switch under the integration and you have to manually edit the devices.py file to make it be discovered as an rgb controller (by replacing the device number from 137 to 33). Not too much effort, but you have to do it after every update. So please could you include that in your next version.
![Spider Z](https://user-images.githubusercontent.com/71525089/192139417-814df843-7e46-4edd-8c80-537e2120989b.jpg)

**Comment by AlexxIT** [comment]
No problem. Will be in next release

**Comment by Opontios** [comment]
Благодарю!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.3.1
