### ISSUE TITLE
light bulb not allowing colour or brightness control

### ISSUE THREAD

**Issue by stevene1919** [AlexxIT/SonoffLAN#988]
hi, 

i had a quick look through your code and could not figure and easy way to modify it to add a device that i have which is a Cygnett Australia rebranded "Mangotek" model "RLD60". I could not find any information on this device or even the company, but it was working fine a few versions of your integration ago. From what I can tell it uses the sonoff led light device to do the colour and brightness and that something has changed that isnt picking up the id and setting it to have colour and brightness, where as a few version ago it was.

if you can help point me to roughly what code is needed and where, ill happily hack at the code to get it working. cheers
* it's working in the ewelink app and google home.

here is the out put of the debug 

      "1000e112c1": {
        "uiid": 33,
        "params": {
          "bindInfos": "***",
          "version": 7,
          "switch": "on",
          "bright": 100,
          "colorR": 255,
          "colorG": 235,
          "colorB": 220,
          "mode": 1,
          "light_type": 2,
          "fwVersion": "3.0.0",
          "rssi": -65
        },
        "model": "RLD60",
        "online": true,
        "localtype": null

**Comment by AlexxIT** [comment]
Same as #985
