### ISSUE TITLE
RF Bridge Local Not Working

### ISSUE THREAD

**Issue by fotis3d** [AlexxIT/SonoffLAN#990]
I use the RF Bridge (black one) with various devices. Mostly door sensors and buttons.
I have added buttons to the Bridge and when I press them some Home Asssistant scripts run.

I have realized that this does not work without internet.

Has anyone else dealed this issue ? The bridge is supposed to support LAN which I have enabled in the ewelink app.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/issues?q=RF+Bridge
