### ISSUE TITLE
DualR3 energy history problem

### ISSUE THREAD

**Issue by sipimokus** [AlexxIT/SonoffLAN#996]
Dear Alexx!

I found a problem in DualR3 energy history, it's need different process function than earlier in `XEnergySensor` class.

Test data:
`003400740074007400760076007500770079007000700072006900710067006600660077008200680067006900340000`

BAD: Actually results with 6 numbers process:
`[0.4, 116.04, 0.4, 118.06, 0.5, 119.09, 0.0, 112.02, 0.9, 113.07, 0.6, 102.07, 0.2, 104.07, 0.9, 52.0]`

GOOD: Fixed results with 4 numbers process:
`[0.34, 0.74, 0.74, 0.74, 0.76, 0.76, 0.75, 0.77, 0.79, 0.7, 0.7, 0.72, 0.69, 0.71, 0.67, 0.66, 0.66, 0.77, 0.82, 0.68, 0.67, 0.69, 0.34, 0.0]`

I will create PR for fix it. 

Best regards

**Comment by sipimokus** [comment]
PR: https://github.com/AlexxIT/SonoffLAN/pull/997

Now we process 4 numbers instead of 6 in DualR3.

**Hypothesis:**
The last 2 numbers are the "decimal digits", the first 2 numbers are the "integers".
I think the "integers" number is in decimal number system instead of hexadecimal number system.

I think this value will never exceed 100kWh hours.

The maximum allowed current is 10A ~ 2300W / channel. [Officially 2200W]
`max_kwh = (230V * 10A * 24H) = 55200Wh = 55.2kWh`
The maximum allowed current is 15A ~ 3500W / total. [Officially 3300W]
`max_kwh = (230V * 15A * 24H) = 82800Wh = 82.8kWh`


Sorry, but I can't test it, I can't even reach 10kWh consumption.

**Comment by AlexxIT** [comment]
Thanks! https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.4.0
