### ISSUE TITLE
Is Sonoff SwitchMan Smart Wall Switch-M5 supported?

### ISSUE THREAD

**Issue by jakobeissler** [AlexxIT/SonoffLAN#998]
Hello,

I was wondering if the new SwitchMan Smart Wall Switch-M5 series are supported by SonoffLAN? I havent found much information about it.

https://sonoff.tech/product/smart-wall-swtich/m5/

Thanks!!

**Comment by AlexxIT** [comment]
Have you search "Switch-M5" in this repo?

https://github.com/AlexxIT/SonoffLAN/issues?q=Switch-M5

#659

**Comment by jakobeissler** [comment]
Sorry about that. Yes i did, but as i dont see the m5 listed on the github page, it was unclear to me if it is supported.

Can it be controlled in local mode?

**Comment by AlexxIT** [comment]
The home page can't keep up with all the updates. But in any case it is better to use the search before a new question.

According to the user logs - the device can work locally.

**Comment by jakobeissler** [comment]
I understand. Thank you.

**Comment by RedyAu** [comment]
Sorry for necroposting, but this seems like the most relevant place to ask this:

I've set up my SwitchMan M5 over Matter. Is that scenario supported?
Can I link an R5 to it like this?

**Comment by AlexxIT** [comment]
This integration about built-in ewelink protocol. Not related to Matter protocol.
